[package]
name = "ost-thesis"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["David Bachmann", "Dominik Buehler", "Thomas Bocek"]
license = "MIT"
description = "A thesis template in the visual style of the OST, Eastern Switzerland University of Applied Sciences."
keywords = ["thesis", "academic", "report", "university", "ost"]
categories = ["paper"]
disciplines = ["computer-science", "engineering"]
exclude = [".github"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
