[package]
name = "kinetic-kit"
version = "0.1.0"
entrypoint = "lib.typ"

authors = ["Nick Le Large <@ll-nick>"]
license = "MIT-0"
description = "Doctoral, Bachelor's and Master's theses at the Karlsruhe Institute of Technology."

repository = "https://github.com/ll-nick/kinetic-kit"
keywords = [
  "dissertation",
  "doctoral",
  "thesis",
  "karlsruhe",
  "kit",
  "karlsruhe institute of technology",
  "ksp",
]
categories = ["thesis"]
disciplines = ["engineering", "computer-science"]
compiler = "0.15.0"
exclude = ["/docs/"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail/thumbnail.png"
