#import "@preview/aio-studi-and-thesis:0.1.2": *

#let bib-file = "literature-and-bibliography.bib" // File generated by Zotero - Export Format: BibTeX
#let bib = load-bibliography(read(bib-file))

#let additional-styling(body) = {

  // General table formatting
  show table.cell.where(y: 0): set text(fill: dark-blue, weight: "bold")
  show table.cell.where(x: 0): set par(justify: false)
  //#show table.cell.where(x: 0): set text(hyphenate: true)

  let frame(stroke) = (x, y) => (
    left: stroke,
    right: stroke,
    top: if y < 2 { stroke } else { 0pt },
    bottom: stroke,
  )

  set table(
    fill: (_, y) => if calc.odd(y) { light-blue },
    stroke: frame(dark-grey),
  )

  // Body
  body
}