// Generated by wasm_minimal_protocol for Nim
#let __nim_posOnlyChk(x) = {let named = x.named();
assert(named.len() == 0, message: "only pos-args allowed but got kw-args: " + repr(named)); x.pos()}
#let __nim_plugin = plugin("./lib.wasm")
#let __nim_plugin = plugin.transition(__nim_plugin.wasm_minimal_protocol_NimMain)
#let sprintf(format,..args,) =  cbor(__nim_plugin.sprintf(cbor.encode(format),cbor.encode(__nim_posOnlyChk(args)),))
#let sprintf-map(format,arg,) =  cbor(__nim_plugin.sprintf-map(cbor.encode(format),cbor.encode(arg),))
