[package]
name = "lovelace"
version = "0.3.1"
entrypoint = "lib.typ"
authors = ["Andreas Kröpelin", "Lovelace contributors"]
license = "MIT"
description = "Algorithms in pseudocode, unopinionated and flexible."
homepage = "https://a5s.eu/toot-lovelace"
repository = "https://github.com/andreasKroepelin/lovelace"
exclude = []
keywords = [
  "algorithm", "pseudocode", "pseudo", "pseudo code", "code", "algorithmic",
  "algorithmicx", "alg", "program", "algorithms"
]
categories = ["components"]
disciplines = ["computer-science", "mathematics"]
compiler = "0.13.0"
