# HWR Berlin — English Localization
## All keys must be identical to those in de.ftl.

## Index headings

toc-title = Table of Contents
abbreviations-title = List of Abbreviations
figures-title = List of Figures
tables-title = List of Tables
appendix-toc-title = List of Appendices
appendix-section-title = Appendix
glossary-title = Glossary
bibliography-title = References

## Appendix section label

appendix-label = Appendix

## Prefixes for figure/table indices

figure-prefix = Fig.
table-prefix = Tab.

## Column headers in figure/table indices

index-col-title = Title
index-col-page = Page
index-col-number = No.

## Abstract

abstract-title = Abstract

## AI Tools Register

ai-tools-title = AI Tools Register
ai-col-tool = AI Tool
ai-col-usage = Usage
ai-col-chapters = Affected Parts
ai-col-remarks = Remarks

## Confidentiality Notice

confidential-title = C O N F I D E N T I A L I T Y   N O T I C E

confidential-intro-chapters =
    The following chapter(s)/section(s) are subject to a confidentiality notice
    due to the use of confidential data and may only be accessed by the
    responsible academic supervisor and the examining supervisor/reviewer:

confidential-short-version =
    An abridged version of the work, containing only the unrestricted chapters
    and sub-chapters, is provided on the enclosed data carrier under the
    name { $filename }.

confidential-text-all =
    All chapters of this work are subject to a confidentiality notice due to
    the use of confidential data and may only be accessed by the responsible
    academic supervisor and the examining supervisor/reviewer.

## Declaration of Authorship

declaration-title = Declaration of Authorship

## Pretty Mode

pretty-warning =
    Note: The selected styling option (Pretty Mode) is not specified in the
    HWR formatting guidelines. Please confirm with your supervising examiner
    whether this styling is acceptable.

## Draft Mode

draft-watermark = DRAFT

## Source Attribution

source-own = Source: Own illustration
declaration-date-label = {""}
declaration-place-date = Place, Date
declaration-signature = Signature

group-signature-note =
    Note: This work has multiple authors. Only one signature field has been included
    (group-signature: false). Please confirm with your supervising examiner whether
    a single representative signature on behalf of the group is acceptable.

# Mandatory text — equivalent of HWR §3.11 (January 2025 guidelines)
# Pluralization: [one] = single author, *[other] = group
declaration-text =
    { $author-count ->
        [one] I hereby declare:

            that I have prepared this work independently in all parts, using no
            sources or aids other than those specified in the work, and that the
            work has not previously been submitted in the same or similar form for
            any other examination. All verbatim or paraphrased quotations and
            citations, as well as all sections that were drafted, written and/or
            edited with the aid of AI-based tools, are identified and documented.
            In the appendix of my work I have listed all AI-based tools used.
            These are recorded with product names and the prompts entered in an
            AI tools register.

            I am aware that using texts or other content and products generated
            by AI-based tools does not guarantee their quality. I take full
            responsibility for the adoption of any machine-generated passages I
            have used and bear responsibility for any errors or distortions
            generated by the AI, incorrect references, violations of data
            protection or copyright law, or plagiarism.
       *[other] We hereby declare:

            that we have prepared this work independently in all parts, using no
            sources or aids other than those specified in the work, and that the
            work has not previously been submitted in the same or similar form for
            any other examination. All verbatim or paraphrased quotations and
            citations, as well as all sections that were drafted, written and/or
            edited with the aid of AI-based tools, are identified and documented.
            In the appendix of our work we have listed all AI-based tools used.
            These are recorded with product names and the prompts entered in an
            AI tools register.

            We are aware that using texts or other content and products generated
            by AI-based tools does not guarantee their quality. We take full
            responsibility for the adoption of any machine-generated passages we
            have used and bear responsibility for any errors or distortions
            generated by the AI, incorrect references, violations of data
            protection or copyright law, or plagiarism.
    }
