[package]
name = "nexus-tools"
version = "0.3.0"
description = "Faster and easier development using commonly used features"
authors = ["Maycon F. Melo <@mayconfmelo>"]
license = "MIT-0"
repository = "https://github.com/mayconfmelo/nexus-tools"
entrypoint = "src/lib.typ"
categories = ["scripting", "utility", "components"]
keywords = [
  "development", "dev", "storage", "database", "components", "callout", "null",
  "testing", "defaults", "content2str", "date"
]
exclude = [
  "dev/", "tests/", "docs/", "scripts/", "plugin/", ".git", ".github", ".gitignore",
  "justfile", "manual.typ"
]