#let luzid(
  color-map: none,
  marker-map: none,
  style-map: none,
  body,
) = {
  import "@preview/valkyrie:0.2.2" as z
  import "@preview/catppuccin:1.0.1": flavors

  // map the different colors to the types
  color-map = z.parse(color-map, z.dictionary((
    task: z.color(default: flavors.latte.colors.subtext0.rgb),
    done: z.color(default: flavors.latte.colors.green.rgb),
    rescheduled: z.color(default: flavors.latte.colors.sapphire.rgb),
    scheduled: z.color(default: flavors.latte.colors.teal.rgb),
    important: z.color(default: flavors.latte.colors.yellow.rgb),
    cancelled: z.color(default: flavors.latte.colors.red.rgb),
    cancelled-stroke: z.color(default: flavors.latte.colors.subtext0.rgb),
    progress: z.color(default: flavors.latte.colors.green.rgb),
    question: z.color(default: flavors.latte.colors.peach.rgb),
    star: z.color(default: flavors.latte.colors.yellow.rgb),
    note: z.color(default: flavors.latte.colors.maroon.rgb),
    location: z.color(default: flavors.latte.colors.mauve.rgb),
    information: z.color(default: flavors.latte.colors.blue.rgb),
    idea: z.color(default: flavors.latte.colors.yellow.rgb),
    amount: z.color(default: flavors.latte.colors.green.rgb),
    pro: z.color(default: flavors.latte.colors.green.rgb),
    contra: z.color(default: flavors.latte.colors.red.rgb),
    bookmark: z.color(default: flavors.latte.colors.red.rgb),
    quote: z.color(default: flavors.latte.colors.subtext0.rgb),
    up: z.color(default: flavors.latte.colors.green.rgb),
    down: z.color(default: flavors.latte.colors.red.rgb),
    win: z.color(default: flavors.latte.colors.mauve.rgb),
    key: z.color(default: flavors.latte.colors.yellow.rgb),
    fire: z.color(default: flavors.latte.colors.red.rgb),
  )))

  // map the chars to the types
  let char-names-map = (
    " ": "task",
    "x": "done",
    ">": "rescheduled",
    "<": "scheduled",
    "!": "important",
    "-": "cancelled",
    "/": "progress",
    "?": "question",
    "*": "star",
    "n": "note",
    "l": "location",
    "i": "information",
    "I": "idea",
    "S": "amount",
    "p": "pro",
    "c": "contra",
    "b": "bookmark",
    "\"": "quote",
    "”": "quote",
    "u": "up",
    "d": "down",
    "w": "win",
    "k": "key",
    "f": "fire",
  )

  // map the icon-paths to the types
  marker-map = z.parse(marker-map, z.dictionary(
    (
      task: z.string(default: "icons/square.svg"),
      done: z.string(default: "icons/square-check-big.svg"),
      rescheduled: z.string(default: "icons/forward.svg"),
      scheduled: z.string(default: "icons/calendar.svg"),
      important: z.string(default: "icons/triangle-alert.svg"),
      cancelled: z.string(default: "icons/square-x.svg"),
      progress: z.string(default: "icons/ellipsis.svg"),
      question: z.string(default: "icons/circle-question-mark.svg"),
      star: z.string(default: "icons/star.svg"),
      note: z.string(default: "icons/pin.svg"),
      location: z.string(default: "icons/map-pin.svg"),
      information: z.string(default: "icons/info.svg"),
      idea: z.string(default: "icons/lightbulb.svg"),
      amount: z.string(default: "icons/dollar-sign.svg"),
      pro: z.string(default: "icons/thumbs-up.svg"),
      contra: z.string(default: "icons/thumbs-down.svg"),
      bookmark: z.string(default: "icons/bookmark.svg"),
      quote: z.string(default: "icons/quote.svg"),
      up: z.string(default: "icons/trending-up.svg"),
      down: z.string(default: "icons/trending-down.svg"),
      win: z.string(default: "icons/cake.svg"),
      key: z.string(default: "icons/key-round.svg"),
      fire: z.string(default: "icons/flame.svg"),
    ),
  ))

  // map the styles to the types
  style-map = z.parse(style-map, z.dictionary((
    task: z.function(optional: true),
    done: z.function(optional: true),
    rescheduled: z.function(optional: true),
    scheduled: z.function(optional: true),
    important: z.function(optional: true),
    cancelled: z.function(default: cc => {
      set text(fill: color-map.cancelled-stroke)
      strike(cc)
    }),
    progress: z.function(optional: true),
    question: z.function(optional: true),
    star: z.function(optional: true),
    note: z.function(optional: true),
    location: z.function(optional: true),
    information: z.function(optional: true),
    idea: z.function(optional: true),
    amount: z.function(optional: true),
    pro: z.function(optional: true),
    contra: z.function(optional: true),
    bookmark: z.function(optional: true),
    quote: z.function(optional: true),
    up: z.function(optional: true),
    down: z.function(optional: true),
    win: z.function(optional: true),
    key: z.function(optional: true),
    fire: z.function(optional: true),
  )))

  // map for the cheboxses generated by pandoc
  let pandoc-map = (
    "☐": " ",
    "☒": "x",
  )

  // get the marker; if it's a svg, replace the "currentColor" with the rgb-value of the marker
  let get-marker(type) = {
    let marker = marker-map.at(type)

    if marker.ends-with(".svg") {
      let color = color-map.at(type)
      bytes(
        read(marker-map.at(type)).replace("currentColor", color.to-hex()),
      )
    } else {
      return marker
    }
  }

  // creates the instance of the marker
  let icon(im) = {
    let type = char-names-map.at(im)

    scale(
      x: 150%,
      y: 150%,
      box(
        image(
          get-marker(type),
          height: 0.7em,
        ),
      ),
    )
  }

  // helper function from pandoc (https://github.com/jgm/pandoc/blob/fe62b25f4926e2d11e3c3cbfe085086766611783/data/templates/template.typst#L1-L11)
  let content-to-string(content) = {
    if content.has("text") {
      content.text
    } else if content.has("children") {
      content.children.map(content-to-string).join("")
    } else if content.has("body") {
      content-to-string(content.body)
    } else if content == [ ] {
      " "
    }
  }

  // modify lists
  show list: it => {
    let is-checklist = false
    let default-marker = if type(it.marker) == array { it.marker.at(0) } else { it.marker }
    let symbols-list = ()
    let body-list = ()

    // go through all children
    for ch in it.children {
      let is-box = false
      let box-type = none
      let item-text = none

      // pandoc-checkbox
      if (
        type(ch.body) == content and ch.body.func() == text
      ) {
        // with content
        if (
          ch.body.text.len() >= 5 // 3 for symbol, 1 space, 1+ content
            and ch.body.text.at(3) == " "
            and pandoc-map.keys().contains(ch.body.text.at(0))
        ) {
          is-box = true
          box-type = pandoc-map.at(ch.body.text.at(0))
          item-text = ch.body.text.slice(4)
          // empty checkbox
        } else if (
          ch.body.text.len() >= 3 and pandoc-map.keys().contains(ch.body.text.at(0))
        ) {
          is-box = true
          box-type = pandoc-map.at(ch.body.text.at(0))
          item-text = []
        }
      }

      // content and sequence
      if type(ch.body) == content and ch.body.func() == [].func() {
        if ch.body.children.at(0).text.len() != 3 {
          let elem = ch.body.children.at(0).text


          // pandoc-box
          if (
            elem.len() >= 4 and elem.at(3) == " " and pandoc-map.keys().contains(elem.at(0))
          ) {
            is-box = true
            box-type = pandoc-map.at(elem.at(0))
            item-text = (ch.body.children.at(0).text.slice(4), ..ch.body.children.slice(1)).join()

            // typst-box
          } else if (
            ch.body.children.len() >= 5
              and ch.body.children.at(0) == [\[]
              and char-names-map.keys().contains(content-to-string(ch.body.children.at(1)))
              and ch.body.children.at(2) == [\]]
              and ch.body.children.at(3) == [ ]
          ) {
            is-box = true
            box-type = content-to-string(ch.body.children.at(1))
            item-text = ch.body.children.slice(4).join()

            // empty typst box
          } else if (
            ch.body.children.len() >= 3
              and ch.body.children.at(0) == "["
              and char-names-map.keys().contains(content-to-string(ch.body.children.at(1)))
              and ch.body.children.at(2) == "]"
          ) {
            is-box = true
            box-type = content-to-string(ch.body.children.at(1))
            item-text = []
          }
        } else {
          if (
            ch.body.children.len() >= 3
              and ch.body.children.at(1) == [ ]
              and ch.body.children.at(0).has("text")
              and pandoc-map.keys().contains(ch.body.children.at(0).text)
          ) {
            is-box = true
            box-type = pandoc-map.at(ch.body.children.at(0).text)
            item-text = ch.body.children.slice(2).join()
          }
        }
      }

      if is-box {
        is-checklist = true

        symbols-list.push(icon(box-type))
        body-list.push(item-text)
      } else {
        symbols-list.push(default-marker)
        body-list.push(ch.body)
      }
    }

    // if it is a checklist, create a modified value
    if is-checklist {
      enum(
        numbering: (.., n) => { symbols-list.at(n - 1) },
        tight: it.tight,
        indent: it.indent,
        body-indent: it.body-indent,
        spacing: it.spacing,
        ..body-list,
      )
    } else {
      // return the unmodified original
      it
    }
  }

  body
}
