#heading(numbering: none, outlined: false)[Statement of Authorship]

#grid(rows: (2em, 1em, 1em, 1em), row-gutter: 2em,
  [Thesis Title:], 
  [Name:], 
  [Date of Birth:], 
  [Matriculation Number:],
)

#v(2em)

I herewith assure that I wrote the present thesis independently, that the thesis has not been partially or fully submitted as graded academic work and that I have used no other means than the ones indicated. I have indicated all parts of the work in which sources are used according to their wording or to their meaning.

I am aware of the fact that violations of copyright can lead to injunctive relief and claims for damages of the author as well as a penalty by the law enforcement agency.

Furthermore, I confirm that I am aware that the use of content (including but not limited to text, figures, images and code) generated by artificial intelligence (AI) in the thesis must be disclosed. In those cases I have specified the AI system used, I have marked the specific sections of the thesis where AI-generated content was used, and I have provided a brief explanation of the level of detail at which the AI system was used to generate the content. I also stated the reason for using the tools.

I assure that even if a generative AI system has been used, the scientific contribution has been made entirely by myself.

\
Magdeburg, #datetime.today().display("[month repr:long] [day], [year]")
#v(3em)

#line(stroke: 0.5pt, length: 50%)
#v(-0.5em)
~Signature