/// Generate URL strings to contents on different media platforms. These links usually have similar patterns that only differs in terms of content ID, and the functions are here to avoid repetitions and simplifying the writing of these links.
///
/// Note that the generated URLs are of type `string`, not `content`. To make the link clickable you can wrap it with a `link` element, or for more nicely-formatted display text, use functions from `linkify.display` instead.
///
/// Due to privacy reasons, platforms like Xhaohongshu are currently not supported.
/// Please beware the share links generated by these apps contain the sharer's personal info and is thus unsafe. Be cautious not to include them in publicized documents.
/// If I discover how to generate a sanitized link in the future, I might consider support those platforms.
///
///
/// 此子模块用于生成各大互联网内容平台的内容链接，由于这些链接通常有着固定的格式，只是某些参数不同，通过本模块提供的函数，可以简化这些链接的生成，减少代码重复。
///
/// 本模块生成的 URL 链接均为字符串 `str` 格式，不是富文本 `content` 格式，若直接插入文档中是不可点击的。若要生成可点击的链接，可使用一个 `link` 元素包裹 URL 字符串。你也可以考虑使用 `linkify.display` 子模块中的函数为这些链接直接生成格式化的显示文本。
///
/// 包括小红书在内的某些平台，其生成的分享链接会包含用户的个人信息，有隐私泄露的风险，故目前尚不提供这些平台内容的链接生成。同时也请注意避免在公开发布的文档中使用这些可能泄露个人信息的分享链接。若未来发现有办法对这些分享链接中的个人信息进行脱敏处理，我可以考虑加入相关的函数。

#import "@preview/based:0.2.0": base64;
#import "./bili.typ": av2bv
#import "@preview/percencode:0.1.0": url-encode

#import "./init.typ": missing

#let /*pub*/ bili(
  ..args,
  uid: missing
) = {
  if uid != missing {
    // user homepage link
    assert.eq(type(uid), int)
    "https://space.bilibili.com/" + str(uid)
  } else {
    // video link
    let pos-args = args.pos()
    assert.eq(pos-args.len(), 1)
    let (bvid,) = pos-args

    if type(bvid) == int {
      // AVID
      bvid = av2bv(bvid, prefix: true)
    } else if type(bvid) == str {
      // BVID
      if bvid.len() == 10 {
        bvid = "BV" + bvid
      }
      assert.eq(bvid.len(), 12, message: "Invalid BVID format.")
    } else {
      panic("Invalid ID type. Expects either a `str` BVID or an `int` AVID")
    }

    "https://www.bilibili.com/video/" + bvid
  }
}

#let /*pub*/ weixin(
  ..args,
  biz: missing
) = {
  if biz != missing {
    // An account
    let biz = if type(biz) == str {
      biz
    } else if type(biz) == int {
      base64.encode(str(biz))
    } else {
      panic("Invalid BIZ type. Expect an integer or a Base64 encoded string.")
    }
    "https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=" + biz
  } else {
    // An article
    let pos-args = args.pos()
    assert.eq(pos-args.len(), 1)
    let (article-id,) = pos-args
    assert.eq(type(article-id), str)
    "https://mp.weixin.qq.com/s/" + article-id
  }
}

#let /*pub*/ zhihu(
  ..args,
  q: missing,
  a: missing,
  user: missing,
) = {
  if q != missing {
    // Question
    assert.eq(type(q), int)
    let url = "https://www.zhihu.com/question/" + str(q)
    if a != missing {
      // A specific answer to the question
      assert.eq(type(a), int)
      url += "/answer/" + str(a)
    }
    url
  } else if user != missing {
    // User profile
    assert.eq(type(user), int)
    "https://www.zhihu.com/people/" + str(user)
  } else {
    // Column article
    let pos-args = args.pos()
    assert.eq(pos-args.len(), 1)
    let (article-id,) = pos-args
    assert.eq(type(article-id), str)
    "https://zhuanlan.zhihu.com/p/" + article-id
  }
}

#let /*pub*/ youtube(
  ..args,
  ch: missing
) = {
  if ch != missing {
    assert.eq(type(ch), str)
    "https://www.youtube.com/@" + ch
  } else {
    let pos-args = args.pos()
    assert.eq(pos-args.len(), 1)
    let (video-id,) = pos-args
    assert.eq(type(video-id), str)
    "https://www.youtube.com/watch?v=" + video-id
  }
}

#let isbn-src = (
  douban: id => "https://book.douban.com/isbn/" + id,
  isbndb: id => "https://isbndb.com/book/" + id,
  google: id => "https://www.google.com/search?tbs=bks:1&q=isbn:" + id,
  amazon: id => "https://www.amazon.com/s?search-alias=stripbooks&field-isbn=" + id,
)

/// book reference by ISBN
///
/// ```example
/// _The Hitchhiker's Guide to the Galaxy_: #isbn("978-0-330-25864-8")
/// ```
///
/// - id (str): 13-digit ISBN code as string. Dashes may be inserted between digits, and will be rendered as-is.
/// - src (str): source of ISBN database. Currently supported values are:
/// #table(
///   columns: 2,
///   [`src`], [],
///   [`douban`], [Douban books],
///   [`google`], [Google search],
///   [`isbndb`], [ISBNDB],
///   [`amazon`], [Amazon book search],
/// )
/// - prefix (bool): whether to prepend `"ISBN "` to the render result
/// -> str
#let /*pub*/ isbn(
  id,
  src: "douban",
) = {
  assert.eq(type(id), str)
  isbn-src.at(src)(id.replace("-", ""))
}

#let /*pub*/ wiki(title, lang: "en", section: none) = {
  // ensure a valid language code to prevent injection
  assert(lang.match(regex("^[a-z]{2}$")) != none)
  (
    "https://" + lang + ".wikipedia.org/wiki/" +
    url-encode(title) +
    if section != none {
      assert.eq(type(section), str)
      "#" + section
    }
  )
}

#let moegirl-src = (
  zh: "https://zh.moegirl.org.cn/",
  mzh: "https://mzh.moegirl.org.cn/",
  icu: "https://moegirl.icu/"
)

#let /*pub*/ moegirl(title, section: none, src: "icu") = {
  assert.eq(type(title), str)
  (
    moegirl-src.at(src) +
    url-encode(title) +
    if section != none {
      assert.eq(type(section), str)
      "#" + url-encode(section)
    }
  )
}

#let /*pub*/ twitter(
  ..args,
) = {
  let pos-args = args.pos()
  if pos-args.len() == 1 {
    let (user-id,) = pos-args
    assert.eq(type(user-id), str)
    "https://x.com/" + user-id
  } else if pos-args.len() == 2 {
    let (user-id, post-id) = pos-args
    assert.eq(type(user-id), str)
    assert.eq(type(post-id), int)
    "https://x.com/" + user-id + "/status/" + str(post-id)
  } else {
    panic("Incorrect number of positional arguments.")
  }
}

#let /*pub*/ B站 = bili
#let /*pub*/ 微信 = weixin
#let /*pub*/ 知乎 = zhihu
#let /*pub*/ 油管 = youtube
#let /*pub*/ 维基 = wiki
#let /*pub*/ 萌百 = moegirl
#let /*pub*/ 推特 = twitter
#let /*pub*/ X = twitter