[package]
name = "touying-aqua"
version = "0.7.1"
entrypoint = "lib.typ"
authors = ["OrangeX4", "zral0kh", "enklht", "Andreas Kröpelin", "ntjess", "Enivex", "Pol Dellaiera", "pride7", "Coekjan"]
license = "MIT"
description = "Aqua theme in Touying - a powerful package for creating presentation slides in Typst."
repository = "https://github.com/touying-typ/touying"
keywords = ["presentation", "pre", "slide", "slides", "lecture", "touying", "beamer", "talk"]
categories = ["presentation"]
exclude = ["examples"]
compiler = "0.12.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"