// Preview-safe Typst – no external packages
// Generated by Sang Math OMR

#set page(
  paper: "a4",
  flipped: false,
  fill: white,
  margin: (top: 5mm, bottom: 5mm, left: 6mm, right: 6mm),
)
#set text(size: 8pt, font: "Times New Roman")

#let marker = box(fill: black, width: 12pt, height: 12pt)
#let tracking-marker = box(fill: black, width: 10pt, height: 10pt)


// Optional: #state("sbd").update("1001") and #state("made").update("0101")
// before #include. Blank states leave the student bubbles unmarked.
#let omr-code(value, digits) = {
  if value == none { return "" }
  let code = str(value)
  if code.len() == 0 or code.len() > digits { panic("sang-math OMR: invalid code length") }
  for i in range(code.len()) { if not "0123456789".contains(code.at(i)) { panic("sang-math OMR: codes must contain digits only") } }
  while code.len() < digits { code = "0" + code }
  code
}
#let omr-marked(name, digits, column, row) = {
  let code = omr-code(state(name).get(), digits)
  code != "" and code.at(column) == str(row)
}

#let bubble(label, marked: false) = {
  align(center + horizon)[
    #circle(
      radius: 4.5pt,
      stroke: 0.5pt + rgb("#333333"),
      fill: if marked { black } else { white },
      align(center + horizon)[#text(size: 6.5pt, weight: "regular", fill: if marked { white } else { rgb("#888888") })[#label]],
    )
  ]
}
#let empty-box = box(stroke: 0.8pt + black, width: if false { 10pt } else { 11pt }, height: if false { 10pt } else { 11pt })
#let qb = box(width: 1.30pt, height: 1.30pt, fill: black)
#let qw = box(width: 1.30pt, height: 1.30pt, fill: white)

#place(top + left, dx: -2mm, dy: -2mm, marker)
#place(top + right, dx: 2mm, dy: -2mm, marker)

#align(top + center)[
  #scale(x: if false { 88% } else { 95% }, y: if false { 88% } else { 95% }, origin: top)[
// ── HEADER ──────────────────────────────────────────────────
#let sbd-box = block(
  inset: (left: if false { 6pt } else { 4pt }, right: if false { 3pt } else { 2pt }, top: if false { 1pt } else { 2pt }, bottom: if false { 1pt } else { 2pt }),
  [
    #place(top + left, dx: -2pt, dy: -2pt)[#tracking-marker]
    #v(if false { 2pt } else { 4pt })
    #align(center)[#text(weight: "bold", size: if false { 7pt } else { 7.5pt })[SỐ BÁO DANH #context omr-code(state("sbd").get(), 6)]]
    #v(if false { 1pt } else { 2pt })
    #grid(
      columns: (12pt,) * 6, gutter: if false { 1.2pt } else { 1.5pt },
      ..range(6).map(i => align(center, empty-box))
    )
    #v(if false { 1pt } else { 2pt })
    #grid(
      columns: (12pt,) * 6, row-gutter: if false { 0.8pt } else { 2pt }, column-gutter: 1.5pt,
      ..range(10).map(r => range(6).map(c => context bubble(str(r), marked: omr-marked("sbd", 6, c, r)))).flatten()
    )
  ],
)

#let made-box = block(
  inset: (left: if false { 3pt } else { 2pt }, right: if false { 3pt } else { 2pt }, top: if false { 1pt } else { 2pt }, bottom: if false { 1pt } else { 2pt }),
  [
    #place(top + left, dx: -2pt, dy: -2pt)[#tracking-marker]
    #v(if false { 2pt } else { 4pt })
    #align(right)[#text(weight: "bold", size: if false { 7pt } else { 7.5pt })[MÃ ĐỀ THI #context omr-code(state("made").get(), 4)]]
    #v(if false { 1pt } else { 2pt })
    #grid(
      columns: (12pt,) * 4,
      gutter: if false { 1.2pt } else { 1.5pt },
      align(center, empty-box), align(center, empty-box), align(center, empty-box), align(center, empty-box),
    )
    #v(if false { 1pt } else { 2pt })
    #grid(
      columns: (12pt,) * 4, row-gutter: if false { 0.8pt } else { 2pt }, column-gutter: 1.5pt,
      ..range(10).map(r => range(4).map(c => context bubble(str(r), marked: omr-marked("made", 4, c, r)))).flatten()
    )
  ],
)

#block(width:100%, stroke:(paint:rgb("#666666"),thickness:0.8pt,dash:"dashed"), radius:4pt, clip:true, [
  #grid(columns:(82pt, 60pt, 1fr, 56pt), gutter:0pt, stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"),
    grid.cell(stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"), sbd-box),
    grid.cell(stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"), made-box),
    grid.cell(stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"), [
      #pad(x:4pt, y:6pt)[
        #text(10pt, weight:"bold", fill:rgb("#c0392b"))[PHIẾU TRẢ LỜI TRẮC NGHIỆM]
        #v(2pt)
        #text(7pt)[SANG MATH OMR]
        #v(4pt)
        #text(7pt)[Họ và tên: .....................................................]
        #v(4pt)
        #text(7pt)[Lớp: ............ Môn: ............... Điểm: ...............]
      ]
    ]),
    grid.cell(stroke:(paint:rgb("#666666"),thickness:0.5pt,dash:"dashed"), [
      #align(center+horizon)[
        #box(width:54pt, height:54pt, stroke:.6pt, radius:2pt)[
          #align(center+horizon)[#grid(columns: 33, column-gutter: 0pt, row-gutter: 0pt,
  qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw,
  qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw,
  qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw,
  qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qb, qb, qb, qb, qb, qb, qw, qw, qb, qw, qb, qw, qw, qw, qb, qb, qw, qb, qb, qb, qb, qb, qb, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qw, qw, qw, qw, qb, qw, qb, qw, qb, qb, qw, qb, qb, qw, qb, qw, qb, qw, qw, qw, qw, qw, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qb, qb, qb, qw, qb, qw, qb, qw, qw, qb, qw, qb, qw, qb, qw, qw, qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qb, qb, qb, qw, qb, qw, qb, qb, qb, qw, qw, qw, qw, qw, qb, qw, qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qb, qb, qb, qw, qb, qw, qw, qb, qw, qb, qb, qw, qw, qb, qb, qw, qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qw, qw, qw, qw, qb, qw, qw, qb, qw, qb, qb, qw, qw, qb, qw, qw, qb, qw, qw, qw, qw, qw, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qb, qb, qb, qb, qb, qb, qw, qb, qw, qb, qw, qb, qw, qb, qw, qb, qw, qb, qb, qb, qb, qb, qb, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qb, qw, qb, qb, qw, qw, qb, qb, qb, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qw, qw, qw, qw, qb, qw, qb, qw, qb, qw, qw, qw, qw, qw, qw, qb, qb, qw, qw, qb, qb, qb, qw, qw, qw, qw, qw,
  qw, qw, qw, qw, qw, qb, qw, qb, qw, qw, qw, qw, qw, qb, qb, qb, qw, qb, qw, qw, qb, qb, qw, qw, qb, qb, qw, qw, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qw, qw, qb, qb, qw, qw, qb, qw, qw, qb, qw, qw, qb, qb, qb, qb, qw, qw, qw, qw, qw, qw, qb, qb, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qw, qw, qb, qb, qb, qw, qw, qw, qw, qw, qw, qw, qb, qb, qw, qw, qw, qw, qw, qw, qw, qb, qw, qb, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qb, qb, qw, qb, qb, qb, qw, qw, qb, qw, qw, qb, qb, qw, qb, qw, qw, qb, qw, qb, qb, qb, qw, qw, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qw, qw, qw, qb, qw, qw, qw, qb, qb, qw, qw, qw, qw, qb, qw, qb, qw, qb, qw, qb, qb, qw, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qb, qw, qw, qw, qb, qb, qb, qw, qw, qb, qb, qw, qw, qb, qb, qb, qb, qw, qb, qw, qw, qb, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qb, qb, qb, qb, qw, qb, qw, qw, qw, qb, qw, qw, qw, qw, qw, qw, qb, qw, qw, qb, qb, qb, qw, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qw, qw, qb, qb, qb, qw, qb, qw, qb, qb, qw, qw, qw, qb, qb, qb, qb, qb, qb, qw, qw, qw, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qb, qw, qb, qw, qb, qb, qb, qb, qb, qw, qw, qw, qb, qw, qw, qb, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qb, qb, qb, qb, qb, qb, qw, qw, qw, qw, qb, qw, qw, qw, qw, qb, qw, qb, qw, qb, qb, qw, qw, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qw, qw, qw, qw, qb, qw, qw, qb, qb, qw, qb, qb, qw, qw, qb, qw, qw, qw, qb, qw, qw, qb, qw, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qb, qb, qb, qw, qb, qw, qw, qb, qb, qw, qb, qw, qb, qb, qb, qb, qb, qb, qb, qw, qb, qb, qw, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qb, qb, qb, qw, qb, qw, qw, qb, qb, qw, qw, qw, qb, qb, qb, qb, qb, qb, qw, qw, qw, qw, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qb, qb, qb, qw, qb, qw, qw, qw, qw, qb, qb, qw, qw, qw, qb, qw, qw, qw, qw, qb, qb, qw, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qw, qw, qw, qw, qw, qb, qw, qw, qb, qw, qb, qw, qw, qb, qw, qb, qb, qw, qb, qb, qw, qw, qw, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qb, qb, qb, qb, qb, qb, qb, qw, qb, qb, qw, qw, qw, qb, qb, qb, qb, qb, qw, qb, qb, qw, qw, qw, qb, qw, qw, qw, qw,
  qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw,
  qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw,
  qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw,
  qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw, qw
)]
        ]
      ]
    ]),
  )
])


#v(4pt)
#block(width:100%, stroke:(paint:rgb("#666666"),thickness:0.8pt,dash:"dashed"), radius:4pt, clip:true, [
  #rect(width:100%, height:16pt, [#align(center+horizon)[#text(8pt, weight:"bold")[PHẦN I – TRẮC NGHIỆM (50 câu, chọn 1 đáp án)]]])
  #grid(columns: (1fr,) * 4, stroke: (x,y) => if x==0 { none } else { 0.5pt },
          block(
            stroke: (right: 0.5pt),
            inset: 2pt,
            [
              #grid(
                columns: (16pt, 12pt, 12pt, 12pt, 12pt),
                align(center)[#tracking-marker], align(center)[*A*], align(center)[*B*], align(center)[*C*], align(center)[*D*],
              )
              #v(2pt)
              #grid(columns: 1, row-gutter: 1.5pt, ..range(1, 14).map(i => grid(
                columns: (16pt, 12pt, 12pt, 12pt, 12pt),
                align(center + horizon)[*#i*],
                bubble(""), bubble(""), bubble(""), bubble(""),
              )))
            ]
          ),

          block(
            stroke: (right: 0.5pt),
            inset: 2pt,
            [
              #grid(
                columns: (16pt, 12pt, 12pt, 12pt, 12pt),
                align(center)[#tracking-marker], align(center)[*A*], align(center)[*B*], align(center)[*C*], align(center)[*D*],
              )
              #v(2pt)
              #grid(columns: 1, row-gutter: 1.5pt, ..range(14, 27).map(i => grid(
                columns: (16pt, 12pt, 12pt, 12pt, 12pt),
                align(center + horizon)[*#i*],
                bubble(""), bubble(""), bubble(""), bubble(""),
              )))
            ]
          ),

          block(
            stroke: (right: 0.5pt),
            inset: 2pt,
            [
              #grid(
                columns: (16pt, 12pt, 12pt, 12pt, 12pt),
                align(center)[#tracking-marker], align(center)[*A*], align(center)[*B*], align(center)[*C*], align(center)[*D*],
              )
              #v(2pt)
              #grid(columns: 1, row-gutter: 1.5pt, ..range(27, 40).map(i => grid(
                columns: (16pt, 12pt, 12pt, 12pt, 12pt),
                align(center + horizon)[*#i*],
                bubble(""), bubble(""), bubble(""), bubble(""),
              )))
            ]
          ),

          block(
            stroke: (right: 0.5pt),
            inset: 2pt,
            [
              #grid(
                columns: (16pt, 12pt, 12pt, 12pt, 12pt),
                align(center)[#tracking-marker], align(center)[*A*], align(center)[*B*], align(center)[*C*], align(center)[*D*],
              )
              #v(2pt)
              #grid(columns: 1, row-gutter: 1.5pt, ..range(40, 51).map(i => grid(
                columns: (16pt, 12pt, 12pt, 12pt, 12pt),
                align(center + horizon)[*#i*],
                bubble(""), bubble(""), bubble(""), bubble(""),
              )))
            ]
          ) )
])



// ── TỰ LUẬN VIẾT TAY ────────────────────────────────────────


#v(5pt)
#block(width: 100%, height: 0pt)[
  #place(left, dx: -5mm, dy: 2mm, marker)
  #place(right, dx: 5mm, dy: 2mm, marker)
]

  ]
]
