[package]
name = "sertyp"
version = "0.1.4"
entrypoint = "lib.typ"
authors = ["Uhrendoktor <docclock85@gmail.com>"]
license = "MIT"
description = "Serialization and deserialization of most Typst types into sertyp CBOR format: This includes markup, math, etc."
repository = "https://github.com/Uhrendoktor/sertyp"
keywords = ["wasm", "serialization", "deserialization"]
categories = ["scripting", "integration", "utility"]
exclude = []
