#import "@preview/tidy:0.4.3": *

#set page(width: 190mm, height: 300mm, margin: 20mm)
#set par(justify: true)
#set text(font: "Libertinus Serif", size: 10pt)

#let number-until-with(max-level, schema) = (..numbers) => {
  if numbers.pos().len() <= max-level {
    numbering(schema, ..numbers)
  }
}

#set heading(numbering: number-until-with(2, "1.1"))

#show heading.where(level: 1): it => [#set text(size: 14pt);#v(12pt);#it;#v(6pt)]
#show heading.where(level: 2): it => [#set text(size: 12pt);#it;#v(4pt)]
#show heading.where(level: 3): it => [#set text(size:  8pt);#it.body;#v(1pt)]

#let pkg-meta = toml("typst.toml")
#let this-pkg = pkg-meta.package

#let pkg-ver = [#raw(this-pkg.name + "-" + this-pkg.version)]

#set document(
  title: [Package API documentation for #pkg-ver],
  author: this-pkg.authors,
  description: [Package API documentation for #pkg-ver],
  keywords: this-pkg.keywords,
  date: datetime.today(),
)

#show title: it => {
  set text(size: 17pt)
  set align(center)
  block(width: 60%, height: 48pt)[
    #align(center + horizon)[#it]
  ]
}

#show "->": text(font: "Libertinus Serif")[#sym.arrow.r]

#title()

#align(center)[#grid(
    columns: (40%),
    align(center)[
      #set text(size: 0.8em)
      C. Naaktgeboren \
      #link("https://github.com/cnaak/blindex.typ")
    ],
  )
]
#v(1em)

= Introduction

The sections below are automatically generated by `tidy-0.4.3` based on the source code
documentation annotations on #pkg-ver.

#import "blindex.typ"
#let api = parse-module(
  read("blindex.typ"),
  name: this-pkg.name,
  scope: (blindex: blindex),
  preamble: "#import blindex: *\n"
)

#show-module(
  api,
  style: styles.default,
  first-heading-level: 1,
)


