[package]
name = "bulb"
version = "0.2.0"
compiler = "0.14.0"
entrypoint = "lib.typ"
authors = ["Miel Peeters <@mielpeeters>"]
license = "MIT"
description = "Image dithering plugin, powered by WASM."
keywords = ["dithering", "image", "stylized", "bayer", "halftone", "palette"]
repository = "https://github.com/mielpeeters/bulb-typst"
categories = ["visualization"]
