[package]
name = "ott-ng"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["pe200012 <pe1326263755@gmail.com>"]
license = "BSD-2-Clause"
description = "Parse Ott snippets and render Typst math through WASM."
repository = "https://github.com/pe200012/ott-typst"
compiler = "0.14.0"
keywords = ["ott", "semantics", "wasm", "math", "grammar"]
categories = ["integration", "scripting"]
