
// The Traditional Colors of China
// https://colors.ichuantong.cn

// The English translation is not the official
// translation of the colors. These are just the
// names I gave them based on what little
// knowledge I have of chinese Characters and
// their meanings. There will be errors in the
// appropriate translated name of the colors.

// 红 - Red
// 黄 - Yellow
// 绿 - Green
// 蓝 - Blue
// 苍 - Pale / Pastel
// 水 - Water
// 灰白 - Grey & White
// 黑 - Black
// 金银 - Gold & Silver

#let zhongguo-traditional = (
  "红": (
    output: (caps: none, hyphen: none),
    "粉红": rgb("#FFB3A7"),
    "妃色": rgb("#ED5736"),
    "品红": rgb("#F00056"),
    "桃红": rgb("#F47983"),
    "海棠红": rgb("#DB5A6B"),
    "石榴红": rgb("#F20C00"),
    "樱桃色": rgb("#C93756"),
    "银红": rgb("#F05654"),
    "大红": rgb("#FF2121"),
    "绛紫": rgb("#8C4356"),
    "绯红": rgb("#C83C23"),
    "胭脂": rgb("#9D2933"),
    "朱红": rgb("#FF4C00"),
    "丹": rgb("#FF4E20"),
    "彤": rgb("#F35336"),
    "茜色": rgb("#CB3A56"),
    "火红": rgb("#FF2D51"),
    "赫赤": rgb("#C91F37"),
    "嫣红": rgb("#EF7A82"),
    "洋红": rgb("#FF0097"),
    "炎": rgb("#FF3300"),
    "赤": rgb("#C3272B"),
    "绾": rgb("#A98175"),
    "枣红": rgb("#C32136"),
    "檀": rgb("#B36D61"),
    "殷红": rgb("#BE002F"),
    "酡红": rgb("#DC3023"),
    "酡颜": rgb("#F9906F"),
  ),
  "黄": (
    output: (caps: none, hyphen: none),
    "鹅黄": rgb("#FFF143"),
    "鸭黄": rgb("#FAFF72"),
    "樱草色": rgb("#EAFF56"),
    "杏黄": rgb("#FFA631"),
    "杏红": rgb("#FF8C31"),
    "橘黄": rgb("#FF8936"),
    "橙黄": rgb("#FFA400"),
    "橘红": rgb("#FF7500"),
    "姜黄": rgb("#FFC773"),
    "缃色": rgb("#F0C239"),
    "橙色": rgb("#FA8C35"),
    "茶色": rgb("#B35C44"),
    "驼色": rgb("#A88462"),
    "昏黄": rgb("#C89B40"),
    "栗色": rgb("#60281E"),
    "棕色": rgb("#B25D25"),
    "棕绿": rgb("#827100"),
    "棕黑": rgb("#7C4B00"),
    "棕红": rgb("#9B4400"),
    "棕黄": rgb("#AE7000"),
    "赭": rgb("#9C5333"),
    "赭色": rgb("#955539"),
    "琥珀": rgb("#CA6924"),
    "褐色": rgb("#6E511E"),
    "枯黄": rgb("#D3B17D"),
    "黄栌": rgb("#E29C45"),
    "秋色": rgb("#896C39"),
    "秋香色": rgb("#D9B611"),
  ),
  "绿": (
    output: (caps: none, hyphen: none),
    "嫩绿": rgb("#BDDD22"),
    "柳黄": rgb("#C9DD22"),
    "柳绿": rgb("#AFDD22"),
    "竹青": rgb("#789262"),
    "葱黄": rgb("#A3D900"),
    "葱绿": rgb("#9ED900"),
    "葱青": rgb("#0EB83A"),
    "葱倩": rgb("#0EB840"),
    "青葱": rgb("#0AA344"),
    "油绿": rgb("#00BC12"),
    "绿沈": rgb("#0C8918"),
    "碧色": rgb("#1BD1A5"),
    "碧绿": rgb("#2ADD9C"),
    "青碧": rgb("#48C0A3"),
    "翡翠色": rgb("#3DE1AD"),
    "草绿": rgb("#40DE5A"),
    "青色": rgb("#00E09E"),
    "青翠": rgb("#00E079"),
    "青白": rgb("#C0EBD7"),
    "鸭卵青": rgb("#E0EEE8"),
    "蟹壳青": rgb("#BBCDC5"),
    "鸦青": rgb("#424C50"),
    "绿色": rgb("#00E500"),
    "豆绿": rgb("#9ED048"),
    "豆青": rgb("#96CE54"),
    "石青": rgb("#7BCFA6"),
    "玉色": rgb("#2EDFA3"),
    "缥": rgb("#7FECAD"),
    "艾绿": rgb("#A4E2C6"),
    "松柏绿": rgb("#21A675"),
    "松花绿": rgb("#057748"),
    "松花色": rgb("#BCE672"),
  ),
  "蓝": (
    output: (caps: none, hyphen: none),
    "蓝": rgb("#44CEF6"),
    "靛青": rgb("#177CB0"),
    "靛蓝": rgb("#065279"),
    "碧蓝": rgb("#3EEDE7"),
    "蔚蓝": rgb("#70F3FF"),
    "宝蓝": rgb("#4B5CC4"),
    "蓝灰色": rgb("#A1AFC9"),
    "藏青": rgb("#2E4E7E"),
    "藏蓝": rgb("#3B2E7E"),
    "黛": rgb("#4A4266"),
    "黛绿": rgb("#426666"),
    "黛蓝": rgb("#425066"),
    "黛紫": rgb("#574266"),
    "紫色": rgb("#8D4BBB"),
    "紫酱": rgb("#815463"),
    "酱紫": rgb("#815476"),
    "紫檀": rgb("#4C221B"),
    "绀青绀紫": rgb("#003371"),
    "紫棠": rgb("#56004F"),
    "青莲": rgb("#801DAE"),
    "群青": rgb("#4C8DAE"),
    "雪青": rgb("#B0A4E3"),
    "丁香色": rgb("#CCA4E3"),
    "藕色": rgb("#EDD1D8"),
    "藕荷色": rgb("#E4C6D0"),
  ),
  "苍": (
    output: (caps: none, hyphen: none),
    "苍色": rgb("#75878A"),
    "苍翠": rgb("#519A73"),
    "苍黄": rgb("#A29B7C"),
    "苍青": rgb("#7397AB"),
    "苍黑": rgb("#395260"),
    "苍白": rgb("#D1D9E0"),
  ),
  "水": (
    output: (caps: none, hyphen: none),
    "水色": rgb("#88ADA6"),
    "水红": rgb("#F3D3E7"),
    "水绿": rgb("#D4F2E7"),
    "水蓝": rgb("#D2F0F4"),
    "淡青": rgb("#D3E0F3"),
    "湖蓝": rgb("#30DFF3"),
    "湖绿": rgb("#25F8CB"),
  ),
  "灰白": (
    output: (caps: none, hyphen: none),
    "精白": rgb("#FFFFFF"),
    "象牙白": rgb("#FFFBF0"),
    "雪白": rgb("#F2FDFF"),
    "月白": rgb("#D6ECF0"),
    "缟": rgb("#F2ECDE"),
    "素": rgb("#E0F0E9"),
    "荼白": rgb("#F3F9F1"),
    "霜色": rgb("#E9F1F6"),
    "花白": rgb("#C2CCD0"),
    "鱼肚白": rgb("#FCEFE8"),
    "莹白": rgb("#E3F9FD"),
    "灰色": rgb("#808080"),
    "牙色": rgb("#EEDEB0"),
    "铅白": rgb("#F0F0F4"),
  ),
  "黑": (
    output: (caps: none, hyphen: none),
    "玄色": rgb("#622A1D"),
    "玄青": rgb("#3D3B4F"),
    "乌色": rgb("#725E82"),
    "乌黑": rgb("#392F41"),
    "漆黑": rgb("#161823"),
    "墨色": rgb("#50616D"),
    "墨灰": rgb("#758A99"),
    "黑色": rgb("#000000"),
    "缁色": rgb("#493131"),
    "煤黑": rgb("#312520"),
    "黧": rgb("#5D513C"),
    "黎": rgb("#75664D"),
    "黝": rgb("#6B6882"),
    "黝黑": rgb("#665757"),
    "黯": rgb("#41555D"),
  ),
  "金银": (
    output: (caps: none, hyphen: none),
    "赤金": rgb("#F2BE45"),
    "金色": rgb("#EACD76"),
    "银白": rgb("#E9E7EF"),
    "老银": rgb("#BACAC6"),
    "乌金": rgb("#A78E44"),
    "铜绿": rgb("#549688"),
  ),
)

#let zhongguo = (
  output: (caps: none, hyphen: false),
  zh: zhongguo-traditional,
  pinyin: (
    output: (caps: none, hyphen: false),
    "hong": (
      output: (caps: none, hyphen: false),
      "fen-hong": zhongguo-traditional.红.粉红,
      "fei-se": zhongguo-traditional.红.妃色,
      "pin-hong": zhongguo-traditional.红.品红,
      "tao-hong": zhongguo-traditional.红.桃红,
      "hai-tang-hong": zhongguo-traditional.红.海棠红,
      "shi-liu-hong": zhongguo-traditional.红.石榴红,
      "ying-tao-se": zhongguo-traditional.红.樱桃色,
      "yin-hong": zhongguo-traditional.红.银红,
      "da-hong": zhongguo-traditional.红.大红,
      "jiang-zi": zhongguo-traditional.红.绛紫,
      "fei-hong": zhongguo-traditional.红.绯红,
      "yan-zhi": zhongguo-traditional.红.胭脂,
      "zhu-hong": zhongguo-traditional.红.朱红,
      "dan": zhongguo-traditional.红.丹,
      "tong": zhongguo-traditional.红.彤,
      "qian-se": zhongguo-traditional.红.茜色,
      "huo-hong": zhongguo-traditional.红.火红,
      "he-chi": zhongguo-traditional.红.赫赤,
      "yan-hong": zhongguo-traditional.红.嫣红,
      "yang-hong": zhongguo-traditional.红.洋红,
      "yan": zhongguo-traditional.红.炎,
      "chi": zhongguo-traditional.红.赤,
      "wan": zhongguo-traditional.红.绾,
      "zao-hong": zhongguo-traditional.红.枣红,
      "tan": zhongguo-traditional.红.檀,
      "yin-hong-2": zhongguo-traditional.红.殷红,
      "tuo-hong": zhongguo-traditional.红.酡红,
      "tuo-yan": zhongguo-traditional.红.酡颜,
    ),
    "huang": (
      output: (caps: none, hyphen: false),
      "e-huang": zhongguo-traditional.黄.鹅黄,
      "ya-huang": zhongguo-traditional.黄.鸭黄,
      "ying-cao-se": zhongguo-traditional.黄.樱草色,
      "xing-huang": zhongguo-traditional.黄.杏黄,
      "xing-hong": zhongguo-traditional.黄.杏红,
      "ju-huang": zhongguo-traditional.黄.橘黄,
      "cheng-huang": zhongguo-traditional.黄.橙黄,
      "ju-hong": zhongguo-traditional.黄.橘红,
      "jiang-huang": zhongguo-traditional.黄.姜黄,
      "xiang-se": zhongguo-traditional.黄.缃色,
      "cheng-se": zhongguo-traditional.黄.橙色,
      "cha-se": zhongguo-traditional.黄.茶色,
      "tuo-se": zhongguo-traditional.黄.驼色,
      "hun-huang": zhongguo-traditional.黄.昏黄,
      "li-se": zhongguo-traditional.黄.栗色,
      "zong-se": zhongguo-traditional.黄.棕色,
      "zong-lu": zhongguo-traditional.黄.棕绿,
      "zong-hei": zhongguo-traditional.黄.棕黑,
      "zong-hong": zhongguo-traditional.黄.棕红,
      "zong-huang": zhongguo-traditional.黄.棕黄,
      "zhe": zhongguo-traditional.黄.赭,
      "zhe-se": zhongguo-traditional.黄.赭色,
      "hu-po": zhongguo-traditional.黄.琥珀,
      "he-se": zhongguo-traditional.黄.褐色,
      "ku-huang": zhongguo-traditional.黄.枯黄,
      "huang-lu": zhongguo-traditional.黄.黄栌,
      "qiu-se": zhongguo-traditional.黄.秋色,
      "qiu-xiang-se": zhongguo-traditional.黄.秋香色,
    ),
    "lu": (
      output: (caps: none, hyphen: false),
      "nen-lu": zhongguo-traditional.绿.嫩绿,
      "liu-huang": zhongguo-traditional.绿.柳黄,
      "liu-lu": zhongguo-traditional.绿.柳绿,
      "zhu-qing": zhongguo-traditional.绿.竹青,
      "cong-huang": zhongguo-traditional.绿.葱黄,
      "cong-lu": zhongguo-traditional.绿.葱绿,
      "cong-qing": zhongguo-traditional.绿.葱青,
      "cong-qian": zhongguo-traditional.绿.葱倩,
      "qing-cong": zhongguo-traditional.绿.青葱,
      "you-lu": zhongguo-traditional.绿.油绿,
      "lu-shen": zhongguo-traditional.绿.绿沈,
      "bi-se": zhongguo-traditional.绿.碧色,
      "bi-lu": zhongguo-traditional.绿.碧绿,
      "qing-bi": zhongguo-traditional.绿.青碧,
      "fei-cui-se": zhongguo-traditional.绿.翡翠色,
      "cao-lu": zhongguo-traditional.绿.草绿,
      "qing-se": zhongguo-traditional.绿.青色,
      "qing-cui": zhongguo-traditional.绿.青翠,
      "qing-bai": zhongguo-traditional.绿.青白,
      "ya-luan-qing": zhongguo-traditional.绿.鸭卵青,
      "xie-ke-qing": zhongguo-traditional.绿.蟹壳青,
      "ya-qing": zhongguo-traditional.绿.鸦青,
      "lu-se": zhongguo-traditional.绿.绿色,
      "dou-lu": zhongguo-traditional.绿.豆绿,
      "dou-qing": zhongguo-traditional.绿.豆青,
      "shi-qing": zhongguo-traditional.绿.石青,
      "yù-se": zhongguo-traditional.绿.玉色,
      "piao": zhongguo-traditional.绿.缥,
      "ai-lu": zhongguo-traditional.绿.艾绿,
      "song-bai-lu": zhongguo-traditional.绿.松柏绿,
      "song-hua-lu": zhongguo-traditional.绿.松花绿,
      "song-hua-se": zhongguo-traditional.绿.松花色,
    ),
    "lan": (
      output: (caps: none, hyphen: false),
      "lan": zhongguo-traditional.蓝.蓝,
      "dian-qing": zhongguo-traditional.蓝.靛青,
      "dian-lan": zhongguo-traditional.蓝.靛蓝,
      "bi-lan": zhongguo-traditional.蓝.碧蓝,
      "wei-lan": zhongguo-traditional.蓝.蔚蓝,
      "bao-lan": zhongguo-traditional.蓝.宝蓝,
      "lan-hui-se": zhongguo-traditional.蓝.蓝灰色,
      "zang-qing": zhongguo-traditional.蓝.藏青,
      "zang-lan": zhongguo-traditional.蓝.藏蓝,
      "dai": zhongguo-traditional.蓝.黛,
      "dai-lu": zhongguo-traditional.蓝.黛绿,
      "dai-lan": zhongguo-traditional.蓝.黛蓝,
      "dai-zi": zhongguo-traditional.蓝.黛紫,
      "zi-se": zhongguo-traditional.蓝.紫色,
      "zi-jiang": zhongguo-traditional.蓝.紫酱,
      "jiang-zi": zhongguo-traditional.蓝.酱紫,
      "zi-tan": zhongguo-traditional.蓝.紫檀,
      "gan-qing-gan-zi": zhongguo-traditional.蓝.绀青绀紫,
      "zi-tang": zhongguo-traditional.蓝.紫棠,
      "qing-lian": zhongguo-traditional.蓝.青莲,
      "qun-qing": zhongguo-traditional.蓝.群青,
      "xue-qing": zhongguo-traditional.蓝.雪青,
      "ding-xiang-se": zhongguo-traditional.蓝.丁香色,
      "ou-se": zhongguo-traditional.蓝.藕色,
      "ou-he-se": zhongguo-traditional.蓝.藕荷色,
    ),
    "cang": (
      output: (caps: none, hyphen: false),
      "cang-se": zhongguo-traditional.苍.苍色,
      "cang-cui": zhongguo-traditional.苍.苍翠,
      "cang-huang": zhongguo-traditional.苍.苍黄,
      "cang-qing": zhongguo-traditional.苍.苍青,
      "cang-hei": zhongguo-traditional.苍.苍黑,
      "cang-bai": zhongguo-traditional.苍.苍白,
    ),
    "shui": (
      output: (caps: none, hyphen: false),
      "shui-se": zhongguo-traditional.水.水色,
      "shui-hong": zhongguo-traditional.水.水红,
      "shui-lu": zhongguo-traditional.水.水绿,
      "shui-lan": zhongguo-traditional.水.水蓝,
      "dan-qing": zhongguo-traditional.水.淡青,
      "hu-lan": zhongguo-traditional.水.湖蓝,
      "hu-lu": zhongguo-traditional.水.湖绿,
    ),
    "huibai": (
      output: (caps: none, hyphen: false),
      "jing-bai": zhongguo-traditional.灰白.精白,
      "xiang-ya-bai": zhongguo-traditional.灰白.象牙白,
      "xue-bai": zhongguo-traditional.灰白.雪白,
      "yue-bai": zhongguo-traditional.灰白.月白,
      "gao": zhongguo-traditional.灰白.缟,
      "sù": zhongguo-traditional.灰白.素,
      "tu-bai": zhongguo-traditional.灰白.荼白,
      "shuang-se": zhongguo-traditional.灰白.霜色,
      "hua-bai": zhongguo-traditional.灰白.花白,
      "yu-du-bai": zhongguo-traditional.灰白.鱼肚白,
      "ying-bai": zhongguo-traditional.灰白.莹白,
      "hui-se": zhongguo-traditional.灰白.灰色,
      "ya-se": zhongguo-traditional.灰白.牙色,
      "qian-bai": zhongguo-traditional.灰白.铅白,
    ),
    "hei": (
      output: (caps: none, hyphen: false),
      "xuan-se": zhongguo-traditional.黑.玄色,
      "xuan-qing": zhongguo-traditional.黑.玄青,
      "wu-se": zhongguo-traditional.黑.乌色,
      "wu-hei": zhongguo-traditional.黑.乌黑,
      "qi-hei": zhongguo-traditional.黑.漆黑,
      "mo-se": zhongguo-traditional.黑.墨色,
      "mo-hui": zhongguo-traditional.黑.墨灰,
      "hei-se": zhongguo-traditional.黑.黑色,
      "zi-se": zhongguo-traditional.黑.缁色,
      "mei-hei": zhongguo-traditional.黑.煤黑,
      "li": zhongguo-traditional.黑.黧,
      "li-2": zhongguo-traditional.黑.黎,
      "you": zhongguo-traditional.黑.黝,
      "you-hei": zhongguo-traditional.黑.黝黑,
      "an": zhongguo-traditional.黑.黯,
    ),
    "jinyin": (
      output: (caps: none, hyphen: false),
      "chi-jin": zhongguo-traditional.金银.赤金,
      "jin-se": zhongguo-traditional.金银.金色,
      "yin-bai": zhongguo-traditional.金银.银白,
      "lao-yin": zhongguo-traditional.金银.老银,
      "wu-jin": zhongguo-traditional.金银.乌金,
      "tong-lu": zhongguo-traditional.金银.铜绿,
    ),
  ),
  en: (
    output: (caps: "each", hyphen: false),
    "red": (
      output: (caps: "each", hyphen: false),
      "pink": zhongguo-traditional.红.粉红,
      "imperial-red": zhongguo-traditional.红.妃色,
      "magenta": zhongguo-traditional.红.品红,
      "peony": zhongguo-traditional.红.桃红,
      "begonia-red": zhongguo-traditional.红.海棠红,
      "pomegranate-red": zhongguo-traditional.红.石榴红,
      "cherry": zhongguo-traditional.红.樱桃色,
      "silver-red": zhongguo-traditional.红.银红,
      "scarlet": zhongguo-traditional.红.大红,
      "dark-red-purple": zhongguo-traditional.红.绛紫,
      "crimson": zhongguo-traditional.红.绯红,
      "rouge": zhongguo-traditional.红.胭脂,
      "vermilion": zhongguo-traditional.红.朱红,
      "cinnabar": zhongguo-traditional.红.丹,
      "sunrise": zhongguo-traditional.红.彤,
      "akane-sunset": zhongguo-traditional.红.茜色,
      "fiery-red": zhongguo-traditional.红.火红,
      "crimson-fire": zhongguo-traditional.红.赫赤,
      "bright-red": zhongguo-traditional.红.嫣红,
      "carmine": zhongguo-traditional.红.洋红,
      "burning-red": zhongguo-traditional.红.炎,
      "red": zhongguo-traditional.红.赤,
      "faded-red": zhongguo-traditional.红.绾,
      "jujube-red": zhongguo-traditional.红.枣红,
      "sandalwood": zhongguo-traditional.红.檀,
      "blood-flowing-red": zhongguo-traditional.红.殷红,
      "drunken-red": zhongguo-traditional.红.酡红,
      "blushing-red": zhongguo-traditional.红.酡颜,
    ),
    "yellow": (
      output: (caps: "each", hyphen: false),
      "goose-yellow": zhongguo-traditional.黄.鹅黄,
      "duck-yellow": zhongguo-traditional.黄.鸭黄,
      "primrose": zhongguo-traditional.黄.樱草色,
      "apricot-yellow": zhongguo-traditional.黄.杏黄,
      "apricot-red": zhongguo-traditional.黄.杏红,
      "tangerine": zhongguo-traditional.黄.橘黄,
      "tangerine-yellow": zhongguo-traditional.黄.橙黄,
      "orange-peel": zhongguo-traditional.黄.橘红,
      "turmeric": zhongguo-traditional.黄.姜黄,
      "silky-yellow": zhongguo-traditional.黄.缃色,
      "orange": zhongguo-traditional.黄.橙色,
      "tawny-brown": zhongguo-traditional.黄.茶色,
      "camel-brown": zhongguo-traditional.黄.驼色,
      "twilight-yellow": zhongguo-traditional.黄.昏黄,
      "maroon": zhongguo-traditional.黄.栗色,
      "husky-brown": zhongguo-traditional.黄.棕色,
      "brown-green": zhongguo-traditional.黄.棕绿,
      "brown-black": zhongguo-traditional.黄.棕黑,
      "brown-red": zhongguo-traditional.黄.棕红,
      "light-brown": zhongguo-traditional.黄.棕黄,
      "ochre": zhongguo-traditional.黄.赭,
      "iron-ochre": zhongguo-traditional.黄.赭色,
      "amber": zhongguo-traditional.黄.琥珀,
      "brown": zhongguo-traditional.黄.褐色,
      "withered-yellow": zhongguo-traditional.黄.枯黄,
      "sumac-brown": zhongguo-traditional.黄.黄栌,
      "autumn": zhongguo-traditional.黄.秋色,
      "autumn-fragrance": zhongguo-traditional.黄.秋香色,
    ),
    "green": (
      output: (caps: "each", hyphen: false),
      "tender-green": zhongguo-traditional.绿.嫩绿,
      "willow-yellow": zhongguo-traditional.绿.柳黄,
      "willow-green": zhongguo-traditional.绿.柳绿,
      "bamboo-green": zhongguo-traditional.绿.竹青,
      "scallion-yellow": zhongguo-traditional.绿.葱黄,
      "scallion-heart-green": zhongguo-traditional.绿.葱绿,
      "scallion-green": zhongguo-traditional.绿.葱青,
      "lush-green": zhongguo-traditional.绿.葱倩,
      "scallion": zhongguo-traditional.绿.青葱,
      "oily-green": zhongguo-traditional.绿.油绿,
      "thick-green": zhongguo-traditional.绿.绿沈,
      "cyan-green": zhongguo-traditional.绿.碧色,
      "aquamarine": zhongguo-traditional.绿.碧绿,
      "turquoise": zhongguo-traditional.绿.青碧,
      "emerald": zhongguo-traditional.绿.翡翠色,
      "lime": zhongguo-traditional.绿.草绿,
      "cyan": zhongguo-traditional.绿.青色,
      "fresh-green": zhongguo-traditional.绿.青翠,
      "light-cyan": zhongguo-traditional.绿.青白,
      "duck-egg-green": zhongguo-traditional.绿.鸭卵青,
      "crab-shell-green": zhongguo-traditional.绿.蟹壳青,
      "crow-feather-green": zhongguo-traditional.绿.鸦青,
      "green": zhongguo-traditional.绿.绿色,
      "bean-green": zhongguo-traditional.绿.豆绿,
      "porcelain-green": zhongguo-traditional.绿.豆青,
      "azurite-green": zhongguo-traditional.绿.石青,
      "jade": zhongguo-traditional.绿.玉色,
      "cyan-white": zhongguo-traditional.绿.缥,
      "mugwort": zhongguo-traditional.绿.艾绿,
      "pine-green": zhongguo-traditional.绿.松柏绿,
      "pine-flower-green": zhongguo-traditional.绿.松花绿,
      "pine-flower": zhongguo-traditional.绿.松花色,
    ),
    "blue": (
      output: (caps: "each", hyphen: false),
      "blue": zhongguo-traditional.蓝.蓝,
      "indigo": zhongguo-traditional.蓝.靛青,
      "indigo-dye": zhongguo-traditional.蓝.靛蓝,
      "jade-blue": zhongguo-traditional.蓝.碧蓝,
      "sky-blue": zhongguo-traditional.蓝.蔚蓝,
      "blue-sapphire": zhongguo-traditional.蓝.宝蓝,
      "blue-gray": zhongguo-traditional.蓝.蓝灰色,
      "navy-blue": zhongguo-traditional.蓝.藏青,
      "navy-blue-purple": zhongguo-traditional.蓝.藏蓝,
      "cyan-black": zhongguo-traditional.蓝.黛,
      "dark-green": zhongguo-traditional.蓝.黛绿,
      "dark-blue": zhongguo-traditional.蓝.黛蓝,
      "dark-purple": zhongguo-traditional.蓝.黛紫,
      "purple": zhongguo-traditional.蓝.紫色,
      "purple-jam": zhongguo-traditional.蓝.紫酱,
      "dark-red-purple": zhongguo-traditional.蓝.酱紫,
      "red-saldalwood": zhongguo-traditional.蓝.紫檀,
      "cyanotic-purple": zhongguo-traditional.蓝.绀青绀紫,
      "purple-begonia": zhongguo-traditional.蓝.紫棠,
      "green-lotus": zhongguo-traditional.蓝.青莲,
      "ultramarine": zhongguo-traditional.蓝.群青,
      "violet-blue": zhongguo-traditional.蓝.雪青,
      "lilac": zhongguo-traditional.蓝.丁香色,
      "tender-lotus-root": zhongguo-traditional.蓝.藕色,
      "lotus-root": zhongguo-traditional.蓝.藕荷色,
    ),
    "pastel": (
      output: (caps: "each", hyphen: false),
      "pale-horizon": zhongguo-traditional.苍.苍色,
      "tender-jade": zhongguo-traditional.苍.苍翠,
      "sallow": zhongguo-traditional.苍.苍黄,
      "pale-cyan": zhongguo-traditional.苍.苍青,
      "pale-black": zhongguo-traditional.苍.苍黑,
      "pale-fright": zhongguo-traditional.苍.苍白,
    ),
    "aqua": (
      output: (caps: "each", hyphen: false),
      "aqua": zhongguo-traditional.水.水色,
      "aquatic-red": zhongguo-traditional.水.水红,
      "aquatic-green": zhongguo-traditional.水.水绿,
      "aquatic-blue": zhongguo-traditional.水.水蓝,
      "light-blue": zhongguo-traditional.水.淡青,
      "lake-blue": zhongguo-traditional.水.湖蓝,
      "lake-green": zhongguo-traditional.水.湖绿,
    ),
    "grey-white": (
      output: (caps: "each", hyphen: false),
      "pure-white": zhongguo-traditional.灰白.精白,
      "ivory": zhongguo-traditional.灰白.象牙白,
      "snow-white": zhongguo-traditional.灰白.雪白,
      "moonlight": zhongguo-traditional.灰白.月白,
      "white-silk": zhongguo-traditional.灰白.缟,
      "plain-white": zhongguo-traditional.灰白.素,
      "white-tea": zhongguo-traditional.灰白.荼白,
      "white-frost": zhongguo-traditional.灰白.霜色,
      "cabbage-white": zhongguo-traditional.灰白.花白,
      "fish-maw-white": zhongguo-traditional.灰白.鱼肚白,
      "crystal-white": zhongguo-traditional.灰白.莹白,
      "grey": zhongguo-traditional.灰白.灰色,
      "milky-white": zhongguo-traditional.灰白.牙色,
      "lead-white": zhongguo-traditional.灰白.铅白,
    ),
    "black": (
      output: (caps: "each", hyphen: false),
      "black-noir": zhongguo-traditional.黑.玄色,
      "deep-black": zhongguo-traditional.黑.玄青,
      "crow-black": zhongguo-traditional.黑.乌色,
      "jet-black": zhongguo-traditional.黑.乌黑,
      "pitch-black": zhongguo-traditional.黑.漆黑,
      "ink": zhongguo-traditional.黑.墨色,
      "grey-ink": zhongguo-traditional.黑.墨灰,
      "black": zhongguo-traditional.黑.黑色,
      "black-silk": zhongguo-traditional.黑.缁色,
      "coal": zhongguo-traditional.黑.煤黑,
      "dark-sallow": zhongguo-traditional.黑.黧,
      "black-millet": zhongguo-traditional.黑.黎,
      "dark-green": zhongguo-traditional.黑.黝,
      "suntan-black": zhongguo-traditional.黑.黝黑,
      "dull-black": zhongguo-traditional.黑.黯,
    ),
    "gold-silver": (
      output: (caps: "each", hyphen: false),
      "pure-gold": zhongguo-traditional.金银.赤金,
      "gold": zhongguo-traditional.金银.金色,
      "silvery-white": zhongguo-traditional.金银.银白,
      "antique-silver": zhongguo-traditional.金银.老银,
      "black-gold": zhongguo-traditional.金银.乌金,
      "patina": zhongguo-traditional.金银.铜绿,
    ),
  ),
)
