

// TODO: Can I automate capitalization? E.g. periods function should ensure uppercase
// (this should be done with a printfield style argument)

// TODO: Internationalize to other languages than English

// TODO: also include the short bibstring and let the user choose


/// The default long bibstring table. 
/// 
/// A bibstring table maps a number of language-independent
/// identifiers to the strings that will be printed in the bibliography (see the
/// `bibstring` parameter of `format-reference`).
/// Modifying the
/// bibstring table can be useful if you want to localize your bibliography to a language
/// other than English, or if your bibliographic conventions differ from those of
/// the standard #biblatex style. For instance, to keep the reference style from
/// printing "In:" with a trailing colon, you could use a bibstring table in which
/// the "in" key maps to "In" rather than "In:".
/// 
/// This default bibstring table is a verbatim copy of the standard English bibstring
/// table in #biblatex. It contains only the "long" versions of these entries; so
/// references will be typeset to print e.g. "Jones, editor", rather than "Jones, ed.".
/// You can find this table in the file #link("https://github.com/alexanderkoller/pergamon/blob/main/src/bibstrings.typ")[bibstrings.typ].
#let default-long-bibstring = (
  // converted from english.lbx
  "bibliography": "Bibliography",
  "references": "References",
  "shorthands": "List of Abbreviations",
  "editor": "editor",
  "editors": "editors",
  "compiler": "compiler",
  "compilers": "compilers",
  "redactor": "redactor",
  "redactors": "redactors",
  "reviser": "reviser",
  "revisers": "revisers",
  "founder": "founder",
  "founders": "founders",
  "continuator": "continued",
  "continuators": "continued",
  "collaborator": "collaborator",
  "collaborators": "collaborators",
  "translator": "translator",
  "translators": "translators",
  "commentator": "commentator",
  "commentators": "commentators",
  "annotator": "annotator",
  "annotators": "annotators",
  "commentary": "commentary",
  "annotations": "annotations",
  "introduction": "introduction",
  "foreword": "foreword",
  "afterword": "afterword",
  "editortr": "editor and translator",
  "editorstr": "editors and translators",
  "editorco": "editor and commentator",
  "editorsco": "editors and commentators",
  "editoran": "editor and annotator",
  "editorsan": "editors and annotators",
  "editorin": "editor and introduction",
  "editorsin": "editors and introduction",
  "editorfo": "editor and foreword",
  "editorsfo": "editors and foreword",
  "editoraf": "editor and afterword",
  "editorsaf": "editors and afterword",
  "editortrco": "editor, translator, and commentator",
  "editorstrco": "editors, translators, and commentators",
  "editortran": "editor, translator, and annotator",
  "editorstran": "editors, translators, and annotators",
  "editortrin": "editor, translator, and introduction",
  "editorstrin": "editors, translators, and introduction",
  "editortrfo": "editor, translator, and foreword",
  "editorstrfo": "editors, translators, and foreword",
  "editortraf": "editor, translator, and afterword",
  "editorstraf": "editors, translators, and afterword",
  "editorcoin": "editor, commentator, and introduction",
  "editorscoin": "editors, commentators, and introduction",
  "editorcofo": "editor, commentator, and foreword",
  "editorscofo": "editors, commentators, and foreword",
  "editorcoaf": "editor, commentator, and afterword",
  "editorscoaf": "editors, commentators, and afterword",
  "editoranin": "editor, annotator, and introduction",
  "editorsanin": "editors, annotators, and introduction",
  "editoranfo": "editor, annotator, and foreword",
  "editorsanfo": "editors, annotators, and foreword",
  "editoranaf": "editor, annotator, and afterword",
  "editorsanaf": "editors, annotators, and afterword",
  "editortrcoin": "editor, translator, commentator, and introduction",
  "editorstrcoin": "editors, translators, commentators, and introduction",
  "editortrcofo": "editor, translator, commentator, and foreword",
  "editorstrcofo": "editors, translators, commentators, and foreword",
  "editortrcoaf": "editor, translator, commentator, and afterword",
  "editorstrcoaf": "editors, translators, commentators, and afterword",
  "editortranin": "editor, translator, annotator, and introduction",
  "editorstranin": "editors, translators, annotators, and introduction",
  "editortranfo": "editor, translator, annotator, and foreword",
  "editorstranfo": "editors, translators, annotators, and foreword",
  "editortranaf": "editor, translator, annotator, and afterword",
  "editorstranaf": "editors, translators, annotators, and afterword",
  "translatorco": "translator and commentator",
  "translatorsco": "translators and commentators",
  "translatoran": "translator and annotator",
  "translatorsan": "translators and annotators",
  "translatorin": "translation and introduction",
  "translatorsin": "translation and introduction",
  "translatorfo": "translation and foreword",
  "translatorsfo": "translation and foreword",
  "translatoraf": "translation and afterword",
  "translatorsaf": "translation and afterword",
  "translatorcoin": "translation, commentary, and introduction",
  "translatorscoin": "translation, commentary, and introduction",
  "translatorcofo": "translation, commentary, and foreword",
  "translatorscofo": "translation, commentary, and foreword",
  "translatorcoaf": "translation, commentary, and afterword",
  "translatorscoaf": "translation, commentary, and afterword",
  "translatoranin": "translation, annotations, and introduction",
  "translatorsanin": "translation, annotations, and introduction",
  "translatoranfo": "translation, annotations, and foreword",
  "translatorsanfo": "translation, annotations, and foreword",
  "translatoranaf": "translation, annotations, and afterword",
  "translatorsanaf": "translation, annotations, and afterword",
  "organizer": "organizer",
  "organizers": "organizers",
  "byorganizer": "organized by",
  "byauthor": "by",
  "byeditor": "Edited by",
  "bycompiler": "Compiled by",
  "byredactor": "Redacted by",
  "byreviser": "Revised by",
  "byreviewer": "Reviewed by",
  "byfounder": "Founded by",
  "bycontinuator": "Continued by",
  "bycollaborator": "in collaboration with",
  "bytranslator": "Translated <fromlang> by",
  "bycommentator": "Commented by",
  "byannotator": "Annotated by",
  "withcommentator": "With a commentary by",
  "withannotator": "With annotations by",
  "withintroduction": "With an introduction by",
  "withforeword": "With a foreword by",
  "withafterword": "With an afterword by",
  "byeditortr": "Edited and translated <fromlang> by",
  "byeditorco": "Edited and commented by",
  "byeditoran": "Edited and annotated by",
  "byeditorin": "edited, with an introduction, by",
  "byeditorfo": "edited, with a foreword, by",
  "byeditoraf": "edited, with an afterword, by",
  "byeditortrco": "edited, translated <fromlang>, and commented by",
  "byeditortran": "edited, translated <fromlang>, and annotated by",
  "byeditortrin": "edited and translated <fromlang>, with an introduction, by",
  "byeditortrfo": "edited and translated <fromlang>, with a foreword, by",
  "byeditortraf": "edited and translated <fromlang>, with an afterword, by",
  "byeditorcoin": "edited and commented, with an introduction, by",
  "byeditorcofo": "edited and commented, with a foreword, by",
  "byeditorcoaf": "edited and commented, with an afterword, by",
  "byeditoranin": "edited and annotated, with an introduction, by",
  "byeditoranfo": "edited and annotated, with a foreword, by",
  "byeditoranaf": "edited and annotated, with an afterword, by",
  "byeditortrcoin": "edited, translated <fromlang>, and commented, with an introduction, by",
  "byeditortrcofo": "edited, translated <fromlang>, and commented, with a foreword, by",
  "byeditortrcoaf": "edited, translated <fromlang>, and commented, with an afterword, by",
  "byeditortranin": "edited, translated <fromlang>, and annotated, with an introduction, by",
  "byeditortranfo": "edited, translated <fromlang>, and annotated, with a foreword, by",
  "byeditortranaf": "edited, translated <fromlang>, and annotated, with an afterword, by",
  "bytranslatorco": "translated <fromlang> and commented by",
  "bytranslatoran": "translated <fromlang> and annotated by",
  "bytranslatorin": "translated <fromlang>, with an introduction, by",
  "bytranslatorfo": "translated <fromlang>, with a foreword, by",
  "bytranslatoraf": "translated <fromlang>, with an afterword, by",
  "bytranslatorcoin": "translated <fromlang> and commented, with an introduction, by",
  "bytranslatorcofo": "translated <fromlang> and commented, with a foreword, by",
  "bytranslatorcoaf": "translated <fromlang> and commented, with an afterword, by",
  "bytranslatoranin": "translated <fromlang> and annotated, with an introduction, by",
  "bytranslatoranfo": "translated <fromlang> and annotated, with a foreword, by",
  "bytranslatoranaf": "translated <fromlang> and annotated, with an afterword, by",
  "and": "and",
  "andothers": "et al.",
  "andmore": "et al.",
  "volume": "Volume",
  "volumes": "volumes",
  "involumes": "In:",
  "jourvol": "volume",
  "jourser": "series",
  "book": "book",
  "part": "part",
  "issue": "issue",
  "newseries": "new series",
  "oldseries": "old series",
  "edition": "edition",
  "reprint": "reprint",
  "reprintof": "reprint of",
  "reprintas": "reprinted as",
  "reprintfrom": "reprinted from",
  "reviewof": "review of",
  "translationof": "translation of",
  "translationas": "translated as",
  "translationfrom": "translated from",
  "origpubas": "originally published as",
  "origpubin": "originally published in",
  "astitle": "as",
  "bypublisher": "by",
  "nodate": "no date",
  "page": "page",
  "pages": "pages",
  "column": "column",
  "columns": "columns",
  "line": "line",
  "lines": "lines",
  "verse": "verse",
  "verses": "verses",
  "section": "section",
  "sections": "sections",
  "paragraph": "paragraph",
  "paragraphs": "paragraphs",
  "pagetotal": "page",
  "pagetotals": "pages",
  "columntotal": "column",
  "columntotals": "columns",
  "linetotal": "line",
  "linetotals": "lines",
  "versetotal": "verse",
  "versetotals": "verses",
  "sectiontotal": "section",
  "sectiontotals": "sections",
  "paragraphtotal": "paragraph",
  "paragraphtotals": "paragraphs",
  "in": "In:",
  "inseries": "in",
  "ofseries": "of",
  "number": "number",
  "chapter": "Chapter",
  "bathesis": "Bachelor's thesis",
  "mathesis": "Master's thesis",
  "phdthesis": "PhD thesis",
  "candthesis": "Candidate thesis",
  "resreport": "research report",
  "techreport": "technical report",
  "software": "computer software",
  "datacd": "CD-ROM",
  "audiocd": "audio CD",
  "version": "version",
  "url": "address",
  "urlfrom": "available from",
  "urlseen": "visited on",
  "inpreparation": "in preparation",
  "submitted": "submitted",
  "forthcoming": "forthcoming",
  "inpress": "in press",
  "prepublished": "pre-published",
  "citedas": "henceforth cited as",
  "thiscite": "especially",
  "seenote": "see note",
  "quotedin": "quoted in",
  "idem": "idem",
  "idemsm": "idem",
  "idemsf": "eadem",
  "idemsn": "idem",
  "idempm": "eidem",
  "idempf": "eaedem",
  "idempn": "eadem",
  "idempp": "eidem",
  "ibidem": "ibidem",
  "opcit": "op.space cit.",
  "loccit": "loc.space cit.",
  "confer": "cf.",
  "sequens": "sq.",
  "sequentes": "sqq.",
  "passim": "passim",
  "see": "see",
  "seealso": "see also",
  "backrefpage": "cited on page",
  "backrefpages": "cited on pages",
  "january": "January",
  "february": "February",
  "march": "March",
  "april": "April",
  "may": "May",
  "june": "June",
  "july": "July",
  "august": "August",
  "september": "September",
  "october": "October",
  "november": "November",
  "december": "December",
  "langamerican": "American",
  "langbasque": "Basque",
  "langbrazilian": "Brazilian",
  "langbulgarian": "Bulgarian",
  "langcatalan": "Catalan",
  "langcroatian": "Croatian",
  "langczech": "Czech",
  "langdanish": "Danish",
  "langdutch": "Dutch",
  "langenglish": "English",
  "langestonian": "Estonian",
  "langfinnish": "Finnish",
  "langfrench": "French",
  "langgalician": "Galician",
  "langgerman": "German",
  "langgreek": "Greek",
  "langhungarian": "Hungarian",
  "langitalian": "Italian",
  "langjapanese": "Japanese",
  "langlatin": "Latin",
  "langlatvian": "Latvian",
  "langlithuanian": "Lithuanian",
  "langmarathi": "Marathi",
  "langnorwegian": "Norwegian",
  "langpolish": "Polish",
  "langportuguese": "Portuguese",
  "langromanian": "Romanian",
  "langrussian": "Russian",
  "langserbian": "Serbian",
  "langslovak": "Slovak",
  "langslovene": "Slovene",
  "langspanish": "Spanish",
  "langswedish": "Swedish",
  "langturkish": "Turkish",
  "langukrainian": "Ukrainian",
  "fromamerican": "from the American",
  "frombasque": "from the Basque",
  "frombrazilian": "from the Brazilian",
  "frombulgarian": "from the Bulgarian",
  "fromcatalan": "from the Catalan",
  "fromcroatian": "from the Croatian",
  "fromczech": "from the Czech",
  "fromdanish": "from the Danish",
  "fromdutch": "from the Dutch",
  "fromenglish": "from the English",
  "fromestonian": "from the Estonian",
  "fromfinnish": "from the Finnish",
  "fromfrench": "from the French",
  "fromgalician": "from the Galician",
  "fromgerman": "from the German",
  "fromgreek": "from the Greek",
  "fromhungarian": "from the Hungarian",
  "fromitalian": "from the Italian",
  "fromjapanese": "from the Japanese",
  "fromlatin": "from the Latin",
  "fromlatvian": "from the Latvian",
  "fromlithuanian": "from the Lithuanian",
  "frommarathi": "from the Marathi",
  "fromnorwegian": "from the Norwegian",
  "frompolish": "from the Polish",
  "fromportuguese": "from the Portuguese",
  "fromromanian": "from the Romanian",
  "fromrussian": "from the Russian",
  "fromserbian": "from the Serbian",
  "fromslovak": "from the Slovak",
  "fromslovene": "from the Slovene",
  "fromspanish": "from the Spanish",
  "fromswedish": "from the Swedish",
  "fromturkish": "from the Turkish",
  "fromukrainian": "from the Ukrainian",
  "countryde": "Germany",
  "countryeu": "European Union",
  "countryep": "European Union",
  "countryfr": "France",
  "countryuk": "United Kingdom",
  "countryus": "United States of America",
  "patent": "patent",
  "patentde": "German patent",
  "patenteu": "European patent",
  "patentfr": "French patent",
  "patentuk": "British patent",
  "patentus": "U.S.space patent",
  "patreq": "patent request",
  "patreqde": "German patent request",
  "patreqeu": "European patent request",
  "patreqfr": "French patent request",
  "patrequk": "British patent request",
  "patrequs": "U.S.space patent request",
  "file": "file",
  "library": "library",
  "abstract": "abstract",
  "annotation": "annotations",
  "commonera": "Common Era",
  "beforecommonera": "Before Common Era",
  "annodomini": "Anno Domini",
  "beforechrist": "Before Christ",
  "circa": "circa",
  "spring": "Spring",
  "summer": "Summer",
  "autumn": "Autumn",
  "winter": "Winter",
  "springN": "Spring (Northern Hemisphere)",
  "summerN": "Summer (Northern Hemisphere)",
  "autumnN": "Autumn (Northern Hemisphere)",
  "winterN": "Winter (Northern Hemisphere)",
  "springS": "Spring (Southern Hemisphere)",
  "summerS": "Summer (Southern Hemisphere)",
  "autumnS": "Autumn (Southern Hemisphere)",
  "winterS": "Winter (Southern Hemisphere)",
  "Q1": "Quarter~1",
  "Q2": "Quarter~2",
  "Q3": "Quarter~3",
  "Q4": "Quarter~4",
  "QD1": "Quadrimester~1",
  "QD2": "Quadrimester~2",
  "QD3": "Quadrimester~3",
  "S1": "Semestral~1",
  "S2": "Semestral~2",
  "am": "AM",
  "pm": "PM",
)

/// The default short bibstring table.
/// 
/// It is similar to the "long" bibstring table in @default-long-bibstring, except
/// that it contains the "short" bibstrings. That is, references will be typeset to
/// print e.g. "Jones, ed." rather than "Jones, editor".
#let default-short-bibstring = (
  "bibliography": "Bibliography",
  "references": "References",
  "shorthands": "Abbreviations",
  "editor": "ed.",
  "editors": "eds.",
  "compiler": "comp.",
  "compilers": "comp.",
  "redactor": "red.",
  "redactors": "red.",
  "reviser": "rev.",
  "revisers": "rev.",
  "founder": "found.",
  "founders": "found.",
  "continuator": "cont.",
  "continuators": "cont.",
  "collaborator": "collab.",
  "collaborators": "collab.",
  "translator": "trans.",
  "translators": "trans.",
  "commentator": "comm.",
  "commentators": "comm.",
  "annotator": "annot.",
  "annotators": "annot.",
  "commentary": "comm.",
  "annotations": "annot.",
  "introduction": "intro.",
  "foreword": "forew.",
  "afterword": "afterw.",
  "editortr": "ed. and trans.",
  "editorstr": "eds. and trans.",
  "editorco": "ed. and comm.",
  "editorsco": "eds. and comm.",
  "editoran": "ed. and annot.",
  "editorsan": "eds. and annot.",
  "editorin": "ed. and introd.",
  "editorsin": "eds. and introd.",
  "editorfo": "ed. and forew.",
  "editorsfo": "eds. and forew.",
  "editoraf": "ed. and afterw.",
  "editorsaf": "eds. and afterw.",
  "editortrco": "ed., trans. and comm.",
  "editorstrco": "eds., trans. and comm.",
  "editortran": "ed., trans. and annot.",
  "editorstran": "eds., trans. and annot.",
  "editortrin": "ed., trans. and introd.",
  "editorstrin": "eds., trans. and introd.",
  "editortrfo": "ed., trans. and forew.",
  "editorstrfo": "eds., trans. and forew.",
  "editortraf": "ed., trans. and afterw.",
  "editorstraf": "eds., trans. and afterw.",
  "editorcoin": "ed., comm. and introd.",
  "editorscoin": "eds., comm. and introd.",
  "editorcofo": "ed., comm. and forew.",
  "editorscofo": "eds., comm. and forew.",
  "editorcoaf": "ed., comm. and afterw.",
  "editorscoaf": "eds., comm. and afterw.",
  "editoranin": "ed., annot. and introd.",
  "editorsanin": "eds., annot. and introd.",
  "editoranfo": "ed., annot. and forew.",
  "editorsanfo": "eds., annot. and forew.",
  "editoranaf": "ed., annot. and afterw.",
  "editorsanaf": "eds., annot. and afterw.",
  "editortrcoin": "ed., trans., comm. and introd.",
  "editorstrcoin": "eds., trans., comm. and introd.",
  "editortrcofo": "ed., trans., comm. and forew.",
  "editorstrcofo": "eds., trans., comm. and forew.",
  "editortrcoaf": "ed., trans., comm. and afterw.",
  "editorstrcoaf": "eds., trans., comm. and afterw.",
  "editortranin": "ed., trans., annot. and introd.",
  "editorstranin": "eds., trans., annot. and introd.",
  "editortranfo": "ed., trans., annot. and forew.",
  "editorstranfo": "eds., trans., annot. and forew.",
  "editortranaf": "ed., trans., annot. and afterw.",
  "editorstranaf": "eds., trans., annot. and afterw.",
  "translatorco": "trans. and comm.",
  "translatorsco": "trans. and comm.",
  "translatoran": "trans. and annot.",
  "translatorsan": "trans. and annot.",
  "translatorin": "trans. and introd.",
  "translatorsin": "trans. and introd.",
  "translatorfo": "trans. and forew.",
  "translatorsfo": "trans. and forew.",
  "translatoraf": "trans. and afterw.",
  "translatorsaf": "trans. and afterw.",
  "translatorcoin": "trans., comm. and introd.",
  "translatorscoin": "trans., comm. and introd.",
  "translatorcofo": "trans., comm. and forew.",
  "translatorscofo": "trans., comm. and forew.",
  "translatorcoaf": "trans., comm. and afterw.",
  "translatorscoaf": "trans., comm. and afterw.",
  "translatoranin": "trans., annot. and introd.",
  "translatorsanin": "trans., annot. and introd.",
  "translatoranfo": "trans., annot. and forew.",
  "translatorsanfo": "trans., annot. and forew.",
  "translatoranaf": "trans., annot. and afterw.",
  "translatorsanaf": "trans., annot. and afterw.",
  "organizer": "org.",
  "organizers": "orgs.",
  "byorganizer": "org. by",
  "byauthor": "by",
  "byeditor": "ed. by",
  "bycompiler": "comp. by",
  "byredactor": "red. by",
  "byreviser": "rev. by",
  "byreviewer": "rev. by",
  "byfounder": "found. by",
  "bycontinuator": "cont. by",
  "bycollaborator": "in collab. with",
  "bytranslator": "trans. by",
  "bycommentator": "comm. by",
  "byannotator": "annot. by",
  "withcommentator": "with a comment. by",
  "withannotator": "with annots. by",
  "withintroduction": "with an intro. by",
  "withforeword": "with a forew. by",
  "withafterword": "with an afterw. by",
  "byeditortr": "ed. and trans. by",
  "byeditorco": "ed. and comm. by",
  "byeditoran": "ed. and annot. by",
  "byeditorin": "ed., with an introd., by",
  "byeditorfo": "ed., with a forew., by",
  "byeditoraf": "ed., with an afterw., by",
  "byeditortrco": "ed., trans. and comm. by",
  "byeditortran": "ed., trans. and annot. by",
  "byeditortrin": "ed. and trans., with an introd., by",
  "byeditortrfo": "ed. and trans., with a forew., by",
  "byeditortraf": "ed. and trans., with an afterw., by",
  "byeditorcoin": "ed. and comm., with an introd., by",
  "byeditorcofo": "ed. and comm., with a forew., by",
  "byeditorcoaf": "ed. and comm., with an afterw., by",
  "byeditoranin": "ed. and annot., with an introd., by",
  "byeditoranfo": "ed. and annot., with a forew., by",
  "byeditoranaf": "ed. and annot., with an afterw., by",
  "byeditortrcoin": "ed., trans. and comm., with an introd., by",
  "byeditortrcofo": "ed., trans. and comm., with a forew., by",
  "byeditortrcoaf": "ed., trans. and comm., with an afterw., by",
  "byeditortranin": "ed., trans. and annot., with an introd., by",
  "byeditortranfo": "ed., trans. and annot., with a forew., by",
  "byeditortranaf": "ed., trans. and annot., with an afterw., by",
  "bytranslatorco": "trans. and comm. by",
  "bytranslatoran": "trans. and annot. by",
  "bytranslatorin": "trans., with an introd., by",
  "bytranslatorfo": "trans., with a forew., by",
  "bytranslatoraf": "trans., with an afterw., by",
  "bytranslatorcoin": "trans. and comm., with an introd., by",
  "bytranslatorcofo": "trans. and comm., with a forew., by",
  "bytranslatorcoaf": "trans. and comm., with an afterw., by",
  "bytranslatoranin": "trans. and annot., with an introd., by",
  "bytranslatoranfo": "trans. and annot., with a forew., by",
  "bytranslatoranaf": "trans. and annot., with an afterw., by",
  "and": "and",
  "andothers": "et al.",
  "andmore": "et al.",
  "volume": "vol.",
  "volumes": "vols.",
  "involumes": "in",
  "jourvol": "vol.",
  "jourser": "ser.",
  "book": "book",
  "part": "part",
  "issue": "issue",
  "newseries": "new ser.",
  "oldseries": "old ser.",
  "edition": "ed.",
  "reprint": "repr.",
  "reprintof": "repr. of",
  "reprintas": "rpt. as",
  "reprintfrom": "repr. from",
  "reviewof": "rev. of",
  "translationof": "trans. of",
  "translationas": "trans. as",
  "translationfrom": "trans. from",
  "origpubas": "orig. pub. as",
  "origpubin": "orig. pub. in",
  "astitle": "as",
  "bypublisher": "by",
  "nodate": "n.d.",
  "page": "p.",
  "pages": "pp.",
  "column": "col.",
  "columns": "cols.",
  "line": "l.",
  "lines": "ll.",
  "verse": "v.",
  "verses": "vv.",
  "section": "§",
  "sections": "§§",
  "paragraph": "par.",
  "paragraphs": "par.",
  "pagetotal": "p.",
  "pagetotals": "pp.",
  "columntotal": "col.",
  "columntotals": "cols.",
  "linetotal": "l.",
  "linetotals": "ll.",
  "versetotal": "v.",
  "versetotals": "vv.",
  "sectiontotal": "§",
  "sectiontotals": "§§",
  "paragraphtotal": "par.",
  "paragraphtotals": "par.",
  "in": "in",
  "inseries": "in",
  "ofseries": "of",
  "number": "no.",
  "chapter": "chap.",
  "bathesis": "BA thesis",
  "mathesis": "MA thesis",
  "phdthesis": "PhD thesis",
  "candthesis": "Cand. thesis",
  "resreport": "research rep.",
  "techreport": "tech. rep.",
  "software": "comp. software",
  "datacd": "CD-ROM",
  "audiocd": "audio CD",
  "version": "version",
  "url": "address",
  "urlfrom": "available from",
  "urlseen": "visited on",
  "inpreparation": "in preparation",
  "submitted": "submitted",
  "forthcoming": "forthcoming",
  "inpress": "in press",
  "prepublished": "pre-published",
  "citedas": "henceforth cited as",
  "thiscite": "esp.",
  "seenote": "see n.",
  "quotedin": "qtd. in",
  "idem": "idem",
  "idemsm": "idem",
  "idemsf": "eadem",
  "idemsn": "idem",
  "idempm": "eidem",
  "idempf": "eaedem",
  "idempn": "eadem",
  "idempp": "eidem",
  "ibidem": "ibid.",
  "opcit": "op. cit.",
  "loccit": "loc. cit.",
  "confer": "cf.",
  "sequens": "sq.",
  "sequentes": "sqq.",
  "passim": "pass.",
  "see": "see",
  "seealso": "see also",
  "backrefpage": "cit. on p.",
  "backrefpages": "cit. on pp.",
  "january": "Jan.",
  "february": "Feb.",
  "march": "Mar.",
  "april": "Apr.",
  "may": "May",
  "june": "June",
  "july": "July",
  "august": "Aug.",
  "september": "Sept.",
  "october": "Oct.",
  "november": "Nov.",
  "december": "Dec.",
  "langamerican": "American",
  "langbasque": "Basque",
  "langbrazilian": "Brazilian",
  "langbulgarian": "Bulgarian",
  "langcatalan": "Catalan",
  "langcroatian": "Croatian",
  "langczech": "Czech",
  "langdanish": "Danish",
  "langdutch": "Dutch",
  "langenglish": "English",
  "langestonian": "Estonian",
  "langfinnish": "Finnish",
  "langfrench": "French",
  "langgalician": "Galician",
  "langgerman": "German",
  "langgreek": "Greek",
  "langhungarian": "Hungarian",
  "langitalian": "Italian",
  "langjapanese": "Japanese",
  "langlatin": "Latin",
  "langlatvian": "Latvian",
  "langlithuanian": "Lithuanian",
  "langmarathi": "Marathi",
  "langnorwegian": "Norwegian",
  "langpolish": "Polish",
  "langportuguese": "Portuguese",
  "langromanian": "Romanian",
  "langrussian": "Russian",
  "langserbian": "Serbian",
  "langslovak": "Slovak",
  "langslovene": "Slovene",
  "langspanish": "Spanish",
  "langswedish": "Swedish",
  "langturkish": "Turkish",
  "langukrainian": "Ukrainian",
  "fromamerican": "from the American",
  "frombasque": "from the Basque",
  "frombrazilian": "from the Brazilian",
  "frombulgarian": "from the Bulgarian",
  "fromcatalan": "from the Catalan",
  "fromcroatian": "from the Croatian",
  "fromczech": "from the Czech",
  "fromdanish": "from the Danish",
  "fromdutch": "from the Dutch",
  "fromenglish": "from the English",
  "fromestonian": "from the Estonian",
  "fromfinnish": "from the Finnish",
  "fromfrench": "from the French",
  "fromgalician": "from the Galician",
  "fromgerman": "from the German",
  "fromgreek": "from the Greek",
  "fromhungarian": "from the Hungarian",
  "fromitalian": "from the Italian",
  "fromjapanese": "from the Japanese",
  "fromlatin": "from the Latin",
  "fromlatvian": "from the Latvian",
  "fromlithuanian": "from the Lithuanian",
  "frommarathi": "from the Marathi",
  "fromnorwegian": "from the Norwegian",
  "frompolish": "from the Polish",
  "fromportuguese": "from the Portuguese",
  "fromromanian": "from the Romanian",
  "fromrussian": "from the Russian",
  "fromserbian": "from the Serbian",
  "fromslovak": "from the Slovak",
  "fromslovene": "from the Slovene",
  "fromspanish": "from the Spanish",
  "fromswedish": "from the Swedish",
  "fromturkish": "from the Turkish",
  "fromukrainian": "from the Ukrainian",
  "countryde": "DE",
  "countryeu": "EU",
  "countryep": "EP",
  "countryfr": "FR",
  "countryuk": "GB",
  "countryus": "US",
  "patent": "pat.",
  "patentde": "German pat.",
  "patenteu": "European pat.",
  "patentfr": "French pat.",
  "patentuk": "British pat.",
  "patentus": "U.S. pat.",
  "patreq": "pat. req.",
  "patreqde": "German pat. req.",
  "patreqeu": "European pat. req.",
  "patreqfr": "French pat. req.",
  "patrequk": "British pat. req.",
  "patrequs": "U.S. pat. req.",
  "file": "file",
  "library": "library",
  "abstract": "abstract",
  "annotation": "annotations",
  "commonera": "CE",
  "beforecommonera": "BCE",
  "annodomini": "AD",
  "beforechrist": "BC",
  "circa": "ca.",
  "spring": "Spr.",
  "summer": "Sum.",
  "autumn": "Aut.",
  "winter": "Win.",
  "springN": "Spr. NH",
  "summerN": "Sum. NH",
  "autumnN": "Aut. NH",
  "winterN": "Win. NH",
  "springS": "Spr. SH",
  "summerS": "Sum. SH",
  "autumnS": "Aut. SH",
  "winterS": "Win. SH",
  "Q1": "Q1",
  "Q2": "Q2",
  "Q3": "Q3",
  "Q4": "Q4",
  "QD1": "Q1",
  "QD2": "Q2",
  "QD3": "Q3",
  "S1": "S1",
  "S2": "S2",
  "am": "AM",
  "pm": "PM",
)

