[package]
name = "keyle"
version = "0.3.0"
authors = ["wesleyel <yxnian@outlook.com>"]
license = "MIT"
description = "This package provides a simple way to style keyboard shortcuts in your documentation."
repository = "https://github.com/wesleyel/keyle"

compiler = "0.13.0"
entrypoint = "src/keyle.typ"
keywords = ["kbd", "keyboard", "shortcut"]
categories = ["utility", "fun"]

exclude = ["*.pdf", "test/**", "doc/**", "example/**"]