[package]
name = "shuimu-touying-zen"
version = "0.1.0"
entrypoint = "theme.typ"
authors = [ "Chenyang Wang <https://github.com/Chenyang-Wang-1999>" ]
license = "MIT"
description = "A Touying template for THU physics presentations."
keywords = ["slides", "presentation", "touying", "PPT", "THU", "Tsinghua University"]
categories = ["presentation"]
exclude = [ "/gallery/*", "/tools/*" ]
