[package]
name = "case-paper-projeto"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Sivaldo Davi Pereira"]
license = "MIT"
description = "Templates para case, paper e projetos acadêmicos em Typst."
repository = "https://github.com/sivas-lab/case-paper-projeto.typ"
keywords = ["template", "academic", "paper"]
categories = ["report", "office"]
