#let i18n = (
  en: (
    date: "Date",
    eval: "Evaluation",
    exam: "Exam",
    fig: "Fig.",
    ho: "handed out",
    item: "Item",
    lab: "Lab",
    lc: "last changed",
    mark: "Mark",
    of: "of",
    on: "on",
    page: "Page",
    poi: "Points",
    sol: "solution",
    subtask: "subtask",
    tab: "Tab.",
    task: "Task",
    with: "with",
  ),
  de: (
    date: "Datum",
    eval: "Bewertung",
    exam: "Klausur",
    fig: "Abb.",
    ho: "ausgegeben von",
    item: "Element",
    lab: "Labor",
    lc: "zuletzt geändert",
    mark: "Note",
    of: "von",
    on: "am",
    page: "Seite",
    poi: "Punkte",
    sol: "Lösung",
    subtask: "Aufgabe",
    tab: "Tab.",
    task: "Aufgabe",
    with: "mit",
  )
)

#let months = (
  "Januar",
  "Februar",
  "März",
  "April",
  "Mai",
  "Juni",
  "Juli",
  "August",
  "September",
  "Oktober",
  "November",
  "Dezember",
)
