/// Default symbol styling dictionary
#let default = (
    variant: "iec",
    scale: (x: 1.0, y: 1.0),
    stroke: .8pt,
    fill: none,
    background: white,
    foreground: black,
    label: (
        scale: auto,
        content: none,
        distance: 7pt,
        anchor: "north",
    ),
    node: (
        stroke: .65pt,
        fill: black,
        nofill: white,
        radius: .06,
    ),
    wire: (
        stroke: .6pt,
    ),
    arrow: (
        symbol: ">",
        scale: 1.0,
        angle: 55deg,
        length: 40pt,
        ratio: (0.5, 0.5),
        stroke: 1pt,
        variable: (
            symbol: auto,
            scale: 1.0,
            stroke: auto,
            length: auto,
            angle: auto,
            ratio: auto,
        ),
        preset: (
            symbol: "|",
            scale: 1.0,
            stroke: auto,
            length: auto,
            angle: auto,
            ratio: auto,
            width: 10pt,
        ),
        sensor: (
            symbol: none,
            scale: 1.0,
            stroke: auto,
            length: auto,
            sensor-length: 12pt,
            angle: auto,
            ratio: auto,
        ),
        radiation: (
            symbol: auto,
            scale: 1,
            stroke: 0.55pt,
            distance: 3pt,
            length: 12pt,
            angle: -120deg,
            reversed: false,
        ),
        adjustable: (
            symbol: auto,
            scale: 1.0,
            stroke: auto,
            length: 0.8,
        ),
    ),
    decoration: (
        symbol: ">",
        scale: 1.0,
        stroke: .6pt,
        content: none,
        distance: 9pt,
        position: (x: "east", y: "north"),
        anchor: "north-east",
        invert: false,
        current: (
            symbol: auto,
            scale: 1.0,
            stroke: auto,
            content: auto,
            distance: auto,
            position: auto,
            anchor: auto,
            invert: auto,
            wire: (
                symbol: auto,
                scale: auto,
                stroke: auto,
                content: auto,
                distance: 7pt,
                position: 50%,
                anchor: "north",
                invert: auto,
            ),
        ),
        flow: (
            symbol: auto,
            scale: 1.0,
            stroke: 0.55pt,
            content: auto,
            distance: auto,
            position: auto,
            anchor: auto,
            invert: auto,
            length: 0.7,
            indent: 0.2,
            label-ratio: 50%,
        ),
        voltage: (
            symbol: auto,
            scale: 1.0,
            stroke: auto,
            content: auto,
            distance: 2pt,
            position: auto,
            anchor: auto,
            invert: auto,
            start: (-.4, .1),
            end: (.4, .1),
            center: (0, .3),
            shape: "curved",
        ),
    ),
    debug: (
        stroke: .2pt + red,
        enabled: false,
        radius: .7pt,
        angle: -30deg,
        shift: 3pt,
        inset: 1pt,
        font: 3pt,
        fill: red,
    ),
    invert: (
        radius: .09,
        wedge-width: 0.2,
        wedge-height: 0.15,
        stroke: .8pt,
    ),
    sign: (
        stroke: .65pt,
        width: 20pt,
        height: 8pt,
        size: .14,
    ),
    // Components
    stub: (
        scale: auto,
        length: .8,
    ),
    capacitor: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: .8,
        distance: .25,
        radius: 0.6,
        angle: 40deg,
    ),
    diode: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: .3,
        width: .25,
        tunnel-length: .11,
    ),
    opamp: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 1.8,
        height: 1.75,
        padding: .28,
        sign-stroke: .55pt,
        sign-size: .14,
        sign-delta: .45,
        label: (
            anchor: "label",
            align: "east",
            distance: 0,
        ),
    ),
    lamp: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: 8pt,
    ),
    switch: (
        variant: auto,
        scale: auto,
        stroke: auto,
        width: .8,
        angle: 35deg,
    ),
    fuse: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: .88,
        height: .88 / 2.4,
        asymmetry: 25%,
    ),
    ground: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: 0.22,
        distance: 0.28,
    ),
    rground: (
        variant: auto,
        scale: auto,
        stroke: auto,
        width: .53,
        distance: .28,
    ),
    frame: (
        variant: auto,
        scale: auto,
        stroke: auto,
        number: 3,
        width: 0.46,
        angle: 20deg,
        depth: 0.25,
        distance: 0.28,
    ),
    earth: (
        variant: auto,
        scale: auto,
        stroke: auto,
        width: .53,
        delta: .09,
        spacing: .11,
        distance: .28,
    ),
    vcc: (
        variant: auto,
        scale: auto,
        stroke: auto,
        angle: 35deg,
        radius: .4,
        distance: .6,
    ),
    vee: (
        variant: auto,
        scale: auto,
        stroke: auto,
        angle: 35deg,
        radius: .4,
        distance: .6,
        label: (
            anchor: "south",
            align: "north",
        ),
    ),
    inductor: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 1.65,
        height: 1.65 / 4,
        bumps: 4,
    ),
    resistor: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 1.41,
        height: .47,
        zigs: 3,
    ),
    vsource: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: .53,
        padding: .25,
        sign: (
            stroke: auto,
            size: .14,
            delta: .07,
        ),
    ),
    isource: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: .53,
        padding: .25,
        arrow-scale: 1,
    ),
    battery: (
        variant: auto,
        scale: auto,
        stroke: auto,
        distance: .18,
        plus-width: 1,
        minus-width: .5,
        polarity: (
            padding: (.15, .1),
            side: 1,
        ),
        multi: (
            distance: 0.7,
            number: 5,
        ),
    ),
    acmotor: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: .58,
    ),
    dcmotor: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: .58,
    ),
    bjt: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: .65,
        base-height: .6,
        base-distance: .12,
        aperture: 50deg,
    ),
    mosfet: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        height: 0.7,
        width: 1,
        base-width: 1.2,
        base-spacing: 0.16,
        base-distance: 0.16,
        radius: 0.85,
    ),
    jfet: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        height: 0.7,
        width: 1,
        base-width: 1.2,
        base-spacing: 0.16,
        base-distance: 0.16,
        radius: 0.85,
    ),
    antenna: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: none,
        number: 3,
        distance: 0.8,
        spacing: 0.35,
        length: 0.5,
    ),
    transformer: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: 0.35,
        distance: 0.45,
    ),
    converter: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 1.7,
        height: 0.7,
        arrow-width: 0.4,
        label: (
            align: "center",
            anchor: "label",
        ),
    ),
    mcu: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 3,
        min-height: 1,
        padding: 0.2,
        spacing: 0.4,
    ),
    round-meter: (
        variant: auto,
        scale: auto,
        stroke: auto,
        radius: .47,
    ),
    button: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: .8,
        angle: 23deg,
        overlap: .1,
        distance: .7,
        lamp-distance: .12,
        button-width: .33,
        button-height: .16,
        button-omega: 1,
        latch-size: 0.1,
        latch-padding: 0.15,
    ),
    circulator: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: 0.53,
        arrow-radius: 0.35,
    ),
    piezo: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 0.4,
        height: 0.7,
        spacing: 0.15,
    ),
    logic: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 0.95,
        min-height: 0.85,
        padding: 0.2,
        xor-spacing: 0.13,
        spacing: .4,
    ),
    flipflop: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 1.8,
        height: 2,
        padding: 0.2,
        spacing: 0.5,
    ),
)
