#let black = rgb("#000000")

// greys and their synonyms
#let silver = rgb("#c0c0c0")
#let gray = rgb("#808080")
#let grey = rgb("#808080")
#let darkgray = rgb("#a9a9a9")
#let darkgrey = rgb("#a9a9a9")
#let dimgray = rgb("#696969")
#let lightgray = rgb("#d3d3d3")
#let lightgrey = rgb("#d3d3d3")
#let slategray = rgb("#708090")
#let slategrey = rgb("#708090")
#let dimgrey = rgb("#696969")
#let lightslategrey = rgb("#778899")
#let lightslategray = rgb("#778899")
#let darkslategray = rgb("#2f4f4f")
#let darkslategrey = rgb("#2f4f4f")

// whites
#let white = rgb("#ffffff")
#let antiquewhite = rgb("#faebd7")
#let floralwhite = rgb("#fffaf0")
#let ghostwhite = rgb("#f8f8ff")
#let navajowhite = rgb("#ffdead")
#let whitesmoke = rgb("#f5f5f5")

// reds
#let red = rgb("#ff0000")
#let darkred = rgb("#8b0000")
#let indianred = rgb("#cd5c5c")
#let crimson = rgb("#dc143c")
#let mediumvioletred = rgb("#c71585")
#let orangered = rgb("#ff4500")
#let palevioletred = rgb("#db7093")
#let maroon = rgb("#800000")

// purples
#let purple = rgb("#800080")
#let mediumpurple = rgb("#9370db")
#let purple = rgb("#800080")
#let rebeccapurple = rgb("#663399")
#let fuchsia = rgb("#ff00ff")

// greens
#let green = rgb("#008000")
#let darkgreen = rgb("#006400")
#let darkolivegreen = rgb("#556b2f")
#let darkseagreen = rgb("#8fbc8f")
#let forestgreen = rgb("#228b22")
#let lime = rgb("#00ff00")
#let olive = rgb("#808000")
#let olivedrab = rgb("#6b8e23")
#let greenyellow = rgb("#adff2f")
#let lawngreen = rgb("#7cfc00")
#let lightgreen = rgb("#90ee90")
#let lightseagreen = rgb("#20b2aa")
#let limegreen = rgb("#32cd32")
#let mediumseagreen = rgb("#3cb371")
#let mediumspringgreen = rgb("#00fa9a")
#let palegreen = rgb("#98fb98")
#let seagreen = rgb("#2e8b57")
#let springgreen = rgb("#00ff7f")
#let yellowgreen = rgb("#9acd32")

// yellows
#let yellow = rgb("#ffff00")
#let gold = rgb("#ffd700")
#let lightgoldenrodyellow = rgb("#fafad2")
#let lightyellow = rgb("#ffffe0")

// blues
#let blue = rgb("#0000ff")
#let mediumblue = rgb("#0000cd")
#let royalblue = rgb("#4169e1")
#let darkblue = rgb("#00008b")
#let navy = rgb("#000080")
#let lightblue = rgb("#add8e6")
#let cyan = rgb("#00ffff") // synonym of aqua
#let aqua = rgb("#00ffff")
#let skyblue = rgb("#87ceeb")
#let steelblue = rgb("#4682b4")
#let lightskyblue = rgb("#87cefa")
#let lightsteelblue = rgb("#b0c4de")
#let mediumslateblue = rgb("#7b68ee")
#let deepskyblue = rgb("#00bfff")
#let darkslateblue = rgb("#483d8b")
#let slateblue = rgb("#6a5acd")
#let midnightblue = rgb("#191970")
#let powderblue = rgb("#b0e0e6")
#let aliceblue = rgb("#f0f8ff")
#let blueviolet = rgb("#8a2be2")
#let cadetblue = rgb("#5f9ea0")
#let cornflowerblue = rgb("#6495ed")
#let dodgerblue = rgb("#1e90ff")

// other colors
#let pink = rgb("#ffc0cb")
#let magenta = rgb("#ff00ff") // synonym of fuchsia
#let teal = rgb("#008080")
#let aquamarine = rgb("#7fffd4")
#let azure = rgb("#f0ffff")
#let beige = rgb("#f5f5dc")
#let bisque = rgb("#ffe4c4")
#let blanchedalmond = rgb("#ffebcd")
#let brown = rgb("#a52a2a")
#let burlywood = rgb("#deb887")
#let chartreuse = rgb("#7fff00")
#let chocolate = rgb("#d2691e")
#let coral = rgb("#ff7f50")
#let cornsilk = rgb("#fff8dc")
#let darkcyan = rgb("#008b8b")
#let darkgoldenrod = rgb("#b8860b")
#let darkkhaki = rgb("#bdb76b")
#let darkmagenta = rgb("#8b008b")
#let darkorange = rgb("#ff8c00")
#let darkorchid = rgb("#9932cc")
#let darksalmon = rgb("#e9967a")
#let darkturquoise = rgb("#00ced1")
#let darkviolet = rgb("#9400d3")
#let deeppink = rgb("#ff1493")
#let firebrick = rgb("#b22222")
#let gainsboro = rgb("#dcdcdc")
#let goldenrod = rgb("#daa520")
#let honeydew = rgb("#f0fff0")
#let hotpink = rgb("#ff69b4")
#let indigo = rgb("#4b0082")
#let ivory = rgb("#fffff0")
#let khaki = rgb("#f0e68c")
#let lavender = rgb("#e6e6fa")
#let lavenderblush = rgb("#fff0f5")
#let lemonchiffon = rgb("#fffacd")
#let lightcoral = rgb("#f08080")
#let lightcyan = rgb("#e0ffff")
#let lightpink = rgb("#ffb6c1")
#let lightsalmon = rgb("#ffa07a")
#let linen = rgb("#faf0e6")
#let mediumaquamarine = rgb("#66cdaa")
#let mediumorchid = rgb("#ba55d3")
#let mediumturquoise = rgb("#48d1cc")
#let mintcream = rgb("#f5fffa")
#let mistyrose = rgb("#ffe4e1")
#let moccasin = rgb("#ffe4b5")
#let oldlace = rgb("#fdf5e6")
#let orange = rgb("#ffa500")
#let orchid = rgb("#da70d6")
#let palegoldenrod = rgb("#eee8aa")
#let paleturquoise = rgb("#afeeee")
#let papayawhip = rgb("#ffefd5")
#let peachpuff = rgb("#ffdab9")
#let peru = rgb("#cd853f")
#let plum = rgb("#dda0dd")
#let rosybrown = rgb("#bc8f8f")
#let saddlebrown = rgb("#8b4513")
#let salmon = rgb("#fa8072")
#let sandybrown = rgb("#f4a460")
#let seashell = rgb("#fff5ee")
#let sienna = rgb("#a0522d")
#let snow = rgb("#fffafa")
#let tan = rgb("#d2b48c")
#let thistle = rgb("#d8bfd8")
#let tomato = rgb("#ff6347")
#let turquoise = rgb("#40e0d0")
#let violet = rgb("#ee82ee")
#let wheat = rgb("#f5deb3")
