/**
 * This file was generated by an LLM and then manually edited.
 *
 * - Clicking any element with a title attribute shows a tooltip.
 * - If the target is inside a `<summary>`, do not toggle the related `<details>` when the target itself is clicked; toggle only when other parts are clicked. However, if the `[title]` element is a link, it must remain navigable.
 */

const AUTO_HIDE_MS = 5000; // Auto hide time
let activeEl = null;
let hideTimer = null;
let isVisible = false;

// Create the global tooltip
const tooltip = document.createElement("div");
tooltip.id = "click-title-tooltip";
Object.assign(tooltip.style, {
  position: "fixed",
  zIndex: "2147483647",
  maxWidth: "320px",
  padding: "8px 10px",
  background: "rgba(0,0,0,0.85)",
  color: "#fff",
  fontSize: "12px",
  lineHeight: "1.3",
  borderRadius: "6px",
  boxShadow: "0 4px 16px rgba(0,0,0,0.25)",
  opacity: "0",
  transition: "opacity 120ms ease",
  pointerEvents: "none",
  display: "none",
  whiteSpace: "normal",
  wordBreak: "break-word",
});
tooltip.setAttribute("role", "tooltip");
document.addEventListener(
  "DOMContentLoaded",
  () => document.body.appendChild(tooltip),
);
if (document.readyState !== "loading" && !tooltip.isConnected) {
  document.body.appendChild(tooltip);
}

function clearHideTimer() {
  if (hideTimer) {
    clearTimeout(hideTimer);
    hideTimer = null;
  }
}

function restoreTitle(el) {
  if (!el) return;
  const orig = el.getAttribute("data-original-title");
  if (orig !== null) {
    el.setAttribute("title", orig);
  }
}

function hideTooltip() {
  if (!isVisible) return;
  isVisible = false;
  tooltip.style.opacity = "0";
  if (activeEl) restoreTitle(activeEl);
  activeEl = null;
  clearHideTimer();
  // Hide after animation ends
  setTimeout(() => {
    if (!isVisible) tooltip.style.display = "none";
  }, 140);
}

function positionTooltip(el) {
  const rect = el.getBoundingClientRect();
  const gap = 8;
  const vw = Math.max(
    document.documentElement.clientWidth,
    window.innerWidth || 0,
  );
  const vh = Math.max(
    document.documentElement.clientHeight,
    window.innerHeight || 0,
  );

  // Pre-layout measurement
  tooltip.style.left = "0px";
  tooltip.style.top = "-9999px";
  tooltip.style.display = "block";
  const ttRect = tooltip.getBoundingClientRect();

  // Default below, if not enough space then above
  let top = rect.bottom + gap;
  if (top + ttRect.height > vh && rect.top - gap - ttRect.height >= 0) {
    top = rect.top - gap - ttRect.height;
  }

  let left = rect.left + rect.width / 2 - ttRect.width / 2;
  left = Math.max(8, Math.min(left, vw - ttRect.width - 8));

  tooltip.style.left = `${Math.round(left)}px`;
  tooltip.style.top = `${Math.round(top)}px`;
}

function showTooltip(el) {
  if (!el) return;
  // Get and cache original title to avoid native tooltip interference
  let orig = el.getAttribute("data-original-title");
  if (orig === null) {
    orig = el.getAttribute("title") || "";
    el.setAttribute("data-original-title", orig);
  }
  const text = (orig || "").trim();
  if (!text) {
    hideTooltip();
    return;
  }

  // If the current element is clicked again, toggle hide
  if (isVisible && activeEl === el) {
    hideTooltip();
    return;
  }

  clearHideTimer();

  if (activeEl) restoreTitle(activeEl);
  activeEl = el;

  // Temporarily clear title to avoid native tooltip
  el.setAttribute("title", "");

  tooltip.textContent = text;
  positionTooltip(el);

  tooltip.style.display = "block";
  // Ensure transition in the next frame
  requestAnimationFrame(() => {
    isVisible = true;
    tooltip.style.opacity = "1";
  });

  // Auto hide
  hideTimer = setTimeout(() => {
    hideTooltip();
  }, AUTO_HIDE_MS);
}

// Event delegation: show tooltip when clicking elements with title
document.addEventListener("click", (e) => {
  const target = e.target.closest("[title]");
  const summary = e.target.closest("summary");

  if (target) {
    // If target is a link, allow navigation
    if (target.tagName === "A") {
      return;
    }
    // If target is inside summary, do not toggle details
    if (summary) {
      e.preventDefault();
      showTooltip(target);
      e.stopPropagation();
    } else {
      showTooltip(target);
    }
  } else {
    hideTooltip();
  }
});

// Hide on scroll/window resize
window.addEventListener("scroll", hideTooltip, { passive: true });
window.addEventListener("resize", hideTooltip);

// Close with Esc key
document.addEventListener("keydown", (e) => {
  if (e.key === "Escape") hideTooltip();
});
