[package]
name = "syddansk-lektion"
version = "0.1.0"
compiler = "0.14.2"
repository = "https://codeberg.org/foxy/syddansk-lektion"
entrypoint = "lib.typ"
authors = ["Stefano Volpe"]
categories = ["presentation"]
license = "GPL-3.0-or-later"
description = "An unofficial Touying port of Southern Denmark University's slideshow template"
keywords = ["university", "denmark"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
