[package]
name = "unofficial-fhs-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["CYS, FH Salzburg <https://fh-salzburg.ac.at>"]
license = "MIT"
description = "Projects and BA/MA thesis FH Salzburg"
categories = ["thesis"]
keywords = ["project", "thesis", "fh salzburg", "fhs"]
repository = "https://its-git.fh-salzburg.ac.at/fhs46581/fhs-its-thesis-typst"

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
