#let data = (
  ("TULU-TIGALARI LETTER A", "Lo", 0, none),
  ("TULU-TIGALARI LETTER AA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER I", "Lo", 0, none),
  ("TULU-TIGALARI LETTER II", "Lo", 0, none),
  ("TULU-TIGALARI LETTER U", "Lo", 0, none),
  ("TULU-TIGALARI LETTER UU", "Lo", 0, none),
  ("TULU-TIGALARI LETTER VOCALIC R", "Lo", 0, none),
  ("TULU-TIGALARI LETTER VOCALIC RR", "Lo", 0, none),
  ("TULU-TIGALARI LETTER VOCALIC L", "Lo", 0, none),
  ("TULU-TIGALARI LETTER VOCALIC LL", "Lo", 0, none),
  (),
  ("TULU-TIGALARI LETTER EE", "Lo", 0, none),
  (),
  (),
  ("TULU-TIGALARI LETTER AI", "Lo", 0, none),
  (),
  ("TULU-TIGALARI LETTER OO", "Lo", 0, none),
  ("TULU-TIGALARI LETTER AU", "Lo", 0, none),
  ("TULU-TIGALARI LETTER KA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER KHA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER GA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER GHA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER NGA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER CA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER CHA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER JA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER JHA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER NYA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER TTA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER TTHA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER DDA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER DDHA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER NNA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER TA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER THA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER DA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER DHA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER NA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER PA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER PHA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER BA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER BHA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER MA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER YA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER RA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER LA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER VA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER SHA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER SSA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER SA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER HA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER LLA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER RRA", "Lo", 0, none),
  ("TULU-TIGALARI LETTER LLLA", "Lo", 0, none),
  (),
  ("TULU-TIGALARI SIGN AVAGRAHA", "Lo", 0, none),
  ("TULU-TIGALARI VOWEL SIGN AA", "Mc", 0, none),
  ("TULU-TIGALARI VOWEL SIGN I", "Mc", 0, none),
  ("TULU-TIGALARI VOWEL SIGN II", "Mc", 0, none),
  ("TULU-TIGALARI VOWEL SIGN U", "Mn", 0, none),
  ("TULU-TIGALARI VOWEL SIGN UU", "Mn", 0, none),
  ("TULU-TIGALARI VOWEL SIGN VOCALIC R", "Mn", 0, none),
  ("TULU-TIGALARI VOWEL SIGN VOCALIC RR", "Mn", 0, none),
  ("TULU-TIGALARI VOWEL SIGN VOCALIC L", "Mn", 0, none),
  ("TULU-TIGALARI VOWEL SIGN VOCALIC LL", "Mn", 0, none),
  (),
  ("TULU-TIGALARI VOWEL SIGN EE", "Mc", 0, none),
  (),
  (),
  ("TULU-TIGALARI VOWEL SIGN AI", "Mc", 0, none),
  (),
  ("TULU-TIGALARI VOWEL SIGN OO", "Mc", 0, none),
  ("TULU-TIGALARI VOWEL SIGN AU", "Mc", 0, none),
  ("TULU-TIGALARI AU LENGTH MARK", "Mc", 0, none),
  ("TULU-TIGALARI SIGN CANDRA ANUNASIKA", "Mc", 0, none),
  (),
  ("TULU-TIGALARI SIGN ANUSVARA", "Mc", 0, none),
  ("TULU-TIGALARI SIGN VISARGA", "Mc", 0, none),
  ("TULU-TIGALARI SIGN VIRAMA", "Mn", 9, none),
  ("TULU-TIGALARI SIGN LOOPED VIRAMA", "Mc", 9, none),
  ("TULU-TIGALARI CONJOINER", "Mn", 9, none),
  ("TULU-TIGALARI REPHA", "Lo", 0, none),
  ("TULU-TIGALARI GEMINATION MARK", "Mn", 0, none),
  ("TULU-TIGALARI SIGN PLUTA", "Lo", 0, none),
  ("TULU-TIGALARI DANDA", "Po", 0, none),
  ("TULU-TIGALARI DOUBLE DANDA", "Po", 0, none),
  (),
  ("TULU-TIGALARI SIGN OM PUSHPIKA", "Po", 0, none),
  ("TULU-TIGALARI SIGN SHRII PUSHPIKA", "Po", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TULU-TIGALARI VEDIC TONE SVARITA", "Mn", 0, none),
  ("TULU-TIGALARI VEDIC TONE ANUDATTA", "Mn", 0, none),
)
