#let data = (
  ("BATAK LETTER A", "Lo", 0, none),
  ("BATAK LETTER SIMALUNGUN A", "Lo", 0, none),
  ("BATAK LETTER HA", "Lo", 0, none),
  ("BATAK LETTER SIMALUNGUN HA", "Lo", 0, none),
  ("BATAK LETTER MANDAILING HA", "Lo", 0, none),
  ("BATAK LETTER BA", "Lo", 0, none),
  ("BATAK LETTER KARO BA", "Lo", 0, none),
  ("BATAK LETTER PA", "Lo", 0, none),
  ("BATAK LETTER SIMALUNGUN PA", "Lo", 0, none),
  ("BATAK LETTER NA", "Lo", 0, none),
  ("BATAK LETTER MANDAILING NA", "Lo", 0, none),
  ("BATAK LETTER WA", "Lo", 0, none),
  ("BATAK LETTER SIMALUNGUN WA", "Lo", 0, none),
  ("BATAK LETTER PAKPAK WA", "Lo", 0, none),
  ("BATAK LETTER GA", "Lo", 0, none),
  ("BATAK LETTER SIMALUNGUN GA", "Lo", 0, none),
  ("BATAK LETTER JA", "Lo", 0, none),
  ("BATAK LETTER DA", "Lo", 0, none),
  ("BATAK LETTER RA", "Lo", 0, none),
  ("BATAK LETTER SIMALUNGUN RA", "Lo", 0, none),
  ("BATAK LETTER MA", "Lo", 0, none),
  ("BATAK LETTER SIMALUNGUN MA", "Lo", 0, none),
  ("BATAK LETTER SOUTHERN TA", "Lo", 0, none),
  ("BATAK LETTER NORTHERN TA", "Lo", 0, none),
  ("BATAK LETTER SA", "Lo", 0, none),
  ("BATAK LETTER SIMALUNGUN SA", "Lo", 0, none),
  ("BATAK LETTER MANDAILING SA", "Lo", 0, none),
  ("BATAK LETTER YA", "Lo", 0, none),
  ("BATAK LETTER SIMALUNGUN YA", "Lo", 0, none),
  ("BATAK LETTER NGA", "Lo", 0, none),
  ("BATAK LETTER LA", "Lo", 0, none),
  ("BATAK LETTER SIMALUNGUN LA", "Lo", 0, none),
  ("BATAK LETTER NYA", "Lo", 0, none),
  ("BATAK LETTER CA", "Lo", 0, none),
  ("BATAK LETTER NDA", "Lo", 0, none),
  ("BATAK LETTER MBA", "Lo", 0, none),
  ("BATAK LETTER I", "Lo", 0, none),
  ("BATAK LETTER U", "Lo", 0, none),
  ("BATAK SIGN TOMPI", "Mn", 7, none),
  ("BATAK VOWEL SIGN E", "Mc", 0, none),
  ("BATAK VOWEL SIGN PAKPAK E", "Mn", 0, none),
  ("BATAK VOWEL SIGN EE", "Mn", 0, none),
  ("BATAK VOWEL SIGN I", "Mc", 0, none),
  ("BATAK VOWEL SIGN KARO I", "Mc", 0, none),
  ("BATAK VOWEL SIGN O", "Mc", 0, none),
  ("BATAK VOWEL SIGN KARO O", "Mn", 0, none),
  ("BATAK VOWEL SIGN U", "Mc", 0, none),
  ("BATAK VOWEL SIGN U FOR SIMALUNGUN SA", "Mn", 0, none),
  ("BATAK CONSONANT SIGN NG", "Mn", 0, none),
  ("BATAK CONSONANT SIGN H", "Mn", 0, none),
  ("BATAK PANGOLAT", "Mc", 9, none),
  ("BATAK PANONGONAN", "Mc", 9, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("BATAK SYMBOL BINDU NA METEK", "Po", 0, none),
  ("BATAK SYMBOL BINDU PINARBORAS", "Po", 0, none),
  ("BATAK SYMBOL BINDU JUDUL", "Po", 0, none),
  ("BATAK SYMBOL BINDU PANGOLAT", "Po", 0, none),
)
