#let data = (
  ("PAU CIN HAU LETTER PA", "Lo", 0, none),
  ("PAU CIN HAU LETTER KA", "Lo", 0, none),
  ("PAU CIN HAU LETTER LA", "Lo", 0, none),
  ("PAU CIN HAU LETTER MA", "Lo", 0, none),
  ("PAU CIN HAU LETTER DA", "Lo", 0, none),
  ("PAU CIN HAU LETTER ZA", "Lo", 0, none),
  ("PAU CIN HAU LETTER VA", "Lo", 0, none),
  ("PAU CIN HAU LETTER NGA", "Lo", 0, none),
  ("PAU CIN HAU LETTER HA", "Lo", 0, none),
  ("PAU CIN HAU LETTER GA", "Lo", 0, none),
  ("PAU CIN HAU LETTER KHA", "Lo", 0, none),
  ("PAU CIN HAU LETTER SA", "Lo", 0, none),
  ("PAU CIN HAU LETTER BA", "Lo", 0, none),
  ("PAU CIN HAU LETTER CA", "Lo", 0, none),
  ("PAU CIN HAU LETTER TA", "Lo", 0, none),
  ("PAU CIN HAU LETTER THA", "Lo", 0, none),
  ("PAU CIN HAU LETTER NA", "Lo", 0, none),
  ("PAU CIN HAU LETTER PHA", "Lo", 0, none),
  ("PAU CIN HAU LETTER RA", "Lo", 0, none),
  ("PAU CIN HAU LETTER FA", "Lo", 0, none),
  ("PAU CIN HAU LETTER CHA", "Lo", 0, none),
  ("PAU CIN HAU LETTER A", "Lo", 0, none),
  ("PAU CIN HAU LETTER E", "Lo", 0, none),
  ("PAU CIN HAU LETTER I", "Lo", 0, none),
  ("PAU CIN HAU LETTER O", "Lo", 0, none),
  ("PAU CIN HAU LETTER U", "Lo", 0, none),
  ("PAU CIN HAU LETTER UA", "Lo", 0, none),
  ("PAU CIN HAU LETTER IA", "Lo", 0, none),
  ("PAU CIN HAU LETTER FINAL P", "Lo", 0, none),
  ("PAU CIN HAU LETTER FINAL K", "Lo", 0, none),
  ("PAU CIN HAU LETTER FINAL T", "Lo", 0, none),
  ("PAU CIN HAU LETTER FINAL M", "Lo", 0, none),
  ("PAU CIN HAU LETTER FINAL N", "Lo", 0, none),
  ("PAU CIN HAU LETTER FINAL L", "Lo", 0, none),
  ("PAU CIN HAU LETTER FINAL W", "Lo", 0, none),
  ("PAU CIN HAU LETTER FINAL NG", "Lo", 0, none),
  ("PAU CIN HAU LETTER FINAL Y", "Lo", 0, none),
  ("PAU CIN HAU RISING TONE LONG", "Lo", 0, none),
  ("PAU CIN HAU RISING TONE", "Lo", 0, none),
  ("PAU CIN HAU SANDHI GLOTTAL STOP", "Lo", 0, none),
  ("PAU CIN HAU RISING TONE LONG FINAL", "Lo", 0, none),
  ("PAU CIN HAU RISING TONE FINAL", "Lo", 0, none),
  ("PAU CIN HAU SANDHI GLOTTAL STOP FINAL", "Lo", 0, none),
  ("PAU CIN HAU SANDHI TONE LONG", "Lo", 0, none),
  ("PAU CIN HAU SANDHI TONE", "Lo", 0, none),
  ("PAU CIN HAU SANDHI TONE LONG FINAL", "Lo", 0, none),
  ("PAU CIN HAU SANDHI TONE FINAL", "Lo", 0, none),
  ("PAU CIN HAU MID-LEVEL TONE", "Lo", 0, none),
  ("PAU CIN HAU GLOTTAL STOP VARIANT", "Lo", 0, none),
  ("PAU CIN HAU MID-LEVEL TONE LONG FINAL", "Lo", 0, none),
  ("PAU CIN HAU MID-LEVEL TONE FINAL", "Lo", 0, none),
  ("PAU CIN HAU LOW-FALLING TONE LONG", "Lo", 0, none),
  ("PAU CIN HAU LOW-FALLING TONE", "Lo", 0, none),
  ("PAU CIN HAU GLOTTAL STOP", "Lo", 0, none),
  ("PAU CIN HAU LOW-FALLING TONE LONG FINAL", "Lo", 0, none),
  ("PAU CIN HAU LOW-FALLING TONE FINAL", "Lo", 0, none),
  ("PAU CIN HAU GLOTTAL STOP FINAL", "Lo", 0, none),
)
