#let data = (
  ("TIBETAN SYLLABLE OM", "Lo", 0, none),
  ("TIBETAN MARK GTER YIG MGO TRUNCATED A", "So", 0, none),
  ("TIBETAN MARK GTER YIG MGO -UM RNAM BCAD MA", "So", 0, none),
  ("TIBETAN MARK GTER YIG MGO -UM GTER TSHEG MA", "So", 0, none),
  ("TIBETAN MARK INITIAL YIG MGO MDUN MA", "Po", 0, none),
  ("TIBETAN MARK CLOSING YIG MGO SGAB MA", "Po", 0, none),
  ("TIBETAN MARK CARET YIG MGO PHUR SHAD MA", "Po", 0, none),
  ("TIBETAN MARK YIG MGO TSHEG SHAD MA", "Po", 0, none),
  ("TIBETAN MARK SBRUL SHAD", "Po", 0, none),
  ("TIBETAN MARK BSKUR YIG MGO", "Po", 0, none),
  ("TIBETAN MARK BKA- SHOG YIG MGO", "Po", 0, none),
  ("TIBETAN MARK INTERSYLLABIC TSHEG", "Po", 0, none),
  ("TIBETAN MARK DELIMITER TSHEG BSTAR", "Po", 0, none),
  ("TIBETAN MARK SHAD", "Po", 0, none),
  ("TIBETAN MARK NYIS SHAD", "Po", 0, none),
  ("TIBETAN MARK TSHEG SHAD", "Po", 0, none),
  ("TIBETAN MARK NYIS TSHEG SHAD", "Po", 0, none),
  ("TIBETAN MARK RIN CHEN SPUNGS SHAD", "Po", 0, none),
  ("TIBETAN MARK RGYA GRAM SHAD", "Po", 0, none),
  ("TIBETAN MARK CARET -DZUD RTAGS ME LONG CAN", "So", 0, none),
  ("TIBETAN MARK GTER TSHEG", "Po", 0, none),
  ("TIBETAN LOGOTYPE SIGN CHAD RTAGS", "So", 0, none),
  ("TIBETAN LOGOTYPE SIGN LHAG RTAGS", "So", 0, none),
  ("TIBETAN ASTROLOGICAL SIGN SGRA GCAN -CHAR RTAGS", "So", 0, none),
  ("TIBETAN ASTROLOGICAL SIGN -KHYUD PA", "Mn", 220, none),
  ("TIBETAN ASTROLOGICAL SIGN SDONG TSHUGS", "Mn", 220, none),
  ("TIBETAN SIGN RDEL DKAR GCIG", "So", 0, none),
  ("TIBETAN SIGN RDEL DKAR GNYIS", "So", 0, none),
  ("TIBETAN SIGN RDEL DKAR GSUM", "So", 0, none),
  ("TIBETAN SIGN RDEL NAG GCIG", "So", 0, none),
  ("TIBETAN SIGN RDEL NAG GNYIS", "So", 0, none),
  ("TIBETAN SIGN RDEL DKAR RDEL NAG", "So", 0, none),
  ("TIBETAN DIGIT ZERO", "Nd", 0, none),
  ("TIBETAN DIGIT ONE", "Nd", 0, none),
  ("TIBETAN DIGIT TWO", "Nd", 0, none),
  ("TIBETAN DIGIT THREE", "Nd", 0, none),
  ("TIBETAN DIGIT FOUR", "Nd", 0, none),
  ("TIBETAN DIGIT FIVE", "Nd", 0, none),
  ("TIBETAN DIGIT SIX", "Nd", 0, none),
  ("TIBETAN DIGIT SEVEN", "Nd", 0, none),
  ("TIBETAN DIGIT EIGHT", "Nd", 0, none),
  ("TIBETAN DIGIT NINE", "Nd", 0, none),
  ("TIBETAN DIGIT HALF ONE", "No", 0, none),
  ("TIBETAN DIGIT HALF TWO", "No", 0, none),
  ("TIBETAN DIGIT HALF THREE", "No", 0, none),
  ("TIBETAN DIGIT HALF FOUR", "No", 0, none),
  ("TIBETAN DIGIT HALF FIVE", "No", 0, none),
  ("TIBETAN DIGIT HALF SIX", "No", 0, none),
  ("TIBETAN DIGIT HALF SEVEN", "No", 0, none),
  ("TIBETAN DIGIT HALF EIGHT", "No", 0, none),
  ("TIBETAN DIGIT HALF NINE", "No", 0, none),
  ("TIBETAN DIGIT HALF ZERO", "No", 0, none),
  ("TIBETAN MARK BSDUS RTAGS", "So", 0, none),
  ("TIBETAN MARK NGAS BZUNG NYI ZLA", "Mn", 220, none),
  ("TIBETAN MARK CARET -DZUD RTAGS BZHI MIG CAN", "So", 0, none),
  ("TIBETAN MARK NGAS BZUNG SGOR RTAGS", "Mn", 220, none),
  ("TIBETAN MARK CHE MGO", "So", 0, none),
  ("TIBETAN MARK TSA -PHRU", "Mn", 216, none),
  ("TIBETAN MARK GUG RTAGS GYON", "Ps", 0, none),
  ("TIBETAN MARK GUG RTAGS GYAS", "Pe", 0, none),
  ("TIBETAN MARK ANG KHANG GYON", "Ps", 0, none),
  ("TIBETAN MARK ANG KHANG GYAS", "Pe", 0, none),
  ("TIBETAN SIGN YAR TSHES", "Mc", 0, none),
  ("TIBETAN SIGN MAR TSHES", "Mc", 0, none),
  ("TIBETAN LETTER KA", "Lo", 0, none),
  ("TIBETAN LETTER KHA", "Lo", 0, none),
  ("TIBETAN LETTER GA", "Lo", 0, none),
  ("TIBETAN LETTER GHA", "Lo", 0, none),
  ("TIBETAN LETTER NGA", "Lo", 0, none),
  ("TIBETAN LETTER CA", "Lo", 0, none),
  ("TIBETAN LETTER CHA", "Lo", 0, none),
  ("TIBETAN LETTER JA", "Lo", 0, none),
  (),
  ("TIBETAN LETTER NYA", "Lo", 0, none),
  ("TIBETAN LETTER TTA", "Lo", 0, none),
  ("TIBETAN LETTER TTHA", "Lo", 0, none),
  ("TIBETAN LETTER DDA", "Lo", 0, none),
  ("TIBETAN LETTER DDHA", "Lo", 0, none),
  ("TIBETAN LETTER NNA", "Lo", 0, none),
  ("TIBETAN LETTER TA", "Lo", 0, none),
  ("TIBETAN LETTER THA", "Lo", 0, none),
  ("TIBETAN LETTER DA", "Lo", 0, none),
  ("TIBETAN LETTER DHA", "Lo", 0, none),
  ("TIBETAN LETTER NA", "Lo", 0, none),
  ("TIBETAN LETTER PA", "Lo", 0, none),
  ("TIBETAN LETTER PHA", "Lo", 0, none),
  ("TIBETAN LETTER BA", "Lo", 0, none),
  ("TIBETAN LETTER BHA", "Lo", 0, none),
  ("TIBETAN LETTER MA", "Lo", 0, none),
  ("TIBETAN LETTER TSA", "Lo", 0, none),
  ("TIBETAN LETTER TSHA", "Lo", 0, none),
  ("TIBETAN LETTER DZA", "Lo", 0, none),
  ("TIBETAN LETTER DZHA", "Lo", 0, none),
  ("TIBETAN LETTER WA", "Lo", 0, none),
  ("TIBETAN LETTER ZHA", "Lo", 0, none),
  ("TIBETAN LETTER ZA", "Lo", 0, none),
  ("TIBETAN LETTER -A", "Lo", 0, none),
  ("TIBETAN LETTER YA", "Lo", 0, none),
  ("TIBETAN LETTER RA", "Lo", 0, none),
  ("TIBETAN LETTER LA", "Lo", 0, none),
  ("TIBETAN LETTER SHA", "Lo", 0, none),
  ("TIBETAN LETTER SSA", "Lo", 0, none),
  ("TIBETAN LETTER SA", "Lo", 0, none),
  ("TIBETAN LETTER HA", "Lo", 0, none),
  ("TIBETAN LETTER A", "Lo", 0, none),
  ("TIBETAN LETTER KSSA", "Lo", 0, none),
  ("TIBETAN LETTER FIXED-FORM RA", "Lo", 0, none),
  ("TIBETAN LETTER KKA", "Lo", 0, none),
  ("TIBETAN LETTER RRA", "Lo", 0, none),
  (),
  (),
  (),
  (),
  ("TIBETAN VOWEL SIGN AA", "Mn", 129, none),
  ("TIBETAN VOWEL SIGN I", "Mn", 130, none),
  ("TIBETAN VOWEL SIGN II", "Mn", 0, none),
  ("TIBETAN VOWEL SIGN U", "Mn", 132, none),
  ("TIBETAN VOWEL SIGN UU", "Mn", 0, none),
  ("TIBETAN VOWEL SIGN VOCALIC R", "Mn", 0, none),
  ("TIBETAN VOWEL SIGN VOCALIC RR", "Mn", 0, none),
  ("TIBETAN VOWEL SIGN VOCALIC L", "Mn", 0, none),
  ("TIBETAN VOWEL SIGN VOCALIC LL", "Mn", 0, none),
  ("TIBETAN VOWEL SIGN E", "Mn", 130, none),
  ("TIBETAN VOWEL SIGN EE", "Mn", 130, none),
  ("TIBETAN VOWEL SIGN O", "Mn", 130, none),
  ("TIBETAN VOWEL SIGN OO", "Mn", 130, none),
  ("TIBETAN SIGN RJES SU NGA RO", "Mn", 0, none),
  ("TIBETAN SIGN RNAM BCAD", "Mc", 0, none),
  ("TIBETAN VOWEL SIGN REVERSED I", "Mn", 130, none),
  ("TIBETAN VOWEL SIGN REVERSED II", "Mn", 0, none),
  ("TIBETAN SIGN NYI ZLA NAA DA", "Mn", 230, none),
  ("TIBETAN SIGN SNA LDAN", "Mn", 230, none),
  ("TIBETAN MARK HALANTA", "Mn", 9, none),
  ("TIBETAN MARK PALUTA", "Po", 0, none),
  ("TIBETAN SIGN LCI RTAGS", "Mn", 230, none),
  ("TIBETAN SIGN YANG RTAGS", "Mn", 230, none),
  ("TIBETAN SIGN LCE TSA CAN", "Lo", 0, none),
  ("TIBETAN SIGN MCHU CAN", "Lo", 0, none),
  ("TIBETAN SIGN GRU CAN RGYINGS", "Lo", 0, none),
  ("TIBETAN SIGN GRU MED RGYINGS", "Lo", 0, none),
  ("TIBETAN SIGN INVERTED MCHU CAN", "Lo", 0, none),
  ("TIBETAN SUBJOINED SIGN LCE TSA CAN", "Mn", 0, none),
  ("TIBETAN SUBJOINED SIGN MCHU CAN", "Mn", 0, none),
  ("TIBETAN SUBJOINED SIGN INVERTED MCHU CAN", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER KA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER KHA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER GA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER GHA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER NGA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER CA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER CHA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER JA", "Mn", 0, none),
  (),
  ("TIBETAN SUBJOINED LETTER NYA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER TTA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER TTHA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER DDA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER DDHA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER NNA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER TA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER THA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER DA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER DHA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER NA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER PA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER PHA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER BA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER BHA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER MA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER TSA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER TSHA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER DZA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER DZHA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER WA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER ZHA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER ZA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER -A", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER YA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER RA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER LA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER SHA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER SSA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER SA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER HA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER A", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER KSSA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER FIXED-FORM WA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER FIXED-FORM YA", "Mn", 0, none),
  ("TIBETAN SUBJOINED LETTER FIXED-FORM RA", "Mn", 0, none),
  (),
  ("TIBETAN KU RU KHA", "So", 0, none),
  ("TIBETAN KU RU KHA BZHI MIG CAN", "So", 0, none),
  ("TIBETAN CANTILLATION SIGN HEAVY BEAT", "So", 0, none),
  ("TIBETAN CANTILLATION SIGN LIGHT BEAT", "So", 0, none),
  ("TIBETAN CANTILLATION SIGN CANG TE-U", "So", 0, none),
  ("TIBETAN CANTILLATION SIGN SBUB -CHAL", "So", 0, none),
  ("TIBETAN SYMBOL DRIL BU", "So", 0, none),
  ("TIBETAN SYMBOL RDO RJE", "So", 0, none),
  ("TIBETAN SYMBOL PADMA GDAN", "Mn", 220, none),
  ("TIBETAN SYMBOL RDO RJE RGYA GRAM", "So", 0, none),
  ("TIBETAN SYMBOL PHUR PA", "So", 0, none),
  ("TIBETAN SYMBOL NOR BU", "So", 0, none),
  ("TIBETAN SYMBOL NOR BU NYIS -KHYIL", "So", 0, none),
  ("TIBETAN SYMBOL NOR BU GSUM -KHYIL", "So", 0, none),
  ("TIBETAN SYMBOL NOR BU BZHI -KHYIL", "So", 0, none),
  (),
  ("TIBETAN SIGN RDEL NAG RDEL DKAR", "So", 0, none),
  ("TIBETAN SIGN RDEL NAG GSUM", "So", 0, none),
  ("TIBETAN MARK BSKA- SHOG GI MGO RGYAN", "Po", 0, none),
  ("TIBETAN MARK MNYAM YIG GI MGO RGYAN", "Po", 0, none),
  ("TIBETAN MARK NYIS TSHEG", "Po", 0, none),
  ("TIBETAN MARK INITIAL BRDA RNYING YIG MGO MDUN MA", "Po", 0, none),
  ("TIBETAN MARK CLOSING BRDA RNYING YIG MGO SGAB MA", "Po", 0, none),
  ("RIGHT-FACING SVASTI SIGN", "So", 0, none),
  ("LEFT-FACING SVASTI SIGN", "So", 0, none),
  ("RIGHT-FACING SVASTI SIGN WITH DOTS", "So", 0, none),
  ("LEFT-FACING SVASTI SIGN WITH DOTS", "So", 0, none),
  ("TIBETAN MARK LEADING MCHAN RTAGS", "Po", 0, none),
  ("TIBETAN MARK TRAILING MCHAN RTAGS", "Po", 0, none),
)
