#let data = (
  ("DEVANAGARI SIGN INVERTED CANDRABINDU", "Mn", 0, none),
  ("DEVANAGARI SIGN CANDRABINDU", "Mn", 0, none),
  ("DEVANAGARI SIGN ANUSVARA", "Mn", 0, none),
  ("DEVANAGARI SIGN VISARGA", "Mc", 0, none),
  ("DEVANAGARI LETTER SHORT A", "Lo", 0, none),
  ("DEVANAGARI LETTER A", "Lo", 0, none),
  ("DEVANAGARI LETTER AA", "Lo", 0, none),
  ("DEVANAGARI LETTER I", "Lo", 0, none),
  ("DEVANAGARI LETTER II", "Lo", 0, none),
  ("DEVANAGARI LETTER U", "Lo", 0, none),
  ("DEVANAGARI LETTER UU", "Lo", 0, none),
  ("DEVANAGARI LETTER VOCALIC R", "Lo", 0, none),
  ("DEVANAGARI LETTER VOCALIC L", "Lo", 0, none),
  ("DEVANAGARI LETTER CANDRA E", "Lo", 0, none),
  ("DEVANAGARI LETTER SHORT E", "Lo", 0, none),
  ("DEVANAGARI LETTER E", "Lo", 0, none),
  ("DEVANAGARI LETTER AI", "Lo", 0, none),
  ("DEVANAGARI LETTER CANDRA O", "Lo", 0, none),
  ("DEVANAGARI LETTER SHORT O", "Lo", 0, none),
  ("DEVANAGARI LETTER O", "Lo", 0, none),
  ("DEVANAGARI LETTER AU", "Lo", 0, none),
  ("DEVANAGARI LETTER KA", "Lo", 0, none),
  ("DEVANAGARI LETTER KHA", "Lo", 0, none),
  ("DEVANAGARI LETTER GA", "Lo", 0, none),
  ("DEVANAGARI LETTER GHA", "Lo", 0, none),
  ("DEVANAGARI LETTER NGA", "Lo", 0, none),
  ("DEVANAGARI LETTER CA", "Lo", 0, none),
  ("DEVANAGARI LETTER CHA", "Lo", 0, none),
  ("DEVANAGARI LETTER JA", "Lo", 0, none),
  ("DEVANAGARI LETTER JHA", "Lo", 0, none),
  ("DEVANAGARI LETTER NYA", "Lo", 0, none),
  ("DEVANAGARI LETTER TTA", "Lo", 0, none),
  ("DEVANAGARI LETTER TTHA", "Lo", 0, none),
  ("DEVANAGARI LETTER DDA", "Lo", 0, none),
  ("DEVANAGARI LETTER DDHA", "Lo", 0, none),
  ("DEVANAGARI LETTER NNA", "Lo", 0, none),
  ("DEVANAGARI LETTER TA", "Lo", 0, none),
  ("DEVANAGARI LETTER THA", "Lo", 0, none),
  ("DEVANAGARI LETTER DA", "Lo", 0, none),
  ("DEVANAGARI LETTER DHA", "Lo", 0, none),
  ("DEVANAGARI LETTER NA", "Lo", 0, none),
  ("DEVANAGARI LETTER NNNA", "Lo", 0, none),
  ("DEVANAGARI LETTER PA", "Lo", 0, none),
  ("DEVANAGARI LETTER PHA", "Lo", 0, none),
  ("DEVANAGARI LETTER BA", "Lo", 0, none),
  ("DEVANAGARI LETTER BHA", "Lo", 0, none),
  ("DEVANAGARI LETTER MA", "Lo", 0, none),
  ("DEVANAGARI LETTER YA", "Lo", 0, none),
  ("DEVANAGARI LETTER RA", "Lo", 0, none),
  ("DEVANAGARI LETTER RRA", "Lo", 0, none),
  ("DEVANAGARI LETTER LA", "Lo", 0, none),
  ("DEVANAGARI LETTER LLA", "Lo", 0, none),
  ("DEVANAGARI LETTER LLLA", "Lo", 0, none),
  ("DEVANAGARI LETTER VA", "Lo", 0, none),
  ("DEVANAGARI LETTER SHA", "Lo", 0, none),
  ("DEVANAGARI LETTER SSA", "Lo", 0, none),
  ("DEVANAGARI LETTER SA", "Lo", 0, none),
  ("DEVANAGARI LETTER HA", "Lo", 0, none),
  ("DEVANAGARI VOWEL SIGN OE", "Mn", 0, none),
  ("DEVANAGARI VOWEL SIGN OOE", "Mc", 0, none),
  ("DEVANAGARI SIGN NUKTA", "Mn", 7, none),
  ("DEVANAGARI SIGN AVAGRAHA", "Lo", 0, none),
  ("DEVANAGARI VOWEL SIGN AA", "Mc", 0, none),
  ("DEVANAGARI VOWEL SIGN I", "Mc", 0, none),
  ("DEVANAGARI VOWEL SIGN II", "Mc", 0, none),
  ("DEVANAGARI VOWEL SIGN U", "Mn", 0, none),
  ("DEVANAGARI VOWEL SIGN UU", "Mn", 0, none),
  ("DEVANAGARI VOWEL SIGN VOCALIC R", "Mn", 0, none),
  ("DEVANAGARI VOWEL SIGN VOCALIC RR", "Mn", 0, none),
  ("DEVANAGARI VOWEL SIGN CANDRA E", "Mn", 0, none),
  ("DEVANAGARI VOWEL SIGN SHORT E", "Mn", 0, none),
  ("DEVANAGARI VOWEL SIGN E", "Mn", 0, none),
  ("DEVANAGARI VOWEL SIGN AI", "Mn", 0, none),
  ("DEVANAGARI VOWEL SIGN CANDRA O", "Mc", 0, none),
  ("DEVANAGARI VOWEL SIGN SHORT O", "Mc", 0, none),
  ("DEVANAGARI VOWEL SIGN O", "Mc", 0, none),
  ("DEVANAGARI VOWEL SIGN AU", "Mc", 0, none),
  ("DEVANAGARI SIGN VIRAMA", "Mn", 9, none),
  ("DEVANAGARI VOWEL SIGN PRISHTHAMATRA E", "Mc", 0, none),
  ("DEVANAGARI VOWEL SIGN AW", "Mc", 0, none),
  ("DEVANAGARI OM", "Lo", 0, none),
  ("DEVANAGARI STRESS SIGN UDATTA", "Mn", 230, none),
  ("DEVANAGARI STRESS SIGN ANUDATTA", "Mn", 220, none),
  ("DEVANAGARI GRAVE ACCENT", "Mn", 230, none),
  ("DEVANAGARI ACUTE ACCENT", "Mn", 230, none),
  ("DEVANAGARI VOWEL SIGN CANDRA LONG E", "Mn", 0, none),
  ("DEVANAGARI VOWEL SIGN UE", "Mn", 0, none),
  ("DEVANAGARI VOWEL SIGN UUE", "Mn", 0, none),
  ("DEVANAGARI LETTER QA", "Lo", 0, none),
  ("DEVANAGARI LETTER KHHA", "Lo", 0, none),
  ("DEVANAGARI LETTER GHHA", "Lo", 0, none),
  ("DEVANAGARI LETTER ZA", "Lo", 0, none),
  ("DEVANAGARI LETTER DDDHA", "Lo", 0, none),
  ("DEVANAGARI LETTER RHA", "Lo", 0, none),
  ("DEVANAGARI LETTER FA", "Lo", 0, none),
  ("DEVANAGARI LETTER YYA", "Lo", 0, none),
  ("DEVANAGARI LETTER VOCALIC RR", "Lo", 0, none),
  ("DEVANAGARI LETTER VOCALIC LL", "Lo", 0, none),
  ("DEVANAGARI VOWEL SIGN VOCALIC L", "Mn", 0, none),
  ("DEVANAGARI VOWEL SIGN VOCALIC LL", "Mn", 0, none),
  ("DEVANAGARI DANDA", "Po", 0, none),
  ("DEVANAGARI DOUBLE DANDA", "Po", 0, none),
  ("DEVANAGARI DIGIT ZERO", "Nd", 0, none),
  ("DEVANAGARI DIGIT ONE", "Nd", 0, none),
  ("DEVANAGARI DIGIT TWO", "Nd", 0, none),
  ("DEVANAGARI DIGIT THREE", "Nd", 0, none),
  ("DEVANAGARI DIGIT FOUR", "Nd", 0, none),
  ("DEVANAGARI DIGIT FIVE", "Nd", 0, none),
  ("DEVANAGARI DIGIT SIX", "Nd", 0, none),
  ("DEVANAGARI DIGIT SEVEN", "Nd", 0, none),
  ("DEVANAGARI DIGIT EIGHT", "Nd", 0, none),
  ("DEVANAGARI DIGIT NINE", "Nd", 0, none),
  ("DEVANAGARI ABBREVIATION SIGN", "Po", 0, none),
  ("DEVANAGARI SIGN HIGH SPACING DOT", "Lm", 0, none),
  ("DEVANAGARI LETTER CANDRA A", "Lo", 0, none),
  ("DEVANAGARI LETTER OE", "Lo", 0, none),
  ("DEVANAGARI LETTER OOE", "Lo", 0, none),
  ("DEVANAGARI LETTER AW", "Lo", 0, none),
  ("DEVANAGARI LETTER UE", "Lo", 0, none),
  ("DEVANAGARI LETTER UUE", "Lo", 0, none),
  ("DEVANAGARI LETTER MARWARI DDA", "Lo", 0, none),
  ("DEVANAGARI LETTER ZHA", "Lo", 0, none),
  ("DEVANAGARI LETTER HEAVY YA", "Lo", 0, none),
  ("DEVANAGARI LETTER GGA", "Lo", 0, none),
  ("DEVANAGARI LETTER JJA", "Lo", 0, none),
  ("DEVANAGARI LETTER GLOTTAL STOP", "Lo", 0, none),
  ("DEVANAGARI LETTER DDDA", "Lo", 0, none),
  ("DEVANAGARI LETTER BBA", "Lo", 0, none),
)
