#let data = (
  ("LATIN SMALL LIGATURE FF", "Ll", 0, none),
  ("LATIN SMALL LIGATURE FI", "Ll", 0, none),
  ("LATIN SMALL LIGATURE FL", "Ll", 0, none),
  ("LATIN SMALL LIGATURE FFI", "Ll", 0, none),
  ("LATIN SMALL LIGATURE FFL", "Ll", 0, none),
  ("LATIN SMALL LIGATURE LONG S T", "Ll", 0, none),
  ("LATIN SMALL LIGATURE ST", "Ll", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("ARMENIAN SMALL LIGATURE MEN NOW", "Ll", 0, none),
  ("ARMENIAN SMALL LIGATURE MEN ECH", "Ll", 0, none),
  ("ARMENIAN SMALL LIGATURE MEN INI", "Ll", 0, none),
  ("ARMENIAN SMALL LIGATURE VEW NOW", "Ll", 0, none),
  ("ARMENIAN SMALL LIGATURE MEN XEH", "Ll", 0, none),
  (),
  (),
  (),
  (),
  (),
  ("HEBREW LETTER YOD WITH HIRIQ", "Lo", 0, none),
  ("HEBREW POINT JUDEO-SPANISH VARIKA", "Mn", 26, none),
  ("HEBREW LIGATURE YIDDISH YOD YOD PATAH", "Lo", 0, none),
  ("HEBREW LETTER ALTERNATIVE AYIN", "Lo", 0, none),
  ("HEBREW LETTER WIDE ALEF", "Lo", 0, none),
  ("HEBREW LETTER WIDE DALET", "Lo", 0, none),
  ("HEBREW LETTER WIDE HE", "Lo", 0, none),
  ("HEBREW LETTER WIDE KAF", "Lo", 0, none),
  ("HEBREW LETTER WIDE LAMED", "Lo", 0, none),
  ("HEBREW LETTER WIDE FINAL MEM", "Lo", 0, none),
  ("HEBREW LETTER WIDE RESH", "Lo", 0, none),
  ("HEBREW LETTER WIDE TAV", "Lo", 0, none),
  ("HEBREW LETTER ALTERNATIVE PLUS SIGN", "Sm", 0, "X"),
  ("HEBREW LETTER SHIN WITH SHIN DOT", "Lo", 0, none),
  ("HEBREW LETTER SHIN WITH SIN DOT", "Lo", 0, none),
  ("HEBREW LETTER SHIN WITH DAGESH AND SHIN DOT", "Lo", 0, none),
  ("HEBREW LETTER SHIN WITH DAGESH AND SIN DOT", "Lo", 0, none),
  ("HEBREW LETTER ALEF WITH PATAH", "Lo", 0, none),
  ("HEBREW LETTER ALEF WITH QAMATS", "Lo", 0, none),
  ("HEBREW LETTER ALEF WITH MAPIQ", "Lo", 0, none),
  ("HEBREW LETTER BET WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER GIMEL WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER DALET WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER HE WITH MAPIQ", "Lo", 0, none),
  ("HEBREW LETTER VAV WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER ZAYIN WITH DAGESH", "Lo", 0, none),
  (),
  ("HEBREW LETTER TET WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER YOD WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER FINAL KAF WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER KAF WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER LAMED WITH DAGESH", "Lo", 0, none),
  (),
  ("HEBREW LETTER MEM WITH DAGESH", "Lo", 0, none),
  (),
  ("HEBREW LETTER NUN WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER SAMEKH WITH DAGESH", "Lo", 0, none),
  (),
  ("HEBREW LETTER FINAL PE WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER PE WITH DAGESH", "Lo", 0, none),
  (),
  ("HEBREW LETTER TSADI WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER QOF WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER RESH WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER SHIN WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER TAV WITH DAGESH", "Lo", 0, none),
  ("HEBREW LETTER VAV WITH HOLAM", "Lo", 0, none),
  ("HEBREW LETTER BET WITH RAFE", "Lo", 0, none),
  ("HEBREW LETTER KAF WITH RAFE", "Lo", 0, none),
  ("HEBREW LETTER PE WITH RAFE", "Lo", 0, none),
  ("HEBREW LIGATURE ALEF LAMED", "Lo", 0, none),
)
