#let data = (
  ("SUNDANESE PUNCTUATION BINDU SURYA", "Po", 0, none),
  ("SUNDANESE PUNCTUATION BINDU PANGLONG", "Po", 0, none),
  ("SUNDANESE PUNCTUATION BINDU PURNAMA", "Po", 0, none),
  ("SUNDANESE PUNCTUATION BINDU CAKRA", "Po", 0, none),
  ("SUNDANESE PUNCTUATION BINDU LEU SATANGA", "Po", 0, none),
  ("SUNDANESE PUNCTUATION BINDU KA SATANGA", "Po", 0, none),
  ("SUNDANESE PUNCTUATION BINDU DA SATANGA", "Po", 0, none),
  ("SUNDANESE PUNCTUATION BINDU BA SATANGA", "Po", 0, none),
)
