#let data = (
  ("PSALTER PAHLAVI LETTER ALEPH", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER BETH", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER GIMEL", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER DALETH", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER HE", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER WAW-AYIN-RESH", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER ZAYIN", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER HETH", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER YODH", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER KAPH", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER LAMEDH", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER MEM-QOPH", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER NUN", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER SAMEKH", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER PE", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER SADHE", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER SHIN", "Lo", 0, none),
  ("PSALTER PAHLAVI LETTER TAW", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("PSALTER PAHLAVI SECTION MARK", "Po", 0, none),
  ("PSALTER PAHLAVI TURNED SECTION MARK", "Po", 0, none),
  ("PSALTER PAHLAVI FOUR DOTS WITH CROSS", "Po", 0, none),
  ("PSALTER PAHLAVI FOUR DOTS WITH DOT", "Po", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("PSALTER PAHLAVI NUMBER ONE", "No", 0, none),
  ("PSALTER PAHLAVI NUMBER TWO", "No", 0, none),
  ("PSALTER PAHLAVI NUMBER THREE", "No", 0, none),
  ("PSALTER PAHLAVI NUMBER FOUR", "No", 0, none),
  ("PSALTER PAHLAVI NUMBER TEN", "No", 0, none),
  ("PSALTER PAHLAVI NUMBER TWENTY", "No", 0, none),
  ("PSALTER PAHLAVI NUMBER ONE HUNDRED", "No", 0, none),
)
