#let data = (
  ("BOPOMOFO LETTER BU", "Lo", 0, none),
  ("BOPOMOFO LETTER ZI", "Lo", 0, none),
  ("BOPOMOFO LETTER JI", "Lo", 0, none),
  ("BOPOMOFO LETTER GU", "Lo", 0, none),
  ("BOPOMOFO LETTER EE", "Lo", 0, none),
  ("BOPOMOFO LETTER ENN", "Lo", 0, none),
  ("BOPOMOFO LETTER OO", "Lo", 0, none),
  ("BOPOMOFO LETTER ONN", "Lo", 0, none),
  ("BOPOMOFO LETTER IR", "Lo", 0, none),
  ("BOPOMOFO LETTER ANN", "Lo", 0, none),
  ("BOPOMOFO LETTER INN", "Lo", 0, none),
  ("BOPOMOFO LETTER UNN", "Lo", 0, none),
  ("BOPOMOFO LETTER IM", "Lo", 0, none),
  ("BOPOMOFO LETTER NGG", "Lo", 0, none),
  ("BOPOMOFO LETTER AINN", "Lo", 0, none),
  ("BOPOMOFO LETTER AUNN", "Lo", 0, none),
  ("BOPOMOFO LETTER AM", "Lo", 0, none),
  ("BOPOMOFO LETTER OM", "Lo", 0, none),
  ("BOPOMOFO LETTER ONG", "Lo", 0, none),
  ("BOPOMOFO LETTER INNN", "Lo", 0, none),
  ("BOPOMOFO FINAL LETTER P", "Lo", 0, none),
  ("BOPOMOFO FINAL LETTER T", "Lo", 0, none),
  ("BOPOMOFO FINAL LETTER K", "Lo", 0, none),
  ("BOPOMOFO FINAL LETTER H", "Lo", 0, none),
  ("BOPOMOFO LETTER GH", "Lo", 0, none),
  ("BOPOMOFO LETTER LH", "Lo", 0, none),
  ("BOPOMOFO LETTER ZY", "Lo", 0, none),
  ("BOPOMOFO FINAL LETTER G", "Lo", 0, none),
  ("BOPOMOFO LETTER GW", "Lo", 0, none),
  ("BOPOMOFO LETTER KW", "Lo", 0, none),
  ("BOPOMOFO LETTER OE", "Lo", 0, none),
  ("BOPOMOFO LETTER AH", "Lo", 0, none),
)
