#let data = (
  ("ETHIOPIC SYLLABLE HA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE LA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE LU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE LI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE LAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE LEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE LE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE LO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE LWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HHA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HHU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HHI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HHAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HHEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HHE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HHO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE HHWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE MA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE MU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE MI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE MAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE MEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ME", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE MO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE MWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SZA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SZU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SZI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SZAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SZEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SZE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SZO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SZWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE RA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE RU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE RI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE RAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE REE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE RE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE RO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE RWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SHA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SHU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SHI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SHAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SHEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SHE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SHO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SHWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QWA", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE QWI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QWAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QWEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QWE", "Lo", 0, none),
  (),
  (),
  ("ETHIOPIC SYLLABLE QHA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QHU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QHI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QHAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QHEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QHE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QHO", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE QHWA", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE QHWI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QHWAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QHWEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QHWE", "Lo", 0, none),
  (),
  (),
  ("ETHIOPIC SYLLABLE BA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE VA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE VU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE VI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE VAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE VEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE VE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE VO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE VWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XWA", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE XWI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XWAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XWEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XWE", "Lo", 0, none),
  (),
  (),
  ("ETHIOPIC SYLLABLE NA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NYA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NYU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NYI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NYAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NYEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NYE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NYO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NYWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GLOTTAL A", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GLOTTAL U", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GLOTTAL I", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GLOTTAL AA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GLOTTAL EE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GLOTTAL E", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GLOTTAL O", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GLOTTAL WA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KWA", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE KWI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KWAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KWEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KWE", "Lo", 0, none),
  (),
  (),
  ("ETHIOPIC SYLLABLE KXA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KXU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KXI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KXAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KXEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KXE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KXO", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE KXWA", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE KXWI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KXWAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KXWEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KXWE", "Lo", 0, none),
  (),
  (),
  ("ETHIOPIC SYLLABLE WA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE WU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE WI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE WAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE WEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE WE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE WO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE WOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHARYNGEAL A", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHARYNGEAL U", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHARYNGEAL I", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHARYNGEAL AA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHARYNGEAL EE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHARYNGEAL E", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHARYNGEAL O", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE ZA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZHA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZHU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZHI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZHAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZHEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZHE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZHO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZHWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE YA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE YU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE YI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE YAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE YEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE YE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE YO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE YOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE JA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE JU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE JI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE JAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE JEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE JE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE JO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE JWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GWA", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE GWI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GWAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GWEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GWE", "Lo", 0, none),
  (),
  (),
  ("ETHIOPIC SYLLABLE GGA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GGU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GGI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GGAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GGEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GGE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GGO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GGWAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE THA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE THU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE THI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE THAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE THEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE THE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE THO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE THWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CHA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CHU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CHI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CHAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CHEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CHE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CHO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CHWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TSA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TSU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TSI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TSAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TSEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TSE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TSO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TSWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TZA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TZU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TZI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TZAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TZEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TZE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TZO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TZOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE FA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE FU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE FI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE FAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE FEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE FE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE FO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE FWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PO", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE RYA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE MYA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE FYA", "Lo", 0, none),
  (),
  (),
  ("ETHIOPIC COMBINING GEMINATION AND VOWEL LENGTH MARK", "Mn", 230, none),
  ("ETHIOPIC COMBINING VOWEL LENGTH MARK", "Mn", 230, none),
  ("ETHIOPIC COMBINING GEMINATION MARK", "Mn", 230, none),
  ("ETHIOPIC SECTION MARK", "Po", 0, none),
  ("ETHIOPIC WORDSPACE", "Po", 0, none),
  ("ETHIOPIC FULL STOP", "Po", 0, none),
  ("ETHIOPIC COMMA", "Po", 0, none),
  ("ETHIOPIC SEMICOLON", "Po", 0, none),
  ("ETHIOPIC COLON", "Po", 0, none),
  ("ETHIOPIC PREFACE COLON", "Po", 0, none),
  ("ETHIOPIC QUESTION MARK", "Po", 0, none),
  ("ETHIOPIC PARAGRAPH SEPARATOR", "Po", 0, none),
  ("ETHIOPIC DIGIT ONE", "No", 0, none),
  ("ETHIOPIC DIGIT TWO", "No", 0, none),
  ("ETHIOPIC DIGIT THREE", "No", 0, none),
  ("ETHIOPIC DIGIT FOUR", "No", 0, none),
  ("ETHIOPIC DIGIT FIVE", "No", 0, none),
  ("ETHIOPIC DIGIT SIX", "No", 0, none),
  ("ETHIOPIC DIGIT SEVEN", "No", 0, none),
  ("ETHIOPIC DIGIT EIGHT", "No", 0, none),
  ("ETHIOPIC DIGIT NINE", "No", 0, none),
  ("ETHIOPIC NUMBER TEN", "No", 0, none),
  ("ETHIOPIC NUMBER TWENTY", "No", 0, none),
  ("ETHIOPIC NUMBER THIRTY", "No", 0, none),
  ("ETHIOPIC NUMBER FORTY", "No", 0, none),
  ("ETHIOPIC NUMBER FIFTY", "No", 0, none),
  ("ETHIOPIC NUMBER SIXTY", "No", 0, none),
  ("ETHIOPIC NUMBER SEVENTY", "No", 0, none),
  ("ETHIOPIC NUMBER EIGHTY", "No", 0, none),
  ("ETHIOPIC NUMBER NINETY", "No", 0, none),
  ("ETHIOPIC NUMBER HUNDRED", "No", 0, none),
  ("ETHIOPIC NUMBER TEN THOUSAND", "No", 0, none),
)
