#let data = (
  ("THAANA LETTER HAA", "Lo", 0, none),
  ("THAANA LETTER SHAVIYANI", "Lo", 0, none),
  ("THAANA LETTER NOONU", "Lo", 0, none),
  ("THAANA LETTER RAA", "Lo", 0, none),
  ("THAANA LETTER BAA", "Lo", 0, none),
  ("THAANA LETTER LHAVIYANI", "Lo", 0, none),
  ("THAANA LETTER KAAFU", "Lo", 0, none),
  ("THAANA LETTER ALIFU", "Lo", 0, none),
  ("THAANA LETTER VAAVU", "Lo", 0, none),
  ("THAANA LETTER MEEMU", "Lo", 0, none),
  ("THAANA LETTER FAAFU", "Lo", 0, none),
  ("THAANA LETTER DHAALU", "Lo", 0, none),
  ("THAANA LETTER THAA", "Lo", 0, none),
  ("THAANA LETTER LAAMU", "Lo", 0, none),
  ("THAANA LETTER GAAFU", "Lo", 0, none),
  ("THAANA LETTER GNAVIYANI", "Lo", 0, none),
  ("THAANA LETTER SEENU", "Lo", 0, none),
  ("THAANA LETTER DAVIYANI", "Lo", 0, none),
  ("THAANA LETTER ZAVIYANI", "Lo", 0, none),
  ("THAANA LETTER TAVIYANI", "Lo", 0, none),
  ("THAANA LETTER YAA", "Lo", 0, none),
  ("THAANA LETTER PAVIYANI", "Lo", 0, none),
  ("THAANA LETTER JAVIYANI", "Lo", 0, none),
  ("THAANA LETTER CHAVIYANI", "Lo", 0, none),
  ("THAANA LETTER TTAA", "Lo", 0, none),
  ("THAANA LETTER HHAA", "Lo", 0, none),
  ("THAANA LETTER KHAA", "Lo", 0, none),
  ("THAANA LETTER THAALU", "Lo", 0, none),
  ("THAANA LETTER ZAA", "Lo", 0, none),
  ("THAANA LETTER SHEENU", "Lo", 0, none),
  ("THAANA LETTER SAADHU", "Lo", 0, none),
  ("THAANA LETTER DAADHU", "Lo", 0, none),
  ("THAANA LETTER TO", "Lo", 0, none),
  ("THAANA LETTER ZO", "Lo", 0, none),
  ("THAANA LETTER AINU", "Lo", 0, none),
  ("THAANA LETTER GHAINU", "Lo", 0, none),
  ("THAANA LETTER QAAFU", "Lo", 0, none),
  ("THAANA LETTER WAAVU", "Lo", 0, none),
  ("THAANA ABAFILI", "Mn", 0, none),
  ("THAANA AABAAFILI", "Mn", 0, none),
  ("THAANA IBIFILI", "Mn", 0, none),
  ("THAANA EEBEEFILI", "Mn", 0, none),
  ("THAANA UBUFILI", "Mn", 0, none),
  ("THAANA OOBOOFILI", "Mn", 0, none),
  ("THAANA EBEFILI", "Mn", 0, none),
  ("THAANA EYBEYFILI", "Mn", 0, none),
  ("THAANA OBOFILI", "Mn", 0, none),
  ("THAANA OABOAFILI", "Mn", 0, none),
  ("THAANA SUKUN", "Mn", 0, none),
  ("THAANA LETTER NAA", "Lo", 0, none),
)
