#let data = (
  ("LYDIAN LETTER A", "Lo", 0, none),
  ("LYDIAN LETTER B", "Lo", 0, none),
  ("LYDIAN LETTER G", "Lo", 0, none),
  ("LYDIAN LETTER D", "Lo", 0, none),
  ("LYDIAN LETTER E", "Lo", 0, none),
  ("LYDIAN LETTER V", "Lo", 0, none),
  ("LYDIAN LETTER I", "Lo", 0, none),
  ("LYDIAN LETTER Y", "Lo", 0, none),
  ("LYDIAN LETTER K", "Lo", 0, none),
  ("LYDIAN LETTER L", "Lo", 0, none),
  ("LYDIAN LETTER M", "Lo", 0, none),
  ("LYDIAN LETTER N", "Lo", 0, none),
  ("LYDIAN LETTER O", "Lo", 0, none),
  ("LYDIAN LETTER R", "Lo", 0, none),
  ("LYDIAN LETTER SS", "Lo", 0, none),
  ("LYDIAN LETTER T", "Lo", 0, none),
  ("LYDIAN LETTER U", "Lo", 0, none),
  ("LYDIAN LETTER F", "Lo", 0, none),
  ("LYDIAN LETTER Q", "Lo", 0, none),
  ("LYDIAN LETTER S", "Lo", 0, none),
  ("LYDIAN LETTER TT", "Lo", 0, none),
  ("LYDIAN LETTER AN", "Lo", 0, none),
  ("LYDIAN LETTER EN", "Lo", 0, none),
  ("LYDIAN LETTER LY", "Lo", 0, none),
  ("LYDIAN LETTER NN", "Lo", 0, none),
  ("LYDIAN LETTER C", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  ("LYDIAN TRIANGULAR MARK", "Po", 0, none),
)
