#let data = (
  ("SUNDANESE SIGN PANYECEK", "Mn", 0, none),
  ("SUNDANESE SIGN PANGLAYAR", "Mn", 0, none),
  ("SUNDANESE SIGN PANGWISAD", "Mc", 0, none),
  ("SUNDANESE LETTER A", "Lo", 0, none),
  ("SUNDANESE LETTER I", "Lo", 0, none),
  ("SUNDANESE LETTER U", "Lo", 0, none),
  ("SUNDANESE LETTER AE", "Lo", 0, none),
  ("SUNDANESE LETTER O", "Lo", 0, none),
  ("SUNDANESE LETTER E", "Lo", 0, none),
  ("SUNDANESE LETTER EU", "Lo", 0, none),
  ("SUNDANESE LETTER KA", "Lo", 0, none),
  ("SUNDANESE LETTER QA", "Lo", 0, none),
  ("SUNDANESE LETTER GA", "Lo", 0, none),
  ("SUNDANESE LETTER NGA", "Lo", 0, none),
  ("SUNDANESE LETTER CA", "Lo", 0, none),
  ("SUNDANESE LETTER JA", "Lo", 0, none),
  ("SUNDANESE LETTER ZA", "Lo", 0, none),
  ("SUNDANESE LETTER NYA", "Lo", 0, none),
  ("SUNDANESE LETTER TA", "Lo", 0, none),
  ("SUNDANESE LETTER DA", "Lo", 0, none),
  ("SUNDANESE LETTER NA", "Lo", 0, none),
  ("SUNDANESE LETTER PA", "Lo", 0, none),
  ("SUNDANESE LETTER FA", "Lo", 0, none),
  ("SUNDANESE LETTER VA", "Lo", 0, none),
  ("SUNDANESE LETTER BA", "Lo", 0, none),
  ("SUNDANESE LETTER MA", "Lo", 0, none),
  ("SUNDANESE LETTER YA", "Lo", 0, none),
  ("SUNDANESE LETTER RA", "Lo", 0, none),
  ("SUNDANESE LETTER LA", "Lo", 0, none),
  ("SUNDANESE LETTER WA", "Lo", 0, none),
  ("SUNDANESE LETTER SA", "Lo", 0, none),
  ("SUNDANESE LETTER XA", "Lo", 0, none),
  ("SUNDANESE LETTER HA", "Lo", 0, none),
  ("SUNDANESE CONSONANT SIGN PAMINGKAL", "Mc", 0, none),
  ("SUNDANESE CONSONANT SIGN PANYAKRA", "Mn", 0, none),
  ("SUNDANESE CONSONANT SIGN PANYIKU", "Mn", 0, none),
  ("SUNDANESE VOWEL SIGN PANGHULU", "Mn", 0, none),
  ("SUNDANESE VOWEL SIGN PANYUKU", "Mn", 0, none),
  ("SUNDANESE VOWEL SIGN PANAELAENG", "Mc", 0, none),
  ("SUNDANESE VOWEL SIGN PANOLONG", "Mc", 0, none),
  ("SUNDANESE VOWEL SIGN PAMEPET", "Mn", 0, none),
  ("SUNDANESE VOWEL SIGN PANEULEUNG", "Mn", 0, none),
  ("SUNDANESE SIGN PAMAAEH", "Mc", 9, none),
  ("SUNDANESE SIGN VIRAMA", "Mn", 9, none),
  ("SUNDANESE CONSONANT SIGN PASANGAN MA", "Mn", 0, none),
  ("SUNDANESE CONSONANT SIGN PASANGAN WA", "Mn", 0, none),
  ("SUNDANESE LETTER KHA", "Lo", 0, none),
  ("SUNDANESE LETTER SYA", "Lo", 0, none),
  ("SUNDANESE DIGIT ZERO", "Nd", 0, none),
  ("SUNDANESE DIGIT ONE", "Nd", 0, none),
  ("SUNDANESE DIGIT TWO", "Nd", 0, none),
  ("SUNDANESE DIGIT THREE", "Nd", 0, none),
  ("SUNDANESE DIGIT FOUR", "Nd", 0, none),
  ("SUNDANESE DIGIT FIVE", "Nd", 0, none),
  ("SUNDANESE DIGIT SIX", "Nd", 0, none),
  ("SUNDANESE DIGIT SEVEN", "Nd", 0, none),
  ("SUNDANESE DIGIT EIGHT", "Nd", 0, none),
  ("SUNDANESE DIGIT NINE", "Nd", 0, none),
  ("SUNDANESE AVAGRAHA", "Lo", 0, none),
  ("SUNDANESE LETTER REU", "Lo", 0, none),
  ("SUNDANESE LETTER LEU", "Lo", 0, none),
  ("SUNDANESE LETTER BHA", "Lo", 0, none),
  ("SUNDANESE LETTER FINAL K", "Lo", 0, none),
  ("SUNDANESE LETTER FINAL M", "Lo", 0, none),
)
