#let data = (
  ("ROMAN SEXTANS SIGN", "So", 0, none),
  ("ROMAN UNCIA SIGN", "So", 0, none),
  ("ROMAN SEMUNCIA SIGN", "So", 0, none),
  ("ROMAN SEXTULA SIGN", "So", 0, none),
  ("ROMAN DIMIDIA SEXTULA SIGN", "So", 0, none),
  ("ROMAN SILIQUA SIGN", "So", 0, none),
  ("ROMAN DENARIUS SIGN", "So", 0, none),
  ("ROMAN QUINARIUS SIGN", "So", 0, none),
  ("ROMAN SESTERTIUS SIGN", "So", 0, none),
  ("ROMAN DUPONDIUS SIGN", "So", 0, none),
  ("ROMAN AS SIGN", "So", 0, none),
  ("ROMAN CENTURIAL SIGN", "So", 0, none),
  ("ASCIA SYMBOL", "So", 0, none),
  (),
  (),
  (),
  ("GREEK SYMBOL TAU RHO", "So", 0, none),
)
