#let data = (
  ("TANGUT ITERATION MARK", "Lm", 0, none),
  ("NUSHU ITERATION MARK", "Lm", 0, none),
  ("OLD CHINESE HOOK MARK", "Po", 0, none),
  ("OLD CHINESE ITERATION MARK", "Lm", 0, none),
  ("KHITAN SMALL SCRIPT FILLER", "Mn", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("VIETNAMESE ALTERNATE READING MARK CA", "Mc", 6, none),
  ("VIETNAMESE ALTERNATE READING MARK NHAY", "Mc", 6, none),
  ("CHINESE SMALL SIMPLIFIED ER", "Lm", 0, none),
  ("CHINESE SMALL TRADITIONAL ER", "Lm", 0, none),
  ("YANGQIN SIGN SLOW ONE BEAT", "Nl", 0, none),
  ("YANGQIN SIGN SLOW THREE HALF BEATS", "Nl", 0, none),
  ("YANGQIN SIGN SLOW TWO BEATS", "Nl", 0, none),
)
