#let data = (
  ("KHUDAWADI LETTER A", "Lo", 0, none),
  ("KHUDAWADI LETTER AA", "Lo", 0, none),
  ("KHUDAWADI LETTER I", "Lo", 0, none),
  ("KHUDAWADI LETTER II", "Lo", 0, none),
  ("KHUDAWADI LETTER U", "Lo", 0, none),
  ("KHUDAWADI LETTER UU", "Lo", 0, none),
  ("KHUDAWADI LETTER E", "Lo", 0, none),
  ("KHUDAWADI LETTER AI", "Lo", 0, none),
  ("KHUDAWADI LETTER O", "Lo", 0, none),
  ("KHUDAWADI LETTER AU", "Lo", 0, none),
  ("KHUDAWADI LETTER KA", "Lo", 0, none),
  ("KHUDAWADI LETTER KHA", "Lo", 0, none),
  ("KHUDAWADI LETTER GA", "Lo", 0, none),
  ("KHUDAWADI LETTER GGA", "Lo", 0, none),
  ("KHUDAWADI LETTER GHA", "Lo", 0, none),
  ("KHUDAWADI LETTER NGA", "Lo", 0, none),
  ("KHUDAWADI LETTER CA", "Lo", 0, none),
  ("KHUDAWADI LETTER CHA", "Lo", 0, none),
  ("KHUDAWADI LETTER JA", "Lo", 0, none),
  ("KHUDAWADI LETTER JJA", "Lo", 0, none),
  ("KHUDAWADI LETTER JHA", "Lo", 0, none),
  ("KHUDAWADI LETTER NYA", "Lo", 0, none),
  ("KHUDAWADI LETTER TTA", "Lo", 0, none),
  ("KHUDAWADI LETTER TTHA", "Lo", 0, none),
  ("KHUDAWADI LETTER DDA", "Lo", 0, none),
  ("KHUDAWADI LETTER DDDA", "Lo", 0, none),
  ("KHUDAWADI LETTER RRA", "Lo", 0, none),
  ("KHUDAWADI LETTER DDHA", "Lo", 0, none),
  ("KHUDAWADI LETTER NNA", "Lo", 0, none),
  ("KHUDAWADI LETTER TA", "Lo", 0, none),
  ("KHUDAWADI LETTER THA", "Lo", 0, none),
  ("KHUDAWADI LETTER DA", "Lo", 0, none),
  ("KHUDAWADI LETTER DHA", "Lo", 0, none),
  ("KHUDAWADI LETTER NA", "Lo", 0, none),
  ("KHUDAWADI LETTER PA", "Lo", 0, none),
  ("KHUDAWADI LETTER PHA", "Lo", 0, none),
  ("KHUDAWADI LETTER BA", "Lo", 0, none),
  ("KHUDAWADI LETTER BBA", "Lo", 0, none),
  ("KHUDAWADI LETTER BHA", "Lo", 0, none),
  ("KHUDAWADI LETTER MA", "Lo", 0, none),
  ("KHUDAWADI LETTER YA", "Lo", 0, none),
  ("KHUDAWADI LETTER RA", "Lo", 0, none),
  ("KHUDAWADI LETTER LA", "Lo", 0, none),
  ("KHUDAWADI LETTER VA", "Lo", 0, none),
  ("KHUDAWADI LETTER SHA", "Lo", 0, none),
  ("KHUDAWADI LETTER SA", "Lo", 0, none),
  ("KHUDAWADI LETTER HA", "Lo", 0, none),
  ("KHUDAWADI SIGN ANUSVARA", "Mn", 0, none),
  ("KHUDAWADI VOWEL SIGN AA", "Mc", 0, none),
  ("KHUDAWADI VOWEL SIGN I", "Mc", 0, none),
  ("KHUDAWADI VOWEL SIGN II", "Mc", 0, none),
  ("KHUDAWADI VOWEL SIGN U", "Mn", 0, none),
  ("KHUDAWADI VOWEL SIGN UU", "Mn", 0, none),
  ("KHUDAWADI VOWEL SIGN E", "Mn", 0, none),
  ("KHUDAWADI VOWEL SIGN AI", "Mn", 0, none),
  ("KHUDAWADI VOWEL SIGN O", "Mn", 0, none),
  ("KHUDAWADI VOWEL SIGN AU", "Mn", 0, none),
  ("KHUDAWADI SIGN NUKTA", "Mn", 7, none),
  ("KHUDAWADI SIGN VIRAMA", "Mn", 9, none),
  (),
  (),
  (),
  (),
  (),
  ("KHUDAWADI DIGIT ZERO", "Nd", 0, none),
  ("KHUDAWADI DIGIT ONE", "Nd", 0, none),
  ("KHUDAWADI DIGIT TWO", "Nd", 0, none),
  ("KHUDAWADI DIGIT THREE", "Nd", 0, none),
  ("KHUDAWADI DIGIT FOUR", "Nd", 0, none),
  ("KHUDAWADI DIGIT FIVE", "Nd", 0, none),
  ("KHUDAWADI DIGIT SIX", "Nd", 0, none),
  ("KHUDAWADI DIGIT SEVEN", "Nd", 0, none),
  ("KHUDAWADI DIGIT EIGHT", "Nd", 0, none),
  ("KHUDAWADI DIGIT NINE", "Nd", 0, none),
)
