#let data = (
  (),
  ("ETHIOPIC SYLLABLE TTHU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TTHI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TTHAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TTHEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TTHE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TTHO", "Lo", 0, none),
  (),
  (),
  ("ETHIOPIC SYLLABLE DDHU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDHI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDHAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDHEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDHE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDHO", "Lo", 0, none),
  (),
  (),
  ("ETHIOPIC SYLLABLE DZU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DZI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DZAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DZEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DZE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DZO", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("ETHIOPIC SYLLABLE CCHHA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCHHU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCHHI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCHHAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCHHEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCHHE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCHHO", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE BBA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BBU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BBI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BBAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BBEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BBE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BBO", "Lo", 0, none),
)
