#let data = (
  ("GOTHIC LETTER AHSA", "Lo", 0, none),
  ("GOTHIC LETTER BAIRKAN", "Lo", 0, none),
  ("GOTHIC LETTER GIBA", "Lo", 0, none),
  ("GOTHIC LETTER DAGS", "Lo", 0, none),
  ("GOTHIC LETTER AIHVUS", "Lo", 0, none),
  ("GOTHIC LETTER QAIRTHRA", "Lo", 0, none),
  ("GOTHIC LETTER IUJA", "Lo", 0, none),
  ("GOTHIC LETTER HAGL", "Lo", 0, none),
  ("GOTHIC LETTER THIUTH", "Lo", 0, none),
  ("GOTHIC LETTER EIS", "Lo", 0, none),
  ("GOTHIC LETTER KUSMA", "Lo", 0, none),
  ("GOTHIC LETTER LAGUS", "Lo", 0, none),
  ("GOTHIC LETTER MANNA", "Lo", 0, none),
  ("GOTHIC LETTER NAUTHS", "Lo", 0, none),
  ("GOTHIC LETTER JER", "Lo", 0, none),
  ("GOTHIC LETTER URUS", "Lo", 0, none),
  ("GOTHIC LETTER PAIRTHRA", "Lo", 0, none),
  ("GOTHIC LETTER NINETY", "Nl", 0, none),
  ("GOTHIC LETTER RAIDA", "Lo", 0, none),
  ("GOTHIC LETTER SAUIL", "Lo", 0, none),
  ("GOTHIC LETTER TEIWS", "Lo", 0, none),
  ("GOTHIC LETTER WINJA", "Lo", 0, none),
  ("GOTHIC LETTER FAIHU", "Lo", 0, none),
  ("GOTHIC LETTER IGGWS", "Lo", 0, none),
  ("GOTHIC LETTER HWAIR", "Lo", 0, none),
  ("GOTHIC LETTER OTHAL", "Lo", 0, none),
  ("GOTHIC LETTER NINE HUNDRED", "Nl", 0, none),
)
