#let data = (
  ("TAMIL FRACTION ONE THREE-HUNDRED-AND-TWENTIETH", "No", 0, none),
  ("TAMIL FRACTION ONE ONE-HUNDRED-AND-SIXTIETH", "No", 0, none),
  ("TAMIL FRACTION ONE EIGHTIETH", "No", 0, none),
  ("TAMIL FRACTION ONE SIXTY-FOURTH", "No", 0, none),
  ("TAMIL FRACTION ONE FORTIETH", "No", 0, none),
  ("TAMIL FRACTION ONE THIRTY-SECOND", "No", 0, none),
  ("TAMIL FRACTION THREE EIGHTIETHS", "No", 0, none),
  ("TAMIL FRACTION THREE SIXTY-FOURTHS", "No", 0, none),
  ("TAMIL FRACTION ONE TWENTIETH", "No", 0, none),
  ("TAMIL FRACTION ONE SIXTEENTH-1", "No", 0, none),
  ("TAMIL FRACTION ONE SIXTEENTH-2", "No", 0, none),
  ("TAMIL FRACTION ONE TENTH", "No", 0, none),
  ("TAMIL FRACTION ONE EIGHTH", "No", 0, none),
  ("TAMIL FRACTION THREE TWENTIETHS", "No", 0, none),
  ("TAMIL FRACTION THREE SIXTEENTHS", "No", 0, none),
  ("TAMIL FRACTION ONE FIFTH", "No", 0, none),
  ("TAMIL FRACTION ONE QUARTER", "No", 0, none),
  ("TAMIL FRACTION ONE HALF-1", "No", 0, none),
  ("TAMIL FRACTION ONE HALF-2", "No", 0, none),
  ("TAMIL FRACTION THREE QUARTERS", "No", 0, none),
  ("TAMIL FRACTION DOWNSCALING FACTOR KIIZH", "No", 0, none),
  ("TAMIL SIGN NEL", "So", 0, none),
  ("TAMIL SIGN CEVITU", "So", 0, none),
  ("TAMIL SIGN AAZHAAKKU", "So", 0, none),
  ("TAMIL SIGN UZHAKKU", "So", 0, none),
  ("TAMIL SIGN MUUVUZHAKKU", "So", 0, none),
  ("TAMIL SIGN KURUNI", "So", 0, none),
  ("TAMIL SIGN PATHAKKU", "So", 0, none),
  ("TAMIL SIGN MUKKURUNI", "So", 0, none),
  ("TAMIL SIGN KAACU", "Sc", 0, none),
  ("TAMIL SIGN PANAM", "Sc", 0, none),
  ("TAMIL SIGN PON", "Sc", 0, none),
  ("TAMIL SIGN VARAAKAN", "Sc", 0, none),
  ("TAMIL SIGN PAARAM", "So", 0, none),
  ("TAMIL SIGN KUZHI", "So", 0, none),
  ("TAMIL SIGN VELI", "So", 0, none),
  ("TAMIL WET CULTIVATION SIGN", "So", 0, none),
  ("TAMIL DRY CULTIVATION SIGN", "So", 0, none),
  ("TAMIL LAND SIGN", "So", 0, none),
  ("TAMIL SALT PAN SIGN", "So", 0, none),
  ("TAMIL TRADITIONAL CREDIT SIGN", "So", 0, none),
  ("TAMIL TRADITIONAL NUMBER SIGN", "So", 0, none),
  ("TAMIL CURRENT SIGN", "So", 0, none),
  ("TAMIL AND ODD SIGN", "So", 0, none),
  ("TAMIL SPENT SIGN", "So", 0, none),
  ("TAMIL TOTAL SIGN", "So", 0, none),
  ("TAMIL IN POSSESSION SIGN", "So", 0, none),
  ("TAMIL STARTING FROM SIGN", "So", 0, none),
  ("TAMIL SIGN MUTHALIYA", "So", 0, none),
  ("TAMIL SIGN VAKAIYARAA", "So", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TAMIL PUNCTUATION END OF TEXT", "Po", 0, none),
)
