#let data = (
  ("BRAHMI SIGN CANDRABINDU", "Mc", 0, none),
  ("BRAHMI SIGN ANUSVARA", "Mn", 0, none),
  ("BRAHMI SIGN VISARGA", "Mc", 0, none),
  ("BRAHMI SIGN JIHVAMULIYA", "Lo", 0, none),
  ("BRAHMI SIGN UPADHMANIYA", "Lo", 0, none),
  ("BRAHMI LETTER A", "Lo", 0, none),
  ("BRAHMI LETTER AA", "Lo", 0, none),
  ("BRAHMI LETTER I", "Lo", 0, none),
  ("BRAHMI LETTER II", "Lo", 0, none),
  ("BRAHMI LETTER U", "Lo", 0, none),
  ("BRAHMI LETTER UU", "Lo", 0, none),
  ("BRAHMI LETTER VOCALIC R", "Lo", 0, none),
  ("BRAHMI LETTER VOCALIC RR", "Lo", 0, none),
  ("BRAHMI LETTER VOCALIC L", "Lo", 0, none),
  ("BRAHMI LETTER VOCALIC LL", "Lo", 0, none),
  ("BRAHMI LETTER E", "Lo", 0, none),
  ("BRAHMI LETTER AI", "Lo", 0, none),
  ("BRAHMI LETTER O", "Lo", 0, none),
  ("BRAHMI LETTER AU", "Lo", 0, none),
  ("BRAHMI LETTER KA", "Lo", 0, none),
  ("BRAHMI LETTER KHA", "Lo", 0, none),
  ("BRAHMI LETTER GA", "Lo", 0, none),
  ("BRAHMI LETTER GHA", "Lo", 0, none),
  ("BRAHMI LETTER NGA", "Lo", 0, none),
  ("BRAHMI LETTER CA", "Lo", 0, none),
  ("BRAHMI LETTER CHA", "Lo", 0, none),
  ("BRAHMI LETTER JA", "Lo", 0, none),
  ("BRAHMI LETTER JHA", "Lo", 0, none),
  ("BRAHMI LETTER NYA", "Lo", 0, none),
  ("BRAHMI LETTER TTA", "Lo", 0, none),
  ("BRAHMI LETTER TTHA", "Lo", 0, none),
  ("BRAHMI LETTER DDA", "Lo", 0, none),
  ("BRAHMI LETTER DDHA", "Lo", 0, none),
  ("BRAHMI LETTER NNA", "Lo", 0, none),
  ("BRAHMI LETTER TA", "Lo", 0, none),
  ("BRAHMI LETTER THA", "Lo", 0, none),
  ("BRAHMI LETTER DA", "Lo", 0, none),
  ("BRAHMI LETTER DHA", "Lo", 0, none),
  ("BRAHMI LETTER NA", "Lo", 0, none),
  ("BRAHMI LETTER PA", "Lo", 0, none),
  ("BRAHMI LETTER PHA", "Lo", 0, none),
  ("BRAHMI LETTER BA", "Lo", 0, none),
  ("BRAHMI LETTER BHA", "Lo", 0, none),
  ("BRAHMI LETTER MA", "Lo", 0, none),
  ("BRAHMI LETTER YA", "Lo", 0, none),
  ("BRAHMI LETTER RA", "Lo", 0, none),
  ("BRAHMI LETTER LA", "Lo", 0, none),
  ("BRAHMI LETTER VA", "Lo", 0, none),
  ("BRAHMI LETTER SHA", "Lo", 0, none),
  ("BRAHMI LETTER SSA", "Lo", 0, none),
  ("BRAHMI LETTER SA", "Lo", 0, none),
  ("BRAHMI LETTER HA", "Lo", 0, none),
  ("BRAHMI LETTER LLA", "Lo", 0, none),
  ("BRAHMI LETTER OLD TAMIL LLLA", "Lo", 0, none),
  ("BRAHMI LETTER OLD TAMIL RRA", "Lo", 0, none),
  ("BRAHMI LETTER OLD TAMIL NNNA", "Lo", 0, none),
  ("BRAHMI VOWEL SIGN AA", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN BHATTIPROLU AA", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN I", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN II", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN U", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN UU", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN VOCALIC R", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN VOCALIC RR", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN VOCALIC L", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN VOCALIC LL", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN E", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN AI", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN O", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN AU", "Mn", 0, none),
  ("BRAHMI VIRAMA", "Mn", 9, none),
  ("BRAHMI DANDA", "Po", 0, none),
  ("BRAHMI DOUBLE DANDA", "Po", 0, none),
  ("BRAHMI PUNCTUATION DOT", "Po", 0, none),
  ("BRAHMI PUNCTUATION DOUBLE DOT", "Po", 0, none),
  ("BRAHMI PUNCTUATION LINE", "Po", 0, none),
  ("BRAHMI PUNCTUATION CRESCENT BAR", "Po", 0, none),
  ("BRAHMI PUNCTUATION LOTUS", "Po", 0, none),
  (),
  (),
  (),
  (),
  ("BRAHMI NUMBER ONE", "No", 0, none),
  ("BRAHMI NUMBER TWO", "No", 0, none),
  ("BRAHMI NUMBER THREE", "No", 0, none),
  ("BRAHMI NUMBER FOUR", "No", 0, none),
  ("BRAHMI NUMBER FIVE", "No", 0, none),
  ("BRAHMI NUMBER SIX", "No", 0, none),
  ("BRAHMI NUMBER SEVEN", "No", 0, none),
  ("BRAHMI NUMBER EIGHT", "No", 0, none),
  ("BRAHMI NUMBER NINE", "No", 0, none),
  ("BRAHMI NUMBER TEN", "No", 0, none),
  ("BRAHMI NUMBER TWENTY", "No", 0, none),
  ("BRAHMI NUMBER THIRTY", "No", 0, none),
  ("BRAHMI NUMBER FORTY", "No", 0, none),
  ("BRAHMI NUMBER FIFTY", "No", 0, none),
  ("BRAHMI NUMBER SIXTY", "No", 0, none),
  ("BRAHMI NUMBER SEVENTY", "No", 0, none),
  ("BRAHMI NUMBER EIGHTY", "No", 0, none),
  ("BRAHMI NUMBER NINETY", "No", 0, none),
  ("BRAHMI NUMBER ONE HUNDRED", "No", 0, none),
  ("BRAHMI NUMBER ONE THOUSAND", "No", 0, none),
  ("BRAHMI DIGIT ZERO", "Nd", 0, none),
  ("BRAHMI DIGIT ONE", "Nd", 0, none),
  ("BRAHMI DIGIT TWO", "Nd", 0, none),
  ("BRAHMI DIGIT THREE", "Nd", 0, none),
  ("BRAHMI DIGIT FOUR", "Nd", 0, none),
  ("BRAHMI DIGIT FIVE", "Nd", 0, none),
  ("BRAHMI DIGIT SIX", "Nd", 0, none),
  ("BRAHMI DIGIT SEVEN", "Nd", 0, none),
  ("BRAHMI DIGIT EIGHT", "Nd", 0, none),
  ("BRAHMI DIGIT NINE", "Nd", 0, none),
  ("BRAHMI SIGN OLD TAMIL VIRAMA", "Mn", 9, none),
  ("BRAHMI LETTER OLD TAMIL SHORT E", "Lo", 0, none),
  ("BRAHMI LETTER OLD TAMIL SHORT O", "Lo", 0, none),
  ("BRAHMI VOWEL SIGN OLD TAMIL SHORT E", "Mn", 0, none),
  ("BRAHMI VOWEL SIGN OLD TAMIL SHORT O", "Mn", 0, none),
  ("BRAHMI LETTER OLD TAMIL LLA", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("BRAHMI NUMBER JOINER", "Mn", 9, none),
)
