#let data = (
  ("SMALL COMMA", "Po", 0, none),
  ("SMALL IDEOGRAPHIC COMMA", "Po", 0, none),
  ("SMALL FULL STOP", "Po", 0, none),
  (),
  ("SMALL SEMICOLON", "Po", 0, none),
  ("SMALL COLON", "Po", 0, none),
  ("SMALL QUESTION MARK", "Po", 0, none),
  ("SMALL EXCLAMATION MARK", "Po", 0, none),
  ("SMALL EM DASH", "Pd", 0, none),
  ("SMALL LEFT PARENTHESIS", "Ps", 0, none),
  ("SMALL RIGHT PARENTHESIS", "Pe", 0, none),
  ("SMALL LEFT CURLY BRACKET", "Ps", 0, none),
  ("SMALL RIGHT CURLY BRACKET", "Pe", 0, none),
  ("SMALL LEFT TORTOISE SHELL BRACKET", "Ps", 0, none),
  ("SMALL RIGHT TORTOISE SHELL BRACKET", "Pe", 0, none),
  ("SMALL NUMBER SIGN", "Po", 0, none),
  ("SMALL AMPERSAND", "Po", 0, none),
  ("SMALL ASTERISK", "Po", 0, "X"),
  ("SMALL PLUS SIGN", "Sm", 0, "X"),
  ("SMALL HYPHEN-MINUS", "Pd", 0, "X"),
  ("SMALL LESS-THAN SIGN", "Sm", 0, "X"),
  ("SMALL GREATER-THAN SIGN", "Sm", 0, "X"),
  ("SMALL EQUALS SIGN", "Sm", 0, "X"),
  (),
  ("SMALL REVERSE SOLIDUS", "Po", 0, "X"),
  ("SMALL DOLLAR SIGN", "Sc", 0, none),
  ("SMALL PERCENT SIGN", "Po", 0, none),
  ("SMALL COMMERCIAL AT", "Po", 0, none),
)
