#let data = (
  (),
  ("GUJARATI SIGN CANDRABINDU", "Mn", 0, none),
  ("GUJARATI SIGN ANUSVARA", "Mn", 0, none),
  ("GUJARATI SIGN VISARGA", "Mc", 0, none),
  (),
  ("GUJARATI LETTER A", "Lo", 0, none),
  ("GUJARATI LETTER AA", "Lo", 0, none),
  ("GUJARATI LETTER I", "Lo", 0, none),
  ("GUJARATI LETTER II", "Lo", 0, none),
  ("GUJARATI LETTER U", "Lo", 0, none),
  ("GUJARATI LETTER UU", "Lo", 0, none),
  ("GUJARATI LETTER VOCALIC R", "Lo", 0, none),
  ("GUJARATI LETTER VOCALIC L", "Lo", 0, none),
  ("GUJARATI VOWEL CANDRA E", "Lo", 0, none),
  (),
  ("GUJARATI LETTER E", "Lo", 0, none),
  ("GUJARATI LETTER AI", "Lo", 0, none),
  ("GUJARATI VOWEL CANDRA O", "Lo", 0, none),
  (),
  ("GUJARATI LETTER O", "Lo", 0, none),
  ("GUJARATI LETTER AU", "Lo", 0, none),
  ("GUJARATI LETTER KA", "Lo", 0, none),
  ("GUJARATI LETTER KHA", "Lo", 0, none),
  ("GUJARATI LETTER GA", "Lo", 0, none),
  ("GUJARATI LETTER GHA", "Lo", 0, none),
  ("GUJARATI LETTER NGA", "Lo", 0, none),
  ("GUJARATI LETTER CA", "Lo", 0, none),
  ("GUJARATI LETTER CHA", "Lo", 0, none),
  ("GUJARATI LETTER JA", "Lo", 0, none),
  ("GUJARATI LETTER JHA", "Lo", 0, none),
  ("GUJARATI LETTER NYA", "Lo", 0, none),
  ("GUJARATI LETTER TTA", "Lo", 0, none),
  ("GUJARATI LETTER TTHA", "Lo", 0, none),
  ("GUJARATI LETTER DDA", "Lo", 0, none),
  ("GUJARATI LETTER DDHA", "Lo", 0, none),
  ("GUJARATI LETTER NNA", "Lo", 0, none),
  ("GUJARATI LETTER TA", "Lo", 0, none),
  ("GUJARATI LETTER THA", "Lo", 0, none),
  ("GUJARATI LETTER DA", "Lo", 0, none),
  ("GUJARATI LETTER DHA", "Lo", 0, none),
  ("GUJARATI LETTER NA", "Lo", 0, none),
  (),
  ("GUJARATI LETTER PA", "Lo", 0, none),
  ("GUJARATI LETTER PHA", "Lo", 0, none),
  ("GUJARATI LETTER BA", "Lo", 0, none),
  ("GUJARATI LETTER BHA", "Lo", 0, none),
  ("GUJARATI LETTER MA", "Lo", 0, none),
  ("GUJARATI LETTER YA", "Lo", 0, none),
  ("GUJARATI LETTER RA", "Lo", 0, none),
  (),
  ("GUJARATI LETTER LA", "Lo", 0, none),
  ("GUJARATI LETTER LLA", "Lo", 0, none),
  (),
  ("GUJARATI LETTER VA", "Lo", 0, none),
  ("GUJARATI LETTER SHA", "Lo", 0, none),
  ("GUJARATI LETTER SSA", "Lo", 0, none),
  ("GUJARATI LETTER SA", "Lo", 0, none),
  ("GUJARATI LETTER HA", "Lo", 0, none),
  (),
  (),
  ("GUJARATI SIGN NUKTA", "Mn", 7, none),
  ("GUJARATI SIGN AVAGRAHA", "Lo", 0, none),
  ("GUJARATI VOWEL SIGN AA", "Mc", 0, none),
  ("GUJARATI VOWEL SIGN I", "Mc", 0, none),
  ("GUJARATI VOWEL SIGN II", "Mc", 0, none),
  ("GUJARATI VOWEL SIGN U", "Mn", 0, none),
  ("GUJARATI VOWEL SIGN UU", "Mn", 0, none),
  ("GUJARATI VOWEL SIGN VOCALIC R", "Mn", 0, none),
  ("GUJARATI VOWEL SIGN VOCALIC RR", "Mn", 0, none),
  ("GUJARATI VOWEL SIGN CANDRA E", "Mn", 0, none),
  (),
  ("GUJARATI VOWEL SIGN E", "Mn", 0, none),
  ("GUJARATI VOWEL SIGN AI", "Mn", 0, none),
  ("GUJARATI VOWEL SIGN CANDRA O", "Mc", 0, none),
  (),
  ("GUJARATI VOWEL SIGN O", "Mc", 0, none),
  ("GUJARATI VOWEL SIGN AU", "Mc", 0, none),
  ("GUJARATI SIGN VIRAMA", "Mn", 9, none),
  (),
  (),
  ("GUJARATI OM", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("GUJARATI LETTER VOCALIC RR", "Lo", 0, none),
  ("GUJARATI LETTER VOCALIC LL", "Lo", 0, none),
  ("GUJARATI VOWEL SIGN VOCALIC L", "Mn", 0, none),
  ("GUJARATI VOWEL SIGN VOCALIC LL", "Mn", 0, none),
  (),
  (),
  ("GUJARATI DIGIT ZERO", "Nd", 0, none),
  ("GUJARATI DIGIT ONE", "Nd", 0, none),
  ("GUJARATI DIGIT TWO", "Nd", 0, none),
  ("GUJARATI DIGIT THREE", "Nd", 0, none),
  ("GUJARATI DIGIT FOUR", "Nd", 0, none),
  ("GUJARATI DIGIT FIVE", "Nd", 0, none),
  ("GUJARATI DIGIT SIX", "Nd", 0, none),
  ("GUJARATI DIGIT SEVEN", "Nd", 0, none),
  ("GUJARATI DIGIT EIGHT", "Nd", 0, none),
  ("GUJARATI DIGIT NINE", "Nd", 0, none),
  ("GUJARATI ABBREVIATION SIGN", "Po", 0, none),
  ("GUJARATI RUPEE SIGN", "Sc", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("GUJARATI LETTER ZHA", "Lo", 0, none),
  ("GUJARATI SIGN SUKUN", "Mn", 0, none),
  ("GUJARATI SIGN SHADDA", "Mn", 0, none),
  ("GUJARATI SIGN MADDAH", "Mn", 0, none),
  ("GUJARATI SIGN THREE-DOT NUKTA ABOVE", "Mn", 0, none),
  ("GUJARATI SIGN CIRCLE NUKTA ABOVE", "Mn", 0, none),
  ("GUJARATI SIGN TWO-CIRCLE NUKTA ABOVE", "Mn", 0, none),
)
