#let data = (
  ("GARAY DIGIT ZERO", "Nd", 0, none),
  ("GARAY DIGIT ONE", "Nd", 0, none),
  ("GARAY DIGIT TWO", "Nd", 0, none),
  ("GARAY DIGIT THREE", "Nd", 0, none),
  ("GARAY DIGIT FOUR", "Nd", 0, none),
  ("GARAY DIGIT FIVE", "Nd", 0, none),
  ("GARAY DIGIT SIX", "Nd", 0, none),
  ("GARAY DIGIT SEVEN", "Nd", 0, none),
  ("GARAY DIGIT EIGHT", "Nd", 0, none),
  ("GARAY DIGIT NINE", "Nd", 0, none),
  ("GARAY VOWEL SIGN A", "Lo", 0, none),
  ("GARAY VOWEL SIGN I", "Lo", 0, none),
  ("GARAY VOWEL SIGN O", "Lo", 0, none),
  ("GARAY VOWEL SIGN EE", "Lo", 0, none),
  ("GARAY VOWEL LENGTH MARK", "Lm", 0, none),
  ("GARAY SUKUN", "Lo", 0, none),
  ("GARAY CAPITAL LETTER A", "Lu", 0, none),
  ("GARAY CAPITAL LETTER CA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER MA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER KA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER BA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER JA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER SA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER WA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER LA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER GA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER DA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER XA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER YA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER TA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER RA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER NYA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER FA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER NA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER PA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER HA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER OLD KA", "Lu", 0, none),
  ("GARAY CAPITAL LETTER OLD NA", "Lu", 0, none),
  (),
  (),
  (),
  ("GARAY VOWEL SIGN E", "Mn", 230, none),
  ("GARAY CONSONANT GEMINATION MARK", "Mn", 230, none),
  ("GARAY COMBINING DOT ABOVE", "Mn", 230, none),
  ("GARAY COMBINING DOUBLE DOT ABOVE", "Mn", 230, none),
  ("GARAY CONSONANT NASALIZATION MARK", "Mn", 230, none),
  ("GARAY HYPHEN", "Pd", 0, none),
  ("GARAY REDUPLICATION MARK", "Lm", 0, none),
  ("GARAY SMALL LETTER A", "Ll", 0, none),
  ("GARAY SMALL LETTER CA", "Ll", 0, none),
  ("GARAY SMALL LETTER MA", "Ll", 0, none),
  ("GARAY SMALL LETTER KA", "Ll", 0, none),
  ("GARAY SMALL LETTER BA", "Ll", 0, none),
  ("GARAY SMALL LETTER JA", "Ll", 0, none),
  ("GARAY SMALL LETTER SA", "Ll", 0, none),
  ("GARAY SMALL LETTER WA", "Ll", 0, none),
  ("GARAY SMALL LETTER LA", "Ll", 0, none),
  ("GARAY SMALL LETTER GA", "Ll", 0, none),
  ("GARAY SMALL LETTER DA", "Ll", 0, none),
  ("GARAY SMALL LETTER XA", "Ll", 0, none),
  ("GARAY SMALL LETTER YA", "Ll", 0, none),
  ("GARAY SMALL LETTER TA", "Ll", 0, none),
  ("GARAY SMALL LETTER RA", "Ll", 0, none),
  ("GARAY SMALL LETTER NYA", "Ll", 0, none),
  ("GARAY SMALL LETTER FA", "Ll", 0, none),
  ("GARAY SMALL LETTER NA", "Ll", 0, none),
  ("GARAY SMALL LETTER PA", "Ll", 0, none),
  ("GARAY SMALL LETTER HA", "Ll", 0, none),
  ("GARAY SMALL LETTER OLD KA", "Ll", 0, none),
  ("GARAY SMALL LETTER OLD NA", "Ll", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("GARAY PLUS SIGN", "Sm", 0, none),
  ("GARAY MINUS SIGN", "Sm", 0, none),
)
