#let data = (
  ("UPPER HALF BLOCK", "So", 0, none),
  ("LOWER ONE EIGHTH BLOCK", "So", 0, none),
  ("LOWER ONE QUARTER BLOCK", "So", 0, none),
  ("LOWER THREE EIGHTHS BLOCK", "So", 0, none),
  ("LOWER HALF BLOCK", "So", 0, none),
  ("LOWER FIVE EIGHTHS BLOCK", "So", 0, none),
  ("LOWER THREE QUARTERS BLOCK", "So", 0, none),
  ("LOWER SEVEN EIGHTHS BLOCK", "So", 0, none),
  ("FULL BLOCK", "So", 0, none),
  ("LEFT SEVEN EIGHTHS BLOCK", "So", 0, none),
  ("LEFT THREE QUARTERS BLOCK", "So", 0, none),
  ("LEFT FIVE EIGHTHS BLOCK", "So", 0, none),
  ("LEFT HALF BLOCK", "So", 0, none),
  ("LEFT THREE EIGHTHS BLOCK", "So", 0, none),
  ("LEFT ONE QUARTER BLOCK", "So", 0, none),
  ("LEFT ONE EIGHTH BLOCK", "So", 0, none),
  ("RIGHT HALF BLOCK", "So", 0, none),
  ("LIGHT SHADE", "So", 0, none),
  ("MEDIUM SHADE", "So", 0, none),
  ("DARK SHADE", "So", 0, none),
  ("UPPER ONE EIGHTH BLOCK", "So", 0, none),
  ("RIGHT ONE EIGHTH BLOCK", "So", 0, none),
  ("QUADRANT LOWER LEFT", "So", 0, none),
  ("QUADRANT LOWER RIGHT", "So", 0, none),
  ("QUADRANT UPPER LEFT", "So", 0, none),
  ("QUADRANT UPPER LEFT AND LOWER LEFT AND LOWER RIGHT", "So", 0, none),
  ("QUADRANT UPPER LEFT AND LOWER RIGHT", "So", 0, none),
  ("QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER LEFT", "So", 0, none),
  ("QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER RIGHT", "So", 0, none),
  ("QUADRANT UPPER RIGHT", "So", 0, none),
  ("QUADRANT UPPER RIGHT AND LOWER LEFT", "So", 0, none),
  ("QUADRANT UPPER RIGHT AND LOWER LEFT AND LOWER RIGHT", "So", 0, none),
)
