#let data = (
  ("SIDETIC LETTER N01", "Lo", 0, none),
  ("SIDETIC LETTER N02", "Lo", 0, none),
  ("SIDETIC LETTER N03", "Lo", 0, none),
  ("SIDETIC LETTER N04", "Lo", 0, none),
  ("SIDETIC LETTER N05", "Lo", 0, none),
  ("SIDETIC LETTER N06", "Lo", 0, none),
  ("SIDETIC LETTER N07", "Lo", 0, none),
  ("SIDETIC LETTER N08", "Lo", 0, none),
  ("SIDETIC LETTER N09", "Lo", 0, none),
  ("SIDETIC LETTER N10", "Lo", 0, none),
  ("SIDETIC LETTER N11", "Lo", 0, none),
  ("SIDETIC LETTER N12", "Lo", 0, none),
  ("SIDETIC LETTER N13", "Lo", 0, none),
  ("SIDETIC LETTER N14", "Lo", 0, none),
  ("SIDETIC LETTER N15", "Lo", 0, none),
  ("SIDETIC LETTER N16", "Lo", 0, none),
  ("SIDETIC LETTER N17", "Lo", 0, none),
  ("SIDETIC LETTER N18", "Lo", 0, none),
  ("SIDETIC LETTER N19", "Lo", 0, none),
  ("SIDETIC LETTER N20", "Lo", 0, none),
  ("SIDETIC LETTER N21", "Lo", 0, none),
  ("SIDETIC LETTER N22", "Lo", 0, none),
  ("SIDETIC LETTER N23", "Lo", 0, none),
  ("SIDETIC LETTER N24", "Lo", 0, none),
  ("SIDETIC LETTER N25", "Lo", 0, none),
  ("SIDETIC LETTER N26", "Lo", 0, none),
)
