#let data = (
  ("KATAKANA-HIRAGANA DOUBLE HYPHEN", "Pd", 0, none),
  ("KATAKANA LETTER SMALL A", "Lo", 0, none),
  ("KATAKANA LETTER A", "Lo", 0, none),
  ("KATAKANA LETTER SMALL I", "Lo", 0, none),
  ("KATAKANA LETTER I", "Lo", 0, none),
  ("KATAKANA LETTER SMALL U", "Lo", 0, none),
  ("KATAKANA LETTER U", "Lo", 0, none),
  ("KATAKANA LETTER SMALL E", "Lo", 0, none),
  ("KATAKANA LETTER E", "Lo", 0, none),
  ("KATAKANA LETTER SMALL O", "Lo", 0, none),
  ("KATAKANA LETTER O", "Lo", 0, none),
  ("KATAKANA LETTER KA", "Lo", 0, none),
  ("KATAKANA LETTER GA", "Lo", 0, none),
  ("KATAKANA LETTER KI", "Lo", 0, none),
  ("KATAKANA LETTER GI", "Lo", 0, none),
  ("KATAKANA LETTER KU", "Lo", 0, none),
  ("KATAKANA LETTER GU", "Lo", 0, none),
  ("KATAKANA LETTER KE", "Lo", 0, none),
  ("KATAKANA LETTER GE", "Lo", 0, none),
  ("KATAKANA LETTER KO", "Lo", 0, none),
  ("KATAKANA LETTER GO", "Lo", 0, none),
  ("KATAKANA LETTER SA", "Lo", 0, none),
  ("KATAKANA LETTER ZA", "Lo", 0, none),
  ("KATAKANA LETTER SI", "Lo", 0, none),
  ("KATAKANA LETTER ZI", "Lo", 0, none),
  ("KATAKANA LETTER SU", "Lo", 0, none),
  ("KATAKANA LETTER ZU", "Lo", 0, none),
  ("KATAKANA LETTER SE", "Lo", 0, none),
  ("KATAKANA LETTER ZE", "Lo", 0, none),
  ("KATAKANA LETTER SO", "Lo", 0, none),
  ("KATAKANA LETTER ZO", "Lo", 0, none),
  ("KATAKANA LETTER TA", "Lo", 0, none),
  ("KATAKANA LETTER DA", "Lo", 0, none),
  ("KATAKANA LETTER TI", "Lo", 0, none),
  ("KATAKANA LETTER DI", "Lo", 0, none),
  ("KATAKANA LETTER SMALL TU", "Lo", 0, none),
  ("KATAKANA LETTER TU", "Lo", 0, none),
  ("KATAKANA LETTER DU", "Lo", 0, none),
  ("KATAKANA LETTER TE", "Lo", 0, none),
  ("KATAKANA LETTER DE", "Lo", 0, none),
  ("KATAKANA LETTER TO", "Lo", 0, none),
  ("KATAKANA LETTER DO", "Lo", 0, none),
  ("KATAKANA LETTER NA", "Lo", 0, none),
  ("KATAKANA LETTER NI", "Lo", 0, none),
  ("KATAKANA LETTER NU", "Lo", 0, none),
  ("KATAKANA LETTER NE", "Lo", 0, none),
  ("KATAKANA LETTER NO", "Lo", 0, none),
  ("KATAKANA LETTER HA", "Lo", 0, none),
  ("KATAKANA LETTER BA", "Lo", 0, none),
  ("KATAKANA LETTER PA", "Lo", 0, none),
  ("KATAKANA LETTER HI", "Lo", 0, none),
  ("KATAKANA LETTER BI", "Lo", 0, none),
  ("KATAKANA LETTER PI", "Lo", 0, none),
  ("KATAKANA LETTER HU", "Lo", 0, none),
  ("KATAKANA LETTER BU", "Lo", 0, none),
  ("KATAKANA LETTER PU", "Lo", 0, none),
  ("KATAKANA LETTER HE", "Lo", 0, none),
  ("KATAKANA LETTER BE", "Lo", 0, none),
  ("KATAKANA LETTER PE", "Lo", 0, none),
  ("KATAKANA LETTER HO", "Lo", 0, none),
  ("KATAKANA LETTER BO", "Lo", 0, none),
  ("KATAKANA LETTER PO", "Lo", 0, none),
  ("KATAKANA LETTER MA", "Lo", 0, none),
  ("KATAKANA LETTER MI", "Lo", 0, none),
  ("KATAKANA LETTER MU", "Lo", 0, none),
  ("KATAKANA LETTER ME", "Lo", 0, none),
  ("KATAKANA LETTER MO", "Lo", 0, none),
  ("KATAKANA LETTER SMALL YA", "Lo", 0, none),
  ("KATAKANA LETTER YA", "Lo", 0, none),
  ("KATAKANA LETTER SMALL YU", "Lo", 0, none),
  ("KATAKANA LETTER YU", "Lo", 0, none),
  ("KATAKANA LETTER SMALL YO", "Lo", 0, none),
  ("KATAKANA LETTER YO", "Lo", 0, none),
  ("KATAKANA LETTER RA", "Lo", 0, none),
  ("KATAKANA LETTER RI", "Lo", 0, none),
  ("KATAKANA LETTER RU", "Lo", 0, none),
  ("KATAKANA LETTER RE", "Lo", 0, none),
  ("KATAKANA LETTER RO", "Lo", 0, none),
  ("KATAKANA LETTER SMALL WA", "Lo", 0, none),
  ("KATAKANA LETTER WA", "Lo", 0, none),
  ("KATAKANA LETTER WI", "Lo", 0, none),
  ("KATAKANA LETTER WE", "Lo", 0, none),
  ("KATAKANA LETTER WO", "Lo", 0, none),
  ("KATAKANA LETTER N", "Lo", 0, none),
  ("KATAKANA LETTER VU", "Lo", 0, none),
  ("KATAKANA LETTER SMALL KA", "Lo", 0, none),
  ("KATAKANA LETTER SMALL KE", "Lo", 0, none),
  ("KATAKANA LETTER VA", "Lo", 0, none),
  ("KATAKANA LETTER VI", "Lo", 0, none),
  ("KATAKANA LETTER VE", "Lo", 0, none),
  ("KATAKANA LETTER VO", "Lo", 0, none),
  ("KATAKANA MIDDLE DOT", "Po", 0, none),
  ("KATAKANA-HIRAGANA PROLONGED SOUND MARK", "Lm", 0, none),
  ("KATAKANA ITERATION MARK", "Lm", 0, none),
  ("KATAKANA VOICED ITERATION MARK", "Lm", 0, none),
  ("KATAKANA DIGRAPH KOTO", "Lo", 0, none),
)
