#let data = (
  ("TAI YO LETTER LOW KO", "Lo", 0, none),
  ("TAI YO LETTER HIGH KO", "Lo", 0, none),
  ("TAI YO LETTER LOW KHO", "Lo", 0, none),
  ("TAI YO LETTER HIGH KHO", "Lo", 0, none),
  ("TAI YO LETTER GO", "Lo", 0, none),
  ("TAI YO LETTER NGO", "Lo", 0, none),
  ("TAI YO LETTER CO", "Lo", 0, none),
  ("TAI YO LETTER LOW XO", "Lo", 0, none),
  ("TAI YO LETTER HIGH XO", "Lo", 0, none),
  ("TAI YO LETTER LOW NYO", "Lo", 0, none),
  ("TAI YO LETTER HIGH NYO", "Lo", 0, none),
  ("TAI YO LETTER DO", "Lo", 0, none),
  ("TAI YO LETTER LOW TO", "Lo", 0, none),
  ("TAI YO LETTER HIGH TO", "Lo", 0, none),
  ("TAI YO LETTER THO", "Lo", 0, none),
  ("TAI YO LETTER NO", "Lo", 0, none),
  ("TAI YO LETTER BO", "Lo", 0, none),
  ("TAI YO LETTER LOW PO", "Lo", 0, none),
  ("TAI YO LETTER HIGH PO", "Lo", 0, none),
  ("TAI YO LETTER PHO", "Lo", 0, none),
  ("TAI YO LETTER LOW FO", "Lo", 0, none),
  ("TAI YO LETTER HIGH FO", "Lo", 0, none),
  ("TAI YO LETTER MO", "Lo", 0, none),
  ("TAI YO LETTER YO", "Lo", 0, none),
  ("TAI YO LETTER LO", "Lo", 0, none),
  ("TAI YO LETTER VO", "Lo", 0, none),
  ("TAI YO LETTER LOW HO", "Lo", 0, none),
  ("TAI YO LETTER HIGH HO", "Lo", 0, none),
  ("TAI YO LETTER QO", "Lo", 0, none),
  ("TAI YO LETTER LOW KVO", "Lo", 0, none),
  ("TAI YO LETTER HIGH KVO", "Lo", 0, none),
  (),
  ("TAI YO LETTER AA", "Lo", 0, none),
  ("TAI YO LETTER I", "Lo", 0, none),
  ("TAI YO LETTER UE", "Lo", 0, none),
  ("TAI YO SIGN UE", "Mn", 230, none),
  ("TAI YO LETTER U", "Lo", 0, none),
  ("TAI YO LETTER AE", "Lo", 0, none),
  ("TAI YO SIGN AU", "Mn", 230, none),
  ("TAI YO LETTER O", "Lo", 0, none),
  ("TAI YO LETTER E", "Lo", 0, none),
  ("TAI YO LETTER IA", "Lo", 0, none),
  ("TAI YO LETTER UEA", "Lo", 0, none),
  ("TAI YO LETTER UA", "Lo", 0, none),
  ("TAI YO LETTER OO", "Lo", 0, none),
  ("TAI YO LETTER AUE", "Lo", 0, none),
  ("TAI YO SIGN AY", "Mn", 230, none),
  ("TAI YO SIGN ANG", "Mn", 230, none),
  ("TAI YO LETTER AN", "Lo", 0, none),
  ("TAI YO LETTER AM", "Lo", 0, none),
  ("TAI YO LETTER AK", "Lo", 0, none),
  ("TAI YO LETTER AT", "Lo", 0, none),
  ("TAI YO LETTER AP", "Lo", 0, none),
  ("TAI YO SIGN OM", "Mn", 230, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TAI YO SYMBOL MUEANG", "Lo", 0, none),
  ("TAI YO XAM LAI", "Lm", 0, none),
)
