#let data = (
  ("KAITHI SIGN CANDRABINDU", "Mn", 0, none),
  ("KAITHI SIGN ANUSVARA", "Mn", 0, none),
  ("KAITHI SIGN VISARGA", "Mc", 0, none),
  ("KAITHI LETTER A", "Lo", 0, none),
  ("KAITHI LETTER AA", "Lo", 0, none),
  ("KAITHI LETTER I", "Lo", 0, none),
  ("KAITHI LETTER II", "Lo", 0, none),
  ("KAITHI LETTER U", "Lo", 0, none),
  ("KAITHI LETTER UU", "Lo", 0, none),
  ("KAITHI LETTER E", "Lo", 0, none),
  ("KAITHI LETTER AI", "Lo", 0, none),
  ("KAITHI LETTER O", "Lo", 0, none),
  ("KAITHI LETTER AU", "Lo", 0, none),
  ("KAITHI LETTER KA", "Lo", 0, none),
  ("KAITHI LETTER KHA", "Lo", 0, none),
  ("KAITHI LETTER GA", "Lo", 0, none),
  ("KAITHI LETTER GHA", "Lo", 0, none),
  ("KAITHI LETTER NGA", "Lo", 0, none),
  ("KAITHI LETTER CA", "Lo", 0, none),
  ("KAITHI LETTER CHA", "Lo", 0, none),
  ("KAITHI LETTER JA", "Lo", 0, none),
  ("KAITHI LETTER JHA", "Lo", 0, none),
  ("KAITHI LETTER NYA", "Lo", 0, none),
  ("KAITHI LETTER TTA", "Lo", 0, none),
  ("KAITHI LETTER TTHA", "Lo", 0, none),
  ("KAITHI LETTER DDA", "Lo", 0, none),
  ("KAITHI LETTER DDDHA", "Lo", 0, none),
  ("KAITHI LETTER DDHA", "Lo", 0, none),
  ("KAITHI LETTER RHA", "Lo", 0, none),
  ("KAITHI LETTER NNA", "Lo", 0, none),
  ("KAITHI LETTER TA", "Lo", 0, none),
  ("KAITHI LETTER THA", "Lo", 0, none),
  ("KAITHI LETTER DA", "Lo", 0, none),
  ("KAITHI LETTER DHA", "Lo", 0, none),
  ("KAITHI LETTER NA", "Lo", 0, none),
  ("KAITHI LETTER PA", "Lo", 0, none),
  ("KAITHI LETTER PHA", "Lo", 0, none),
  ("KAITHI LETTER BA", "Lo", 0, none),
  ("KAITHI LETTER BHA", "Lo", 0, none),
  ("KAITHI LETTER MA", "Lo", 0, none),
  ("KAITHI LETTER YA", "Lo", 0, none),
  ("KAITHI LETTER RA", "Lo", 0, none),
  ("KAITHI LETTER LA", "Lo", 0, none),
  ("KAITHI LETTER VA", "Lo", 0, none),
  ("KAITHI LETTER SHA", "Lo", 0, none),
  ("KAITHI LETTER SSA", "Lo", 0, none),
  ("KAITHI LETTER SA", "Lo", 0, none),
  ("KAITHI LETTER HA", "Lo", 0, none),
  ("KAITHI VOWEL SIGN AA", "Mc", 0, none),
  ("KAITHI VOWEL SIGN I", "Mc", 0, none),
  ("KAITHI VOWEL SIGN II", "Mc", 0, none),
  ("KAITHI VOWEL SIGN U", "Mn", 0, none),
  ("KAITHI VOWEL SIGN UU", "Mn", 0, none),
  ("KAITHI VOWEL SIGN E", "Mn", 0, none),
  ("KAITHI VOWEL SIGN AI", "Mn", 0, none),
  ("KAITHI VOWEL SIGN O", "Mc", 0, none),
  ("KAITHI VOWEL SIGN AU", "Mc", 0, none),
  ("KAITHI SIGN VIRAMA", "Mn", 9, none),
  ("KAITHI SIGN NUKTA", "Mn", 7, none),
  ("KAITHI ABBREVIATION SIGN", "Po", 0, none),
  ("KAITHI ENUMERATION SIGN", "Po", 0, none),
  ("KAITHI NUMBER SIGN", "Cf", 0, none),
  ("KAITHI SECTION MARK", "Po", 0, none),
  ("KAITHI DOUBLE SECTION MARK", "Po", 0, none),
  ("KAITHI DANDA", "Po", 0, none),
  ("KAITHI DOUBLE DANDA", "Po", 0, none),
  ("KAITHI VOWEL SIGN VOCALIC R", "Mn", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("KAITHI NUMBER SIGN ABOVE", "Cf", 0, none),
)
