#let data = (
  ("VARIATION SELECTOR-1", "Mn", 0, "D"),
  ("VARIATION SELECTOR-2", "Mn", 0, none),
  ("VARIATION SELECTOR-3", "Mn", 0, none),
  ("VARIATION SELECTOR-4", "Mn", 0, none),
  ("VARIATION SELECTOR-5", "Mn", 0, none),
  ("VARIATION SELECTOR-6", "Mn", 0, none),
  ("VARIATION SELECTOR-7", "Mn", 0, none),
  ("VARIATION SELECTOR-8", "Mn", 0, none),
  ("VARIATION SELECTOR-9", "Mn", 0, none),
  ("VARIATION SELECTOR-10", "Mn", 0, none),
  ("VARIATION SELECTOR-11", "Mn", 0, none),
  ("VARIATION SELECTOR-12", "Mn", 0, none),
  ("VARIATION SELECTOR-13", "Mn", 0, none),
  ("VARIATION SELECTOR-14", "Mn", 0, none),
  ("VARIATION SELECTOR-15", "Mn", 0, none),
  ("VARIATION SELECTOR-16", "Mn", 0, none),
)
