#let data = (
  ("PAHAWH HMONG VOWEL KEEB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KEEV", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KIB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KIV", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KAUB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KAUV", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KUB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KUV", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KEB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KEV", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KAIB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KAIV", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KOOB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KOOV", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KAWB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KAWV", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KUAB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KUAV", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KOB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KOV", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KIAB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KIAV", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KAB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KAV", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KWB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KWV", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KAAB", "Lo", 0, none),
  ("PAHAWH HMONG VOWEL KAAV", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT VAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT NTSAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT LAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT HAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT NLAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT RAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT NKAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT QHAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT YAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT HLAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT MAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT CHAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT NCHAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT HNAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT PLHAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT NTHAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT NAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT AU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT XAU", "Lo", 0, none),
  ("PAHAWH HMONG CONSONANT CAU", "Lo", 0, none),
  ("PAHAWH HMONG MARK CIM TUB", "Mn", 230, none),
  ("PAHAWH HMONG MARK CIM SO", "Mn", 230, none),
  ("PAHAWH HMONG MARK CIM KES", "Mn", 230, none),
  ("PAHAWH HMONG MARK CIM KHAV", "Mn", 230, none),
  ("PAHAWH HMONG MARK CIM SUAM", "Mn", 230, none),
  ("PAHAWH HMONG MARK CIM HOM", "Mn", 230, none),
  ("PAHAWH HMONG MARK CIM TAUM", "Mn", 230, none),
  ("PAHAWH HMONG SIGN VOS THOM", "Po", 0, none),
  ("PAHAWH HMONG SIGN VOS TSHAB CEEB", "Po", 0, none),
  ("PAHAWH HMONG SIGN CIM CHEEM", "Po", 0, none),
  ("PAHAWH HMONG SIGN VOS THIAB", "Po", 0, none),
  ("PAHAWH HMONG SIGN VOS FEEM", "Po", 0, none),
  ("PAHAWH HMONG SIGN XYEEM NTXIV", "So", 0, none),
  ("PAHAWH HMONG SIGN XYEEM RHO", "So", 0, none),
  ("PAHAWH HMONG SIGN XYEEM TOV", "So", 0, none),
  ("PAHAWH HMONG SIGN XYEEM FAIB", "So", 0, none),
  ("PAHAWH HMONG SIGN VOS SEEV", "Lm", 0, none),
  ("PAHAWH HMONG SIGN MEEJ SUAB", "Lm", 0, none),
  ("PAHAWH HMONG SIGN VOS NRUA", "Lm", 0, none),
  ("PAHAWH HMONG SIGN IB YAM", "Lm", 0, none),
  ("PAHAWH HMONG SIGN XAUS", "Po", 0, none),
  ("PAHAWH HMONG SIGN CIM TSOV ROG", "So", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("PAHAWH HMONG DIGIT ZERO", "Nd", 0, none),
  ("PAHAWH HMONG DIGIT ONE", "Nd", 0, none),
  ("PAHAWH HMONG DIGIT TWO", "Nd", 0, none),
  ("PAHAWH HMONG DIGIT THREE", "Nd", 0, none),
  ("PAHAWH HMONG DIGIT FOUR", "Nd", 0, none),
  ("PAHAWH HMONG DIGIT FIVE", "Nd", 0, none),
  ("PAHAWH HMONG DIGIT SIX", "Nd", 0, none),
  ("PAHAWH HMONG DIGIT SEVEN", "Nd", 0, none),
  ("PAHAWH HMONG DIGIT EIGHT", "Nd", 0, none),
  ("PAHAWH HMONG DIGIT NINE", "Nd", 0, none),
  (),
  ("PAHAWH HMONG NUMBER TENS", "No", 0, none),
  ("PAHAWH HMONG NUMBER HUNDREDS", "No", 0, none),
  ("PAHAWH HMONG NUMBER TEN THOUSANDS", "No", 0, none),
  ("PAHAWH HMONG NUMBER MILLIONS", "No", 0, none),
  ("PAHAWH HMONG NUMBER HUNDRED MILLIONS", "No", 0, none),
  ("PAHAWH HMONG NUMBER TEN BILLIONS", "No", 0, none),
  ("PAHAWH HMONG NUMBER TRILLIONS", "No", 0, none),
  (),
  ("PAHAWH HMONG SIGN VOS LUB", "Lo", 0, none),
  ("PAHAWH HMONG SIGN XYOO", "Lo", 0, none),
  ("PAHAWH HMONG SIGN HLI", "Lo", 0, none),
  ("PAHAWH HMONG SIGN THIRD-STAGE HLI", "Lo", 0, none),
  ("PAHAWH HMONG SIGN ZWJ THAJ", "Lo", 0, none),
  ("PAHAWH HMONG SIGN HNUB", "Lo", 0, none),
  ("PAHAWH HMONG SIGN NQIG", "Lo", 0, none),
  ("PAHAWH HMONG SIGN XIAB", "Lo", 0, none),
  ("PAHAWH HMONG SIGN NTUJ", "Lo", 0, none),
  ("PAHAWH HMONG SIGN AV", "Lo", 0, none),
  ("PAHAWH HMONG SIGN TXHEEJ CEEV", "Lo", 0, none),
  ("PAHAWH HMONG SIGN MEEJ TSEEB", "Lo", 0, none),
  ("PAHAWH HMONG SIGN TAU", "Lo", 0, none),
  ("PAHAWH HMONG SIGN LOS", "Lo", 0, none),
  ("PAHAWH HMONG SIGN MUS", "Lo", 0, none),
  ("PAHAWH HMONG SIGN CIM HAIS LUS NTOG NTOG", "Lo", 0, none),
  ("PAHAWH HMONG SIGN CIM CUAM TSHOOJ", "Lo", 0, none),
  ("PAHAWH HMONG SIGN CIM TXWV", "Lo", 0, none),
  ("PAHAWH HMONG SIGN CIM TXWV CHWV", "Lo", 0, none),
  ("PAHAWH HMONG SIGN CIM PUB DAWB", "Lo", 0, none),
  ("PAHAWH HMONG SIGN CIM NRES TOS", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  ("PAHAWH HMONG CLAN SIGN TSHEEJ", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN YEEG", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN LIS", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN LAUJ", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN XYOOJ", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN KOO", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN HAWJ", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN MUAS", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN THOJ", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN TSAB", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN PHAB", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN KHAB", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN HAM", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN VAJ", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN FAJ", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN YAJ", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN TSWB", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN KWM", "Lo", 0, none),
  ("PAHAWH HMONG CLAN SIGN VWJ", "Lo", 0, none),
)
