#let data = (
  ("SYRIAC END OF PARAGRAPH", "Po", 0, none),
  ("SYRIAC SUPRALINEAR FULL STOP", "Po", 0, none),
  ("SYRIAC SUBLINEAR FULL STOP", "Po", 0, none),
  ("SYRIAC SUPRALINEAR COLON", "Po", 0, none),
  ("SYRIAC SUBLINEAR COLON", "Po", 0, none),
  ("SYRIAC HORIZONTAL COLON", "Po", 0, none),
  ("SYRIAC COLON SKEWED LEFT", "Po", 0, none),
  ("SYRIAC COLON SKEWED RIGHT", "Po", 0, none),
  ("SYRIAC SUPRALINEAR COLON SKEWED LEFT", "Po", 0, none),
  ("SYRIAC SUBLINEAR COLON SKEWED RIGHT", "Po", 0, none),
  ("SYRIAC CONTRACTION", "Po", 0, none),
  ("SYRIAC HARKLEAN OBELUS", "Po", 0, none),
  ("SYRIAC HARKLEAN METOBELUS", "Po", 0, none),
  ("SYRIAC HARKLEAN ASTERISCUS", "Po", 0, none),
  (),
  ("SYRIAC ABBREVIATION MARK", "Cf", 0, none),
  ("SYRIAC LETTER ALAPH", "Lo", 0, none),
  ("SYRIAC LETTER SUPERSCRIPT ALAPH", "Mn", 36, none),
  ("SYRIAC LETTER BETH", "Lo", 0, none),
  ("SYRIAC LETTER GAMAL", "Lo", 0, none),
  ("SYRIAC LETTER GAMAL GARSHUNI", "Lo", 0, none),
  ("SYRIAC LETTER DALATH", "Lo", 0, none),
  ("SYRIAC LETTER DOTLESS DALATH RISH", "Lo", 0, none),
  ("SYRIAC LETTER HE", "Lo", 0, none),
  ("SYRIAC LETTER WAW", "Lo", 0, none),
  ("SYRIAC LETTER ZAIN", "Lo", 0, none),
  ("SYRIAC LETTER HETH", "Lo", 0, none),
  ("SYRIAC LETTER TETH", "Lo", 0, none),
  ("SYRIAC LETTER TETH GARSHUNI", "Lo", 0, none),
  ("SYRIAC LETTER YUDH", "Lo", 0, none),
  ("SYRIAC LETTER YUDH HE", "Lo", 0, none),
  ("SYRIAC LETTER KAPH", "Lo", 0, none),
  ("SYRIAC LETTER LAMADH", "Lo", 0, none),
  ("SYRIAC LETTER MIM", "Lo", 0, none),
  ("SYRIAC LETTER NUN", "Lo", 0, none),
  ("SYRIAC LETTER SEMKATH", "Lo", 0, none),
  ("SYRIAC LETTER FINAL SEMKATH", "Lo", 0, none),
  ("SYRIAC LETTER E", "Lo", 0, none),
  ("SYRIAC LETTER PE", "Lo", 0, none),
  ("SYRIAC LETTER REVERSED PE", "Lo", 0, none),
  ("SYRIAC LETTER SADHE", "Lo", 0, none),
  ("SYRIAC LETTER QAPH", "Lo", 0, none),
  ("SYRIAC LETTER RISH", "Lo", 0, none),
  ("SYRIAC LETTER SHIN", "Lo", 0, none),
  ("SYRIAC LETTER TAW", "Lo", 0, none),
  ("SYRIAC LETTER PERSIAN BHETH", "Lo", 0, none),
  ("SYRIAC LETTER PERSIAN GHAMAL", "Lo", 0, none),
  ("SYRIAC LETTER PERSIAN DHALATH", "Lo", 0, none),
  ("SYRIAC PTHAHA ABOVE", "Mn", 230, none),
  ("SYRIAC PTHAHA BELOW", "Mn", 220, none),
  ("SYRIAC PTHAHA DOTTED", "Mn", 230, none),
  ("SYRIAC ZQAPHA ABOVE", "Mn", 230, none),
  ("SYRIAC ZQAPHA BELOW", "Mn", 220, none),
  ("SYRIAC ZQAPHA DOTTED", "Mn", 230, none),
  ("SYRIAC RBASA ABOVE", "Mn", 230, none),
  ("SYRIAC RBASA BELOW", "Mn", 220, none),
  ("SYRIAC DOTTED ZLAMA HORIZONTAL", "Mn", 220, none),
  ("SYRIAC DOTTED ZLAMA ANGULAR", "Mn", 220, none),
  ("SYRIAC HBASA ABOVE", "Mn", 230, none),
  ("SYRIAC HBASA BELOW", "Mn", 220, none),
  ("SYRIAC HBASA-ESASA DOTTED", "Mn", 220, none),
  ("SYRIAC ESASA ABOVE", "Mn", 230, none),
  ("SYRIAC ESASA BELOW", "Mn", 220, none),
  ("SYRIAC RWAHA", "Mn", 230, none),
  ("SYRIAC FEMININE DOT", "Mn", 230, none),
  ("SYRIAC QUSHSHAYA", "Mn", 230, none),
  ("SYRIAC RUKKAKHA", "Mn", 220, none),
  ("SYRIAC TWO VERTICAL DOTS ABOVE", "Mn", 230, none),
  ("SYRIAC TWO VERTICAL DOTS BELOW", "Mn", 220, none),
  ("SYRIAC THREE DOTS ABOVE", "Mn", 230, none),
  ("SYRIAC THREE DOTS BELOW", "Mn", 220, none),
  ("SYRIAC OBLIQUE LINE ABOVE", "Mn", 230, none),
  ("SYRIAC OBLIQUE LINE BELOW", "Mn", 220, none),
  ("SYRIAC MUSIC", "Mn", 230, none),
  ("SYRIAC BARREKH", "Mn", 230, none),
  (),
  (),
  ("SYRIAC LETTER SOGDIAN ZHAIN", "Lo", 0, none),
  ("SYRIAC LETTER SOGDIAN KHAPH", "Lo", 0, none),
  ("SYRIAC LETTER SOGDIAN FE", "Lo", 0, none),
)
