#let data = (
  ("BLACK LEFT-POINTING ISOSCELES RIGHT TRIANGLE", "So", 0, none),
  ("BLACK UP-POINTING ISOSCELES RIGHT TRIANGLE", "So", 0, none),
  ("BLACK RIGHT-POINTING ISOSCELES RIGHT TRIANGLE", "So", 0, none),
  ("BLACK DOWN-POINTING ISOSCELES RIGHT TRIANGLE", "So", 0, none),
  ("BLACK SLIGHTLY SMALL CIRCLE", "So", 0, "N"),
  ("MEDIUM BOLD WHITE CIRCLE", "So", 0, none),
  ("BOLD WHITE CIRCLE", "So", 0, none),
  ("HEAVY WHITE CIRCLE", "So", 0, none),
  ("VERY HEAVY WHITE CIRCLE", "So", 0, none),
  ("EXTREMELY HEAVY WHITE CIRCLE", "So", 0, none),
  ("WHITE CIRCLE CONTAINING BLACK SMALL CIRCLE", "So", 0, none),
  ("ROUND TARGET", "So", 0, none),
  ("BLACK TINY SQUARE", "So", 0, "N"),
  ("BLACK SLIGHTLY SMALL SQUARE", "So", 0, "N"),
  ("LIGHT WHITE SQUARE", "So", 0, none),
  ("MEDIUM WHITE SQUARE", "So", 0, none),
  ("BOLD WHITE SQUARE", "So", 0, none),
  ("HEAVY WHITE SQUARE", "So", 0, none),
  ("VERY HEAVY WHITE SQUARE", "So", 0, none),
  ("EXTREMELY HEAVY WHITE SQUARE", "So", 0, none),
  ("WHITE SQUARE CONTAINING BLACK VERY SMALL SQUARE", "So", 0, none),
  ("WHITE SQUARE CONTAINING BLACK MEDIUM SQUARE", "So", 0, none),
  ("SQUARE TARGET", "So", 0, none),
  ("BLACK TINY DIAMOND", "So", 0, "N"),
  ("BLACK VERY SMALL DIAMOND", "So", 0, "N"),
  ("BLACK MEDIUM SMALL DIAMOND", "So", 0, "N"),
  ("WHITE DIAMOND CONTAINING BLACK VERY SMALL DIAMOND", "So", 0, none),
  ("WHITE DIAMOND CONTAINING BLACK MEDIUM DIAMOND", "So", 0, none),
  ("DIAMOND TARGET", "So", 0, none),
  ("BLACK TINY LOZENGE", "So", 0, "N"),
  ("BLACK VERY SMALL LOZENGE", "So", 0, "N"),
  ("BLACK MEDIUM SMALL LOZENGE", "So", 0, "N"),
  ("WHITE LOZENGE CONTAINING BLACK SMALL LOZENGE", "So", 0, none),
  ("THIN GREEK CROSS", "So", 0, none),
  ("LIGHT GREEK CROSS", "So", 0, none),
  ("MEDIUM GREEK CROSS", "So", 0, none),
  ("BOLD GREEK CROSS", "So", 0, none),
  ("VERY BOLD GREEK CROSS", "So", 0, none),
  ("VERY HEAVY GREEK CROSS", "So", 0, none),
  ("EXTREMELY HEAVY GREEK CROSS", "So", 0, none),
  ("THIN SALTIRE", "So", 0, none),
  ("LIGHT SALTIRE", "So", 0, none),
  ("MEDIUM SALTIRE", "So", 0, none),
  ("BOLD SALTIRE", "So", 0, none),
  ("HEAVY SALTIRE", "So", 0, none),
  ("VERY HEAVY SALTIRE", "So", 0, none),
  ("EXTREMELY HEAVY SALTIRE", "So", 0, none),
  ("LIGHT FIVE SPOKED ASTERISK", "So", 0, none),
  ("MEDIUM FIVE SPOKED ASTERISK", "So", 0, none),
  ("BOLD FIVE SPOKED ASTERISK", "So", 0, none),
  ("HEAVY FIVE SPOKED ASTERISK", "So", 0, none),
  ("VERY HEAVY FIVE SPOKED ASTERISK", "So", 0, none),
  ("EXTREMELY HEAVY FIVE SPOKED ASTERISK", "So", 0, none),
  ("LIGHT SIX SPOKED ASTERISK", "So", 0, none),
  ("MEDIUM SIX SPOKED ASTERISK", "So", 0, none),
  ("BOLD SIX SPOKED ASTERISK", "So", 0, none),
  ("HEAVY SIX SPOKED ASTERISK", "So", 0, none),
  ("VERY HEAVY SIX SPOKED ASTERISK", "So", 0, none),
  ("EXTREMELY HEAVY SIX SPOKED ASTERISK", "So", 0, none),
  ("LIGHT EIGHT SPOKED ASTERISK", "So", 0, none),
  ("MEDIUM EIGHT SPOKED ASTERISK", "So", 0, none),
  ("BOLD EIGHT SPOKED ASTERISK", "So", 0, none),
  ("HEAVY EIGHT SPOKED ASTERISK", "So", 0, none),
  ("VERY HEAVY EIGHT SPOKED ASTERISK", "So", 0, none),
  ("LIGHT THREE POINTED BLACK STAR", "So", 0, none),
  ("MEDIUM THREE POINTED BLACK STAR", "So", 0, none),
  ("THREE POINTED BLACK STAR", "So", 0, none),
  ("MEDIUM THREE POINTED PINWHEEL STAR", "So", 0, none),
  ("LIGHT FOUR POINTED BLACK STAR", "So", 0, none),
  ("MEDIUM FOUR POINTED BLACK STAR", "So", 0, none),
  ("FOUR POINTED BLACK STAR", "So", 0, none),
  ("MEDIUM FOUR POINTED PINWHEEL STAR", "So", 0, none),
  ("REVERSE LIGHT FOUR POINTED PINWHEEL STAR", "So", 0, none),
  ("LIGHT FIVE POINTED BLACK STAR", "So", 0, none),
  ("HEAVY FIVE POINTED BLACK STAR", "So", 0, none),
  ("MEDIUM SIX POINTED BLACK STAR", "So", 0, none),
  ("HEAVY SIX POINTED BLACK STAR", "So", 0, none),
  ("SIX POINTED PINWHEEL STAR", "So", 0, none),
  ("MEDIUM EIGHT POINTED BLACK STAR", "So", 0, none),
  ("HEAVY EIGHT POINTED BLACK STAR", "So", 0, none),
  ("VERY HEAVY EIGHT POINTED BLACK STAR", "So", 0, none),
  ("HEAVY EIGHT POINTED PINWHEEL STAR", "So", 0, none),
  ("LIGHT TWELVE POINTED BLACK STAR", "So", 0, none),
  ("HEAVY TWELVE POINTED BLACK STAR", "So", 0, none),
  ("HEAVY TWELVE POINTED PINWHEEL STAR", "So", 0, none),
  ("CIRCLED TRIANGLE", "So", 0, none),
  ("NEGATIVE CIRCLED TRIANGLE", "So", 0, none),
  ("CIRCLED SQUARE", "So", 0, none),
  ("NEGATIVE CIRCLED SQUARE", "So", 0, none),
  ("NINE POINTED WHITE STAR", "So", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  ("LARGE ORANGE CIRCLE", "So", 0, none),
  ("LARGE YELLOW CIRCLE", "So", 0, none),
  ("LARGE GREEN CIRCLE", "So", 0, none),
  ("LARGE PURPLE CIRCLE", "So", 0, none),
  ("LARGE BROWN CIRCLE", "So", 0, none),
  ("LARGE RED SQUARE", "So", 0, none),
  ("LARGE BLUE SQUARE", "So", 0, none),
  ("LARGE ORANGE SQUARE", "So", 0, none),
  ("LARGE YELLOW SQUARE", "So", 0, none),
  ("LARGE GREEN SQUARE", "So", 0, none),
  ("LARGE PURPLE SQUARE", "So", 0, none),
  ("LARGE BROWN SQUARE", "So", 0, none),
  (),
  (),
  (),
  (),
  ("HEAVY EQUALS SIGN", "So", 0, none),
)
