#let data = (
  ("KAKTOVIK NUMERAL ZERO", "No", 0, none),
  ("KAKTOVIK NUMERAL ONE", "No", 0, none),
  ("KAKTOVIK NUMERAL TWO", "No", 0, none),
  ("KAKTOVIK NUMERAL THREE", "No", 0, none),
  ("KAKTOVIK NUMERAL FOUR", "No", 0, none),
  ("KAKTOVIK NUMERAL FIVE", "No", 0, none),
  ("KAKTOVIK NUMERAL SIX", "No", 0, none),
  ("KAKTOVIK NUMERAL SEVEN", "No", 0, none),
  ("KAKTOVIK NUMERAL EIGHT", "No", 0, none),
  ("KAKTOVIK NUMERAL NINE", "No", 0, none),
  ("KAKTOVIK NUMERAL TEN", "No", 0, none),
  ("KAKTOVIK NUMERAL ELEVEN", "No", 0, none),
  ("KAKTOVIK NUMERAL TWELVE", "No", 0, none),
  ("KAKTOVIK NUMERAL THIRTEEN", "No", 0, none),
  ("KAKTOVIK NUMERAL FOURTEEN", "No", 0, none),
  ("KAKTOVIK NUMERAL FIFTEEN", "No", 0, none),
  ("KAKTOVIK NUMERAL SIXTEEN", "No", 0, none),
  ("KAKTOVIK NUMERAL SEVENTEEN", "No", 0, none),
  ("KAKTOVIK NUMERAL EIGHTEEN", "No", 0, none),
  ("KAKTOVIK NUMERAL NINETEEN", "No", 0, none),
)
