#let data = (
  ("KHMER SYMBOL PATHAMASAT", "So", 0, none),
  ("KHMER SYMBOL MUOY KOET", "So", 0, none),
  ("KHMER SYMBOL PII KOET", "So", 0, none),
  ("KHMER SYMBOL BEI KOET", "So", 0, none),
  ("KHMER SYMBOL BUON KOET", "So", 0, none),
  ("KHMER SYMBOL PRAM KOET", "So", 0, none),
  ("KHMER SYMBOL PRAM-MUOY KOET", "So", 0, none),
  ("KHMER SYMBOL PRAM-PII KOET", "So", 0, none),
  ("KHMER SYMBOL PRAM-BEI KOET", "So", 0, none),
  ("KHMER SYMBOL PRAM-BUON KOET", "So", 0, none),
  ("KHMER SYMBOL DAP KOET", "So", 0, none),
  ("KHMER SYMBOL DAP-MUOY KOET", "So", 0, none),
  ("KHMER SYMBOL DAP-PII KOET", "So", 0, none),
  ("KHMER SYMBOL DAP-BEI KOET", "So", 0, none),
  ("KHMER SYMBOL DAP-BUON KOET", "So", 0, none),
  ("KHMER SYMBOL DAP-PRAM KOET", "So", 0, none),
  ("KHMER SYMBOL TUTEYASAT", "So", 0, none),
  ("KHMER SYMBOL MUOY ROC", "So", 0, none),
  ("KHMER SYMBOL PII ROC", "So", 0, none),
  ("KHMER SYMBOL BEI ROC", "So", 0, none),
  ("KHMER SYMBOL BUON ROC", "So", 0, none),
  ("KHMER SYMBOL PRAM ROC", "So", 0, none),
  ("KHMER SYMBOL PRAM-MUOY ROC", "So", 0, none),
  ("KHMER SYMBOL PRAM-PII ROC", "So", 0, none),
  ("KHMER SYMBOL PRAM-BEI ROC", "So", 0, none),
  ("KHMER SYMBOL PRAM-BUON ROC", "So", 0, none),
  ("KHMER SYMBOL DAP ROC", "So", 0, none),
  ("KHMER SYMBOL DAP-MUOY ROC", "So", 0, none),
  ("KHMER SYMBOL DAP-PII ROC", "So", 0, none),
  ("KHMER SYMBOL DAP-BEI ROC", "So", 0, none),
  ("KHMER SYMBOL DAP-BUON ROC", "So", 0, none),
  ("KHMER SYMBOL DAP-PRAM ROC", "So", 0, none),
)
