#let data = (
  ("SYLOTI NAGRI LETTER A", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER I", "Lo", 0, none),
  ("SYLOTI NAGRI SIGN DVISVARA", "Mn", 0, none),
  ("SYLOTI NAGRI LETTER U", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER E", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER O", "Lo", 0, none),
  ("SYLOTI NAGRI SIGN HASANTA", "Mn", 9, none),
  ("SYLOTI NAGRI LETTER KO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER KHO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER GO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER GHO", "Lo", 0, none),
  ("SYLOTI NAGRI SIGN ANUSVARA", "Mn", 0, none),
  ("SYLOTI NAGRI LETTER CO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER CHO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER JO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER JHO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER TTO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER TTHO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER DDO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER DDHO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER TO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER THO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER DO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER DHO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER NO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER PO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER PHO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER BO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER BHO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER MO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER RO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER LO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER RRO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER SO", "Lo", 0, none),
  ("SYLOTI NAGRI LETTER HO", "Lo", 0, none),
  ("SYLOTI NAGRI VOWEL SIGN A", "Mc", 0, none),
  ("SYLOTI NAGRI VOWEL SIGN I", "Mc", 0, none),
  ("SYLOTI NAGRI VOWEL SIGN U", "Mn", 0, none),
  ("SYLOTI NAGRI VOWEL SIGN E", "Mn", 0, none),
  ("SYLOTI NAGRI VOWEL SIGN OO", "Mc", 0, none),
  ("SYLOTI NAGRI POETRY MARK-1", "So", 0, none),
  ("SYLOTI NAGRI POETRY MARK-2", "So", 0, none),
  ("SYLOTI NAGRI POETRY MARK-3", "So", 0, none),
  ("SYLOTI NAGRI POETRY MARK-4", "So", 0, none),
  ("SYLOTI NAGRI SIGN ALTERNATE HASANTA", "Mn", 9, none),
)
