#let data = (
  ("RIGHT ANGLE SUBSTITUTION MARKER", "Po", 0, none),
  ("RIGHT ANGLE DOTTED SUBSTITUTION MARKER", "Po", 0, none),
  ("LEFT SUBSTITUTION BRACKET", "Pi", 0, none),
  ("RIGHT SUBSTITUTION BRACKET", "Pf", 0, none),
  ("LEFT DOTTED SUBSTITUTION BRACKET", "Pi", 0, none),
  ("RIGHT DOTTED SUBSTITUTION BRACKET", "Pf", 0, none),
  ("RAISED INTERPOLATION MARKER", "Po", 0, none),
  ("RAISED DOTTED INTERPOLATION MARKER", "Po", 0, none),
  ("DOTTED TRANSPOSITION MARKER", "Po", 0, none),
  ("LEFT TRANSPOSITION BRACKET", "Pi", 0, none),
  ("RIGHT TRANSPOSITION BRACKET", "Pf", 0, none),
  ("RAISED SQUARE", "Po", 0, none),
  ("LEFT RAISED OMISSION BRACKET", "Pi", 0, none),
  ("RIGHT RAISED OMISSION BRACKET", "Pf", 0, none),
  ("EDITORIAL CORONIS", "Po", 0, none),
  ("PARAGRAPHOS", "Po", 0, none),
  ("FORKED PARAGRAPHOS", "Po", 0, none),
  ("REVERSED FORKED PARAGRAPHOS", "Po", 0, none),
  ("HYPODIASTOLE", "Po", 0, none),
  ("DOTTED OBELOS", "Po", 0, none),
  ("DOWNWARDS ANCORA", "Po", 0, none),
  ("UPWARDS ANCORA", "Po", 0, none),
  ("DOTTED RIGHT-POINTING ANGLE", "Po", 0, none),
  ("DOUBLE OBLIQUE HYPHEN", "Pd", 0, none),
  ("INVERTED INTERROBANG", "Po", 0, none),
  ("PALM BRANCH", "Po", 0, none),
  ("HYPHEN WITH DIAERESIS", "Pd", 0, none),
  ("TILDE WITH RING ABOVE", "Po", 0, none),
  ("LEFT LOW PARAPHRASE BRACKET", "Pi", 0, none),
  ("RIGHT LOW PARAPHRASE BRACKET", "Pf", 0, none),
  ("TILDE WITH DOT ABOVE", "Po", 0, none),
  ("TILDE WITH DOT BELOW", "Po", 0, none),
  ("LEFT VERTICAL BAR WITH QUILL", "Pi", 0, none),
  ("RIGHT VERTICAL BAR WITH QUILL", "Pf", 0, none),
  ("TOP LEFT HALF BRACKET", "Ps", 0, none),
  ("TOP RIGHT HALF BRACKET", "Pe", 0, none),
  ("BOTTOM LEFT HALF BRACKET", "Ps", 0, none),
  ("BOTTOM RIGHT HALF BRACKET", "Pe", 0, none),
  ("LEFT SIDEWAYS U BRACKET", "Ps", 0, none),
  ("RIGHT SIDEWAYS U BRACKET", "Pe", 0, none),
  ("LEFT DOUBLE PARENTHESIS", "Ps", 0, none),
  ("RIGHT DOUBLE PARENTHESIS", "Pe", 0, none),
  ("TWO DOTS OVER ONE DOT PUNCTUATION", "Po", 0, none),
  ("ONE DOT OVER TWO DOTS PUNCTUATION", "Po", 0, none),
  ("SQUARED FOUR DOT PUNCTUATION", "Po", 0, none),
  ("FIVE DOT MARK", "Po", 0, none),
  ("REVERSED QUESTION MARK", "Po", 0, none),
  ("VERTICAL TILDE", "Lm", 0, none),
  ("RING POINT", "Po", 0, none),
  ("WORD SEPARATOR MIDDLE DOT", "Po", 0, none),
  ("TURNED COMMA", "Po", 0, none),
  ("RAISED DOT", "Po", 0, none),
  ("RAISED COMMA", "Po", 0, none),
  ("TURNED SEMICOLON", "Po", 0, none),
  ("DAGGER WITH LEFT GUARD", "Po", 0, none),
  ("DAGGER WITH RIGHT GUARD", "Po", 0, none),
  ("TURNED DAGGER", "Po", 0, none),
  ("TOP HALF SECTION SIGN", "Po", 0, none),
  ("TWO-EM DASH", "Pd", 0, none),
  ("THREE-EM DASH", "Pd", 0, none),
  ("STENOGRAPHIC FULL STOP", "Po", 0, none),
  ("VERTICAL SIX DOTS", "Po", 0, none),
  ("WIGGLY VERTICAL LINE", "Po", 0, none),
  ("CAPITULUM", "Po", 0, none),
  ("DOUBLE HYPHEN", "Pd", 0, none),
  ("REVERSED COMMA", "Po", 0, none),
  ("DOUBLE LOW-REVERSED-9 QUOTATION MARK", "Ps", 0, none),
  ("DASH WITH LEFT UPTURN", "Po", 0, none),
  ("DOUBLE SUSPENSION MARK", "Po", 0, none),
  ("INVERTED LOW KAVYKA", "Po", 0, none),
  ("INVERTED LOW KAVYKA WITH KAVYKA ABOVE", "Po", 0, none),
  ("LOW KAVYKA", "Po", 0, none),
  ("LOW KAVYKA WITH DOT", "Po", 0, none),
  ("DOUBLE STACKED COMMA", "Po", 0, none),
  ("DOTTED SOLIDUS", "Po", 0, none),
  ("TRIPLE DAGGER", "Po", 0, none),
  ("MEDIEVAL COMMA", "Po", 0, none),
  ("PARAGRAPHUS MARK", "Po", 0, none),
  ("PUNCTUS ELEVATUS MARK", "Po", 0, none),
  ("CORNISH VERSE DIVIDER", "Po", 0, none),
  ("CROSS PATTY WITH RIGHT CROSSBAR", "So", 0, none),
  ("CROSS PATTY WITH LEFT CROSSBAR", "So", 0, none),
  ("TIRONIAN SIGN CAPITAL ET", "Po", 0, none),
  ("MEDIEVAL EXCLAMATION MARK", "Po", 0, none),
  ("MEDIEVAL QUESTION MARK", "Po", 0, none),
  ("LEFT SQUARE BRACKET WITH STROKE", "Ps", 0, none),
  ("RIGHT SQUARE BRACKET WITH STROKE", "Pe", 0, none),
  ("LEFT SQUARE BRACKET WITH DOUBLE STROKE", "Ps", 0, none),
  ("RIGHT SQUARE BRACKET WITH DOUBLE STROKE", "Pe", 0, none),
  ("TOP HALF LEFT PARENTHESIS", "Ps", 0, none),
  ("TOP HALF RIGHT PARENTHESIS", "Pe", 0, none),
  ("BOTTOM HALF LEFT PARENTHESIS", "Ps", 0, none),
  ("BOTTOM HALF RIGHT PARENTHESIS", "Pe", 0, none),
  ("OBLIQUE HYPHEN", "Pd", 0, none),
)
