#let data = (
  ("CYCLONE", "So", 0, none),
  ("FOGGY", "So", 0, none),
  ("CLOSED UMBRELLA", "So", 0, none),
  ("NIGHT WITH STARS", "So", 0, none),
  ("SUNRISE OVER MOUNTAINS", "So", 0, none),
  ("SUNRISE", "So", 0, none),
  ("CITYSCAPE AT DUSK", "So", 0, none),
  ("SUNSET OVER BUILDINGS", "So", 0, none),
  ("RAINBOW", "So", 0, none),
  ("BRIDGE AT NIGHT", "So", 0, none),
  ("WATER WAVE", "So", 0, none),
  ("VOLCANO", "So", 0, none),
  ("MILKY WAY", "So", 0, none),
  ("EARTH GLOBE EUROPE-AFRICA", "So", 0, none),
  ("EARTH GLOBE AMERICAS", "So", 0, none),
  ("EARTH GLOBE ASIA-AUSTRALIA", "So", 0, none),
  ("GLOBE WITH MERIDIANS", "So", 0, none),
  ("NEW MOON SYMBOL", "So", 0, none),
  ("WAXING CRESCENT MOON SYMBOL", "So", 0, none),
  ("FIRST QUARTER MOON SYMBOL", "So", 0, none),
  ("WAXING GIBBOUS MOON SYMBOL", "So", 0, none),
  ("FULL MOON SYMBOL", "So", 0, none),
  ("WANING GIBBOUS MOON SYMBOL", "So", 0, none),
  ("LAST QUARTER MOON SYMBOL", "So", 0, none),
  ("WANING CRESCENT MOON SYMBOL", "So", 0, none),
  ("CRESCENT MOON", "So", 0, none),
  ("NEW MOON WITH FACE", "So", 0, none),
  ("FIRST QUARTER MOON WITH FACE", "So", 0, none),
  ("LAST QUARTER MOON WITH FACE", "So", 0, none),
  ("FULL MOON WITH FACE", "So", 0, none),
  ("SUN WITH FACE", "So", 0, none),
  ("GLOWING STAR", "So", 0, none),
  ("SHOOTING STAR", "So", 0, none),
  ("THERMOMETER", "So", 0, none),
  ("BLACK DROPLET", "So", 0, none),
  ("WHITE SUN", "So", 0, none),
  ("WHITE SUN WITH SMALL CLOUD", "So", 0, none),
  ("WHITE SUN BEHIND CLOUD", "So", 0, none),
  ("WHITE SUN BEHIND CLOUD WITH RAIN", "So", 0, none),
  ("CLOUD WITH RAIN", "So", 0, none),
  ("CLOUD WITH SNOW", "So", 0, none),
  ("CLOUD WITH LIGHTNING", "So", 0, none),
  ("CLOUD WITH TORNADO", "So", 0, none),
  ("FOG", "So", 0, none),
  ("WIND BLOWING FACE", "So", 0, none),
  ("HOT DOG", "So", 0, none),
  ("TACO", "So", 0, none),
  ("BURRITO", "So", 0, none),
  ("CHESTNUT", "So", 0, none),
  ("SEEDLING", "So", 0, none),
  ("EVERGREEN TREE", "So", 0, none),
  ("DECIDUOUS TREE", "So", 0, none),
  ("PALM TREE", "So", 0, none),
  ("CACTUS", "So", 0, none),
  ("HOT PEPPER", "So", 0, none),
  ("TULIP", "So", 0, none),
  ("CHERRY BLOSSOM", "So", 0, none),
  ("ROSE", "So", 0, none),
  ("HIBISCUS", "So", 0, none),
  ("SUNFLOWER", "So", 0, none),
  ("BLOSSOM", "So", 0, none),
  ("EAR OF MAIZE", "So", 0, none),
  ("EAR OF RICE", "So", 0, none),
  ("HERB", "So", 0, none),
  ("FOUR LEAF CLOVER", "So", 0, none),
  ("MAPLE LEAF", "So", 0, none),
  ("FALLEN LEAF", "So", 0, none),
  ("LEAF FLUTTERING IN WIND", "So", 0, none),
  ("MUSHROOM", "So", 0, none),
  ("TOMATO", "So", 0, none),
  ("AUBERGINE", "So", 0, none),
  ("GRAPES", "So", 0, none),
  ("MELON", "So", 0, none),
  ("WATERMELON", "So", 0, none),
  ("TANGERINE", "So", 0, none),
  ("LEMON", "So", 0, none),
  ("BANANA", "So", 0, none),
  ("PINEAPPLE", "So", 0, none),
  ("RED APPLE", "So", 0, none),
  ("GREEN APPLE", "So", 0, none),
  ("PEAR", "So", 0, none),
  ("PEACH", "So", 0, none),
  ("CHERRIES", "So", 0, none),
  ("STRAWBERRY", "So", 0, none),
  ("HAMBURGER", "So", 0, none),
  ("SLICE OF PIZZA", "So", 0, none),
  ("MEAT ON BONE", "So", 0, none),
  ("POULTRY LEG", "So", 0, none),
  ("RICE CRACKER", "So", 0, none),
  ("RICE BALL", "So", 0, none),
  ("COOKED RICE", "So", 0, none),
  ("CURRY AND RICE", "So", 0, none),
  ("STEAMING BOWL", "So", 0, none),
  ("SPAGHETTI", "So", 0, none),
  ("BREAD", "So", 0, none),
  ("FRENCH FRIES", "So", 0, none),
  ("ROASTED SWEET POTATO", "So", 0, none),
  ("DANGO", "So", 0, none),
  ("ODEN", "So", 0, none),
  ("SUSHI", "So", 0, none),
  ("FRIED SHRIMP", "So", 0, none),
  ("FISH CAKE WITH SWIRL DESIGN", "So", 0, none),
  ("SOFT ICE CREAM", "So", 0, none),
  ("SHAVED ICE", "So", 0, none),
  ("ICE CREAM", "So", 0, none),
  ("DOUGHNUT", "So", 0, none),
  ("COOKIE", "So", 0, none),
  ("CHOCOLATE BAR", "So", 0, none),
  ("CANDY", "So", 0, none),
  ("LOLLIPOP", "So", 0, none),
  ("CUSTARD", "So", 0, none),
  ("HONEY POT", "So", 0, none),
  ("SHORTCAKE", "So", 0, none),
  ("BENTO BOX", "So", 0, none),
  ("POT OF FOOD", "So", 0, none),
  ("COOKING", "So", 0, none),
  ("FORK AND KNIFE", "So", 0, none),
  ("TEACUP WITHOUT HANDLE", "So", 0, none),
  ("SAKE BOTTLE AND CUP", "So", 0, none),
  ("WINE GLASS", "So", 0, none),
  ("COCKTAIL GLASS", "So", 0, none),
  ("TROPICAL DRINK", "So", 0, none),
  ("BEER MUG", "So", 0, none),
  ("CLINKING BEER MUGS", "So", 0, none),
  ("BABY BOTTLE", "So", 0, none),
  ("FORK AND KNIFE WITH PLATE", "So", 0, none),
  ("BOTTLE WITH POPPING CORK", "So", 0, none),
  ("POPCORN", "So", 0, none),
  ("RIBBON", "So", 0, none),
  ("WRAPPED PRESENT", "So", 0, none),
  ("BIRTHDAY CAKE", "So", 0, none),
  ("JACK-O-LANTERN", "So", 0, none),
  ("CHRISTMAS TREE", "So", 0, none),
  ("FATHER CHRISTMAS", "So", 0, none),
  ("FIREWORKS", "So", 0, none),
  ("FIREWORK SPARKLER", "So", 0, none),
  ("BALLOON", "So", 0, none),
  ("PARTY POPPER", "So", 0, none),
  ("CONFETTI BALL", "So", 0, none),
  ("TANABATA TREE", "So", 0, none),
  ("CROSSED FLAGS", "So", 0, none),
  ("PINE DECORATION", "So", 0, none),
  ("JAPANESE DOLLS", "So", 0, none),
  ("CARP STREAMER", "So", 0, none),
  ("WIND CHIME", "So", 0, none),
  ("MOON VIEWING CEREMONY", "So", 0, none),
  ("SCHOOL SATCHEL", "So", 0, none),
  ("GRADUATION CAP", "So", 0, none),
  ("HEART WITH TIP ON THE LEFT", "So", 0, none),
  ("BOUQUET OF FLOWERS", "So", 0, none),
  ("MILITARY MEDAL", "So", 0, none),
  ("REMINDER RIBBON", "So", 0, none),
  ("MUSICAL KEYBOARD WITH JACKS", "So", 0, none),
  ("STUDIO MICROPHONE", "So", 0, none),
  ("LEVEL SLIDER", "So", 0, none),
  ("CONTROL KNOBS", "So", 0, none),
  ("BEAMED ASCENDING MUSICAL NOTES", "So", 0, none),
  ("BEAMED DESCENDING MUSICAL NOTES", "So", 0, none),
  ("FILM FRAMES", "So", 0, none),
  ("ADMISSION TICKETS", "So", 0, none),
  ("CAROUSEL HORSE", "So", 0, none),
  ("FERRIS WHEEL", "So", 0, none),
  ("ROLLER COASTER", "So", 0, none),
  ("FISHING POLE AND FISH", "So", 0, none),
  ("MICROPHONE", "So", 0, none),
  ("MOVIE CAMERA", "So", 0, none),
  ("CINEMA", "So", 0, none),
  ("HEADPHONE", "So", 0, none),
  ("ARTIST PALETTE", "So", 0, none),
  ("TOP HAT", "So", 0, none),
  ("CIRCUS TENT", "So", 0, none),
  ("TICKET", "So", 0, none),
  ("CLAPPER BOARD", "So", 0, none),
  ("PERFORMING ARTS", "So", 0, none),
  ("VIDEO GAME", "So", 0, none),
  ("DIRECT HIT", "So", 0, none),
  ("SLOT MACHINE", "So", 0, none),
  ("BILLIARDS", "So", 0, none),
  ("GAME DIE", "So", 0, none),
  ("BOWLING", "So", 0, none),
  ("FLOWER PLAYING CARDS", "So", 0, none),
  ("MUSICAL NOTE", "So", 0, none),
  ("MULTIPLE MUSICAL NOTES", "So", 0, none),
  ("SAXOPHONE", "So", 0, none),
  ("GUITAR", "So", 0, none),
  ("MUSICAL KEYBOARD", "So", 0, none),
  ("TRUMPET", "So", 0, none),
  ("VIOLIN", "So", 0, none),
  ("MUSICAL SCORE", "So", 0, none),
  ("RUNNING SHIRT WITH SASH", "So", 0, none),
  ("TENNIS RACQUET AND BALL", "So", 0, none),
  ("SKI AND SKI BOOT", "So", 0, none),
  ("BASKETBALL AND HOOP", "So", 0, none),
  ("CHEQUERED FLAG", "So", 0, none),
  ("SNOWBOARDER", "So", 0, none),
  ("RUNNER", "So", 0, none),
  ("SURFER", "So", 0, none),
  ("SPORTS MEDAL", "So", 0, none),
  ("TROPHY", "So", 0, none),
  ("HORSE RACING", "So", 0, none),
  ("AMERICAN FOOTBALL", "So", 0, none),
  ("RUGBY FOOTBALL", "So", 0, none),
  ("SWIMMER", "So", 0, none),
  ("WEIGHT LIFTER", "So", 0, none),
  ("GOLFER", "So", 0, none),
  ("RACING MOTORCYCLE", "So", 0, none),
  ("RACING CAR", "So", 0, none),
  ("CRICKET BAT AND BALL", "So", 0, none),
  ("VOLLEYBALL", "So", 0, none),
  ("FIELD HOCKEY STICK AND BALL", "So", 0, none),
  ("ICE HOCKEY STICK AND PUCK", "So", 0, none),
  ("TABLE TENNIS PADDLE AND BALL", "So", 0, none),
  ("SNOW CAPPED MOUNTAIN", "So", 0, none),
  ("CAMPING", "So", 0, none),
  ("BEACH WITH UMBRELLA", "So", 0, none),
  ("BUILDING CONSTRUCTION", "So", 0, none),
  ("HOUSE BUILDINGS", "So", 0, none),
  ("CITYSCAPE", "So", 0, none),
  ("DERELICT HOUSE BUILDING", "So", 0, none),
  ("CLASSICAL BUILDING", "So", 0, none),
  ("DESERT", "So", 0, none),
  ("DESERT ISLAND", "So", 0, none),
  ("NATIONAL PARK", "So", 0, none),
  ("STADIUM", "So", 0, none),
  ("HOUSE BUILDING", "So", 0, none),
  ("HOUSE WITH GARDEN", "So", 0, none),
  ("OFFICE BUILDING", "So", 0, none),
  ("JAPANESE POST OFFICE", "So", 0, none),
  ("EUROPEAN POST OFFICE", "So", 0, none),
  ("HOSPITAL", "So", 0, none),
  ("BANK", "So", 0, none),
  ("AUTOMATED TELLER MACHINE", "So", 0, none),
  ("HOTEL", "So", 0, none),
  ("LOVE HOTEL", "So", 0, none),
  ("CONVENIENCE STORE", "So", 0, none),
  ("SCHOOL", "So", 0, none),
  ("DEPARTMENT STORE", "So", 0, none),
  ("FACTORY", "So", 0, none),
  ("IZAKAYA LANTERN", "So", 0, none),
  ("JAPANESE CASTLE", "So", 0, none),
  ("EUROPEAN CASTLE", "So", 0, none),
  ("WHITE PENNANT", "So", 0, none),
  ("BLACK PENNANT", "So", 0, none),
  ("WAVING WHITE FLAG", "So", 0, none),
  ("WAVING BLACK FLAG", "So", 0, none),
  ("ROSETTE", "So", 0, none),
  ("BLACK ROSETTE", "So", 0, none),
  ("LABEL", "So", 0, none),
  ("BADMINTON RACQUET AND SHUTTLECOCK", "So", 0, none),
  ("BOW AND ARROW", "So", 0, none),
  ("AMPHORA", "So", 0, none),
  ("EMOJI MODIFIER FITZPATRICK TYPE-1-2", "Sk", 0, none),
  ("EMOJI MODIFIER FITZPATRICK TYPE-3", "Sk", 0, none),
  ("EMOJI MODIFIER FITZPATRICK TYPE-4", "Sk", 0, none),
  ("EMOJI MODIFIER FITZPATRICK TYPE-5", "Sk", 0, none),
  ("EMOJI MODIFIER FITZPATRICK TYPE-6", "Sk", 0, none),
  ("RAT", "So", 0, none),
  ("MOUSE", "So", 0, none),
  ("OX", "So", 0, none),
  ("WATER BUFFALO", "So", 0, none),
  ("COW", "So", 0, none),
  ("TIGER", "So", 0, none),
  ("LEOPARD", "So", 0, none),
  ("RABBIT", "So", 0, none),
  ("CAT", "So", 0, none),
  ("DRAGON", "So", 0, none),
  ("CROCODILE", "So", 0, none),
  ("WHALE", "So", 0, none),
  ("SNAIL", "So", 0, none),
  ("SNAKE", "So", 0, none),
  ("HORSE", "So", 0, none),
  ("RAM", "So", 0, none),
  ("GOAT", "So", 0, none),
  ("SHEEP", "So", 0, none),
  ("MONKEY", "So", 0, none),
  ("ROOSTER", "So", 0, none),
  ("CHICKEN", "So", 0, none),
  ("DOG", "So", 0, none),
  ("PIG", "So", 0, none),
  ("BOAR", "So", 0, none),
  ("ELEPHANT", "So", 0, none),
  ("OCTOPUS", "So", 0, none),
  ("SPIRAL SHELL", "So", 0, none),
  ("BUG", "So", 0, none),
  ("ANT", "So", 0, none),
  ("HONEYBEE", "So", 0, none),
  ("LADY BEETLE", "So", 0, none),
  ("FISH", "So", 0, none),
  ("TROPICAL FISH", "So", 0, none),
  ("BLOWFISH", "So", 0, none),
  ("TURTLE", "So", 0, none),
  ("HATCHING CHICK", "So", 0, none),
  ("BABY CHICK", "So", 0, none),
  ("FRONT-FACING BABY CHICK", "So", 0, none),
  ("BIRD", "So", 0, none),
  ("PENGUIN", "So", 0, none),
  ("KOALA", "So", 0, none),
  ("POODLE", "So", 0, none),
  ("DROMEDARY CAMEL", "So", 0, none),
  ("BACTRIAN CAMEL", "So", 0, none),
  ("DOLPHIN", "So", 0, none),
  ("MOUSE FACE", "So", 0, none),
  ("COW FACE", "So", 0, none),
  ("TIGER FACE", "So", 0, none),
  ("RABBIT FACE", "So", 0, none),
  ("CAT FACE", "So", 0, none),
  ("DRAGON FACE", "So", 0, none),
  ("SPOUTING WHALE", "So", 0, none),
  ("HORSE FACE", "So", 0, none),
  ("MONKEY FACE", "So", 0, none),
  ("DOG FACE", "So", 0, none),
  ("PIG FACE", "So", 0, none),
  ("FROG FACE", "So", 0, none),
  ("HAMSTER FACE", "So", 0, none),
  ("WOLF FACE", "So", 0, none),
  ("BEAR FACE", "So", 0, none),
  ("PANDA FACE", "So", 0, none),
  ("PIG NOSE", "So", 0, none),
  ("PAW PRINTS", "So", 0, none),
  ("CHIPMUNK", "So", 0, none),
  ("EYES", "So", 0, none),
  ("EYE", "So", 0, none),
  ("EAR", "So", 0, none),
  ("NOSE", "So", 0, none),
  ("MOUTH", "So", 0, none),
  ("TONGUE", "So", 0, none),
  ("WHITE UP POINTING BACKHAND INDEX", "So", 0, none),
  ("WHITE DOWN POINTING BACKHAND INDEX", "So", 0, none),
  ("WHITE LEFT POINTING BACKHAND INDEX", "So", 0, none),
  ("WHITE RIGHT POINTING BACKHAND INDEX", "So", 0, none),
  ("FISTED HAND SIGN", "So", 0, none),
  ("WAVING HAND SIGN", "So", 0, none),
  ("OK HAND SIGN", "So", 0, none),
  ("THUMBS UP SIGN", "So", 0, none),
  ("THUMBS DOWN SIGN", "So", 0, none),
  ("CLAPPING HANDS SIGN", "So", 0, none),
  ("OPEN HANDS SIGN", "So", 0, none),
  ("CROWN", "So", 0, none),
  ("WOMANS HAT", "So", 0, none),
  ("EYEGLASSES", "So", 0, none),
  ("NECKTIE", "So", 0, none),
  ("T-SHIRT", "So", 0, none),
  ("JEANS", "So", 0, none),
  ("DRESS", "So", 0, none),
  ("KIMONO", "So", 0, none),
  ("BIKINI", "So", 0, none),
  ("WOMANS CLOTHES", "So", 0, none),
  ("PURSE", "So", 0, none),
  ("HANDBAG", "So", 0, none),
  ("POUCH", "So", 0, none),
  ("MANS SHOE", "So", 0, none),
  ("ATHLETIC SHOE", "So", 0, none),
  ("HIGH-HEELED SHOE", "So", 0, none),
  ("WOMANS SANDAL", "So", 0, none),
  ("WOMANS BOOTS", "So", 0, none),
  ("FOOTPRINTS", "So", 0, none),
  ("BUST IN SILHOUETTE", "So", 0, none),
  ("BUSTS IN SILHOUETTE", "So", 0, none),
  ("BOY", "So", 0, none),
  ("GIRL", "So", 0, none),
  ("MAN", "So", 0, none),
  ("WOMAN", "So", 0, none),
  ("FAMILY", "So", 0, none),
  ("MAN AND WOMAN HOLDING HANDS", "So", 0, none),
  ("TWO MEN HOLDING HANDS", "So", 0, none),
  ("TWO WOMEN HOLDING HANDS", "So", 0, none),
  ("POLICE OFFICER", "So", 0, none),
  ("WOMAN WITH BUNNY EARS", "So", 0, none),
  ("BRIDE WITH VEIL", "So", 0, none),
  ("PERSON WITH BLOND HAIR", "So", 0, none),
  ("MAN WITH GUA PI MAO", "So", 0, none),
  ("MAN WITH TURBAN", "So", 0, none),
  ("OLDER MAN", "So", 0, none),
  ("OLDER WOMAN", "So", 0, none),
  ("BABY", "So", 0, none),
  ("CONSTRUCTION WORKER", "So", 0, none),
  ("PRINCESS", "So", 0, none),
  ("JAPANESE OGRE", "So", 0, none),
  ("JAPANESE GOBLIN", "So", 0, none),
  ("GHOST", "So", 0, none),
  ("BABY ANGEL", "So", 0, none),
  ("EXTRATERRESTRIAL ALIEN", "So", 0, none),
  ("ALIEN MONSTER", "So", 0, none),
  ("IMP", "So", 0, none),
  ("SKULL", "So", 0, none),
  ("INFORMATION DESK PERSON", "So", 0, none),
  ("GUARDSMAN", "So", 0, none),
  ("DANCER", "So", 0, none),
  ("LIPSTICK", "So", 0, none),
  ("NAIL POLISH", "So", 0, none),
  ("FACE MASSAGE", "So", 0, none),
  ("HAIRCUT", "So", 0, none),
  ("BARBER POLE", "So", 0, none),
  ("SYRINGE", "So", 0, none),
  ("PILL", "So", 0, none),
  ("KISS MARK", "So", 0, none),
  ("LOVE LETTER", "So", 0, none),
  ("RING", "So", 0, none),
  ("GEM STONE", "So", 0, none),
  ("KISS", "So", 0, none),
  ("BOUQUET", "So", 0, none),
  ("COUPLE WITH HEART", "So", 0, none),
  ("WEDDING", "So", 0, none),
  ("BEATING HEART", "So", 0, none),
  ("BROKEN HEART", "So", 0, none),
  ("TWO HEARTS", "So", 0, none),
  ("SPARKLING HEART", "So", 0, none),
  ("GROWING HEART", "So", 0, none),
  ("HEART WITH ARROW", "So", 0, none),
  ("BLUE HEART", "So", 0, none),
  ("GREEN HEART", "So", 0, none),
  ("YELLOW HEART", "So", 0, none),
  ("PURPLE HEART", "So", 0, none),
  ("HEART WITH RIBBON", "So", 0, none),
  ("REVOLVING HEARTS", "So", 0, none),
  ("HEART DECORATION", "So", 0, none),
  ("DIAMOND SHAPE WITH A DOT INSIDE", "So", 0, none),
  ("ELECTRIC LIGHT BULB", "So", 0, none),
  ("ANGER SYMBOL", "So", 0, none),
  ("BOMB", "So", 0, none),
  ("SLEEPING SYMBOL", "So", 0, none),
  ("COLLISION SYMBOL", "So", 0, none),
  ("SPLASHING SWEAT SYMBOL", "So", 0, none),
  ("DROPLET", "So", 0, none),
  ("DASH SYMBOL", "So", 0, none),
  ("PILE OF POO", "So", 0, none),
  ("FLEXED BICEPS", "So", 0, none),
  ("DIZZY SYMBOL", "So", 0, none),
  ("SPEECH BALLOON", "So", 0, none),
  ("THOUGHT BALLOON", "So", 0, none),
  ("WHITE FLOWER", "So", 0, none),
  ("HUNDRED POINTS SYMBOL", "So", 0, none),
  ("MONEY BAG", "So", 0, none),
  ("CURRENCY EXCHANGE", "So", 0, none),
  ("HEAVY DOLLAR SIGN", "So", 0, none),
  ("CREDIT CARD", "So", 0, none),
  ("BANKNOTE WITH YEN SIGN", "So", 0, none),
  ("BANKNOTE WITH DOLLAR SIGN", "So", 0, none),
  ("BANKNOTE WITH EURO SIGN", "So", 0, none),
  ("BANKNOTE WITH POUND SIGN", "So", 0, none),
  ("MONEY WITH WINGS", "So", 0, none),
  ("CHART WITH UPWARDS TREND AND YEN SIGN", "So", 0, none),
  ("SEAT", "So", 0, none),
  ("PERSONAL COMPUTER", "So", 0, none),
  ("BRIEFCASE", "So", 0, none),
  ("MINIDISC", "So", 0, none),
  ("FLOPPY DISK", "So", 0, none),
  ("OPTICAL DISC", "So", 0, none),
  ("DVD", "So", 0, none),
  ("FILE FOLDER", "So", 0, none),
  ("OPEN FILE FOLDER", "So", 0, none),
  ("PAGE WITH CURL", "So", 0, none),
  ("PAGE FACING UP", "So", 0, none),
  ("CALENDAR", "So", 0, none),
  ("TEAR-OFF CALENDAR", "So", 0, none),
  ("CARD INDEX", "So", 0, none),
  ("CHART WITH UPWARDS TREND", "So", 0, none),
  ("CHART WITH DOWNWARDS TREND", "So", 0, none),
  ("BAR CHART", "So", 0, none),
  ("CLIPBOARD", "So", 0, none),
  ("PUSHPIN", "So", 0, none),
  ("ROUND PUSHPIN", "So", 0, none),
  ("PAPERCLIP", "So", 0, none),
  ("STRAIGHT RULER", "So", 0, none),
  ("TRIANGULAR RULER", "So", 0, none),
  ("BOOKMARK TABS", "So", 0, none),
  ("LEDGER", "So", 0, none),
  ("NOTEBOOK", "So", 0, none),
  ("NOTEBOOK WITH DECORATIVE COVER", "So", 0, none),
  ("CLOSED BOOK", "So", 0, none),
  ("OPEN BOOK", "So", 0, none),
  ("GREEN BOOK", "So", 0, none),
  ("BLUE BOOK", "So", 0, none),
  ("ORANGE BOOK", "So", 0, none),
  ("BOOKS", "So", 0, none),
  ("NAME BADGE", "So", 0, none),
  ("SCROLL", "So", 0, none),
  ("MEMO", "So", 0, none),
  ("TELEPHONE RECEIVER", "So", 0, none),
  ("PAGER", "So", 0, none),
  ("FAX MACHINE", "So", 0, none),
  ("SATELLITE ANTENNA", "So", 0, none),
  ("PUBLIC ADDRESS LOUDSPEAKER", "So", 0, none),
  ("CHEERING MEGAPHONE", "So", 0, none),
  ("OUTBOX TRAY", "So", 0, none),
  ("INBOX TRAY", "So", 0, none),
  ("PACKAGE", "So", 0, none),
  ("E-MAIL SYMBOL", "So", 0, none),
  ("INCOMING ENVELOPE", "So", 0, none),
  ("ENVELOPE WITH DOWNWARDS ARROW ABOVE", "So", 0, none),
  ("CLOSED MAILBOX WITH LOWERED FLAG", "So", 0, none),
  ("CLOSED MAILBOX WITH RAISED FLAG", "So", 0, none),
  ("OPEN MAILBOX WITH RAISED FLAG", "So", 0, none),
  ("OPEN MAILBOX WITH LOWERED FLAG", "So", 0, none),
  ("POSTBOX", "So", 0, none),
  ("POSTAL HORN", "So", 0, none),
  ("NEWSPAPER", "So", 0, none),
  ("MOBILE PHONE", "So", 0, none),
  ("MOBILE PHONE WITH RIGHTWARDS ARROW AT LEFT", "So", 0, none),
  ("VIBRATION MODE", "So", 0, none),
  ("MOBILE PHONE OFF", "So", 0, none),
  ("NO MOBILE PHONES", "So", 0, none),
  ("ANTENNA WITH BARS", "So", 0, none),
  ("CAMERA", "So", 0, none),
  ("CAMERA WITH FLASH", "So", 0, none),
  ("VIDEO CAMERA", "So", 0, none),
  ("TELEVISION", "So", 0, none),
  ("RADIO", "So", 0, none),
  ("VIDEOCASSETTE", "So", 0, none),
  ("FILM PROJECTOR", "So", 0, none),
  ("PORTABLE STEREO", "So", 0, none),
  ("PRAYER BEADS", "So", 0, none),
  ("TWISTED RIGHTWARDS ARROWS", "So", 0, none),
  ("CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS", "So", 0, none),
  ("CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS WITH CIRCLED ONE OVERLAY", "So", 0, none),
  ("CLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS", "So", 0, none),
  ("ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS", "So", 0, none),
  ("LOW BRIGHTNESS SYMBOL", "So", 0, none),
  ("HIGH BRIGHTNESS SYMBOL", "So", 0, none),
  ("SPEAKER WITH CANCELLATION STROKE", "So", 0, none),
  ("SPEAKER", "So", 0, none),
  ("SPEAKER WITH ONE SOUND WAVE", "So", 0, none),
  ("SPEAKER WITH THREE SOUND WAVES", "So", 0, none),
  ("BATTERY", "So", 0, none),
  ("ELECTRIC PLUG", "So", 0, none),
  ("LEFT-POINTING MAGNIFYING GLASS", "So", 0, none),
  ("RIGHT-POINTING MAGNIFYING GLASS", "So", 0, none),
  ("LOCK WITH INK PEN", "So", 0, none),
  ("CLOSED LOCK WITH KEY", "So", 0, none),
  ("KEY", "So", 0, none),
  ("LOCK", "So", 0, none),
  ("OPEN LOCK", "So", 0, none),
  ("BELL", "So", 0, none),
  ("BELL WITH CANCELLATION STROKE", "So", 0, none),
  ("BOOKMARK", "So", 0, none),
  ("LINK SYMBOL", "So", 0, none),
  ("RADIO BUTTON", "So", 0, none),
  ("BACK WITH LEFTWARDS ARROW ABOVE", "So", 0, none),
  ("END WITH LEFTWARDS ARROW ABOVE", "So", 0, none),
  ("ON WITH EXCLAMATION MARK WITH LEFT RIGHT ARROW ABOVE", "So", 0, none),
  ("SOON WITH RIGHTWARDS ARROW ABOVE", "So", 0, none),
  ("TOP WITH UPWARDS ARROW ABOVE", "So", 0, none),
  ("NO ONE UNDER EIGHTEEN SYMBOL", "So", 0, none),
  ("KEYCAP TEN", "So", 0, none),
  ("INPUT SYMBOL FOR LATIN CAPITAL LETTERS", "So", 0, none),
  ("INPUT SYMBOL FOR LATIN SMALL LETTERS", "So", 0, none),
  ("INPUT SYMBOL FOR NUMBERS", "So", 0, none),
  ("INPUT SYMBOL FOR SYMBOLS", "So", 0, none),
  ("INPUT SYMBOL FOR LATIN LETTERS", "So", 0, none),
  ("FIRE", "So", 0, none),
  ("ELECTRIC TORCH", "So", 0, none),
  ("WRENCH", "So", 0, none),
  ("HAMMER", "So", 0, none),
  ("NUT AND BOLT", "So", 0, none),
  ("HOCHO", "So", 0, none),
  ("PISTOL", "So", 0, none),
  ("MICROSCOPE", "So", 0, none),
  ("TELESCOPE", "So", 0, none),
  ("CRYSTAL BALL", "So", 0, none),
  ("SIX POINTED STAR WITH MIDDLE DOT", "So", 0, none),
  ("JAPANESE SYMBOL FOR BEGINNER", "So", 0, none),
  ("TRIDENT EMBLEM", "So", 0, none),
  ("BLACK SQUARE BUTTON", "So", 0, none),
  ("WHITE SQUARE BUTTON", "So", 0, none),
  ("LARGE RED CIRCLE", "So", 0, none),
  ("LARGE BLUE CIRCLE", "So", 0, none),
  ("LARGE ORANGE DIAMOND", "So", 0, none),
  ("LARGE BLUE DIAMOND", "So", 0, none),
  ("SMALL ORANGE DIAMOND", "So", 0, none),
  ("SMALL BLUE DIAMOND", "So", 0, none),
  ("UP-POINTING RED TRIANGLE", "So", 0, none),
  ("DOWN-POINTING RED TRIANGLE", "So", 0, none),
  ("UP-POINTING SMALL RED TRIANGLE", "So", 0, none),
  ("DOWN-POINTING SMALL RED TRIANGLE", "So", 0, none),
  ("LOWER RIGHT SHADOWED WHITE CIRCLE", "So", 0, none),
  ("UPPER RIGHT SHADOWED WHITE CIRCLE", "So", 0, none),
  ("CIRCLED CROSS POMMEE", "So", 0, none),
  ("CROSS POMMEE WITH HALF-CIRCLE BELOW", "So", 0, none),
  ("CROSS POMMEE", "So", 0, none),
  ("NOTCHED LEFT SEMICIRCLE WITH THREE DOTS", "So", 0, none),
  ("NOTCHED RIGHT SEMICIRCLE WITH THREE DOTS", "So", 0, none),
  ("SYMBOL FOR MARKS CHAPTER", "So", 0, none),
  ("WHITE LATIN CROSS", "So", 0, none),
  ("HEAVY LATIN CROSS", "So", 0, none),
  ("CELTIC CROSS", "So", 0, none),
  ("OM SYMBOL", "So", 0, none),
  ("DOVE OF PEACE", "So", 0, none),
  ("KAABA", "So", 0, none),
  ("MOSQUE", "So", 0, none),
  ("SYNAGOGUE", "So", 0, none),
  ("MENORAH WITH NINE BRANCHES", "So", 0, none),
  ("BOWL OF HYGIEIA", "So", 0, none),
  ("CLOCK FACE ONE OCLOCK", "So", 0, none),
  ("CLOCK FACE TWO OCLOCK", "So", 0, none),
  ("CLOCK FACE THREE OCLOCK", "So", 0, none),
  ("CLOCK FACE FOUR OCLOCK", "So", 0, none),
  ("CLOCK FACE FIVE OCLOCK", "So", 0, none),
  ("CLOCK FACE SIX OCLOCK", "So", 0, none),
  ("CLOCK FACE SEVEN OCLOCK", "So", 0, none),
  ("CLOCK FACE EIGHT OCLOCK", "So", 0, none),
  ("CLOCK FACE NINE OCLOCK", "So", 0, none),
  ("CLOCK FACE TEN OCLOCK", "So", 0, none),
  ("CLOCK FACE ELEVEN OCLOCK", "So", 0, none),
  ("CLOCK FACE TWELVE OCLOCK", "So", 0, none),
  ("CLOCK FACE ONE-THIRTY", "So", 0, none),
  ("CLOCK FACE TWO-THIRTY", "So", 0, none),
  ("CLOCK FACE THREE-THIRTY", "So", 0, none),
  ("CLOCK FACE FOUR-THIRTY", "So", 0, none),
  ("CLOCK FACE FIVE-THIRTY", "So", 0, none),
  ("CLOCK FACE SIX-THIRTY", "So", 0, none),
  ("CLOCK FACE SEVEN-THIRTY", "So", 0, none),
  ("CLOCK FACE EIGHT-THIRTY", "So", 0, none),
  ("CLOCK FACE NINE-THIRTY", "So", 0, none),
  ("CLOCK FACE TEN-THIRTY", "So", 0, none),
  ("CLOCK FACE ELEVEN-THIRTY", "So", 0, none),
  ("CLOCK FACE TWELVE-THIRTY", "So", 0, none),
  ("RIGHT SPEAKER", "So", 0, none),
  ("RIGHT SPEAKER WITH ONE SOUND WAVE", "So", 0, none),
  ("RIGHT SPEAKER WITH THREE SOUND WAVES", "So", 0, none),
  ("BULLHORN", "So", 0, none),
  ("BULLHORN WITH SOUND WAVES", "So", 0, none),
  ("RINGING BELL", "So", 0, none),
  ("BOOK", "So", 0, none),
  ("CANDLE", "So", 0, none),
  ("MANTELPIECE CLOCK", "So", 0, none),
  ("BLACK SKULL AND CROSSBONES", "So", 0, none),
  ("NO PIRACY", "So", 0, none),
  ("HOLE", "So", 0, none),
  ("MAN IN BUSINESS SUIT LEVITATING", "So", 0, none),
  ("SLEUTH OR SPY", "So", 0, none),
  ("DARK SUNGLASSES", "So", 0, none),
  ("SPIDER", "So", 0, none),
  ("SPIDER WEB", "So", 0, none),
  ("JOYSTICK", "So", 0, none),
  ("MAN DANCING", "So", 0, none),
  ("LEFT HAND TELEPHONE RECEIVER", "So", 0, none),
  ("TELEPHONE RECEIVER WITH PAGE", "So", 0, none),
  ("RIGHT HAND TELEPHONE RECEIVER", "So", 0, none),
  ("WHITE TOUCHTONE TELEPHONE", "So", 0, none),
  ("BLACK TOUCHTONE TELEPHONE", "So", 0, none),
  ("TELEPHONE ON TOP OF MODEM", "So", 0, none),
  ("CLAMSHELL MOBILE PHONE", "So", 0, none),
  ("BACK OF ENVELOPE", "So", 0, none),
  ("STAMPED ENVELOPE", "So", 0, none),
  ("ENVELOPE WITH LIGHTNING", "So", 0, none),
  ("FLYING ENVELOPE", "So", 0, none),
  ("PEN OVER STAMPED ENVELOPE", "So", 0, none),
  ("LINKED PAPERCLIPS", "So", 0, none),
  ("BLACK PUSHPIN", "So", 0, none),
  ("LOWER LEFT PENCIL", "So", 0, none),
  ("LOWER LEFT BALLPOINT PEN", "So", 0, none),
  ("LOWER LEFT FOUNTAIN PEN", "So", 0, none),
  ("LOWER LEFT PAINTBRUSH", "So", 0, none),
  ("LOWER LEFT CRAYON", "So", 0, none),
  ("LEFT WRITING HAND", "So", 0, none),
  ("TURNED OK HAND SIGN", "So", 0, none),
  ("RAISED HAND WITH FINGERS SPLAYED", "So", 0, none),
  ("REVERSED RAISED HAND WITH FINGERS SPLAYED", "So", 0, none),
  ("REVERSED THUMBS UP SIGN", "So", 0, none),
  ("REVERSED THUMBS DOWN SIGN", "So", 0, none),
  ("REVERSED VICTORY HAND", "So", 0, none),
  ("REVERSED HAND WITH MIDDLE FINGER EXTENDED", "So", 0, none),
  ("RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS", "So", 0, none),
  ("WHITE DOWN POINTING LEFT HAND INDEX", "So", 0, none),
  ("SIDEWAYS WHITE LEFT POINTING INDEX", "So", 0, none),
  ("SIDEWAYS WHITE RIGHT POINTING INDEX", "So", 0, none),
  ("SIDEWAYS BLACK LEFT POINTING INDEX", "So", 0, none),
  ("SIDEWAYS BLACK RIGHT POINTING INDEX", "So", 0, none),
  ("BLACK LEFT POINTING BACKHAND INDEX", "So", 0, none),
  ("BLACK RIGHT POINTING BACKHAND INDEX", "So", 0, none),
  ("SIDEWAYS WHITE UP POINTING INDEX", "So", 0, none),
  ("SIDEWAYS WHITE DOWN POINTING INDEX", "So", 0, none),
  ("SIDEWAYS BLACK UP POINTING INDEX", "So", 0, none),
  ("SIDEWAYS BLACK DOWN POINTING INDEX", "So", 0, none),
  ("BLACK UP POINTING BACKHAND INDEX", "So", 0, none),
  ("BLACK DOWN POINTING BACKHAND INDEX", "So", 0, none),
  ("BLACK HEART", "So", 0, none),
  ("DESKTOP COMPUTER", "So", 0, none),
  ("KEYBOARD AND MOUSE", "So", 0, none),
  ("THREE NETWORKED COMPUTERS", "So", 0, none),
  ("PRINTER", "So", 0, none),
  ("POCKET CALCULATOR", "So", 0, none),
  ("BLACK HARD SHELL FLOPPY DISK", "So", 0, none),
  ("WHITE HARD SHELL FLOPPY DISK", "So", 0, none),
  ("SOFT SHELL FLOPPY DISK", "So", 0, none),
  ("TAPE CARTRIDGE", "So", 0, none),
  ("WIRED KEYBOARD", "So", 0, none),
  ("ONE BUTTON MOUSE", "So", 0, none),
  ("TWO BUTTON MOUSE", "So", 0, none),
  ("THREE BUTTON MOUSE", "So", 0, none),
  ("TRACKBALL", "So", 0, none),
  ("OLD PERSONAL COMPUTER", "So", 0, none),
  ("HARD DISK", "So", 0, none),
  ("SCREEN", "So", 0, none),
  ("PRINTER ICON", "So", 0, none),
  ("FAX ICON", "So", 0, none),
  ("OPTICAL DISC ICON", "So", 0, none),
  ("DOCUMENT WITH TEXT", "So", 0, none),
  ("DOCUMENT WITH TEXT AND PICTURE", "So", 0, none),
  ("DOCUMENT WITH PICTURE", "So", 0, none),
  ("FRAME WITH PICTURE", "So", 0, none),
  ("FRAME WITH TILES", "So", 0, none),
  ("FRAME WITH AN X", "So", 0, none),
  ("BLACK FOLDER", "So", 0, none),
  ("FOLDER", "So", 0, none),
  ("OPEN FOLDER", "So", 0, none),
  ("CARD INDEX DIVIDERS", "So", 0, none),
  ("CARD FILE BOX", "So", 0, none),
  ("FILE CABINET", "So", 0, none),
  ("EMPTY NOTE", "So", 0, none),
  ("EMPTY NOTE PAGE", "So", 0, none),
  ("EMPTY NOTE PAD", "So", 0, none),
  ("NOTE", "So", 0, none),
  ("NOTE PAGE", "So", 0, none),
  ("NOTE PAD", "So", 0, none),
  ("EMPTY DOCUMENT", "So", 0, none),
  ("EMPTY PAGE", "So", 0, none),
  ("EMPTY PAGES", "So", 0, none),
  ("DOCUMENT", "So", 0, none),
  ("PAGE", "So", 0, none),
  ("PAGES", "So", 0, none),
  ("WASTEBASKET", "So", 0, none),
  ("SPIRAL NOTE PAD", "So", 0, none),
  ("SPIRAL CALENDAR PAD", "So", 0, none),
  ("DESKTOP WINDOW", "So", 0, none),
  ("MINIMIZE", "So", 0, none),
  ("MAXIMIZE", "So", 0, none),
  ("OVERLAP", "So", 0, none),
  ("CLOCKWISE RIGHT AND LEFT SEMICIRCLE ARROWS", "So", 0, none),
  ("CANCELLATION X", "So", 0, none),
  ("INCREASE FONT SIZE SYMBOL", "So", 0, none),
  ("DECREASE FONT SIZE SYMBOL", "So", 0, none),
  ("COMPRESSION", "So", 0, none),
  ("OLD KEY", "So", 0, none),
  ("ROLLED-UP NEWSPAPER", "So", 0, none),
  ("PAGE WITH CIRCLED TEXT", "So", 0, none),
  ("STOCK CHART", "So", 0, none),
  ("DAGGER KNIFE", "So", 0, none),
  ("LIPS", "So", 0, none),
  ("SPEAKING HEAD IN SILHOUETTE", "So", 0, none),
  ("THREE RAYS ABOVE", "So", 0, none),
  ("THREE RAYS BELOW", "So", 0, none),
  ("THREE RAYS LEFT", "So", 0, none),
  ("THREE RAYS RIGHT", "So", 0, none),
  ("LEFT SPEECH BUBBLE", "So", 0, none),
  ("RIGHT SPEECH BUBBLE", "So", 0, none),
  ("TWO SPEECH BUBBLES", "So", 0, none),
  ("THREE SPEECH BUBBLES", "So", 0, none),
  ("LEFT THOUGHT BUBBLE", "So", 0, none),
  ("RIGHT THOUGHT BUBBLE", "So", 0, none),
  ("LEFT ANGER BUBBLE", "So", 0, none),
  ("RIGHT ANGER BUBBLE", "So", 0, none),
  ("MOOD BUBBLE", "So", 0, none),
  ("LIGHTNING MOOD BUBBLE", "So", 0, none),
  ("LIGHTNING MOOD", "So", 0, none),
  ("BALLOT BOX WITH BALLOT", "So", 0, none),
  ("BALLOT SCRIPT X", "So", 0, none),
  ("BALLOT BOX WITH SCRIPT X", "So", 0, none),
  ("BALLOT BOLD SCRIPT X", "So", 0, none),
  ("BALLOT BOX WITH BOLD SCRIPT X", "So", 0, none),
  ("LIGHT CHECK MARK", "So", 0, none),
  ("BALLOT BOX WITH BOLD CHECK", "So", 0, none),
  ("WORLD MAP", "So", 0, none),
  ("MOUNT FUJI", "So", 0, none),
  ("TOKYO TOWER", "So", 0, none),
  ("STATUE OF LIBERTY", "So", 0, none),
  ("SILHOUETTE OF JAPAN", "So", 0, none),
  ("MOYAI", "So", 0, none),
)
