#let data = (
  ("SYMBOL FOR NULL", "So", 0, none),
  ("SYMBOL FOR START OF HEADING", "So", 0, none),
  ("SYMBOL FOR START OF TEXT", "So", 0, none),
  ("SYMBOL FOR END OF TEXT", "So", 0, none),
  ("SYMBOL FOR END OF TRANSMISSION", "So", 0, none),
  ("SYMBOL FOR ENQUIRY", "So", 0, none),
  ("SYMBOL FOR ACKNOWLEDGE", "So", 0, none),
  ("SYMBOL FOR BELL", "So", 0, none),
  ("SYMBOL FOR BACKSPACE", "So", 0, none),
  ("SYMBOL FOR HORIZONTAL TABULATION", "So", 0, none),
  ("SYMBOL FOR LINE FEED", "So", 0, none),
  ("SYMBOL FOR VERTICAL TABULATION", "So", 0, none),
  ("SYMBOL FOR FORM FEED", "So", 0, none),
  ("SYMBOL FOR CARRIAGE RETURN", "So", 0, none),
  ("SYMBOL FOR SHIFT OUT", "So", 0, none),
  ("SYMBOL FOR SHIFT IN", "So", 0, none),
  ("SYMBOL FOR DATA LINK ESCAPE", "So", 0, none),
  ("SYMBOL FOR DEVICE CONTROL ONE", "So", 0, none),
  ("SYMBOL FOR DEVICE CONTROL TWO", "So", 0, none),
  ("SYMBOL FOR DEVICE CONTROL THREE", "So", 0, none),
  ("SYMBOL FOR DEVICE CONTROL FOUR", "So", 0, none),
  ("SYMBOL FOR NEGATIVE ACKNOWLEDGE", "So", 0, none),
  ("SYMBOL FOR SYNCHRONOUS IDLE", "So", 0, none),
  ("SYMBOL FOR END OF TRANSMISSION BLOCK", "So", 0, none),
  ("SYMBOL FOR CANCEL", "So", 0, none),
  ("SYMBOL FOR END OF MEDIUM", "So", 0, none),
  ("SYMBOL FOR SUBSTITUTE", "So", 0, none),
  ("SYMBOL FOR ESCAPE", "So", 0, none),
  ("SYMBOL FOR FILE SEPARATOR", "So", 0, none),
  ("SYMBOL FOR GROUP SEPARATOR", "So", 0, none),
  ("SYMBOL FOR RECORD SEPARATOR", "So", 0, none),
  ("SYMBOL FOR UNIT SEPARATOR", "So", 0, none),
  ("SYMBOL FOR SPACE", "So", 0, none),
  ("SYMBOL FOR DELETE", "So", 0, none),
  ("BLANK SYMBOL", "So", 0, none),
  ("OPEN BOX", "So", 0, none),
  ("SYMBOL FOR NEWLINE", "So", 0, none),
  ("SYMBOL FOR DELETE FORM TWO", "So", 0, none),
  ("SYMBOL FOR SUBSTITUTE FORM TWO", "So", 0, none),
  ("SYMBOL FOR DELETE SQUARE CHECKER BOARD FORM", "So", 0, none),
  ("SYMBOL FOR DELETE RECTANGULAR CHECKER BOARD FORM", "So", 0, none),
  ("SYMBOL FOR DELETE MEDIUM SHADE FORM", "So", 0, none),
)
