#let data = (
  ("MAYAN NUMERAL ZERO", "No", 0, none),
  ("MAYAN NUMERAL ONE", "No", 0, none),
  ("MAYAN NUMERAL TWO", "No", 0, none),
  ("MAYAN NUMERAL THREE", "No", 0, none),
  ("MAYAN NUMERAL FOUR", "No", 0, none),
  ("MAYAN NUMERAL FIVE", "No", 0, none),
  ("MAYAN NUMERAL SIX", "No", 0, none),
  ("MAYAN NUMERAL SEVEN", "No", 0, none),
  ("MAYAN NUMERAL EIGHT", "No", 0, none),
  ("MAYAN NUMERAL NINE", "No", 0, none),
  ("MAYAN NUMERAL TEN", "No", 0, none),
  ("MAYAN NUMERAL ELEVEN", "No", 0, none),
  ("MAYAN NUMERAL TWELVE", "No", 0, none),
  ("MAYAN NUMERAL THIRTEEN", "No", 0, none),
  ("MAYAN NUMERAL FOURTEEN", "No", 0, none),
  ("MAYAN NUMERAL FIFTEEN", "No", 0, none),
  ("MAYAN NUMERAL SIXTEEN", "No", 0, none),
  ("MAYAN NUMERAL SEVENTEEN", "No", 0, none),
  ("MAYAN NUMERAL EIGHTEEN", "No", 0, none),
  ("MAYAN NUMERAL NINETEEN", "No", 0, none),
)
