#let data = (
  ("GRINNING FACE", "So", 0, none),
  ("GRINNING FACE WITH SMILING EYES", "So", 0, none),
  ("FACE WITH TEARS OF JOY", "So", 0, none),
  ("SMILING FACE WITH OPEN MOUTH", "So", 0, none),
  ("SMILING FACE WITH OPEN MOUTH AND SMILING EYES", "So", 0, none),
  ("SMILING FACE WITH OPEN MOUTH AND COLD SWEAT", "So", 0, none),
  ("SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES", "So", 0, none),
  ("SMILING FACE WITH HALO", "So", 0, none),
  ("SMILING FACE WITH HORNS", "So", 0, none),
  ("WINKING FACE", "So", 0, none),
  ("SMILING FACE WITH SMILING EYES", "So", 0, none),
  ("FACE SAVOURING DELICIOUS FOOD", "So", 0, none),
  ("RELIEVED FACE", "So", 0, none),
  ("SMILING FACE WITH HEART-SHAPED EYES", "So", 0, none),
  ("SMILING FACE WITH SUNGLASSES", "So", 0, none),
  ("SMIRKING FACE", "So", 0, none),
  ("NEUTRAL FACE", "So", 0, none),
  ("EXPRESSIONLESS FACE", "So", 0, none),
  ("UNAMUSED FACE", "So", 0, none),
  ("FACE WITH COLD SWEAT", "So", 0, none),
  ("PENSIVE FACE", "So", 0, none),
  ("CONFUSED FACE", "So", 0, none),
  ("CONFOUNDED FACE", "So", 0, none),
  ("KISSING FACE", "So", 0, none),
  ("FACE THROWING A KISS", "So", 0, none),
  ("KISSING FACE WITH SMILING EYES", "So", 0, none),
  ("KISSING FACE WITH CLOSED EYES", "So", 0, none),
  ("FACE WITH STUCK-OUT TONGUE", "So", 0, none),
  ("FACE WITH STUCK-OUT TONGUE AND WINKING EYE", "So", 0, none),
  ("FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES", "So", 0, none),
  ("DISAPPOINTED FACE", "So", 0, none),
  ("WORRIED FACE", "So", 0, none),
  ("ANGRY FACE", "So", 0, none),
  ("POUTING FACE", "So", 0, none),
  ("CRYING FACE", "So", 0, none),
  ("PERSEVERING FACE", "So", 0, none),
  ("FACE WITH LOOK OF TRIUMPH", "So", 0, none),
  ("DISAPPOINTED BUT RELIEVED FACE", "So", 0, none),
  ("FROWNING FACE WITH OPEN MOUTH", "So", 0, none),
  ("ANGUISHED FACE", "So", 0, none),
  ("FEARFUL FACE", "So", 0, none),
  ("WEARY FACE", "So", 0, none),
  ("SLEEPY FACE", "So", 0, none),
  ("TIRED FACE", "So", 0, none),
  ("GRIMACING FACE", "So", 0, none),
  ("LOUDLY CRYING FACE", "So", 0, none),
  ("FACE WITH OPEN MOUTH", "So", 0, none),
  ("HUSHED FACE", "So", 0, none),
  ("FACE WITH OPEN MOUTH AND COLD SWEAT", "So", 0, none),
  ("FACE SCREAMING IN FEAR", "So", 0, none),
  ("ASTONISHED FACE", "So", 0, none),
  ("FLUSHED FACE", "So", 0, none),
  ("SLEEPING FACE", "So", 0, none),
  ("DIZZY FACE", "So", 0, none),
  ("FACE WITHOUT MOUTH", "So", 0, none),
  ("FACE WITH MEDICAL MASK", "So", 0, none),
  ("GRINNING CAT FACE WITH SMILING EYES", "So", 0, none),
  ("CAT FACE WITH TEARS OF JOY", "So", 0, none),
  ("SMILING CAT FACE WITH OPEN MOUTH", "So", 0, none),
  ("SMILING CAT FACE WITH HEART-SHAPED EYES", "So", 0, none),
  ("CAT FACE WITH WRY SMILE", "So", 0, none),
  ("KISSING CAT FACE WITH CLOSED EYES", "So", 0, none),
  ("POUTING CAT FACE", "So", 0, none),
  ("CRYING CAT FACE", "So", 0, none),
  ("WEARY CAT FACE", "So", 0, none),
  ("SLIGHTLY FROWNING FACE", "So", 0, none),
  ("SLIGHTLY SMILING FACE", "So", 0, none),
  ("UPSIDE-DOWN FACE", "So", 0, none),
  ("FACE WITH ROLLING EYES", "So", 0, none),
  ("FACE WITH NO GOOD GESTURE", "So", 0, none),
  ("FACE WITH OK GESTURE", "So", 0, none),
  ("PERSON BOWING DEEPLY", "So", 0, none),
  ("SEE-NO-EVIL MONKEY", "So", 0, none),
  ("HEAR-NO-EVIL MONKEY", "So", 0, none),
  ("SPEAK-NO-EVIL MONKEY", "So", 0, none),
  ("HAPPY PERSON RAISING ONE HAND", "So", 0, none),
  ("PERSON RAISING BOTH HANDS IN CELEBRATION", "So", 0, none),
  ("PERSON FROWNING", "So", 0, none),
  ("PERSON WITH POUTING FACE", "So", 0, none),
  ("PERSON WITH FOLDED HANDS", "So", 0, none),
)
