#let data = (
  ("GEORGIAN CAPITAL LETTER AN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER BAN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER GAN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER DON", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER EN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER VIN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER ZEN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER TAN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER IN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER KAN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER LAS", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER MAN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER NAR", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER ON", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER PAR", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER ZHAR", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER RAE", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER SAN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER TAR", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER UN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER PHAR", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER KHAR", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER GHAN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER QAR", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER SHIN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER CHIN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER CAN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER JIL", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER CIL", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER CHAR", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER XAN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER JHAN", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER HAE", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER HE", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER HIE", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER WE", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER HAR", "Lu", 0, none),
  ("GEORGIAN CAPITAL LETTER HOE", "Lu", 0, none),
  (),
  ("GEORGIAN CAPITAL LETTER YN", "Lu", 0, none),
  (),
  (),
  (),
  (),
  (),
  ("GEORGIAN CAPITAL LETTER AEN", "Lu", 0, none),
  (),
  (),
  ("GEORGIAN LETTER AN", "Ll", 0, none),
  ("GEORGIAN LETTER BAN", "Ll", 0, none),
  ("GEORGIAN LETTER GAN", "Ll", 0, none),
  ("GEORGIAN LETTER DON", "Ll", 0, none),
  ("GEORGIAN LETTER EN", "Ll", 0, none),
  ("GEORGIAN LETTER VIN", "Ll", 0, none),
  ("GEORGIAN LETTER ZEN", "Ll", 0, none),
  ("GEORGIAN LETTER TAN", "Ll", 0, none),
  ("GEORGIAN LETTER IN", "Ll", 0, none),
  ("GEORGIAN LETTER KAN", "Ll", 0, none),
  ("GEORGIAN LETTER LAS", "Ll", 0, none),
  ("GEORGIAN LETTER MAN", "Ll", 0, none),
  ("GEORGIAN LETTER NAR", "Ll", 0, none),
  ("GEORGIAN LETTER ON", "Ll", 0, none),
  ("GEORGIAN LETTER PAR", "Ll", 0, none),
  ("GEORGIAN LETTER ZHAR", "Ll", 0, none),
  ("GEORGIAN LETTER RAE", "Ll", 0, none),
  ("GEORGIAN LETTER SAN", "Ll", 0, none),
  ("GEORGIAN LETTER TAR", "Ll", 0, none),
  ("GEORGIAN LETTER UN", "Ll", 0, none),
  ("GEORGIAN LETTER PHAR", "Ll", 0, none),
  ("GEORGIAN LETTER KHAR", "Ll", 0, none),
  ("GEORGIAN LETTER GHAN", "Ll", 0, none),
  ("GEORGIAN LETTER QAR", "Ll", 0, none),
  ("GEORGIAN LETTER SHIN", "Ll", 0, none),
  ("GEORGIAN LETTER CHIN", "Ll", 0, none),
  ("GEORGIAN LETTER CAN", "Ll", 0, none),
  ("GEORGIAN LETTER JIL", "Ll", 0, none),
  ("GEORGIAN LETTER CIL", "Ll", 0, none),
  ("GEORGIAN LETTER CHAR", "Ll", 0, none),
  ("GEORGIAN LETTER XAN", "Ll", 0, none),
  ("GEORGIAN LETTER JHAN", "Ll", 0, none),
  ("GEORGIAN LETTER HAE", "Ll", 0, none),
  ("GEORGIAN LETTER HE", "Ll", 0, none),
  ("GEORGIAN LETTER HIE", "Ll", 0, none),
  ("GEORGIAN LETTER WE", "Ll", 0, none),
  ("GEORGIAN LETTER HAR", "Ll", 0, none),
  ("GEORGIAN LETTER HOE", "Ll", 0, none),
  ("GEORGIAN LETTER FI", "Ll", 0, none),
  ("GEORGIAN LETTER YN", "Ll", 0, none),
  ("GEORGIAN LETTER ELIFI", "Ll", 0, none),
  ("GEORGIAN LETTER TURNED GAN", "Ll", 0, none),
  ("GEORGIAN LETTER AIN", "Ll", 0, none),
  ("GEORGIAN PARAGRAPH SEPARATOR", "Po", 0, none),
  ("MODIFIER LETTER GEORGIAN NAR", "Lm", 0, none),
  ("GEORGIAN LETTER AEN", "Ll", 0, none),
  ("GEORGIAN LETTER HARD SIGN", "Ll", 0, none),
  ("GEORGIAN LETTER LABIAL SIGN", "Ll", 0, none),
)
