#let data = (
  ("RUNIC LETTER FEHU FEOH FE F", "Lo", 0, none),
  ("RUNIC LETTER V", "Lo", 0, none),
  ("RUNIC LETTER URUZ UR U", "Lo", 0, none),
  ("RUNIC LETTER YR", "Lo", 0, none),
  ("RUNIC LETTER Y", "Lo", 0, none),
  ("RUNIC LETTER W", "Lo", 0, none),
  ("RUNIC LETTER THURISAZ THURS THORN", "Lo", 0, none),
  ("RUNIC LETTER ETH", "Lo", 0, none),
  ("RUNIC LETTER ANSUZ A", "Lo", 0, none),
  ("RUNIC LETTER OS O", "Lo", 0, none),
  ("RUNIC LETTER AC A", "Lo", 0, none),
  ("RUNIC LETTER AESC", "Lo", 0, none),
  ("RUNIC LETTER LONG-BRANCH-OSS O", "Lo", 0, none),
  ("RUNIC LETTER SHORT-TWIG-OSS O", "Lo", 0, none),
  ("RUNIC LETTER O", "Lo", 0, none),
  ("RUNIC LETTER OE", "Lo", 0, none),
  ("RUNIC LETTER ON", "Lo", 0, none),
  ("RUNIC LETTER RAIDO RAD REID R", "Lo", 0, none),
  ("RUNIC LETTER KAUNA", "Lo", 0, none),
  ("RUNIC LETTER CEN", "Lo", 0, none),
  ("RUNIC LETTER KAUN K", "Lo", 0, none),
  ("RUNIC LETTER G", "Lo", 0, none),
  ("RUNIC LETTER ENG", "Lo", 0, none),
  ("RUNIC LETTER GEBO GYFU G", "Lo", 0, none),
  ("RUNIC LETTER GAR", "Lo", 0, none),
  ("RUNIC LETTER WUNJO WYNN W", "Lo", 0, none),
  ("RUNIC LETTER HAGLAZ H", "Lo", 0, none),
  ("RUNIC LETTER HAEGL H", "Lo", 0, none),
  ("RUNIC LETTER LONG-BRANCH-HAGALL H", "Lo", 0, none),
  ("RUNIC LETTER SHORT-TWIG-HAGALL H", "Lo", 0, none),
  ("RUNIC LETTER NAUDIZ NYD NAUD N", "Lo", 0, none),
  ("RUNIC LETTER SHORT-TWIG-NAUD N", "Lo", 0, none),
  ("RUNIC LETTER DOTTED-N", "Lo", 0, none),
  ("RUNIC LETTER ISAZ IS ISS I", "Lo", 0, none),
  ("RUNIC LETTER E", "Lo", 0, none),
  ("RUNIC LETTER JERAN J", "Lo", 0, none),
  ("RUNIC LETTER GER", "Lo", 0, none),
  ("RUNIC LETTER LONG-BRANCH-AR AE", "Lo", 0, none),
  ("RUNIC LETTER SHORT-TWIG-AR A", "Lo", 0, none),
  ("RUNIC LETTER IWAZ EOH", "Lo", 0, none),
  ("RUNIC LETTER PERTHO PEORTH P", "Lo", 0, none),
  ("RUNIC LETTER ALGIZ EOLHX", "Lo", 0, none),
  ("RUNIC LETTER SOWILO S", "Lo", 0, none),
  ("RUNIC LETTER SIGEL LONG-BRANCH-SOL S", "Lo", 0, none),
  ("RUNIC LETTER SHORT-TWIG-SOL S", "Lo", 0, none),
  ("RUNIC LETTER C", "Lo", 0, none),
  ("RUNIC LETTER Z", "Lo", 0, none),
  ("RUNIC LETTER TIWAZ TIR TYR T", "Lo", 0, none),
  ("RUNIC LETTER SHORT-TWIG-TYR T", "Lo", 0, none),
  ("RUNIC LETTER D", "Lo", 0, none),
  ("RUNIC LETTER BERKANAN BEORC BJARKAN B", "Lo", 0, none),
  ("RUNIC LETTER SHORT-TWIG-BJARKAN B", "Lo", 0, none),
  ("RUNIC LETTER DOTTED-P", "Lo", 0, none),
  ("RUNIC LETTER OPEN-P", "Lo", 0, none),
  ("RUNIC LETTER EHWAZ EH E", "Lo", 0, none),
  ("RUNIC LETTER MANNAZ MAN M", "Lo", 0, none),
  ("RUNIC LETTER LONG-BRANCH-MADR M", "Lo", 0, none),
  ("RUNIC LETTER SHORT-TWIG-MADR M", "Lo", 0, none),
  ("RUNIC LETTER LAUKAZ LAGU LOGR L", "Lo", 0, none),
  ("RUNIC LETTER DOTTED-L", "Lo", 0, none),
  ("RUNIC LETTER INGWAZ", "Lo", 0, none),
  ("RUNIC LETTER ING", "Lo", 0, none),
  ("RUNIC LETTER DAGAZ DAEG D", "Lo", 0, none),
  ("RUNIC LETTER OTHALAN ETHEL O", "Lo", 0, none),
  ("RUNIC LETTER EAR", "Lo", 0, none),
  ("RUNIC LETTER IOR", "Lo", 0, none),
  ("RUNIC LETTER CWEORTH", "Lo", 0, none),
  ("RUNIC LETTER CALC", "Lo", 0, none),
  ("RUNIC LETTER CEALC", "Lo", 0, none),
  ("RUNIC LETTER STAN", "Lo", 0, none),
  ("RUNIC LETTER LONG-BRANCH-YR", "Lo", 0, none),
  ("RUNIC LETTER SHORT-TWIG-YR", "Lo", 0, none),
  ("RUNIC LETTER ICELANDIC-YR", "Lo", 0, none),
  ("RUNIC LETTER Q", "Lo", 0, none),
  ("RUNIC LETTER X", "Lo", 0, none),
  ("RUNIC SINGLE PUNCTUATION", "Po", 0, none),
  ("RUNIC MULTIPLE PUNCTUATION", "Po", 0, none),
  ("RUNIC CROSS PUNCTUATION", "Po", 0, none),
  ("RUNIC ARLAUG SYMBOL", "Nl", 0, none),
  ("RUNIC TVIMADUR SYMBOL", "Nl", 0, none),
  ("RUNIC BELGTHOR SYMBOL", "Nl", 0, none),
  ("RUNIC LETTER K", "Lo", 0, none),
  ("RUNIC LETTER SH", "Lo", 0, none),
  ("RUNIC LETTER OO", "Lo", 0, none),
  ("RUNIC LETTER FRANKS CASKET OS", "Lo", 0, none),
  ("RUNIC LETTER FRANKS CASKET IS", "Lo", 0, none),
  ("RUNIC LETTER FRANKS CASKET EH", "Lo", 0, none),
  ("RUNIC LETTER FRANKS CASKET AC", "Lo", 0, none),
  ("RUNIC LETTER FRANKS CASKET AESC", "Lo", 0, none),
)
