#let data = (
  ("ACCOUNT OF", "So", 0, none),
  ("ADDRESSED TO THE SUBJECT", "So", 0, none),
  ("DOUBLE-STRUCK CAPITAL C", "Lu", 0, "A"),
  ("DEGREE CELSIUS", "So", 0, none),
  ("CENTRE LINE SYMBOL", "So", 0, none),
  ("CARE OF", "So", 0, none),
  ("CADA UNA", "So", 0, none),
  ("EULER CONSTANT", "Lu", 0, "N"),
  ("SCRUPLE", "So", 0, none),
  ("DEGREE FAHRENHEIT", "So", 0, none),
  ("SCRIPT SMALL G", "Ll", 0, "A"),
  ("SCRIPT CAPITAL H", "Lu", 0, "A"),
  ("BLACK-LETTER CAPITAL H", "Lu", 0, "A"),
  ("DOUBLE-STRUCK CAPITAL H", "Lu", 0, "A"),
  ("PLANCK CONSTANT", "Ll", 0, "N"),
  ("PLANCK CONSTANT OVER TWO PI", "Ll", 0, "N"),
  ("SCRIPT CAPITAL I", "Lu", 0, "A"),
  ("BLACK-LETTER CAPITAL I", "Lu", 0, "A"),
  ("SCRIPT CAPITAL L", "Lu", 0, "A"),
  ("SCRIPT SMALL L", "Ll", 0, "A"),
  ("L B BAR SYMBOL", "So", 0, none),
  ("DOUBLE-STRUCK CAPITAL N", "Lu", 0, "A"),
  ("NUMERO SIGN", "So", 0, none),
  ("SOUND RECORDING COPYRIGHT", "So", 0, none),
  ("SCRIPT CAPITAL P", "Sm", 0, "A"),
  ("DOUBLE-STRUCK CAPITAL P", "Lu", 0, "A"),
  ("DOUBLE-STRUCK CAPITAL Q", "Lu", 0, "A"),
  ("SCRIPT CAPITAL R", "Lu", 0, "A"),
  ("BLACK-LETTER CAPITAL R", "Lu", 0, "A"),
  ("DOUBLE-STRUCK CAPITAL R", "Lu", 0, "A"),
  ("PRESCRIPTION TAKE", "So", 0, none),
  ("RESPONSE", "So", 0, none),
  ("SERVICE MARK", "So", 0, none),
  ("TELEPHONE SIGN", "So", 0, none),
  ("TRADE MARK SIGN", "So", 0, none),
  ("VERSICLE", "So", 0, none),
  ("DOUBLE-STRUCK CAPITAL Z", "Lu", 0, "A"),
  ("OUNCE SIGN", "So", 0, none),
  ("OHM SIGN", "Lu", 0, "N"),
  ("INVERTED OHM SIGN", "So", 0, "N"),
  ("BLACK-LETTER CAPITAL Z", "Lu", 0, "A"),
  ("TURNED GREEK SMALL LETTER IOTA", "So", 0, "N"),
  ("KELVIN SIGN", "Lu", 0, none),
  ("ANGSTROM SIGN", "Lu", 0, "A"),
  ("SCRIPT CAPITAL B", "Lu", 0, "A"),
  ("BLACK-LETTER CAPITAL C", "Lu", 0, "A"),
  ("ESTIMATED SYMBOL", "So", 0, none),
  ("SCRIPT SMALL E", "Ll", 0, "A"),
  ("SCRIPT CAPITAL E", "Lu", 0, "A"),
  ("SCRIPT CAPITAL F", "Lu", 0, "A"),
  ("TURNED CAPITAL F", "Lu", 0, "N"),
  ("SCRIPT CAPITAL M", "Lu", 0, "A"),
  ("SCRIPT SMALL O", "Ll", 0, "A"),
  ("ALEF SYMBOL", "Lo", 0, "A"),
  ("BET SYMBOL", "Lo", 0, "A"),
  ("GIMEL SYMBOL", "Lo", 0, "A"),
  ("DALET SYMBOL", "Lo", 0, "A"),
  ("INFORMATION SOURCE", "Ll", 0, none),
  ("ROTATED CAPITAL Q", "So", 0, none),
  ("FACSIMILE SIGN", "So", 0, none),
  ("DOUBLE-STRUCK SMALL PI", "Ll", 0, "A"),
  ("DOUBLE-STRUCK SMALL GAMMA", "Ll", 0, "A"),
  ("DOUBLE-STRUCK CAPITAL GAMMA", "Lu", 0, "N"),
  ("DOUBLE-STRUCK CAPITAL PI", "Lu", 0, "A"),
  ("DOUBLE-STRUCK N-ARY SUMMATION", "Sm", 0, "L"),
  ("TURNED SANS-SERIF CAPITAL G", "Sm", 0, "N"),
  ("TURNED SANS-SERIF CAPITAL L", "Sm", 0, "N"),
  ("REVERSED SANS-SERIF CAPITAL L", "Sm", 0, "N"),
  ("TURNED SANS-SERIF CAPITAL Y", "Sm", 0, "N"),
  ("DOUBLE-STRUCK ITALIC CAPITAL D", "Lu", 0, "N"),
  ("DOUBLE-STRUCK ITALIC SMALL D", "Ll", 0, "N"),
  ("DOUBLE-STRUCK ITALIC SMALL E", "Ll", 0, "N"),
  ("DOUBLE-STRUCK ITALIC SMALL I", "Ll", 0, "N"),
  ("DOUBLE-STRUCK ITALIC SMALL J", "Ll", 0, "N"),
  ("PROPERTY LINE", "So", 0, none),
  ("TURNED AMPERSAND", "Sm", 0, "N"),
  ("PER SIGN", "So", 0, none),
  ("AKTIESELSKAB", "So", 0, none),
  ("TURNED SMALL F", "Ll", 0, none),
  ("SYMBOL FOR SAMARITAN SOURCE", "So", 0, none),
)
