#let data = (
  (),
  ("HIRAGANA LETTER SMALL A", "Lo", 0, none),
  ("HIRAGANA LETTER A", "Lo", 0, none),
  ("HIRAGANA LETTER SMALL I", "Lo", 0, none),
  ("HIRAGANA LETTER I", "Lo", 0, none),
  ("HIRAGANA LETTER SMALL U", "Lo", 0, none),
  ("HIRAGANA LETTER U", "Lo", 0, none),
  ("HIRAGANA LETTER SMALL E", "Lo", 0, none),
  ("HIRAGANA LETTER E", "Lo", 0, none),
  ("HIRAGANA LETTER SMALL O", "Lo", 0, none),
  ("HIRAGANA LETTER O", "Lo", 0, none),
  ("HIRAGANA LETTER KA", "Lo", 0, none),
  ("HIRAGANA LETTER GA", "Lo", 0, none),
  ("HIRAGANA LETTER KI", "Lo", 0, none),
  ("HIRAGANA LETTER GI", "Lo", 0, none),
  ("HIRAGANA LETTER KU", "Lo", 0, none),
  ("HIRAGANA LETTER GU", "Lo", 0, none),
  ("HIRAGANA LETTER KE", "Lo", 0, none),
  ("HIRAGANA LETTER GE", "Lo", 0, none),
  ("HIRAGANA LETTER KO", "Lo", 0, none),
  ("HIRAGANA LETTER GO", "Lo", 0, none),
  ("HIRAGANA LETTER SA", "Lo", 0, none),
  ("HIRAGANA LETTER ZA", "Lo", 0, none),
  ("HIRAGANA LETTER SI", "Lo", 0, none),
  ("HIRAGANA LETTER ZI", "Lo", 0, none),
  ("HIRAGANA LETTER SU", "Lo", 0, none),
  ("HIRAGANA LETTER ZU", "Lo", 0, none),
  ("HIRAGANA LETTER SE", "Lo", 0, none),
  ("HIRAGANA LETTER ZE", "Lo", 0, none),
  ("HIRAGANA LETTER SO", "Lo", 0, none),
  ("HIRAGANA LETTER ZO", "Lo", 0, none),
  ("HIRAGANA LETTER TA", "Lo", 0, none),
  ("HIRAGANA LETTER DA", "Lo", 0, none),
  ("HIRAGANA LETTER TI", "Lo", 0, none),
  ("HIRAGANA LETTER DI", "Lo", 0, none),
  ("HIRAGANA LETTER SMALL TU", "Lo", 0, none),
  ("HIRAGANA LETTER TU", "Lo", 0, none),
  ("HIRAGANA LETTER DU", "Lo", 0, none),
  ("HIRAGANA LETTER TE", "Lo", 0, none),
  ("HIRAGANA LETTER DE", "Lo", 0, none),
  ("HIRAGANA LETTER TO", "Lo", 0, none),
  ("HIRAGANA LETTER DO", "Lo", 0, none),
  ("HIRAGANA LETTER NA", "Lo", 0, none),
  ("HIRAGANA LETTER NI", "Lo", 0, none),
  ("HIRAGANA LETTER NU", "Lo", 0, none),
  ("HIRAGANA LETTER NE", "Lo", 0, none),
  ("HIRAGANA LETTER NO", "Lo", 0, "N"),
  ("HIRAGANA LETTER HA", "Lo", 0, none),
  ("HIRAGANA LETTER BA", "Lo", 0, none),
  ("HIRAGANA LETTER PA", "Lo", 0, none),
  ("HIRAGANA LETTER HI", "Lo", 0, none),
  ("HIRAGANA LETTER BI", "Lo", 0, none),
  ("HIRAGANA LETTER PI", "Lo", 0, none),
  ("HIRAGANA LETTER HU", "Lo", 0, none),
  ("HIRAGANA LETTER BU", "Lo", 0, none),
  ("HIRAGANA LETTER PU", "Lo", 0, none),
  ("HIRAGANA LETTER HE", "Lo", 0, none),
  ("HIRAGANA LETTER BE", "Lo", 0, none),
  ("HIRAGANA LETTER PE", "Lo", 0, none),
  ("HIRAGANA LETTER HO", "Lo", 0, none),
  ("HIRAGANA LETTER BO", "Lo", 0, none),
  ("HIRAGANA LETTER PO", "Lo", 0, none),
  ("HIRAGANA LETTER MA", "Lo", 0, none),
  ("HIRAGANA LETTER MI", "Lo", 0, none),
  ("HIRAGANA LETTER MU", "Lo", 0, none),
  ("HIRAGANA LETTER ME", "Lo", 0, none),
  ("HIRAGANA LETTER MO", "Lo", 0, none),
  ("HIRAGANA LETTER SMALL YA", "Lo", 0, none),
  ("HIRAGANA LETTER YA", "Lo", 0, none),
  ("HIRAGANA LETTER SMALL YU", "Lo", 0, none),
  ("HIRAGANA LETTER YU", "Lo", 0, none),
  ("HIRAGANA LETTER SMALL YO", "Lo", 0, none),
  ("HIRAGANA LETTER YO", "Lo", 0, none),
  ("HIRAGANA LETTER RA", "Lo", 0, none),
  ("HIRAGANA LETTER RI", "Lo", 0, none),
  ("HIRAGANA LETTER RU", "Lo", 0, none),
  ("HIRAGANA LETTER RE", "Lo", 0, none),
  ("HIRAGANA LETTER RO", "Lo", 0, none),
  ("HIRAGANA LETTER SMALL WA", "Lo", 0, none),
  ("HIRAGANA LETTER WA", "Lo", 0, none),
  ("HIRAGANA LETTER WI", "Lo", 0, none),
  ("HIRAGANA LETTER WE", "Lo", 0, none),
  ("HIRAGANA LETTER WO", "Lo", 0, none),
  ("HIRAGANA LETTER N", "Lo", 0, none),
  ("HIRAGANA LETTER VU", "Lo", 0, none),
  ("HIRAGANA LETTER SMALL KA", "Lo", 0, none),
  ("HIRAGANA LETTER SMALL KE", "Lo", 0, none),
  (),
  (),
  ("COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK", "Mn", 8, none),
  ("COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK", "Mn", 8, none),
  ("KATAKANA-HIRAGANA VOICED SOUND MARK", "Sk", 0, none),
  ("KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK", "Sk", 0, none),
  ("HIRAGANA ITERATION MARK", "Lm", 0, none),
  ("HIRAGANA VOICED ITERATION MARK", "Lm", 0, none),
  ("HIRAGANA DIGRAPH YORI", "Lo", 0, none),
)
