#let data = (
  ("SOYOMBO LETTER A", "Lo", 0, none),
  ("SOYOMBO VOWEL SIGN I", "Mn", 0, none),
  ("SOYOMBO VOWEL SIGN UE", "Mn", 0, none),
  ("SOYOMBO VOWEL SIGN U", "Mn", 0, none),
  ("SOYOMBO VOWEL SIGN E", "Mn", 0, none),
  ("SOYOMBO VOWEL SIGN O", "Mn", 0, none),
  ("SOYOMBO VOWEL SIGN OE", "Mn", 0, none),
  ("SOYOMBO VOWEL SIGN AI", "Mc", 0, none),
  ("SOYOMBO VOWEL SIGN AU", "Mc", 0, none),
  ("SOYOMBO VOWEL SIGN VOCALIC R", "Mn", 0, none),
  ("SOYOMBO VOWEL SIGN VOCALIC L", "Mn", 0, none),
  ("SOYOMBO VOWEL LENGTH MARK", "Mn", 0, none),
  ("SOYOMBO LETTER KA", "Lo", 0, none),
  ("SOYOMBO LETTER KHA", "Lo", 0, none),
  ("SOYOMBO LETTER GA", "Lo", 0, none),
  ("SOYOMBO LETTER GHA", "Lo", 0, none),
  ("SOYOMBO LETTER NGA", "Lo", 0, none),
  ("SOYOMBO LETTER CA", "Lo", 0, none),
  ("SOYOMBO LETTER CHA", "Lo", 0, none),
  ("SOYOMBO LETTER JA", "Lo", 0, none),
  ("SOYOMBO LETTER JHA", "Lo", 0, none),
  ("SOYOMBO LETTER NYA", "Lo", 0, none),
  ("SOYOMBO LETTER TTA", "Lo", 0, none),
  ("SOYOMBO LETTER TTHA", "Lo", 0, none),
  ("SOYOMBO LETTER DDA", "Lo", 0, none),
  ("SOYOMBO LETTER DDHA", "Lo", 0, none),
  ("SOYOMBO LETTER NNA", "Lo", 0, none),
  ("SOYOMBO LETTER TA", "Lo", 0, none),
  ("SOYOMBO LETTER THA", "Lo", 0, none),
  ("SOYOMBO LETTER DA", "Lo", 0, none),
  ("SOYOMBO LETTER DHA", "Lo", 0, none),
  ("SOYOMBO LETTER NA", "Lo", 0, none),
  ("SOYOMBO LETTER PA", "Lo", 0, none),
  ("SOYOMBO LETTER PHA", "Lo", 0, none),
  ("SOYOMBO LETTER BA", "Lo", 0, none),
  ("SOYOMBO LETTER BHA", "Lo", 0, none),
  ("SOYOMBO LETTER MA", "Lo", 0, none),
  ("SOYOMBO LETTER TSA", "Lo", 0, none),
  ("SOYOMBO LETTER TSHA", "Lo", 0, none),
  ("SOYOMBO LETTER DZA", "Lo", 0, none),
  ("SOYOMBO LETTER ZHA", "Lo", 0, none),
  ("SOYOMBO LETTER ZA", "Lo", 0, none),
  ("SOYOMBO LETTER -A", "Lo", 0, none),
  ("SOYOMBO LETTER YA", "Lo", 0, none),
  ("SOYOMBO LETTER RA", "Lo", 0, none),
  ("SOYOMBO LETTER LA", "Lo", 0, none),
  ("SOYOMBO LETTER VA", "Lo", 0, none),
  ("SOYOMBO LETTER SHA", "Lo", 0, none),
  ("SOYOMBO LETTER SSA", "Lo", 0, none),
  ("SOYOMBO LETTER SA", "Lo", 0, none),
  ("SOYOMBO LETTER HA", "Lo", 0, none),
  ("SOYOMBO LETTER KSSA", "Lo", 0, none),
  ("SOYOMBO SIGN JIHVAMULIYA", "Lo", 0, none),
  ("SOYOMBO SIGN UPADHMANIYA", "Lo", 0, none),
  ("SOYOMBO CLUSTER-INITIAL LETTER RA", "Lo", 0, none),
  ("SOYOMBO CLUSTER-INITIAL LETTER LA", "Lo", 0, none),
  ("SOYOMBO CLUSTER-INITIAL LETTER SHA", "Lo", 0, none),
  ("SOYOMBO CLUSTER-INITIAL LETTER SA", "Lo", 0, none),
  ("SOYOMBO FINAL CONSONANT SIGN G", "Mn", 0, none),
  ("SOYOMBO FINAL CONSONANT SIGN K", "Mn", 0, none),
  ("SOYOMBO FINAL CONSONANT SIGN NG", "Mn", 0, none),
  ("SOYOMBO FINAL CONSONANT SIGN D", "Mn", 0, none),
  ("SOYOMBO FINAL CONSONANT SIGN N", "Mn", 0, none),
  ("SOYOMBO FINAL CONSONANT SIGN B", "Mn", 0, none),
  ("SOYOMBO FINAL CONSONANT SIGN M", "Mn", 0, none),
  ("SOYOMBO FINAL CONSONANT SIGN R", "Mn", 0, none),
  ("SOYOMBO FINAL CONSONANT SIGN L", "Mn", 0, none),
  ("SOYOMBO FINAL CONSONANT SIGN SH", "Mn", 0, none),
  ("SOYOMBO FINAL CONSONANT SIGN S", "Mn", 0, none),
  ("SOYOMBO FINAL CONSONANT SIGN -A", "Mn", 0, none),
  ("SOYOMBO SIGN ANUSVARA", "Mn", 0, none),
  ("SOYOMBO SIGN VISARGA", "Mc", 0, none),
  ("SOYOMBO GEMINATION MARK", "Mn", 0, none),
  ("SOYOMBO SUBJOINER", "Mn", 9, none),
  ("SOYOMBO MARK TSHEG", "Po", 0, none),
  ("SOYOMBO MARK SHAD", "Po", 0, none),
  ("SOYOMBO MARK DOUBLE SHAD", "Po", 0, none),
  ("SOYOMBO MARK PLUTA", "Lo", 0, none),
  ("SOYOMBO HEAD MARK WITH MOON AND SUN AND TRIPLE FLAME", "Po", 0, none),
  ("SOYOMBO HEAD MARK WITH MOON AND SUN AND FLAME", "Po", 0, none),
  ("SOYOMBO HEAD MARK WITH MOON AND SUN", "Po", 0, none),
  ("SOYOMBO TERMINAL MARK-1", "Po", 0, none),
  ("SOYOMBO TERMINAL MARK-2", "Po", 0, none),
)
