#let data = (
  ("DUPLOYAN LETTER H", "Lo", 0, none),
  ("DUPLOYAN LETTER X", "Lo", 0, none),
  ("DUPLOYAN LETTER P", "Lo", 0, none),
  ("DUPLOYAN LETTER T", "Lo", 0, none),
  ("DUPLOYAN LETTER F", "Lo", 0, none),
  ("DUPLOYAN LETTER K", "Lo", 0, none),
  ("DUPLOYAN LETTER L", "Lo", 0, none),
  ("DUPLOYAN LETTER B", "Lo", 0, none),
  ("DUPLOYAN LETTER D", "Lo", 0, none),
  ("DUPLOYAN LETTER V", "Lo", 0, none),
  ("DUPLOYAN LETTER G", "Lo", 0, none),
  ("DUPLOYAN LETTER R", "Lo", 0, none),
  ("DUPLOYAN LETTER P N", "Lo", 0, none),
  ("DUPLOYAN LETTER D S", "Lo", 0, none),
  ("DUPLOYAN LETTER F N", "Lo", 0, none),
  ("DUPLOYAN LETTER K M", "Lo", 0, none),
  ("DUPLOYAN LETTER R S", "Lo", 0, none),
  ("DUPLOYAN LETTER TH", "Lo", 0, none),
  ("DUPLOYAN LETTER SLOAN DH", "Lo", 0, none),
  ("DUPLOYAN LETTER DH", "Lo", 0, none),
  ("DUPLOYAN LETTER KK", "Lo", 0, none),
  ("DUPLOYAN LETTER SLOAN J", "Lo", 0, none),
  ("DUPLOYAN LETTER HL", "Lo", 0, none),
  ("DUPLOYAN LETTER LH", "Lo", 0, none),
  ("DUPLOYAN LETTER RH", "Lo", 0, none),
  ("DUPLOYAN LETTER M", "Lo", 0, none),
  ("DUPLOYAN LETTER N", "Lo", 0, none),
  ("DUPLOYAN LETTER J", "Lo", 0, none),
  ("DUPLOYAN LETTER S", "Lo", 0, none),
  ("DUPLOYAN LETTER M N", "Lo", 0, none),
  ("DUPLOYAN LETTER N M", "Lo", 0, none),
  ("DUPLOYAN LETTER J M", "Lo", 0, none),
  ("DUPLOYAN LETTER S J", "Lo", 0, none),
  ("DUPLOYAN LETTER M WITH DOT", "Lo", 0, none),
  ("DUPLOYAN LETTER N WITH DOT", "Lo", 0, none),
  ("DUPLOYAN LETTER J WITH DOT", "Lo", 0, none),
  ("DUPLOYAN LETTER J WITH DOTS INSIDE AND ABOVE", "Lo", 0, none),
  ("DUPLOYAN LETTER S WITH DOT", "Lo", 0, none),
  ("DUPLOYAN LETTER S WITH DOT BELOW", "Lo", 0, none),
  ("DUPLOYAN LETTER M S", "Lo", 0, none),
  ("DUPLOYAN LETTER N S", "Lo", 0, none),
  ("DUPLOYAN LETTER J S", "Lo", 0, none),
  ("DUPLOYAN LETTER S S", "Lo", 0, none),
  ("DUPLOYAN LETTER M N S", "Lo", 0, none),
  ("DUPLOYAN LETTER N M S", "Lo", 0, none),
  ("DUPLOYAN LETTER J M S", "Lo", 0, none),
  ("DUPLOYAN LETTER S J S", "Lo", 0, none),
  ("DUPLOYAN LETTER J S WITH DOT", "Lo", 0, none),
  ("DUPLOYAN LETTER J N", "Lo", 0, none),
  ("DUPLOYAN LETTER J N S", "Lo", 0, none),
  ("DUPLOYAN LETTER S T", "Lo", 0, none),
  ("DUPLOYAN LETTER S T R", "Lo", 0, none),
  ("DUPLOYAN LETTER S P", "Lo", 0, none),
  ("DUPLOYAN LETTER S P R", "Lo", 0, none),
  ("DUPLOYAN LETTER T S", "Lo", 0, none),
  ("DUPLOYAN LETTER T R S", "Lo", 0, none),
  ("DUPLOYAN LETTER W", "Lo", 0, none),
  ("DUPLOYAN LETTER WH", "Lo", 0, none),
  ("DUPLOYAN LETTER W R", "Lo", 0, none),
  ("DUPLOYAN LETTER S N", "Lo", 0, none),
  ("DUPLOYAN LETTER S M", "Lo", 0, none),
  ("DUPLOYAN LETTER K R S", "Lo", 0, none),
  ("DUPLOYAN LETTER G R S", "Lo", 0, none),
  ("DUPLOYAN LETTER S K", "Lo", 0, none),
  ("DUPLOYAN LETTER S K R", "Lo", 0, none),
  ("DUPLOYAN LETTER A", "Lo", 0, none),
  ("DUPLOYAN LETTER SLOAN OW", "Lo", 0, none),
  ("DUPLOYAN LETTER OA", "Lo", 0, none),
  ("DUPLOYAN LETTER O", "Lo", 0, none),
  ("DUPLOYAN LETTER AOU", "Lo", 0, none),
  ("DUPLOYAN LETTER I", "Lo", 0, none),
  ("DUPLOYAN LETTER E", "Lo", 0, none),
  ("DUPLOYAN LETTER IE", "Lo", 0, none),
  ("DUPLOYAN LETTER SHORT I", "Lo", 0, none),
  ("DUPLOYAN LETTER UI", "Lo", 0, none),
  ("DUPLOYAN LETTER EE", "Lo", 0, none),
  ("DUPLOYAN LETTER SLOAN EH", "Lo", 0, none),
  ("DUPLOYAN LETTER ROMANIAN I", "Lo", 0, none),
  ("DUPLOYAN LETTER SLOAN EE", "Lo", 0, none),
  ("DUPLOYAN LETTER LONG I", "Lo", 0, none),
  ("DUPLOYAN LETTER YE", "Lo", 0, none),
  ("DUPLOYAN LETTER U", "Lo", 0, none),
  ("DUPLOYAN LETTER EU", "Lo", 0, none),
  ("DUPLOYAN LETTER XW", "Lo", 0, none),
  ("DUPLOYAN LETTER U N", "Lo", 0, none),
  ("DUPLOYAN LETTER LONG U", "Lo", 0, none),
  ("DUPLOYAN LETTER ROMANIAN U", "Lo", 0, none),
  ("DUPLOYAN LETTER UH", "Lo", 0, none),
  ("DUPLOYAN LETTER SLOAN U", "Lo", 0, none),
  ("DUPLOYAN LETTER OOH", "Lo", 0, none),
  ("DUPLOYAN LETTER OW", "Lo", 0, none),
  ("DUPLOYAN LETTER OU", "Lo", 0, none),
  ("DUPLOYAN LETTER WA", "Lo", 0, none),
  ("DUPLOYAN LETTER WO", "Lo", 0, none),
  ("DUPLOYAN LETTER WI", "Lo", 0, none),
  ("DUPLOYAN LETTER WEI", "Lo", 0, none),
  ("DUPLOYAN LETTER WOW", "Lo", 0, none),
  ("DUPLOYAN LETTER NASAL U", "Lo", 0, none),
  ("DUPLOYAN LETTER NASAL O", "Lo", 0, none),
  ("DUPLOYAN LETTER NASAL I", "Lo", 0, none),
  ("DUPLOYAN LETTER NASAL A", "Lo", 0, none),
  ("DUPLOYAN LETTER PERNIN AN", "Lo", 0, none),
  ("DUPLOYAN LETTER PERNIN AM", "Lo", 0, none),
  ("DUPLOYAN LETTER SLOAN EN", "Lo", 0, none),
  ("DUPLOYAN LETTER SLOAN AN", "Lo", 0, none),
  ("DUPLOYAN LETTER SLOAN ON", "Lo", 0, none),
  ("DUPLOYAN LETTER VOCALIC M", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  ("DUPLOYAN AFFIX LEFT HORIZONTAL SECANT", "Lo", 0, none),
  ("DUPLOYAN AFFIX MID HORIZONTAL SECANT", "Lo", 0, none),
  ("DUPLOYAN AFFIX RIGHT HORIZONTAL SECANT", "Lo", 0, none),
  ("DUPLOYAN AFFIX LOW VERTICAL SECANT", "Lo", 0, none),
  ("DUPLOYAN AFFIX MID VERTICAL SECANT", "Lo", 0, none),
  ("DUPLOYAN AFFIX HIGH VERTICAL SECANT", "Lo", 0, none),
  ("DUPLOYAN AFFIX ATTACHED SECANT", "Lo", 0, none),
  ("DUPLOYAN AFFIX ATTACHED LEFT-TO-RIGHT SECANT", "Lo", 0, none),
  ("DUPLOYAN AFFIX ATTACHED TANGENT", "Lo", 0, none),
  ("DUPLOYAN AFFIX ATTACHED TAIL", "Lo", 0, none),
  ("DUPLOYAN AFFIX ATTACHED E HOOK", "Lo", 0, none),
  ("DUPLOYAN AFFIX ATTACHED I HOOK", "Lo", 0, none),
  ("DUPLOYAN AFFIX ATTACHED TANGENT HOOK", "Lo", 0, none),
  (),
  (),
  (),
  ("DUPLOYAN AFFIX HIGH ACUTE", "Lo", 0, none),
  ("DUPLOYAN AFFIX HIGH TIGHT ACUTE", "Lo", 0, none),
  ("DUPLOYAN AFFIX HIGH GRAVE", "Lo", 0, none),
  ("DUPLOYAN AFFIX HIGH LONG GRAVE", "Lo", 0, none),
  ("DUPLOYAN AFFIX HIGH DOT", "Lo", 0, none),
  ("DUPLOYAN AFFIX HIGH CIRCLE", "Lo", 0, none),
  ("DUPLOYAN AFFIX HIGH LINE", "Lo", 0, none),
  ("DUPLOYAN AFFIX HIGH WAVE", "Lo", 0, none),
  ("DUPLOYAN AFFIX HIGH VERTICAL", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("DUPLOYAN AFFIX LOW ACUTE", "Lo", 0, none),
  ("DUPLOYAN AFFIX LOW TIGHT ACUTE", "Lo", 0, none),
  ("DUPLOYAN AFFIX LOW GRAVE", "Lo", 0, none),
  ("DUPLOYAN AFFIX LOW LONG GRAVE", "Lo", 0, none),
  ("DUPLOYAN AFFIX LOW DOT", "Lo", 0, none),
  ("DUPLOYAN AFFIX LOW CIRCLE", "Lo", 0, none),
  ("DUPLOYAN AFFIX LOW LINE", "Lo", 0, none),
  ("DUPLOYAN AFFIX LOW WAVE", "Lo", 0, none),
  ("DUPLOYAN AFFIX LOW VERTICAL", "Lo", 0, none),
  ("DUPLOYAN AFFIX LOW ARROW", "Lo", 0, none),
  (),
  (),
  ("DUPLOYAN SIGN O WITH CROSS", "So", 0, none),
  ("DUPLOYAN THICK LETTER SELECTOR", "Mn", 0, none),
  ("DUPLOYAN DOUBLE MARK", "Mn", 1, none),
  ("DUPLOYAN PUNCTUATION CHINOOK FULL STOP", "Po", 0, none),
)
