#let data = (
  ("MEETEI MAYEK LETTER KOK", "Lo", 0, none),
  ("MEETEI MAYEK LETTER SAM", "Lo", 0, none),
  ("MEETEI MAYEK LETTER LAI", "Lo", 0, none),
  ("MEETEI MAYEK LETTER MIT", "Lo", 0, none),
  ("MEETEI MAYEK LETTER PA", "Lo", 0, none),
  ("MEETEI MAYEK LETTER NA", "Lo", 0, none),
  ("MEETEI MAYEK LETTER CHIL", "Lo", 0, none),
  ("MEETEI MAYEK LETTER TIL", "Lo", 0, none),
  ("MEETEI MAYEK LETTER KHOU", "Lo", 0, none),
  ("MEETEI MAYEK LETTER NGOU", "Lo", 0, none),
  ("MEETEI MAYEK LETTER THOU", "Lo", 0, none),
  ("MEETEI MAYEK LETTER WAI", "Lo", 0, none),
  ("MEETEI MAYEK LETTER YANG", "Lo", 0, none),
  ("MEETEI MAYEK LETTER HUK", "Lo", 0, none),
  ("MEETEI MAYEK LETTER UN", "Lo", 0, none),
  ("MEETEI MAYEK LETTER I", "Lo", 0, none),
  ("MEETEI MAYEK LETTER PHAM", "Lo", 0, none),
  ("MEETEI MAYEK LETTER ATIYA", "Lo", 0, none),
  ("MEETEI MAYEK LETTER GOK", "Lo", 0, none),
  ("MEETEI MAYEK LETTER JHAM", "Lo", 0, none),
  ("MEETEI MAYEK LETTER RAI", "Lo", 0, none),
  ("MEETEI MAYEK LETTER BA", "Lo", 0, none),
  ("MEETEI MAYEK LETTER JIL", "Lo", 0, none),
  ("MEETEI MAYEK LETTER DIL", "Lo", 0, none),
  ("MEETEI MAYEK LETTER GHOU", "Lo", 0, none),
  ("MEETEI MAYEK LETTER DHOU", "Lo", 0, none),
  ("MEETEI MAYEK LETTER BHAM", "Lo", 0, none),
  ("MEETEI MAYEK LETTER KOK LONSUM", "Lo", 0, none),
  ("MEETEI MAYEK LETTER LAI LONSUM", "Lo", 0, none),
  ("MEETEI MAYEK LETTER MIT LONSUM", "Lo", 0, none),
  ("MEETEI MAYEK LETTER PA LONSUM", "Lo", 0, none),
  ("MEETEI MAYEK LETTER NA LONSUM", "Lo", 0, none),
  ("MEETEI MAYEK LETTER TIL LONSUM", "Lo", 0, none),
  ("MEETEI MAYEK LETTER NGOU LONSUM", "Lo", 0, none),
  ("MEETEI MAYEK LETTER I LONSUM", "Lo", 0, none),
  ("MEETEI MAYEK VOWEL SIGN ONAP", "Mc", 0, none),
  ("MEETEI MAYEK VOWEL SIGN INAP", "Mc", 0, none),
  ("MEETEI MAYEK VOWEL SIGN ANAP", "Mn", 0, none),
  ("MEETEI MAYEK VOWEL SIGN YENAP", "Mc", 0, none),
  ("MEETEI MAYEK VOWEL SIGN SOUNAP", "Mc", 0, none),
  ("MEETEI MAYEK VOWEL SIGN UNAP", "Mn", 0, none),
  ("MEETEI MAYEK VOWEL SIGN CHEINAP", "Mc", 0, none),
  ("MEETEI MAYEK VOWEL SIGN NUNG", "Mc", 0, none),
  ("MEETEI MAYEK CHEIKHEI", "Po", 0, none),
  ("MEETEI MAYEK LUM IYEK", "Mc", 0, none),
  ("MEETEI MAYEK APUN IYEK", "Mn", 9, none),
  (),
  (),
  ("MEETEI MAYEK DIGIT ZERO", "Nd", 0, none),
  ("MEETEI MAYEK DIGIT ONE", "Nd", 0, none),
  ("MEETEI MAYEK DIGIT TWO", "Nd", 0, none),
  ("MEETEI MAYEK DIGIT THREE", "Nd", 0, none),
  ("MEETEI MAYEK DIGIT FOUR", "Nd", 0, none),
  ("MEETEI MAYEK DIGIT FIVE", "Nd", 0, none),
  ("MEETEI MAYEK DIGIT SIX", "Nd", 0, none),
  ("MEETEI MAYEK DIGIT SEVEN", "Nd", 0, none),
  ("MEETEI MAYEK DIGIT EIGHT", "Nd", 0, none),
  ("MEETEI MAYEK DIGIT NINE", "Nd", 0, none),
)
