#let data = (
  ("OLD PERSIAN SIGN A", "Lo", 0, none),
  ("OLD PERSIAN SIGN I", "Lo", 0, none),
  ("OLD PERSIAN SIGN U", "Lo", 0, none),
  ("OLD PERSIAN SIGN KA", "Lo", 0, none),
  ("OLD PERSIAN SIGN KU", "Lo", 0, none),
  ("OLD PERSIAN SIGN GA", "Lo", 0, none),
  ("OLD PERSIAN SIGN GU", "Lo", 0, none),
  ("OLD PERSIAN SIGN XA", "Lo", 0, none),
  ("OLD PERSIAN SIGN CA", "Lo", 0, none),
  ("OLD PERSIAN SIGN JA", "Lo", 0, none),
  ("OLD PERSIAN SIGN JI", "Lo", 0, none),
  ("OLD PERSIAN SIGN TA", "Lo", 0, none),
  ("OLD PERSIAN SIGN TU", "Lo", 0, none),
  ("OLD PERSIAN SIGN DA", "Lo", 0, none),
  ("OLD PERSIAN SIGN DI", "Lo", 0, none),
  ("OLD PERSIAN SIGN DU", "Lo", 0, none),
  ("OLD PERSIAN SIGN THA", "Lo", 0, none),
  ("OLD PERSIAN SIGN PA", "Lo", 0, none),
  ("OLD PERSIAN SIGN BA", "Lo", 0, none),
  ("OLD PERSIAN SIGN FA", "Lo", 0, none),
  ("OLD PERSIAN SIGN NA", "Lo", 0, none),
  ("OLD PERSIAN SIGN NU", "Lo", 0, none),
  ("OLD PERSIAN SIGN MA", "Lo", 0, none),
  ("OLD PERSIAN SIGN MI", "Lo", 0, none),
  ("OLD PERSIAN SIGN MU", "Lo", 0, none),
  ("OLD PERSIAN SIGN YA", "Lo", 0, none),
  ("OLD PERSIAN SIGN VA", "Lo", 0, none),
  ("OLD PERSIAN SIGN VI", "Lo", 0, none),
  ("OLD PERSIAN SIGN RA", "Lo", 0, none),
  ("OLD PERSIAN SIGN RU", "Lo", 0, none),
  ("OLD PERSIAN SIGN LA", "Lo", 0, none),
  ("OLD PERSIAN SIGN SA", "Lo", 0, none),
  ("OLD PERSIAN SIGN ZA", "Lo", 0, none),
  ("OLD PERSIAN SIGN SHA", "Lo", 0, none),
  ("OLD PERSIAN SIGN SSA", "Lo", 0, none),
  ("OLD PERSIAN SIGN HA", "Lo", 0, none),
  (),
  (),
  (),
  (),
  ("OLD PERSIAN SIGN AURAMAZDAA", "Lo", 0, none),
  ("OLD PERSIAN SIGN AURAMAZDAA-2", "Lo", 0, none),
  ("OLD PERSIAN SIGN AURAMAZDAAHA", "Lo", 0, none),
  ("OLD PERSIAN SIGN XSHAAYATHIYA", "Lo", 0, none),
  ("OLD PERSIAN SIGN DAHYAAUSH", "Lo", 0, none),
  ("OLD PERSIAN SIGN DAHYAAUSH-2", "Lo", 0, none),
  ("OLD PERSIAN SIGN BAGA", "Lo", 0, none),
  ("OLD PERSIAN SIGN BUUMISH", "Lo", 0, none),
  ("OLD PERSIAN WORD DIVIDER", "Po", 0, none),
  ("OLD PERSIAN NUMBER ONE", "Nl", 0, none),
  ("OLD PERSIAN NUMBER TWO", "Nl", 0, none),
  ("OLD PERSIAN NUMBER TEN", "Nl", 0, none),
  ("OLD PERSIAN NUMBER TWENTY", "Nl", 0, none),
  ("OLD PERSIAN NUMBER HUNDRED", "Nl", 0, none),
)
