#let data = (
  (),
  ("HEBREW ACCENT ETNAHTA", "Mn", 220, none),
  ("HEBREW ACCENT SEGOL", "Mn", 230, none),
  ("HEBREW ACCENT SHALSHELET", "Mn", 230, none),
  ("HEBREW ACCENT ZAQEF QATAN", "Mn", 230, none),
  ("HEBREW ACCENT ZAQEF GADOL", "Mn", 230, none),
  ("HEBREW ACCENT TIPEHA", "Mn", 220, none),
  ("HEBREW ACCENT REVIA", "Mn", 230, none),
  ("HEBREW ACCENT ZARQA", "Mn", 230, none),
  ("HEBREW ACCENT PASHTA", "Mn", 230, none),
  ("HEBREW ACCENT YETIV", "Mn", 222, none),
  ("HEBREW ACCENT TEVIR", "Mn", 220, none),
  ("HEBREW ACCENT GERESH", "Mn", 230, none),
  ("HEBREW ACCENT GERESH MUQDAM", "Mn", 230, none),
  ("HEBREW ACCENT GERSHAYIM", "Mn", 230, none),
  ("HEBREW ACCENT QARNEY PARA", "Mn", 230, none),
  ("HEBREW ACCENT TELISHA GEDOLA", "Mn", 230, none),
  ("HEBREW ACCENT PAZER", "Mn", 230, none),
  ("HEBREW ACCENT ATNAH HAFUKH", "Mn", 220, none),
  ("HEBREW ACCENT MUNAH", "Mn", 220, none),
  ("HEBREW ACCENT MAHAPAKH", "Mn", 220, none),
  ("HEBREW ACCENT MERKHA", "Mn", 220, none),
  ("HEBREW ACCENT MERKHA KEFULA", "Mn", 220, none),
  ("HEBREW ACCENT DARGA", "Mn", 220, none),
  ("HEBREW ACCENT QADMA", "Mn", 230, none),
  ("HEBREW ACCENT TELISHA QETANA", "Mn", 230, none),
  ("HEBREW ACCENT YERAH BEN YOMO", "Mn", 220, none),
  ("HEBREW ACCENT OLE", "Mn", 230, none),
  ("HEBREW ACCENT ILUY", "Mn", 230, none),
  ("HEBREW ACCENT DEHI", "Mn", 222, none),
  ("HEBREW ACCENT ZINOR", "Mn", 228, none),
  ("HEBREW MARK MASORA CIRCLE", "Mn", 230, none),
  ("HEBREW POINT SHEVA", "Mn", 10, none),
  ("HEBREW POINT HATAF SEGOL", "Mn", 11, none),
  ("HEBREW POINT HATAF PATAH", "Mn", 12, none),
  ("HEBREW POINT HATAF QAMATS", "Mn", 13, none),
  ("HEBREW POINT HIRIQ", "Mn", 14, none),
  ("HEBREW POINT TSERE", "Mn", 15, none),
  ("HEBREW POINT SEGOL", "Mn", 16, none),
  ("HEBREW POINT PATAH", "Mn", 17, none),
  ("HEBREW POINT QAMATS", "Mn", 18, none),
  ("HEBREW POINT HOLAM", "Mn", 19, none),
  ("HEBREW POINT HOLAM HASER FOR VAV", "Mn", 19, none),
  ("HEBREW POINT QUBUTS", "Mn", 20, none),
  ("HEBREW POINT DAGESH OR MAPIQ", "Mn", 21, none),
  ("HEBREW POINT METEG", "Mn", 22, none),
  ("HEBREW PUNCTUATION MAQAF", "Pd", 0, none),
  ("HEBREW POINT RAFE", "Mn", 23, none),
  ("HEBREW PUNCTUATION PASEQ", "Po", 0, none),
  ("HEBREW POINT SHIN DOT", "Mn", 24, none),
  ("HEBREW POINT SIN DOT", "Mn", 25, none),
  ("HEBREW PUNCTUATION SOF PASUQ", "Po", 0, none),
  ("HEBREW MARK UPPER DOT", "Mn", 230, none),
  ("HEBREW MARK LOWER DOT", "Mn", 220, none),
  ("HEBREW PUNCTUATION NUN HAFUKHA", "Po", 0, none),
  ("HEBREW POINT QAMATS QATAN", "Mn", 18, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("HEBREW LETTER ALEF", "Lo", 0, none),
  ("HEBREW LETTER BET", "Lo", 0, none),
  ("HEBREW LETTER GIMEL", "Lo", 0, none),
  ("HEBREW LETTER DALET", "Lo", 0, none),
  ("HEBREW LETTER HE", "Lo", 0, none),
  ("HEBREW LETTER VAV", "Lo", 0, none),
  ("HEBREW LETTER ZAYIN", "Lo", 0, none),
  ("HEBREW LETTER HET", "Lo", 0, none),
  ("HEBREW LETTER TET", "Lo", 0, none),
  ("HEBREW LETTER YOD", "Lo", 0, none),
  ("HEBREW LETTER FINAL KAF", "Lo", 0, none),
  ("HEBREW LETTER KAF", "Lo", 0, none),
  ("HEBREW LETTER LAMED", "Lo", 0, none),
  ("HEBREW LETTER FINAL MEM", "Lo", 0, none),
  ("HEBREW LETTER MEM", "Lo", 0, none),
  ("HEBREW LETTER FINAL NUN", "Lo", 0, none),
  ("HEBREW LETTER NUN", "Lo", 0, none),
  ("HEBREW LETTER SAMEKH", "Lo", 0, none),
  ("HEBREW LETTER AYIN", "Lo", 0, none),
  ("HEBREW LETTER FINAL PE", "Lo", 0, none),
  ("HEBREW LETTER PE", "Lo", 0, none),
  ("HEBREW LETTER FINAL TSADI", "Lo", 0, none),
  ("HEBREW LETTER TSADI", "Lo", 0, none),
  ("HEBREW LETTER QOF", "Lo", 0, none),
  ("HEBREW LETTER RESH", "Lo", 0, none),
  ("HEBREW LETTER SHIN", "Lo", 0, none),
  ("HEBREW LETTER TAV", "Lo", 0, none),
  (),
  (),
  (),
  (),
  ("HEBREW YOD TRIANGLE", "Lo", 0, none),
  ("HEBREW LIGATURE YIDDISH DOUBLE VAV", "Lo", 0, none),
  ("HEBREW LIGATURE YIDDISH VAV YOD", "Lo", 0, none),
  ("HEBREW LIGATURE YIDDISH DOUBLE YOD", "Lo", 0, none),
  ("HEBREW PUNCTUATION GERESH", "Po", 0, none),
  ("HEBREW PUNCTUATION GERSHAYIM", "Po", 0, none),
)
