#let data = (
  ("PHAGS-PA LETTER KA", "Lo", 0, none),
  ("PHAGS-PA LETTER KHA", "Lo", 0, none),
  ("PHAGS-PA LETTER GA", "Lo", 0, none),
  ("PHAGS-PA LETTER NGA", "Lo", 0, none),
  ("PHAGS-PA LETTER CA", "Lo", 0, none),
  ("PHAGS-PA LETTER CHA", "Lo", 0, none),
  ("PHAGS-PA LETTER JA", "Lo", 0, none),
  ("PHAGS-PA LETTER NYA", "Lo", 0, none),
  ("PHAGS-PA LETTER TA", "Lo", 0, none),
  ("PHAGS-PA LETTER THA", "Lo", 0, none),
  ("PHAGS-PA LETTER DA", "Lo", 0, none),
  ("PHAGS-PA LETTER NA", "Lo", 0, none),
  ("PHAGS-PA LETTER PA", "Lo", 0, none),
  ("PHAGS-PA LETTER PHA", "Lo", 0, none),
  ("PHAGS-PA LETTER BA", "Lo", 0, none),
  ("PHAGS-PA LETTER MA", "Lo", 0, none),
  ("PHAGS-PA LETTER TSA", "Lo", 0, none),
  ("PHAGS-PA LETTER TSHA", "Lo", 0, none),
  ("PHAGS-PA LETTER DZA", "Lo", 0, none),
  ("PHAGS-PA LETTER WA", "Lo", 0, none),
  ("PHAGS-PA LETTER ZHA", "Lo", 0, none),
  ("PHAGS-PA LETTER ZA", "Lo", 0, none),
  ("PHAGS-PA LETTER SMALL A", "Lo", 0, none),
  ("PHAGS-PA LETTER YA", "Lo", 0, none),
  ("PHAGS-PA LETTER RA", "Lo", 0, none),
  ("PHAGS-PA LETTER LA", "Lo", 0, none),
  ("PHAGS-PA LETTER SHA", "Lo", 0, none),
  ("PHAGS-PA LETTER SA", "Lo", 0, none),
  ("PHAGS-PA LETTER HA", "Lo", 0, none),
  ("PHAGS-PA LETTER A", "Lo", 0, none),
  ("PHAGS-PA LETTER I", "Lo", 0, none),
  ("PHAGS-PA LETTER U", "Lo", 0, none),
  ("PHAGS-PA LETTER E", "Lo", 0, none),
  ("PHAGS-PA LETTER O", "Lo", 0, none),
  ("PHAGS-PA LETTER QA", "Lo", 0, none),
  ("PHAGS-PA LETTER XA", "Lo", 0, none),
  ("PHAGS-PA LETTER FA", "Lo", 0, none),
  ("PHAGS-PA LETTER GGA", "Lo", 0, none),
  ("PHAGS-PA LETTER EE", "Lo", 0, none),
  ("PHAGS-PA SUBJOINED LETTER WA", "Lo", 0, none),
  ("PHAGS-PA SUBJOINED LETTER YA", "Lo", 0, none),
  ("PHAGS-PA LETTER TTA", "Lo", 0, none),
  ("PHAGS-PA LETTER TTHA", "Lo", 0, none),
  ("PHAGS-PA LETTER DDA", "Lo", 0, none),
  ("PHAGS-PA LETTER NNA", "Lo", 0, none),
  ("PHAGS-PA LETTER ALTERNATE YA", "Lo", 0, none),
  ("PHAGS-PA LETTER VOICELESS SHA", "Lo", 0, none),
  ("PHAGS-PA LETTER VOICED HA", "Lo", 0, none),
  ("PHAGS-PA LETTER ASPIRATED FA", "Lo", 0, none),
  ("PHAGS-PA SUBJOINED LETTER RA", "Lo", 0, none),
  ("PHAGS-PA SUPERFIXED LETTER RA", "Lo", 0, none),
  ("PHAGS-PA LETTER CANDRABINDU", "Lo", 0, none),
  ("PHAGS-PA SINGLE HEAD MARK", "Po", 0, none),
  ("PHAGS-PA DOUBLE HEAD MARK", "Po", 0, none),
  ("PHAGS-PA MARK SHAD", "Po", 0, none),
  ("PHAGS-PA MARK DOUBLE SHAD", "Po", 0, none),
)
