#let data = (
  ("SAURASHTRA SIGN ANUSVARA", "Mc", 0, none),
  ("SAURASHTRA SIGN VISARGA", "Mc", 0, none),
  ("SAURASHTRA LETTER A", "Lo", 0, none),
  ("SAURASHTRA LETTER AA", "Lo", 0, none),
  ("SAURASHTRA LETTER I", "Lo", 0, none),
  ("SAURASHTRA LETTER II", "Lo", 0, none),
  ("SAURASHTRA LETTER U", "Lo", 0, none),
  ("SAURASHTRA LETTER UU", "Lo", 0, none),
  ("SAURASHTRA LETTER VOCALIC R", "Lo", 0, none),
  ("SAURASHTRA LETTER VOCALIC RR", "Lo", 0, none),
  ("SAURASHTRA LETTER VOCALIC L", "Lo", 0, none),
  ("SAURASHTRA LETTER VOCALIC LL", "Lo", 0, none),
  ("SAURASHTRA LETTER E", "Lo", 0, none),
  ("SAURASHTRA LETTER EE", "Lo", 0, none),
  ("SAURASHTRA LETTER AI", "Lo", 0, none),
  ("SAURASHTRA LETTER O", "Lo", 0, none),
  ("SAURASHTRA LETTER OO", "Lo", 0, none),
  ("SAURASHTRA LETTER AU", "Lo", 0, none),
  ("SAURASHTRA LETTER KA", "Lo", 0, none),
  ("SAURASHTRA LETTER KHA", "Lo", 0, none),
  ("SAURASHTRA LETTER GA", "Lo", 0, none),
  ("SAURASHTRA LETTER GHA", "Lo", 0, none),
  ("SAURASHTRA LETTER NGA", "Lo", 0, none),
  ("SAURASHTRA LETTER CA", "Lo", 0, none),
  ("SAURASHTRA LETTER CHA", "Lo", 0, none),
  ("SAURASHTRA LETTER JA", "Lo", 0, none),
  ("SAURASHTRA LETTER JHA", "Lo", 0, none),
  ("SAURASHTRA LETTER NYA", "Lo", 0, none),
  ("SAURASHTRA LETTER TTA", "Lo", 0, none),
  ("SAURASHTRA LETTER TTHA", "Lo", 0, none),
  ("SAURASHTRA LETTER DDA", "Lo", 0, none),
  ("SAURASHTRA LETTER DDHA", "Lo", 0, none),
  ("SAURASHTRA LETTER NNA", "Lo", 0, none),
  ("SAURASHTRA LETTER TA", "Lo", 0, none),
  ("SAURASHTRA LETTER THA", "Lo", 0, none),
  ("SAURASHTRA LETTER DA", "Lo", 0, none),
  ("SAURASHTRA LETTER DHA", "Lo", 0, none),
  ("SAURASHTRA LETTER NA", "Lo", 0, none),
  ("SAURASHTRA LETTER PA", "Lo", 0, none),
  ("SAURASHTRA LETTER PHA", "Lo", 0, none),
  ("SAURASHTRA LETTER BA", "Lo", 0, none),
  ("SAURASHTRA LETTER BHA", "Lo", 0, none),
  ("SAURASHTRA LETTER MA", "Lo", 0, none),
  ("SAURASHTRA LETTER YA", "Lo", 0, none),
  ("SAURASHTRA LETTER RA", "Lo", 0, none),
  ("SAURASHTRA LETTER LA", "Lo", 0, none),
  ("SAURASHTRA LETTER VA", "Lo", 0, none),
  ("SAURASHTRA LETTER SHA", "Lo", 0, none),
  ("SAURASHTRA LETTER SSA", "Lo", 0, none),
  ("SAURASHTRA LETTER SA", "Lo", 0, none),
  ("SAURASHTRA LETTER HA", "Lo", 0, none),
  ("SAURASHTRA LETTER LLA", "Lo", 0, none),
  ("SAURASHTRA CONSONANT SIGN HAARU", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN AA", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN I", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN II", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN U", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN UU", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN VOCALIC R", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN VOCALIC RR", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN VOCALIC L", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN VOCALIC LL", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN E", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN EE", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN AI", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN O", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN OO", "Mc", 0, none),
  ("SAURASHTRA VOWEL SIGN AU", "Mc", 0, none),
  ("SAURASHTRA SIGN VIRAMA", "Mn", 9, none),
  ("SAURASHTRA SIGN CANDRABINDU", "Mn", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("SAURASHTRA DANDA", "Po", 0, none),
  ("SAURASHTRA DOUBLE DANDA", "Po", 0, none),
  ("SAURASHTRA DIGIT ZERO", "Nd", 0, none),
  ("SAURASHTRA DIGIT ONE", "Nd", 0, none),
  ("SAURASHTRA DIGIT TWO", "Nd", 0, none),
  ("SAURASHTRA DIGIT THREE", "Nd", 0, none),
  ("SAURASHTRA DIGIT FOUR", "Nd", 0, none),
  ("SAURASHTRA DIGIT FIVE", "Nd", 0, none),
  ("SAURASHTRA DIGIT SIX", "Nd", 0, none),
  ("SAURASHTRA DIGIT SEVEN", "Nd", 0, none),
  ("SAURASHTRA DIGIT EIGHT", "Nd", 0, none),
  ("SAURASHTRA DIGIT NINE", "Nd", 0, none),
)
