#let data = (
  (),
  ("THAI CHARACTER KO KAI", "Lo", 0, none),
  ("THAI CHARACTER KHO KHAI", "Lo", 0, none),
  ("THAI CHARACTER KHO KHUAT", "Lo", 0, none),
  ("THAI CHARACTER KHO KHWAI", "Lo", 0, none),
  ("THAI CHARACTER KHO KHON", "Lo", 0, none),
  ("THAI CHARACTER KHO RAKHANG", "Lo", 0, none),
  ("THAI CHARACTER NGO NGU", "Lo", 0, none),
  ("THAI CHARACTER CHO CHAN", "Lo", 0, none),
  ("THAI CHARACTER CHO CHING", "Lo", 0, none),
  ("THAI CHARACTER CHO CHANG", "Lo", 0, none),
  ("THAI CHARACTER SO SO", "Lo", 0, none),
  ("THAI CHARACTER CHO CHOE", "Lo", 0, none),
  ("THAI CHARACTER YO YING", "Lo", 0, none),
  ("THAI CHARACTER DO CHADA", "Lo", 0, none),
  ("THAI CHARACTER TO PATAK", "Lo", 0, none),
  ("THAI CHARACTER THO THAN", "Lo", 0, none),
  ("THAI CHARACTER THO NANGMONTHO", "Lo", 0, none),
  ("THAI CHARACTER THO PHUTHAO", "Lo", 0, none),
  ("THAI CHARACTER NO NEN", "Lo", 0, none),
  ("THAI CHARACTER DO DEK", "Lo", 0, none),
  ("THAI CHARACTER TO TAO", "Lo", 0, none),
  ("THAI CHARACTER THO THUNG", "Lo", 0, none),
  ("THAI CHARACTER THO THAHAN", "Lo", 0, none),
  ("THAI CHARACTER THO THONG", "Lo", 0, none),
  ("THAI CHARACTER NO NU", "Lo", 0, none),
  ("THAI CHARACTER BO BAIMAI", "Lo", 0, none),
  ("THAI CHARACTER PO PLA", "Lo", 0, none),
  ("THAI CHARACTER PHO PHUNG", "Lo", 0, none),
  ("THAI CHARACTER FO FA", "Lo", 0, none),
  ("THAI CHARACTER PHO PHAN", "Lo", 0, none),
  ("THAI CHARACTER FO FAN", "Lo", 0, none),
  ("THAI CHARACTER PHO SAMPHAO", "Lo", 0, none),
  ("THAI CHARACTER MO MA", "Lo", 0, none),
  ("THAI CHARACTER YO YAK", "Lo", 0, none),
  ("THAI CHARACTER RO RUA", "Lo", 0, none),
  ("THAI CHARACTER RU", "Lo", 0, none),
  ("THAI CHARACTER LO LING", "Lo", 0, none),
  ("THAI CHARACTER LU", "Lo", 0, none),
  ("THAI CHARACTER WO WAEN", "Lo", 0, none),
  ("THAI CHARACTER SO SALA", "Lo", 0, none),
  ("THAI CHARACTER SO RUSI", "Lo", 0, none),
  ("THAI CHARACTER SO SUA", "Lo", 0, none),
  ("THAI CHARACTER HO HIP", "Lo", 0, none),
  ("THAI CHARACTER LO CHULA", "Lo", 0, none),
  ("THAI CHARACTER O ANG", "Lo", 0, none),
  ("THAI CHARACTER HO NOKHUK", "Lo", 0, none),
  ("THAI CHARACTER PAIYANNOI", "Lo", 0, none),
  ("THAI CHARACTER SARA A", "Lo", 0, none),
  ("THAI CHARACTER MAI HAN-AKAT", "Mn", 0, none),
  ("THAI CHARACTER SARA AA", "Lo", 0, none),
  ("THAI CHARACTER SARA AM", "Lo", 0, none),
  ("THAI CHARACTER SARA I", "Mn", 0, none),
  ("THAI CHARACTER SARA II", "Mn", 0, none),
  ("THAI CHARACTER SARA UE", "Mn", 0, none),
  ("THAI CHARACTER SARA UEE", "Mn", 0, none),
  ("THAI CHARACTER SARA U", "Mn", 103, none),
  ("THAI CHARACTER SARA UU", "Mn", 103, none),
  ("THAI CHARACTER PHINTHU", "Mn", 9, none),
  (),
  (),
  (),
  (),
  ("THAI CURRENCY SYMBOL BAHT", "Sc", 0, none),
  ("THAI CHARACTER SARA E", "Lo", 0, none),
  ("THAI CHARACTER SARA AE", "Lo", 0, none),
  ("THAI CHARACTER SARA O", "Lo", 0, none),
  ("THAI CHARACTER SARA AI MAIMUAN", "Lo", 0, none),
  ("THAI CHARACTER SARA AI MAIMALAI", "Lo", 0, none),
  ("THAI CHARACTER LAKKHANGYAO", "Lo", 0, none),
  ("THAI CHARACTER MAIYAMOK", "Lm", 0, none),
  ("THAI CHARACTER MAITAIKHU", "Mn", 0, none),
  ("THAI CHARACTER MAI EK", "Mn", 107, none),
  ("THAI CHARACTER MAI THO", "Mn", 107, none),
  ("THAI CHARACTER MAI TRI", "Mn", 107, none),
  ("THAI CHARACTER MAI CHATTAWA", "Mn", 107, none),
  ("THAI CHARACTER THANTHAKHAT", "Mn", 0, none),
  ("THAI CHARACTER NIKHAHIT", "Mn", 0, none),
  ("THAI CHARACTER YAMAKKAN", "Mn", 0, none),
  ("THAI CHARACTER FONGMAN", "Po", 0, none),
  ("THAI DIGIT ZERO", "Nd", 0, none),
  ("THAI DIGIT ONE", "Nd", 0, none),
  ("THAI DIGIT TWO", "Nd", 0, none),
  ("THAI DIGIT THREE", "Nd", 0, none),
  ("THAI DIGIT FOUR", "Nd", 0, none),
  ("THAI DIGIT FIVE", "Nd", 0, none),
  ("THAI DIGIT SIX", "Nd", 0, none),
  ("THAI DIGIT SEVEN", "Nd", 0, none),
  ("THAI DIGIT EIGHT", "Nd", 0, none),
  ("THAI DIGIT NINE", "Nd", 0, none),
  ("THAI CHARACTER ANGKHANKHU", "Po", 0, none),
  ("THAI CHARACTER KHOMUT", "Po", 0, none),
)
