#let data = (
  ("TOLONG SIKI LETTER I", "Lo", 0, none),
  ("TOLONG SIKI LETTER E", "Lo", 0, none),
  ("TOLONG SIKI LETTER U", "Lo", 0, none),
  ("TOLONG SIKI LETTER O", "Lo", 0, none),
  ("TOLONG SIKI LETTER A", "Lo", 0, none),
  ("TOLONG SIKI LETTER AA", "Lo", 0, none),
  ("TOLONG SIKI LETTER P", "Lo", 0, none),
  ("TOLONG SIKI LETTER PH", "Lo", 0, none),
  ("TOLONG SIKI LETTER B", "Lo", 0, none),
  ("TOLONG SIKI LETTER BH", "Lo", 0, none),
  ("TOLONG SIKI LETTER M", "Lo", 0, none),
  ("TOLONG SIKI LETTER T", "Lo", 0, none),
  ("TOLONG SIKI LETTER TH", "Lo", 0, none),
  ("TOLONG SIKI LETTER D", "Lo", 0, none),
  ("TOLONG SIKI LETTER DH", "Lo", 0, none),
  ("TOLONG SIKI LETTER N", "Lo", 0, none),
  ("TOLONG SIKI LETTER TT", "Lo", 0, none),
  ("TOLONG SIKI LETTER TTH", "Lo", 0, none),
  ("TOLONG SIKI LETTER DD", "Lo", 0, none),
  ("TOLONG SIKI LETTER DDH", "Lo", 0, none),
  ("TOLONG SIKI LETTER NN", "Lo", 0, none),
  ("TOLONG SIKI LETTER C", "Lo", 0, none),
  ("TOLONG SIKI LETTER CH", "Lo", 0, none),
  ("TOLONG SIKI LETTER J", "Lo", 0, none),
  ("TOLONG SIKI LETTER JH", "Lo", 0, none),
  ("TOLONG SIKI LETTER NY", "Lo", 0, none),
  ("TOLONG SIKI LETTER K", "Lo", 0, none),
  ("TOLONG SIKI LETTER KH", "Lo", 0, none),
  ("TOLONG SIKI LETTER G", "Lo", 0, none),
  ("TOLONG SIKI LETTER GH", "Lo", 0, none),
  ("TOLONG SIKI LETTER NG", "Lo", 0, none),
  ("TOLONG SIKI LETTER Y", "Lo", 0, none),
  ("TOLONG SIKI LETTER R", "Lo", 0, none),
  ("TOLONG SIKI LETTER L", "Lo", 0, none),
  ("TOLONG SIKI LETTER V", "Lo", 0, none),
  ("TOLONG SIKI LETTER NNY", "Lo", 0, none),
  ("TOLONG SIKI LETTER S", "Lo", 0, none),
  ("TOLONG SIKI LETTER H", "Lo", 0, none),
  ("TOLONG SIKI LETTER X", "Lo", 0, none),
  ("TOLONG SIKI LETTER RR", "Lo", 0, none),
  ("TOLONG SIKI LETTER RRH", "Lo", 0, none),
  ("TOLONG SIKI SIGN SELA", "Lm", 0, none),
  ("TOLONG SIKI SIGN HECAKA", "Lo", 0, none),
  ("TOLONG SIKI UNGGA", "Lo", 0, none),
  (),
  (),
  (),
  (),
  ("TOLONG SIKI DIGIT ZERO", "Nd", 0, none),
  ("TOLONG SIKI DIGIT ONE", "Nd", 0, none),
  ("TOLONG SIKI DIGIT TWO", "Nd", 0, none),
  ("TOLONG SIKI DIGIT THREE", "Nd", 0, none),
  ("TOLONG SIKI DIGIT FOUR", "Nd", 0, none),
  ("TOLONG SIKI DIGIT FIVE", "Nd", 0, none),
  ("TOLONG SIKI DIGIT SIX", "Nd", 0, none),
  ("TOLONG SIKI DIGIT SEVEN", "Nd", 0, none),
  ("TOLONG SIKI DIGIT EIGHT", "Nd", 0, none),
  ("TOLONG SIKI DIGIT NINE", "Nd", 0, none),
)
