#set page(width: auto, height: auto, margin: 5mm)

#let layers = (
  (
    type: "input",
    height: 8,
    depth: 8,
    label: "input",
    channels: (3, 224),
  ),
  (
    type: "conv",
    widths: (0.3, 0.3),
    height: 8,
    depth: 8,
    label: "conv1",
    channels: (64, 64, 224),
  ),
  (
    type: "pool",
    height: 6,
    depth: 6,
    label: "pool1",
  ),
  (
    type: "convres",
    widths: (0.4,0.4,),
    height: 6,
    depth: 6,
    label: "res2",
    channels: (128, 128, 112),
  ),
  (
    type: "pool",
    height: 4,
    depth: 4,
    label: "pool2",
  ),
  (
    type: "convres",
    widths: (0.5, 0.5, 0.5),
    height: 4,
    depth: 4,
    label: "res3",
    channels: (256, 256, 256, 56),
  ),
  (
    type: "pool",
    height: 2,
    depth: 2,
    label: "pool3",
  ),
  (
    type: "convres",
    widths: (0.6, 0.6, 0.6),
    height: 2,
    depth: 2,
    label: "res4",
    channels: (512, 512, 512, 28),
    offset: 1,
  ),
  (
    type: "pool",
    height: 1,
    depth: 1,
    label: "pool4",
  ),
  (
    type: "convres",
    widths: (0.6, 0.8, 0.8),
    height: 1,
    depth: 1,
    label: "res5",
    channels: (512, 512, 512, 14),
    offset: 0.8,
  ),
  (
    type: "pool",
    height: 0.5,
    depth: 0.5,
    label: "pool4",
  ),
  (
    type: "fc",
    label: "fc",
    channels: (4096,),
    height: 5,
    depth: 0.3,
    offset: 0.8,
  ),
  (
    type: "fc",
    label: "fc",
    channels: (4096,),
    height: 5,
    depth: 0.3,
    offset: 0.5,
  ),
  (
    type: "fc",
    label: "fc",
    channels: (1000,),
    height: 4,
    depth: 0.3,
    offset: 0.5,
  ),
  (
    type: "softmax",
    label: "softmax",
    height: 4,
    depth: 0.3,
    offset: 0.9,
  ),
)

#draw-network(
  layers,
  show-relu: true,
)