// https://support.apple.com/en-hk/guide/mac-help/cpmh0011/mac
#let mac-key = (
  command: "⌘",
  shift: "⇧",
  option: "⌥",
  control: "⌃",
  "return": "↩",
  delete: "⌫",
  forward-delete: "⌦",
  escape: "⎋",
  left: "←",
  right: "→",
  up: "↑",
  down: "↓",
  pageup: "⇞",
  pagedown: "⇟",
  home: "↖",
  end: "↘",
  tab-right: "⇥",
  tab-left: "⇤",
)

#let com-key = (
  control: "Ctrl",
  shift: "Shift",
  alt: "Alt",
  "return": "Enter",
  delete: "Del",
  escape: "Esc",
  left: "←",
  right: "→",
  up: "↑",
  down: "↓",
  pageup: "PgUp",
  pagedown: "PgDn",
  home: "Home",
  end: "End",
  tab: "Tab",
)