
#let tuhi-palette = (
  // Neutral tones (for text and backgrounds)
  neutral-darkest: rgb(29, 27, 28),      // Deep gray (Set)
  neutral-darker: rgb(40, 40, 40),       // Dark gray (Contrast for dark text)
  neutral-dark: rgb(80, 80, 80),         // Mid-dark gray (Used for text or borders)
  neutral: rgb(100, 100, 100),           // Neutral gray (Set)
  neutral-light: rgb(230, 230, 230),     // Light gray (For backgrounds and subtle text)
  neutral-lighter: rgb(245, 245, 245),   // Very light gray (Light background)
  neutral-lightest: rgb(255, 255, 255),  // White (Set, for background or text on dark background)

  // Primary tones (for main brand and highlights)
  primary-darkest: rgb(0, 70, 0),         // Very dark green (For main accents or strong emphasis)
  primary-darker: rgb(0, 91, 0),          // Dark green (For headers, strong sections)
  primary-dark: rgb(0, 112, 0),           // Slightly lighter dark green (For subheadings or key elements)
  primary: rgb(113, 135, 121),            // Medium green (Primary tone for text or background elements)
  primary-light: rgb(135, 160, 141),      // Light green (Slightly lighter to distinguish it from primary)
  primary-lighter: rgb(205, 229, 204),    // Pastel green (For highlights, light backgrounds)
  primary-lightest: rgb(225, 240, 220),   // Very light green (For background fills or subtle highlights)

  // Secondary tones (for calls-to-action or secondary elements)
  secondary-darkest: rgb(94, 0, 32),      // Very dark magenta (For strong emphasis or headings)
  secondary-darker: rgb(146, 4, 61),      // Dark magenta (For key elements or bold accents)
  secondary-dark: rgb(173, 7, 85),        // Bold magenta (Primary secondary tone, unchanged)
  secondary: rgb(204, 16, 102),           // Medium magenta (For text, highlights, or buttons)
  secondary-light: rgb(248, 77, 154),     // Slightly brighter magenta (For softer accents, borders)
  secondary-lighter: rgb(255, 179, 211),  // Pale pink (For very soft background accents)
  secondary-lightest: rgb(250, 240, 245), // Very light pink (Almost a neutral background)

  // Tertiary tones (For tertiary elements or further contrast)
  tertiary-darkest: rgb(205, 92, 0),       // Dark orange (Deep tone for strong contrast)
  tertiary-darker: rgb(255, 122, 0),        // Medium orange (Stronger accent)
  tertiary-dark: rgb(255, 145, 0),          // Standard orange (Main tertiary color)
  tertiary: rgb(255, 178, 77),              // Light orange (Complementary, softer accent)
  tertiary-light: rgb(255, 212, 140),       // Adjusted light orange (For smoother transition between shades)
  tertiary-lighter: rgb(255, 229, 186),     // Pale orange (Used for light background elements)
  tertiary-lightest: rgb(255, 240, 215),    // Lightest orange (Almost a cream tone, for subtle fills)
)
