[package]
name = "coquille-st-jacques"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Damien Metzler <dmetzler@gmail.com>"]
license = "Apache-2.0"
description = "Illustrated course handout for French school teachers of St Jacque Hazebrouck Institution."
repository = "https://github.com/dmetzler/un-cours-avec-l-ia"
keywords = ["lesson", "revision", "callout", "education", "mcq"]
categories = ["report"]
disciplines = ["education"]
exclude = ["tests"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
