[package]
name = "molchemist"
version = "0.1.2"
entrypoint = "lib.typ"
authors = ["Eito Yoneyama"]
license = "MIT"
description = "Render chemical structures from Molfile, SDF, and SMILES data."
compiler = "0.13.1"
repository = "https://github.com/rice8y/molchemist"
keywords = ["chemistry", "molecule", "sdf", "molfile", "cetz", "wasm", "science", "alchemist"]
exclude = ["/images"]