//============================================================================================//
//                                          Imports                                           //
//============================================================================================//

#import "./books.typ": iboo


//============================================================================================//
//                                   blindex Languages File                                   //
//============================================================================================//

// Declaration and structuring of the {ldict} language dictionary
#let ldict = (:)

// Populate ldict with book keys
#for K in iboo.keys() { ldict.insert(K, (:)) }


//--------------------------------------------------------------------------------------------//
//                         Default, 3-char English, "en-3", language                          //
//--------------------------------------------------------------------------------------------//

#{
  let lang = "en-3"
  ldict.at("1001").insert(lang, ("Gen", "Genesis"))
  ldict.at("1002").insert(lang, ("Exo", "Exodus"))
  ldict.at("1003").insert(lang, ("Lev", "Leviticus"))
  ldict.at("1004").insert(lang, ("Num", "Numbers"))
  ldict.at("1005").insert(lang, ("Det", "Deuteronomy"))
  ldict.at("1101").insert(lang, ("Jos", "Joshua"))
  ldict.at("1102").insert(lang, ("Jdg", "Judges"))
  ldict.at("1103").insert(lang, ("Rth", "Ruth"))
  ldict.at("1104").insert(lang, ("1Sm", "1 Samuel"))
  ldict.at("1105").insert(lang, ("2Sm", "2 Samuel"))
  ldict.at("1106").insert(lang, ("1Ki", "1 Kings"))
  ldict.at("1107").insert(lang, ("2Ki", "2 Kings"))
  ldict.at("1108").insert(lang, ("1Ch", "1 Chronicles"))
  ldict.at("1109").insert(lang, ("2Ch", "2 Chronicles"))
  ldict.at("1110").insert(lang, ("Ezr", "Ezra"))
  ldict.at("1111").insert(lang, ("Neh", "Nehemiah"))
  ldict.at("1112").insert(lang, ("Est", "Esther"))
  ldict.at("1201").insert(lang, ("Job", "Job"))
  ldict.at("1202").insert(lang, ("Psa", "Psalms"))
  ldict.at("1203").insert(lang, ("Pro", "Proverbs"))
  ldict.at("1204").insert(lang, ("Ecc", "Ecclesiastes"))
  ldict.at("1205").insert(lang, ("SOS", "Song of Solomon"))
  ldict.at("1301").insert(lang, ("Isa", "Isaiah"))
  ldict.at("1302").insert(lang, ("Jer", "Jeremiah"))
  ldict.at("1303").insert(lang, ("Lam", "Lamentations"))
  ldict.at("1304").insert(lang, ("Eze", "Ezekiel"))
  ldict.at("1305").insert(lang, ("Dan", "Daniel"))
  ldict.at("1306").insert(lang, ("Hos", "Hosea"))
  ldict.at("1307").insert(lang, ("Jol", "Joel"))
  ldict.at("1308").insert(lang, ("Ams", "Amos"))
  ldict.at("1309").insert(lang, ("Oba", "Obadiah"))
  ldict.at("1310").insert(lang, ("Jon", "Jonah"))
  ldict.at("1311").insert(lang, ("Mic", "Micah"))
  ldict.at("1312").insert(lang, ("Nah", "Nahum"))
  ldict.at("1313").insert(lang, ("Hab", "Habakkuk"))
  ldict.at("1314").insert(lang, ("Zep", "Zephaniah"))
  ldict.at("1315").insert(lang, ("Hag", "Haggai"))
  ldict.at("1316").insert(lang, ("Zec", "Zechariah"))
  ldict.at("1317").insert(lang, ("Mal", "Malachi"))
  ldict.at("1401").insert(lang, ("Mat", "Matthew"))
  ldict.at("1402").insert(lang, ("Mrk", "Mark"))
  ldict.at("1403").insert(lang, ("Luk", "Luke"))
  ldict.at("1404").insert(lang, ("Jhn", "John"))
  ldict.at("1501").insert(lang, ("Act", "Acts"))
  ldict.at("1601").insert(lang, ("Rom", "Romans"))
  ldict.at("1602").insert(lang, ("1Co", "1 Corinthians"))
  ldict.at("1603").insert(lang, ("2Co", "2 Corinthians"))
  ldict.at("1604").insert(lang, ("Gal", "Galatians"))
  ldict.at("1605").insert(lang, ("Eph", "Ephesians"))
  ldict.at("1606").insert(lang, ("Php", "Philippians"))
  ldict.at("1607").insert(lang, ("Col", "Colossians"))
  ldict.at("1608").insert(lang, ("1Th", "1 Thessalonians"))
  ldict.at("1609").insert(lang, ("2Th", "2 Thessalonians"))
  ldict.at("1610").insert(lang, ("1Ti", "1 Timothy"))
  ldict.at("1611").insert(lang, ("2Ti", "2 Timothy"))
  ldict.at("1612").insert(lang, ("Tit", "Titus"))
  ldict.at("1613").insert(lang, ("Phm", "Philemon"))
  ldict.at("1700").insert(lang, ("Heb", "Hebrews"))
  ldict.at("1701").insert(lang, ("Jas", "James"))
  ldict.at("1702").insert(lang, ("1Pe", "1 Peter"))
  ldict.at("1703").insert(lang, ("2Pe", "2 Peter"))
  ldict.at("1704").insert(lang, ("1Jn", "1 John"))
  ldict.at("1705").insert(lang, ("2Jn", "2 John"))
  ldict.at("1706").insert(lang, ("3Jn", "3 John"))
  ldict.at("1707").insert(lang, ("Jud", "Jude"))
  ldict.at("1801").insert(lang, ("Rev", "Revelation"))
  ldict.at("3101").insert(lang, ("1Es", "1 Esdras"))
  ldict.at("3102").insert(lang, ("Jdt", "Judith"))
  ldict.at("3103").insert(lang, ("Tob", "Tobit"))
  ldict.at("3104").insert(lang, ("1Ma", "1 Maccabees"))
  ldict.at("3105").insert(lang, ("2Ma", "2 Maccabees"))
  ldict.at("3106").insert(lang, ("3Ma", "3 Maccabees"))
  ldict.at("3107").insert(lang, ("4Ma", "4 Maccabees"))
  ldict.at("3108").insert(lang, ("AEs", "Additions to Esther"))
  ldict.at("3201").insert(lang, ("APs", "Additional Psalm"))
  ldict.at("3202").insert(lang, ("Ode", "Ode"))
  ldict.at("3203").insert(lang, ("Wis", "Wisdom of Solomon"))
  ldict.at("3204").insert(lang, ("Sir", "Sirach"))
  ldict.at("3205").insert(lang, ("PsS", "Psalms of Solomon"))
  ldict.at("3206").insert(lang, ("Bar", "Baruch"))
  ldict.at("3207").insert(lang, ("LJe", "Letter of Jeremiah"))
  ldict.at("3208").insert(lang, ("Sus", "Susanna"))
  ldict.at("3209").insert(lang, ("Bel", "Bel and the Dragon"))
  ldict.at("3210").insert(lang, ("Sg3", "Song of Three Youths"))
  ldict.at("5101").insert(lang, ("3Es", "3 Esdras"))
  ldict.at("5102").insert(lang, ("4Es", "4 Esdras"))
  ldict.at("5103").insert(lang, ("PMa", "Prayer of Manasseh"))
}


//--------------------------------------------------------------------------------------------//
//                         English, Logos bible, "en-logos", language                         //
//--------------------------------------------------------------------------------------------//

#{
  let lang = "en-logos"
  ldict.at("1001").insert(lang, ("Gen",       "Genesis"))
  ldict.at("1002").insert(lang, ("Ex",        "Exodus"))
  ldict.at("1003").insert(lang, ("Lev",       "Leviticus"))
  ldict.at("1004").insert(lang, ("Num",       "Numbers"))
  ldict.at("1005").insert(lang, ("Deut",      "Deuteronomy"))
  ldict.at("1101").insert(lang, ("Josh",      "Joshua"))
  ldict.at("1102").insert(lang, ("Judg",      "Judges"))
  ldict.at("1103").insert(lang, ("Ruth",      "Ruth"))
  ldict.at("1104").insert(lang, ("1Sam",      "1 Samuel"))
  ldict.at("1105").insert(lang, ("2Sam",      "2 Samuel"))
  ldict.at("1106").insert(lang, ("1Kings",    "1 Kings"))
  ldict.at("1107").insert(lang, ("2Kings",    "2 Kings"))
  ldict.at("1108").insert(lang, ("1Chron",    "1 Chronicles"))
  ldict.at("1109").insert(lang, ("2Chron",    "2 Chronicles"))
  ldict.at("1110").insert(lang, ("Ezra",      "Ezra"))
  ldict.at("1111").insert(lang, ("Neh",       "Nehemiah"))
  ldict.at("1112").insert(lang, ("Est",       "Esther"))
  ldict.at("1201").insert(lang, ("Job",       "Job"))
  ldict.at("1202").insert(lang, ("Ps",        "Psalms"))
  ldict.at("1203").insert(lang, ("Prov",      "Proverbs"))
  ldict.at("1204").insert(lang, ("Eccles",    "Ecclesiastes"))
  ldict.at("1205").insert(lang, ("Song",      "Song of Solomon"))
  ldict.at("1301").insert(lang, ("Isa",       "Isaiah"))
  ldict.at("1302").insert(lang, ("Jer",       "Jeremiah"))
  ldict.at("1303").insert(lang, ("Lam",       "Lamentations"))
  ldict.at("1304").insert(lang, ("Ezek",      "Ezekiel"))
  ldict.at("1305").insert(lang, ("Dan",       "Daniel"))
  ldict.at("1306").insert(lang, ("Hos",       "Hosea"))
  ldict.at("1307").insert(lang, ("Joel",      "Joel"))
  ldict.at("1308").insert(lang, ("Amos",      "Amos"))
  ldict.at("1309").insert(lang, ("Obad",      "Obadiah"))
  ldict.at("1310").insert(lang, ("Jonah",     "Jonah"))
  ldict.at("1311").insert(lang, ("Mic",       "Micah"))
  ldict.at("1312").insert(lang, ("Nah",       "Nahum"))
  ldict.at("1313").insert(lang, ("Hab",       "Habakkuk"))
  ldict.at("1314").insert(lang, ("Zeph",      "Zephaniah"))
  ldict.at("1315").insert(lang, ("Hag",       "Haggai"))
  ldict.at("1316").insert(lang, ("Zech",      "Zechariah"))
  ldict.at("1317").insert(lang, ("Mal",       "Malachi"))
  ldict.at("1401").insert(lang, ("Matt",      "Matthew"))
  ldict.at("1402").insert(lang, ("Mark",      "Mark"))
  ldict.at("1403").insert(lang, ("Luke",      "Luke"))
  ldict.at("1404").insert(lang, ("John",      "John"))
  ldict.at("1501").insert(lang, ("Acts",      "Acts"))
  ldict.at("1601").insert(lang, ("Rom",       "Romans"))
  ldict.at("1602").insert(lang, ("1Cor",      "1 Corinthians"))
  ldict.at("1603").insert(lang, ("2Cor",      "2 Corinthians"))
  ldict.at("1604").insert(lang, ("Gal",       "Galatians"))
  ldict.at("1605").insert(lang, ("Eph",       "Ephesians"))
  ldict.at("1606").insert(lang, ("Phil",      "Philippians"))
  ldict.at("1607").insert(lang, ("Col",       "Colossians"))
  ldict.at("1608").insert(lang, ("1Thess",    "1 Thessalonians"))
  ldict.at("1609").insert(lang, ("2Thess",    "2 Thessalonians"))
  ldict.at("1610").insert(lang, ("1Tim",      "1 Timothy"))
  ldict.at("1611").insert(lang, ("2Tim",      "2 Timothy"))
  ldict.at("1612").insert(lang, ("Titus",     "Titus"))
  ldict.at("1613").insert(lang, ("Philem",    "Philemon"))
  ldict.at("1700").insert(lang, ("Heb",       "Hebrews"))
  ldict.at("1701").insert(lang, ("James",     "James"))
  ldict.at("1702").insert(lang, ("1Pet",      "1 Peter"))
  ldict.at("1703").insert(lang, ("2Pet",      "2 Peter"))
  ldict.at("1704").insert(lang, ("1John",     "1 John"))
  ldict.at("1705").insert(lang, ("2John",     "2 John"))
  ldict.at("1706").insert(lang, ("3John",     "3 John"))
  ldict.at("1707").insert(lang, ("Jude",      "Jude"))
  ldict.at("1801").insert(lang, ("Rev",       "Revelation"))
  ldict.at("3101").insert(lang, ("1Esd",      "1 Esdras"))
  ldict.at("3102").insert(lang, ("Jth",       "Judith"))
  ldict.at("3103").insert(lang, ("Tob",       "Tobit"))
  ldict.at("3104").insert(lang, ("1Macc",     "1 Maccabees"))
  ldict.at("3105").insert(lang, ("2Macc",     "2 Maccabees"))
  ldict.at("3106").insert(lang, ("3Macc",     "3 Maccabees"))
  ldict.at("3107").insert(lang, ("4Macc",     "4 Maccabees"))
  ldict.at("3108").insert(lang, ("AddEsth",   "Additions to Esther"))
  ldict.at("3201").insert(lang, ("AddPsalm",  "Additional Psalm"))
  ldict.at("3202").insert(lang, ("Ode",       "Ode"))
  ldict.at("3203").insert(lang, ("WisdOfSol", "Wisdom of Solomon"))
  ldict.at("3204").insert(lang, ("Sir",       "Sirach"))
  ldict.at("3205").insert(lang, ("PsSolomon", "Psalms of Solomon"))
  ldict.at("3206").insert(lang, ("Bar",       "Baruch"))
  ldict.at("3207").insert(lang, ("EpJer",     "Letter of Jeremiah"))
  ldict.at("3208").insert(lang, ("Sus",       "Susanna"))
  ldict.at("3209").insert(lang, ("BelAndDr",  "Bel and the Dragon"))
  ldict.at("3210").insert(lang, ("SgOf3",     "Song of Three Youths"))
  ldict.at("5101").insert(lang, ("3Esd",      "3 Esdras"))
  ldict.at("5102").insert(lang, ("4Esd",      "4 Esdras"))
  ldict.at("5103").insert(lang, ("PrOfMan",   "Prayer of Manasseh"))
}


//--------------------------------------------------------------------------------------------//
//                    Brazilian Portuguese, Protestant, "br-pro", language                    //
//--------------------------------------------------------------------------------------------//

#{
  let lang = "br-pro"
  ldict.at("1001").insert(lang, ("Gn",  "Gênesis"))
  ldict.at("1002").insert(lang, ("Êx",  "Êxodo"))
  ldict.at("1003").insert(lang, ("Lv",  "Levítico"))
  ldict.at("1004").insert(lang, ("Nm",  "Números"))
  ldict.at("1005").insert(lang, ("Dt",  "Deuteronômio"))
  ldict.at("1101").insert(lang, ("Js",  "Josué"))
  ldict.at("1102").insert(lang, ("Jz",  "Juízes"))
  ldict.at("1103").insert(lang, ("Rt",  "Rute"))
  ldict.at("1104").insert(lang, ("1Sm", "1 Samuel"))
  ldict.at("1105").insert(lang, ("2Sm", "2 Samuel"))
  ldict.at("1106").insert(lang, ("1Rs", "1 Reis"))
  ldict.at("1107").insert(lang, ("2Rs", "2 Reis"))
  ldict.at("1108").insert(lang, ("1Cr", "1 Crônicas"))
  ldict.at("1109").insert(lang, ("2Cr", "2 Crônicas"))
  ldict.at("1110").insert(lang, ("Ed",  "Esdras"))
  ldict.at("1111").insert(lang, ("Ne",  "Neemias"))
  ldict.at("1112").insert(lang, ("Et",  "Ester"))
  ldict.at("1201").insert(lang, ("Jó",  "Jó"))
  ldict.at("1202").insert(lang, ("Sl",  "Salmos"))
  ldict.at("1203").insert(lang, ("Pv",  "Provérbios"))
  ldict.at("1204").insert(lang, ("Ec",  "Eclesiastes"))
  ldict.at("1205").insert(lang, ("Ct",  "Cântico dos Cânticos"))
  ldict.at("1301").insert(lang, ("Is",  "Isaías"))
  ldict.at("1302").insert(lang, ("Jr",  "Jeremias"))
  ldict.at("1303").insert(lang, ("Lm",  "Lamentações"))
  ldict.at("1304").insert(lang, ("Ez",  "Ezequiel"))
  ldict.at("1305").insert(lang, ("Dn",  "Daniel"))
  ldict.at("1306").insert(lang, ("Os",  "Oséias"))
  ldict.at("1307").insert(lang, ("Jl",  "Joel"))
  ldict.at("1308").insert(lang, ("Am",  "Amos"))
  ldict.at("1309").insert(lang, ("Ob",  "Obadias"))
  ldict.at("1310").insert(lang, ("Jn",  "Jonas"))
  ldict.at("1311").insert(lang, ("Mq",  "Miquéias"))
  ldict.at("1312").insert(lang, ("Na",  "Naum"))
  ldict.at("1313").insert(lang, ("Hc",  "Habacuc"))
  ldict.at("1314").insert(lang, ("Sf",  "Sofonias"))
  ldict.at("1315").insert(lang, ("Ag",  "Ageu"))
  ldict.at("1316").insert(lang, ("Zc",  "Zacarias"))
  ldict.at("1317").insert(lang, ("Ml",  "Malaquias"))
  ldict.at("1401").insert(lang, ("Mt",  "Mateus"))
  ldict.at("1402").insert(lang, ("Mc",  "Marcos"))
  ldict.at("1403").insert(lang, ("Lc",  "Lucas"))
  ldict.at("1404").insert(lang, ("Jo",  "João"))
  ldict.at("1501").insert(lang, ("At",  "Atos dos Apóstolos"))
  ldict.at("1601").insert(lang, ("Rm",  "Romanos"))
  ldict.at("1602").insert(lang, ("1Co", "1 Coríntios"))
  ldict.at("1603").insert(lang, ("2Co", "2 Coríntios"))
  ldict.at("1604").insert(lang, ("Gl",  "Gálatas"))
  ldict.at("1605").insert(lang, ("Ef",  "Efésios"))
  ldict.at("1606").insert(lang, ("Fp",  "Filipenses"))
  ldict.at("1607").insert(lang, ("Cl",  "Colossenses"))
  ldict.at("1608").insert(lang, ("1Ts", "1 Tessalonicenses"))
  ldict.at("1609").insert(lang, ("2Ts", "2 Tessalonicenses"))
  ldict.at("1610").insert(lang, ("1Tm", "1 Timóteo"))
  ldict.at("1611").insert(lang, ("2Tm", "2 Timóteo"))
  ldict.at("1612").insert(lang, ("Tt",  "Tito"))
  ldict.at("1613").insert(lang, ("Fm",  "Filemon"))
  ldict.at("1700").insert(lang, ("Hb",  "Hebreus"))
  ldict.at("1701").insert(lang, ("Tg",  "Tiago"))
  ldict.at("1702").insert(lang, ("1Pe", "1 Pedro"))
  ldict.at("1703").insert(lang, ("2Pe", "2 Pedro"))
  ldict.at("1704").insert(lang, ("1Jo", "1 João"))
  ldict.at("1705").insert(lang, ("2Jo", "2 João"))
  ldict.at("1706").insert(lang, ("3Jo", "3 João"))
  ldict.at("1707").insert(lang, ("Jd",  "Judas"))
  ldict.at("1801").insert(lang, ("Ap",  "Apocalipse"))
  ldict.at("3101").insert(lang, ("1Ed", "1 Esdras"))
  ldict.at("3102").insert(lang, ("Jt",  "Judite"))
  ldict.at("3103").insert(lang, ("Tb",  "Tobias"))
  ldict.at("3104").insert(lang, ("1Mc", "1 Macabeus"))
  ldict.at("3105").insert(lang, ("2Mc", "2 Macabeus"))
  ldict.at("3106").insert(lang, ("3Mc", "3 Macabeus"))
  ldict.at("3107").insert(lang, ("4Mc", "4 Macabeus"))
  ldict.at("3108").insert(lang, ("EG",  "Ester (Grego)"))
  ldict.at("3201").insert(lang, ("SA",  "Salmo Adicional"))
  ldict.at("3202").insert(lang, ("Od",  "Odes"))
  ldict.at("3203").insert(lang, ("Sb",  "Sabedoria (de Salomão)"))
  ldict.at("3204").insert(lang, ("Si",  "Sirácida (Eclesiástico)"))
  ldict.at("3205").insert(lang, ("SS",  "Salmos de Salomão"))
  ldict.at("3206").insert(lang, ("Ba",  "Baruque"))
  ldict.at("3207").insert(lang, ("CJ",  "Carta de Jeremias"))
  ldict.at("3208").insert(lang, ("Su",  "Susana"))
  ldict.at("3209").insert(lang, ("BD",  "Bel e o Dragão"))
  ldict.at("3210").insert(lang, ("TJ",  "Canção dos Três Jovens"))
  ldict.at("5101").insert(lang, ("3Ed", "3 Esdras"))
  ldict.at("5102").insert(lang, ("4Ed", "4 Esdras"))
  ldict.at("5103").insert(lang, ("OM",  "Oração de Manassés"))
}


//--------------------------------------------------------------------------------------------//
//                     Brazilian Portuguese, Catholic, "br-cat", language                     //
//--------------------------------------------------------------------------------------------//

#{
  let lang = "br-cat"
  ldict.at("1001").insert(lang, ("Gn",   "Gênesis"))
  ldict.at("1002").insert(lang, ("Ex",   "Êxodo"))
  ldict.at("1003").insert(lang, ("Lv",   "Levítico"))
  ldict.at("1004").insert(lang, ("Nm",   "Números"))
  ldict.at("1005").insert(lang, ("Dt",   "Deuteronômio"))
  ldict.at("1101").insert(lang, ("Js",   "Josué"))
  ldict.at("1102").insert(lang, ("Jz",   "Juízes"))
  ldict.at("1103").insert(lang, ("Rt",   "Rute"))
  ldict.at("1104").insert(lang, ("1Sm",  "1 Samuel"))
  ldict.at("1105").insert(lang, ("2Sm",  "2 Samuel"))
  ldict.at("1106").insert(lang, ("1Rs",  "1 Reis"))
  ldict.at("1107").insert(lang, ("2Rs",  "2 Reis"))
  ldict.at("1108").insert(lang, ("1Cr",  "1 Crônicas"))
  ldict.at("1109").insert(lang, ("2Cr",  "2 Crônicas"))
  ldict.at("1110").insert(lang, ("Esd",  "Esdras"))
  ldict.at("1111").insert(lang, ("Ne",   "Neemias"))
  ldict.at("3103").insert(lang, ("Tb",   "Tobias"))
  ldict.at("3102").insert(lang, ("Jt",   "Judite"))
  ldict.at("1112").insert(lang, ("Est",  "Ester"))
  ldict.at("3108").insert(lang, ("Est",  "Ester (Grego)")) // Same abbr due to book merging
  ldict.at("3104").insert(lang, ("1Mc",  "1 Macabeus"))
  ldict.at("3105").insert(lang, ("2Mc",  "2 Macabeus"))
  ldict.at("1201").insert(lang, ("Jó",   "Jó"))
  ldict.at("1202").insert(lang, ("Sl",   "Salmos"))
  ldict.at("1203").insert(lang, ("Pr",   "Provérbios"))
  ldict.at("1204").insert(lang, ("Ecl",  "Eclesiastes"))
  ldict.at("1205").insert(lang, ("Ct",   "Cântico dos Cânticos"))
  ldict.at("3203").insert(lang, ("Sb",   "Sabedoria"))
  ldict.at("3204").insert(lang, ("Eclo", "Eclesiástico"))
  ldict.at("1301").insert(lang, ("Is",   "Isaías"))
  ldict.at("1302").insert(lang, ("Jr",   "Jeremias"))
  ldict.at("1303").insert(lang, ("Lm",   "Lamentações"))
  ldict.at("3206").insert(lang, ("Br",   "Baruc"))
  ldict.at("3207").insert(lang, ("Br",   "Carta de Jeremias"))       // book merging
  ldict.at("1304").insert(lang, ("Ez",   "Ezequiel"))
  ldict.at("1305").insert(lang, ("Dn",   "Daniel"))
  ldict.at("3210").insert(lang, ("Dn",   "Canção dos Três Jovens"))  // book merging
  ldict.at("3208").insert(lang, ("Dn",   "Susana"))                  // book merging
  ldict.at("3209").insert(lang, ("Dn",   "Bel e o Dragão"))          // book merging
  ldict.at("1306").insert(lang, ("Os",   "Oséias"))
  ldict.at("1307").insert(lang, ("Jl",   "Joel"))
  ldict.at("1308").insert(lang, ("Am",   "Amos"))
  ldict.at("1309").insert(lang, ("Ab",   "Abdias"))
  ldict.at("1310").insert(lang, ("Jn",   "Jonas"))
  ldict.at("1311").insert(lang, ("Mq",   "Miquéias"))
  ldict.at("1312").insert(lang, ("Na",   "Naum"))
  ldict.at("1313").insert(lang, ("Hab",  "Habacuc"))
  ldict.at("1314").insert(lang, ("Sf",   "Sofonias"))
  ldict.at("1315").insert(lang, ("Ag",   "Ageu"))
  ldict.at("1316").insert(lang, ("Zc",   "Zacarias"))
  ldict.at("1317").insert(lang, ("Ml",   "Malaquias"))
  ldict.at("1401").insert(lang, ("Mt",   "Mateus"))
  ldict.at("1402").insert(lang, ("Mc",   "Marcos"))
  ldict.at("1403").insert(lang, ("Lc",   "Lucas"))
  ldict.at("1404").insert(lang, ("Jo",   "João"))
  ldict.at("1501").insert(lang, ("At",   "Atos dos Apóstolos"))
  ldict.at("1601").insert(lang, ("Rm",   "Romanos"))
  ldict.at("1602").insert(lang, ("1Cor", "1 Coríntios"))
  ldict.at("1603").insert(lang, ("2Cor", "2 Coríntios"))
  ldict.at("1604").insert(lang, ("Gl",   "Gálatas"))
  ldict.at("1605").insert(lang, ("Ef",   "Efésios"))
  ldict.at("1606").insert(lang, ("Fl",   "Filipenses"))
  ldict.at("1607").insert(lang, ("Cl",   "Colossenses"))
  ldict.at("1608").insert(lang, ("1Ts",  "1 Tessalonicenses"))
  ldict.at("1609").insert(lang, ("2Ts",  "2 Tessalonicenses"))
  ldict.at("1610").insert(lang, ("1Tm",  "1 Timóteo"))
  ldict.at("1611").insert(lang, ("2Tm",  "2 Timóteo"))
  ldict.at("1612").insert(lang, ("Tt",   "Tito"))
  ldict.at("1613").insert(lang, ("Fm",   "Filemon"))
  ldict.at("1700").insert(lang, ("Hb",   "Hebreus"))
  ldict.at("1701").insert(lang, ("Tg",   "Tiago"))
  ldict.at("1702").insert(lang, ("1Pd",  "1 Pedro"))
  ldict.at("1703").insert(lang, ("2Pd",  "2 Pedro"))
  ldict.at("1704").insert(lang, ("1Jo",  "1 João"))
  ldict.at("1705").insert(lang, ("2Jo",  "2 João"))
  ldict.at("1706").insert(lang, ("3Jo",  "3 João"))
  ldict.at("1707").insert(lang, ("Jd",   "Judas"))
  ldict.at("1801").insert(lang, ("Ap",   "Apocalipse"))
  ldict.at("3101").insert(lang, ("1Esd", "1 Esdras"))
  ldict.at("3106").insert(lang, ("3Mc",  "3 Macabeus"))
  ldict.at("3107").insert(lang, ("4Mc",  "4 Macabeus"))
  ldict.at("5101").insert(lang, ("3Esd", "3 Esdras"))
  ldict.at("5102").insert(lang, ("4Esd", "4 Esdras"))
  ldict.at("5103").insert(lang, ("PrM",  "Prece de Manassés"))
  ldict.at("3201").insert(lang, ("SlA",  "Salmo Adicional"))
  ldict.at("3202").insert(lang, ("Ode",  "Odes"))
  ldict.at("3205").insert(lang, ("SlS",  "Salmos de Salomão"))
}


//--------------------------------------------------------------------------------------------//
//                          Français, Œcuménique, "fr-TOB", language                          //
//--------------------------------------------------------------------------------------------//

#{
  let lang = "fr-TOB"
  ldict.at("1001").insert(lang, ("Gn",       "Genèse"))
  ldict.at("1002").insert(lang, ("Ex",       "Exode"))
  ldict.at("1003").insert(lang, ("Lv",       "Lévitique"))
  ldict.at("1004").insert(lang, ("Nb",       "Nombres"))
  ldict.at("1005").insert(lang, ("Dt",       "Deutéronome"))
  ldict.at("1101").insert(lang, ("Jos",      "Josué"))
  ldict.at("1102").insert(lang, ("Jg",       "Juges"))
  ldict.at("1103").insert(lang, ("Rt",       "Ruth"))
  ldict.at("1104").insert(lang, ("1S",       "1 Samuel"))
  ldict.at("1105").insert(lang, ("2S",       "2 Samuel"))
  ldict.at("1106").insert(lang, ("1R",       "1 Rois"))
  ldict.at("1107").insert(lang, ("2R",       "2 Rois"))
  ldict.at("1108").insert(lang, ("1Ch",      "1 Chroniques"))
  ldict.at("1109").insert(lang, ("2Ch",      "2 Chroniques"))
  ldict.at("1110").insert(lang, ("Esd",      "Esdras"))
  ldict.at("1111").insert(lang, ("Ne",       "Néhémie"))
  ldict.at("1112").insert(lang, ("Est",      "Esther"))
  ldict.at("1201").insert(lang, ("Jb",       "Job"))
  ldict.at("1202").insert(lang, ("Ps",       "Psaumes"))
  ldict.at("1203").insert(lang, ("Pr",       "Proverbes"))
  ldict.at("1204").insert(lang, ("Qo",       "Qohéleth"))
  ldict.at("1205").insert(lang, ("Ct",       "Cantique des cantiques"))
  ldict.at("1301").insert(lang, ("Es",       "Esaïe"))
  ldict.at("1302").insert(lang, ("Jr",       "Jérémie"))
  ldict.at("1303").insert(lang, ("Lm",       "Lamentations"))
  ldict.at("1304").insert(lang, ("Ez",       "Ezéchiel"))
  ldict.at("1305").insert(lang, ("Dn",       "Daniel"))
  ldict.at("1306").insert(lang, ("Os",       "Osée"))
  ldict.at("1307").insert(lang, ("Jl",       "Joël"))
  ldict.at("1308").insert(lang, ("Am",       "Amos"))
  ldict.at("1309").insert(lang, ("Ab",       "Abdias"))
  ldict.at("1310").insert(lang, ("Jon",      "Jonas"))
  ldict.at("1311").insert(lang, ("Mi",       "Michée"))
  ldict.at("1312").insert(lang, ("Na",       "Nahoum"))
  ldict.at("1313").insert(lang, ("Ha",       "Habaquq"))
  ldict.at("1314").insert(lang, ("So",       "Sophonie"))
  ldict.at("1315").insert(lang, ("Ag",       "Aggée"))
  ldict.at("1316").insert(lang, ("Za",       "Zacharie"))
  ldict.at("1317").insert(lang, ("Ml",       "Malachie"))
  ldict.at("1401").insert(lang, ("Mt",       "Matthieu"))
  ldict.at("1402").insert(lang, ("Mc",       "Marc"))
  ldict.at("1403").insert(lang, ("Lc",       "Luc"))
  ldict.at("1404").insert(lang, ("Jn",       "Jean"))
  ldict.at("1501").insert(lang, ("Ac",       "Actes des Apôtres"))
  ldict.at("1601").insert(lang, ("Rm",       "Romains"))
  ldict.at("1602").insert(lang, ("1Co",      "1 Corinthiens"))
  ldict.at("1603").insert(lang, ("2Co",      "2 Corinthiens"))
  ldict.at("1604").insert(lang, ("Ga",       "Galates"))
  ldict.at("1605").insert(lang, ("Ep",       "Ephésiens"))
  ldict.at("1606").insert(lang, ("Ph",       "Philippiens"))
  ldict.at("1607").insert(lang, ("Col",      "Colossiens"))
  ldict.at("1608").insert(lang, ("1Th",      "1 Thessaloniciens"))
  ldict.at("1609").insert(lang, ("2Th",      "2 Thessaloniciens"))
  ldict.at("1610").insert(lang, ("1Tm",      "1 Timothée"))
  ldict.at("1611").insert(lang, ("2Tm",      "2 Timothée"))
  ldict.at("1612").insert(lang, ("Tt",       "Tite"))
  ldict.at("1613").insert(lang, ("Phm",      "Philémon"))
  ldict.at("1700").insert(lang, ("He",       "Hébreux"))
  ldict.at("1701").insert(lang, ("Jc",       "Jacques"))
  ldict.at("1702").insert(lang, ("1P",       "1 Pierre"))
  ldict.at("1703").insert(lang, ("2P",       "2 Pierre"))
  ldict.at("1704").insert(lang, ("1Jn",      "1 Jean"))
  ldict.at("1705").insert(lang, ("2Jn",      "2 Jean"))
  ldict.at("1706").insert(lang, ("3Jn",      "3 Jean"))
  ldict.at("1707").insert(lang, ("Jude",     "Jude"))
  ldict.at("1801").insert(lang, ("Ap",       "Apocalypse"))
  ldict.at("3101").insert(lang, ("1Esd",     "1 Esdras"))
  ldict.at("3102").insert(lang, ("Jdt",      "Judith"))
  ldict.at("3103").insert(lang, ("Tb",       "Tobit"))
  ldict.at("3104").insert(lang, ("1M",       "1 Maccabées"))
  ldict.at("3105").insert(lang, ("2M",       "2 Maccabées"))
  ldict.at("3106").insert(lang, ("3M",       "3 Maccabées"))
  ldict.at("3107").insert(lang, ("4M",       "4 Maccabées"))
  ldict.at("3108").insert(lang, ("Est-grec", "Esther grec"))
  ldict.at("3201").insert(lang, ("Ps-151",   "Psaume 151"))
  ldict.at("3202").insert(lang, ("Ode",      "Odes"))
  ldict.at("3203").insert(lang, ("Sg",       "Sagesse"))
  ldict.at("3204").insert(lang, ("Si",       "Siracide"))
  ldict.at("3205").insert(lang, ("Ps-Sol",   "Psaumes Solomon"))
  ldict.at("3206").insert(lang, ("Ba",       "Baruch"))
  ldict.at("3207").insert(lang, ("Lt-Jr",    "Lettre de Jérémie"))
  ldict.at("3208").insert(lang, ("Dn-grec",  "Suzanne"))            // Chapître 13
  ldict.at("3209").insert(lang, ("Dn-grec",  "Bel et le Dragon"))   // Chapître 14
  ldict.at("3210").insert(lang, ("Dn-grec",  "Prière d'Azarya"))    // Chapître 3
  ldict.at("5101").insert(lang, ("3Esd",     "3 Esdras"))
  ldict.at("5102").insert(lang, ("4Esd",     "4 Esdras"))
  ldict.at("5103").insert(lang, ("Mn",       "Prière de Manassé"))
}


