[package]
name = "blindex"
version = "0.3.0"
entrypoint = "blindex.typ"
authors = ["Naaktgeboren, C.", ]
license = "MIT"
description = "Index-making of Biblical literature citations in Typst"
keywords = ["index", "biblical", "literature", "canonical", "deuterocanonical", "apocripha"]
categories = ["model", "scripting"]
disciplines = ["theology", ]
compiler = "0.14.1"
