[package]
name = "vote-card"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Aurelien Saudemont"]
license = "MIT"
description = "Un composant pour afficher des résultats de vote avec des barres de progression."
