[package]
name = "itemplate"
version = "0.3.2"
entrypoint = "itemplate.typ"
exclude = ["assets/*", ]
authors = ["HeXiongwu"]
license = "MIT"
description = "A html template developed by an amateur, use with caution."
repository = "https://github.com/hexiongwu1995/iTemplate"
keywords = ["html", "template"]
categories = ["html", "layout"]
compiler = "0.15.0"