[package]
name = "newt"
version = "0.1.0"
compiler = "0.12.0"
entrypoint = "src/lib.typ"
authors = ["kanagrou <https://github.com/kanagrou>"]
license = "MIT"
description = "Simple number and unit typesetting."
categories = ["text"]
disciplines = [
    "engineering",
    "mathematics",
    "physics",
]
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  "examples",
  ".typstignore",
  "justfile",
]
