#import "default.typ"
#import "simple.typ"
#import "classic.typ"
#import "structured/progressive-outline.typ"
#import "structured/sidebar.typ"
#import "structured/miniframes.typ"
#import "structured/split.typ"
#import "structured/minimal.typ"