[package]
name = "longops"
version = "0.2.0"
entrypoint = "lib.typ"
authors = [ "Akilon <https://github.com/Akilon27>" ]
license = "MIT"
description = "Long operations and detailed calculations.                        Opérations posées et calculs détaillés."
repository = "https://github.com/Akilon27/longops"
categories = [ "utility", "visualization" ]
disciplines = [ "mathematics", "education" ]
keywords = [
  "addition",
  "soustraction",
  "subtraction",
  "multiplication",
  "division",
  "opérations",
  "operations",
  "racine",
  "sqrt",
  "square root",
  "durées",
  "durations",
  "xlop",
  "base",
  "binary",
  "hexadecimal"
]
exclude = [ "/Exemples/*", "*.pdf", "*.svg" ]
compiler = "0.12.0"
