[package]
name = "breezy-report"
version = "0.1.0"
entrypoint = "template.typ"
authors = ["Breanna Barraclough <https://github.com/brebarra>"]
license = "MIT"
description = "Clean, colour-customisable engineering report template for university submissions."
repository = "https://github.com/brebarra/breezy-report"
keywords = ["report","assignment","university"]
categories = ["report"]
exclude = [
    "/imgs/2.png",
    "/imgs/3.png"
]


[template]
path = "main.typ"
entrypoint = "template.typ"
thumbnail = "imgs/1.png"