[package]
name = "oak-grove"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Àlex Touza"]
license = "MIT"
description = "Create problem sets with support for multiple solutions, tags, links and code."
repository = "https://github.com/alex-touza/oak-grove"
categories = ["model", "scripting"]
disciplines = ["computer-science", "education"]
