/// folio — Hardware Construction Project Example
/// Demonstrates: full budget with line items, risk register, compliance,
/// deliverables, and custom section injection. Uses the corporate preset.

#import "@preview/folio:0.0.1": card, project-doc

// Custom section: site-safety annex
#let site-safety(data-path) = context {
  heading(level: 2)[Site Safety Plan]
  card(title: "Emergency Protocols")[
    All personnel must complete site-safety induction before entering the works area.
    Emergency assembly point: north car park. Site supervisor carries first-aid kit at all times.
  ]
  card(title: "PPE Requirements")[
    Hard hat, hi-vis vest, steel-toed boots, and safety glasses are mandatory on-site.
    Hearing protection required in machinery zones.
  ]
}

#show: project-doc(
  data: (
    project: (
      name: "Riverside Community Centre — Structural Refurbishment",
      description: "Full structural assessment, remedial works, and interior fit-out. Phase 1 contract.",
    ),
    initiation: (
      pitch: "Upgrade the 1972-built community centre to modern seismic and energy standards while retaining the original façade. Estimated 20-year asset life extension.",
      business_case: "The council faces a binary choice: invest in refurbishment at ~$1.8M or demolish and rebuild at ~$4.5M. Refurbishment preserves a heritage asset, reduces embodied carbon by 60%, and keeps the facility operational for the neighbourhood during works.",
      objectives: (
        (
          id: "OBJ-1",
          description: "Complete structural remediation to NZS 3101 compliance",
          priority: "high",
        ),
        (
          id: "OBJ-2",
          description: "Achieve 7.5-star NatHERS energy rating",
          priority: "high",
        ),
        (
          id: "OBJ-3",
          description: "Maintain 70% facility operation throughout works",
          priority: "high",
        ),
        (
          id: "OBJ-4",
          description: "Deliver within approved $1.82M budget",
          priority: "neutral",
        ),
      ),
      success_criteria: (
        (
          id: "SC-1",
          type: "project",
          criterion: "Seismic IEP score ≥ 67% NBS",
          measurement: "IEP assessment",
          target: "≥ 67%",
          objective_id: "OBJ-1",
        ),
        (
          id: "SC-2",
          type: "product",
          criterion: "Energy star rating",
          measurement: "NatHERS certificate",
          target: "7.5★",
          objective_id: "OBJ-2",
        ),
        (
          id: "SC-3",
          type: "project",
          criterion: "Operational continuity",
          measurement: "% facility accessible",
          target: "≥ 70%",
          objective_id: "OBJ-3",
        ),
        (
          id: "SC-4",
          type: "project",
          criterion: "Final cost vs. approved budget",
          measurement: "Cost variance",
          target: "< +5%",
          objective_id: "OBJ-4",
        ),
      ),
      stakeholders: (
        (
          id: "SH-1",
          name: "Riverside District Council",
          role: "Client / Funder",
          interest: "high",
          influence: "high",
          engagement: "Weekly progress meeting",
        ),
        (
          id: "SH-2",
          name: "Structural Works Ltd",
          role: "Head Contractor",
          interest: "high",
          influence: "high",
          engagement: "Daily site briefing",
        ),
        (
          id: "SH-3",
          name: "Community Users Group",
          role: "End Users",
          interest: "high",
          influence: "medium",
          engagement: "Monthly update newsletter",
        ),
        (
          id: "SH-4",
          name: "Heritage NZ",
          role: "Regulatory Body",
          interest: "medium",
          influence: "high",
          engagement: "Milestone sign-off",
        ),
        (
          id: "SH-5",
          name: "Building Consents Authority",
          role: "Regulatory Body",
          interest: "low",
          influence: "high",
          engagement: "Inspection hold points",
        ),
      ),
      assumptions_log: (
        (
          id: "A-1",
          type: "assumption",
          description: "Ground conditions match 2024 geotechnical report",
          status: "Validated",
        ),
        (
          id: "A-2",
          type: "constraint",
          description: "Heritage façade cannot be altered or clad",
          status: "Validated",
        ),
        (
          id: "A-3",
          type: "assumption",
          description: "Asbestos removal complete before structural works",
          status: "Open",
          risk_id: "R1",
        ),
        (
          id: "A-4",
          type: "dependency",
          description: "Council budget appropriation confirmed by June",
          status: "Validated",
        ),
      ),
    ),
    baselines: (
      scope: (
        in_scope: (
          "Seismic retrofit — base isolation and moment frames",
          "Roof replacement with insulated metal deck",
          "Façade repointing and damp-proof membrane",
          "Mechanical/electrical systems upgrade",
          "Interior fit-out (3 community rooms + foyer)",
          "Accessibility compliance (DDA)",
          "Landscaping — car park reseal and ramp construction",
        ),
        out_of_scope: (
          "Kitchen equipment (separate council procurement)",
          "IT infrastructure (separate contract)",
          "Furniture and loose fittings",
          "External signage",
        ),
      ),
      requirements: (
        (
          id: "REQ-01",
          description: "Seismic base isolation system",
          category: "Structural",
          priority: "high",
          qty: 1,
          unit: "system",
          unit_cost: 320000,
          compliance_ids: ("COMP-1",),
        ),
        (
          id: "REQ-02",
          description: "Moment-resisting steel frames",
          category: "Structural",
          priority: "high",
          qty: 4,
          unit: "frames",
          unit_cost: 45000,
        ),
        (
          id: "REQ-03",
          description: "Roof replacement — insulated metal deck",
          category: "Envelope",
          priority: "high",
          qty: 1,
          unit: "job",
          unit_cost: 185000,
        ),
        (
          id: "REQ-04",
          description: "External façade repointing + membrane",
          category: "Envelope",
          priority: "high",
          qty: 680,
          unit: "m²",
          unit_cost: 180,
          compliance_ids: ("COMP-2",),
        ),
        (
          id: "REQ-05",
          description: "HVAC replacement — VRF system",
          category: "Mechanical",
          priority: "high",
          qty: 1,
          unit: "system",
          unit_cost: 145000,
        ),
        (
          id: "REQ-06",
          description: "Electrical distribution board upgrade",
          category: "Electrical",
          priority: "high",
          qty: 1,
          unit: "install",
          unit_cost: 38000,
        ),
        (
          id: "REQ-07",
          description: "LED lighting throughout",
          category: "Electrical",
          priority: "medium",
          qty: 220,
          unit: "fixtures",
          unit_cost: 280,
        ),
        (
          id: "REQ-08",
          description: "Interior fit-out — community rooms",
          category: "Interior",
          priority: "high",
          qty: 3,
          unit: "rooms",
          unit_cost: 85000,
        ),
        (
          id: "REQ-09",
          description: "Foyer and reception fit-out",
          category: "Interior",
          priority: "medium",
          qty: 1,
          unit: "job",
          unit_cost: 62000,
        ),
        (
          id: "REQ-10",
          description: "DDA access ramp + lift",
          category: "Accessibility",
          priority: "high",
          qty: 1,
          unit: "job",
          unit_cost: 78000,
          compliance_ids: ("COMP-3",),
        ),
        (
          id: "REQ-11",
          description: "Car park reseal + line marking",
          category: "External",
          priority: "medium",
          qty: 1,
          unit: "job",
          unit_cost: 24000,
        ),
        (
          id: "REQ-12",
          description: "Asbestos removal and disposal",
          category: "Remediation",
          priority: "high",
          qty: 1,
          unit: "job",
          unit_cost: 55000,
          compliance_ids: ("COMP-4",),
        ),
      ),
      schedule: (
        milestones: (
          (
            id: "M1",
            date: "2026-08-01",
            title: "Asbestos clearance certificate",
            status: "Pending",
          ),
          (
            id: "M2",
            date: "2026-09-15",
            title: "Structural works — practical completion",
            status: "Pending",
          ),
          (
            id: "M3",
            date: "2026-12-01",
            title: "Envelope complete (roof + façade)",
            status: "Pending",
          ),
          (
            id: "M4",
            date: "2027-02-15",
            title: "M&E services commissioned",
            status: "Pending",
          ),
          (
            id: "M5",
            date: "2027-05-01",
            title: "Interior fit-out complete",
            status: "Pending",
          ),
          (
            id: "M6",
            date: "2027-06-30",
            title: "Practical completion — project",
            status: "Pending",
          ),
        ),
        gantt: (
          start: "2026-07-01",
          end: "2027-07-31",
          tasks: (
            (
              name: "Preliminary",
              subtasks: (
                (
                  id: "T1",
                  name: "Asbestos removal",
                  start: "2026-07-01",
                  end: "2026-08-01",
                ),
                (
                  id: "T2",
                  name: "Site establishment",
                  start: "2026-07-15",
                  end: "2026-08-01",
                ),
              ),
            ),
            (
              name: "Structural",
              subtasks: (
                (
                  id: "T3",
                  name: "Base isolation install",
                  start: "2026-08-01",
                  end: "2026-09-01",
                ),
                (
                  id: "T4",
                  name: "Steel moment frames",
                  start: "2026-08-15",
                  end: "2026-09-15",
                ),
              ),
            ),
            (
              name: "Envelope",
              subtasks: (
                (
                  id: "T5",
                  name: "Roof replacement",
                  start: "2026-09-15",
                  end: "2026-11-01",
                ),
                (
                  id: "T6",
                  name: "Façade works",
                  start: "2026-10-01",
                  end: "2026-12-01",
                ),
              ),
            ),
            (
              name: "Services",
              subtasks: (
                (
                  id: "T7",
                  name: "HVAC installation",
                  start: "2026-12-01",
                  end: "2027-02-01",
                ),
                (
                  id: "T8",
                  name: "Electrical upgrade",
                  start: "2026-12-15",
                  end: "2027-02-15",
                ),
              ),
            ),
            (
              name: "Interior & External",
              subtasks: (
                (
                  id: "T9",
                  name: "Interior fit-out",
                  start: "2027-02-15",
                  end: "2027-05-01",
                ),
                (
                  id: "T10",
                  name: "DDA ramp + car park",
                  start: "2027-04-01",
                  end: "2027-06-01",
                ),
              ),
            ),
            (
              name: "Commissioning",
              subtasks: (
                (
                  id: "T11",
                  name: "Services commissioning",
                  start: "2027-05-01",
                  end: "2027-06-01",
                ),
                (
                  id: "T12",
                  name: "Defects rectification",
                  start: "2027-06-01",
                  end: "2027-06-30",
                ),
              ),
            ),
          ),
          milestones: (
            (name: "Asbestos clear", date: "2026-08-01", show-date: true),
            (name: "Structural PC", date: "2026-09-15", show-date: true),
            (name: "Practical completion", date: "2027-06-30", show-date: true),
          ),
        ),
      ),
      financials: (
        budget: (
          line_items: (
            (
              id: "BUD-01",
              description: "Base isolation system",
              category: "Structural",
              qty: 1,
              unit: "system",
              unit_cost: 320000,
              req_id: "REQ-01",
            ),
            (
              id: "BUD-02",
              description: "Moment-resisting frames (×4)",
              category: "Structural",
              qty: 4,
              unit: "frames",
              unit_cost: 45000,
              req_id: "REQ-02",
            ),
            (
              id: "BUD-03",
              description: "Roof replacement",
              category: "Envelope",
              qty: 1,
              unit: "job",
              unit_cost: 185000,
              req_id: "REQ-03",
            ),
            (
              id: "BUD-04",
              description: "Façade repointing + membrane",
              category: "Envelope",
              qty: 680,
              unit: "m²",
              unit_cost: 180,
              req_id: "REQ-04",
            ),
            (
              id: "BUD-05",
              description: "HVAC — VRF system",
              category: "Mechanical",
              qty: 1,
              unit: "system",
              unit_cost: 145000,
              req_id: "REQ-05",
            ),
            (
              id: "BUD-06",
              description: "Electrical board upgrade",
              category: "Electrical",
              qty: 1,
              unit: "install",
              unit_cost: 38000,
              req_id: "REQ-06",
            ),
            (
              id: "BUD-07",
              description: "LED lighting (220 fixtures)",
              category: "Electrical",
              qty: 220,
              unit: "fix.",
              unit_cost: 280,
              req_id: "REQ-07",
            ),
            (
              id: "BUD-08",
              description: "Community room fit-out (×3)",
              category: "Interior",
              qty: 3,
              unit: "rooms",
              unit_cost: 85000,
              req_id: "REQ-08",
            ),
            (
              id: "BUD-09",
              description: "Foyer fit-out",
              category: "Interior",
              qty: 1,
              unit: "job",
              unit_cost: 62000,
              req_id: "REQ-09",
            ),
            (
              id: "BUD-10",
              description: "DDA ramp + lift",
              category: "Accessibility",
              qty: 1,
              unit: "job",
              unit_cost: 78000,
              req_id: "REQ-10",
            ),
            (
              id: "BUD-11",
              description: "Car park reseal",
              category: "External",
              qty: 1,
              unit: "job",
              unit_cost: 24000,
              req_id: "REQ-11",
            ),
            (
              id: "BUD-12",
              description: "Asbestos removal",
              category: "Remediation",
              qty: 1,
              unit: "job",
              unit_cost: 55000,
              req_id: "REQ-12",
            ),
          ),
          extra_costs: (
            (
              description: "Contractor margin + prelims (12%)",
              percentage: 0.12,
            ),
            (
              description: "Contingency — unforeseen conditions (8%)",
              percentage: 0.08,
            ),
            (description: "Consultant fees (PM, QS, Engineers)", cost: 95000),
          ),
        ),
      ),
      quality: (
        standards: (
          "NZS 3101:2006 — Concrete Structures Standard",
          "NZS 3404:1997 — Steel Structures Standard",
          "NZS 4218:2009 — Energy Efficiency",
          "NZBC Clause F8 — Signs (accessibility)",
        ),
        acceptance_procedure: "Hold-point inspections at each milestone. BCA consent authority sign-off required at structural, envelope, and services stages.",
        testing_strategy: "Seismic IEP assessment post-structural works. HVAC commissioning report. Air-tightness blower-door test.",
        criteria: (
          (
            req_id: "REQ-01",
            criterion: "IEP score ≥ 67% NBS",
            method: "Peer-reviewed IEP assessment",
          ),
          (
            req_id: "REQ-03",
            criterion: "Air-tightness < 3 ACH @ 50Pa",
            method: "Blower-door test",
          ),
          (
            req_id: "REQ-05",
            criterion: "HVAC commissioned to spec",
            method: "Commissioning report",
          ),
        ),
      ),
      communication: (
        (
          what: "Site progress report",
          audience: "Council project manager",
          frequency: "Weekly",
          channel: "Email + Procore",
          owner: "Head contractor",
        ),
        (
          what: "Community newsletter",
          audience: "Residents & users",
          frequency: "Monthly",
          channel: "Council website",
          owner: "PM",
        ),
        (
          what: "BCA hold-point notice",
          audience: "Building consents",
          frequency: "Per hold pt",
          channel: "InspectionXpress",
          owner: "PM",
        ),
        (
          what: "Heritage consultation",
          audience: "Heritage NZ",
          frequency: "Milestone",
          channel: "Formal letter",
          owner: "Architect",
        ),
      ),
      risk_strategy: (
        approach: "Construction risk managed under AS/NZS 4360. Contractor holds site-specific risk register reviewed weekly in progress meetings.",
        categories: (
          "Ground conditions",
          "Heritage fabric",
          "Weather / programme",
          "Regulatory",
          "Cost escalation",
        ),
        scoring: "5×5 likelihood × consequence matrix",
        tolerance: "No High risks unmitigated before works commence in that zone.",
        escalation_threshold: "Any Very High risk paused immediately; reported to council within 24h.",
      ),
      compliance: (
        (
          id: "COMP-1",
          regulation: "NZS 3101:2006 — Seismic Design",
          jurisdiction: "NZ",
          req_ids: ("REQ-01", "REQ-02"),
          status: "Pending",
          audit_date: "2026-09-15",
        ),
        (
          id: "COMP-2",
          regulation: "Heritage NZ Act 2014 — Listed Building",
          jurisdiction: "NZ",
          req_ids: ("REQ-04",),
          status: "Compliant",
        ),
        (
          id: "COMP-3",
          regulation: "NZBC Clause D1 — Access Routes",
          jurisdiction: "NZ",
          req_ids: ("REQ-10",),
          status: "Pending",
        ),
        (
          id: "COMP-4",
          regulation: "HSWA 2015 — Hazardous Substances",
          jurisdiction: "NZ",
          req_ids: ("REQ-12",),
          status: "Compliant",
          audit_date: "2026-08-01",
        ),
      ),
    ),
    governance: (
      team: (
        (
          role: "Project Manager",
          name: "Sarah Kim",
          email: "s.kim@councilpm.nz",
        ),
        (
          role: "Head Contractor",
          name: "Dave Structural Ltd",
          email: "d.structural@works.nz",
        ),
        (
          role: "Structural Engineer",
          name: "Ana Ferreira PE",
          email: "a.ferreira@structeng.nz",
        ),
        (
          role: "Quantity Surveyor",
          name: "Tom Walsh MNZIQS",
          email: "t.walsh@qs.nz",
        ),
        (
          role: "Heritage Architect",
          name: "Lena Park",
          email: "l.park@heritage-arch.nz",
        ),
      ),
    ),
    execution: (
      status: (
        health: "Good",
        spend: "0%",
        variance: "0d",
        summary: "Project in mobilisation phase. Asbestos contractor on-site from July 1. All consents issued.",
      ),
    ),
    registers: (
      risk_register: (
        (
          id: "R1",
          description: "Unexpected asbestos quantities beyond initial survey",
          mitigation: "Provisional sum in budget; daily progress monitoring with licensed removalist",
          probability: "Medium",
          impact: "High",
          status: "Open",
          source_assumption: "A-3",
          affects_wbs: ("T1",),
          blocks_milestone: ("M1",),
        ),
        (
          id: "R2",
          description: "Ground conditions worse than geotechnical report (soft pockets)",
          mitigation: "Provisional sum for ground improvement; engineer present at foundation level",
          probability: "Low",
          impact: "High",
          status: "Open",
          affects_wbs: ("T3",),
        ),
        (
          id: "R3",
          description: "Heritage NZ direction to halt works on façade discovery",
          mitigation: "Pre-engagement with Heritage NZ; photographic record before any works",
          probability: "Low",
          impact: "High",
          status: "Open",
          affects_wbs: ("T6",),
        ),
        (
          id: "R4",
          description: "Steel price escalation beyond contract allowance",
          mitigation: "Fixed-price subcontract for structural steel locked in at contract award",
          probability: "Medium",
          impact: "Medium",
          status: "Monitoring",
        ),
        (
          id: "R5",
          description: "Wet weather delays to envelope programme",
          mitigation: "Weather days allowance in programme; temporary roofing over critical zones",
          probability: "High",
          impact: "Medium",
          status: "Monitoring",
          affects_wbs: ("T5", "T6"),
        ),
      ),
      issue_log: (
        (
          id: "I1",
          description: "Asbestos survey identified additional AIB in roof void not in original scope",
          owner: "Sarah Kim",
          status: "In-Progress",
          blocks_milestone: ("M1",),
        ),
      ),
      change_log: (
        (
          id: "C1",
          description: "Additional asbestos removal — roof void AIB",
          status: "Pending",
          type: "scope",
          affects_baseline: "baselines.financials.budget",
        ),
        (
          id: "C2",
          description: "Substitute VRF brand due to lead-time (equiv. spec.)",
          status: "Approved",
          type: "procurement",
          affects_baseline: "baselines.requirements",
        ),
      ),
      decision_log: (
        (
          id: "DEC-1",
          description: "Retain base isolation over traditional wall bracing",
          date: "2026-05-10",
          decision_maker: "Ana Ferreira PE",
          rationale: "Base isolation provides 20% better seismic performance and reduces fit-out disruption.",
          reversibility: "Type-1",
        ),
        (
          id: "DEC-2",
          description: "Proceed with fixed-price steel subcontract despite spot market",
          date: "2026-05-20",
          decision_maker: "Sarah Kim",
          rationale: "Budget certainty outweighs potential savings; council requires fixed-price delivery.",
          reversibility: "Type-1",
          prompted_by_risk: "R4",
        ),
      ),
      deliverables_register: (
        (
          id: "D1",
          description: "Asbestos clearance certificate",
          owner: "Licensed removalist",
          due_date: "2026-08-01",
          status: "Planned",
          req_ids: ("REQ-12",),
        ),
        (
          id: "D2",
          description: "Structural works — as-built drawings",
          owner: "Ana Ferreira PE",
          due_date: "2026-09-30",
          status: "Planned",
          req_ids: ("REQ-01", "REQ-02"),
        ),
        (
          id: "D3",
          description: "Building consent CCC — structure",
          owner: "BCA",
          due_date: "2026-10-15",
          status: "Planned",
          req_ids: ("REQ-01",),
        ),
        (
          id: "D4",
          description: "HVAC commissioning report",
          owner: "M&E contractor",
          due_date: "2027-02-28",
          status: "Planned",
          req_ids: ("REQ-05",),
        ),
        (
          id: "D5",
          description: "NatHERS 7.5★ certificate",
          owner: "Energy assessor",
          due_date: "2027-03-15",
          status: "Planned",
          req_ids: ("REQ-03", "REQ-05"),
        ),
        (
          id: "D6",
          description: "Project CCC — practical completion",
          owner: "BCA",
          due_date: "2027-07-15",
          status: "Planned",
          req_ids: ("REQ-10",),
        ),
      ),
    ),
    closure: (
      lessons_learned: (),
      sign_off: (
        (name: "Sarah Kim", role: "Project Manager"),
        (name: "Riverside District Council", role: "Client Representative"),
        (name: "Structural Works Ltd", role: "Head Contractor"),
        (name: "Heritage NZ", role: "Heritage Approval"),
      ),
    ),
    custom: (
      safety: (level: "Full site — class 2 hazard zone"),
    ),
  ),
  config: (
    toc: true,
    audit: false,
    extra-sections: (
      (
        id: "site-safety",
        phase: "custom",
        data-path: "custom.safety",
        render: site-safety,
      ),
    ),
  ),
  brand: (
    // preset: "corporate",
    // preset: "academic",
    // preset: "minimal",
    palette: (primary: rgb("#1a3a5c")),
  ),
)
