[package]
name = "citrus"
version = "0.2.1"
entrypoint = "lib.typ"
authors = ["lucifer1004"]
license = "MIT"
description = "Fresh citations — format bibliographies with standard CSL styles, plus CSL-M support."
repository = "https://github.com/pku-typst/citeproc-typst"
keywords = ["bibliography", "citation", "csl", "reference"]
categories = ["utility"]
compiler = "0.14.0"
