[package]
name = "minerva-thesis"
version = "0.3.0"
license = "MIT"
entrypoint = "lib/lib.typ"
authors = ["Lieven Vandevelde"]
description = "Doctoral and master's theses using both generic and Ghent University specific functions and features."
repository = "https://github.com/lvandevelde/typst-minerva-thesis"
keywords = [
    "template",
    "thesis",
    "Ghent University",
    "Universiteit Gent",
    "UGent"
]
categories = [
    "model",
    "layout",
    "thesis",
]
compiler = "0.15.0"

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
