// This file was autogenerated. Please refer to the project README for instructions.

// The data contained in this file were retrieved from the NIST CODATA 2022 database.

// Eite Tiesinga, Peter J. Mohr, David B. Newell, and Barry N. Taylor (2024), "The 2022 CODATA
// Recommended Values of the Fundamental Physical Constants" (Web Version 9.0). Database developed
// by J. Baker, M. Douma, and S. Kotochigova. Available at https://physics.nist.gov/constants,
// National Institute of Standards and Technology, Gaithersburg, MD 20899.

#import "../common-packages.typ": *

#let avogadro-constant = (
  val: 6.02214076e+23,
  uncert: none,
  unit: "mol^-1",
  symbol: $N_upright(A)$,
  quantity: "Avogadro constant"
)
#let boltzmann-constant = (
  val: 1.380649e-23,
  uncert: none,
  unit: "J K^-1",
  symbol: $k$,
  quantity: "Boltzmann constant"
)
#let elementary-charge = (
  val: 1.602176634e-19,
  uncert: none,
  unit: "C",
  symbol: $e$,
  quantity: "elementary charge"
)
#let hyperfine-transition-frequency-of-cs133 = (
  val: 9192631770,
  uncert: none,
  unit: "Hz",
  symbol: $Delta nu_(upright(C) s)$,
  quantity: "hyperfine transition frequency of Cs-133"
)
#let luminous-efficacy = (
  val: 683,
  uncert: none,
  unit: "lm W^-1",
  symbol: $K_(upright(c) d)$,
  quantity: "luminous efficacy"
)
#let planck-constant = (
  val: 6.62607015e-34,
  uncert: none,
  unit: "J Hz^-1",
  symbol: $h$,
  quantity: "Planck constant"
)
#let reduced-planck-constant = (
  val: 1.054571817e-34,
  uncert: none,
  unit: "J s",
  symbol: $planck$,
  quantity: "reduced Planck constant"
)
#let speed-of-light-in-vacuum = (
  val: 299792458,
  uncert: none,
  unit: "m s^-1",
  symbol: $c$,
  quantity: "speed of light in vacuum"
)
#let standard-acceleration-of-gravity = (
  val: 9.80665,
  uncert: none,
  unit: "m s^-2",
  symbol: $g_upright(n)$,
  quantity: "standard acceleration of gravity"
)
#let standard-atmosphere = (
  val: 101325,
  uncert: none,
  unit: "Pa",
  symbol: $a t m$,
  quantity: "standard atmosphere"
)
#let standardstate-pressure = (
  val: 100000,
  uncert: none,
  unit: "Pa",
  symbol: $s s p$,
  quantity: "standard-state pressure"
)
