// This file was autogenerated. Please refer to the project README for instructions.

// The data contained in this file were retrieved from the NIST CODATA 2022 database.

// Eite Tiesinga, Peter J. Mohr, David B. Newell, and Barry N. Taylor (2024), "The 2022 CODATA
// Recommended Values of the Fundamental Physical Constants" (Web Version 9.0). Database developed
// by J. Baker, M. Douma, and S. Kotochigova. Available at https://physics.nist.gov/constants,
// National Institute of Standards and Technology, Gaithersburg, MD 20899.

#import "../common-packages.typ": *

#let atomic-mass-constant = (
  val: 1.66053906892e-27,
  uncert: 5.2e-37,
  unit: "kg",
  symbol: $m_upright(u)$,
  quantity: "atomic mass constant"
)
#let atomic-mass-constant-energy-equivalent = (
  val: 1.49241808768e-10,
  uncert: 4.6e-20,
  unit: "J",
  symbol: $m_upright(u) c^2$,
  quantity: "atomic mass constant energy equivalent"
)
#let atomic-mass-constant-energy-equivalent-in-mev = (
  val: 931.49410372,
  uncert: 2.9e-07,
  unit: " MeV",
  symbol: $m_upright(u) c^2$,
  quantity: "atomic mass constant energy equivalent in MeV"
)
#let avogadro-constant = (
  val: 6.02214076e+23,
  uncert: none,
  unit: "mol^-1",
  symbol: $N_upright(A)$,
  quantity: "Avogadro constant"
)
#let boltzmann-constant = (
  val: 1.380649e-23,
  uncert: none,
  unit: "J K^-1",
  symbol: $k$,
  quantity: "Boltzmann constant"
)
#let boltzmann-constant-in-ev-per-k = (
  val: 8.617333262e-05,
  uncert: none,
  unit: "eV K^-1",
  symbol: $k$,
  quantity: "Boltzmann constant in eV/K"
)
#let boltzmann-constant-in-hz-per-k = (
  val: 20836619120.0,
  uncert: none,
  unit: "Hz K^-1",
  symbol: $k \/ h$,
  quantity: "Boltzmann constant in Hz/K"
)
#let boltzmann-constant-in-inverse-meter-per-kelvin = (
  val: 69.50348004,
  uncert: none,
  unit: "m^-1 K^-1",
  symbol: $k \/ h c$,
  quantity: "Boltzmann constant in inverse meter per kelvin"
)
#let faraday-constant = (
  val: 96485.33212,
  uncert: none,
  unit: "C mol^-1",
  symbol: $F$,
  quantity: "Faraday constant"
)
#let first-radiation-constant = (
  val: 3.741771852e-16,
  uncert: none,
  unit: "W m^2",
  symbol: $c_1$,
  quantity: "first radiation constant"
)
#let first-radiation-constant-for-spectral-radiance = (
  val: 1.191042972e-16,
  uncert: none,
  unit: "W m^2 sr^-1",
  symbol: $c_(1 upright(L))$,
  quantity: "first radiation constant for spectral radiance"
)
#let loschmidt-constant-27315-k-100-kpa = (
  val: 2.651645804e+25,
  uncert: none,
  unit: "m^-3",
  symbol: $n_0$,
  quantity: "Loschmidt constant (273.15 K, 100 kPa)"
)
#let loschmidt-constant-27315-k-101325-kpa = (
  val: 2.686780111e+25,
  uncert: none,
  unit: "m^-3",
  symbol: $n_0$,
  quantity: "Loschmidt constant (273.15 K, 101.325 kPa)"
)
#let molar-gas-constant = (
  val: 8.314462618,
  uncert: none,
  unit: "J mol^-1 K^-1",
  symbol: $R$,
  quantity: "molar gas constant"
)
#let molar-mass-constant = (
  val: 0.00100000000105,
  uncert: 3.1e-13,
  unit: " kg mol^-1",
  symbol: $M_upright(u)$,
  quantity: "molar mass constant"
)
#let molar-mass-of-carbon12 = (
  val: 0.0120000000126,
  uncert: 3.7e-12,
  unit: " kg mol^-1",
  symbol: $M(attach(upright(C), tl: 12))$,
  quantity: "molar mass of carbon-12"
)
#let molar-planck-constant = (
  val: 3.990312712e-10,
  uncert: none,
  unit: "J Hz^-1 mol^-1",
  symbol: $N_upright(A) h$,
  quantity: "molar Planck constant"
)
#let molar-volume-of-ideal-gas-27315-k-100-kpa = (
  val: 0.02271095464,
  uncert: none,
  unit: "m^3 mol^-1",
  symbol: $V_upright(m)$,
  quantity: "molar volume of ideal gas (273.15 K, 100 kPa)"
)
#let molar-volume-of-ideal-gas-27315-k-101325-kpa = (
  val: 0.02241396954,
  uncert: none,
  unit: "m^3 mol^-1",
  symbol: $V_upright(m)$,
  quantity: "molar volume of ideal gas (273.15 K, 101.325 kPa)"
)
#let sackurtetrode-constant-1-k-100-kpa = (
  val: -1.15170753496,
  uncert: 4.7e-10,
  unit: "none",
  symbol: $S_0 \/ R$,
  quantity: "Sackur-Tetrode constant (1 K, 100 kPa)"
)
#let sackurtetrode-constant-1-k-101325-kpa = (
  val: -1.16487052149,
  uncert: 4.7e-10,
  unit: "none",
  symbol: $S_0 \/ R$,
  quantity: "Sackur-Tetrode constant (1 K, 101.325 kPa)"
)
#let second-radiation-constant = (
  val: 0.01438776877,
  uncert: none,
  unit: "m K",
  symbol: $c_2$,
  quantity: "second radiation constant"
)
#let stefanboltzmann-constant = (
  val: 5.670374419e-08,
  uncert: none,
  unit: "W m^-2 K^-4",
  symbol: $sigma$,
  quantity: "Stefan-Boltzmann constant"
)
#let wien-frequency-displacement-law-constant = (
  val: 58789257570.0,
  uncert: none,
  unit: "Hz K^-1",
  symbol: $b^prime$,
  quantity: "Wien frequency displacement law constant"
)
#let wien-wavelength-displacement-law-constant = (
  val: 0.002897771955,
  uncert: none,
  unit: "m K",
  symbol: $b$,
  quantity: "Wien wavelength displacement law constant"
)
