// This file was autogenerated. Please refer to the project README for instructions.

// The data contained in this file were retrieved from the NIST CODATA 2022 database.

// Eite Tiesinga, Peter J. Mohr, David B. Newell, and Barry N. Taylor (2024), "The 2022 CODATA
// Recommended Values of the Fundamental Physical Constants" (Web Version 9.0). Database developed
// by J. Baker, M. Douma, and S. Kotochigova. Available at https://physics.nist.gov/constants,
// National Institute of Standards and Technology, Gaithersburg, MD 20899.

#import "../common-packages.typ": *

#let characteristic-impedance-of-vacuum = (
  val: 376.730313412,
  uncert: 5.9e-08,
  unit: "ohm",
  symbol: $Z_0$,
  quantity: "characteristic impedance of vacuum"
)
#let newtonian-constant-of-gravitation = (
  val: 6.6743e-11,
  uncert: 1.5e-15,
  unit: "m^3 kg^-1 s^-2",
  symbol: $G$,
  quantity: "Newtonian constant of gravitation"
)
#let newtonian-constant-of-gravitation-over-hbar-c = (
  val: 6.70883e-39,
  uncert: 1.5e-43,
  unit: "(GeV/c^2)^-2",
  symbol: $G \/ planck c$,
  quantity: "Newtonian constant of gravitation over h-bar c"
)
#let planck-constant = (
  val: 6.62607015e-34,
  uncert: none,
  unit: "J Hz^-1",
  symbol: $h$,
  quantity: "Planck constant"
)
#let planck-constant-in-ev-per-hz = (
  val: 4.135667696e-15,
  uncert: none,
  unit: "eV Hz^-1",
  symbol: $h$,
  quantity: "Planck constant in eV/Hz"
)
#let planck-length = (
  val: 1.616255e-35,
  uncert: 1.8e-40,
  unit: " m",
  symbol: $l_upright(P)$,
  quantity: "Planck length"
)
#let planck-mass = (
  val: 2.176434e-08,
  uncert: 2.4e-13,
  unit: "kg",
  symbol: $m_upright(P)$,
  quantity: "Planck mass"
)
#let planck-mass-energy-equivalent-in-gev = (
  val: 1.22089e+19,
  uncert: 140000000000000.0,
  unit: "GeV",
  symbol: $m_upright(P) c^2$,
  quantity: "Planck mass energy equivalent in GeV"
)
#let planck-temperature = (
  val: 1.416784e+32,
  uncert: 1.6e+27,
  unit: "K",
  symbol: $T_upright(P)$,
  quantity: "Planck temperature"
)
#let planck-time = (
  val: 5.391247e-44,
  uncert: 6e-49,
  unit: " s",
  symbol: $t_upright(P)$,
  quantity: "Planck time"
)
#let reduced-planck-constant = (
  val: 1.054571817e-34,
  uncert: none,
  unit: "J s",
  symbol: $planck$,
  quantity: "reduced Planck constant"
)
#let reduced-planck-constant-in-ev-s = (
  val: 6.582119569e-16,
  uncert: none,
  unit: "eV s",
  symbol: $planck$,
  quantity: "reduced Planck constant in eV s"
)
#let reduced-planck-constant-times-c-in-mev-fm = (
  val: 197.3269804,
  uncert: none,
  unit: "MeV fm",
  symbol: $planck c$,
  quantity: "reduced Planck constant times c in MeV fm"
)
#let speed-of-light-in-vacuum = (
  val: 299792458,
  uncert: none,
  unit: "m s^-1",
  symbol: $c$,
  quantity: "speed of light in vacuum"
)
#let vacuum-electric-permittivity = (
  val: 8.8541878188e-12,
  uncert: 1.4e-21,
  unit: "F m^-1",
  symbol: $epsilon_0$,
  quantity: "vacuum electric permittivity"
)
