[package]
name = "unofficial-icl-doc-thesis"
version = "0.1.0"
entrypoint = "template.typ"
authors = ["bkmashiro <https://github.com/bkmashiro>"]
license = "MIT"
description = "Unofficial Typst port of the Imperial College London Department of Computing Individual Project LaTeX template."
repository = "https://github.com/bkmashiro/ic-individual-project-typst"
keywords = ["thesis", "imperial", "university", "template"]
categories = ["thesis"]
compiler = "0.11.0"
exclude = ["example.pdf", "build.sh", "build.ps1", "Makefile", ".github", "fonts/", "figures/IMPERIAL_I_*.svg", "main.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
