

// TODO: Can I automate capitalization? E.g. periods function should ensure uppercase
// (this should be done with a printfield style argument)

// TODO: Internationalize to other languages than English

// TODO: also include the short bibstring and let the user choose


/// The default bibstring table. A bibstring table maps a number of language-independent
/// identifiers to the strings that will be printed in the bibliography (see the
/// `bibstring` parameter of `format-reference`).
/// Modifying the
/// bibstring table can be useful if you want to localize your bibliography to a language
/// other than English, or if your bibliographic conventions differ from those of
/// the standard #biblatex style. For instance, to keep the reference style from
/// printing "In:" with a trailing colon, you could use a bibstring table in which
/// the "in" key maps to "In" rather than "In:".
/// 
/// This default bibstring table is a verbatim copy of the standard English bibstring
/// table in #biblatex. It contains only the "long" versions of these entries; so
/// references will be typeset to print e.g. "Jones, editor", rather than "Jones, ed.".
/// You can find this table in the file #link("https://github.com/alexanderkoller/pergamon/blob/main/src/bibstrings.typ")[bibstrings.typ]
/// and modify it to your needs.
#let default-bibstring = (
  // converted from english.lbx
  "bibliography": "Bibliography",
  "references": "References",
  "shorthands": "List of Abbreviations",
  "editor": "editor",
  "editors": "editors",
  "compiler": "compiler",
  "compilers": "compilers",
  "redactor": "redactor",
  "redactors": "redactors",
  "reviser": "reviser",
  "revisers": "revisers",
  "founder": "founder",
  "founders": "founders",
  "continuator": "continued",
  "continuators": "continued",
  "collaborator": "collaborator",
  "collaborators": "collaborators",
  "translator": "translator",
  "translators": "translators",
  "commentator": "commentator",
  "commentators": "commentators",
  "annotator": "annotator",
  "annotators": "annotators",
  "commentary": "commentary",
  "annotations": "annotations",
  "introduction": "introduction",
  "foreword": "foreword",
  "afterword": "afterword",
  "editortr": "editor and translator",
  "editorstr": "editors and translators",
  "editorco": "editor and commentator",
  "editorsco": "editors and commentators",
  "editoran": "editor and annotator",
  "editorsan": "editors and annotators",
  "editorin": "editor and introduction",
  "editorsin": "editors and introduction",
  "editorfo": "editor and foreword",
  "editorsfo": "editors and foreword",
  "editoraf": "editor and afterword",
  "editorsaf": "editors and afterword",
  "editortrco": "editor, translator, and commentator",
  "editorstrco": "editors, translators, and commentators",
  "editortran": "editor, translator, and annotator",
  "editorstran": "editors, translators, and annotators",
  "editortrin": "editor, translator, and introduction",
  "editorstrin": "editors, translators, and introduction",
  "editortrfo": "editor, translator, and foreword",
  "editorstrfo": "editors, translators, and foreword",
  "editortraf": "editor, translator, and afterword",
  "editorstraf": "editors, translators, and afterword",
  "editorcoin": "editor, commentator, and introduction",
  "editorscoin": "editors, commentators, and introduction",
  "editorcofo": "editor, commentator, and foreword",
  "editorscofo": "editors, commentators, and foreword",
  "editorcoaf": "editor, commentator, and afterword",
  "editorscoaf": "editors, commentators, and afterword",
  "editoranin": "editor, annotator, and introduction",
  "editorsanin": "editors, annotators, and introduction",
  "editoranfo": "editor, annotator, and foreword",
  "editorsanfo": "editors, annotators, and foreword",
  "editoranaf": "editor, annotator, and afterword",
  "editorsanaf": "editors, annotators, and afterword",
  "editortrcoin": "editor, translator, commentator, and introduction",
  "editorstrcoin": "editors, translators, commentators, and introduction",
  "editortrcofo": "editor, translator, commentator, and foreword",
  "editorstrcofo": "editors, translators, commentators, and foreword",
  "editortrcoaf": "editor, translator, commentator, and afterword",
  "editorstrcoaf": "editors, translators, commentators, and afterword",
  "editortranin": "editor, translator, annotator, and introduction",
  "editorstranin": "editors, translators, annotators, and introduction",
  "editortranfo": "editor, translator, annotator, and foreword",
  "editorstranfo": "editors, translators, annotators, and foreword",
  "editortranaf": "editor, translator, annotator, and afterword",
  "editorstranaf": "editors, translators, annotators, and afterword",
  "translatorco": "translator and commentator",
  "translatorsco": "translators and commentators",
  "translatoran": "translator and annotator",
  "translatorsan": "translators and annotators",
  "translatorin": "translation and introduction",
  "translatorsin": "translation and introduction",
  "translatorfo": "translation and foreword",
  "translatorsfo": "translation and foreword",
  "translatoraf": "translation and afterword",
  "translatorsaf": "translation and afterword",
  "translatorcoin": "translation, commentary, and introduction",
  "translatorscoin": "translation, commentary, and introduction",
  "translatorcofo": "translation, commentary, and foreword",
  "translatorscofo": "translation, commentary, and foreword",
  "translatorcoaf": "translation, commentary, and afterword",
  "translatorscoaf": "translation, commentary, and afterword",
  "translatoranin": "translation, annotations, and introduction",
  "translatorsanin": "translation, annotations, and introduction",
  "translatoranfo": "translation, annotations, and foreword",
  "translatorsanfo": "translation, annotations, and foreword",
  "translatoranaf": "translation, annotations, and afterword",
  "translatorsanaf": "translation, annotations, and afterword",
  "organizer": "organizer",
  "organizers": "organizers",
  "byorganizer": "organized by",
  "byauthor": "by",
  "byeditor": "Edited by",
  "bycompiler": "Compiled by",
  "byredactor": "Redacted by",
  "byreviser": "Revised by",
  "byreviewer": "Reviewed by",
  "byfounder": "Founded by",
  "bycontinuator": "Continued by",
  "bycollaborator": "in collaboration with",
  "bytranslator": "Translated (TODO: FROM LANGUAGE) by",
  "bycommentator": "Commented by",
  "byannotator": "Annotated by",
  "withcommentator": "With a commentary by",
  "withannotator": "With annotations by",
  "withintroduction": "With an introduction by",
  "withforeword": "With a foreword by",
  "withafterword": "With an afterword by",
  "byeditortr": "Edited and translated (TODO: FROM LANGUAGE) by",
  "byeditorco": "Edited and commented by",
  "byeditoran": "Edited and annotated by",
  "byeditorin": "edited, with an introduction, by",
  "byeditorfo": "edited, with a foreword, by",
  "byeditoraf": "edited, with an afterword, by",
  "byeditortrco": "edited, translated (TODO: FROM LANGUAGE), and commented by",
  "byeditortran": "edited, translated (TODO: FROM LANGUAGE), and annotated by",
  "byeditortrin": "edited and translated (TODO: FROM LANGUAGE), with an introduction, by",
  "byeditortrfo": "edited and translated (TODO: FROM LANGUAGE), with a foreword, by",
  "byeditortraf": "edited and translated (TODO: FROM LANGUAGE), with an afterword, by",
  "byeditorcoin": "edited and commented, with an introduction, by",
  "byeditorcofo": "edited and commented, with a foreword, by",
  "byeditorcoaf": "edited and commented, with an afterword, by",
  "byeditoranin": "edited and annotated, with an introduction, by",
  "byeditoranfo": "edited and annotated, with a foreword, by",
  "byeditoranaf": "edited and annotated, with an afterword, by",
  "byeditortrcoin": "edited, translated (TODO: FROM LANGUAGE), and commented, with an introduction, by",
  "byeditortrcofo": "edited, translated (TODO: FROM LANGUAGE), and commented, with a foreword, by",
  "byeditortrcoaf": "edited, translated (TODO: FROM LANGUAGE), and commented, with an afterword, by",
  "byeditortranin": "edited, translated (TODO: FROM LANGUAGE), and annotated, with an introduction, by",
  "byeditortranfo": "edited, translated (TODO: FROM LANGUAGE), and annotated, with a foreword, by",
  "byeditortranaf": "edited, translated (TODO: FROM LANGUAGE), and annotated, with an afterword, by",
  "bytranslatorco": "translated (TODO: FROM LANGUAGE) and commented by",
  "bytranslatoran": "translated (TODO: FROM LANGUAGE) and annotated by",
  "bytranslatorin": "translated (TODO: FROM LANGUAGE), with an introduction, by",
  "bytranslatorfo": "translated (TODO: FROM LANGUAGE), with a foreword, by",
  "bytranslatoraf": "translated (TODO: FROM LANGUAGE), with an afterword, by",
  "bytranslatorcoin": "translated (TODO: FROM LANGUAGE) and commented, with an introduction, by",
  "bytranslatorcofo": "translated (TODO: FROM LANGUAGE) and commented, with a foreword, by",
  "bytranslatorcoaf": "translated (TODO: FROM LANGUAGE) and commented, with an afterword, by",
  "bytranslatoranin": "translated (TODO: FROM LANGUAGE) and annotated, with an introduction, by",
  "bytranslatoranfo": "translated (TODO: FROM LANGUAGE) and annotated, with a foreword, by",
  "bytranslatoranaf": "translated (TODO: FROM LANGUAGE) and annotated, with an afterword, by",
  "and": "and",
  "andothers": "et al.",
  "andmore": "et al.",
  "volume": "Volume",
  "volumes": "volumes",
  "involumes": "In:",
  "jourvol": "volume",
  "jourser": "series",
  "book": "book",
  "part": "part",
  "issue": "issue",
  "newseries": "new series",
  "oldseries": "old series",
  "edition": "edition",
  "reprint": "reprint",
  "reprintof": "reprint of",
  "reprintas": "reprinted as",
  "reprintfrom": "reprinted from",
  "reviewof": "review of",
  "translationof": "translation of",
  "translationas": "translated as",
  "translationfrom": "translated from",
  "origpubas": "originally published as",
  "origpubin": "originally published in",
  "astitle": "as",
  "bypublisher": "by",
  "nodate": "n.d.", // was long version "no date"
  "page": "p.", // "page",
  "pages": "pp.", //"pages",
  "column": "column",
  "columns": "columns",
  "line": "line",
  "lines": "lines",
  "verse": "verse",
  "verses": "verses",
  "section": "section",
  "sections": "sections",
  "paragraph": "paragraph",
  "paragraphs": "paragraphs",
  "pagetotal": "page",
  "pagetotals": "pages",
  "columntotal": "column",
  "columntotals": "columns",
  "linetotal": "line",
  "linetotals": "lines",
  "versetotal": "verse",
  "versetotals": "verses",
  "sectiontotal": "section",
  "sectiontotals": "sections",
  "paragraphtotal": "paragraph",
  "paragraphtotals": "paragraphs",
  "in": "In:",
  "inseries": "in",
  "ofseries": "of",
  "number": "number",
  "chapter": "Chapter",
  "bathesis": "Bachelor's thesis",
  "mathesis": "Master's thesis",
  "phdthesis": "PhD thesis",
  "candthesis": "Candidate thesis",
  "resreport": "research report",
  "techreport": "technical report",
  "software": "computer software",
  "datacd": "CD-ROM",
  "audiocd": "audio CD",
  "version": "version",
  "url": "address",
  "urlfrom": "available from",
  "urlseen": "visited on",
  "inpreparation": "in preparation",
  "submitted": "submitted",
  "forthcoming": "forthcoming",
  "inpress": "in press",
  "prepublished": "pre-published",
  "citedas": "henceforth cited as",
  "thiscite": "especially",
  "seenote": "see note",
  "quotedin": "quoted in",
  "idem": "idem",
  "idemsm": "idem",
  "idemsf": "eadem",
  "idemsn": "idem",
  "idempm": "eidem",
  "idempf": "eaedem",
  "idempn": "eadem",
  "idempp": "eidem",
  "ibidem": "ibidem",
  "opcit": "op.space cit.",
  "loccit": "loc.space cit.",
  "confer": "cf.",
  "sequens": "sq.",
  "sequentes": "sqq.",
  "passim": "passim",
  "see": "see",
  "seealso": "see also",
  "backrefpage": "cited on page",
  "backrefpages": "cited on pages",
  "january": "January",
  "february": "February",
  "march": "March",
  "april": "April",
  "may": "May",
  "june": "June",
  "july": "July",
  "august": "August",
  "september": "September",
  "october": "October",
  "november": "November",
  "december": "December",
  "langamerican": "American",
  "langbasque": "Basque",
  "langbrazilian": "Brazilian",
  "langbulgarian": "Bulgarian",
  "langcatalan": "Catalan",
  "langcroatian": "Croatian",
  "langczech": "Czech",
  "langdanish": "Danish",
  "langdutch": "Dutch",
  "langenglish": "English",
  "langestonian": "Estonian",
  "langfinnish": "Finnish",
  "langfrench": "French",
  "langgalician": "Galician",
  "langgerman": "German",
  "langgreek": "Greek",
  "langhungarian": "Hungarian",
  "langitalian": "Italian",
  "langjapanese": "Japanese",
  "langlatin": "Latin",
  "langlatvian": "Latvian",
  "langlithuanian": "Lithuanian",
  "langmarathi": "Marathi",
  "langnorwegian": "Norwegian",
  "langpolish": "Polish",
  "langportuguese": "Portuguese",
  "langromanian": "Romanian",
  "langrussian": "Russian",
  "langserbian": "Serbian",
  "langslovak": "Slovak",
  "langslovene": "Slovene",
  "langspanish": "Spanish",
  "langswedish": "Swedish",
  "langturkish": "Turkish",
  "langukrainian": "Ukrainian",
  "fromamerican": "from the American",
  "frombasque": "from the Basque",
  "frombrazilian": "from the Brazilian",
  "frombulgarian": "from the Bulgarian",
  "fromcatalan": "from the Catalan",
  "fromcroatian": "from the Croatian",
  "fromczech": "from the Czech",
  "fromdanish": "from the Danish",
  "fromdutch": "from the Dutch",
  "fromenglish": "from the English",
  "fromestonian": "from the Estonian",
  "fromfinnish": "from the Finnish",
  "fromfrench": "from the French",
  "fromgalician": "from the Galician",
  "fromgerman": "from the German",
  "fromgreek": "from the Greek",
  "fromhungarian": "from the Hungarian",
  "fromitalian": "from the Italian",
  "fromjapanese": "from the Japanese",
  "fromlatin": "from the Latin",
  "fromlatvian": "from the Latvian",
  "fromlithuanian": "from the Lithuanian",
  "frommarathi": "from the Marathi",
  "fromnorwegian": "from the Norwegian",
  "frompolish": "from the Polish",
  "fromportuguese": "from the Portuguese",
  "fromromanian": "from the Romanian",
  "fromrussian": "from the Russian",
  "fromserbian": "from the Serbian",
  "fromslovak": "from the Slovak",
  "fromslovene": "from the Slovene",
  "fromspanish": "from the Spanish",
  "fromswedish": "from the Swedish",
  "fromturkish": "from the Turkish",
  "fromukrainian": "from the Ukrainian",
  "countryde": "Germany",
  "countryeu": "European Union",
  "countryep": "European Union",
  "countryfr": "France",
  "countryuk": "United Kingdom",
  "countryus": "United States of America",
  "patent": "patent",
  "patentde": "German patent",
  "patenteu": "European patent",
  "patentfr": "French patent",
  "patentuk": "British patent",
  "patentus": "U.S.space patent",
  "patreq": "patent request",
  "patreqde": "German patent request",
  "patreqeu": "European patent request",
  "patreqfr": "French patent request",
  "patrequk": "British patent request",
  "patrequs": "U.S.space patent request",
  "file": "file",
  "library": "library",
  "abstract": "abstract",
  "annotation": "annotations",
  "commonera": "Common Era",
  "beforecommonera": "Before Common Era",
  "annodomini": "Anno Domini",
  "beforechrist": "Before Christ",
  "circa": "circa",
  "spring": "Spring",
  "summer": "Summer",
  "autumn": "Autumn",
  "winter": "Winter",
  "springN": "Spring (Northern Hemisphere)",
  "summerN": "Summer (Northern Hemisphere)",
  "autumnN": "Autumn (Northern Hemisphere)",
  "winterN": "Winter (Northern Hemisphere)",
  "springS": "Spring (Southern Hemisphere)",
  "summerS": "Summer (Southern Hemisphere)",
  "autumnS": "Autumn (Southern Hemisphere)",
  "winterS": "Winter (Southern Hemisphere)",
  "Q1": "Quarter~1",
  "Q2": "Quarter~2",
  "Q3": "Quarter~3",
  "Q4": "Quarter~4",
  "QD1": "Quadrimester~1",
  "QD2": "Quadrimester~2",
  "QD3": "Quadrimester~3",
  "S1": "Semestral~1",
  "S2": "Semestral~2",
  "am": "AM",
  "pm": "PM",
)



// hand-written:
// #let default-bibstring = (
//   "editor": "Ed.",
//   "editors": "Eds.",
//   "translator": "translator",
//   "translators": "translators",
//   "in": "In:",
//   "volume": "Volume",
//   "byeditor": "Edited by",
//   "bytranslator": "Translated by",
//   "withcommentator": "With a commentary by",
//   "withannotator": "With annotations by",
//   "withintroduction": "With an introduction by",
//   "withforeword": "With a foreword by",
//   "withafterword": "With an afterword by",
//   "edition": "edition", // e.g. 3rd edition
//   "chapter": "Chapter",  // e.g. Chapter 3
//   "jourser": "series", // e.g. third series
//   "urlseen": "visited on",
//   "version": "version",
//   "volumes": "volumes"
// )
