[package]
name = "ornacover"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Naam Mohamed"]
license = "MIT"
description = "Ornamental covers package for Typst educational documents"
repository = "https://github.com/naam11/ornacover"

[dependencies]
cetz = "0.5.2"

