#let author-first-name = "Имя Отчество"
#let thesis-author-initials = "И.О."
#let author-last-name = "Фамилия"
#let author-name = author-last-name+" "+author-first-name
#let author-short = author-last-name+" "+thesis-author-initials
#let thesis-title = "Длинное-длинное название диссертации из достаточно большого количества сложных и непонятных слов"
#let thesis-udk = "xxx.xxx" // Диссертация, УДК
#let thesis-specialty-number = "XX.XX.XX"
#let thesis-specialty-title = "Название специальности"
#let thesis-degree = "кандидата физико-математических наук"
#let thesis-degree-short = "канд. физ.-мат. наук"
#let thesis-city = "Город"
#let thesis-year = datetime.today().year()
#let thesis-organization = [Федеральное государственное автономное образовательное учреждение высшего образования "Длинное название образовательного учреждения \ "АББРЕВИАТУРА"]
#let thesis-in-organization = "учреждении с длинным длинным длинным длинным названием, в котором выполнялась данная диссертационная работа" // в предложном падеже 
#let thesis-organization-short = "Сокращенное название организации"
#let supervisor-fio = "Фамилия Имя Отчество" // Научный руководитель, ФИО
#let supervisor-regalia = "уч. степень, уч. звание"
#let supervisor-fio-short = "И.О. Фамилия"
#let supervisor-regalia-short = "уч. ст., уч. зв."
#let opponent-one-fio = "Фамилия Имя Отчество"
#let opponent-one-regalia = "доктор физико-математических наук, профессор"
#let opponent-one-job-place = "Не очень длинное название для места работы"
#let opponent-one-job-post = "старший научный сотрудник"
#let opponent-two-fio = "Фамилия Имя Отчество"
#let opponent-two-regalia = "доктор физико-математических наук, профессор"
#let opponent-two-job-place = "Не очень длинное название для места работы"
#let opponent-two-job-post = "старший научный сотрудник"
#let leading-organization-title = "Федеральное государственное бюджетное образовательное учреждение высшего профессионального образования с длинным длинным длинным длинным названием" // Ведущая организация, дополнительные строки. Удалить, чтобы не отображать в автореферате
#let defense-date = "DD mmmmmmmm YYYY г. в XX часов" // % Защита дата
#let defense-council-number = "Д ,123.456.78" // Защита, номер диссертационного совета
#let defense-cuncil-title = "Название учреждения" // Защита, учреждение диссертационного совета
#let defense-council-addres = "Адрес" // Защита, адрес учреждение диссертационного совета
#let defense-council-phone = "+7 (0000) 00-00-00" // Телефон для справок
#let defense-secretary-fio = "Фамилия Имя Отчество" // Секретарь диссертационного совета, ФИО
#let defense-secretary-regalia = "д-р физ.-мат. наук" // Для сокращений есть ГОСТы, например: ГОСТ Р 7.0.12-2011 + http://base.garant.ru/179724/#block_30000
#let synopsis-library = "Название библиотеки" // Автореферат, название библиотеки
#let synopsis-date = "DD mmmmmmmm yyyy года" // Автореферат, дата рассылки