[package]
name = "campanile"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Joshua You <@buggy213>"]
license = "MIT-0"
description = "Master's thesis and PhD dissertation at UC Berkeley (Unofficial)"
keywords = ["ucbthesis", "Berkeley"]
categories = ["thesis"]
repository = "" # todo add

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"