[package]
name = "na-arabox"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Naam Mohamed"]
license = "MIT"
description = "A customized box for Arabic content with professional styling / حزمة لإنشاء صناديق مخصصة تدعم الكتابة باللغة العربية"
