[package]
name = "slr-parser"
version = "0.0.1"
entrypoint = "src/vis.typ"
authors = ["Lucas Ramos"]
license = "MIT"
description = "A typst template to visualize SLR parser steps."
homepage = "https://github.com/lukinhasram/slr-visualizer"
repository = "https://github.com/lukinhasram/slr-visualizer"
compiler = "0.15.0"
categories = ["components", "visualization"]
disciplines = ["computer-science", "mathematics", "education", "linguistics"]
keywords = ["parser", "slr", "grammar", "compiler", "AST"]
exclude = ["README.md", "docs", "example.typ", "example.pdf"]