#import "@preview/scribe:0.2.0": *
#show: scribe.with("operations", "miscellaneous", "relations", "grouping-brackets", "logicals", "caligraphics")

// vanilla
#let v(body) = {
  set text(gray)
  show: it => [ *#it*]
  [ #body ]
}

#let operations = (
  v(`+`),$+$,
  v(`-`),$-$,
  `*`,$*$,
  `**`,$**$,
  `***`,$***$,
  `\\`,$\\$,
  `//`,[],
  `xx`,$xx$,
  `-:`,$-:$,
  `|><`,$|><$,
  `><|`,$><|$,
  `|><|`,$|><|$,
  `@`,$@$,
  `o+`,$o+$,
  `ox`,$ox$,
  `o.`,$o.$,
  v(`sum`),$sum$,
  `prod`,$prod$,
  `^^`,[],
  `^^^`,[],
  `vv`,$vv$,
  `vvv`,$vvv$,
  `nn`,$nn$,
  `nnn`,$nnn$,
  `uu`,$uu$,
  `uuu`,$uuu$,
)

#let miscellaneous = (
  v(`2/3`), $2/3$,
  v(`2^3`), $2^3$,
  v(`sqrt(x)`), $sqrt(x)$,
  v(`root(3,x)`), $root(3,x)$,
  `int`, $int$,
  v(`oint`), $oint$,
  `del`, $del$,
  `grad`, $grad$,
  `+-`, $+-$,
  `O/`, [],
  v(`oo`), $oo$,
  `aleph`, $aleph$,
  `:.`, $:.$,
  `:'`, $:'$,
  `|ldots|`, $|ldots|$,
  `vdots`, $vdots$,
  `ddots`, $ddots$,
  v(`|\|`), $|\|$,
  v(`|quad|`), $|quad|$,
  `/_`, [],
  `frown`, [],
  `/_\`, [],
  v(`diamond`), $diamond$,
  v(`square`), $square$,
  `|__`, [],
  `__|`, [],
  `|~`, $|~$,
  `~|`, $~|$,
  v(`CC`), $CC$,
  v(`NN`), $NN$,
  v(`QQ`), $QQ$,
  v(`RR`), $RR$,
  v(`ZZ`), $ZZ$,
  v(`"hi"`), $"hi"$,
)

#let relations = (
  v(`=`), $=$,
  v(`!=`), $!=$,
  v(`<`), $<$,
  v(`>`), $>$,
  v(`<=`), $<=$,
  `m ll`, $m ll$,
  `m gg`, $m gg$,
  `-<`, $-<$,
  `-<=`, $-<=$,
  `>-`, $>-$,
  `>-=`, $>-=$,
  v(`in`), $in$,
  `!in`, [],
  `!in`, [],
  `sub`, $sub$,
  `sup`, $sup$,
  `sube`, $sube$,
  `sup`, $supe$,
  `-=`, $-=$,
  `~=`, $~=$,
  `~~`, $~~$,
  v(`prop`), $prop$,
)

#let grouping-brackets = (
  v(`(`), $($,
  v(`)`), $)$,
  v(`[`), $[$,
  v(`]`), $]$,
  v(`{`), ${$,
  v(`}`), $}$,
  `(:`, $(:$,
  `:)`, $:)$,
  `<<`, $<<$,
  `>>`, $>>$,
  `{:x)`, [],
  `(x:}`, [],
  v(`abs(x)`), $abs(x)$,
  v(`floor(x)`), $floor(x)$,
  v(`ceil(x)`), $ceil(x)$,
  v(`norm(x)`), $norm(x)$,
)

#let logicals = (
  v(`and`), $and$,
  v(`or`), $or$,
  v(`not`), $not$,
  v(`=>`), $=>$,
  `if`, [],
  v(`<=>`), $<=>$,
  `AA`, $AA$,
  `EE`, $EE$,
  `_|_`, [],
  `TT`, $TT$,
  `|--`, $|--$,
  `|==`, $|==$,

)

#let caligraphics = (
`Aa`, $Aa$, 
`Bb`, $Bb$,
`Cc`, $Cc$,
`Dd`, $Dd$,
`Ee`, $Ee$,
`Ff`, $Ff$,
`Gg`, $Gg$,
`Hh`, $Hh$,
`Ii`, $Ii$,
`Jj`, $Jj$,
`Kk`, $Kk$,
`Ll`, $Ll$,
`Mm`, $Mm$,
`Nn`, $Nn$,
`Oo`, $Oo$,
`Pp`, $Pp$,
`Qq`, $Qq$,
`Rr`, $Rr$,
`Ss`, $Ss$,
`Tt`, $Tt$,
`Uu`, $Uu$,
`Vv`, $Vv$,
`Ww`, $Ww$,
`Xx`, $Xx$,
`Yy`, $Yy$,
`Zz`, $Zz$,
`aA`, $aA$,
`bB`, $bB$,
`cC`, $cC$,
`dD`, $dD$,
`eE`, $eE$,
`fF`, $fF$,
`gG`, $gG$,
`hH`, $hH$,
`iI`, $iI$,
`jJ`, $jJ$,
`kK`, $kK$,
`lL`, $lL$,
`mM`, $mM$,
`nN`, $nN$,
`oO`, $oO$,
`pP`, $pP$,
`qQ`, $qQ$,
`rR`, $rR$,
`sS`, $sS$,
`tT`, $tT$,
`uU`, $uU$,
`vV`, $vV$,
`wW`, $wW$,
`xX`, $xX$,
`yY`, $yY$,
`zZ`, $zZ$,
)


#set page(footer: [Grayed symbols are available in vanilla typst and only included for completeness.])

#show figure: set block(breakable: true)
#show: columns.with(4, gutter: 1%)
#context{
  figure(table(
    columns: ( auto, auto),
    inset: 10pt,
    align: horizon,
    table.cell(colspan: 2, [*OPERATIONS*]), 
    ..operations,
    table.cell(colspan: 2, [*MISC SYMBOLS*]), 
    ..miscellaneous,
    table.cell(colspan: 2, [*RELATIONS*]), 
    ..relations,
    table.cell(colspan: 2, [*BRACKETS*]), 
    ..grouping-brackets,
    table.cell(colspan: 2, [*LOGICALS*]), 
    ..logicals,
    table.cell(colspan: 2, [*CALIGRAPHICS*]), 
    ..caligraphics
    )
  )
}
