// Colors
#let __ucpc_color_named = (
  brown: (
    rgb("#9d4900"),
    rgb("#a54f00"),
    rgb("#ad5600"),
    rgb("#b55d0a"),
    rgb("#c67739"),
  ),
  bluegray: (
    rgb("#38546e"),
    rgb("#3d5a74"),
    rgb("#435f7a"),
    rgb("#496580"),
    rgb("#4e6a86"),
  ),
  yellow: (
    rgb("#d28500"),
    rgb("#df8f00"),
    rgb("#ec9a00"),
    rgb("#f9a518"),
    rgb("#ffb028"),
  ),
  cyan: (
    rgb("#00c78b"),
    rgb("#00d497"),
    rgb("#27e2a4"),
    rgb("#3ef0b1"),
    rgb("#51fdbd"),
  ),
  skyblue: (
    rgb("#009ee5"),
    rgb("#00a9f0"),
    rgb("#00b4fc"),
    rgb("#2bbfff"),
    rgb("#41caff"),
  ),
  cherry: (
    rgb("#e0004c"),
    rgb("#ea0053"),
    rgb("#f5005a"),
    rgb("#ff0062"),
    rgb("#ff3071"),
  ),
)
#let color = (
  brown: __ucpc_color_named.brown,
  bluegray: __ucpc_color_named.bluegray,
  yellow: __ucpc_color_named.yellow,
  cyan: __ucpc_color_named.cyan,
  skyblue: __ucpc_color_named.skyblue,
  cherry: __ucpc_color_named.cherry,
  bronze: (
    V: __ucpc_color_named.brown.at(0),
    IV: __ucpc_color_named.brown.at(1),
    III: __ucpc_color_named.brown.at(2),
    II: __ucpc_color_named.brown.at(3),
    I: __ucpc_color_named.brown.at(4),
  ),
  silver: (
    V: __ucpc_color_named.bluegray.at(0),
    IV: __ucpc_color_named.bluegray.at(1),
    III: __ucpc_color_named.bluegray.at(2),
    II: __ucpc_color_named.bluegray.at(3),
    I: __ucpc_color_named.bluegray.at(4),
  ),
  gold: (
    V: __ucpc_color_named.yellow.at(0),
    IV: __ucpc_color_named.yellow.at(1),
    III: __ucpc_color_named.yellow.at(2),
    II: __ucpc_color_named.yellow.at(3),
    I: __ucpc_color_named.yellow.at(4),
  ),
  platinum: (
    V: __ucpc_color_named.cyan.at(0),
    IV: __ucpc_color_named.cyan.at(1),
    III: __ucpc_color_named.cyan.at(2),
    II: __ucpc_color_named.cyan.at(3),
    I: __ucpc_color_named.cyan.at(4),
  ),
  diamond: (
    V: __ucpc_color_named.skyblue.at(0),
    IV: __ucpc_color_named.skyblue.at(1),
    III: __ucpc_color_named.skyblue.at(2),
    II: __ucpc_color_named.skyblue.at(3),
    I: __ucpc_color_named.skyblue.at(4),
  ),
  ruby: (
    V: __ucpc_color_named.cherry.at(0),
    IV: __ucpc_color_named.cherry.at(1),
    III: __ucpc_color_named.cherry.at(2),
    II: __ucpc_color_named.cherry.at(3),
    I: __ucpc_color_named.cherry.at(4),
  ),
  misc: (
    ghudegy: rgb("#8769af"),
    unrated: rgb("#2d2d2d"),
  ),
)
