
#pdf.embed(
  "use-of-ai.typ",
  relationship: "source",
  mime-type: "text/vnd.typst",
  description: "The Typst source code for the front matter section describing how AI was used in producing this work.",
)

I hereby declare, that the AI-based applications used in generating this work are as follows:

#table(
	align: left,
	columns : (70%,30%),
	table.header(
		[*Application*],
		[*Version*]
	),
	[...],
	[...],
	[...],
	[...],
)

== Purpose of the use of AI

Explain here _in detail_, for which purpose and how AI was utilized in writing this thesis.

== Parts of this work,  where AI was used

List here all chapters, sections, subsections, tables, figures and so forth,
that were generated by an AI, or that an AI had a hand in generating.
