[package]
name = "parcio-slides"
version = "0.2.0"
entrypoint = "src/parcio.typ"
authors = ["Kevin Kulot <@xkevio>", "Luke <@AdmiralLuke>", "Ruben Felgenhauer <@felsenhower>", "ParCIO"]
license = "0BSD"
description = "A simple polylux slide template for the ParCIO working group at OvGU Magdeburg."
repository = "https://github.com/parcio/templates"
categories = ["presentation", "thesis"]
keywords = ["presentation", "slides", "polylux", "thesis", "university", "OvGU", "Magdeburg", "Otto von Guericke Universität"]
compiler = "0.15.0"
exclude = ["thumbnails"]

[template]
path = "template"
entrypoint = "slides.typ"
thumbnail = "thumbnails/p-01.png"
