#import "dataset.typ": make-dataset

#let make-latent-space(
  title,
  subtitle: none,
  legend: none,
  legend-position: "below",
  width: 0.7,
  height: 3.2,
  pos: none,
  after: none,
  gap: 1.0,
  y: none,
  color: rgb("#fcd97a"),
  title-size: 0.54em,
  subtitle-size: 0.46em,
  legend-size: 0.44em,
  wrap-lines: 2,
  title-truncate: false,
  max-title-chars: 18,
  title-position: "below",
  image-spacing: 0.0,
) = {
  make-dataset(
    title,
    subtitle: subtitle,
    legend: legend,
    legend-position: legend-position,
    images: 1,
    image-size: (width, height),
    image-spacing: image-spacing,
    title-truncate: title-truncate,
    max-title-chars: max-title-chars,
    title-position: title-position,
    pos: pos,
    after: after,
    gap: gap,
    y: y,
    color: color,
    title-size: title-size,
    subtitle-size: subtitle-size,
    legend-size: legend-size,
    wrap-lines: wrap-lines,
  )
}
