// This file was autogenerated. Please refer to the project README for instructions.

#import "../common_packages.typ": *

#let characteristic_impedance_of_vacuum = (val: 376.730313412, uncert: 5.9e-08, unit: "ohm", symbol: " $Z_0$ ", quantity: "characteristic impedance of vacuum")
#let newtonian_constant_of_gravitation = (val: 6.6743e-11, uncert: 1.5e-15, unit: "m^3 kg^-1 s^-2", symbol: " $ G $ ", quantity: "Newtonian constant of gravitation")
#let newtonian_constant_of_gravitation_over_h-bar_c = (val: 6.70883e-39, uncert: 1.5e-43, unit: "(GeV/c^2)^-2", symbol: " $ G/\hbar c $ ", quantity: "Newtonian constant of gravitation over h-bar c")
#let planck_constant = (val: 6.62607015e-34, uncert: none, unit: "J Hz^-1", symbol: " $ h $ ", quantity: "Planck constant")
#let planck_constant_in_ev_per_hz = (val: 4.135667696e-15, uncert: none, unit: "eV Hz^-1", symbol: " $ h $ ", quantity: "Planck constant in eV/Hz")
#let planck_length = (val: 1.616255e-35, uncert: 1.8e-40, unit: " m", symbol: " $l_{\rm P}$ ", quantity: "Planck length")
#let planck_mass = (val: 2.176434e-08, uncert: 2.4e-13, unit: "kg", symbol: " $m_{\rm P}$ ", quantity: "Planck mass")
#let planck_mass_energy_equivalent_in_gev = (val: 1.22089e+19, uncert: 140000000000000.0, unit: "GeV", symbol: " $m_{\rm P}c^2$ ", quantity: "Planck mass energy equivalent in GeV")
#let planck_temperature = (val: 1.416784e+32, uncert: 1.6e+27, unit: "K", symbol: " $T_{\rm P}$ ", quantity: "Planck temperature")
#let planck_time = (val: 5.391247e-44, uncert: 6e-49, unit: " s", symbol: " $t_{\rm P}$ ", quantity: "Planck time")
#let reduced_planck_constant = (val: 1.054571817e-34, uncert: none, unit: "J s", symbol: " $\hbar$ ", quantity: "reduced Planck constant")
#let reduced_planck_constant_in_ev_s = (val: 6.582119569e-16, uncert: none, unit: "eV s", symbol: " $\hbar$ ", quantity: "reduced Planck constant in eV s")
#let reduced_planck_constant_times_c_in_mev_fm = (val: 197.3269804, uncert: none, unit: "MeV fm", symbol: " $ \hbar c $ ", quantity: "reduced Planck constant times c in MeV fm")
#let speed_of_light_in_vacuum = (val: 299792458, uncert: none, unit: "m s^-1", symbol: " $c$ ", quantity: "speed of light in vacuum")
#let vacuum_electric_permittivity = (val: 8.8541878188e-12, uncert: 1.4e-21, unit: "F m^-1", symbol: " $\varepsilon_0$ ", quantity: "vacuum electric permittivity")
