// This file was autogenerated. Please refer to the project README for instructions.

#import "../common_packages.typ": *

#let angstrom_star = (val: 1.00001495e-10, uncert: 9e-17, unit: "m", symbol: " \AA$^{\ast}$ ", quantity: "Angstrom star")
#let copper_x_unit = (val: 1.00207697e-13, uncert: 2.8e-20, unit: "m", symbol: " ${\rm xu}({\rm CuK}\alpha_{\rm 1})$ ", quantity: "Copper x unit")
#let lattice_parameter_of_silicon = (val: 5.431020511e-10, uncert: 8.9e-18, unit: " m", symbol: " $a$ ", quantity: "lattice parameter of silicon")
#let lattice_spacing_of_ideal_si_220 = (val: 1.920155716e-10, uncert: 3.2e-18, unit: " m", symbol: " $d_{220}$ ", quantity: "lattice spacing of ideal Si (220)")
#let molar_volume_of_silicon = (val: 1.205883199e-05, uncert: 6e-13, unit: "m^3 mol^-1", symbol: " $V_{\rm m}$(Si) ", quantity: "molar volume of silicon")
#let molybdenum_x_unit = (val: 1.00209952e-13, uncert: 5.3e-20, unit: "m", symbol: " ${\rm xu}({\rm MoK}\alpha_{\rm 1})$ ", quantity: "Molybdenum x unit")
