// citrus - Locale Data
//
// Auto-generated by scripts/generate-locales.py
// DO NOT EDIT MANUALLY - edit the generator script instead.

// =============================================================================
// Import All Locales
// =============================================================================

#import "af-ZA.typ": locale as _af-ZA
#import "ar.typ": locale as _ar
#import "bal-PK.typ": locale as _bal-PK
#import "bg-BG.typ": locale as _bg-BG
#import "brh-PK.typ": locale as _brh-PK
#import "ca-AD.typ": locale as _ca-AD
#import "cs-CZ.typ": locale as _cs-CZ
#import "cy-GB.typ": locale as _cy-GB
#import "da-DK.typ": locale as _da-DK
#import "de-AT.typ": locale as _de-AT
#import "de-CH.typ": locale as _de-CH
#import "de-DE.typ": locale as _de-DE
#import "el-GR.typ": locale as _el-GR
#import "en-GB.typ": locale as _en-GB
#import "en-US.typ": locale as _en-US
#import "es-CL.typ": locale as _es-CL
#import "es-ES.typ": locale as _es-ES
#import "es-MX.typ": locale as _es-MX
#import "et-EE.typ": locale as _et-EE
#import "eu.typ": locale as _eu
#import "fa-IR.typ": locale as _fa-IR
#import "fi-FI.typ": locale as _fi-FI
#import "fr-CA.typ": locale as _fr-CA
#import "fr-FR.typ": locale as _fr-FR
#import "gl-ES.typ": locale as _gl-ES
#import "he-IL.typ": locale as _he-IL
#import "hi-IN.typ": locale as _hi-IN
#import "hr-HR.typ": locale as _hr-HR
#import "hu-HU.typ": locale as _hu-HU
#import "id-ID.typ": locale as _id-ID
#import "is-IS.typ": locale as _is-IS
#import "it-IT.typ": locale as _it-IT
#import "ja-JP.typ": locale as _ja-JP
#import "km-KH.typ": locale as _km-KH
#import "ko-KR.typ": locale as _ko-KR
#import "la.typ": locale as _la
#import "lij-IT.typ": locale as _lij-IT
#import "lt-LT.typ": locale as _lt-LT
#import "lv-LV.typ": locale as _lv-LV
#import "mn-MN.typ": locale as _mn-MN
#import "ms-MY.typ": locale as _ms-MY
#import "nb-NO.typ": locale as _nb-NO
#import "nl-NL.typ": locale as _nl-NL
#import "nn-NO.typ": locale as _nn-NO
#import "pa-PK.typ": locale as _pa-PK
#import "pl-PL.typ": locale as _pl-PL
#import "pt-BR.typ": locale as _pt-BR
#import "pt-PT.typ": locale as _pt-PT
#import "ro-RO.typ": locale as _ro-RO
#import "ru-RU.typ": locale as _ru-RU
#import "sk-SK.typ": locale as _sk-SK
#import "sl-SI.typ": locale as _sl-SI
#import "sr-Cyrl-RS.typ": locale as _sr-Cyrl-RS
#import "sr-Latn-RS.typ": locale as _sr-Latn-RS
#import "sv-SE.typ": locale as _sv-SE
#import "th-TH.typ": locale as _th-TH
#import "tr-TR.typ": locale as _tr-TR
#import "uk-UA.typ": locale as _uk-UA
#import "vi-VN.typ": locale as _vi-VN
#import "zh-CN.typ": locale as _zh-CN
#import "zh-TW.typ": locale as _zh-TW

// =============================================================================
// Built-in Locale Registry
// =============================================================================

#let _builtin-locales = (
  "af-ZA": _af-ZA,
  "ar": _ar,
  "bal-PK": _bal-PK,
  "bg-BG": _bg-BG,
  "brh-PK": _brh-PK,
  "ca-AD": _ca-AD,
  "cs-CZ": _cs-CZ,
  "cy-GB": _cy-GB,
  "da-DK": _da-DK,
  "de-AT": _de-AT,
  "de-CH": _de-CH,
  "de-DE": _de-DE,
  "el-GR": _el-GR,
  "en-GB": _en-GB,
  "en-US": _en-US,
  "es-CL": _es-CL,
  "es-ES": _es-ES,
  "es-MX": _es-MX,
  "et-EE": _et-EE,
  "eu": _eu,
  "fa-IR": _fa-IR,
  "fi-FI": _fi-FI,
  "fr-CA": _fr-CA,
  "fr-FR": _fr-FR,
  "gl-ES": _gl-ES,
  "he-IL": _he-IL,
  "hi-IN": _hi-IN,
  "hr-HR": _hr-HR,
  "hu-HU": _hu-HU,
  "id-ID": _id-ID,
  "is-IS": _is-IS,
  "it-IT": _it-IT,
  "ja-JP": _ja-JP,
  "km-KH": _km-KH,
  "ko-KR": _ko-KR,
  "la": _la,
  "lij-IT": _lij-IT,
  "lt-LT": _lt-LT,
  "lv-LV": _lv-LV,
  "mn-MN": _mn-MN,
  "ms-MY": _ms-MY,
  "nb-NO": _nb-NO,
  "nl-NL": _nl-NL,
  "nn-NO": _nn-NO,
  "pa-PK": _pa-PK,
  "pl-PL": _pl-PL,
  "pt-BR": _pt-BR,
  "pt-PT": _pt-PT,
  "ro-RO": _ro-RO,
  "ru-RU": _ru-RU,
  "sk-SK": _sk-SK,
  "sl-SI": _sl-SI,
  "sr-Cyrl-RS": _sr-Cyrl-RS,
  "sr-Latn-RS": _sr-Latn-RS,
  "sv-SE": _sv-SE,
  "th-TH": _th-TH,
  "tr-TR": _tr-TR,
  "uk-UA": _uk-UA,
  "vi-VN": _vi-VN,
  "zh-CN": _zh-CN,
  "zh-TW": _zh-TW,
  "kh-KH": _km-KH,
)

// =============================================================================
// Language Detection Data
// =============================================================================

// Language name to code mappings
#let _language-name-map = (
  "afrikaans": "af",
  "arabic": "ar",
  "balochi": "bal",
  "basque": "eu",
  "brahui": "brh",
  "bulgarian": "bg",
  "catalan": "ca",
  "chinese": "zh",
  "croatian": "hr",
  "czech": "cs",
  "danish": "da",
  "dutch": "nl",
  "english": "en",
  "estonian": "et",
  "finnish": "fi",
  "french": "fr",
  "galician": "gl",
  "german": "de",
  "greek": "el",
  "hebrew": "he",
  "hindi": "hi",
  "hungarian": "hu",
  "icelandic": "is",
  "indonesian": "id",
  "italian": "it",
  "japanese": "ja",
  "khmer": "km",
  "korean": "ko",
  "latin": "la",
  "latvian": "lv",
  "ligurian": "lij",
  "lithuanian": "lt",
  "malay": "ms",
  "mongolian": "mn",
  "norwegian bokmål": "nb",
  "norwegian nynorsk": "nn",
  "persian": "fa",
  "polish": "pl",
  "portuguese": "pt",
  "punjabi": "pa",
  "romanian": "ro",
  "russian": "ru",
  "serbian": "sr",
  "slovak": "sk",
  "slovenian": "sl",
  "spanish": "es",
  "swedish": "sv",
  "thai": "th",
  "turkish": "tr",
  "ukrainian": "uk",
  "vietnamese": "vi",
  "welsh": "cy",
)

// Language code prefixes for detection
#let _language-code-prefixes = (
  "af",
  "ar",
  "bal",
  "bg",
  "brh",
  "ca",
  "cs",
  "cy",
  "da",
  "de",
  "el",
  "en",
  "es",
  "et",
  "eu",
  "fa",
  "fi",
  "fr",
  "gl",
  "he",
  "hi",
  "hr",
  "hu",
  "id",
  "is",
  "it",
  "ja",
  "km",
  "ko",
  "la",
  "lij",
  "lt",
  "lv",
  "mn",
  "ms",
  "nb",
  "nl",
  "nn",
  "pa",
  "pl",
  "pt",
  "ro",
  "ru",
  "sk",
  "sl",
  "sr",
  "sv",
  "th",
  "tr",
  "uk",
  "vi",
  "zh",
)

// =============================================================================
// Language Family Mappings
// =============================================================================

/// Language family mappings for fallback (prefix -> default locale)
#let _language-family-map = (
  "af": "af-ZA",
  "ar": "ar",
  "bal": "bal-PK",
  "bg": "bg-BG",
  "brh": "brh-PK",
  "ca": "ca-AD",
  "cs": "cs-CZ",
  "cy": "cy-GB",
  "da": "da-DK",
  "de": "de-DE",
  "el": "el-GR",
  "en": "en-US",
  "es": "es-ES",
  "et": "et-EE",
  "eu": "eu",
  "fa": "fa-IR",
  "fi": "fi-FI",
  "fr": "fr-FR",
  "gl": "gl-ES",
  "he": "he-IL",
  "hi": "hi-IN",
  "hr": "hr-HR",
  "hu": "hu-HU",
  "id": "id-ID",
  "is": "is-IS",
  "it": "it-IT",
  "ja": "ja-JP",
  "km": "km-KH",
  "ko": "ko-KR",
  "la": "la",
  "lij": "lij-IT",
  "lt": "lt-LT",
  "lv": "lv-LV",
  "mn": "mn-MN",
  "ms": "ms-MY",
  "nb": "nb-NO",
  "nl": "nl-NL",
  "nn": "nn-NO",
  "pa": "pa-PK",
  "pl": "pl-PL",
  "pt": "pt-BR",
  "ro": "ro-RO",
  "ru": "ru-RU",
  "sk": "sk-SK",
  "sl": "sl-SI",
  "sr": "sr-Latn-RS",
  "sv": "sv-SE",
  "th": "th-TH",
  "tr": "tr-TR",
  "uk": "uk-UA",
  "vi": "vi-VN",
  "zh": "zh-CN",
  "kh": "km-KH",
)
