[package]
name = "telecom-paris-report"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Arsene MALLET <@arsnm>"]
license = "Unlicense"
description = "Unofficial Télécom Paris report template."
exclude = ["tests/", "thumbnail.png"]
repository = "https://github.com/arsnm/typstelecom-paris-report"
keywords = [
    "telecom-paris", "report", "télécom", "academic", "university", "ip-paris"
]
categories = ["report", "layout"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
