#import "fontawesome.typ": *

#let title = "Typst-FontAwesome"

#set page(
    paper: "a4",
      header: [
        #set text(6pt)
      ],
    numbering: "1 / 1"
)
#set heading(
  level: 2,
  numbering: "1.",
)
#set par(
  justify: true,
  leading: 1em,
  linebreaks: "optimized"
)
#set block(above: 1em, below: 0.5em)

#align(center, text(18pt)[
    *#title*
])

#outline(
   title: [],
   indent: auto
)

#pagebreak()

= Brands
<Brands>

== A-C

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [brand-42-group], [#fa("brand-42-group")],
    [brand-500px], [#fa("brand-500px")],
    [brand-accessible-icon], [#fa("brand-accessible-icon")],
    [brand-accusoft], [#fa("brand-accusoft")],
    [brand-adn], [#fa("brand-adn")],
    [brand-adversal], [#fa("brand-adversal")],
    [brand-affiliatetheme], [#fa("brand-affiliatetheme")],
    [brand-airbnb], [#fa("brand-airbnb")],
    [brand-algolia], [#fa("brand-algolia")],
    [brand-alipay], [#fa("brand-alipay")],
    [brand-amazon-pay], [#fa("brand-amazon-pay")],
    [brand-amazon], [#fa("brand-amazon")],
    [brand-amilia], [#fa("brand-amilia")],
    [brand-android], [#fa("brand-android")],
    [brand-angellist], [#fa("brand-angellist")],
    [brand-angrycreative], [#fa("brand-angrycreative")],
    [brand-angular], [#fa("brand-angular")],
    [brand-app-store-ios], [#fa("brand-app-store-ios")],
    [brand-app-store], [#fa("brand-app-store")],
    [brand-apper], [#fa("brand-apper")],
    [brand-apple-pay], [#fa("brand-apple-pay")],
    [brand-apple], [#fa("brand-apple")],
    [brand-artstation], [#fa("brand-artstation")],
    [brand-asymmetrik], [#fa("brand-asymmetrik")],
    [brand-atlassian], [#fa("brand-atlassian")],
    [brand-audible], [#fa("brand-audible")],
    [brand-autoprefixer], [#fa("brand-autoprefixer")],
    [brand-avianex], [#fa("brand-avianex")],
    [brand-aviato], [#fa("brand-aviato")],
    [brand-aws], [#fa("brand-aws")],
    [brand-bandcamp], [#fa("brand-bandcamp")],
    [brand-battle-net], [#fa("brand-battle-net")],
    [brand-behance], [#fa("brand-behance")],
    [brand-bilibili], [#fa("brand-bilibili")],
    [brand-bimobject], [#fa("brand-bimobject")],
    [brand-bitbucket], [#fa("brand-bitbucket")],
    [brand-bitcoin], [#fa("brand-bitcoin")],
    [brand-bity], [#fa("brand-bity")],
    [brand-black-tie], [#fa("brand-black-tie")],
    [brand-blackberry], [#fa("brand-blackberry")],
    [brand-blogger-b], [#fa("brand-blogger-b")],
    [brand-blogger], [#fa("brand-blogger")],
    [brand-bluetooth-b], [#fa("brand-bluetooth-b")],
    [brand-bluetooth], [#fa("brand-bluetooth")],
    [brand-bootstrap], [#fa("brand-bootstrap")],
    [brand-bots], [#fa("brand-bots")],
    [brand-btc], [#fa("brand-btc")],
    [brand-buffer], [#fa("brand-buffer")],
    [brand-buromobelexperte], [#fa("brand-buromobelexperte")],
    [brand-buy-n-large], [#fa("brand-buy-n-large")],
    [brand-buysellads], [#fa("brand-buysellads")],
    [brand-canadian-maple-leaf], [#fa("brand-canadian-maple-leaf")],
    [brand-cc-amazon-pay], [#fa("brand-cc-amazon-pay")],
    [brand-cc-amex], [#fa("brand-cc-amex")],
    [brand-cc-apple-pay], [#fa("brand-cc-apple-pay")],
    [brand-cc-diners-club], [#fa("brand-cc-diners-club")],
    [brand-cc-discover], [#fa("brand-cc-discover")],
    [brand-cc-jcb], [#fa("brand-cc-jcb")],
    [brand-cc-mastercard], [#fa("brand-cc-mastercard")],
    [brand-cc-paypal], [#fa("brand-cc-paypal")],
    [brand-cc-stripe], [#fa("brand-cc-stripe")],
    [brand-cc-visa], [#fa("brand-cc-visa")],
    [brand-centercode], [#fa("brand-centercode")],
    [brand-centos], [#fa("brand-centos")],
    [brand-chrome], [#fa("brand-chrome")],
    [brand-chromecast], [#fa("brand-chromecast")],
    [brand-cloudflare], [#fa("brand-cloudflare")],
    [brand-cloudscale], [#fa("brand-cloudscale")],
    [brand-cloudsmith], [#fa("brand-cloudsmith")],
    [brand-cloudversify], [#fa("brand-cloudversify")],
    [brand-cmplid], [#fa("brand-cmplid")],
    [brand-codepen], [#fa("brand-codepen")],
    [brand-codiepie], [#fa("brand-codiepie")],
    [brand-confluence], [#fa("brand-confluence")],
    [brand-connectdevelop], [#fa("brand-connectdevelop")],
    [brand-contao], [#fa("brand-contao")],
    [brand-cotton-bureau], [#fa("brand-cotton-bureau")],
    [brand-cpanel], [#fa("brand-cpanel")],
    [brand-critical-role], [#fa("brand-critical-role")],
    [brand-css3-alt], [#fa("brand-css3-alt")],
    [brand-css3], [#fa("brand-css3")],
    [brand-cuttlefish], [#fa("brand-cuttlefish")],
)])

#pagebreak(weak: true)

=== Creative

#figure(
align(center)[#table(
    columns: 4,
    align: center,
    [brand-creative-commons-by], [#fa("brand-creative-commons-by")],
    [brand-creative-commons-nc-eu], [#fa("brand-creative-commons-nc-eu")],
    [brand-creative-commons-nc-jp], [#fa("brand-creative-commons-nc-jp")],
    [brand-creative-commons-nc], [#fa("brand-creative-commons-nc")],
    [brand-creative-commons-nd], [#fa("brand-creative-commons-nd")],
    [brand-creative-commons-pd-alt], [#fa("brand-creative-commons-pd-alt")],
    [brand-creative-commons-pd], [#fa("brand-creative-commons-pd")],
    [brand-creative-commons-remix], [#fa("brand-creative-commons-remix")],
    [brand-creative-commons-sa], [#fa("brand-creative-commons-sa")],
    [brand-creative-commons-sampling-plus], [#fa("brand-creative-commons-sampling-plus")],
    [brand-creative-commons-sampling], [#fa("brand-creative-commons-sampling")],
    [brand-creative-commons-share], [#fa("brand-creative-commons-share")],
    [brand-creative-commons-zero], [#fa("brand-creative-commons-zero")],
    [brand-creative-commons], [#fa("brand-creative-commons")],
)])

== D-F

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [brand-d-and-d-beyond], [#fa("brand-d-and-d-beyond")],
    [brand-d-and-d], [#fa("brand-d-and-d")],
    [brand-dailymotion], [#fa("brand-dailymotion")],
    [brand-dashcube], [#fa("brand-dashcube")],
    [brand-debian], [#fa("brand-debian")],
    [brand-deezer], [#fa("brand-deezer")],
    [brand-delicious], [#fa("brand-delicious")],
    [brand-deploydog], [#fa("brand-deploydog")],
    [brand-deskpro], [#fa("brand-deskpro")],
    [brand-dev], [#fa("brand-dev")],
    [brand-deviantart], [#fa("brand-deviantart")],
    [brand-dhl], [#fa("brand-dhl")],
    [brand-diaspora], [#fa("brand-diaspora")],
    [brand-digg], [#fa("brand-digg")],
    [brand-digital-ocean], [#fa("brand-digital-ocean")],
    [brand-discord], [#fa("brand-discord")],
    [brand-discourse], [#fa("brand-discourse")],
    [brand-dochub], [#fa("brand-dochub")],
    [brand-docker], [#fa("brand-docker")],
    [brand-draft2digital], [#fa("brand-draft2digital")],
    [brand-dribbble], [#fa("brand-dribbble")],
    [brand-dropbox], [#fa("brand-dropbox")],
    [brand-drupal], [#fa("brand-drupal")],
    [brand-dyalog], [#fa("brand-dyalog")],
    [brand-earlybirds], [#fa("brand-earlybirds")],
    [brand-ebay], [#fa("brand-ebay")],
    [brand-edge-legacy], [#fa("brand-edge-legacy")],
    [brand-edge], [#fa("brand-edge")],
    [brand-elementor], [#fa("brand-elementor")],
    [brand-ello], [#fa("brand-ello")],
    [brand-ember], [#fa("brand-ember")],
    [brand-empire], [#fa("brand-empire")],
    [brand-envira], [#fa("brand-envira")],
    [brand-erlang], [#fa("brand-erlang")],
    [brand-ethereum], [#fa("brand-ethereum")],
    [brand-etsy], [#fa("brand-etsy")],
    [brand-evernote], [#fa("brand-evernote")],
    [brand-expeditedssl], [#fa("brand-expeditedssl")],
    [brand-facebook-f], [#fa("brand-facebook-f")],
    [brand-facebook-messenger], [#fa("brand-facebook-messenger")],
    [brand-facebook], [#fa("brand-facebook")],
    [brand-fantasy-flight-games], [#fa("brand-fantasy-flight-games")],
    [brand-fedex], [#fa("brand-fedex")],
    [brand-fedora], [#fa("brand-fedora")],
    [brand-figma], [#fa("brand-figma")],
    [brand-firefox-browser], [#fa("brand-firefox-browser")],
    [brand-firefox], [#fa("brand-firefox")],
    [brand-first-order-alt], [#fa("brand-first-order-alt")],
    [brand-first-order], [#fa("brand-first-order")],
    [brand-firstdraft], [#fa("brand-firstdraft")],
    [brand-flickr], [#fa("brand-flickr")],
    [brand-flipboard], [#fa("brand-flipboard")],
    [brand-fly], [#fa("brand-fly")],
    [brand-font-awesome], [#fa("brand-font-awesome")],
    [brand-fonticons-fi], [#fa("brand-fonticons-fi")],
    [brand-fonticons], [#fa("brand-fonticons")],
    [brand-fort-awesome-alt], [#fa("brand-fort-awesome-alt")],
    [brand-fort-awesome], [#fa("brand-fort-awesome")],
    [brand-forumbee], [#fa("brand-forumbee")],
    [brand-foursquare], [#fa("brand-foursquare")],
    [brand-free-code-camp], [#fa("brand-free-code-camp")],
    [brand-freebsd], [#fa("brand-freebsd")],
    [brand-fulcrum], [#fa("brand-fulcrum")],
)])

== G-I

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [brand-galactic-republic], [#fa("brand-galactic-republic")],
    [brand-galactic-senate], [#fa("brand-galactic-senate")],
    [brand-get-pocket], [#fa("brand-get-pocket")],
    [brand-gg-circle], [#fa("brand-gg-circle")],
    [brand-gg], [#fa("brand-gg")],
    [brand-git-alt], [#fa("brand-git-alt")],
    [brand-git], [#fa("brand-git")],
    [brand-github-alt], [#fa("brand-github-alt")],
    [brand-github], [#fa("brand-github")],
    [brand-gitkraken], [#fa("brand-gitkraken")],
    [brand-gitlab], [#fa("brand-gitlab")],
    [brand-gitter], [#fa("brand-gitter")],
    [brand-glide-g], [#fa("brand-glide-g")],
    [brand-glide], [#fa("brand-glide")],
    [brand-gofore], [#fa("brand-gofore")],
    [brand-golang], [#fa("brand-golang")],
    [brand-goodreads-g], [#fa("brand-goodreads-g")],
    [brand-goodreads], [#fa("brand-goodreads")],
    [brand-google-drive], [#fa("brand-google-drive")],
    [brand-google-pay], [#fa("brand-google-pay")],
    [brand-google-play], [#fa("brand-google-play")],
    [brand-google-plus-g], [#fa("brand-google-plus-g")],
    [brand-google-plus], [#fa("brand-google-plus")],
    [brand-google-wallet], [#fa("brand-google-wallet")],
    [brand-google], [#fa("brand-google")],
    [brand-gratipay], [#fa("brand-gratipay")],
    [brand-grav], [#fa("brand-grav")],
    [brand-gripfire], [#fa("brand-gripfire")],
    [brand-grunt], [#fa("brand-grunt")],
    [brand-guilded], [#fa("brand-guilded")],
    [brand-gulp], [#fa("brand-gulp")],
    [brand-hacker-news], [#fa("brand-hacker-news")],
    [brand-hackerrank], [#fa("brand-hackerrank")],
    [brand-hashnode], [#fa("brand-hashnode")],
    [brand-hips], [#fa("brand-hips")],
    [brand-hire-a-helper], [#fa("brand-hire-a-helper")],
    [brand-hive], [#fa("brand-hive")],
    [brand-hooli], [#fa("brand-hooli")],
    [brand-hornbill], [#fa("brand-hornbill")],
    [brand-hotjar], [#fa("brand-hotjar")],
    [brand-houzz], [#fa("brand-houzz")],
    [brand-html5], [#fa("brand-html5")],
    [brand-hubspot], [#fa("brand-hubspot")],
    [brand-ideal], [#fa("brand-ideal")],
    [brand-imdb], [#fa("brand-imdb")],
    [brand-instagram], [#fa("brand-instagram")],
    [brand-instalod], [#fa("brand-instalod")],
    [brand-intercom], [#fa("brand-intercom")],
    [brand-internet-explorer], [#fa("brand-internet-explorer")],
    [brand-invision], [#fa("brand-invision")],
    [brand-ioxhost], [#fa("brand-ioxhost")],
    [brand-itch-io], [#fa("brand-itch-io")],
    [brand-itunes-note], [#fa("brand-itunes-note")],
    [brand-itunes], [#fa("brand-itunes")],
    [brand-java], [#fa("brand-java")],
    [brand-jedi-order], [#fa("brand-jedi-order")],
    [brand-jenkins], [#fa("brand-jenkins")],
    [brand-jira], [#fa("brand-jira")],
    [brand-joget], [#fa("brand-joget")],
    [brand-joomla], [#fa("brand-joomla")],
    [brand-js], [#fa("brand-js")],
    [brand-jsfiddle], [#fa("brand-jsfiddle")],
    [brand-kaggle], [#fa("brand-kaggle")],
    [brand-keybase], [#fa("brand-keybase")],
    [brand-keycdn], [#fa("brand-keycdn")],
    [brand-kickstarter-k], [#fa("brand-kickstarter-k")],
    [brand-kickstarter], [#fa("brand-kickstarter")],
    [brand-korvue], [#fa("brand-korvue")],
    [brand-laravel], [#fa("brand-laravel")],
    [brand-lastfm], [#fa("brand-lastfm")],
    [brand-leanpub], [#fa("brand-leanpub")],
    [brand-less], [#fa("brand-less")],
    [brand-line], [#fa("brand-line")],
    [brand-linkedin-in], [#fa("brand-linkedin-in")],
    [brand-linkedin], [#fa("brand-linkedin")],
    [brand-linode], [#fa("brand-linode")],
    [brand-linux], [#fa("brand-linux")],
    [brand-lyft], [#fa("brand-lyft")],
)])

#pagebreak()

== M-R

#figure(
align(center)[#table(
    columns: 6,
    [brand-magento], [#fa("brand-magento")],
    [brand-mailchimp], [#fa("brand-mailchimp")],
    [brand-mandalorian], [#fa("brand-mandalorian")],
    [brand-markdown], [#fa("brand-markdown")],
    [brand-mastodon], [#fa("brand-mastodon")],
    [brand-maxcdn], [#fa("brand-maxcdn")],
    [brand-mdb], [#fa("brand-mdb")],
    [brand-medapps], [#fa("brand-medapps")],
    [brand-medium], [#fa("brand-medium")],
    [brand-medrt], [#fa("brand-medrt")],
    [brand-meetup], [#fa("brand-meetup")],
    [brand-megaport], [#fa("brand-megaport")],
    [brand-mendeley], [#fa("brand-mendeley")],
    [brand-meta], [#fa("brand-meta")],
    [brand-microblog], [#fa("brand-microblog")],
    [brand-microsoft], [#fa("brand-microsoft")],
    [brand-mix], [#fa("brand-mix")],
    [brand-mixcloud], [#fa("brand-mixcloud")],
    [brand-mixer], [#fa("brand-mixer")],
    [brand-mizuni], [#fa("brand-mizuni")],
    [brand-modx], [#fa("brand-modx")],
    [brand-monero], [#fa("brand-monero")],
    [brand-napster], [#fa("brand-napster")],
    [brand-neos], [#fa("brand-neos")],
    [brand-nfc-directional], [#fa("brand-nfc-directional")],
    [brand-nfc-symbol], [#fa("brand-nfc-symbol")],
    [brand-nimblr], [#fa("brand-nimblr")],
    [brand-node-js], [#fa("brand-node-js")],
    [brand-node], [#fa("brand-node")],
    [brand-npm], [#fa("brand-npm")],
    [brand-ns8], [#fa("brand-ns8")],
    [brand-nutritionix], [#fa("brand-nutritionix")],
    [brand-octopus-deploy], [#fa("brand-octopus-deploy")],
    [brand-odnoklassniki], [#fa("brand-odnoklassniki")],
    [brand-odysee], [#fa("brand-odysee")],
    [brand-old-republic], [#fa("brand-old-republic")],
    [brand-opencart], [#fa("brand-opencart")],
    [brand-openid], [#fa("brand-openid")],
    [brand-opera], [#fa("brand-opera")],
    [brand-optin-monster], [#fa("brand-optin-monster")],
    [brand-orcid], [#fa("brand-orcid")],
    [brand-osi], [#fa("brand-osi")],
    [brand-padlet], [#fa("brand-padlet")],
    [brand-page4], [#fa("brand-page4")],
    [brand-pagelines], [#fa("brand-pagelines")],
    [brand-palfed], [#fa("brand-palfed")],
    [brand-patreon], [#fa("brand-patreon")],
    [brand-paypal], [#fa("brand-paypal")],
    [brand-perbyte], [#fa("brand-perbyte")],
    [brand-periscope], [#fa("brand-periscope")],
    [brand-phabricator], [#fa("brand-phabricator")],
    [brand-phoenix-framework], [#fa("brand-phoenix-framework")],
    [brand-phoenix-squadron], [#fa("brand-phoenix-squadron")],
    [brand-php], [#fa("brand-php")],
    [brand-pied-piper-alt], [#fa("brand-pied-piper-alt")],
    [brand-pied-piper-hat], [#fa("brand-pied-piper-hat")],
    [brand-pied-piper-pp], [#fa("brand-pied-piper-pp")],
    [brand-pied-piper], [#fa("brand-pied-piper")],
    [brand-pinterest-p], [#fa("brand-pinterest-p")],
    [brand-pinterest], [#fa("brand-pinterest")],
    [brand-pix], [#fa("brand-pix")],
    [brand-playstation], [#fa("brand-playstation")],
    [brand-product-hunt], [#fa("brand-product-hunt")],
    [brand-pushed], [#fa("brand-pushed")],
    [brand-python], [#fa("brand-python")],
    [brand-qq], [#fa("brand-qq")],
    [brand-quinscape], [#fa("brand-quinscape")],
    [brand-quora], [#fa("brand-quora")],
    [brand-r-project], [#fa("brand-r-project")],
    [brand-raspberry-pi], [#fa("brand-raspberry-pi")],
    [brand-ravelry], [#fa("brand-ravelry")],
    [brand-react], [#fa("brand-react")],
    [brand-reacteurope], [#fa("brand-reacteurope")],
    [brand-readme], [#fa("brand-readme")],
    [brand-rebel], [#fa("brand-rebel")],
    [brand-red-river], [#fa("brand-red-river")],
    [brand-reddit-alien], [#fa("brand-reddit-alien")],
    [brand-reddit], [#fa("brand-reddit")],
    [brand-redhat], [#fa("brand-redhat")],
    [brand-renren], [#fa("brand-renren")],
    [brand-replyd], [#fa("brand-replyd")],
    [brand-researchgate], [#fa("brand-researchgate")],
    [brand-resolving], [#fa("brand-resolving")],
    [brand-rev], [#fa("brand-rev")],
    [brand-rocketchat], [#fa("brand-rocketchat")],
    [brand-rockrms], [#fa("brand-rockrms")],
    [brand-rust], [#fa("brand-rust")],
)])

#pagebreak()

== S-V

#figure(
align(center)[#table(
    columns: 6,
    [brand-safari], [#fa("brand-safari")],
    [brand-salesforce], [#fa("brand-salesforce")],
    [brand-sass], [#fa("brand-sass")],
    [brand-schlix], [#fa("brand-schlix")],
    [brand-screenpal], [#fa("brand-screenpal")],
    [brand-scribd], [#fa("brand-scribd")],
    [brand-searchengin], [#fa("brand-searchengin")],
    [brand-sellcast], [#fa("brand-sellcast")],
    [brand-sellsy], [#fa("brand-sellsy")],
    [brand-servicestack], [#fa("brand-servicestack")],
    [brand-shirtsinbulk], [#fa("brand-shirtsinbulk")],
    [brand-shopify], [#fa("brand-shopify")],
    [brand-shopware], [#fa("brand-shopware")],
    [brand-simplybuilt], [#fa("brand-simplybuilt")],
    [brand-sistrix], [#fa("brand-sistrix")],
    [brand-sith], [#fa("brand-sith")],
    [brand-sitrox], [#fa("brand-sitrox")],
    [brand-sketch], [#fa("brand-sketch")],
    [brand-skyatlas], [#fa("brand-skyatlas")],
    [brand-skype], [#fa("brand-skype")],
    [brand-slack], [#fa("brand-slack")],
    [brand-slideshare], [#fa("brand-slideshare")],
    [brand-snapchat], [#fa("brand-snapchat")],
    [brand-soundcloud], [#fa("brand-soundcloud")],
    [brand-sourcetree], [#fa("brand-sourcetree")],
    [brand-space-awesome], [#fa("brand-space-awesome")],
    [brand-speakap], [#fa("brand-speakap")],
    [brand-speaker-deck], [#fa("brand-speaker-deck")],
    [brand-spotify], [#fa("brand-spotify")],
    [brand-stack-exchange], [#fa("brand-stack-exchange")],
    [brand-stack-overflow], [#fa("brand-stack-overflow")],
    [brand-stackpath], [#fa("brand-stackpath")],
    [brand-staylinked], [#fa("brand-staylinked")],
    [brand-steam-symbol], [#fa("brand-steam-symbol")],
    [brand-steam], [#fa("brand-steam")],
    [brand-sticker-mule], [#fa("brand-sticker-mule")],
    [brand-strava], [#fa("brand-strava")],
    [brand-stripe-s], [#fa("brand-stripe-s")],
    [brand-stripe], [#fa("brand-stripe")],
    [brand-stubber], [#fa("brand-stubber")],
    [brand-studiovinari], [#fa("brand-studiovinari")],
    [brand-stumbleupon-circle], [#fa("brand-stumbleupon-circle")],
    [brand-stumbleupon], [#fa("brand-stumbleupon")],
    [brand-superpowers], [#fa("brand-superpowers")],
    [brand-supple], [#fa("brand-supple")],
    [brand-suse], [#fa("brand-suse")],
    [brand-swift], [#fa("brand-swift")],
    [brand-symfony], [#fa("brand-symfony")],
    [brand-teamspeak], [#fa("brand-teamspeak")],
    [brand-telegram], [#fa("brand-telegram")],
    [brand-tencent-weibo], [#fa("brand-tencent-weibo")],
    [brand-the-red-yeti], [#fa("brand-the-red-yeti")],
    [brand-themeco], [#fa("brand-themeco")],
    [brand-themeisle], [#fa("brand-themeisle")],
    [brand-think-peaks], [#fa("brand-think-peaks")],
    [brand-threads], [#fa("brand-threads")],
    [brand-tiktok], [#fa("brand-tiktok")],
    [brand-trade-federation], [#fa("brand-trade-federation")],
    [brand-trello], [#fa("brand-trello")],
    [brand-tumblr], [#fa("brand-tumblr")],
    [brand-twitch], [#fa("brand-twitch")],
    [brand-twitter], [#fa("brand-twitter")],
    [brand-typo3], [#fa("brand-typo3")],
    [brand-uber], [#fa("brand-uber")],
    [brand-ubuntu], [#fa("brand-ubuntu")],
    [brand-uikit], [#fa("brand-uikit")],
    [brand-umbraco], [#fa("brand-umbraco")],
    [brand-uncharted], [#fa("brand-uncharted")],
    [brand-uniregistry], [#fa("brand-uniregistry")],
    [brand-unity], [#fa("brand-unity")],
    [brand-unsplash], [#fa("brand-unsplash")],
    [brand-untappd], [#fa("brand-untappd")],
    [brand-ups], [#fa("brand-ups")],
    [brand-usb], [#fa("brand-usb")],
    [brand-usps], [#fa("brand-usps")],
    [brand-ussunnah], [#fa("brand-ussunnah")],
    [brand-vaadin], [#fa("brand-vaadin")],
    [brand-viacoin], [#fa("brand-viacoin")],
    [brand-viadeo], [#fa("brand-viadeo")],
    [brand-viber], [#fa("brand-viber")],
    [brand-vimeo-v], [#fa("brand-vimeo-v")],
    [brand-vimeo], [#fa("brand-vimeo")],
    [brand-vine], [#fa("brand-vine")],
    [brand-vk], [#fa("brand-vk")],
    [brand-vnv], [#fa("brand-vnv")],
    [brand-vuejs], [#fa("brand-vuejs")],
)])

#pagebreak()

=== Square

#figure(
align(center)[#table(
    columns: 4,
    [brand-square-behance], [#fa("brand-square-behance")],
    [brand-square-dribbble], [#fa("brand-square-dribbble")],
    [brand-square-facebook], [#fa("brand-square-facebook")],
    [brand-square-font-awesome-stroke], [#fa("brand-square-font-awesome-stroke")],
    [brand-square-font-awesome], [#fa("brand-square-font-awesome")],
    [brand-square-git], [#fa("brand-square-git")],
    [brand-square-github], [#fa("brand-square-github")],
    [brand-square-gitlab], [#fa("brand-square-gitlab")],
    [brand-square-google-plus], [#fa("brand-square-google-plus")],
    [brand-square-hacker-news], [#fa("brand-square-hacker-news")],
    [brand-square-instagram], [#fa("brand-square-instagram")],
    [brand-square-js], [#fa("brand-square-js")],
    [brand-square-lastfm], [#fa("brand-square-lastfm")],
    [brand-square-odnoklassniki], [#fa("brand-square-odnoklassniki")],
    [brand-square-pied-piper], [#fa("brand-square-pied-piper")],
    [brand-square-pinterest], [#fa("brand-square-pinterest")],
    [brand-square-reddit], [#fa("brand-square-reddit")],
    [brand-square-snapchat], [#fa("brand-square-snapchat")],
    [brand-square-steam], [#fa("brand-square-steam")],
    [brand-square-threads], [#fa("brand-square-threads")],
    [brand-square-tumblr], [#fa("brand-square-tumblr")],
    [brand-square-twitter], [#fa("brand-square-twitter")],
    [brand-square-viadeo], [#fa("brand-square-viadeo")],
    [brand-square-vimeo], [#fa("brand-square-vimeo")],
    [brand-square-whatsapp], [#fa("brand-square-whatsapp")],
    [brand-square-x-twitter], [#fa("brand-square-x-twitter")],
    [brand-square-xing], [#fa("brand-square-xing")],
    [brand-square-youtube], [#fa("brand-square-youtube")],
    [brand-squarespace], [#fa("brand-squarespace")],
)])

== W-Z

#figure(
align(center)[#table(
    columns: 6,
    [brand-watchman-monitoring], [#fa("brand-watchman-monitoring")],
    [brand-waze], [#fa("brand-waze")],
    [brand-weebly], [#fa("brand-weebly")],
    [brand-weibo], [#fa("brand-weibo")],
    [brand-weixin], [#fa("brand-weixin")],
    [brand-whatsapp], [#fa("brand-whatsapp")],
    [brand-whmcs], [#fa("brand-whmcs")],
    [brand-wikipedia-w], [#fa("brand-wikipedia-w")],
    [brand-windows], [#fa("brand-windows")],
    [brand-wirsindhandwerk], [#fa("brand-wirsindhandwerk")],
    [brand-wix], [#fa("brand-wix")],
    [brand-wizards-of-the-coast], [#fa("brand-wizards-of-the-coast")],
    [brand-wodu], [#fa("brand-wodu")],
    [brand-wolf-pack-battalion], [#fa("brand-wolf-pack-battalion")],
    [brand-wordpress-simple], [#fa("brand-wordpress-simple")],
    [brand-wordpress], [#fa("brand-wordpress")],
    [brand-wpbeginner], [#fa("brand-wpbeginner")],
    [brand-wpexplorer], [#fa("brand-wpexplorer")],
    [brand-wpforms], [#fa("brand-wpforms")],
    [brand-wpressr], [#fa("brand-wpressr")],
    [brand-x-twitter], [#fa("brand-x-twitter")],
    [brand-xbox], [#fa("brand-xbox")],
    [brand-xing], [#fa("brand-xing")],
    [brand-y-combinator], [#fa("brand-y-combinator")],
    [brand-yahoo], [#fa("brand-yahoo")],
    [brand-yammer], [#fa("brand-yammer")],
    [brand-yandex-international], [#fa("brand-yandex-international")],
    [brand-yandex], [#fa("brand-yandex")],
    [brand-yarn], [#fa("brand-yarn")],
    [brand-yelp], [#fa("brand-yelp")],
    [brand-yoast], [#fa("brand-yoast")],
    [brand-youtube], [#fa("brand-youtube")],
    [brand-zhihu], [#fa("brand-zhihu")],
)])

#pagebreak()

= Regular
<Regular>

== A-E

#figure(
align(center)[#table(
    columns: 6,
    align: center,
    [reg-address-book], [#fa("reg-address-book")],
    [reg-address-card], [#fa("reg-address-card")],
    [reg-bell-slash], [#fa("reg-bell-slash")],
    [reg-bell], [#fa("reg-bell")],
    [reg-bookmark], [#fa("reg-bookmark")],
    [reg-building], [#fa("reg-building")],
    [reg-calendar-check], [#fa("reg-calendar-check")],
    [reg-calendar-days], [#fa("reg-calendar-days")],
    [reg-calendar-minus], [#fa("reg-calendar-minus")],
    [reg-calendar-plus], [#fa("reg-calendar-plus")],
    [reg-calendar-xmark], [#fa("reg-calendar-xmark")],
    [reg-calendar], [#fa("reg-calendar")],
    [reg-chart-bar], [#fa("reg-chart-bar")],
    [reg-chess-bishop], [#fa("reg-chess-bishop")],
    [reg-chess-king], [#fa("reg-chess-king")],
    [reg-chess-knight], [#fa("reg-chess-knight")],
    [reg-chess-pawn], [#fa("reg-chess-pawn")],
    [reg-chess-queen], [#fa("reg-chess-queen")],
    [reg-chess-rook], [#fa("reg-chess-rook")],
    [reg-circle-check], [#fa("reg-circle-check")],
    [reg-circle-dot], [#fa("reg-circle-dot")],
    [reg-circle-down], [#fa("reg-circle-down")],
    [reg-circle-left], [#fa("reg-circle-left")],
    [reg-circle-pause], [#fa("reg-circle-pause")],
    [reg-circle-play], [#fa("reg-circle-play")],
    [reg-circle-question], [#fa("reg-circle-question")],
    [reg-circle-right], [#fa("reg-circle-right")],
    [reg-circle-stop], [#fa("reg-circle-stop")],
    [reg-circle-up], [#fa("reg-circle-up")],
    [reg-circle-user], [#fa("reg-circle-user")],
    [reg-circle-xmark], [#fa("reg-circle-xmark")],
    [reg-circle], [#fa("reg-circle")],
    [reg-clipboard], [#fa("reg-clipboard")],
    [reg-clock], [#fa("reg-clock")],
    [reg-clone], [#fa("reg-clone")],
    [reg-closed-captioning], [#fa("reg-closed-captioning")],
    [reg-comment-dots], [#fa("reg-comment-dots")],
    [reg-comment], [#fa("reg-comment")],
    [reg-comments], [#fa("reg-comments")],
    [reg-compass], [#fa("reg-compass")],
    [reg-copy], [#fa("reg-copy")],
    [reg-copyright], [#fa("reg-copyright")],
    [reg-credit-card], [#fa("reg-credit-card")],
    [reg-envelope-open], [#fa("reg-envelope-open")],
    [reg-envelope], [#fa("reg-envelope")],
    [reg-eye-slash], [#fa("reg-eye-slash")],
    [reg-eye], [#fa("reg-eye")],
    [reg-freg-ile-audio], [#fa("reg-file-audio")],
    [reg-file-code], [#fa("reg-file-code")],
    [reg-file-excel], [#fa("reg-file-excel")],
    [reg-file-image], [#fa("reg-file-image")],
    [reg-file-lines], [#fa("reg-file-lines")],
    [reg-file-pdf], [#fa("reg-file-pdf")],
    [reg-file-powerpoint], [#fa("reg-file-powerpoint")],
    [reg-file-video], [#fa("reg-file-video")],
    [reg-file-word], [#fa("reg-file-word")],
    [reg-file-zipper], [#fa("reg-file-zipper")],
    [reg-file], [#fa("reg-file")],
    [reg-flag], [#fa("reg-flag")],
    [reg-floppy-disk], [#fa("reg-floppy-disk")],
    [reg-folder-closed], [#fa("reg-folder-closed")],
    [reg-folder-open], [#fa("reg-folder-open")],
    [reg-folder], [#fa("reg-folder")],
    [reg-font-awesome], [#fa("reg-font-awesome")],
    [reg-futbol], [#fa("reg-futbol")],
    [reg-gem], [#fa("reg-gem")],
    [reg-hand-back-fist], [#fa("reg-hand-back-fist")],
    [reg-hand-lizard], [#fa("reg-hand-lizard")],
    [reg-hand-peace], [#fa("reg-hand-peace")],
    [reg-hand-point-down], [#fa("reg-hand-point-down")],
    [reg-hand-point-left], [#fa("reg-hand-point-left")],
    [reg-hand-point-right], [#fa("reg-hand-point-right")],
    [reg-hand-point-up], [#fa("reg-hand-point-up")],
    [reg-hand-pointer], [#fa("reg-hand-pointer")],
    [reg-hand-scissors], [#fa("reg-hand-scissors")],
    [reg-hand-spock], [#fa("reg-hand-spock")],
    [reg-hand], [#fa("reg-hand")],
    [reg-handshake], [#fa("reg-handshake")],
    [reg-hard-drive], [#fa("reg-hard-drive")],
    [reg-heart], [#fa("reg-heart")],
    [reg-hospital], [#fa("reg-hospital")],
    [reg-hourglass-half], [#fa("reg-hourglass-half")],
    [reg-hourglass], [#fa("reg-hourglass")],
    [reg-id-badge], [#fa("reg-id-badge")],
    [reg-id-card], [#fa("reg-id-card")],
    [reg-image], [#fa("reg-image")],
    [reg-images], [#fa("reg-images")],
    [reg-keyboard], [#fa("reg-keyboard")],
    [reg-lemon], [#fa("reg-lemon")],
    [reg-life-ring], [#fa("reg-life-ring")],
    [reg-lightbulb], [#fa("reg-lightbulb")],
)])

#pagebreak(weak: true)

== M-W

#figure(
align(center)[#table(
    columns: 6,
    [reg-map], [#fa("reg-map")],
    [reg-message], [#fa("reg-message")],
    [reg-money-bill-1], [#fa("reg-money-bill-1")],
    [reg-moon], [#fa("reg-moon")],
    [reg-newspaper], [#fa("reg-newspaper")],
    [reg-note-sticky], [#fa("reg-note-sticky")],
    [reg-object-group], [#fa("reg-object-group")],
    [reg-object-ungroup], [#fa("reg-object-ungroup")],
    [reg-paper-plane], [#fa("reg-paper-plane")],
    [reg-paste], [#fa("reg-paste")],
    [reg-pen-to-square], [#fa("reg-pen-to-square")],
    [reg-rectangle-list], [#fa("reg-rectangle-list")],
    [reg-rectangle-xmark], [#fa("reg-rectangle-xmark")],
    [reg-registered], [#fa("reg-registered")],
    [reg-share-from-square], [#fa("reg-share-from-square")],
    [reg-snowflake], [#fa("reg-snowflake")],
    [reg-star-half-stroke], [#fa("reg-star-half-stroke")],
    [reg-star-half], [#fa("reg-star-half")],
    [reg-star], [#fa("reg-star")],
    [reg-sun], [#fa("reg-sun")],
    [reg-thumbs-down], [#fa("reg-thumbs-down")],
    [reg-thumbs-up], [#fa("reg-thumbs-up")],
    [reg-trash-can], [#fa("reg-trash-can")],
    [reg-user], [#fa("reg-user")],
    [reg-window-maximize], [#fa("reg-window-maximize")],
    [reg-window-minimize], [#fa("reg-window-minimize")],
    [reg-window-restore], [#fa("reg-window-restore")],
)])

=== Face

#figure(
align(center)[#table(
    columns: 6,
    [reg-face-angry], [#fa("reg-face-angry")],
    [reg-face-dizzy], [#fa("reg-face-dizzy")],
    [reg-face-flushed], [#fa("reg-face-flushed")],
    [reg-face-frown-open], [#fa("reg-face-frown-open")],
    [reg-face-frown], [#fa("reg-face-frown")],
    [reg-face-grimace], [#fa("reg-face-grimace")],
    [reg-face-grin-beam-sweat], [#fa("reg-face-grin-beam-sweat")],
    [reg-face-grin-beam], [#fa("reg-face-grin-beam")],
    [reg-face-grin-hearts], [#fa("reg-face-grin-hearts")],
    [reg-face-grin-squint-tears], [#fa("reg-face-grin-squint-tears")],
    [reg-face-grin-squint], [#fa("reg-face-grin-squint")],
    [reg-face-grin-stars], [#fa("reg-face-grin-stars")],
    [reg-face-grin-tears], [#fa("reg-face-grin-tears")],
    [reg-face-grin-tongue-squint], [#fa("reg-face-grin-tongue-squint")],
    [reg-face-grin-tongue-wink], [#fa("reg-face-grin-tongue-wink")],
    [reg-face-grin-tongue], [#fa("reg-face-grin-tongue")],
    [reg-face-grin-wide], [#fa("reg-face-grin-wide")],
    [reg-face-grin-wink], [#fa("reg-face-grin-wink")],
    [reg-face-grin], [#fa("reg-face-grin")],
    [reg-face-kiss-beam], [#fa("reg-face-kiss-beam")],
    [reg-face-kiss-wink-heart], [#fa("reg-face-kiss-wink-heart")],
    [reg-face-kiss], [#fa("reg-face-kiss")],
    [reg-face-laugh-beam], [#fa("reg-face-laugh-beam")],
    [reg-face-laugh-squint], [#fa("reg-face-laugh-squint")],
    [reg-face-laugh-wink], [#fa("reg-face-laugh-wink")],
    [reg-face-laugh], [#fa("reg-face-laugh")],
    [reg-face-meh-blank], [#fa("reg-face-meh-blank")],
    [reg-face-meh], [#fa("reg-face-meh")],
    [reg-face-rolling-eyes], [#fa("reg-face-rolling-eyes")],
    [reg-face-sad-cry], [#fa("reg-face-sad-cry")],
    [reg-face-sad-tear], [#fa("reg-face-sad-tear")],
    [reg-face-smile-beam], [#fa("reg-face-smile-beam")],
    [reg-face-smile-wink], [#fa("reg-face-smile-wink")],
    [reg-face-smile], [#fa("reg-face-smile")],
    [reg-face-surprise], [#fa("reg-face-surprise")],
    [reg-face-tired], [#fa("reg-face-tired")],
)])

=== Square

#figure(
align(center)[#table(
    columns: 6,
    [reg-square-caret-down], [#fa("reg-square-caret-down")],
    [reg-square-caret-left], [#fa("reg-square-caret-left")],
    [reg-square-caret-right], [#fa("reg-square-caret-right")],
    [reg-square-caret-up], [#fa("reg-square-caret-up")],
    [reg-square-check], [#fa("reg-square-check")],
    [reg-square-full], [#fa("reg-square-full")],
    [reg-square-minus], [#fa("reg-square-minus")],
    [reg-square-plus], [#fa("reg-square-plus")],
    [reg-square], [#fa("reg-square")],
)])

#pagebreak()

= Solid

== A

#figure(
align(center)[#table(
    columns: 8,
    align: center,
    [solid-0], [#fa("solid-0")],
    [solid-1], [#fa("solid-1")],
    [solid-2], [#fa("solid-2")],
    [solid-3], [#fa("solid-3")],
    [solid-4], [#fa("solid-4")],
    [solid-5], [#fa("solid-5")],
    [solid-6], [#fa("solid-6")],
    [solid-7], [#fa("solid-7")],
    [solid-8], [#fa("solid-8")],
    [solid-9], [#fa("solid-9")],
    [a], [#fa("a")],
    [address-book], [#fa("address-book")],
    [address-card], [#fa("address-card")],
    [align-center], [#fa("align-center")],
    [align-justify], [#fa("align-justify")],
    [align-left], [#fa("align-left")],
    [align-right], [#fa("align-right")],
    [ankh], [#fa("ankh")],
    [apple-whole], [#fa("apple-whole")],
    [archway], [#fa("archway")],
    [asterisk], [#fa("asterisk")],
    [at], [#fa("at")],
    [atom], [#fa("atom")],
    [audio-description], [#fa("audio-description")],
    [austral-sign], [#fa("austral-sign")],
    [award], [#fa("award")],
)])

=== Angle, Anchor

#figure(
align(center)[#table(
    columns: 6,
    [angle-down], [#fa("angle-down")],
    [angle-left], [#fa("angle-left")],
    [angle-right], [#fa("angle-right")],
    [angle-up], [#fa("angle-up")],
    [angles-down], [#fa("angles-down")],
    [angles-left], [#fa("angles-left")],
    [angles-right], [#fa("angles-right")],
    [angles-up], [#fa("angles-up")],
    [anchor-circle-check], [#fa("anchor-circle-check")],
    [anchor-circle-exclamation], [#fa("anchor-circle-exclamation")],
    [anchor-circle-xmark], [#fa("anchor-circle-xmark")],
    [anchor-lock], [#fa("anchor-lock")],
    [anchor], [#fa("anchor")],
)])

=== Battery, Bridge, Building

#figure(
align(center)[#table(
    columns: 6,
    [battery-empty], [#fa("battery-empty")],
    [battery-full], [#fa("battery-full")],
    [battery-half], [#fa("battery-half")],
    [battery-quarter], [#fa("battery-quarter")],
    [battery-three-quarters], [#fa("battery-three-quarters")],
    [bridge-circle-check], [#fa("bridge-circle-check")],
    [bridge-circle-exclamation], [#fa("bridge-circle-exclamation")],
    [bridge-circle-xmark], [#fa("bridge-circle-xmark")],
    [bridge-lock], [#fa("bridge-lock")],
    [bridge-water], [#fa("bridge-water")],
    [bridge], [#fa("bridge")],
    [building-circle-arrow-right], [#fa("building-circle-arrow-right")],
    [building-circle-check], [#fa("building-circle-check")],
    [building-circle-exclamation], [#fa("building-circle-exclamation")],
    [building-circle-xmark], [#fa("building-circle-xmark")],
    [building-columns], [#fa("building-columns")],
    [building-flag], [#fa("building-flag")],
    [building-lock], [#fa("building-lock")],
    [building-ngo], [#fa("building-ngo")],
    [building-shield], [#fa("building-shield")],
    [building-un], [#fa("building-un")],
    [building-user], [#fa("building-user")],
    [building-wheat], [#fa("building-wheat")],
    [building], [#fa("building")],
)])

#pagebreak()

=== Arrow

#figure(
align(center)[#table(
    columns: 4,
    [arrow-down-1-9], [#fa("arrow-down-1-9")],
    [arrow-down-9-1], [#fa("arrow-down-9-1")],
    [arrow-down-a-z], [#fa("arrow-down-a-z")],
    [arrow-down-long], [#fa("arrow-down-long")],
    [arrow-down-short-wide], [#fa("arrow-down-short-wide")],
    [arrow-down-up-across-line], [#fa("arrow-down-up-across-line")],
    [arrow-down-up-lock], [#fa("arrow-down-up-lock")],
    [arrow-down-wide-short], [#fa("arrow-down-wide-short")],
    [arrow-down-z-a], [#fa("arrow-down-z-a")],
    [arrow-down], [#fa("arrow-down")],
    [arrow-left-long], [#fa("arrow-left-long")],
    [arrow-left], [#fa("arrow-left")],
    [arrow-pointer], [#fa("arrow-pointer")],
    [arrow-right-arrow-left], [#fa("arrow-right-arrow-left")],
    [arrow-right-from-bracket], [#fa("arrow-right-from-bracket")],
    [arrow-right-long], [#fa("arrow-right-long")],
    [arrow-right-to-bracket], [#fa("arrow-right-to-bracket")],
    [arrow-right-to-city], [#fa("arrow-right-to-city")],
    [arrow-right], [#fa("arrow-right")],
    [arrow-rotate-left], [#fa("arrow-rotate-left")],
    [arrow-rotate-right], [#fa("arrow-rotate-right")],
    [arrow-trend-down], [#fa("arrow-trend-down")],
    [arrow-trend-up], [#fa("arrow-trend-up")],
    [arrow-turn-down], [#fa("arrow-turn-down")],
    [arrow-turn-up], [#fa("arrow-turn-up")],
    [arrow-up-1-9], [#fa("arrow-up-1-9")],
    [arrow-up-9-1], [#fa("arrow-up-9-1")],
    [arrow-up-a-z], [#fa("arrow-up-a-z")],
    [arrow-up-from-bracket], [#fa("arrow-up-from-bracket")],
    [arrow-up-from-ground-water], [#fa("arrow-up-from-ground-water")],
    [arrow-up-from-water-pump], [#fa("arrow-up-from-water-pump")],
    [arrow-up-long], [#fa("arrow-up-long")],
    [arrow-up-right-dots], [#fa("arrow-up-right-dots")],
    [arrow-up-right-from-square], [#fa("arrow-up-right-from-square")],
    [arrow-up-short-wide], [#fa("arrow-up-short-wide")],
    [arrow-up-wide-short], [#fa("arrow-up-wide-short")],
    [arrow-up-z-a], [#fa("arrow-up-z-a")],
    [arrow-up], [#fa("arrow-up")],
    [arrows-down-to-line], [#fa("arrows-down-to-line")],
    [arrows-down-to-people], [#fa("arrows-down-to-people")],
    [arrows-left-right-to-line], [#fa("arrows-left-right-to-line")],
    [arrows-left-right], [#fa("arrows-left-right")],
    [arrows-rotate], [#fa("arrows-rotate")],
    [arrows-spin], [#fa("arrows-spin")],
    [arrows-split-up-and-left], [#fa("arrows-split-up-and-left")],
    [arrows-to-circle], [#fa("arrows-to-circle")],
    [arrows-to-dot], [#fa("arrows-to-dot")],
    [arrows-to-eye], [#fa("arrows-to-eye")],
    [arrows-turn-right], [#fa("arrows-turn-right")],
    [arrows-turn-to-dots], [#fa("arrows-turn-to-dots")],
    [arrows-up-down-left-right], [#fa("arrows-up-down-left-right")],
    [arrows-up-down], [#fa("arrows-up-down")],
    [arrows-up-to-line], [#fa("arrows-up-to-line")],
)])

#pagebreak()

== B

#figure(
align(center)[#table(
    columns: 8,
    [b], [#fa("b")],
    [baby-carriage], [#fa("baby-carriage")],
    [baby], [#fa("baby")],
    [backward-fast], [#fa("backward-fast")],
    [backward-step], [#fa("backward-step")],
    [backward], [#fa("backward")],
    [bacon], [#fa("bacon")],
    [bacteria], [#fa("bacteria")],
    [bacterium], [#fa("bacterium")],
    [bag-shopping], [#fa("bag-shopping")],
    [bahai], [#fa("bahai")],
    [baht-sign], [#fa("baht-sign")],
    [ban-smoking], [#fa("ban-smoking")],
    [ban], [#fa("ban")],
    [bandage], [#fa("bandage")],
    [bangladeshi-taka-sign], [#fa("bangladeshi-taka-sign")],
    [barcode], [#fa("barcode")],
    [bars-progress], [#fa("bars-progress")],
    [bars-staggered], [#fa("bars-staggered")],
    [bars], [#fa("bars")],
    [baseball-bat-ball], [#fa("baseball-bat-ball")],
    [baseball], [#fa("baseball")],
    [basket-shopping], [#fa("basket-shopping")],
    [basketball], [#fa("basketball")],
    [bath], [#fa("bath")],
    [bed-pulse], [#fa("bed-pulse")],
    [bed], [#fa("bed")],
    [beer-mug-empty], [#fa("beer-mug-empty")],
    [bell-concierge], [#fa("bell-concierge")],
    [bell-slash], [#fa("bell-slash")],
    [bell], [#fa("bell")],
    [bezier-curve], [#fa("bezier-curve")],
    [bicycle], [#fa("bicycle")],
    [binoculars], [#fa("binoculars")],
    [biohazard], [#fa("biohazard")],
    [bitcoin-sign], [#fa("bitcoin-sign")],
    [blender-phone], [#fa("blender-phone")],
    [blender], [#fa("blender")],
    [blog], [#fa("blog")],
    [bold], [#fa("bold")],
    [bolt-lightning], [#fa("bolt-lightning")],
    [bolt], [#fa("bolt")],
    [bomb], [#fa("bomb")],
    [bone], [#fa("bone")],
    [bong], [#fa("bong")],
    [book-atlas], [#fa("book-atlas")],
    [book-bible], [#fa("book-bible")],
    [book-bookmark], [#fa("book-bookmark")],
    [book-journal-whills], [#fa("book-journal-whills")],
    [book-medical], [#fa("book-medical")],
    [book-open-reader], [#fa("book-open-reader")],
    [book-open], [#fa("book-open")],
    [book-quran], [#fa("book-quran")],
    [book-skull], [#fa("book-skull")],
    [book-tanakh], [#fa("book-tanakh")],
    [book], [#fa("book")],
    [bookmark], [#fa("bookmark")],
    [border-all], [#fa("border-all")],
    [border-none], [#fa("border-none")],
    [border-top-left], [#fa("border-top-left")],
    [bore-hole], [#fa("bore-hole")],
    [bottle-droplet], [#fa("bottle-droplet")],
    [bottle-water], [#fa("bottle-water")],
    [bowl-food], [#fa("bowl-food")],
    [bowl-rice], [#fa("bowl-rice")],
    [bowling-ball], [#fa("bowling-ball")],
    [box-archive], [#fa("box-archive")],
    [box-open], [#fa("box-open")],
    [box-tissue], [#fa("box-tissue")],
    [box], [#fa("box")],
    [boxes-packing], [#fa("boxes-packing")],
    [boxes-stacked], [#fa("boxes-stacked")],
    [braille], [#fa("braille")],
    [brain], [#fa("brain")],
    [brazilian-real-sign], [#fa("brazilian-real-sign")],
    [bread-slice], [#fa("bread-slice")],
    [briefcase-medical], [#fa("briefcase-medical")],
    [briefcase], [#fa("briefcase")],
    [broom-ball], [#fa("broom-ball")],
    [broom], [#fa("broom")],
    [brush], [#fa("brush")],
    [bucket], [#fa("bucket")],
    [bug-slash], [#fa("bug-slash")],
    [bug], [#fa("bug")],
    [bugs], [#fa("bugs")],
    [bullhorn], [#fa("bullhorn")],
    [bullseye], [#fa("bullseye")],
    [burger], [#fa("burger")],
    [burst], [#fa("burst")],
    [bus-simple], [#fa("bus-simple")],
    [bus], [#fa("bus")],
    [business-time], [#fa("business-time")],
)])

#pagebreak()

== C

#figure(
align(center)[#table(
    columns: 8,
    [c], [#fa("c")],
    [cable-car], [#fa("cable-car")],
    [calculator], [#fa("calculator")],
    [cake-candles], [#fa("cake-candles")],
    [camera-retro], [#fa("camera-retro")],
    [camera-rotate], [#fa("camera-rotate")],
    [camera], [#fa("camera")],
    [campground], [#fa("campground")],
    [candy-cane], [#fa("candy-cane")],
    [cannabis], [#fa("cannabis")],
    [capsules], [#fa("capsules")],
    [car-battery], [#fa("car-battery")],
    [car-burst], [#fa("car-burst")],
    [car-on], [#fa("car-on")],
    [car-rear], [#fa("car-rear")],
    [car-side], [#fa("car-side")],
    [car-tunnel], [#fa("car-tunnel")],
    [car], [#fa("car")],
    [caravan], [#fa("caravan")],
    [caret-down], [#fa("caret-down")],
    [caret-left], [#fa("caret-left")],
    [caret-right], [#fa("caret-right")],
    [caret-up], [#fa("caret-up")],
    [carrot], [#fa("carrot")],
    [cash-register], [#fa("cash-register")],
    [cat], [#fa("cat")],
    [cedi-sign], [#fa("cedi-sign")],
    [cent-sign], [#fa("cent-sign")],
    [certificate], [#fa("certificate")],
    [chair], [#fa("chair")],
    [chalkboard-user], [#fa("chalkboard-user")],
    [chalkboard], [#fa("chalkboard")],
    [champagne-glasses], [#fa("champagne-glasses")],
    [charging-station], [#fa("charging-station")],
    [check-double], [#fa("check-double")],
    [check-to-slot], [#fa("check-to-slot")],
    [check], [#fa("check")],
    [cheese], [#fa("cheese")],
    [chess-bishop], [#fa("chess-bishop")],
    [chess-board], [#fa("chess-board")],
    [chess-king], [#fa("chess-king")],
    [chess-knight], [#fa("chess-knight")],
    [chess-pawn], [#fa("chess-pawn")],
    [chess-queen], [#fa("chess-queen")],
    [chess-rook], [#fa("chess-rook")],
    [chess], [#fa("chess")],
    [chevron-down], [#fa("chevron-down")],
    [chevron-left], [#fa("chevron-left")],
    [chevron-right], [#fa("chevron-right")],
    [chevron-up], [#fa("chevron-up")],
    [child-combatant], [#fa("child-combatant")],
    [child-dress], [#fa("child-dress")],
    [child-reaching], [#fa("child-reaching")],
    [child], [#fa("child")],
    [children], [#fa("children")],
    [church], [#fa("church")],
    [city], [#fa("city")],
    [clapperboard], [#fa("clapperboard")],
    [clock-rotate-left], [#fa("clock-rotate-left")],
    [clock], [#fa("clock")],
    [clone], [#fa("clone")],
    [closed-captioning], [#fa("closed-captioning")],
    [coins], [#fa("coins")],
    [colon-sign], [#fa("colon-sign")],
    [clover], [#fa("clover")],
    [compact-disc], [#fa("compact-disc")],
    [compass-drafting], [#fa("compass-drafting")],
    [compass], [#fa("compass")],
    [compress], [#fa("compress")],
    [computer-mouse], [#fa("computer-mouse")],
    [computer], [#fa("computer")],
    [cookie-bite], [#fa("cookie-bite")],
    [cookie], [#fa("cookie")],
    [copy], [#fa("copy")],
    [copyright], [#fa("copyright")],
    [couch], [#fa("couch")],
    [cow], [#fa("cow")],
    [credit-card], [#fa("credit-card")],
    [crop-simple], [#fa("crop-simple")],
    [crop], [#fa("crop")],
    [cross], [#fa("cross")],
    [crosshairs], [#fa("crosshairs")],
    [crow], [#fa("crow")],
    [crown], [#fa("crown")],
    [crutch], [#fa("crutch")],
    [cruzeiro-sign], [#fa("cruzeiro-sign")],
    [cube], [#fa("cube")],
    [cubes-stacked], [#fa("cubes-stacked")],
    [cubes], [#fa("cubes")],
)])

#pagebreak()

=== Calendar, Cart, Chart

#figure(
align(center)[#table(
    columns: 8,
    [calendar-check], [#fa("calendar-check")],
    [calendar-day], [#fa("calendar-day")],
    [calendar-days], [#fa("calendar-days")],
    [calendar-minus], [#fa("calendar-minus")],
    [calendar-plus], [#fa("calendar-plus")],
    [calendar-week], [#fa("calendar-week")],
    [calendar-xmark], [#fa("calendar-xmark")],
    [calendar], [#fa("calendar")],
    [cart-arrow-down], [#fa("cart-arrow-down")],
    [cart-flatbed-suitcase], [#fa("cart-flatbed-suitcase")],
    [cart-flatbed], [#fa("cart-flatbed")],
    [cart-plus], [#fa("cart-plus")],
    [cart-shopping], [#fa("cart-shopping")],
    [chart-area], [#fa("chart-area")],
    [chart-bar], [#fa("chart-bar")],
    [chart-column], [#fa("chart-column")],
    [chart-gantt], [#fa("chart-gantt")],
    [chart-line], [#fa("chart-line")],
    [chart-pie], [#fa("chart-pie")],
    [chart-simple], [#fa("chart-simple")],
)])

=== Circle, Clipboard, Comment, Code

#figure(
align(center)[#table(
    columns: 6,
    [circle-arrow-down], [#fa("circle-arrow-down")],
    [circle-arrow-left], [#fa("circle-arrow-left")],
    [circle-arrow-right], [#fa("circle-arrow-right")],
    [circle-arrow-up], [#fa("circle-arrow-up")],
    [circle-check], [#fa("circle-check")],
    [circle-chevron-down], [#fa("circle-chevron-down")],
    [circle-chevron-left], [#fa("circle-chevron-left")],
    [circle-chevron-right], [#fa("circle-chevron-right")],
    [circle-chevron-up], [#fa("circle-chevron-up")],
    [circle-dollar-to-slot], [#fa("circle-dollar-to-slot")],
    [circle-dot], [#fa("circle-dot")],
    [circle-down], [#fa("circle-down")],
    [circle-exclamation], [#fa("circle-exclamation")],
    [circle-h], [#fa("circle-h")],
    [circle-half-stroke], [#fa("circle-half-stroke")],
    [circle-info], [#fa("circle-info")],
    [circle-left], [#fa("circle-left")],
    [circle-minus], [#fa("circle-minus")],
    [circle-nodes], [#fa("circle-nodes")],
    [circle-notch], [#fa("circle-notch")],
    [circle-pause], [#fa("circle-pause")],
    [circle-play], [#fa("circle-play")],
    [circle-plus], [#fa("circle-plus")],
    [circle-question], [#fa("circle-question")],
    [circle-radiation], [#fa("circle-radiation")],
    [circle-right], [#fa("circle-right")],
    [circle-stop], [#fa("circle-stop")],
    [circle-up], [#fa("circle-up")],
    [circle-user], [#fa("circle-user")],
    [circle-xmark], [#fa("circle-xmark")],
    [circle], [#fa("circle")],
    [clipboard-check], [#fa("clipboard-check")],
    [clipboard-list], [#fa("clipboard-list")],
    [clipboard-question], [#fa("clipboard-question")],
    [clipboard-user], [#fa("clipboard-user")],
    [clipboard], [#fa("clipboard")],
    [cloud-arrow-down], [#fa("cloud-arrow-down")],
    [cloud-arrow-up], [#fa("cloud-arrow-up")],
    [cloud-bolt], [#fa("cloud-bolt")],
    [cloud-meatball], [#fa("cloud-meatball")],
    [cloud-moon-rain], [#fa("cloud-moon-rain")],
    [cloud-moon], [#fa("cloud-moon")],
    [cloud-rain], [#fa("cloud-rain")],
    [cloud-showers-heavy], [#fa("cloud-showers-heavy")],
    [cloud-showers-water], [#fa("cloud-showers-water")],
    [cloud-sun-rain], [#fa("cloud-sun-rain")],
    [cloud-sun], [#fa("cloud-sun")],
    [cloud], [#fa("cloud")],
    [code-branch], [#fa("code-branch")],
    [code-commit], [#fa("code-commit")],
    [code-compare], [#fa("code-compare")],
    [code-fork], [#fa("code-fork")],
    [code-merge], [#fa("code-merge")],
    [code-pull-request], [#fa("code-pull-request")],
    [code], [#fa("code")],
    [comment-dollar], [#fa("comment-dollar")],
    [comment-dots], [#fa("comment-dots")],
    [comment-medical], [#fa("comment-medical")],
    [comment-slash], [#fa("comment-slash")],
    [comment-sms], [#fa("comment-sms")],
    [comment], [#fa("comment")],
    [comments-dollar], [#fa("comments-dollar")],
    [comments], [#fa("comments")],
)])

#pagebreak()

== D

#figure(
align(center)[#table(
    columns: 6,
    [d], [#fa("d")],
    [database], [#fa("database")],
    [delete-left], [#fa("delete-left")],
    [democrat], [#fa("democrat")],
    [desktop], [#fa("desktop")],
    [dharmachakra], [#fa("dharmachakra")],
    [diagram-next], [#fa("diagram-next")],
    [diagram-predecessor], [#fa("diagram-predecessor")],
    [diagram-project], [#fa("diagram-project")],
    [diagram-successor], [#fa("diagram-successor")],
    [diamond-turn-right], [#fa("diamond-turn-right")],
    [diamond], [#fa("diamond")],
    [dice-d6], [#fa("dice-d6")],
    [dice-d20], [#fa("dice-d20")],
    [dice-five], [#fa("dice-five")],
    [dice-four], [#fa("dice-four")],
    [dice-one], [#fa("dice-one")],
    [dice-six], [#fa("dice-six")],
    [dice-three], [#fa("dice-three")],
    [dice-two], [#fa("dice-two")],
    [dice], [#fa("dice")],
    [disease], [#fa("disease")],
    [display], [#fa("display")],
    [divide], [#fa("divide")],
    [dna], [#fa("dna")],
    [dog], [#fa("dog")],
    [dollar-sign], [#fa("dollar-sign")],
    [dolly], [#fa("dolly")],
    [dong-sign], [#fa("dong-sign")],
    [door-closed], [#fa("door-closed")],
    [door-open], [#fa("door-open")],
    [dove], [#fa("dove")],
     [down-long], [#fa("down-long")],
    [download], [#fa("download")],
    [dragon], [#fa("dragon")],
    [draw-polygon], [#fa("draw-polygon")],
    [droplet-slash], [#fa("droplet-slash")],
    [droplet], [#fa("droplet")],
    [drum-steelpan], [#fa("drum-steelpan")],
    [drum], [#fa("drum")],
    [drumstick-bite], [#fa("drumstick-bite")],
    [dumbbell], [#fa("dumbbell")],
    [dumpster-fire], [#fa("dumpster-fire")],
    [dumpster], [#fa("dumpster")],
    [dungeon], [#fa("dungeon")],
)])

== E

#figure(
align(center)[#table(
    columns: 6,
    [e], [#fa("e")],
    [ear-deaf], [#fa("ear-deaf")],
    [ear-listen], [#fa("ear-listen")],
    [earth-africa], [#fa("earth-africa")],
    [earth-americas], [#fa("earth-americas")],
    [earth-asia], [#fa("earth-asia")],
    [earth-europe], [#fa("earth-europe")],
    [earth-oceania], [#fa("earth-oceania")],
    [egg], [#fa("egg")],
    [eject], [#fa("eject")],
    [elevator], [#fa("elevator")],
    [ellipsis-vertical], [#fa("ellipsis-vertical")],
    [ellipsis], [#fa("ellipsis")],
    [envelope-circle-check], [#fa("envelope-circle-check")],
    [envelope-open-text], [#fa("envelope-open-text")],
    [envelope-open], [#fa("envelope-open")],
    [envelope], [#fa("envelope")],
    [envelopes-bulk], [#fa("envelopes-bulk")],
    [equals], [#fa("equals")],
    [eraser], [#fa("eraser")],
    [ethernet], [#fa("ethernet")],
    [euro-sign], [#fa("euro-sign")],
    [exclamation], [#fa("exclamation")],
    [expand], [#fa("expand")],
    [explosion], [#fa("explosion")],
    [eye-dropper], [#fa("eye-dropper")],
    [eye-low-vision], [#fa("eye-low-vision")],
    [eye-slash], [#fa("eye-slash")],
    [eye], [#fa("eye")],
)])

#pagebreak()

== F

#figure(
align(center)[#table(
    columns: 6,
    [f], [#fa("f")],
    [fan], [#fa("fan")],
    [faucet-drip], [#fa("faucet-drip")],
    [faucet], [#fa("faucet")],
    [fax], [#fa("fax")],
    [feather-pointed], [#fa("feather-pointed")],
    [feather], [#fa("feather")],
    [ferry], [#fa("ferry")],
    [file-arrow-down], [#fa("file-arrow-down")],
    [file-arrow-up], [#fa("file-arrow-up")],
    [file-audio], [#fa("file-audio")],
    [file-circle-check], [#fa("file-circle-check")],
    [file-circle-exclamation], [#fa("file-circle-exclamation")],
    [file-circle-minus], [#fa("file-circle-minus")],
    [file-circle-plus], [#fa("file-circle-plus")],
    [file-circle-question], [#fa("file-circle-question")],
    [file-circle-xmark], [#fa("file-circle-xmark")],
    [file-code], [#fa("file-code")],
    [file-contract], [#fa("file-contract")],
    [file-csv], [#fa("file-csv")],
    [file-excel], [#fa("file-excel")],
    [file-export], [#fa("file-export")],
    [file-image], [#fa("file-image")],
    [file-import], [#fa("file-import")],
    [file-invoice-dollar], [#fa("file-invoice-dollar")],
    [file-invoice], [#fa("file-invoice")],
    [file-lines], [#fa("file-lines")],
    [file-medical], [#fa("file-medical")],
    [file-pdf], [#fa("file-pdf")],
    [file-pen], [#fa("file-pen")],
    [file-powerpoint], [#fa("file-powerpoint")],
    [file-prescription], [#fa("file-prescription")],
    [file-shield], [#fa("file-shield")],
    [file-signature], [#fa("file-signature")],
    [file-video], [#fa("file-video")],
    [file-waveform], [#fa("file-waveform")],
    [file-word], [#fa("file-word")],
    [file-zipper], [#fa("file-zipper")],
    [file], [#fa("file")],
    [fill-drip], [#fa("fill-drip")],
    [fill], [#fa("fill")],
    [film], [#fa("film")],
    [filter-circle-dollar], [#fa("filter-circle-dollar")],
    [filter-circle-xmark], [#fa("filter-circle-xmark")],
    [filter], [#fa("filter")],
    [fingerprint], [#fa("fingerprint")],
    [fire-burner], [#fa("fire-burner")],
    [fire-extinguisher], [#fa("fire-extinguisher")],
    [fire-flame-curved], [#fa("fire-flame-curved")],
    [fire-flame-simple], [#fa("fire-flame-simple")],
    [fire], [#fa("fire")],
    [fish-fins], [#fa("fish-fins")],
    [fish], [#fa("fish")],
    [flag-checkered], [#fa("flag-checkered")],
    [flag-usa], [#fa("flag-usa")],
    [flag], [#fa("flag")],
    [flask-vial], [#fa("flask-vial")],
    [flask], [#fa("flask")],
     [floppy-disk], [#fa("floppy-disk")],
    [florin-sign], [#fa("florin-sign")],
    [folder-closed], [#fa("folder-closed")],
    [folder-minus], [#fa("folder-minus")],
    [folder-open], [#fa("folder-open")],
    [folder-plus], [#fa("folder-plus")],
    [folder-tree], [#fa("folder-tree")],
    [folder], [#fa("folder")],
    [font-awesome], [#fa("font-awesome")],
    [font], [#fa("font")],
    [football], [#fa("football")],
    [forward-fast], [#fa("forward-fast")],
    [forward-step], [#fa("forward-step")],
    [forward], [#fa("forward")],
    [franc-sign], [#fa("franc-sign")],
    [frog], [#fa("frog")],
    [futbol], [#fa("futbol")],
)])

#pagebreak()

=== Face

#figure(
align(center)[#table(
    columns: 6,
    [face-angry], [#fa("face-angry")],
    [face-dizzy], [#fa("face-dizzy")],
    [face-flushed], [#fa("face-flushed")],
    [face-frown-open], [#fa("face-frown-open")],
    [face-frown], [#fa("face-frown")],
    [face-grimace], [#fa("face-grimace")],
    [face-grin-beam-sweat], [#fa("face-grin-beam-sweat")],
    [face-grin-beam], [#fa("face-grin-beam")],
    [face-grin-hearts], [#fa("face-grin-hearts")],
    [face-grin-squint-tears], [#fa("face-grin-squint-tears")],
    [face-grin-squint], [#fa("face-grin-squint")],
    [face-grin-stars], [#fa("face-grin-stars")],
    [face-grin-tears], [#fa("face-grin-tears")],
    [face-grin-tongue-squint], [#fa("face-grin-tongue-squint")],
    [face-grin-tongue-wink], [#fa("face-grin-tongue-wink")],
    [face-grin-tongue], [#fa("face-grin-tongue")],
    [face-grin-wide], [#fa("face-grin-wide")],
    [face-grin-wink], [#fa("face-grin-wink")],
    [face-grin], [#fa("face-grin")],
    [face-kiss-beam], [#fa("face-kiss-beam")],
    [face-kiss-wink-heart], [#fa("face-kiss-wink-heart")],
    [face-kiss], [#fa("face-kiss")],
    [face-laugh-beam], [#fa("face-laugh-beam")],
    [face-laugh-squint], [#fa("face-laugh-squint")],
    [face-laugh-wink], [#fa("face-laugh-wink")],
    [face-laugh], [#fa("face-laugh")],
    [face-meh-blank], [#fa("face-meh-blank")],
    [face-meh], [#fa("face-meh")],
    [face-rolling-eyes], [#fa("face-rolling-eyes")],
    [face-sad-cry], [#fa("face-sad-cry")],
    [face-sad-tear], [#fa("face-sad-tear")],
    [face-smile-beam], [#fa("face-smile-beam")],
    [face-smile-wink], [#fa("face-smile-wink")],
    [face-smile], [#fa("face-smile")],
    [face-surprise], [#fa("face-surprise")],
    [face-tired], [#fa("face-tired")],
)])

== G

#figure(
align(center)[#table(
    columns: 6,
    [g], [#fa("g")],
    [gamepad], [#fa("gamepad")],
    [gas-pump], [#fa("gas-pump")],
    [gauge-high], [#fa("gauge-high")],
    [gauge-simple-high], [#fa("gauge-simple-high")],
    [gauge-simple], [#fa("gauge-simple")],
    [gauge], [#fa("gauge")],
    [gavel], [#fa("gavel")],
    [gear], [#fa("gear")],
    [gears], [#fa("gears")],
    [gem], [#fa("gem")],
    [genderless], [#fa("genderless")],
    [ghost], [#fa("ghost")],
    [gift], [#fa("gift")],
    [gifts], [#fa("gifts")],
    [glass-water-droplet], [#fa("glass-water-droplet")],
    [glass-water], [#fa("glass-water")],
    [glasses], [#fa("glasses")],
    [globe], [#fa("globe")],
    [golf-ball-tee], [#fa("golf-ball-tee")],
    [gopuram], [#fa("gopuram")],
    [graduation-cap], [#fa("graduation-cap")],
    [greater-than-equal], [#fa("greater-than-equal")],
    [greater-than], [#fa("greater-than")],
    [grip-lines-vertical], [#fa("grip-lines-vertical")],
    [grip-lines], [#fa("grip-lines")],
    [grip-vertical], [#fa("grip-vertical")],
    [grip], [#fa("grip")],
    [group-arrows-rotate], [#fa("group-arrows-rotate")],
    [guarani-sign], [#fa("guarani-sign")],
    [guitar], [#fa("guitar")],
    [gun], [#fa("gun")],
)])

#pagebreak()

== H

#figure(
align(center)[#table(
    columns: 6,
    [h], [#fa("h")],
    [hammer], [#fa("hammer")],
    [hamsa], [#fa("hamsa")],
    [hand-back-fist], [#fa("hand-back-fist")],
    [hand-dots], [#fa("hand-dots")],
    [hand-fist], [#fa("hand-fist")],
    [hand-holding-dollar], [#fa("hand-holding-dollar")],
    [hand-holding-droplet], [#fa("hand-holding-droplet")],
    [hand-holding-hand], [#fa("hand-holding-hand")],
    [hand-holding-heart], [#fa("hand-holding-heart")],
    [hand-holding-medical], [#fa("hand-holding-medical")],
    [hand-holding], [#fa("hand-holding")],
    [hand-lizard], [#fa("hand-lizard")],
    [hand-middle-finger], [#fa("hand-middle-finger")],
    [hand-peace], [#fa("hand-peace")],
    [hand-point-down], [#fa("hand-point-down")],
    [hand-point-left], [#fa("hand-point-left")],
    [hand-point-right], [#fa("hand-point-right")],
    [hand-point-up], [#fa("hand-point-up")],
    [hand-pointer], [#fa("hand-pointer")],
    [hand-scissors], [#fa("hand-scissors")],
    [hand-sparkles], [#fa("hand-sparkles")],
    [hand-spock], [#fa("hand-spock")],
    [hand], [#fa("hand")],
    [handcuffs], [#fa("handcuffs")],
    [hands-asl-interpreting], [#fa("hands-asl-interpreting")],
    [hands-bound], [#fa("hands-bound")],
    [hands-bubbles], [#fa("hands-bubbles")],
    [hands-clapping], [#fa("hands-clapping")],
    [hands-holding-child], [#fa("hands-holding-child")],
    [hands-holding-circle], [#fa("hands-holding-circle")],
    [hands-holding], [#fa("hands-holding")],
    [hands-praying], [#fa("hands-praying")],
    [hands], [#fa("hands")],
    [handshake-angle], [#fa("handshake-angle")],
    [handshake-simple-slash], [#fa("handshake-simple-slash")],
    [handshake-simple], [#fa("handshake-simple")],
    [handshake-slash], [#fa("handshake-slash")],
    [handshake], [#fa("handshake")],
    [hanukiah], [#fa("hanukiah")],
    [hard-drive], [#fa("hard-drive")],
    [hashtag], [#fa("hashtag")],
    [hat-cowboy-side], [#fa("hat-cowboy-side")],
    [hat-cowboy], [#fa("hat-cowboy")],
    [hat-wizard], [#fa("hat-wizard")],
    [head-side-cough-slash], [#fa("head-side-cough-slash")],
    [head-side-cough], [#fa("head-side-cough")],
    [head-side-mask], [#fa("head-side-mask")],
    [head-side-virus], [#fa("head-side-virus")],
    [heading], [#fa("heading")],
    [headphones-simple], [#fa("headphones-simple")],
    [headphones], [#fa("headphones")],
    [headset], [#fa("headset")],
    [heart-circle-bolt], [#fa("heart-circle-bolt")],
    [heart-circle-check], [#fa("heart-circle-check")],
    [heart-circle-exclamation], [#fa("heart-circle-exclamation")],
    [heart-circle-minus], [#fa("heart-circle-minus")],
    [heart-circle-plus], [#fa("heart-circle-plus")],
    [heart-circle-xmark], [#fa("heart-circle-xmark")],
    [heart-crack], [#fa("heart-crack")],
    [heart-pulse], [#fa("heart-pulse")],
    [heart], [#fa("heart")],
    [helicopter-symbol], [#fa("helicopter-symbol")],
    [helicopter], [#fa("helicopter")],
    [helmet-safety], [#fa("helmet-safety")],
    [helmet-un], [#fa("helmet-un")],
    [highlighter], [#fa("highlighter")],
    [hill-avalanche], [#fa("hill-avalanche")],
    [hill-rockslide], [#fa("hill-rockslide")],
    [hippo], [#fa("hippo")],
    [hockey-puck], [#fa("hockey-puck")],
    [holly-berry], [#fa("holly-berry")],
    [horse-head], [#fa("horse-head")],
    [horse], [#fa("horse")],
    [hospital-user], [#fa("hospital-user")],
    [hospital], [#fa("hospital")],
    [hot-tub-person], [#fa("hot-tub-person")],
    [hotdog], [#fa("hotdog")],
    [hotel], [#fa("hotel")],
    [hourglass-end], [#fa("hourglass-end")],
    [hourglass-half], [#fa("hourglass-half")],
    [hourglass-start], [#fa("hourglass-start")],
    [hourglass], [#fa("hourglass")],
    [hryvnia-sign], [#fa("hryvnia-sign")],
    [hurricane], [#fa("hurricane")],
)])

#pagebreak()

=== House

#figure(
align(center)[#table(
    columns: 4,
    [house-chimney-crack], [#fa("house-chimney-crack")],
    [house-chimney-medical], [#fa("house-chimney-medical")],
    [house-chimney-user], [#fa("house-chimney-user")],
    [house-chimney-window], [#fa("house-chimney-window")],
    [house-chimney], [#fa("house-chimney")],
    [house-circle-check], [#fa("house-circle-check")],
    [house-circle-exclamation], [#fa("house-circle-exclamation")],
    [house-circle-xmark], [#fa("house-circle-xmark")],
    [house-crack], [#fa("house-crack")],
    [house-fire], [#fa("house-fire")],
    [house-flag], [#fa("house-flag")],
    [house-flood-water-circle-arrow-right], [#fa("house-flood-water-circle-arrow-right")],
    [house-flood-water], [#fa("house-flood-water")],
    [house-laptop], [#fa("house-laptop")],
    [house-lock], [#fa("house-lock")],
    [house-medical-circle-check], [#fa("house-medical-circle-check")],
    [house-medical-circle-exclamation], [#fa("house-medical-circle-exclamation")],
    [house-medical-circle-xmark], [#fa("house-medical-circle-xmark")],
    [house-medical-flag], [#fa("house-medical-flag")],
    [house-medical], [#fa("house-medical")],
    [house-signal], [#fa("house-signal")],
    [house-tsunami], [#fa("house-tsunami")],
    [house-user], [#fa("house-user")],
    [house], [#fa("house")],
)])

#pagebreak()

== I-L

#figure(
align(center)[#table(
    columns: 8,
    [i-cursor], [#fa("i-cursor")],
    [i], [#fa("i")],
    [ice-cream], [#fa("ice-cream")],
    [icicles], [#fa("icicles")],
    [icons], [#fa("icons")],
    [id-badge], [#fa("id-badge")],
    [id-card-clip], [#fa("id-card-clip")],
    [id-card], [#fa("id-card")],
    [igloo], [#fa("igloo")],
    [image-portrait], [#fa("image-portrait")],
    [image], [#fa("image")],
    [images], [#fa("images")],
    [inbox], [#fa("inbox")],
    [indent], [#fa("indent")],
    [indian-rupee-sign], [#fa("indian-rupee-sign")],
    [industry], [#fa("industry")],
    [infinity], [#fa("infinity")],
    [info], [#fa("info")],
    [italic], [#fa("italic")],
    [j], [#fa("j")],
    [jar-wheat], [#fa("jar-wheat")],
    [jar], [#fa("jar")],
    [jedi], [#fa("jedi")],
    [jet-fighter-up], [#fa("jet-fighter-up")],
    [jet-fighter], [#fa("jet-fighter")],
    [joint], [#fa("joint")],
    [jug-detergent], [#fa("jug-detergent")],
    [k], [#fa("k")],
    [kaaba], [#fa("kaaba")],
    [key], [#fa("key")],
    [keyboard], [#fa("keyboard")],
    [khanda], [#fa("khanda")],
    [kip-sign], [#fa("kip-sign")],
    [kit-medical], [#fa("kit-medical")],
    [kitchen-set], [#fa("kitchen-set")],
    [kiwi-bird], [#fa("kiwi-bird")],
    [l], [#fa("l")],
    [land-mine-on], [#fa("land-mine-on")],
    [landmark-dome], [#fa("landmark-dome")],
    [landmark-flag], [#fa("landmark-flag")],
    [landmark], [#fa("landmark")],
    [language], [#fa("language")],
    [laptop-code], [#fa("laptop-code")],
    [laptop-file], [#fa("laptop-file")],
    [laptop-medical], [#fa("laptop-medical")],
    [laptop], [#fa("laptop")],
    [lari-sign], [#fa("lari-sign")],
    [layer-group], [#fa("layer-group")],
    [leaf], [#fa("leaf")],
    [left-long], [#fa("left-long")],
    [left-right], [#fa("left-right")],
    [lemon], [#fa("lemon")],
    [less-than-equal], [#fa("less-than-equal")],
    [less-than], [#fa("less-than")],
    [life-ring], [#fa("life-ring")],
    [lightbulb], [#fa("lightbulb")],
    [lines-leaning], [#fa("lines-leaning")],
    [link-slash], [#fa("link-slash")],
    [link], [#fa("link")],
    [lira-sign], [#fa("lira-sign")],
    [list-check], [#fa("list-check")],
    [list-ol], [#fa("list-ol")],
    [list-ul], [#fa("list-ul")],
    [list], [#fa("list")],
    [litecoin-sign], [#fa("litecoin-sign")],
    [location-arrow], [#fa("location-arrow")],
    [location-crosshairs], [#fa("location-crosshairs")],
    [location-dot], [#fa("location-dot")],
    [location-pin-lock], [#fa("location-pin-lock")],
    [location-pin], [#fa("location-pin")],
    [lock-open], [#fa("lock-open")],
    [lock], [#fa("lock")],
    [locust], [#fa("locust")],
    [lungs-virus], [#fa("lungs-virus")],
    [lungs], [#fa("lungs")],
)])

#pagebreak()

== M

#figure(
align(center)[#table(
    columns: 6,
    [m], [#fa("m")],
    [magnet], [#fa("magnet")],
    [manat-sign], [#fa("manat-sign")],
    [map-location-dot], [#fa("map-location-dot")],
    [map-location], [#fa("map-location")],
    [map-pin], [#fa("map-pin")],
    [map], [#fa("map")],
    [marker], [#fa("marker")],
    [mars-and-venus-burst], [#fa("mars-and-venus-burst")],
    [mars-and-venus], [#fa("mars-and-venus")],
    [mars-double], [#fa("mars-double")],
    [mars-stroke-right], [#fa("mars-stroke-right")],
    [mars-stroke-up], [#fa("mars-stroke-up")],
    [mars-stroke], [#fa("mars-stroke")],
    [mars], [#fa("mars")],
    [martini-glass-citrus], [#fa("martini-glass-citrus")],
    [martini-glass-empty], [#fa("martini-glass-empty")],
    [martini-glass], [#fa("martini-glass")],
    [mask-face], [#fa("mask-face")],
    [mask-ventilator], [#fa("mask-ventilator")],
    [mask], [#fa("mask")],
    [masks-theater], [#fa("masks-theater")],
    [mattress-pillow], [#fa("mattress-pillow")],
    [maximize], [#fa("maximize")],
    [medal], [#fa("medal")],
    [memory], [#fa("memory")],
    [menorah], [#fa("menorah")],
    [mercury], [#fa("mercury")],
    [message], [#fa("message")],
    [meteor], [#fa("meteor")],
    [microchip], [#fa("microchip")],
    [microphone-lines-slash], [#fa("microphone-lines-slash")],
    [microphone-lines], [#fa("microphone-lines")],
    [microphone-slash], [#fa("microphone-slash")],
    [microphone], [#fa("microphone")],
    [microscope], [#fa("microscope")],
    [mill-sign], [#fa("mill-sign")],
    [minimize], [#fa("minimize")],
    [minus], [#fa("minus")],
    [mitten], [#fa("mitten")],
    [mobile-button], [#fa("mobile-button")],
    [mobile-retro], [#fa("mobile-retro")],
    [mobile-screen-button], [#fa("mobile-screen-button")],
    [mobile-screen], [#fa("mobile-screen")],
    [mobile], [#fa("mobile")],
    [money-bill-1-wave], [#fa("money-bill-1-wave")],
    [money-bill-1], [#fa("money-bill-1")],
    [money-bill-transfer], [#fa("money-bill-transfer")],
    [money-bill-trend-up], [#fa("money-bill-trend-up")],
    [money-bill-wave], [#fa("money-bill-wave")],
    [money-bill-wheat], [#fa("money-bill-wheat")],
    [money-bill], [#fa("money-bill")],
    [money-bills], [#fa("money-bills")],
    [money-check-dollar], [#fa("money-check-dollar")],
    [money-check], [#fa("money-check")],
    [monument], [#fa("monument")],
    [moon], [#fa("moon")],
    [mortar-pestle], [#fa("mortar-pestle")],
    [mosque], [#fa("mosque")],
    [mosquito-net], [#fa("mosquito-net")],
    [mosquito], [#fa("mosquito")],
    [motorcycle], [#fa("motorcycle")],
    [mound], [#fa("mound")],
    [mountain-city], [#fa("mountain-city")],
    [mountain-sun], [#fa("mountain-sun")],
    [mountain], [#fa("mountain")],
    [mug-hot], [#fa("mug-hot")],
    [mug-saucer], [#fa("mug-saucer")],
    [music], [#fa("music")],
)])

=== Magnifying

#figure(
align(center)[#table(
    columns: 4,
    [magnifying-glass-arrow-right], [#fa("magnifying-glass-arrow-right")],
    [magnifying-glass-chart], [#fa("magnifying-glass-chart")],
    [magnifying-glass-dollar], [#fa("magnifying-glass-dollar")],
    [magnifying-glass-location], [#fa("magnifying-glass-location")],
    [magnifying-glass-minus], [#fa("magnifying-glass-minus")],
    [magnifying-glass-plus], [#fa("magnifying-glass-plus")],
    [magnifying-glass], [#fa("magnifying-glass")],
)])

#pagebreak()

== N-P

#figure(
align(center)[#table(
    columns: 6,
    [n], [#fa("n")],
    [naira-sign], [#fa("naira-sign")],
    [network-wired], [#fa("network-wired")],
    [neuter], [#fa("neuter")],
    [newspaper], [#fa("newspaper")],
    [not-equal], [#fa("not-equal")],
    [notdef], [#fa("notdef")],
    [note-sticky], [#fa("note-sticky")],
    [notes-medical], [#fa("notes-medical")],
    [o], [#fa("o")],
    [object-group], [#fa("object-group")],
    [object-ungroup], [#fa("object-ungroup")],
    [oil-can], [#fa("oil-can")],
    [oil-well], [#fa("oil-well")],
    [om], [#fa("om")],
    [otter], [#fa("otter")],
    [outdent], [#fa("outdent")],
    [p], [#fa("p")],
    [pager], [#fa("pager")],
    [paint-roller], [#fa("paint-roller")],
    [paintbrush], [#fa("paintbrush")],
    [palette], [#fa("palette")],
    [pallet], [#fa("pallet")],
    [panorama], [#fa("panorama")],
    [paper-plane], [#fa("paper-plane")],
    [paperclip], [#fa("paperclip")],
    [parachute-box], [#fa("parachute-box")],
    [paragraph], [#fa("paragraph")],
    [passport], [#fa("passport")],
    [paste], [#fa("paste")],
    [pause], [#fa("pause")],
    [paw], [#fa("paw")],
    [peace], [#fa("peace")],
    [pencil], [#fa("pencil")],
    [pepper-hot], [#fa("pepper-hot")],
    [percent], [#fa("percent")],
    [peseta-sign], [#fa("peseta-sign")],
    [peso-sign], [#fa("peso-sign")],
    [phone-flip], [#fa("phone-flip")],
    [phone-slash], [#fa("phone-slash")],
    [phone-volume], [#fa("phone-volume")],
    [phone], [#fa("phone")],
    [photo-film], [#fa("photo-film")],
    [piggy-bank], [#fa("piggy-bank")],
    [pills], [#fa("pills")],
    [pizza-slice], [#fa("pizza-slice")],
    [place-of-worship], [#fa("place-of-worship")],
    [plant-wilt], [#fa("plant-wilt")],
    [plate-wheat], [#fa("plate-wheat")],
    [play], [#fa("play")],
    [plus-minus], [#fa("plus-minus")],
    [plus], [#fa("plus")],
    [podcast], [#fa("podcast")],
    [poo-storm], [#fa("poo-storm")],
    [poo], [#fa("poo")],
    [poop], [#fa("poop")],
    [power-off], [#fa("power-off")],
    [prescription-bottle-medical], [#fa("prescription-bottle-medical")],
    [prescription-bottle], [#fa("prescription-bottle")],
    [prescription], [#fa("prescription")],
    [print], [#fa("print")],
    [pump-medical], [#fa("pump-medical")],
    [pump-soap], [#fa("pump-soap")],
    [puzzle-piece], [#fa("puzzle-piece")],
)])

=== Pen, Plane, Plug

#figure(
align(center)[#table(
    columns: 6,
     [pen-clip], [#fa("pen-clip")],
    [pen-fancy], [#fa("pen-fancy")],
    [pen-nib], [#fa("pen-nib")],
    [pen-ruler], [#fa("pen-ruler")],
    [pen-to-square], [#fa("pen-to-square")],
    [pen], [#fa("pen")],
    [plane-arrival], [#fa("plane-arrival")],
    [plane-circle-check], [#fa("plane-circle-check")],
    [plane-circle-exclamation], [#fa("plane-circle-exclamation")],
    [plane-circle-xmark], [#fa("plane-circle-xmark")],
    [plane-departure], [#fa("plane-departure")],
    [plane-lock], [#fa("plane-lock")],
    [plane-slash], [#fa("plane-slash")],
    [plane-up], [#fa("plane-up")],
    [plane], [#fa("plane")],
     [plug-circle-bolt], [#fa("plug-circle-bolt")],
    [plug-circle-check], [#fa("plug-circle-check")],
    [plug-circle-exclamation], [#fa("plug-circle-exclamation")],
    [plug-circle-minus], [#fa("plug-circle-minus")],
    [plug-circle-plus], [#fa("plug-circle-plus")],
    [plug-circle-xmark], [#fa("plug-circle-xmark")],
    [plug], [#fa("plug")],
)])

=== People, Person

#figure(
align(center)[#table(
    columns: 4,
    [people-arrows], [#fa("people-arrows")],
    [people-carry-box], [#fa("people-carry-box")],
    [people-group], [#fa("people-group")],
    [people-line], [#fa("people-line")],
    [people-pulling], [#fa("people-pulling")],
    [people-robbery], [#fa("people-robbery")],
    [people-roof], [#fa("people-roof")],
    [person-arrow-down-to-line], [#fa("person-arrow-down-to-line")],
    [person-arrow-up-from-line], [#fa("person-arrow-up-from-line")],
    [person-biking], [#fa("person-biking")],
    [person-booth], [#fa("person-booth")],
    [person-breastfeeding], [#fa("person-breastfeeding")],
    [person-burst], [#fa("person-burst")],
    [person-cane], [#fa("person-cane")],
    [person-chalkboard], [#fa("person-chalkboard")],
    [person-circle-check], [#fa("person-circle-check")],
    [person-circle-exclamation], [#fa("person-circle-exclamation")],
    [person-circle-minus], [#fa("person-circle-minus")],
    [person-circle-plus], [#fa("person-circle-plus")],
    [person-circle-question], [#fa("person-circle-question")],
    [person-circle-xmark], [#fa("person-circle-xmark")],
    [person-digging], [#fa("person-digging")],
    [person-dots-from-line], [#fa("person-dots-from-line")],
    [person-dress-burst], [#fa("person-dress-burst")],
    [person-dress], [#fa("person-dress")],
    [person-drowning], [#fa("person-drowning")],
    [person-falling-burst], [#fa("person-falling-burst")],
    [person-falling], [#fa("person-falling")],
    [person-half-dress], [#fa("person-half-dress")],
    [person-harassing], [#fa("person-harassing")],
    [person-hiking], [#fa("person-hiking")],
    [person-military-pointing], [#fa("person-military-pointing")],
    [person-military-rifle], [#fa("person-military-rifle")],
    [person-military-to-person], [#fa("person-military-to-person")],
    [person-praying], [#fa("person-praying")],
    [person-pregnant], [#fa("person-pregnant")],
    [person-rays], [#fa("person-rays")],
    [person-rifle], [#fa("person-rifle")],
    [person-running], [#fa("person-running")],
    [person-shelter], [#fa("person-shelter")],
    [person-skating], [#fa("person-skating")],
    [person-skiing-nordic], [#fa("person-skiing-nordic")],
    [person-skiing], [#fa("person-skiing")],
    [person-snowboarding], [#fa("person-snowboarding")],
    [person-swimming], [#fa("person-swimming")],
    [person-through-window], [#fa("person-through-window")],
    [person-walking-arrow-loop-left], [#fa("person-walking-arrow-loop-left")],
    [person-walking-arrow-right], [#fa("person-walking-arrow-right")],
    [person-walking-dashed-line-arrow-right], [#fa("person-walking-dashed-line-arrow-right")],
    [person-walking-luggage], [#fa("person-walking-luggage")],
    [person-walking-with-cane], [#fa("person-walking-with-cane")],
    [person-walking], [#fa("person-walking")],
    [person], [#fa("person")],
)])

#pagebreak()

== Q-R

#figure(
align(center)[#table(
    columns: 6,
    [q], [#fa("q")],
    [qrcode], [#fa("qrcode")],
    [question], [#fa("question")],
    [quote-left], [#fa("quote-left")],
    [quote-right], [#fa("quote-right")],
    [r], [#fa("r")],
    [radiation], [#fa("radiation")],
    [radio], [#fa("radio")],
    [rainbow], [#fa("rainbow")],
    [ranking-star], [#fa("ranking-star")],
    [receipt], [#fa("receipt")],
    [record-vinyl], [#fa("record-vinyl")],
    [rectangle-ad], [#fa("rectangle-ad")],
    [rectangle-list], [#fa("rectangle-list")],
    [rectangle-xmark], [#fa("rectangle-xmark")],
    [recycle], [#fa("recycle")],
    [registered], [#fa("registered")],
    [repeat], [#fa("repeat")],
    [reply-all], [#fa("reply-all")],
    [reply], [#fa("reply")],
    [republican], [#fa("republican")],
    [restroom], [#fa("restroom")],
    [retweet], [#fa("retweet")],
    [ribbon], [#fa("ribbon")],
    [right-from-bracket], [#fa("right-from-bracket")],
    [right-left], [#fa("right-left")],
    [right-long], [#fa("right-long")],
    [right-to-bracket], [#fa("right-to-bracket")],
    [ring], [#fa("ring")],
    [road-barrier], [#fa("road-barrier")],
    [road-bridge], [#fa("road-bridge")],
    [road-circle-check], [#fa("road-circle-check")],
    [road-circle-exclamation], [#fa("road-circle-exclamation")],
    [road-circle-xmark], [#fa("road-circle-xmark")],
    [road-lock], [#fa("road-lock")],
    [road-spikes], [#fa("road-spikes")],
    [road], [#fa("road")],
    [robot], [#fa("robot")],
    [rocket], [#fa("rocket")],
    [rotate-left], [#fa("rotate-left")],
    [rotate-right], [#fa("rotate-right")],
    [rotate], [#fa("rotate")],
    [route], [#fa("route")],
    [rss], [#fa("rss")],
    [ruble-sign], [#fa("ruble-sign")],
    [rug], [#fa("rug")],
    [ruler-combined], [#fa("ruler-combined")],
    [ruler-horizontal], [#fa("ruler-horizontal")],
    [ruler-vertical], [#fa("ruler-vertical")],
    [ruler], [#fa("ruler")],
    [rupee-sign], [#fa("rupee-sign")],
    [rupiah-sign], [#fa("rupiah-sign")],
)])

#pagebreak()

== S

#figure(
align(center)[#table(
    columns: 6,
    [s], [#fa("s")],
    [sack-dollar], [#fa("sack-dollar")],
    [sack-xmark], [#fa("sack-xmark")],
    [sailboat], [#fa("sailboat")],
    [satellite-dish], [#fa("satellite-dish")],
    [satellite], [#fa("satellite")],
    [scale-balanced], [#fa("scale-balanced")],
    [scale-unbalanced-flip], [#fa("scale-unbalanced-flip")],
    [scale-unbalanced], [#fa("scale-unbalanced")],
    [scissors], [#fa("scissors")],
    [screwdriver-wrench], [#fa("screwdriver-wrench")],
    [screwdriver], [#fa("screwdriver")],
    [scroll-torah], [#fa("scroll-torah")],
    [scroll], [#fa("scroll")],
    [sd-card], [#fa("sd-card")],
    [section], [#fa("section")],
    [seedling], [#fa("seedling")],
    [server], [#fa("server")],
    [shapes], [#fa("shapes")],
    [share-from-square], [#fa("share-from-square")],
    [share-nodes], [#fa("share-nodes")],
    [share], [#fa("share")],
    [sheet-plastic], [#fa("sheet-plastic")],
    [shekel-sign], [#fa("shekel-sign")],
    [ship], [#fa("ship")],
    [shirt], [#fa("shirt")],
    [shoe-prints], [#fa("shoe-prints")],
    [shop-lock], [#fa("shop-lock")],
    [shop-slash], [#fa("shop-slash")],
    [shop], [#fa("shop")],
    [shower], [#fa("shower")],
    [shrimp], [#fa("shrimp")],
    [shuffle], [#fa("shuffle")],
    [shuttle-space], [#fa("shuttle-space")],
    [sign-hanging], [#fa("sign-hanging")],
    [signal], [#fa("signal")],
    [signature], [#fa("signature")],
    [signs-post], [#fa("signs-post")],
    [sim-card], [#fa("sim-card")],
    [sink], [#fa("sink")],
    [sitemap], [#fa("sitemap")],
    [skull-crossbones], [#fa("skull-crossbones")],
    [skull], [#fa("skull")],
    [slash], [#fa("slash")],
    [sleigh], [#fa("sleigh")],
    [sliders], [#fa("sliders")],
    [smog], [#fa("smog")],
    [smoking], [#fa("smoking")],
    [snowflake], [#fa("snowflake")],
    [snowman], [#fa("snowman")],
    [snowplow], [#fa("snowplow")],
    [soap], [#fa("soap")],
    [socks], [#fa("socks")],
    [solar-panel], [#fa("solar-panel")],
    [sort-down], [#fa("sort-down")],
    [sort-up], [#fa("sort-up")],
    [sort], [#fa("sort")],
    [spa], [#fa("spa")],
    [spaghetti-monster-flying], [#fa("spaghetti-monster-flying")],
    [spell-check], [#fa("spell-check")],
    [spider], [#fa("spider")],
    [spinner], [#fa("spinner")],
    [splotch], [#fa("splotch")],
    [spoon], [#fa("spoon")],
    [spray-can-sparkles], [#fa("spray-can-sparkles")],
    [spray-can], [#fa("spray-can")],
    [staff-snake], [#fa("staff-snake")],
    [stairs], [#fa("stairs")],
    [stamp], [#fa("stamp")],
    [stapler], [#fa("stapler")],
    [sterling-sign], [#fa("sterling-sign")],
    [stethoscope], [#fa("stethoscope")],
     [stop], [#fa("stop")],
    [stopwatch-20], [#fa("stopwatch-20")],
    [stopwatch], [#fa("stopwatch")],
    [store-slash], [#fa("store-slash")],
    [store], [#fa("store")],
    [street-view], [#fa("street-view")],
    [strikethrough], [#fa("strikethrough")],
    [stroopwafel], [#fa("stroopwafel")],
    [subscript], [#fa("subscript")],
    [suitcase-medical], [#fa("suitcase-medical")],
    [suitcase-rolling], [#fa("suitcase-rolling")],
    [suitcase], [#fa("suitcase")],
    [sun-plant-wilt], [#fa("sun-plant-wilt")],
    [sun], [#fa("sun")],
    [superscript], [#fa("superscript")],
    [swatchbook], [#fa("swatchbook")],
    [synagogue], [#fa("synagogue")],
    [syringe], [#fa("syringe")],
)])

#pagebreak()

=== Shield, School, Square, Star

#figure(
align(center)[#table(
    columns: 6,
    [shield-cat], [#fa("shield-cat")],
    [shield-dog], [#fa("shield-dog")],
    [shield-halved], [#fa("shield-halved")],
    [shield-heart], [#fa("shield-heart")],
    [shield-virus], [#fa("shield-virus")],
    [shield], [#fa("shield")],
    [school-circle-check], [#fa("school-circle-check")],
    [school-circle-exclamation], [#fa("school-circle-exclamation")],
    [school-circle-xmark], [#fa("school-circle-xmark")],
    [school-flag], [#fa("school-flag")],
    [school-lock], [#fa("school-lock")],
    [school], [#fa("school")],
    [square-arrow-up-right], [#fa("square-arrow-up-right")],
    [square-caret-down], [#fa("square-caret-down")],
    [square-caret-left], [#fa("square-caret-left")],
    [square-caret-right], [#fa("square-caret-right")],
    [square-caret-up], [#fa("square-caret-up")],
    [square-check], [#fa("square-check")],
    [square-envelope], [#fa("square-envelope")],
    [square-full], [#fa("square-full")],
    [square-h], [#fa("square-h")],
    [square-minus], [#fa("square-minus")],
    [square-nfi], [#fa("square-nfi")],
    [square-parking], [#fa("square-parking")],
    [square-pen], [#fa("square-pen")],
    [square-person-confined], [#fa("square-person-confined")],
    [square-phone-flip], [#fa("square-phone-flip")],
    [square-phone], [#fa("square-phone")],
    [square-plus], [#fa("square-plus")],
    [square-poll-horizontal], [#fa("square-poll-horizontal")],
    [square-poll-vertical], [#fa("square-poll-vertical")],
    [square-root-variable], [#fa("square-root-variable")],
    [square-rss], [#fa("square-rss")],
    [square-share-nodes], [#fa("square-share-nodes")],
    [square-up-right], [#fa("square-up-right")],
    [square-virus], [#fa("square-virus")],
    [square-xmark], [#fa("square-xmark")],
    [square], [#fa("square")],
    [star-and-crescent], [#fa("star-and-crescent")],
    [star-half-stroke], [#fa("star-half-stroke")],
    [star-half], [#fa("star-half")],
    [star-of-david], [#fa("star-of-david")],
    [star-of-life], [#fa("star-of-life")],
    [star], [#fa("star")],
)])

=== Table, Tent, Temperature, Toilet, Truck

#figure(
align(center)[#table(
    columns: 6,
    [table-cells-large], [#fa("table-cells-large")],
    [table-cells], [#fa("table-cells")],
    [table-columns], [#fa("table-columns")],
    [table-list], [#fa("table-list")],
    [table-tennis-paddle-ball], [#fa("table-tennis-paddle-ball")],
    [table], [#fa("table")],
    [tent-arrow-down-to-line], [#fa("tent-arrow-down-to-line")],
    [tent-arrow-left-right], [#fa("tent-arrow-left-right")],
    [tent-arrow-turn-left], [#fa("tent-arrow-turn-left")],
    [tent-arrows-down], [#fa("tent-arrows-down")],
    [tent], [#fa("tent")],
    [tents], [#fa("tents")],
    [temperature-arrow-down], [#fa("temperature-arrow-down")],
    [temperature-arrow-up], [#fa("temperature-arrow-up")],
    [temperature-empty], [#fa("temperature-empty")],
    [temperature-full], [#fa("temperature-full")],
    [temperature-half], [#fa("temperature-half")],
    [temperature-high], [#fa("temperature-high")],
    [temperature-low], [#fa("temperature-low")],
    [temperature-quarter], [#fa("temperature-quarter")],
    [temperature-three-quarters], [#fa("temperature-three-quarters")],
    [toilet-paper-slash], [#fa("toilet-paper-slash")],
    [toilet-paper], [#fa("toilet-paper")],
    [toilet-portable], [#fa("toilet-portable")],
    [toilet], [#fa("toilet")],
    [toilets-portable], [#fa("toilets-portable")],
    [truck-arrow-right], [#fa("truck-arrow-right")],
    [truck-droplet], [#fa("truck-droplet")],
    [truck-fast], [#fa("truck-fast")],
    [truck-field-un], [#fa("truck-field-un")],
    [truck-field], [#fa("truck-field")],
    [truck-front], [#fa("truck-front")],
    [truck-medical], [#fa("truck-medical")],
    [truck-monster], [#fa("truck-monster")],
    [truck-moving], [#fa("truck-moving")],
    [truck-pickup], [#fa("truck-pickup")],
    [truck-plane], [#fa("truck-plane")],
    [truck-ramp-box], [#fa("truck-ramp-box")],
    [truck], [#fa("truck")],
)])

#pagebreak()

== T

#figure(
align(center)[#table(
    columns: 6,
    [t], [#fa("t")],
    [tablet-button], [#fa("tablet-button")],
    [tablet-screen-button], [#fa("tablet-screen-button")],
    [tablet], [#fa("tablet")],
    [tablets], [#fa("tablets")],
    [tachograph-digital], [#fa("tachograph-digital")],
    [tag], [#fa("tag")],
    [tags], [#fa("tags")],
    [tape], [#fa("tape")],
    [tarp-droplet], [#fa("tarp-droplet")],
    [tarp], [#fa("tarp")],
    [taxi], [#fa("taxi")],
    [teeth-open], [#fa("teeth-open")],
    [teeth], [#fa("teeth")],
     [tenge-sign], [#fa("tenge-sign")],
    [terminal], [#fa("terminal")],
    [text-height], [#fa("text-height")],
    [text-slash], [#fa("text-slash")],
    [text-width], [#fa("text-width")],
    [thermometer], [#fa("thermometer")],
    [thumbs-down], [#fa("thumbs-down")],
    [thumbs-up], [#fa("thumbs-up")],
    [thumbtack], [#fa("thumbtack")],
    [ticket-simple], [#fa("ticket-simple")],
    [ticket], [#fa("ticket")],
    [timeline], [#fa("timeline")],
    [toggle-off], [#fa("toggle-off")],
    [toggle-on], [#fa("toggle-on")],
    [toolbox], [#fa("toolbox")],
    [tooth], [#fa("tooth")],
    [torii-gate], [#fa("torii-gate")],
    [tornado], [#fa("tornado")],
    [tower-broadcast], [#fa("tower-broadcast")],
    [tower-cell], [#fa("tower-cell")],
    [tower-observation], [#fa("tower-observation")],
    [tractor], [#fa("tractor")],
    [trademark], [#fa("trademark")],
    [traffic-light], [#fa("traffic-light")],
    [trailer], [#fa("trailer")],
    [train-subway], [#fa("train-subway")],
    [train-tram], [#fa("train-tram")],
    [train], [#fa("train")],
    [transgender], [#fa("transgender")],
    [trash-arrow-up], [#fa("trash-arrow-up")],
    [trash-can-arrow-up], [#fa("trash-can-arrow-up")],
    [trash-can], [#fa("trash-can")],
    [trash], [#fa("trash")],
    [tree-city], [#fa("tree-city")],
    [tree], [#fa("tree")],
    [triangle-exclamation], [#fa("triangle-exclamation")],
    [trophy], [#fa("trophy")],
    [trowel-bricks], [#fa("trowel-bricks")],
    [trowel], [#fa("trowel")],
    [tty], [#fa("tty")],
    [turkish-lira-sign], [#fa("turkish-lira-sign")],
    [turn-down], [#fa("turn-down")],
    [turn-up], [#fa("turn-up")],
    [tv], [#fa("tv")],
)])

== U

#figure(
align(center)[#table(
    columns: 8,
    [u], [#fa("u")],
    [umbrella-beach], [#fa("umbrella-beach")],
    [umbrella], [#fa("umbrella")],
    [underline], [#fa("underline")],
    [universal-access], [#fa("universal-access")],
    [unlock-keyhole], [#fa("unlock-keyhole")],
    [unlock], [#fa("unlock")],
    [utensils], [#fa("utensils")],
    [up-down-left-right], [#fa("up-down-left-right")],
    [up-down], [#fa("up-down")],
    [up-long], [#fa("up-long")],
    [up-right-from-square], [#fa("up-right-from-square")],
    [upload], [#fa("upload")],
)])

#pagebreak()

== User

#figure(
align(center)[#table(
    columns: 8,
    [user-astronaut], [#fa("user-astronaut")],
    [user-check], [#fa("user-check")],
    [user-clock], [#fa("user-clock")],
    [user-doctor], [#fa("user-doctor")],
    [user-gear], [#fa("user-gear")],
    [user-graduate], [#fa("user-graduate")],
    [user-group], [#fa("user-group")],
    [user-injured], [#fa("user-injured")],
    [user-large-slash], [#fa("user-large-slash")],
    [user-large], [#fa("user-large")],
    [user-lock], [#fa("user-lock")],
    [user-minus], [#fa("user-minus")],
    [user-ninja], [#fa("user-ninja")],
    [user-nurse], [#fa("user-nurse")],
    [user-pen], [#fa("user-pen")],
    [user-plus], [#fa("user-plus")],
    [user-secret], [#fa("user-secret")],
    [user-shield], [#fa("user-shield")],
    [user-slash], [#fa("user-slash")],
    [user-tag], [#fa("user-tag")],
    [user-tie], [#fa("user-tie")],
    [user-xmark], [#fa("user-xmark")],
    [user], [#fa("user")],
    [users-between-lines], [#fa("users-between-lines")],
    [users-gear], [#fa("users-gear")],
    [users-line], [#fa("users-line")],
    [users-rays], [#fa("users-rays")],
    [users-rectangle], [#fa("users-rectangle")],
    [users-slash], [#fa("users-slash")],
    [users-viewfinder], [#fa("users-viewfinder")],
    [users], [#fa("users")],
)])

== V-Z

#figure(
align(center)[#table(
    columns: 6,
    [v], [#fa("v")],
    [van-shuttle], [#fa("van-shuttle")],
    [vault], [#fa("vault")],
    [vector-square], [#fa("vector-square")],
    [venus-double], [#fa("venus-double")],
    [venus-mars], [#fa("venus-mars")],
    [venus], [#fa("venus")],
    [vest-patches], [#fa("vest-patches")],
    [vest], [#fa("vest")],
    [vial-circle-check], [#fa("vial-circle-check")],
    [vial-virus], [#fa("vial-virus")],
    [vial], [#fa("vial")],
    [vials], [#fa("vials")],
    [video-slash], [#fa("video-slash")],
    [video], [#fa("video")],
    [vihara], [#fa("vihara")],
    [voicemail], [#fa("voicemail")],
    [volcano], [#fa("volcano")],
    [volleyball], [#fa("volleyball")],
    [vr-cardboard], [#fa("vr-cardboard")],
    [w], [#fa("w")],
    [walkie-talkie], [#fa("walkie-talkie")],
    [wallet], [#fa("wallet")],
    [wand-magic-sparkles], [#fa("wand-magic-sparkles")],
    [wand-magic], [#fa("wand-magic")],
    [wand-sparkles], [#fa("wand-sparkles")],
    [warehouse], [#fa("warehouse")],
    [water-ladder], [#fa("water-ladder")],
    [water], [#fa("water")],
    [wave-square], [#fa("wave-square")],
    [weight-hanging], [#fa("weight-hanging")],
    [weight-scale], [#fa("weight-scale")],
    [wheat-awn-circle-exclamation], [#fa("wheat-awn-circle-exclamation")],
    [wheat-awn], [#fa("wheat-awn")],
    [wheelchair-move], [#fa("wheelchair-move")],
    [wheelchair], [#fa("wheelchair")],
    [whiskey-glass], [#fa("whiskey-glass")],
    [wifi], [#fa("wifi")],
    [wind], [#fa("wind")],
    [window-maximize], [#fa("window-maximize")],
    [window-minimize], [#fa("window-minimize")],
    [window-restore], [#fa("window-restore")],
    [wine-bottle], [#fa("wine-bottle")],
    [wine-glass-empty], [#fa("wine-glass-empty")],
    [wine-glass], [#fa("wine-glass")],
    [won-sign], [#fa("won-sign")],
    [worm], [#fa("worm")],
    [wrench], [#fa("wrench")],
    [x-ray], [#fa("x-ray")],
    [x], [#fa("x")],
    [xmark], [#fa("xmark")],
    [xmarks-lines], [#fa("xmarks-lines")],
    [y], [#fa("y")],
    [yen-sign], [#fa("yen-sign")],
    [yin-yang], [#fa("yin-yang")],
    [z], [#fa("z")],
)])

#pagebreak(weak: true)

=== Virus, Volume

#figure(
align(center)[#table(
    columns: 8,
    [virus-covid-slash], [#fa("virus-covid-slash")],
    [virus-covid], [#fa("virus-covid")],
    [virus-slash], [#fa("virus-slash")],
    [virus], [#fa("virus")],
    [viruses], [#fa("viruses")],
    [volume-high], [#fa("volume-high")],
    [volume-low], [#fa("volume-low")],
    [volume-off], [#fa("volume-off")],
    [volume-xmark], [#fa("volume-xmark")],
)])

== Other

#figure(
align(center)[#table(
    columns: 4,
    [down-left-and-up-right-to-center], [#fa("down-left-and-up-right-to-center")],
    [up-right-and-down-left-from-center], [#fa("up-right-and-down-left-from-center")],
)])
