// =========================================================================
// CAS Identities Truth Table
// =========================================================================
// Single source of truth for simplify rewrite identities.
// Each entry maps a one-way canonical rewrite with metadata:
//   - id: unique rule key
//   - priority: lower runs earlier
//   - lhs: AST pattern (supports wildcard nodes `(type: "wild", name: "...")`)
//   - rhs: AST template
//   - label: human-readable identity text
//   - domain-sensitive: metadata flag for domain-caveat identities
// =========================================================================

#import "../expr.typ": *

/// Internal helper `_log-one-rule`.
#let _log-one-rule(id, priority, fname, label) = (
  id: id,
  priority: priority,
  lhs: func(fname, num(1)),
  rhs: num(0),
  label: label + "(1) = 0",
  domain-sensitive: false,
)

/// Public helper `identity-rules`.
#let identity-rules = (
  // Trig Pythagorean
  (
    id: "trig-pythagorean",
    priority: 10,
    lhs: add(pow(func("sin", (type: "wild", name: "u")), num(2)), pow(func("cos", (type: "wild", name: "u")), num(2))),
    rhs: num(1),
    label: "sin²(u) + cos²(u) = 1",
    domain-sensitive: false,
  ),
  // Reciprocal canonical forms
  (
    id: "recip-sin",
    priority: 20,
    lhs: cdiv(num(1), func("sin", (type: "wild", name: "u"))),
    rhs: func("csc", (type: "wild", name: "u")),
    label: "1/sin(u) = csc(u)",
    domain-sensitive: false,
  ),
  (
    id: "recip-cos",
    priority: 21,
    lhs: cdiv(num(1), func("cos", (type: "wild", name: "u"))),
    rhs: func("sec", (type: "wild", name: "u")),
    label: "1/cos(u) = sec(u)",
    domain-sensitive: false,
  ),
  (
    id: "recip-tan",
    priority: 22,
    lhs: cdiv(num(1), func("tan", (type: "wild", name: "u"))),
    rhs: func("cot", (type: "wild", name: "u")),
    label: "1/tan(u) = cot(u)",
    domain-sensitive: false,
  ),
  (
    id: "recip-sinh",
    priority: 23,
    lhs: cdiv(num(1), func("sinh", (type: "wild", name: "u"))),
    rhs: func("csch", (type: "wild", name: "u")),
    label: "1/sinh(u) = csch(u)",
    domain-sensitive: false,
  ),
  (
    id: "recip-cosh",
    priority: 24,
    lhs: cdiv(num(1), func("cosh", (type: "wild", name: "u"))),
    rhs: func("sech", (type: "wild", name: "u")),
    label: "1/cosh(u) = sech(u)",
    domain-sensitive: false,
  ),
  (
    id: "recip-tanh",
    priority: 25,
    lhs: cdiv(num(1), func("tanh", (type: "wild", name: "u"))),
    rhs: func("coth", (type: "wild", name: "u")),
    label: "1/tanh(u) = coth(u)",
    domain-sensitive: false,
  ),
  // Quotients
  (
    id: "quot-sin-cos",
    priority: 30,
    lhs: cdiv(func("sin", (type: "wild", name: "u")), func("cos", (type: "wild", name: "u"))),
    rhs: func("tan", (type: "wild", name: "u")),
    label: "sin(u)/cos(u) = tan(u)",
    domain-sensitive: false,
  ),
  (
    id: "quot-cos-sin",
    priority: 31,
    lhs: cdiv(func("cos", (type: "wild", name: "u")), func("sin", (type: "wild", name: "u"))),
    rhs: func("cot", (type: "wild", name: "u")),
    label: "cos(u)/sin(u) = cot(u)",
    domain-sensitive: false,
  ),
  (
    id: "quot-sinh-cosh",
    priority: 32,
    lhs: cdiv(func("sinh", (type: "wild", name: "u")), func("cosh", (type: "wild", name: "u"))),
    rhs: func("tanh", (type: "wild", name: "u")),
    label: "sinh(u)/cosh(u) = tanh(u)",
    domain-sensitive: false,
  ),
  (
    id: "quot-cosh-sinh",
    priority: 33,
    lhs: cdiv(func("cosh", (type: "wild", name: "u")), func("sinh", (type: "wild", name: "u"))),
    rhs: func("coth", (type: "wild", name: "u")),
    label: "cosh(u)/sinh(u) = coth(u)",
    domain-sensitive: false,
  ),
  // Product collapses
  (
    id: "prod-sin-csc",
    priority: 34,
    lhs: mul(func("sin", (type: "wild", name: "u")), func("csc", (type: "wild", name: "u"))),
    rhs: num(1),
    label: "sin(u)csc(u) = 1",
    domain-sensitive: true,
  ),
  (
    id: "prod-cos-sec",
    priority: 35,
    lhs: mul(func("cos", (type: "wild", name: "u")), func("sec", (type: "wild", name: "u"))),
    rhs: num(1),
    label: "cos(u)sec(u) = 1",
    domain-sensitive: true,
  ),
  (
    id: "prod-tan-cot",
    priority: 36,
    lhs: mul(func("tan", (type: "wild", name: "u")), func("cot", (type: "wild", name: "u"))),
    rhs: num(1),
    label: "tan(u)cot(u) = 1",
    domain-sensitive: true,
  ),
  (
    id: "prod-sinh-csch",
    priority: 37,
    lhs: mul(func("sinh", (type: "wild", name: "u")), func("csch", (type: "wild", name: "u"))),
    rhs: num(1),
    label: "sinh(u)csch(u) = 1",
    domain-sensitive: true,
  ),
  (
    id: "prod-cosh-sech",
    priority: 38,
    lhs: mul(func("cosh", (type: "wild", name: "u")), func("sech", (type: "wild", name: "u"))),
    rhs: num(1),
    label: "cosh(u)sech(u) = 1",
    domain-sensitive: true,
  ),
  (
    id: "prod-tanh-coth",
    priority: 39,
    lhs: mul(func("tanh", (type: "wild", name: "u")), func("coth", (type: "wild", name: "u"))),
    rhs: num(1),
    label: "tanh(u)coth(u) = 1",
    domain-sensitive: true,
  ),
  // Inverse/function cancellation
  (
    id: "sin-arcsin",
    priority: 40,
    lhs: func("sin", func("arcsin", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "sin(arcsin(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "cos-arccos",
    priority: 41,
    lhs: func("cos", func("arccos", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "cos(arccos(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "tan-arctan",
    priority: 42,
    lhs: func("tan", func("arctan", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "tan(arctan(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "csc-arccsc",
    priority: 43,
    lhs: func("csc", func("arccsc", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "csc(arccsc(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "sec-arcsec",
    priority: 44,
    lhs: func("sec", func("arcsec", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "sec(arcsec(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "cot-arccot",
    priority: 45,
    lhs: func("cot", func("arccot", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "cot(arccot(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "sinh-arcsinh",
    priority: 46,
    lhs: func("sinh", func("arcsinh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "sinh(arcsinh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "cosh-arccosh",
    priority: 47,
    lhs: func("cosh", func("arccosh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "cosh(arccosh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "tanh-arctanh",
    priority: 48,
    lhs: func("tanh", func("arctanh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "tanh(arctanh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "csch-arccsch",
    priority: 49,
    lhs: func("csch", func("arccsch", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "csch(arccsch(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "sech-arcsech",
    priority: 50,
    lhs: func("sech", func("arcsech", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "sech(arcsech(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "coth-arccoth",
    priority: 51,
    lhs: func("coth", func("arccoth", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "coth(arccoth(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arcsin-sin",
    priority: 52,
    lhs: func("arcsin", func("sin", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arcsin(sin(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "arccos-cos",
    priority: 53,
    lhs: func("arccos", func("cos", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arccos(cos(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "arctan-tan",
    priority: 54,
    lhs: func("arctan", func("tan", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arctan(tan(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "arccsc-csc",
    priority: 55,
    lhs: func("arccsc", func("csc", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arccsc(csc(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "arcsec-sec",
    priority: 56,
    lhs: func("arcsec", func("sec", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arcsec(sec(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "arccot-cot",
    priority: 57,
    lhs: func("arccot", func("cot", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arccot(cot(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "arcsinh-sinh",
    priority: 58,
    lhs: func("arcsinh", func("sinh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arcsinh(sinh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arccosh-cosh",
    priority: 59,
    lhs: func("arccosh", func("cosh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arccosh(cosh(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "arctanh-tanh",
    priority: 60,
    lhs: func("arctanh", func("tanh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arctanh(tanh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arccsch-csch",
    priority: 61,
    lhs: func("arccsch", func("csch", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arccsch(csch(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "arcsech-sech",
    priority: 62,
    lhs: func("arcsech", func("sech", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arcsech(sech(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "arccoth-coth",
    priority: 63,
    lhs: func("arccoth", func("coth", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "arccoth(coth(u)) = u",
    domain-sensitive: false,
  ),
  // Inverse/function cancellation (short aliases)
  (
    id: "sin-asin",
    priority: 64,
    lhs: func("sin", func("asin", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "sin(asin(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "cos-acos",
    priority: 65,
    lhs: func("cos", func("acos", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "cos(acos(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "tan-atan",
    priority: 66,
    lhs: func("tan", func("atan", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "tan(atan(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "csc-acsc",
    priority: 67,
    lhs: func("csc", func("acsc", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "csc(acsc(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "sec-asec",
    priority: 68,
    lhs: func("sec", func("asec", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "sec(asec(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "cot-acot",
    priority: 69,
    lhs: func("cot", func("acot", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "cot(acot(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "sinh-asinh",
    priority: 70,
    lhs: func("sinh", func("asinh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "sinh(asinh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "cosh-acosh",
    priority: 71,
    lhs: func("cosh", func("acosh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "cosh(acosh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "tanh-atanh",
    priority: 72,
    lhs: func("tanh", func("atanh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "tanh(atanh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "csch-acsch",
    priority: 73,
    lhs: func("csch", func("acsch", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "csch(acsch(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "sech-asech",
    priority: 74,
    lhs: func("sech", func("asech", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "sech(asech(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "coth-acoth",
    priority: 75,
    lhs: func("coth", func("acoth", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "coth(acoth(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "asin-sin",
    priority: 76,
    lhs: func("asin", func("sin", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "asin(sin(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "acos-cos",
    priority: 77,
    lhs: func("acos", func("cos", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "acos(cos(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "atan-tan",
    priority: 78,
    lhs: func("atan", func("tan", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "atan(tan(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "acsc-csc",
    priority: 79,
    lhs: func("acsc", func("csc", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "acsc(csc(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "asec-sec",
    priority: 80,
    lhs: func("asec", func("sec", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "asec(sec(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "acot-cot",
    priority: 81,
    lhs: func("acot", func("cot", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "acot(cot(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "asinh-sinh",
    priority: 82,
    lhs: func("asinh", func("sinh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "asinh(sinh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "acosh-cosh",
    priority: 83,
    lhs: func("acosh", func("cosh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "acosh(cosh(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "atanh-tanh",
    priority: 84,
    lhs: func("atanh", func("tanh", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "atanh(tanh(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "acsch-csch",
    priority: 85,
    lhs: func("acsch", func("csch", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "acsch(csch(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "asech-sech",
    priority: 86,
    lhs: func("asech", func("sech", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "asech(sech(u)) = u",
    domain-sensitive: true,
  ),
  (
    id: "acoth-coth",
    priority: 87,
    lhs: func("acoth", func("coth", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "acoth(coth(u)) = u",
    domain-sensitive: false,
  ),
  // Pythagorean family extensions
  (
    id: "trig-one-plus-tan2",
    priority: 88,
    lhs: add(pow(func("tan", (type: "wild", name: "u")), num(2)), num(1)),
    rhs: pow(func("sec", (type: "wild", name: "u")), num(2)),
    label: "1 + tan²(u) = sec²(u)",
    domain-sensitive: false,
  ),
  (
    id: "trig-one-plus-cot2",
    priority: 89,
    lhs: add(pow(func("cot", (type: "wild", name: "u")), num(2)), num(1)),
    rhs: pow(func("csc", (type: "wild", name: "u")), num(2)),
    label: "1 + cot²(u) = csc²(u)",
    domain-sensitive: false,
  ),
  (
    id: "hyperbolic-cosh2-minus-sinh2",
    priority: 90,
    lhs: add(pow(func("cosh", (type: "wild", name: "u")), num(2)), neg(pow(func("sinh", (type: "wild", name: "u")), num(2)))),
    rhs: num(1),
    label: "cosh²(u) - sinh²(u) = 1",
    domain-sensitive: false,
  ),
  (
    id: "hyperbolic-sech2-plus-tanh2",
    priority: 91,
    lhs: add(pow(func("sech", (type: "wild", name: "u")), num(2)), pow(func("tanh", (type: "wild", name: "u")), num(2))),
    rhs: num(1),
    label: "sech²(u) + tanh²(u) = 1",
    domain-sensitive: false,
  ),
  (
    id: "hyperbolic-coth2-minus-csch2",
    priority: 92,
    lhs: add(pow(func("coth", (type: "wild", name: "u")), num(2)), neg(pow(func("csch", (type: "wild", name: "u")), num(2)))),
    rhs: num(1),
    label: "coth²(u) - csch²(u) = 1",
    domain-sensitive: false,
  ),
  // Function constants / normalizations
  (
    id: "exp-zero",
    priority: 93,
    lhs: func("exp", num(0)),
    rhs: num(1),
    label: "exp(0) = 1",
    domain-sensitive: false,
  ),
  _log-one-rule("ln-one", 94, "ln", "ln"),
  _log-one-rule("log-one", 95, "log", "log"),
  _log-one-rule("log2-one", 96, "log2", "log₂"),
  _log-one-rule("log10-one", 97, "log10", "log₁₀"),
  (
    id: "ln-e",
    priority: 98,
    lhs: func("ln", const-expr("e")),
    rhs: num(1),
    label: "ln(e) = 1",
    domain-sensitive: false,
  ),
  (
    id: "sin-zero",
    priority: 99,
    lhs: func("sin", num(0)),
    rhs: num(0),
    label: "sin(0) = 0",
    domain-sensitive: false,
  ),
  (
    id: "cos-zero",
    priority: 100,
    lhs: func("cos", num(0)),
    rhs: num(1),
    label: "cos(0) = 1",
    domain-sensitive: false,
  ),
  (
    id: "tan-zero",
    priority: 101,
    lhs: func("tan", num(0)),
    rhs: num(0),
    label: "tan(0) = 0",
    domain-sensitive: false,
  ),
  (
    id: "sinh-zero",
    priority: 102,
    lhs: func("sinh", num(0)),
    rhs: num(0),
    label: "sinh(0) = 0",
    domain-sensitive: false,
  ),
  (
    id: "cosh-zero",
    priority: 103,
    lhs: func("cosh", num(0)),
    rhs: num(1),
    label: "cosh(0) = 1",
    domain-sensitive: false,
  ),
  (
    id: "tanh-zero",
    priority: 104,
    lhs: func("tanh", num(0)),
    rhs: num(0),
    label: "tanh(0) = 0",
    domain-sensitive: false,
  ),
  (
    id: "sqrt-square-half-rational",
    priority: 104,
    lhs: pow(pow((type: "wild", name: "u"), num(2)), cdiv(num(1), num(2))),
    rhs: func("abs", (type: "wild", name: "u")),
    label: "sqrt(u^2) = |u|",
    domain-sensitive: false,
  ),
  (
    id: "sqrt-square-half-float",
    priority: 104,
    lhs: pow(pow((type: "wild", name: "u"), num(2)), num(0.5)),
    rhs: func("abs", (type: "wild", name: "u")),
    label: "sqrt(u^2) = |u|",
    domain-sensitive: false,
  ),
  (
    id: "abs-neg",
    priority: 105,
    lhs: func("abs", neg((type: "wild", name: "u"))),
    rhs: func("abs", (type: "wild", name: "u")),
    label: "|-u| = |u|",
    domain-sensitive: false,
  ),
  (
    id: "abs-abs",
    priority: 106,
    lhs: func("abs", func("abs", (type: "wild", name: "u"))),
    rhs: func("abs", (type: "wild", name: "u")),
    label: "||u|| = |u|",
    domain-sensitive: false,
  ),
  (
    id: "abs-div-abs",
    priority: 107,
    lhs: func("abs", cdiv(func("abs", (type: "wild", name: "u")), func("abs", (type: "wild", name: "v")))),
    rhs: func("abs", cdiv((type: "wild", name: "u"), (type: "wild", name: "v"))),
    label: "||u|/|v|| = |u/v|",
    domain-sensitive: false,
  ),
  (
    id: "exp-ln",
    priority: 108,
    lhs: func("exp", func("ln", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "exp(ln(u)) = u",
    domain-sensitive: false,
  ),
  (
    id: "ln-exp",
    priority: 109,
    lhs: func("ln", func("exp", (type: "wild", name: "u"))),
    rhs: (type: "wild", name: "u"),
    label: "ln(exp(u)) = u",
    domain-sensitive: false,
  ),
  // Log structural rewrites (kept for compatibility; domain-sensitive metadata only).
  (
    id: "ln-mul",
    priority: 110,
    lhs: func("ln", mul((type: "wild", name: "a"), (type: "wild", name: "b"))),
    rhs: add(func("ln", (type: "wild", name: "a")), func("ln", (type: "wild", name: "b"))),
    label: "ln(a·b) = ln(a) + ln(b)",
    domain-sensitive: true,
  ),
  (
    id: "ln-div",
    priority: 111,
    lhs: func("ln", cdiv((type: "wild", name: "a"), (type: "wild", name: "b"))),
    rhs: sub(func("ln", (type: "wild", name: "a")), func("ln", (type: "wild", name: "b"))),
    label: "ln(a/b) = ln(a) - ln(b)",
    domain-sensitive: true,
  ),
  (
    id: "ln-pow",
    priority: 112,
    lhs: func("ln", pow((type: "wild", name: "a"), (type: "wild", name: "n"))),
    rhs: mul((type: "wild", name: "n"), func("ln", (type: "wild", name: "a"))),
    label: "ln(a^n) = n·ln(a)",
    domain-sensitive: true,
  ),
)
