name: Build Typst Template

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v3
        with:
          enable-cache: true

      - name: Compile template
        run: typst compile template/main.typ template/main.pdf
      
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-template
          path: template/main.pdf
