[package]
name = "universal-tongji-thesis"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["xialugui<@139.com>"]
license = "MIT"
description = "同济大学学位论文模板。Tongji University Thesis Template."
repository = "https://github.com/xialugui/universal-tongji-thesis"
keywords = ["Tongji University", "thesis"]
categories = ["thesis"]
exclude = [
    ".github",
    "docs",
    "scripts",
    "tests",
    ".typstignore",
    "Justfile",
    ".gitignore",
    "thumbnail.png",
]
compiler = "0.14.0"

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"
