// AMS symbols for Typst 0.14+.
//
// The symbols below address the original 10-point msam/msbm glyphs through
// private-use codepoints in companion OpenType-MATH derivatives. Each symbol
// carries its own font selection, while every unrelated part of an equation
// inherits the document's math font.

#let _symbol(class, font, value) = math.class(
  class,
  text(font: font, fallback: false, symbol(value)),
)
#let _amsa(class, slot) = _symbol(
  class,
  "AMS Symbols A 10",
  str.from-unicode(0xe000 + slot),
)
#let _amsb(class, slot) = _symbol(
  class,
  "AMS Symbols B 10",
  str.from-unicode(0xe100 + slot),
)
#let _amsa-ord(slot) = _amsa("normal", slot)
#let _amsa-bin(slot) = _amsa("binary", slot)
#let _amsa-rel(slot) = _amsa("relation", slot)
#let _amsa-open(slot) = _amsa("opening", slot)
#let _amsa-close(slot) = _amsa("closing", slot)
#let _amsb-ord(slot) = _amsb("normal", slot)
#let _amsb-bin(slot) = _amsb("binary", slot)
#let _amsb-rel(slot) = _amsb("relation", slot)

// AMSa symbols. Slot numbers are those in amssymb.sty/amsfonts.sty.
#let boxdot = _amsa-bin(0x00)
#let boxplus = _amsa-bin(0x01)
#let boxtimes = _amsa-bin(0x02)
#let square = _amsa-ord(0x03)
#let blacksquare = _amsa-ord(0x04)
#let centerdot = _amsa-bin(0x05)
#let lozenge = _amsa-ord(0x06)
#let blacklozenge = _amsa-ord(0x07)
#let circlearrowright = _amsa-rel(0x08)
#let circlearrowleft = _amsa-rel(0x09)
#let rightleftharpoons = _amsa-rel(0x0a)
#let leftrightharpoons = _amsa-rel(0x0b)
#let boxminus = _amsa-bin(0x0c)
#let Vdash = _amsa-rel(0x0d)
#let Vvdash = _amsa-rel(0x0e)
#let vDash = _amsa-rel(0x0f)
#let twoheadrightarrow = _amsa-rel(0x10)
#let twoheadleftarrow = _amsa-rel(0x11)
#let leftleftarrows = _amsa-rel(0x12)
#let rightrightarrows = _amsa-rel(0x13)
#let upuparrows = _amsa-rel(0x14)
#let downdownarrows = _amsa-rel(0x15)
#let upharpoonright = _amsa-rel(0x16)
#let downharpoonright = _amsa-rel(0x17)
#let upharpoonleft = _amsa-rel(0x18)
#let downharpoonleft = _amsa-rel(0x19)
#let rightarrowtail = _amsa-rel(0x1a)
#let leftarrowtail = _amsa-rel(0x1b)
#let leftrightarrows = _amsa-rel(0x1c)
#let rightleftarrows = _amsa-rel(0x1d)
#let Lsh = _amsa-rel(0x1e)
#let Rsh = _amsa-rel(0x1f)
#let rightsquigarrow = _amsa-rel(0x20)
#let leftrightsquigarrow = _amsa-rel(0x21)
#let looparrowleft = _amsa-rel(0x22)
#let looparrowright = _amsa-rel(0x23)
#let circeq = _amsa-rel(0x24)
#let succsim = _amsa-rel(0x25)
#let gtrsim = _amsa-rel(0x26)
#let gtrapprox = _amsa-rel(0x27)
#let multimap = _amsa-rel(0x28)
#let therefore = _amsa-rel(0x29)
#let because = _amsa-rel(0x2a)
#let doteqdot = _amsa-rel(0x2b)
#let triangleq = _amsa-rel(0x2c)
#let precsim = _amsa-rel(0x2d)
#let lesssim = _amsa-rel(0x2e)
#let lessapprox = _amsa-rel(0x2f)
#let eqslantless = _amsa-rel(0x30)
#let eqslantgtr = _amsa-rel(0x31)
#let curlyeqprec = _amsa-rel(0x32)
#let curlyeqsucc = _amsa-rel(0x33)
#let preccurlyeq = _amsa-rel(0x34)
#let leqq = _amsa-rel(0x35)
#let leqslant = _amsa-rel(0x36)
#let lessgtr = _amsa-rel(0x37)
#let backprime = _amsa-ord(0x38)
#let risingdotseq = _amsa-rel(0x3a)
#let fallingdotseq = _amsa-rel(0x3b)
#let succcurlyeq = _amsa-rel(0x3c)
#let geqq = _amsa-rel(0x3d)
#let geqslant = _amsa-rel(0x3e)
#let gtrless = _amsa-rel(0x3f)
#let sqsubset = _amsa-rel(0x40)
#let sqsupset = _amsa-rel(0x41)
#let vartriangleright = _amsa-rel(0x42)
#let vartriangleleft = _amsa-rel(0x43)
#let trianglerighteq = _amsa-rel(0x44)
#let trianglelefteq = _amsa-rel(0x45)
#let bigstar = _amsa-ord(0x46)
#let between = _amsa-rel(0x47)
#let blacktriangledown = _amsa-ord(0x48)
#let blacktriangleright = _amsa-rel(0x49)
#let blacktriangleleft = _amsa-rel(0x4a)
#let vartriangle = _amsa-rel(0x4d)
#let blacktriangle = _amsa-ord(0x4e)
#let triangledown = _amsa-ord(0x4f)
#let eqcirc = _amsa-rel(0x50)
#let lesseqgtr = _amsa-rel(0x51)
#let gtreqless = _amsa-rel(0x52)
#let lesseqqgtr = _amsa-rel(0x53)
#let gtreqqless = _amsa-rel(0x54)
#let Rrightarrow = _amsa-rel(0x56)
#let Lleftarrow = _amsa-rel(0x57)
#let veebar = _amsa-bin(0x59)
#let barwedge = _amsa-bin(0x5a)
#let doublebarwedge = _amsa-bin(0x5b)
#let angle = _amsa-ord(0x5c)
#let measuredangle = _amsa-ord(0x5d)
#let sphericalangle = _amsa-ord(0x5e)
#let varpropto = _amsa-rel(0x5f)
#let smallsmile = _amsa-rel(0x60)
#let smallfrown = _amsa-rel(0x61)
#let Subset = _amsa-rel(0x62)
#let Supset = _amsa-rel(0x63)
#let Cup = _amsa-bin(0x64)
#let Cap = _amsa-bin(0x65)
#let curlywedge = _amsa-bin(0x66)
#let curlyvee = _amsa-bin(0x67)
#let leftthreetimes = _amsa-bin(0x68)
#let rightthreetimes = _amsa-bin(0x69)
#let subseteqq = _amsa-rel(0x6a)
#let supseteqq = _amsa-rel(0x6b)
#let bumpeq = _amsa-rel(0x6c)
#let Bumpeq = _amsa-rel(0x6d)
#let lll = _amsa-rel(0x6e)
#let ggg = _amsa-rel(0x6f)
#let circledS = _amsa-ord(0x73)
#let pitchfork = _amsa-rel(0x74)
#let dotplus = _amsa-bin(0x75)
#let backsim = _amsa-rel(0x76)
#let backsimeq = _amsa-rel(0x77)
#let complement = _amsa-ord(0x7b)
#let intercal = _amsa-bin(0x7c)
#let circledcirc = _amsa-bin(0x7d)
#let circledast = _amsa-bin(0x7e)
#let circleddash = _amsa-bin(0x7f)

// AMSb negated relations and variants.
#let lvertneqq = _amsb-rel(0x00)
#let gvertneqq = _amsb-rel(0x01)
#let nleq = _amsb-rel(0x02)
#let ngeq = _amsb-rel(0x03)
#let nless = _amsb-rel(0x04)
#let ngtr = _amsb-rel(0x05)
#let nprec = _amsb-rel(0x06)
#let nsucc = _amsb-rel(0x07)
#let lneqq = _amsb-rel(0x08)
#let gneqq = _amsb-rel(0x09)
#let nleqslant = _amsb-rel(0x0a)
#let ngeqslant = _amsb-rel(0x0b)
#let lneq = _amsb-rel(0x0c)
#let gneq = _amsb-rel(0x0d)
#let npreceq = _amsb-rel(0x0e)
#let nsucceq = _amsb-rel(0x0f)
#let precnsim = _amsb-rel(0x10)
#let succnsim = _amsb-rel(0x11)
#let lnsim = _amsb-rel(0x12)
#let gnsim = _amsb-rel(0x13)
#let nleqq = _amsb-rel(0x14)
#let ngeqq = _amsb-rel(0x15)
#let precneqq = _amsb-rel(0x16)
#let succneqq = _amsb-rel(0x17)
#let precnapprox = _amsb-rel(0x18)
#let succnapprox = _amsb-rel(0x19)
#let lnapprox = _amsb-rel(0x1a)
#let gnapprox = _amsb-rel(0x1b)
#let nsim = _amsb-rel(0x1c)
#let ncong = _amsb-rel(0x1d)
#let diagup = _amsb-ord(0x1e)
#let diagdown = _amsb-ord(0x1f)
#let varsubsetneq = _amsb-rel(0x20)
#let varsupsetneq = _amsb-rel(0x21)
#let nsubseteqq = _amsb-rel(0x22)
#let nsupseteqq = _amsb-rel(0x23)
#let subsetneqq = _amsb-rel(0x24)
#let supsetneqq = _amsb-rel(0x25)
#let varsubsetneqq = _amsb-rel(0x26)
#let varsupsetneqq = _amsb-rel(0x27)
#let subsetneq = _amsb-rel(0x28)
#let supsetneq = _amsb-rel(0x29)
#let nsubseteq = _amsb-rel(0x2a)
#let nsupseteq = _amsb-rel(0x2b)
#let nparallel = _amsb-rel(0x2c)
#let nmid = _amsb-rel(0x2d)
#let nshortmid = _amsb-rel(0x2e)
#let nshortparallel = _amsb-rel(0x2f)
#let nvdash = _amsb-rel(0x30)
#let nVdash = _amsb-rel(0x31)
#let nvDash = _amsb-rel(0x32)
#let nVDash = _amsb-rel(0x33)
#let ntrianglerighteq = _amsb-rel(0x34)
#let ntrianglelefteq = _amsb-rel(0x35)
#let ntriangleleft = _amsb-rel(0x36)
#let ntriangleright = _amsb-rel(0x37)
#let nleftarrow = _amsb-rel(0x38)
#let nrightarrow = _amsb-rel(0x39)
#let nLeftarrow = _amsb-rel(0x3a)
#let nRightarrow = _amsb-rel(0x3b)
#let nLeftrightarrow = _amsb-rel(0x3c)
#let nleftrightarrow = _amsb-rel(0x3d)

// AMSb miscellaneous symbols.
#let divideontimes = _amsb-bin(0x3e)
#let varnothing = _amsb-ord(0x3f)
#let nexists = _amsb-ord(0x40)
#let Finv = _amsb-ord(0x60)
#let Game = _amsb-ord(0x61)
#let mho = _amsb-ord(0x66)
#let eth = _amsb-ord(0x67)
#let eqsim = _amsb-rel(0x68)
#let beth = _amsb-ord(0x69)
#let gimel = _amsb-ord(0x6a)
#let daleth = _amsb-ord(0x6b)
#let lessdot = _amsb-bin(0x6c)
#let gtrdot = _amsb-bin(0x6d)
#let ltimes = _amsb-bin(0x6e)
#let rtimes = _amsb-bin(0x6f)
#let shortmid = _amsb-rel(0x70)
#let shortparallel = _amsb-rel(0x71)
#let smallsetminus = _amsb-bin(0x72)
#let thicksim = _amsb-rel(0x73)
#let thickapprox = _amsb-rel(0x74)
#let approxeq = _amsb-rel(0x75)
#let succapprox = _amsb-rel(0x76)
#let precapprox = _amsb-rel(0x77)
#let curvearrowleft = _amsb-rel(0x78)
#let curvearrowright = _amsb-rel(0x79)
#let digamma = _amsb-ord(0x7a)
#let varkappa = _amsb-ord(0x7b)
#let Bbbk = _amsb-ord(0x7c)
#let hslash = _amsb-ord(0x7d)
#let hbar = _amsb-ord(0x7e)
#let backepsilon = _amsb-rel(0x7f)

// Symbols and delimiters provided transitively by amsfonts.
#let yen = _amsa-ord(0x55)
#let checkmark = _amsa-ord(0x58)
#let circledR = _amsa-ord(0x72)
#let maltese = _amsa-ord(0x7a)
#let ulcorner = _amsa-open(0x70)
#let urcorner = _amsa-close(0x71)
#let llcorner = _amsa-open(0x78)
#let lrcorner = _amsa-close(0x79)
#let dashrightarrow = _amsa-rel(0x80)
#let dashleftarrow = _amsa-rel(0x81)
#let Join = _amsb-rel(0x80)
#let lhd = _amsa-bin(0x43)
#let unlhd = _amsa-bin(0x45)
#let rhd = _amsa-bin(0x42)
#let unrhd = _amsa-bin(0x44)

// AMS aliases, including the historical amsfonts alphabet names.
#let restriction = upharpoonright
#let Doteq = doteqdot
#let doublecup = Cup
#let doublecap = Cap
#let llless = lll
#let gggtr = ggg
#let Box = square
#let Diamond = lozenge
#let leadsto = rightsquigarrow
#let dasharrow = dashrightarrow
#let mathbb = math.bb
#let mathfrak = math.frak
#let frak = mathfrak
#let Bbb = mathbb
#let bold = math.bold
#let widehat = math.hat
#let widetilde = math.tilde
