[package]
name = "gribouille"
version = "0.3.0"
compiler = "0.14.0"
entrypoint = "lib.typ"
authors = ["Mickaël Canouil <https://mickael.canouil.fr>"]
license = "MIT"
description = "Create elegant graphics with the Grammar of Graphics."
repository = "https://github.com/mcanouil/gribouille"
homepage = "https://m.canouil.dev/gribouille"
keywords = ["plot", "chart", "grammar-of-graphics", "visualization"]
categories = ["visualization"]
exclude = [
  ".github",
  ".gitignore",
  "docs",
  "examples",
  "tests",
  "tools",
  "GLOSSARY.md",
  "ARCHITECTURE.md",
  "CONTRIBUTING.md",
  "CHANGELOG.md",
  "CITATION.cff",
]
