#let default = (
    variant: "iec",
    scale: (x: 1.0, y: 1.0),
    stroke: (
        thickness: .8pt,
        paint: auto,
        join: "miter",
        cap: "butt",
        miter-limit: 4,
        dash: none,
    ),
    fill: auto,
    background: white,
    foreground: black,
    label: (
        scale: auto,
        content: none,
        distance: 7pt,
        anchor: "north",
    ),
    node: (
        stroke: (
            thickness: .4pt,
            paint: auto,
        ),
        fill: auto,
        nofill: auto,
        radius: .05,
    ),
    wire: (
        stroke: (
            thickness: .5pt,
        ),
    ),
    arrow: (
        symbol: ">",
        scale: 1.0,
        angle: 55deg,
        length: 40pt,
        ratio: (0.5, 0.5),
        stroke: (
            thickness: 1pt,
            paint: auto,
        ),
        variable: (
            symbol: auto,
            scale: 1.0,
            stroke: auto,
            length: auto,
            angle: auto,
            ratio: auto,
        ),
        preset: (
            symbol: "|",
            scale: 1.0,
            stroke: auto,
            length: auto,
            angle: auto,
            ratio: auto,
            width: 10pt,
        ),
        sensor: (
            symbol: none,
            scale: 1.0,
            stroke: auto,
            length: auto,
            sensor-length: 12pt,
            angle: auto,
            ratio: auto,
        ),
        radiation: (
            symbol: auto,
            scale: 1,
            stroke: (
                thickness: 0.55pt,
            ),
            distance: 3pt,
            length: 12pt,
            angle: -120deg,
            reversed: false,
        ),
        adjustable: (
            symbol: auto,
            scale: 1.0,
            stroke: auto,
            length: 0.8,
        ),
    ),
    decoration: (
        symbol: ">",
        scale: 1.0,
        stroke: (
            thickness: .6pt,
            paint: auto,
        ),
        content: none,
        distance: 9pt,
        position: (x: "east", y: "north"),
        anchor: "north-east",
        invert: false,
        current: (
            symbol: auto,
            scale: 1.0,
            stroke: auto,
            content: auto,
            distance: auto,
            position: auto,
            anchor: auto,
            invert: auto,
            wire: (
                symbol: auto,
                scale: auto,
                stroke: auto,
                content: auto,
                distance: 7pt,
                position: 50%,
                anchor: "north",
                invert: auto,
            ),
        ),
        flow: (
            symbol: auto,
            scale: 1.0,
            stroke: (
                thickness: 0.55pt,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            content: auto,
            distance: auto,
            position: auto,
            anchor: auto,
            invert: auto,
            length: 0.7,
            indent: 0.2,
            label-ratio: 50%,
        ),
        voltage: (
            symbol: auto,
            scale: 1.0,
            stroke: auto,
            content: auto,
            distance: 2pt,
            position: auto,
            anchor: auto,
            invert: auto,
            start: (-.4, .1),
            end: (.4, .1),
            center: (0, .3),
        ),
    ),
    debug: (
        stroke: (
            thickness: .2pt,
            paint: red,
        ),
        enabled: false,
        radius: .7pt,
        angle: -30deg,
        shift: 3pt,
        inset: 1pt,
        font: 3pt,
        fill: red,
    ),
    // Components
    stub: (
        scale: auto,
        length: .8,
    ),
    capacitor: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: .8,
        distance: .25,
        radius: 0.6,
        angle: 40deg,
    ),
    diode: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: .3,
        width: .25,
        tunnel-length: .11,
    ),
    opamp: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 1.8,
        height: 1.75,
        padding: .28,
        sign-stroke: .55pt,
        sign-size: .14,
        sign-delta: .45,
    ),
    switch: (
        variant: auto,
        scale: auto,
        stroke: auto,
        width: .8,
        angle: 35deg,
    ),
    fuse: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: .88,
        height: .88 / 2.4,
        asymmetry: 25%,
    ),
    ground: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: 0.22,
        distance: 0.28,
    ),
    frame: (
        variant: auto,
        scale: auto,
        stroke: auto,
        number: 3,
        width: 0.46,
        angle: 20deg,
        depth: 0.25,
        distance: 0.28,
    ),
    earth: (
        variant: auto,
        scale: auto,
        stroke: auto,
        width: .53,
        delta: .09,
        spacing: .11,
        distance: .28,
    ),
    vcc: (
        variant: auto,
        scale: auto,
        stroke: auto,
        angle: 35deg,
        radius: .4,
        distance: .6,
    ),
    vee: (
        variant: auto,
        scale: auto,
        stroke: auto,
        angle: 35deg,
        radius: .4,
        distance: .6,
    ),
    inductor: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 1.41,
        height: 1.41 / 3,
        bumps: 3,
    ),
    resistor: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 1.41,
        height: .47,
        zigs: 3,
    ),
    vsource: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: .53,
        padding: .25,
        sign-stroke: .55pt,
        sign-size: .14,
        sign-delta: .07,
    ),
    isource: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: .53,
        padding: .25,
        arrow-scale: 1,
    ),
    acmotor: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: .49,
        magnet-width: 1.23,
        magnet-height: 1.23 / 4,
    ),
    dcmotor: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: .49,
        magnet-width: 1.23,
        magnet-height: 1.23 / 4,
    ),
    bjt: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: .65,
        base-height: .6,
        base-distance: .12,
        aperture: 50deg,
    ),
    mosfet: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        height: 0.7,
        width: 1,
        base-width: 1.2,
        base-spacing: 0.16,
        base-distance: 0.16,
        radius: 0.85,
    ),
    antenna: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: none,
        number: 3,
        distance: 0.8,
        spacing: 0.35,
        length: 0.5,
    ),
    transformer: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: 0.35,
        distance: 0.45,
    ),
    converter: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 1.7,
        height: 0.7,
        arrow-width: 0.4,
        label: (
            align: "center",
        ),
    ),
    mcu: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 3,
        min-height: 1,
        padding: 0.2,
        spacing: 0.4,
    ),
    round-meter: (
        variant: auto,
        scale: auto,
        stroke: auto,
        radius: .47,
    ),
    button: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: .8,
        angle: 23deg,
        overlap: .1,
        distance: .7,
        lamp-distance: .12,
        button-width: .33,
        button-height: .16,
        button-omega: 1,
        latch-size: 0.1,
        latch-padding: 0.15,
    ),
    circulator: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        radius: 0.53,
        arrow-radius: 0.35,
    ),
    logic: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 1.1,
        min-height: 1,
        padding: 0.2,
        invert-width: 0.3,
        invert-height: 0.2,
        spacing: .4,
    ),
    flipflop: (
        variant: auto,
        scale: auto,
        stroke: auto,
        fill: auto,
        width: 1.8,
        height: 2,
        padding: 0.2,
        spacing: 0.5,
    ),
)
