// Uses structural data from RCSB PDB / wwPDB.
// PDB ID: 1CRN
// PDB DOI: https://doi.org/10.2210/pdb1CRN/pdb
// Deposition authors: Hendrickson, W.A.; Teeter, M.M.
// PDB archive data files are available under CC0 1.0.
// Primary citation: Teeter, M.M. (1984) Proc Natl Acad Sci U S A 81: 6014-6018.
// Article DOI: https://doi.org/10.1073/pnas.81.19.6014

#import "@preview/molfig:0.1.2"

#set page(width: 100mm, height: auto, margin: 8mm)
#set text(font: "New Computer Modern", size: 9pt)

#let data = read("data/1crn.bcif", encoding: none)
#let obj = molfig.to-obj(data, format: "bcif", representation: "cartoon")
#let mtl = molfig.to-mtl(data, format: "bcif", representation: "cartoon")
#let stl = molfig.to-stl(data, format: "bcif", representation: "cartoon")
#let ply = molfig.to-ply(data, format: "bcif", representation: "cartoon")

#table(
  columns: (1fr, 1fr),
  inset: 5pt,
  stroke: 0.4pt + luma(75%),
  table.header([*Export*], [*Generated bytes*]),
  [OBJ], [#obj.len()],
  [MTL], [#mtl.len()],
  [STL], [#stl.len()],
  [PLY], [#ply.len()],
)
