[package]
name = "furiruby"
version = "0.1.0"
entrypoint = "furiruby.typ"
authors = ["Park, Jonghyeon <https://github.com/shapelayer>"]
license = "MIT"
description = "Ruby implementation for furigana annotation in Typst."
exclude = ["*.pdf", "example.typ"]
