[package]
name = "hes-so-core"
version = "0.1.0"
compiler = "0.15.0"
authors = [
  "Silvan Zahno <https://github.com/tschinz>",
  "Rémi Heredero <https://github.com/Klagarge>",
  "Louis Heredero <https://github.com/LordBaryhobal>",
  "HES-SO <https://hes-so.ch>"
]
repository = "https://github.com/HES-SO/Typst-HES-SO-core"
homepage = "https://www.hes-so.ch/accueil"
license = "MIT"
description = "Common library for most HES-SO templates and packages."
entrypoint = "src/lib.typ"
categories = ["components", "layout", "utility", ]
disciplines = ["engineering", "computer-science", "education"]
keywords = [
  "Package",
  "Thesis",
  "Report",
  "University",
  "HES-SO",
  "MSE",
]
exclude = [
  "CONTRIBUTING.md"
]
