[package]
name = "vivid-cv"
version = "0.1.1"
entrypoint = "vivid-cv.typ"
authors = ["Loïc Fontaine <https://lfontaine.ch/>"]
license = "MIT"
description = "A colourful, ATS friendly, design-forward resume template with a profile picture."
repository = "https://github.com/loicfontaine/vivid-cv"
categories = ["cv"]
keywords = ["cv", "resume", "ATS", "photo", "design"]
compiler = "0.13.0"
exclude = [
    "*.pdf",
]

[template]
path = "example"
entrypoint = "main.typ"
thumbnail = "preview.png"