[package]
name = "xmlit"
version = "0.1.3"
compiler = "0.15.0"
repository = "https://github.com/siefkenj/typst-xmlit"
entrypoint = "src/lib.typ"
authors = ["Jason Siefken <https://github.com/siefkenj>"]
categories = ["utility"]
license = "MIT"
description = "Generate XML documents using native syntax, serialize, and validate with RelaxNG schemas."
keywords = ["xml", "serialization", "markup", "relaxng", "relax-ng", "schema"]
exclude = [
  "tests",
  "plugin",
  "src/elem/elem.test.typ",
  "src/relaxng/relaxng.test.typ",
]

[tool.tytanic]
tests = "tests"
