// ---------------------------------------------------------------------------
// --------------------------------DECLARATION--------------------------------
// ---------------------------------------------------------------------------

/// Renders the signature block used by student declarations.
///
/// - `author`: Name of the student.
/// - `role`: Localized role displayed below the signature line.
#let _declaration-signature(author, role) = {
  grid(
    columns: (1fr, auto),

    [],
    align(right)[
      #block(
        width: 7cm,
        inset: (top: 0.65em),
        stroke: (top: 0.05em),
      )[
        #align(center)[
          #text(style: "italic")[#author] \
          #role
        ]
      ]
    ],
  )
}

/// Renders the English student declaration.
///
/// - `author`: Author's name
/// - `date`: Formatted declaration date.
/// - `thesis-type`: Thesis type, such as `"bsc"` or `"msc"`.
#let _en-declaration(
  author,
  date,
  thesis-type,
) = {
  align(center)[
    #text(weight: "bold", size: 14pt)[STUDENT DECLARATION]
  ]

  block()[
    I, #author, the undersigned, hereby declare that the present
    #if thesis-type == "msc" {
      [Master's Thesis]
    } else {
      [Bachelor's Thesis]
    }
    work has been prepared by myself and without any unauthorized help or
    assistance. Only the specified sources (references, tools, etc.) were used.
    All parts taken from other sources word by word, or after rephrasing but
    with identical meaning, were unambiguously identified with explicit
    reference to the sources utilized. In the Appendix, I have clearly
    indicated whether I used artificial intelligence tools in preparing the
    thesis; if so, I have specified the manner and extent of their use in the
    table. I acknowledge that I bear full responsibility for any content
    generated by artificial intelligence -- regardless of the extent of its use.

    I agree that the basic information of my present work (author(s), title,
    abstracts in English and in a second language, year of preparation, name
    of advisor(s)) will be made publicly available on the internet by BME VIK,
    and the full text of the work will be available to persons registered in
    the BME Directory. I declare that the submitted hardcopy of the thesis work
    and its electronic version are identical.

    Full text of thesis works classified upon the decision of the Dean will be
    published after a period of three years.
  ]

  block(above: 4em, below: 4em)[
    Budapest, #date
  ]

  _declaration-signature(author, "student")
}

/// Renders the Hungarian student declaration.
///
/// - `author`: Author's name
/// - `date`: Formatted declaration date.
/// - `thesis-type`: Thesis type, such as `"bsc"` or `"msc"`.
#let _hu-declaration(
  author,
  date,
  thesis-type,
) = {
  align(center)[
    #text(weight: "bold", size: 14pt)[HALLGATÓI NYILATKOZAT]
  ]

  block(above: 2em)[
    #set par(first-line-indent: (amount: 2em, all: true))

    Alulírott #author, szigorló hallgató kijelentem, hogy ezt a
    #if thesis-type == "msc" {
      [diplomatervet]
    } else {
      [szakdolgozatot]
    }
    meg nem engedett segítség nélkül, saját magam készítettem, csak a megadott
    forrásokat (szakirodalom, eszközök stb.) használtam fel. Minden olyan részt,
    melyet szó szerint, vagy azonos értelemben, de átfogalmazva más forrásból
    átvettem, egyértelműen, a forrás megadásával megjelöltem. A Függelékben
    egyértelműen megjelöltem, hogy a mesterséges intelligencia eszközeit
    alkalmaztam-e a dolgozat elkészítéséhez; amennyiben igen, annak módját és
    mértékét a táblázatban közöltem. Tudomásul veszem, hogy a mesterséges
    intelligenciával generált tartalomért -- annak mértékétől függetlenül --
    teljes felelősséggel tartozom.

    Hozzájárulok, hogy a jelen munkám alapadatait (szerző(k), cím, angol és
    magyar nyelvű tartalmi kivonat, készítés éve, konzulens(ek) neve) a BME VIK
    nyilvánosan hozzáférhető elektronikus formában, a munka teljes szövege pedig
    a BME Címtárban regisztrált személyek számára elérhető legyen. Kijelentem,
    hogy a benyújtott munka és annak elektronikus verziója megegyezik. Dékáni
    engedéllyel titkosított diplomatervek esetén a dolgozat szövege csak 3 év
    eltelte után válik hozzáférhetővé.
  ]

  block(above: 4em, below: 4em)[
    Budapest, #date
  ]

  _declaration-signature(author, "hallgató")
}

/// Renders the localized student declaration.
///
/// Selects the Hungarian or English declaration based on `lang`.
///
/// - `authors`: Array of author names. The first author is used for the declaration.
/// - `date`: Formatted declaration date.
/// - `lang`: Document language, such as `"hu"` or `"en"`.
/// - `thesis-type`: Thesis type, such as `"bsc"` or `"msc"`.
#let declaration(
  authors,
  date,
  lang,
  thesis-type,
) = {
  let author = authors.first()

  if lang == "en" {
    _en-declaration(author, date, thesis-type)
  } else {
    _hu-declaration(author, date, thesis-type)
  }
}