[package]
name = "htlium"
version = "1.6.0"
entrypoint = "src/template.typ"
authors = ["Elias Pöschl <@DeltaAT>"]
license = "MIT"
description = "A template for school protocols, designed for HTL Salzburg, but adaptable to other schools as well."
repository = "https://github.com/DeltaAT/htl-protocol"
compiler = "0.14.0"
exclude = ["example"]
categories = ["layout", "paper"]
disciplines = ["computer-science", "education"]

[template]
path = "src"
entrypoint = "template.typ"
thumbnail = "thumbnail.png"