[package]
name = "circuiteria"
version = "0.2.1"
compiler = "0.13.1"
repository = "https://git.kb28.ch/HEL/circuiteria"
entrypoint = "src/lib.typ"
authors = [
    "Louis Heredero <https://git.kb28.ch/HEL>"
]
categories = [ "visualization" ]
license = "Apache-2.0"
description = "Drawing block circuits made easy, using CeTZ"
keywords = [ "circuit", "block", "draw" ]
exclude = [ "gallery", "justfile", "doc" ]