#let title = "Bachelorarbeit Title"
#let thesis-type = "Bachelorarbeit"
#let author = "Max Mustermann"
#let description = "Thema Beschreibung"
#let date = datetime.today()
#let date-of-submission = "14.07.2025"
#let place = "Bocholt"
#let keywords = ("Bachelorarbeit", "Westfälische Hochschule", "Informatik")
#let degree = "Bachelor of Science (B.Sc.)"
#let studyCourse = "Informatik.Softwaresysteme"
#let department = "Wirtschaft und Informationstechnik"
#let first-examiner = "Prof. Dr. Max Mustermann"
#let second-examiner = "Prof. Dr. Max Mustermann"
#let bibliography = bibliography.with("bibliography.bib")