[package]
name = "typograph"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Benjamin Cichos <https://github.com/BenCichos>"]
license = "MIT"
description = "Draw unopinionated diagrams: nodes, edges, curves, ports."
repository = "https://github.com/BenCichos/typograph"
keywords = ["diagram", "graph", "node", "edge", "drawing"]
categories = ["visualization"]
compiler = "0.15.1"
exclude = [".github", ".gitignore", "/*.pdf", "img/*"]
