[package]
name = "telepresentation"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Alexandre Meneceur <alexandre.meneceur@ip-paris.fr>"]
license = "MIT"
description = "Télécom Paris themed Touying presentation template."
repository = "https://github.com/ameneceur/tp_slides_template"
categories = ["presentation", "components"]
keywords = ["touying", "slides", "telepresentation", "academic", "telecom"]
exclude = ["example.pdf", "example.typ", "previews", "TODO.md", ".vscode"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
