[package]
name = "xkcdyst"
version = "0.1.0"
entrypoint = "xkcd-lib.typ"
authors = ["gelden324 <@gelden324>"]
repository = "https://github.com/gelden324/xkcd-typst"
keywords = ["xkcd", "sketch", "hand drawing", "penciline"]
categories = ["visualization", "components", "drawing"]
disciplines = ["education", "computer-science"]
compiler = "0.15.0"
exclude = [
	".gitignore",
	"*.pdf",
]

description = "render hand drawn xkcd style drawings."
license = "MIT"