#let colors = (
  red: rgb("#ff0000"),
  orange: rgb("ff9900"),
  green: rgb("#00e600"),
  blue: rgb("#3333ff"),
  white: rgb("#ffffcc"),
  yellow: rgb("#ffff1a"),
  grey: rgb("#595959"),
)

#let pll-cube = (
  u : (colors.white, colors.white, colors.white, 
        colors.white, colors.white, colors.white, 
        colors.white, colors.white, colors.white),
  d : (colors.yellow, colors.yellow, colors.yellow, 
          colors.yellow, colors.yellow, colors.yellow, 
          colors.yellow, colors.yellow, colors.yellow),
  f : (colors.green, colors.green, colors.green, 
          colors.green, colors.green, colors.green, 
          colors.green, colors.green, colors.green),
  b : (colors.blue, colors.blue, colors.blue, 
          colors.blue, colors.blue, colors.blue, 
          colors.blue, colors.blue, colors.blue),
  r : (colors.red, colors.red, colors.red, 
          colors.red, colors.red, colors.red, 
          colors.red, colors.red, colors.red),
  l : (colors.orange, colors.orange, colors.orange, 
          colors.orange, colors.orange, colors.orange, 
          colors.orange, colors.orange, colors.orange)
)

#let oll-cube = (
  u : (colors.white, colors.white, colors.white, 
        colors.white, colors.white, colors.white, 
        colors.white, colors.white, colors.white),
  d : (colors.yellow, colors.yellow, colors.yellow, 
          colors.yellow, colors.yellow, colors.yellow, 
          colors.yellow, colors.yellow, colors.yellow),
  f : (colors.green, colors.green, colors.green, 
          colors.green, colors.green, colors.green, 
          colors.grey, colors.grey, colors.grey),
  b : (colors.blue, colors.blue, colors.blue, 
          colors.blue, colors.blue, colors.blue, 
          colors.grey, colors.grey, colors.grey),
  r : (colors.red, colors.red, colors.red, 
          colors.red, colors.red, colors.red, 
          colors.grey, colors.grey, colors.grey),
  l : (colors.orange, colors.orange, colors.orange, 
          colors.orange, colors.orange, colors.orange, 
          colors.grey, colors.grey, colors.grey),
)

#let f2l-cube = (
  u : (colors.white, colors.white, colors.white, 
        colors.white, colors.white, colors.white, 
        colors.white, colors.white, colors.white),
  d : (colors.grey, colors.grey, colors.grey, 
          colors.grey, colors.grey, colors.grey, 
          colors.grey, colors.grey, colors.grey),
  f : (colors.green, colors.green, colors.green, 
          colors.green, colors.green, colors.green, 
          colors.grey, colors.grey, colors.grey),
  b : (colors.blue, colors.blue, colors.blue, 
          colors.blue, colors.blue, colors.blue, 
          colors.grey, colors.grey, colors.grey),
  r : (colors.red, colors.red, colors.red, 
          colors.red, colors.red, colors.red, 
          colors.grey, colors.grey, colors.grey),
  l : (colors.orange, colors.orange, colors.orange, 
          colors.orange, colors.orange, colors.orange, 
          colors.grey, colors.grey, colors.grey),
)