[package]
name = "basic-postcard"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["GrossKahn"]
license = "MIT"
description = "Design and print your own postcards."
repository = "https://codeberg.org/GrossKahn/basic-typst-postcard-template"
keywords = ["postcard", "greetingcard"]
categories = ["fun", "flyer"]
disciplines = ["design"]

[template]
path = "template"
entrypoint =  "main.typ"
thumbnail = "thumbnail.png"