[package]
name = "tfguf"
version = "0.0.5"
entrypoint = "unirfisica.typ"
authors = ["Alberto Corbi (UNIR)"]
license = "MIT"
description = "This Typst template is intended for writing Bachelor’s Degree Final Projects for the Physics Degree at UNIR University."
repository = "https://github.com/pammacdotnet/TFGUF"
categories = ["thesis"]

[template]
path = "template"
entrypoint = "tfg.typ"
thumbnail = "portada.png"
