[package]
name = "simple-nwu-year-paper"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Easecond"]
license = "MIT"
description = "西北大学学年论文。 | Northwest University (China) Academic Year Paper."
repository = "https://github.com/Easecond/nwu-academic-year-paper"
keywords = ["Northwest University", "paper"]
categories = ["paper"]

[template]
path = "template"
entrypoint = "paper.typ"
thumbnail = "thumbnail.png"
