// Named SMILES strings for common molecules, bundled so documents can draw
// familiar structures offline without looking up their SMILES. Each entry is
// written in an atom order that gives a recognizable textbook layout, and each
// stereocenter encodes the naturally occurring or commonly sold isomer.

#let molecules = (
  // Small molecules and gases
  water: "O",
  methane: "C",
  ammonia: "N",
  carbon-dioxide: "O=C=O",
  hydrogen-chloride: "Cl",
  ethylene: "C=C",
  acetylene: "C#C",
  butadiene: "C=CC=C",
  isoprene: "C=CC(C)=C",
  cyclohexane: "C1CCCCC1",
  hexane: "CCCCCC",

  // Common solvents and simple organics
  methanol: "CO",
  ethanol: "CCO",
  isopropanol: "CC(C)O",
  glycerol: "OCC(O)CO",
  formaldehyde: "C=O",
  acetone: "CC(C)=O",
  acetic-acid: "CC(=O)O",
  diethyl-ether: "CCOCC",
  tetrahydrofuran: "C1CCOC1",
  dichloromethane: "ClCCl",
  chloroform: "ClC(Cl)Cl",
  dimethyl-sulfoxide: "CS(C)=O",
  dimethylformamide: "CN(C)C=O",
  acetonitrile: "CC#N",
  ethyl-acetate: "CCOC(C)=O",
  urea: "NC(N)=O",

  // Aromatics and heterocycles
  benzene: "c1ccccc1",
  toluene: "Cc1ccccc1",
  phenol: "Oc1ccccc1",
  aniline: "Nc1ccccc1",
  benzaldehyde: "O=Cc1ccccc1",
  benzoic-acid: "OC(=O)c1ccccc1",
  nitrobenzene: "[O-][N+](=O)c1ccccc1",
  naphthalene: "c1ccc2ccccc2c1",
  anthracene: "c1ccc2cc3ccccc3cc2c1",
  pyridine: "c1ccncc1",
  pyrrole: "[nH]1cccc1",
  furan: "c1ccoc1",
  thiophene: "c1ccsc1",
  imidazole: "[nH]1ccnc1",
  indole: "[nH]1ccc2ccccc12",
  quinoline: "c1ccc2ncccc2c1",
  pyrimidine: "c1cncnc1",

  // Nucleobases
  adenine: "[nH]1cnc2c(N)ncnc12",
  guanine: "NC1=NC2=C(N=CN2)C(=O)N1",
  cytosine: "O=C1NC=CC(N)=N1",
  thymine: "O=C1NC(=O)C(C)=CN1",
  uracil: "O=C1NC=CC(=O)N1",

  // Amino acids (natural L forms)
  glycine: "NCC(=O)O",
  alanine: "N[C@@H](C)C(=O)O",
  valine: "N[C@@H](C(C)C)C(=O)O",
  leucine: "N[C@@H](CC(C)C)C(=O)O",
  isoleucine: "N[C@@H]([C@@H](C)CC)C(=O)O",
  proline: "OC(=O)[C@@H]1CCCN1",
  phenylalanine: "N[C@@H](Cc1ccccc1)C(=O)O",
  tryptophan: "N[C@@H](Cc1c[nH]c2ccccc12)C(=O)O",
  methionine: "N[C@@H](CCSC)C(=O)O",
  serine: "N[C@@H](CO)C(=O)O",
  threonine: "N[C@@H]([C@@H](C)O)C(=O)O",
  cysteine: "N[C@@H](CS)C(=O)O",
  tyrosine: "N[C@@H](Cc1ccc(O)cc1)C(=O)O",
  asparagine: "N[C@@H](CC(N)=O)C(=O)O",
  glutamine: "N[C@@H](CCC(N)=O)C(=O)O",
  aspartic-acid: "N[C@@H](CC(=O)O)C(=O)O",
  glutamic-acid: "N[C@@H](CCC(=O)O)C(=O)O",
  lysine: "N[C@@H](CCCCN)C(=O)O",
  arginine: "N[C@@H](CCCNC(N)=N)C(=O)O",
  histidine: "N[C@@H](Cc1cnc[nH]1)C(=O)O",

  // Sugars (D forms; glucose as the pyranose, ribose as the furanose)
  alpha-d-glucose: "OC[C@H]1O[C@H](O)[C@H](O)[C@@H](O)[C@@H]1O",
  beta-d-glucose: "OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O",
  beta-d-ribose: "OC[C@H]1O[C@@H](O)[C@H](O)[C@@H]1O",
  sucrose: "OC[C@H]1O[C@H](O[C@]2(CO)O[C@H](CO)[C@@H](O)[C@@H]2O)[C@H](O)[C@@H](O)[C@@H]1O",

  // Metabolic and dicarboxylic acids
  lactic-acid: "C[C@H](O)C(=O)O",
  pyruvic-acid: "CC(=O)C(=O)O",
  citric-acid: "OC(=O)CC(O)(CC(=O)O)C(=O)O",
  succinic-acid: "OC(=O)CCC(=O)O",
  fumaric-acid: "OC(=O)/C=C/C(=O)O",
  maleic-acid: "OC(=O)/C=C\\C(=O)O",
  salicylic-acid: "OC(=O)c1ccccc1O",

  // Drugs, hormones, and natural products
  caffeine: "CN1C=NC2=C1C(=O)N(C)C(=O)N2C",
  aspirin: "CC(=O)Oc1ccccc1C(=O)O",
  paracetamol: "CC(=O)Nc1ccc(O)cc1",
  ibuprofen: "CC(C)Cc1ccc(cc1)C(C)C(=O)O",
  naproxen: "COc1ccc2cc(ccc2c1)[C@H](C)C(=O)O",
  nicotine: "CN1CCC[C@H]1c1cccnc1",
  dopamine: "NCCc1ccc(O)c(O)c1",
  adrenaline: "CNC[C@H](O)c1ccc(O)c(O)c1",
  serotonin: "NCCc1c[nH]c2ccc(O)cc12",
  histamine: "NCCc1cnc[nH]1",
  melatonin: "CC(=O)NCCc1c[nH]c2ccc(OC)cc12",
  acetylcholine: "CC(=O)OCC[N+](C)(C)C",
  gamma-aminobutyric-acid: "NCCCC(=O)O",
  capsaicin: "COc1cc(CNC(=O)CCCC/C=C/C(C)C)ccc1O",
  vanillin: "COc1cc(C=O)ccc1O",
  menthol: "CC(C)[C@@H]1CC[C@@H](C)C[C@H]1O",
  limonene: "CC1=CC[C@@H](CC1)C(C)=C",
  lidocaine: "CCN(CC)CC(=O)Nc1c(C)cccc1C",
  cholesterol: "CC(C)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C",
  testosterone: "C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@]34C)[C@@H]1CC[C@@H]2O",
  estradiol: "C[C@]12CC[C@H]3[C@@H](CCc4cc(O)ccc34)[C@@H]1CC[C@@H]2O",

  // Laboratory reagents
  sulfuric-acid: "OS(=O)(=O)O",
  thionyl-chloride: "ClS(Cl)=O",
  acetic-anhydride: "CC(=O)OC(C)=O",
  acetyl-chloride: "CC(Cl)=O",
  triethylamine: "CCN(CC)CC",
  triphenylphosphine: "c1ccc(cc1)P(c1ccccc1)c1ccccc1",
  tosyl-chloride: "Cc1ccc(cc1)S(Cl)(=O)=O",
  butyllithium: "CCCC[Li]",
  sodium-borohydride: "[Na+].[BH4-]",
  lithium-aluminium-hydride: "[Li+].[AlH4-]",
  sodium-chloride: "[Na+].[Cl-]",
  sodium-hydroxide: "[Na+].[OH-]",
)
