[package]
name = "tieffiction"
version = "0.2.1"
compiler = "0.13.1"
authors = ["Lena Tauchner"]
entrypoint = "lib.typ"
license = "MIT"
description = "A simple book template for fiction."
keywords = []
categories = ["layout", "fun", "book"]
disciplines = []
repository = "https://github.com/Tiefseetauchner/TiefFiction"
homepage = "https://www.lukechriswalker.at/projects/6a26a275b6efd610e8e3928b"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
