#let data = (:
  "2": ("HIRAGANA LETTER SMALL KO", "Lo", 0),
  "20": ("HIRAGANA LETTER SMALL WI", "Lo", 0),
  "21": ("HIRAGANA LETTER SMALL WE", "Lo", 0),
  "22": ("HIRAGANA LETTER SMALL WO", "Lo", 0),
  "25": ("KATAKANA LETTER SMALL KO", "Lo", 0),
  "34": ("KATAKANA LETTER SMALL WI", "Lo", 0),
  "35": ("KATAKANA LETTER SMALL WE", "Lo", 0),
  "36": ("KATAKANA LETTER SMALL WO", "Lo", 0),
  "37": ("KATAKANA LETTER SMALL N", "Lo", 0),
)
