#let data = (
  ("NKO DIGIT ZERO", "Nd", 0),
  ("NKO DIGIT ONE", "Nd", 0),
  ("NKO DIGIT TWO", "Nd", 0),
  ("NKO DIGIT THREE", "Nd", 0),
  ("NKO DIGIT FOUR", "Nd", 0),
  ("NKO DIGIT FIVE", "Nd", 0),
  ("NKO DIGIT SIX", "Nd", 0),
  ("NKO DIGIT SEVEN", "Nd", 0),
  ("NKO DIGIT EIGHT", "Nd", 0),
  ("NKO DIGIT NINE", "Nd", 0),
  ("NKO LETTER A", "Lo", 0),
  ("NKO LETTER EE", "Lo", 0),
  ("NKO LETTER I", "Lo", 0),
  ("NKO LETTER E", "Lo", 0),
  ("NKO LETTER U", "Lo", 0),
  ("NKO LETTER OO", "Lo", 0),
  ("NKO LETTER O", "Lo", 0),
  ("NKO LETTER DAGBASINNA", "Lo", 0),
  ("NKO LETTER N", "Lo", 0),
  ("NKO LETTER BA", "Lo", 0),
  ("NKO LETTER PA", "Lo", 0),
  ("NKO LETTER TA", "Lo", 0),
  ("NKO LETTER JA", "Lo", 0),
  ("NKO LETTER CHA", "Lo", 0),
  ("NKO LETTER DA", "Lo", 0),
  ("NKO LETTER RA", "Lo", 0),
  ("NKO LETTER RRA", "Lo", 0),
  ("NKO LETTER SA", "Lo", 0),
  ("NKO LETTER GBA", "Lo", 0),
  ("NKO LETTER FA", "Lo", 0),
  ("NKO LETTER KA", "Lo", 0),
  ("NKO LETTER LA", "Lo", 0),
  ("NKO LETTER NA WOLOSO", "Lo", 0),
  ("NKO LETTER MA", "Lo", 0),
  ("NKO LETTER NYA", "Lo", 0),
  ("NKO LETTER NA", "Lo", 0),
  ("NKO LETTER HA", "Lo", 0),
  ("NKO LETTER WA", "Lo", 0),
  ("NKO LETTER YA", "Lo", 0),
  ("NKO LETTER NYA WOLOSO", "Lo", 0),
  ("NKO LETTER JONA JA", "Lo", 0),
  ("NKO LETTER JONA CHA", "Lo", 0),
  ("NKO LETTER JONA RA", "Lo", 0),
  ("NKO COMBINING SHORT HIGH TONE", "Mn", 230),
  ("NKO COMBINING SHORT LOW TONE", "Mn", 230),
  ("NKO COMBINING SHORT RISING TONE", "Mn", 230),
  ("NKO COMBINING LONG DESCENDING TONE", "Mn", 230),
  ("NKO COMBINING LONG HIGH TONE", "Mn", 230),
  ("NKO COMBINING LONG LOW TONE", "Mn", 230),
  ("NKO COMBINING LONG RISING TONE", "Mn", 230),
  ("NKO COMBINING NASALIZATION MARK", "Mn", 220),
  ("NKO COMBINING DOUBLE DOT ABOVE", "Mn", 230),
  ("NKO HIGH TONE APOSTROPHE", "Lm", 0),
  ("NKO LOW TONE APOSTROPHE", "Lm", 0),
  ("NKO SYMBOL OO DENNEN", "So", 0),
  ("NKO SYMBOL GBAKURUNEN", "Po", 0),
  ("NKO COMMA", "Po", 0),
  ("NKO EXCLAMATION MARK", "Po", 0),
  ("NKO LAJANYALAN", "Lm", 0),
  (),
  (),
  ("NKO DANTAYALAN", "Mn", 220),
  ("NKO DOROME SIGN", "Sc", 0),
  ("NKO TAMAN SIGN", "Sc", 0),
)
