#let data = (
  ("CJK STROKE T", "So", 0),
  ("CJK STROKE WG", "So", 0),
  ("CJK STROKE XG", "So", 0),
  ("CJK STROKE BXG", "So", 0),
  ("CJK STROKE SW", "So", 0),
  ("CJK STROKE HZZ", "So", 0),
  ("CJK STROKE HZG", "So", 0),
  ("CJK STROKE HP", "So", 0),
  ("CJK STROKE HZWG", "So", 0),
  ("CJK STROKE SZWG", "So", 0),
  ("CJK STROKE HZT", "So", 0),
  ("CJK STROKE HZZP", "So", 0),
  ("CJK STROKE HPWG", "So", 0),
  ("CJK STROKE HZW", "So", 0),
  ("CJK STROKE HZZZ", "So", 0),
  ("CJK STROKE N", "So", 0),
  ("CJK STROKE H", "So", 0),
  ("CJK STROKE S", "So", 0),
  ("CJK STROKE P", "So", 0),
  ("CJK STROKE SP", "So", 0),
  ("CJK STROKE D", "So", 0),
  ("CJK STROKE HZ", "So", 0),
  ("CJK STROKE HG", "So", 0),
  ("CJK STROKE SZ", "So", 0),
  ("CJK STROKE SWZ", "So", 0),
  ("CJK STROKE ST", "So", 0),
  ("CJK STROKE SG", "So", 0),
  ("CJK STROKE PD", "So", 0),
  ("CJK STROKE PZ", "So", 0),
  ("CJK STROKE TN", "So", 0),
  ("CJK STROKE SZZ", "So", 0),
  ("CJK STROKE SWG", "So", 0),
  ("CJK STROKE HXWG", "So", 0),
  ("CJK STROKE HZZZG", "So", 0),
  ("CJK STROKE PG", "So", 0),
  ("CJK STROKE Q", "So", 0),
  ("CJK STROKE HXG", "So", 0),
  ("CJK STROKE SZP", "So", 0),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("IDEOGRAPHIC DESCRIPTION CHARACTER SUBTRACTION", "So", 0),
)
