#let data = (
  ("MIAO LETTER PA", "Lo", 0),
  ("MIAO LETTER BA", "Lo", 0),
  ("MIAO LETTER YI PA", "Lo", 0),
  ("MIAO LETTER PLA", "Lo", 0),
  ("MIAO LETTER MA", "Lo", 0),
  ("MIAO LETTER MHA", "Lo", 0),
  ("MIAO LETTER ARCHAIC MA", "Lo", 0),
  ("MIAO LETTER FA", "Lo", 0),
  ("MIAO LETTER VA", "Lo", 0),
  ("MIAO LETTER VFA", "Lo", 0),
  ("MIAO LETTER TA", "Lo", 0),
  ("MIAO LETTER DA", "Lo", 0),
  ("MIAO LETTER YI TTA", "Lo", 0),
  ("MIAO LETTER YI TA", "Lo", 0),
  ("MIAO LETTER TTA", "Lo", 0),
  ("MIAO LETTER DDA", "Lo", 0),
  ("MIAO LETTER NA", "Lo", 0),
  ("MIAO LETTER NHA", "Lo", 0),
  ("MIAO LETTER YI NNA", "Lo", 0),
  ("MIAO LETTER ARCHAIC NA", "Lo", 0),
  ("MIAO LETTER NNA", "Lo", 0),
  ("MIAO LETTER NNHA", "Lo", 0),
  ("MIAO LETTER LA", "Lo", 0),
  ("MIAO LETTER LYA", "Lo", 0),
  ("MIAO LETTER LHA", "Lo", 0),
  ("MIAO LETTER LHYA", "Lo", 0),
  ("MIAO LETTER TLHA", "Lo", 0),
  ("MIAO LETTER DLHA", "Lo", 0),
  ("MIAO LETTER TLHYA", "Lo", 0),
  ("MIAO LETTER DLHYA", "Lo", 0),
  ("MIAO LETTER KA", "Lo", 0),
  ("MIAO LETTER GA", "Lo", 0),
  ("MIAO LETTER YI KA", "Lo", 0),
  ("MIAO LETTER QA", "Lo", 0),
  ("MIAO LETTER QGA", "Lo", 0),
  ("MIAO LETTER NGA", "Lo", 0),
  ("MIAO LETTER NGHA", "Lo", 0),
  ("MIAO LETTER ARCHAIC NGA", "Lo", 0),
  ("MIAO LETTER HA", "Lo", 0),
  ("MIAO LETTER XA", "Lo", 0),
  ("MIAO LETTER GHA", "Lo", 0),
  ("MIAO LETTER GHHA", "Lo", 0),
  ("MIAO LETTER TSSA", "Lo", 0),
  ("MIAO LETTER DZZA", "Lo", 0),
  ("MIAO LETTER NYA", "Lo", 0),
  ("MIAO LETTER NYHA", "Lo", 0),
  ("MIAO LETTER TSHA", "Lo", 0),
  ("MIAO LETTER DZHA", "Lo", 0),
  ("MIAO LETTER YI TSHA", "Lo", 0),
  ("MIAO LETTER YI DZHA", "Lo", 0),
  ("MIAO LETTER REFORMED TSHA", "Lo", 0),
  ("MIAO LETTER SHA", "Lo", 0),
  ("MIAO LETTER SSA", "Lo", 0),
  ("MIAO LETTER ZHA", "Lo", 0),
  ("MIAO LETTER ZSHA", "Lo", 0),
  ("MIAO LETTER TSA", "Lo", 0),
  ("MIAO LETTER DZA", "Lo", 0),
  ("MIAO LETTER YI TSA", "Lo", 0),
  ("MIAO LETTER SA", "Lo", 0),
  ("MIAO LETTER ZA", "Lo", 0),
  ("MIAO LETTER ZSA", "Lo", 0),
  ("MIAO LETTER ZZA", "Lo", 0),
  ("MIAO LETTER ZZSA", "Lo", 0),
  ("MIAO LETTER ARCHAIC ZZA", "Lo", 0),
  ("MIAO LETTER ZZYA", "Lo", 0),
  ("MIAO LETTER ZZSYA", "Lo", 0),
  ("MIAO LETTER WA", "Lo", 0),
  ("MIAO LETTER AH", "Lo", 0),
  ("MIAO LETTER HHA", "Lo", 0),
  ("MIAO LETTER BRI", "Lo", 0),
  ("MIAO LETTER SYI", "Lo", 0),
  ("MIAO LETTER DZYI", "Lo", 0),
  ("MIAO LETTER TE", "Lo", 0),
  ("MIAO LETTER TSE", "Lo", 0),
  ("MIAO LETTER RTE", "Lo", 0),
  (),
  (),
  (),
  (),
  ("MIAO SIGN CONSONANT MODIFIER BAR", "Mn", 0),
  ("MIAO LETTER NASALIZATION", "Lo", 0),
  ("MIAO SIGN ASPIRATION", "Mc", 0),
  ("MIAO SIGN REFORMED VOICING", "Mc", 0),
  ("MIAO SIGN REFORMED ASPIRATION", "Mc", 0),
  ("MIAO VOWEL SIGN A", "Mc", 0),
  ("MIAO VOWEL SIGN AA", "Mc", 0),
  ("MIAO VOWEL SIGN AHH", "Mc", 0),
  ("MIAO VOWEL SIGN AN", "Mc", 0),
  ("MIAO VOWEL SIGN ANG", "Mc", 0),
  ("MIAO VOWEL SIGN O", "Mc", 0),
  ("MIAO VOWEL SIGN OO", "Mc", 0),
  ("MIAO VOWEL SIGN WO", "Mc", 0),
  ("MIAO VOWEL SIGN W", "Mc", 0),
  ("MIAO VOWEL SIGN E", "Mc", 0),
  ("MIAO VOWEL SIGN EN", "Mc", 0),
  ("MIAO VOWEL SIGN ENG", "Mc", 0),
  ("MIAO VOWEL SIGN OEY", "Mc", 0),
  ("MIAO VOWEL SIGN I", "Mc", 0),
  ("MIAO VOWEL SIGN IA", "Mc", 0),
  ("MIAO VOWEL SIGN IAN", "Mc", 0),
  ("MIAO VOWEL SIGN IANG", "Mc", 0),
  ("MIAO VOWEL SIGN IO", "Mc", 0),
  ("MIAO VOWEL SIGN IE", "Mc", 0),
  ("MIAO VOWEL SIGN II", "Mc", 0),
  ("MIAO VOWEL SIGN IU", "Mc", 0),
  ("MIAO VOWEL SIGN ING", "Mc", 0),
  ("MIAO VOWEL SIGN U", "Mc", 0),
  ("MIAO VOWEL SIGN UA", "Mc", 0),
  ("MIAO VOWEL SIGN UAN", "Mc", 0),
  ("MIAO VOWEL SIGN UANG", "Mc", 0),
  ("MIAO VOWEL SIGN UU", "Mc", 0),
  ("MIAO VOWEL SIGN UEI", "Mc", 0),
  ("MIAO VOWEL SIGN UNG", "Mc", 0),
  ("MIAO VOWEL SIGN Y", "Mc", 0),
  ("MIAO VOWEL SIGN YI", "Mc", 0),
  ("MIAO VOWEL SIGN AE", "Mc", 0),
  ("MIAO VOWEL SIGN AEE", "Mc", 0),
  ("MIAO VOWEL SIGN ERR", "Mc", 0),
  ("MIAO VOWEL SIGN ROUNDED ERR", "Mc", 0),
  ("MIAO VOWEL SIGN ER", "Mc", 0),
  ("MIAO VOWEL SIGN ROUNDED ER", "Mc", 0),
  ("MIAO VOWEL SIGN AI", "Mc", 0),
  ("MIAO VOWEL SIGN EI", "Mc", 0),
  ("MIAO VOWEL SIGN AU", "Mc", 0),
  ("MIAO VOWEL SIGN OU", "Mc", 0),
  ("MIAO VOWEL SIGN N", "Mc", 0),
  ("MIAO VOWEL SIGN NG", "Mc", 0),
  ("MIAO VOWEL SIGN UOG", "Mc", 0),
  ("MIAO VOWEL SIGN YUI", "Mc", 0),
  ("MIAO VOWEL SIGN OG", "Mc", 0),
  ("MIAO VOWEL SIGN OER", "Mc", 0),
  ("MIAO VOWEL SIGN VW", "Mc", 0),
  ("MIAO VOWEL SIGN IG", "Mc", 0),
  ("MIAO VOWEL SIGN EA", "Mc", 0),
  ("MIAO VOWEL SIGN IONG", "Mc", 0),
  ("MIAO VOWEL SIGN UI", "Mc", 0),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("MIAO TONE RIGHT", "Mn", 0),
  ("MIAO TONE TOP RIGHT", "Mn", 0),
  ("MIAO TONE ABOVE", "Mn", 0),
  ("MIAO TONE BELOW", "Mn", 0),
  ("MIAO LETTER TONE-2", "Lm", 0),
  ("MIAO LETTER TONE-3", "Lm", 0),
  ("MIAO LETTER TONE-4", "Lm", 0),
  ("MIAO LETTER TONE-5", "Lm", 0),
  ("MIAO LETTER TONE-6", "Lm", 0),
  ("MIAO LETTER TONE-7", "Lm", 0),
  ("MIAO LETTER TONE-8", "Lm", 0),
  ("MIAO LETTER REFORMED TONE-1", "Lm", 0),
  ("MIAO LETTER REFORMED TONE-2", "Lm", 0),
  ("MIAO LETTER REFORMED TONE-4", "Lm", 0),
  ("MIAO LETTER REFORMED TONE-5", "Lm", 0),
  ("MIAO LETTER REFORMED TONE-6", "Lm", 0),
  ("MIAO LETTER REFORMED TONE-8", "Lm", 0),
)
