#let data = (
  ("CHAM LETTER A", "Lo", 0),
  ("CHAM LETTER I", "Lo", 0),
  ("CHAM LETTER U", "Lo", 0),
  ("CHAM LETTER E", "Lo", 0),
  ("CHAM LETTER AI", "Lo", 0),
  ("CHAM LETTER O", "Lo", 0),
  ("CHAM LETTER KA", "Lo", 0),
  ("CHAM LETTER KHA", "Lo", 0),
  ("CHAM LETTER GA", "Lo", 0),
  ("CHAM LETTER GHA", "Lo", 0),
  ("CHAM LETTER NGUE", "Lo", 0),
  ("CHAM LETTER NGA", "Lo", 0),
  ("CHAM LETTER CHA", "Lo", 0),
  ("CHAM LETTER CHHA", "Lo", 0),
  ("CHAM LETTER JA", "Lo", 0),
  ("CHAM LETTER JHA", "Lo", 0),
  ("CHAM LETTER NHUE", "Lo", 0),
  ("CHAM LETTER NHA", "Lo", 0),
  ("CHAM LETTER NHJA", "Lo", 0),
  ("CHAM LETTER TA", "Lo", 0),
  ("CHAM LETTER THA", "Lo", 0),
  ("CHAM LETTER DA", "Lo", 0),
  ("CHAM LETTER DHA", "Lo", 0),
  ("CHAM LETTER NUE", "Lo", 0),
  ("CHAM LETTER NA", "Lo", 0),
  ("CHAM LETTER DDA", "Lo", 0),
  ("CHAM LETTER PA", "Lo", 0),
  ("CHAM LETTER PPA", "Lo", 0),
  ("CHAM LETTER PHA", "Lo", 0),
  ("CHAM LETTER BA", "Lo", 0),
  ("CHAM LETTER BHA", "Lo", 0),
  ("CHAM LETTER MUE", "Lo", 0),
  ("CHAM LETTER MA", "Lo", 0),
  ("CHAM LETTER BBA", "Lo", 0),
  ("CHAM LETTER YA", "Lo", 0),
  ("CHAM LETTER RA", "Lo", 0),
  ("CHAM LETTER LA", "Lo", 0),
  ("CHAM LETTER VA", "Lo", 0),
  ("CHAM LETTER SSA", "Lo", 0),
  ("CHAM LETTER SA", "Lo", 0),
  ("CHAM LETTER HA", "Lo", 0),
  ("CHAM VOWEL SIGN AA", "Mn", 0),
  ("CHAM VOWEL SIGN I", "Mn", 0),
  ("CHAM VOWEL SIGN II", "Mn", 0),
  ("CHAM VOWEL SIGN EI", "Mn", 0),
  ("CHAM VOWEL SIGN U", "Mn", 0),
  ("CHAM VOWEL SIGN OE", "Mn", 0),
  ("CHAM VOWEL SIGN O", "Mc", 0),
  ("CHAM VOWEL SIGN AI", "Mc", 0),
  ("CHAM VOWEL SIGN AU", "Mn", 0),
  ("CHAM VOWEL SIGN UE", "Mn", 0),
  ("CHAM CONSONANT SIGN YA", "Mc", 0),
  ("CHAM CONSONANT SIGN RA", "Mc", 0),
  ("CHAM CONSONANT SIGN LA", "Mn", 0),
  ("CHAM CONSONANT SIGN WA", "Mn", 0),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("CHAM LETTER FINAL K", "Lo", 0),
  ("CHAM LETTER FINAL G", "Lo", 0),
  ("CHAM LETTER FINAL NG", "Lo", 0),
  ("CHAM CONSONANT SIGN FINAL NG", "Mn", 0),
  ("CHAM LETTER FINAL CH", "Lo", 0),
  ("CHAM LETTER FINAL T", "Lo", 0),
  ("CHAM LETTER FINAL N", "Lo", 0),
  ("CHAM LETTER FINAL P", "Lo", 0),
  ("CHAM LETTER FINAL Y", "Lo", 0),
  ("CHAM LETTER FINAL R", "Lo", 0),
  ("CHAM LETTER FINAL L", "Lo", 0),
  ("CHAM LETTER FINAL SS", "Lo", 0),
  ("CHAM CONSONANT SIGN FINAL M", "Mn", 0),
  ("CHAM CONSONANT SIGN FINAL H", "Mc", 0),
  (),
  (),
  ("CHAM DIGIT ZERO", "Nd", 0),
  ("CHAM DIGIT ONE", "Nd", 0),
  ("CHAM DIGIT TWO", "Nd", 0),
  ("CHAM DIGIT THREE", "Nd", 0),
  ("CHAM DIGIT FOUR", "Nd", 0),
  ("CHAM DIGIT FIVE", "Nd", 0),
  ("CHAM DIGIT SIX", "Nd", 0),
  ("CHAM DIGIT SEVEN", "Nd", 0),
  ("CHAM DIGIT EIGHT", "Nd", 0),
  ("CHAM DIGIT NINE", "Nd", 0),
  (),
  (),
  ("CHAM PUNCTUATION SPIRAL", "Po", 0),
  ("CHAM PUNCTUATION DANDA", "Po", 0),
  ("CHAM PUNCTUATION DOUBLE DANDA", "Po", 0),
  ("CHAM PUNCTUATION TRIPLE DANDA", "Po", 0),
)
