#let data = (
  ("CYRILLIC SMALL LETTER ROUNDED VE", "Ll", 0),
  ("CYRILLIC SMALL LETTER LONG-LEGGED DE", "Ll", 0),
  ("CYRILLIC SMALL LETTER NARROW O", "Ll", 0),
  ("CYRILLIC SMALL LETTER WIDE ES", "Ll", 0),
  ("CYRILLIC SMALL LETTER TALL TE", "Ll", 0),
  ("CYRILLIC SMALL LETTER THREE-LEGGED TE", "Ll", 0),
  ("CYRILLIC SMALL LETTER TALL HARD SIGN", "Ll", 0),
  ("CYRILLIC SMALL LETTER TALL YAT", "Ll", 0),
  ("CYRILLIC SMALL LETTER UNBLENDED UK", "Ll", 0),
  ("CYRILLIC CAPITAL LETTER TJE", "Lu", 0),
  ("CYRILLIC SMALL LETTER TJE", "Ll", 0),
)
