#let data = (
  ("KAWI SIGN CANDRABINDU", "Mn", 0),
  ("KAWI SIGN ANUSVARA", "Mn", 0),
  ("KAWI SIGN REPHA", "Lo", 0),
  ("KAWI SIGN VISARGA", "Mc", 0),
  ("KAWI LETTER A", "Lo", 0),
  ("KAWI LETTER AA", "Lo", 0),
  ("KAWI LETTER I", "Lo", 0),
  ("KAWI LETTER II", "Lo", 0),
  ("KAWI LETTER U", "Lo", 0),
  ("KAWI LETTER UU", "Lo", 0),
  ("KAWI LETTER VOCALIC R", "Lo", 0),
  ("KAWI LETTER VOCALIC RR", "Lo", 0),
  ("KAWI LETTER VOCALIC L", "Lo", 0),
  ("KAWI LETTER VOCALIC LL", "Lo", 0),
  ("KAWI LETTER E", "Lo", 0),
  ("KAWI LETTER AI", "Lo", 0),
  ("KAWI LETTER O", "Lo", 0),
  (),
  ("KAWI LETTER KA", "Lo", 0),
  ("KAWI LETTER KHA", "Lo", 0),
  ("KAWI LETTER GA", "Lo", 0),
  ("KAWI LETTER GHA", "Lo", 0),
  ("KAWI LETTER NGA", "Lo", 0),
  ("KAWI LETTER CA", "Lo", 0),
  ("KAWI LETTER CHA", "Lo", 0),
  ("KAWI LETTER JA", "Lo", 0),
  ("KAWI LETTER JHA", "Lo", 0),
  ("KAWI LETTER NYA", "Lo", 0),
  ("KAWI LETTER TTA", "Lo", 0),
  ("KAWI LETTER TTHA", "Lo", 0),
  ("KAWI LETTER DDA", "Lo", 0),
  ("KAWI LETTER DDHA", "Lo", 0),
  ("KAWI LETTER NNA", "Lo", 0),
  ("KAWI LETTER TA", "Lo", 0),
  ("KAWI LETTER THA", "Lo", 0),
  ("KAWI LETTER DA", "Lo", 0),
  ("KAWI LETTER DHA", "Lo", 0),
  ("KAWI LETTER NA", "Lo", 0),
  ("KAWI LETTER PA", "Lo", 0),
  ("KAWI LETTER PHA", "Lo", 0),
  ("KAWI LETTER BA", "Lo", 0),
  ("KAWI LETTER BHA", "Lo", 0),
  ("KAWI LETTER MA", "Lo", 0),
  ("KAWI LETTER YA", "Lo", 0),
  ("KAWI LETTER RA", "Lo", 0),
  ("KAWI LETTER LA", "Lo", 0),
  ("KAWI LETTER WA", "Lo", 0),
  ("KAWI LETTER SHA", "Lo", 0),
  ("KAWI LETTER SSA", "Lo", 0),
  ("KAWI LETTER SA", "Lo", 0),
  ("KAWI LETTER HA", "Lo", 0),
  ("KAWI LETTER JNYA", "Lo", 0),
  ("KAWI VOWEL SIGN AA", "Mc", 0),
  ("KAWI VOWEL SIGN ALTERNATE AA", "Mc", 0),
  ("KAWI VOWEL SIGN I", "Mn", 0),
  ("KAWI VOWEL SIGN II", "Mn", 0),
  ("KAWI VOWEL SIGN U", "Mn", 0),
  ("KAWI VOWEL SIGN UU", "Mn", 0),
  ("KAWI VOWEL SIGN VOCALIC R", "Mn", 0),
  (),
  (),
  (),
  ("KAWI VOWEL SIGN E", "Mc", 0),
  ("KAWI VOWEL SIGN AI", "Mc", 0),
  ("KAWI VOWEL SIGN EU", "Mn", 0),
  ("KAWI SIGN KILLER", "Mc", 9),
  ("KAWI CONJOINER", "Mn", 9),
  ("KAWI DANDA", "Po", 0),
  ("KAWI DOUBLE DANDA", "Po", 0),
  ("KAWI PUNCTUATION SECTION MARKER", "Po", 0),
  ("KAWI PUNCTUATION ALTERNATE SECTION MARKER", "Po", 0),
  ("KAWI PUNCTUATION FLOWER", "Po", 0),
  ("KAWI PUNCTUATION SPACE FILLER", "Po", 0),
  ("KAWI PUNCTUATION DOT", "Po", 0),
  ("KAWI PUNCTUATION DOUBLE DOT", "Po", 0),
  ("KAWI PUNCTUATION TRIPLE DOT", "Po", 0),
  ("KAWI PUNCTUATION CIRCLE", "Po", 0),
  ("KAWI PUNCTUATION FILLED CIRCLE", "Po", 0),
  ("KAWI PUNCTUATION SPIRAL", "Po", 0),
  ("KAWI PUNCTUATION CLOSING SPIRAL", "Po", 0),
  ("KAWI DIGIT ZERO", "Nd", 0),
  ("KAWI DIGIT ONE", "Nd", 0),
  ("KAWI DIGIT TWO", "Nd", 0),
  ("KAWI DIGIT THREE", "Nd", 0),
  ("KAWI DIGIT FOUR", "Nd", 0),
  ("KAWI DIGIT FIVE", "Nd", 0),
  ("KAWI DIGIT SIX", "Nd", 0),
  ("KAWI DIGIT SEVEN", "Nd", 0),
  ("KAWI DIGIT EIGHT", "Nd", 0),
  ("KAWI DIGIT NINE", "Nd", 0),
  ("KAWI SIGN NUKTA", "Mn", 0),
)
