#let data = (
  ("MRO LETTER TA", "Lo", 0),
  ("MRO LETTER NGI", "Lo", 0),
  ("MRO LETTER YO", "Lo", 0),
  ("MRO LETTER MIM", "Lo", 0),
  ("MRO LETTER BA", "Lo", 0),
  ("MRO LETTER DA", "Lo", 0),
  ("MRO LETTER A", "Lo", 0),
  ("MRO LETTER PHI", "Lo", 0),
  ("MRO LETTER KHAI", "Lo", 0),
  ("MRO LETTER HAO", "Lo", 0),
  ("MRO LETTER DAI", "Lo", 0),
  ("MRO LETTER CHU", "Lo", 0),
  ("MRO LETTER KEAAE", "Lo", 0),
  ("MRO LETTER OL", "Lo", 0),
  ("MRO LETTER MAEM", "Lo", 0),
  ("MRO LETTER NIN", "Lo", 0),
  ("MRO LETTER PA", "Lo", 0),
  ("MRO LETTER OO", "Lo", 0),
  ("MRO LETTER O", "Lo", 0),
  ("MRO LETTER RO", "Lo", 0),
  ("MRO LETTER SHI", "Lo", 0),
  ("MRO LETTER THEA", "Lo", 0),
  ("MRO LETTER EA", "Lo", 0),
  ("MRO LETTER WA", "Lo", 0),
  ("MRO LETTER E", "Lo", 0),
  ("MRO LETTER KO", "Lo", 0),
  ("MRO LETTER LAN", "Lo", 0),
  ("MRO LETTER LA", "Lo", 0),
  ("MRO LETTER HAI", "Lo", 0),
  ("MRO LETTER RI", "Lo", 0),
  ("MRO LETTER TEK", "Lo", 0),
  (),
  ("MRO DIGIT ZERO", "Nd", 0),
  ("MRO DIGIT ONE", "Nd", 0),
  ("MRO DIGIT TWO", "Nd", 0),
  ("MRO DIGIT THREE", "Nd", 0),
  ("MRO DIGIT FOUR", "Nd", 0),
  ("MRO DIGIT FIVE", "Nd", 0),
  ("MRO DIGIT SIX", "Nd", 0),
  ("MRO DIGIT SEVEN", "Nd", 0),
  ("MRO DIGIT EIGHT", "Nd", 0),
  ("MRO DIGIT NINE", "Nd", 0),
  (),
  (),
  (),
  (),
  ("MRO DANDA", "Po", 0),
  ("MRO DOUBLE DANDA", "Po", 0),
)
