#let data = (
  ("SHORTHAND FORMAT LETTER OVERLAP", "Cf", 0),
  ("SHORTHAND FORMAT CONTINUING OVERLAP", "Cf", 0),
  ("SHORTHAND FORMAT DOWN STEP", "Cf", 0),
  ("SHORTHAND FORMAT UP STEP", "Cf", 0),
)
