#let data = (:
  "0": ("TANGUT ITERATION MARK", "Lm", 0),
  "1": ("NUSHU ITERATION MARK", "Lm", 0),
  "2": ("OLD CHINESE HOOK MARK", "Po", 0),
  "3": ("OLD CHINESE ITERATION MARK", "Lm", 0),
  "4": ("KHITAN SMALL SCRIPT FILLER", "Mn", 0),
  "10": ("VIETNAMESE ALTERNATE READING MARK CA", "Mc", 6),
  "11": ("VIETNAMESE ALTERNATE READING MARK NHAY", "Mc", 6),
)
