#let data = (
  (),
  ("LAO LETTER KO", "Lo", 0),
  ("LAO LETTER KHO SUNG", "Lo", 0),
  (),
  ("LAO LETTER KHO TAM", "Lo", 0),
  (),
  ("LAO LETTER PALI GHA", "Lo", 0),
  ("LAO LETTER NGO", "Lo", 0),
  ("LAO LETTER CO", "Lo", 0),
  ("LAO LETTER PALI CHA", "Lo", 0),
  ("LAO LETTER SO TAM", "Lo", 0),
  (),
  ("LAO LETTER PALI JHA", "Lo", 0),
  ("LAO LETTER NYO", "Lo", 0),
  ("LAO LETTER PALI NYA", "Lo", 0),
  ("LAO LETTER PALI TTA", "Lo", 0),
  ("LAO LETTER PALI TTHA", "Lo", 0),
  ("LAO LETTER PALI DDA", "Lo", 0),
  ("LAO LETTER PALI DDHA", "Lo", 0),
  ("LAO LETTER PALI NNA", "Lo", 0),
  ("LAO LETTER DO", "Lo", 0),
  ("LAO LETTER TO", "Lo", 0),
  ("LAO LETTER THO SUNG", "Lo", 0),
  ("LAO LETTER THO TAM", "Lo", 0),
  ("LAO LETTER PALI DHA", "Lo", 0),
  ("LAO LETTER NO", "Lo", 0),
  ("LAO LETTER BO", "Lo", 0),
  ("LAO LETTER PO", "Lo", 0),
  ("LAO LETTER PHO SUNG", "Lo", 0),
  ("LAO LETTER FO TAM", "Lo", 0),
  ("LAO LETTER PHO TAM", "Lo", 0),
  ("LAO LETTER FO SUNG", "Lo", 0),
  ("LAO LETTER PALI BHA", "Lo", 0),
  ("LAO LETTER MO", "Lo", 0),
  ("LAO LETTER YO", "Lo", 0),
  ("LAO LETTER LO LING", "Lo", 0),
  (),
  ("LAO LETTER LO LOOT", "Lo", 0),
  (),
  ("LAO LETTER WO", "Lo", 0),
  ("LAO LETTER SANSKRIT SHA", "Lo", 0),
  ("LAO LETTER SANSKRIT SSA", "Lo", 0),
  ("LAO LETTER SO SUNG", "Lo", 0),
  ("LAO LETTER HO SUNG", "Lo", 0),
  ("LAO LETTER PALI LLA", "Lo", 0),
  ("LAO LETTER O", "Lo", 0),
  ("LAO LETTER HO TAM", "Lo", 0),
  ("LAO ELLIPSIS", "Lo", 0),
  ("LAO VOWEL SIGN A", "Lo", 0),
  ("LAO VOWEL SIGN MAI KAN", "Mn", 0),
  ("LAO VOWEL SIGN AA", "Lo", 0),
  ("LAO VOWEL SIGN AM", "Lo", 0),
  ("LAO VOWEL SIGN I", "Mn", 0),
  ("LAO VOWEL SIGN II", "Mn", 0),
  ("LAO VOWEL SIGN Y", "Mn", 0),
  ("LAO VOWEL SIGN YY", "Mn", 0),
  ("LAO VOWEL SIGN U", "Mn", 118),
  ("LAO VOWEL SIGN UU", "Mn", 118),
  ("LAO SIGN PALI VIRAMA", "Mn", 9),
  ("LAO VOWEL SIGN MAI KON", "Mn", 0),
  ("LAO SEMIVOWEL SIGN LO", "Mn", 0),
  ("LAO SEMIVOWEL SIGN NYO", "Lo", 0),
  (),
  (),
  ("LAO VOWEL SIGN E", "Lo", 0),
  ("LAO VOWEL SIGN EI", "Lo", 0),
  ("LAO VOWEL SIGN O", "Lo", 0),
  ("LAO VOWEL SIGN AY", "Lo", 0),
  ("LAO VOWEL SIGN AI", "Lo", 0),
  (),
  ("LAO KO LA", "Lm", 0),
  (),
  ("LAO TONE MAI EK", "Mn", 122),
  ("LAO TONE MAI THO", "Mn", 122),
  ("LAO TONE MAI TI", "Mn", 122),
  ("LAO TONE MAI CATAWA", "Mn", 122),
  ("LAO CANCELLATION MARK", "Mn", 0),
  ("LAO NIGGAHITA", "Mn", 0),
  ("LAO YAMAKKAN", "Mn", 0),
  (),
  ("LAO DIGIT ZERO", "Nd", 0),
  ("LAO DIGIT ONE", "Nd", 0),
  ("LAO DIGIT TWO", "Nd", 0),
  ("LAO DIGIT THREE", "Nd", 0),
  ("LAO DIGIT FOUR", "Nd", 0),
  ("LAO DIGIT FIVE", "Nd", 0),
  ("LAO DIGIT SIX", "Nd", 0),
  ("LAO DIGIT SEVEN", "Nd", 0),
  ("LAO DIGIT EIGHT", "Nd", 0),
  ("LAO DIGIT NINE", "Nd", 0),
  (),
  (),
  ("LAO HO NO", "Lo", 0),
  ("LAO HO MO", "Lo", 0),
  ("LAO LETTER KHMU GO", "Lo", 0),
  ("LAO LETTER KHMU NYO", "Lo", 0),
)
