#let data = (
  ("TAGBANWA LETTER A", "Lo", 0),
  ("TAGBANWA LETTER I", "Lo", 0),
  ("TAGBANWA LETTER U", "Lo", 0),
  ("TAGBANWA LETTER KA", "Lo", 0),
  ("TAGBANWA LETTER GA", "Lo", 0),
  ("TAGBANWA LETTER NGA", "Lo", 0),
  ("TAGBANWA LETTER TA", "Lo", 0),
  ("TAGBANWA LETTER DA", "Lo", 0),
  ("TAGBANWA LETTER NA", "Lo", 0),
  ("TAGBANWA LETTER PA", "Lo", 0),
  ("TAGBANWA LETTER BA", "Lo", 0),
  ("TAGBANWA LETTER MA", "Lo", 0),
  ("TAGBANWA LETTER YA", "Lo", 0),
  (),
  ("TAGBANWA LETTER LA", "Lo", 0),
  ("TAGBANWA LETTER WA", "Lo", 0),
  ("TAGBANWA LETTER SA", "Lo", 0),
  (),
  ("TAGBANWA VOWEL SIGN I", "Mn", 0),
  ("TAGBANWA VOWEL SIGN U", "Mn", 0),
)
