#let data = (
  (),
  (),
  ("TAMIL SIGN ANUSVARA", "Mn", 0),
  ("TAMIL SIGN VISARGA", "Lo", 0),
  (),
  ("TAMIL LETTER A", "Lo", 0),
  ("TAMIL LETTER AA", "Lo", 0),
  ("TAMIL LETTER I", "Lo", 0),
  ("TAMIL LETTER II", "Lo", 0),
  ("TAMIL LETTER U", "Lo", 0),
  ("TAMIL LETTER UU", "Lo", 0),
  (),
  (),
  (),
  ("TAMIL LETTER E", "Lo", 0),
  ("TAMIL LETTER EE", "Lo", 0),
  ("TAMIL LETTER AI", "Lo", 0),
  (),
  ("TAMIL LETTER O", "Lo", 0),
  ("TAMIL LETTER OO", "Lo", 0),
  ("TAMIL LETTER AU", "Lo", 0),
  ("TAMIL LETTER KA", "Lo", 0),
  (),
  (),
  (),
  ("TAMIL LETTER NGA", "Lo", 0),
  ("TAMIL LETTER CA", "Lo", 0),
  (),
  ("TAMIL LETTER JA", "Lo", 0),
  (),
  ("TAMIL LETTER NYA", "Lo", 0),
  ("TAMIL LETTER TTA", "Lo", 0),
  (),
  (),
  (),
  ("TAMIL LETTER NNA", "Lo", 0),
  ("TAMIL LETTER TA", "Lo", 0),
  (),
  (),
  (),
  ("TAMIL LETTER NA", "Lo", 0),
  ("TAMIL LETTER NNNA", "Lo", 0),
  ("TAMIL LETTER PA", "Lo", 0),
  (),
  (),
  (),
  ("TAMIL LETTER MA", "Lo", 0),
  ("TAMIL LETTER YA", "Lo", 0),
  ("TAMIL LETTER RA", "Lo", 0),
  ("TAMIL LETTER RRA", "Lo", 0),
  ("TAMIL LETTER LA", "Lo", 0),
  ("TAMIL LETTER LLA", "Lo", 0),
  ("TAMIL LETTER LLLA", "Lo", 0),
  ("TAMIL LETTER VA", "Lo", 0),
  ("TAMIL LETTER SHA", "Lo", 0),
  ("TAMIL LETTER SSA", "Lo", 0),
  ("TAMIL LETTER SA", "Lo", 0),
  ("TAMIL LETTER HA", "Lo", 0),
  (),
  (),
  (),
  (),
  ("TAMIL VOWEL SIGN AA", "Mc", 0),
  ("TAMIL VOWEL SIGN I", "Mc", 0),
  ("TAMIL VOWEL SIGN II", "Mn", 0),
  ("TAMIL VOWEL SIGN U", "Mc", 0),
  ("TAMIL VOWEL SIGN UU", "Mc", 0),
  (),
  (),
  (),
  ("TAMIL VOWEL SIGN E", "Mc", 0),
  ("TAMIL VOWEL SIGN EE", "Mc", 0),
  ("TAMIL VOWEL SIGN AI", "Mc", 0),
  (),
  ("TAMIL VOWEL SIGN O", "Mc", 0),
  ("TAMIL VOWEL SIGN OO", "Mc", 0),
  ("TAMIL VOWEL SIGN AU", "Mc", 0),
  ("TAMIL SIGN VIRAMA", "Mn", 9),
  (),
  (),
  ("TAMIL OM", "Lo", 0),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TAMIL AU LENGTH MARK", "Mc", 0),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TAMIL DIGIT ZERO", "Nd", 0),
  ("TAMIL DIGIT ONE", "Nd", 0),
  ("TAMIL DIGIT TWO", "Nd", 0),
  ("TAMIL DIGIT THREE", "Nd", 0),
  ("TAMIL DIGIT FOUR", "Nd", 0),
  ("TAMIL DIGIT FIVE", "Nd", 0),
  ("TAMIL DIGIT SIX", "Nd", 0),
  ("TAMIL DIGIT SEVEN", "Nd", 0),
  ("TAMIL DIGIT EIGHT", "Nd", 0),
  ("TAMIL DIGIT NINE", "Nd", 0),
  ("TAMIL NUMBER TEN", "No", 0),
  ("TAMIL NUMBER ONE HUNDRED", "No", 0),
  ("TAMIL NUMBER ONE THOUSAND", "No", 0),
  ("TAMIL DAY SIGN", "So", 0),
  ("TAMIL MONTH SIGN", "So", 0),
  ("TAMIL YEAR SIGN", "So", 0),
  ("TAMIL DEBIT SIGN", "So", 0),
  ("TAMIL CREDIT SIGN", "So", 0),
  ("TAMIL AS ABOVE SIGN", "So", 0),
  ("TAMIL RUPEE SIGN", "Sc", 0),
  ("TAMIL NUMBER SIGN", "So", 0),
)
