#let data = (
  ("OSMANYA LETTER ALEF", "Lo", 0),
  ("OSMANYA LETTER BA", "Lo", 0),
  ("OSMANYA LETTER TA", "Lo", 0),
  ("OSMANYA LETTER JA", "Lo", 0),
  ("OSMANYA LETTER XA", "Lo", 0),
  ("OSMANYA LETTER KHA", "Lo", 0),
  ("OSMANYA LETTER DEEL", "Lo", 0),
  ("OSMANYA LETTER RA", "Lo", 0),
  ("OSMANYA LETTER SA", "Lo", 0),
  ("OSMANYA LETTER SHIIN", "Lo", 0),
  ("OSMANYA LETTER DHA", "Lo", 0),
  ("OSMANYA LETTER CAYN", "Lo", 0),
  ("OSMANYA LETTER GA", "Lo", 0),
  ("OSMANYA LETTER FA", "Lo", 0),
  ("OSMANYA LETTER QAAF", "Lo", 0),
  ("OSMANYA LETTER KAAF", "Lo", 0),
  ("OSMANYA LETTER LAAN", "Lo", 0),
  ("OSMANYA LETTER MIIN", "Lo", 0),
  ("OSMANYA LETTER NUUN", "Lo", 0),
  ("OSMANYA LETTER WAW", "Lo", 0),
  ("OSMANYA LETTER HA", "Lo", 0),
  ("OSMANYA LETTER YA", "Lo", 0),
  ("OSMANYA LETTER A", "Lo", 0),
  ("OSMANYA LETTER E", "Lo", 0),
  ("OSMANYA LETTER I", "Lo", 0),
  ("OSMANYA LETTER O", "Lo", 0),
  ("OSMANYA LETTER U", "Lo", 0),
  ("OSMANYA LETTER AA", "Lo", 0),
  ("OSMANYA LETTER EE", "Lo", 0),
  ("OSMANYA LETTER OO", "Lo", 0),
  (),
  (),
  ("OSMANYA DIGIT ZERO", "Nd", 0),
  ("OSMANYA DIGIT ONE", "Nd", 0),
  ("OSMANYA DIGIT TWO", "Nd", 0),
  ("OSMANYA DIGIT THREE", "Nd", 0),
  ("OSMANYA DIGIT FOUR", "Nd", 0),
  ("OSMANYA DIGIT FIVE", "Nd", 0),
  ("OSMANYA DIGIT SIX", "Nd", 0),
  ("OSMANYA DIGIT SEVEN", "Nd", 0),
  ("OSMANYA DIGIT EIGHT", "Nd", 0),
  ("OSMANYA DIGIT NINE", "Nd", 0),
)
