#let data = (
  ("SUNUWAR LETTER DEVI", "Lo", 0),
  ("SUNUWAR LETTER TASLA", "Lo", 0),
  ("SUNUWAR LETTER EKO", "Lo", 0),
  ("SUNUWAR LETTER IMAR", "Lo", 0),
  ("SUNUWAR LETTER REU", "Lo", 0),
  ("SUNUWAR LETTER UTTHI", "Lo", 0),
  ("SUNUWAR LETTER KIK", "Lo", 0),
  ("SUNUWAR LETTER MA", "Lo", 0),
  ("SUNUWAR LETTER APPHO", "Lo", 0),
  ("SUNUWAR LETTER PIP", "Lo", 0),
  ("SUNUWAR LETTER GIL", "Lo", 0),
  ("SUNUWAR LETTER HAMSO", "Lo", 0),
  ("SUNUWAR LETTER CARMI", "Lo", 0),
  ("SUNUWAR LETTER NAH", "Lo", 0),
  ("SUNUWAR LETTER BUR", "Lo", 0),
  ("SUNUWAR LETTER JYAH", "Lo", 0),
  ("SUNUWAR LETTER LOACHA", "Lo", 0),
  ("SUNUWAR LETTER OTTHI", "Lo", 0),
  ("SUNUWAR LETTER SHYELE", "Lo", 0),
  ("SUNUWAR LETTER VARCA", "Lo", 0),
  ("SUNUWAR LETTER YAT", "Lo", 0),
  ("SUNUWAR LETTER AVA", "Lo", 0),
  ("SUNUWAR LETTER AAL", "Lo", 0),
  ("SUNUWAR LETTER DONGA", "Lo", 0),
  ("SUNUWAR LETTER THARI", "Lo", 0),
  ("SUNUWAR LETTER PHAR", "Lo", 0),
  ("SUNUWAR LETTER NGAR", "Lo", 0),
  ("SUNUWAR LETTER KHA", "Lo", 0),
  ("SUNUWAR LETTER SHYER", "Lo", 0),
  ("SUNUWAR LETTER CHELAP", "Lo", 0),
  ("SUNUWAR LETTER TENTU", "Lo", 0),
  ("SUNUWAR LETTER THELE", "Lo", 0),
  ("SUNUWAR LETTER KLOKO", "Lo", 0),
  ("SUNUWAR SIGN PVO", "Po", 0),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("SUNUWAR DIGIT ZERO", "Nd", 0),
  ("SUNUWAR DIGIT ONE", "Nd", 0),
  ("SUNUWAR DIGIT TWO", "Nd", 0),
  ("SUNUWAR DIGIT THREE", "Nd", 0),
  ("SUNUWAR DIGIT FOUR", "Nd", 0),
  ("SUNUWAR DIGIT FIVE", "Nd", 0),
  ("SUNUWAR DIGIT SIX", "Nd", 0),
  ("SUNUWAR DIGIT SEVEN", "Nd", 0),
  ("SUNUWAR DIGIT EIGHT", "Nd", 0),
  ("SUNUWAR DIGIT NINE", "Nd", 0),
)
