#let data = (
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("<control>", "Cc", 0),
  ("SPACE", "Zs", 0),
  ("EXCLAMATION MARK", "Po", 0),
  ("QUOTATION MARK", "Po", 0),
  ("NUMBER SIGN", "Po", 0),
  ("DOLLAR SIGN", "Sc", 0),
  ("PERCENT SIGN", "Po", 0),
  ("AMPERSAND", "Po", 0),
  ("APOSTROPHE", "Po", 0),
  ("LEFT PARENTHESIS", "Ps", 0),
  ("RIGHT PARENTHESIS", "Pe", 0),
  ("ASTERISK", "Po", 0),
  ("PLUS SIGN", "Sm", 0),
  ("COMMA", "Po", 0),
  ("HYPHEN-MINUS", "Pd", 0),
  ("FULL STOP", "Po", 0),
  ("SOLIDUS", "Po", 0),
  ("DIGIT ZERO", "Nd", 0),
  ("DIGIT ONE", "Nd", 0),
  ("DIGIT TWO", "Nd", 0),
  ("DIGIT THREE", "Nd", 0),
  ("DIGIT FOUR", "Nd", 0),
  ("DIGIT FIVE", "Nd", 0),
  ("DIGIT SIX", "Nd", 0),
  ("DIGIT SEVEN", "Nd", 0),
  ("DIGIT EIGHT", "Nd", 0),
  ("DIGIT NINE", "Nd", 0),
  ("COLON", "Po", 0),
  ("SEMICOLON", "Po", 0),
  ("LESS-THAN SIGN", "Sm", 0),
  ("EQUALS SIGN", "Sm", 0),
  ("GREATER-THAN SIGN", "Sm", 0),
  ("QUESTION MARK", "Po", 0),
  ("COMMERCIAL AT", "Po", 0),
  ("LATIN CAPITAL LETTER A", "Lu", 0),
  ("LATIN CAPITAL LETTER B", "Lu", 0),
  ("LATIN CAPITAL LETTER C", "Lu", 0),
  ("LATIN CAPITAL LETTER D", "Lu", 0),
  ("LATIN CAPITAL LETTER E", "Lu", 0),
  ("LATIN CAPITAL LETTER F", "Lu", 0),
  ("LATIN CAPITAL LETTER G", "Lu", 0),
  ("LATIN CAPITAL LETTER H", "Lu", 0),
  ("LATIN CAPITAL LETTER I", "Lu", 0),
  ("LATIN CAPITAL LETTER J", "Lu", 0),
  ("LATIN CAPITAL LETTER K", "Lu", 0),
  ("LATIN CAPITAL LETTER L", "Lu", 0),
  ("LATIN CAPITAL LETTER M", "Lu", 0),
  ("LATIN CAPITAL LETTER N", "Lu", 0),
  ("LATIN CAPITAL LETTER O", "Lu", 0),
  ("LATIN CAPITAL LETTER P", "Lu", 0),
  ("LATIN CAPITAL LETTER Q", "Lu", 0),
  ("LATIN CAPITAL LETTER R", "Lu", 0),
  ("LATIN CAPITAL LETTER S", "Lu", 0),
  ("LATIN CAPITAL LETTER T", "Lu", 0),
  ("LATIN CAPITAL LETTER U", "Lu", 0),
  ("LATIN CAPITAL LETTER V", "Lu", 0),
  ("LATIN CAPITAL LETTER W", "Lu", 0),
  ("LATIN CAPITAL LETTER X", "Lu", 0),
  ("LATIN CAPITAL LETTER Y", "Lu", 0),
  ("LATIN CAPITAL LETTER Z", "Lu", 0),
  ("LEFT SQUARE BRACKET", "Ps", 0),
  ("REVERSE SOLIDUS", "Po", 0),
  ("RIGHT SQUARE BRACKET", "Pe", 0),
  ("CIRCUMFLEX ACCENT", "Sk", 0),
  ("LOW LINE", "Pc", 0),
  ("GRAVE ACCENT", "Sk", 0),
  ("LATIN SMALL LETTER A", "Ll", 0),
  ("LATIN SMALL LETTER B", "Ll", 0),
  ("LATIN SMALL LETTER C", "Ll", 0),
  ("LATIN SMALL LETTER D", "Ll", 0),
  ("LATIN SMALL LETTER E", "Ll", 0),
  ("LATIN SMALL LETTER F", "Ll", 0),
  ("LATIN SMALL LETTER G", "Ll", 0),
  ("LATIN SMALL LETTER H", "Ll", 0),
  ("LATIN SMALL LETTER I", "Ll", 0),
  ("LATIN SMALL LETTER J", "Ll", 0),
  ("LATIN SMALL LETTER K", "Ll", 0),
  ("LATIN SMALL LETTER L", "Ll", 0),
  ("LATIN SMALL LETTER M", "Ll", 0),
  ("LATIN SMALL LETTER N", "Ll", 0),
  ("LATIN SMALL LETTER O", "Ll", 0),
  ("LATIN SMALL LETTER P", "Ll", 0),
  ("LATIN SMALL LETTER Q", "Ll", 0),
  ("LATIN SMALL LETTER R", "Ll", 0),
  ("LATIN SMALL LETTER S", "Ll", 0),
  ("LATIN SMALL LETTER T", "Ll", 0),
  ("LATIN SMALL LETTER U", "Ll", 0),
  ("LATIN SMALL LETTER V", "Ll", 0),
  ("LATIN SMALL LETTER W", "Ll", 0),
  ("LATIN SMALL LETTER X", "Ll", 0),
  ("LATIN SMALL LETTER Y", "Ll", 0),
  ("LATIN SMALL LETTER Z", "Ll", 0),
  ("LEFT CURLY BRACKET", "Ps", 0),
  ("VERTICAL LINE", "Sm", 0),
  ("RIGHT CURLY BRACKET", "Pe", 0),
  ("TILDE", "Sm", 0),
  ("<control>", "Cc", 0),
)
