#let data = (
  ("DOGRA LETTER A", "Lo", 0),
  ("DOGRA LETTER AA", "Lo", 0),
  ("DOGRA LETTER I", "Lo", 0),
  ("DOGRA LETTER II", "Lo", 0),
  ("DOGRA LETTER U", "Lo", 0),
  ("DOGRA LETTER UU", "Lo", 0),
  ("DOGRA LETTER E", "Lo", 0),
  ("DOGRA LETTER AI", "Lo", 0),
  ("DOGRA LETTER O", "Lo", 0),
  ("DOGRA LETTER AU", "Lo", 0),
  ("DOGRA LETTER KA", "Lo", 0),
  ("DOGRA LETTER KHA", "Lo", 0),
  ("DOGRA LETTER GA", "Lo", 0),
  ("DOGRA LETTER GHA", "Lo", 0),
  ("DOGRA LETTER NGA", "Lo", 0),
  ("DOGRA LETTER CA", "Lo", 0),
  ("DOGRA LETTER CHA", "Lo", 0),
  ("DOGRA LETTER JA", "Lo", 0),
  ("DOGRA LETTER JHA", "Lo", 0),
  ("DOGRA LETTER NYA", "Lo", 0),
  ("DOGRA LETTER TTA", "Lo", 0),
  ("DOGRA LETTER TTHA", "Lo", 0),
  ("DOGRA LETTER DDA", "Lo", 0),
  ("DOGRA LETTER DDHA", "Lo", 0),
  ("DOGRA LETTER NNA", "Lo", 0),
  ("DOGRA LETTER TA", "Lo", 0),
  ("DOGRA LETTER THA", "Lo", 0),
  ("DOGRA LETTER DA", "Lo", 0),
  ("DOGRA LETTER DHA", "Lo", 0),
  ("DOGRA LETTER NA", "Lo", 0),
  ("DOGRA LETTER PA", "Lo", 0),
  ("DOGRA LETTER PHA", "Lo", 0),
  ("DOGRA LETTER BA", "Lo", 0),
  ("DOGRA LETTER BHA", "Lo", 0),
  ("DOGRA LETTER MA", "Lo", 0),
  ("DOGRA LETTER YA", "Lo", 0),
  ("DOGRA LETTER RA", "Lo", 0),
  ("DOGRA LETTER LA", "Lo", 0),
  ("DOGRA LETTER VA", "Lo", 0),
  ("DOGRA LETTER SHA", "Lo", 0),
  ("DOGRA LETTER SSA", "Lo", 0),
  ("DOGRA LETTER SA", "Lo", 0),
  ("DOGRA LETTER HA", "Lo", 0),
  ("DOGRA LETTER RRA", "Lo", 0),
  ("DOGRA VOWEL SIGN AA", "Mc", 0),
  ("DOGRA VOWEL SIGN I", "Mc", 0),
  ("DOGRA VOWEL SIGN II", "Mc", 0),
  ("DOGRA VOWEL SIGN U", "Mn", 0),
  ("DOGRA VOWEL SIGN UU", "Mn", 0),
  ("DOGRA VOWEL SIGN VOCALIC R", "Mn", 0),
  ("DOGRA VOWEL SIGN VOCALIC RR", "Mn", 0),
  ("DOGRA VOWEL SIGN E", "Mn", 0),
  ("DOGRA VOWEL SIGN AI", "Mn", 0),
  ("DOGRA VOWEL SIGN O", "Mn", 0),
  ("DOGRA VOWEL SIGN AU", "Mn", 0),
  ("DOGRA SIGN ANUSVARA", "Mn", 0),
  ("DOGRA SIGN VISARGA", "Mc", 0),
  ("DOGRA SIGN VIRAMA", "Mn", 9),
  ("DOGRA SIGN NUKTA", "Mn", 7),
  ("DOGRA ABBREVIATION SIGN", "Po", 0),
)
