[package]
name = "visillos-excelencia"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Jesús Manuel González Meneses"]
license = "MIT"
description = "Unofficial template for Excellence Baccalaureate projects at IES Carmen Martín Gaite (Spain) // Plantilla para los proyectos del Bachillerato de Excelencia del IES Carmen Martín Gaite."
categories = ["report", "thesis"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
