// Copyright (C) 2026 Eito Yoneyama
// SPDX-License-Identifier: GPL-2.0

#import "../engine/config.typ" as _config

#let sequence-type(value) = _config.sequence-type(value)
#let color-scheme(name) = _config.color-scheme(name)
#let scoring-mode(name, option: none) = _config.scoring-mode(name, option: option)
#let tcoffee-scores(source) = scoring-mode("T-Coffee", option: source)
#let sequence-window(sequence, selection, start: none) = _config.sequence-window(sequence, selection, start: start)
#let residues-per-line(value) = _config.residues-per-line(value)
#let threshold(value) = _config.threshold(value)
#let shade-all-residues() = _config.shade-all-residues()
#let all-match-threshold(value: 100) = _config.all-match-threshold(value: value)
#let disable-all-match-threshold() = _config.disable-all-match-threshold()
#let hide-all-match-positions() = _config.hide-all-match-positions()
#let show-all-match-positions() = _config.show-all-match-positions()

#let weight-table(name) = _config.weight-table(name)
#let set-weight(residue-a, residue-b, value) = _config.set-weight(residue-a, residue-b, value)
#let gap-penalty(value) = _config.gap-penalty(value)

#let residue-style(target, fg, bg, case: "upper", style: "normal") = _config.residue-style(target, fg, bg, case: case, style: style)
#let peptide-groups(groups) = _config.peptide-groups(groups)
#let dna-groups(groups) = _config.dna-groups(groups)
#let peptide-similarities(residue, similars) = _config.peptide-similarities(residue, similars)
#let dna-similarities(residue, similars) = _config.dna-similarities(residue, similars)
#let clear-functional-groups() = _config.clear-functional-groups()
#let functional-group(name, residues, fg, bg, case: "upper", style: "normal") = _config.functional-group(name, residues, fg, bg, case: case, style: style)
#let functional-style(residue, fg, bg, case: "upper", style: "normal") = _config.functional-style(residue, fg, bg, case: case, style: style)

#let names-track(position: "left", color: none) = _config.names-track(position: position, color: color)
#let no-names() = _config.no-names-track()
#let numbering-track(position: "right", color: none) = _config.numbering-track(position: position, color: color)
#let no-numbering() = _config.no-numbering-track()
#let sequence-name(sequence, name) = _config.sequence-name(sequence, name)
#let names-color(color) = _config.names-color(color)
#let sequence-name-color(sequences, color) = _config.sequence-name-color(sequences, color)
#let hide-sequence-name(sequences) = _config.hide-sequence-name(sequences)
#let numbering-color(color) = _config.numbering-color(color)
#let sequence-number-color(sequences, color) = _config.sequence-number-color(sequences, color)
#let hide-sequence-number(sequences) = _config.hide-sequence-number(sequences)

#let consensus-name(name) = _config.consensus-name(name)
#let consensus-language(name) = _config.language(name)
#let consensus-symbols(none-symbol, conserved-symbol, allmatch-symbol) = _config.consensus-symbols(none-symbol, conserved-symbol, allmatch-symbol)
#let consensus-colors(none-fg: "Black", none-bg: "White", conserved-fg: "Black", conserved-bg: "White", allmatch-fg: "Black", allmatch-bg: "White") = _config.consensus-colors(
  none-fg: none-fg,
  none-bg: none-bg,
  conserved-fg: conserved-fg,
  conserved-bg: conserved-bg,
  allmatch-fg: allmatch-fg,
  allmatch-bg: allmatch-bg,
)
#let consensus-from-sequence(sequence) = _config.consensus-from-sequence(sequence)
#let consensus-from-all-sequences() = _config.consensus-from-all-sequences()

#let ruler-steps(value, position: none) = _config.ruler-steps(value, position: position)
#let ruler-color(color, position: none) = _config.ruler-color(color, position: position)
#let ruler-name(name, position: none) = _config.ruler-name(name, position: position)
#let ruler-name-color(color, position: none) = _config.ruler-name-color(color, position: position)
#let ruler-space(value, position: none) = _config.ruler-space(value, position: position)
#let rotate-ruler(position: none) = _config.rotate-ruler(position)
#let unrotate-ruler(position: none) = _config.unrotate-ruler(position)

#let gap-char(symbol) = _config.gap-char(symbol)
#let gap-rule(thickness) = _config.gap-rule(thickness)
#let gap-colors(foreground, background) = _config.gap-colors(foreground, background)
#let stop-char(symbol) = _config.stop-char(symbol)
#let show-leading-gaps() = _config.show-leading-gaps()
#let hide-leading-gaps() = _config.hide-leading-gaps()

#let start-number(sequence, start, selection: none) = _config.start-number(sequence, start, selection: selection)
#let allow-zero-numbering() = _config.allow-zero-numbering()
#let disallow-zero-numbering() = _config.disallow-zero-numbering()
#let sequence-length(sequence, length) = _config.sequence-length(sequence, length)
#let domain(sequence, selection) = _config.domain(sequence, selection)
#let domain-gap-rule(thickness) = _config.domain-gap-rule(thickness)
#let domain-gap-colors(foreground, background) = _config.domain-gap-colors(foreground, background)

#let highlight-block(sequence, selection, ..args) = _config.highlight-block(sequence, selection, ..args)
#let region-color-scheme(sequence, selection, scheme) = _config.region-color-scheme(sequence, selection, scheme)
#let lower(sequence, selection) = _config.region-lower(sequence, selection)
#let lower-block(sequence, selection) = _config.lower-block(sequence, selection)
#let emphasis-block(sequence, selection, style: "italic") = _config.emphasis-block(sequence, selection, style: style)
#let tint-block(sequence, selection, intensity: "medium") = _config.tint-block(sequence, selection, intensity: intensity)
#let tint-default(effect) = _config.tint-default(effect)
#let emphasis-default(style) = _config.emphasis-default(style)
#let frame(sequence, selection, color: "Red") = _config.frame-block(sequence, selection, color: color)

#let hide-sequence(sequence) = _config.hide-sequence(sequence)
#let hide-all-sequences() = _config.hide-all-sequences()
#let show-all-sequences() = _config.show-all-sequences()
#let remove-sequence(sequence) = _config.remove-sequence(sequence)
#let no-shade(sequences) = _config.no-shade(sequences)
#let separation-line(sequence) = _config.separation-line(sequence)
#let sequence-order(order) = _config.sequence-order(order)

#let feature-rule(thickness) = _config.feature-rule(thickness)
#let codon(residue, triplets) = _config.codon(residue, triplets)
#let genetic-code(name) = _config.genetic-code(name)
#let backtranslation-label(..args) = _config.backtranslation-label(..args)
#let backtranslation-text(..args) = _config.backtranslation-text(..args)
#let feature-text-label(position, name) = _config.feature-text-label(position, name)
#let feature-style-label(position, name) = _config.feature-style-label(position, name)
#let hide-feature-text-label(position) = _config.hide-feature-text-label(position)
#let hide-feature-style-label(position) = _config.hide-feature-style-label(position)
#let hide-feature-text-labels() = _config.hide-feature-text-labels()
#let hide-feature-style-labels() = _config.hide-feature-style-labels()
#let feature-text-label-color(color) = _config.feature-text-label-color(color)
#let feature-style-label-color(color) = _config.feature-style-label-color(color)
#let feature-text-label-color-at(position, color) = _config.feature-text-label-color-at(position, color)
#let feature-style-label-color-at(position, color) = _config.feature-style-label-color-at(position, color)

#let frequency-correction() = _config.frequency-correction()
#let no-frequency-correction() = _config.no-frequency-correction()
#let subfamily(sequences) = _config.subfamily(sequences)
#let sequence-logo-name(name) = _config.sequence-logo-name(name)
#let subfamily-logo-name(name, negative-name: none) = _config.subfamily-logo-name(name, negative-name: negative-name)
#let logo-scale(position: "leftright", color: "Black") = _config.logo-scale(position: position, color: color)
#let no-logo-scale() = _config.no-logo-scale()
#let logo-stretch(value) = _config.logo-stretch(value)
#let negative-logo-values() = _config.negative-logo-values()
#let no-negative-logo-values() = _config.no-negative-logo-values()
#let relevance-threshold(value) = _config.relevance-threshold(value)
#let relevance-marker(char: "*", color: "Black") = _config.relevance-marker(char: char, color: color)
#let no-relevance-marker() = _config.no-relevance-marker()
#let logo-color(residues, color) = _config.logo-color(residues, color)
#let clear-logo-colors(default: "Black") = _config.clear-logo-colors(default: default)

#let no-legend() = _config.no-legend-track()
#let legend-color(color) = _config.legend-color(color)
#let legend-offset(dx, dy) = _config.legend-offset(dx, dy)
#let color-swatch(color) = _config.color-swatch(color)

#let show-structure-types(format, types) = _config.show-structure-types(format, types)
#let hide-structure-types(format, types) = _config.hide-structure-types(format, types)
#let structure-appearance(format, structure-type, position, style, text) = _config.structure-appearance(format, structure-type, position, style, text)
#let use-first-dssp-column() = _config.use-first-dssp-column()
#let use-second-dssp-column() = _config.use-second-dssp-column()
#let stride-track(sequence, source) = _config.stride-track(sequence, source)
#let dssp-track(sequence, source) = _config.dssp-track(sequence, source)
#let hmmtop-track(sequence, source, source-sequence: none) = _config.hmmtop-track(sequence, source, source-sequence: source-sequence)
#let phd-topology-track(sequence, source) = _config.phd-topology-track(sequence, source)
#let phd-secondary-track(sequence, source) = _config.phd-secondary-track(sequence, source)

#let keep-single-sequence-gaps() = _config.keep-single-sequence-gaps()
#let shift-single-sequence(value: -1) = _config.shift-single-sequence(value)
#let hide-residues() = _config.hide-residues()
#let show-residues() = _config.show-residues()
#let bar-graph-stretch(value, position: none) = _config.bar-graph-stretch(value, position: position)
#let color-scale-stretch(value, position: none) = _config.color-scale-stretch(value, position: position)
#let alignment-position(position) = _config.alignment(position)
#let character-stretch(value) = _config.character-stretch(value)
#let line-stretch(value) = _config.line-stretch(value)
#let numbering-width(digits) = _config.numbering-width(digits)
#let fingerprint(value) = _config.fingerprint(value)
#let align-right-labels() = _config.align-right-labels()
#let align-left-labels() = _config.align-left-labels()

#let text-family(target, family) = _config.text-family(target, family)
#let text-weight(target, weight) = _config.text-weight(target, weight)
#let text-posture(target, posture) = _config.text-posture(target, posture)
#let text-size(target, size) = _config.text-size(target, size)
#let text-style(target, family, weight, posture, size) = _config.text-style(target, family, weight, posture, size)

#let caption(text, position: "bottom") = _config.caption(text, position: position)
#let short-caption(text) = _config.short-caption(text)
#let small-separator() = _config.small-separator()
#let medium-separator() = _config.medium-separator()
#let large-separator() = _config.large-separator()
#let no-block-gap() = _config.no-block-gap()
#let small-block-gap() = _config.small-block-gap()
#let medium-block-gap() = _config.medium-block-gap()
#let large-block-gap() = _config.large-block-gap()
#let block-gap(value) = _config.block-gap(value)
#let flexible-block-gap() = _config.flexible-block-gap()
#let fixed-block-gap() = _config.fixed-block-gap()
#let no-line-gap() = _config.no-line-gap()
#let small-line-gap() = _config.small-line-gap()
#let medium-line-gap() = _config.medium-line-gap()
#let large-line-gap() = _config.large-line-gap()
#let line-gap(value) = _config.line-gap(value)
#let feature-slot-space(position, value) = _config.feature-slot-space(position, value)

#let molecular-weight(sequence, unit: "Da") = _config.molweight(sequence, unit: unit)
#let net-charge(sequence, termini: "o") = _config.charge(sequence, termini: termini)
#let pdb-selection(selection) = _config.pdb-selection(selection)
