[package]
name = "jq"
version = "0.1.0"
compiler = "0.13.0"
entrypoint = "lib.typ"
authors = ["lublak"]
license = "MIT"
description = "Run jq filter agains data."

repository = "https://github.com/lublak/typst-jq-package"

keywords = [
    "jq",
    "jqlang",
    "json",
    "slice",
    "filter",
    "map",
    "transform",
    "processor",
]
