// Shared UI-language helpers for translatable labels.

#let _ui-lang-aliases = (
  "en": "en",
  "english": "en",
  "fr": "fr",
  "french": "fr",
  "pt": "pt",
  "portuguese": "pt",
)

#let _ui-lang-available = "en, english, fr, french, pt, portuguese"

#let resolve-ui-lang(ui-lang) = {
  if type(ui-lang) != str {
    none
  } else {
    let key = lower(ui-lang.trim())
    _ui-lang-aliases.at(key, default: none)
  }
}

#let ui-lang-error(ui-lang) = [*Error:* UI language "#ui-lang" not available. \
  Available UI languages: #_ui-lang-available]

#let _consonant-ui-labels = (
  "en": (
    places: (
      "Bilabial",
      "Labiodental",
      "Dental",
      "Alveolar",
      "Postalveolar",
      "Retroflex",
      "Palatal",
      "Velar",
      "Uvular",
      "Pharyngeal",
      "Glottal",
    ),
    places_short: (
      "Bilab",
      "Labdent",
      "Dent",
      "Alv",
      "Postalv",
      "Retro",
      "Pal",
      "Vel",
      "Uvu",
      "Phar",
      "Glot",
    ),
    manners: (
      "Plosive",
      "Nasal",
      "Trill",
      "Tap or Flap",
      "Fricative",
      "Lateral fricative",
      "Approximant",
      "Lateral approximant",
    ),
    manners_short: (
      "Plos",
      "Nas",
      "Trill",
      "Tap/Flap",
      "Fric",
      "Lat fric",
      "Approx",
      "Lat approx",
    ),
    aspirated_plosive: "Plosive (aspirated)",
    aspirated_plosive_short: "Plos (asp)",
    affricate: "Affricate",
    affricate_short: "Affr",
    aspirated_affricate: "Affricate (aspirated)",
    aspirated_affricate_short: "Affr (asp)",
  ),
  "fr": (
    places: (
      "Bilabiale",
      "Labio-dentale",
      "Dentale",
      "Alvéolaire",
      "Post-alvéolaire",
      "Retroflexe",
      "Palatale",
      "Vélaire",
      "Uvulaire",
      "Pharyngale",
      "Glottale",
    ),
    places_short: (
      "Bilab",
      "Labiod",
      "Dent",
      "Alv",
      "Postalv",
      "Retrof",
      "Pal",
      "Vel",
      "Uvul",
      "Phar",
      "Glot",
    ),
    manners: (
      "Plosive",
      "Nasale",
      "Vibrante",
      "Battue",
      "Fricative",
      "Fricative latérale",
      "Approximante",
      "Approximante latérale",
    ),
    manners_short: (
      "Plos",
      "Nas",
      "Vibr",
      "Batt",
      "Fric",
      "Fric lat",
      "Approx",
      "Approx lat",
    ),
    aspirated_plosive: "Plosive (aspirée)",
    aspirated_plosive_short: "Plos (asp)",
    affricate: "Affriquée",
    affricate_short: "Affr",
    aspirated_affricate: "Affriquée (aspirée)",
    aspirated_affricate_short: "Affr (asp)",
  ),
  "pt": (
    places: (
      "Bilabial",
      "Labiodental",
      "Dental",
      "Alveolar",
      "Pós-alveolar",
      "Retroflexa",
      "Palatal",
      "Velar",
      "Uvular",
      "Faríngea",
      "Glotal",
    ),
    places_short: (
      "Bilab",
      "Labdent",
      "Dent",
      "Alv",
      "Posalv",
      "Retrof",
      "Pal",
      "Vel",
      "Uvul",
      "Far",
      "Glot",
    ),
    manners: (
      "Plosiva",
      "Nasal",
      "Vibrante",
      "Tepe",
      "Fricativa",
      "Fricativa lateral",
      "Aproximante",
      "Aproximante lateral",
    ),
    manners_short: (
      "Plos",
      "Nas",
      "Vibr",
      "Tepe",
      "Fric",
      "Fric lat",
      "Aprox",
      "Aprox lat",
    ),
    aspirated_plosive: "Plosiva (aspirada)",
    aspirated_plosive_short: "Plos (asp)",
    affricate: "Africada",
    affricate_short: "Afr",
    aspirated_affricate: "Africada (aspirada)",
    aspirated_affricate_short: "Afr (asp)",
  ),
)

#let ui-consonant-labels(ui-lang) = _consonant-ui-labels.at(ui-lang)

#let _feature-ui-labels = (
  "en": (
    "consonantal": "consonantal",
    "sonorant": "sonorant",
    "continuant": "continuant",
    "delayed_release": "del rel",
    "approximant": "approximant",
    "tap": "tap",
    "trill": "trill",
    "nasal": "nasal",
    "voice": "voice",
    "spread_gl": "spread gl",
    "constr_gl": "constr gl",
    "labial": "labial",
    "round": "round",
    "labiodental": "labiodental",
    "coronal": "coronal",
    "anterior": "anterior",
    "distributed": "distributed",
    "strident": "strident",
    "lateral": "lateral",
    "dorsal": "dorsal",
    "high": "high",
    "low": "low",
    "front": "front",
    "back": "back",
    "tense": "tense",
  ),
  "fr": (
    "consonantal": "consonantique",
    "sonorant": "sonant",
    "continuant": "continu",
    "delayed_release": "rel ret",
    "approximant": "approximant",
    "tap": "battu",
    "trill": "vibrant",
    "nasal": "nasal",
    "voice": "voisé",
    "spread_gl": "gl écartée",
    "constr_gl": "gl contr",
    "labial": "labial",
    "round": "arrondi",
    "labiodental": "labio-dental",
    "coronal": "coronal",
    "anterior": "antérieur",
    "distributed": "distribué",
    "strident": "strident",
    "lateral": "latéral",
    "dorsal": "dorsal",
    "high": "haut",
    "low": "bas",
    "front": "antérieur",
    "back": "postérieur",
    "tense": "tendu",
  ),
  "pt": (
    "consonantal": "consonantal",
    "sonorant": "sonorante",
    "continuant": "contínuo",
    "delayed_release": "lib ret",
    "approximant": "aproximante",
    "tap": "tepe",
    "trill": "vibrante",
    "nasal": "nasal",
    "voice": "vozeado",
    "spread_gl": "gl aberta",
    "constr_gl": "gl constr",
    "labial": "labial",
    "round": "arredondado",
    "labiodental": "labiodental",
    "coronal": "coronal",
    "anterior": "anterior",
    "distributed": "distribuído",
    "strident": "estridente",
    "lateral": "lateral",
    "dorsal": "dorsal",
    "high": "alto",
    "low": "baixo",
    "front": "anterior",
    "back": "posterior",
    "tense": "tenso",
  ),
)

#let ui-feature-label(key, ui-lang) = _feature-ui-labels.at(ui-lang).at(key, default: key)

#let _geom-ui-labels = (
  "en": (
    "root": "root",
    "laryngeal": "laryngeal",
    "oral cavity": "oral cavity",
    "C-place": "C-place",
    "vocalic": "vocalic",
    "V-place": "V-place",
    "aperture": "aperture",
    "constricted": "constr",
    "continuant": "cont",
    "distributed": "distr",
    "dorsal": "dor",
    "coronal": "cor",
    "labial": "lab",
    "anterior": "ant",
    "radical": "rad",
    "high": "hi",
    "low": "low",
    "back": "back",
    "round": "round",
    "tense": "tense",
    "voice": "voice",
    "nasal": "nasal",
    "spread": "spread",
    "open1": "open1",
    "open2": "open2",
    "open3": "open3",
  ),
  "fr": (
    "root": "racine",
    "laryngeal": "laryng",
    "oral cavity": "cav orale",
    "C-place": "lieu C",
    "vocalic": "vocaliq",
    "V-place": "lieu V",
    "aperture": "apert",
    "constricted": "constr",
    "continuant": "cont",
    "distributed": "distr",
    "dorsal": "dor",
    "coronal": "cor",
    "labial": "lab",
    "anterior": "ant",
    "radical": "rad",
    "high": "haut",
    "low": "bas",
    "back": "post",
    "round": "arr",
    "tense": "tens",
    "voice": "vois",
    "nasal": "nas",
    "spread": "écart",
    "open1": "ouv1",
    "open2": "ouv2",
    "open3": "ouv3",
  ),
  "pt": (
    "root": "raiz",
    "laryngeal": "laring",
    "oral cavity": "cav oral",
    "C-place": "ponto C",
    "vocalic": "vocal",
    "V-place": "ponto V",
    "aperture": "abert",
    "constricted": "constr",
    "continuant": "cont",
    "distributed": "distr",
    "dorsal": "dor",
    "coronal": "cor",
    "labial": "lab",
    "anterior": "ant",
    "radical": "rad",
    "high": "alto",
    "low": "baixo",
    "back": "post",
    "round": "arr",
    "tense": "tens",
    "voice": "voz",
    "nasal": "nas",
    "spread": "abert",
    "open1": "abr1",
    "open2": "abr2",
    "open3": "abr3",
  ),
)

#let ui-geom-label(key, ui-lang) = _geom-ui-labels.at(ui-lang).at(key, default: key)
