#let data = (
  ("NORTH INDIC FRACTION ONE QUARTER", "No", 0),
  ("NORTH INDIC FRACTION ONE HALF", "No", 0),
  ("NORTH INDIC FRACTION THREE QUARTERS", "No", 0),
  ("NORTH INDIC FRACTION ONE SIXTEENTH", "No", 0),
  ("NORTH INDIC FRACTION ONE EIGHTH", "No", 0),
  ("NORTH INDIC FRACTION THREE SIXTEENTHS", "No", 0),
  ("NORTH INDIC QUARTER MARK", "So", 0),
  ("NORTH INDIC PLACEHOLDER MARK", "So", 0),
  ("NORTH INDIC RUPEE MARK", "Sc", 0),
  ("NORTH INDIC QUANTITY MARK", "So", 0),
)
