#let data = (
  ("KHOJKI LETTER A", "Lo", 0),
  ("KHOJKI LETTER AA", "Lo", 0),
  ("KHOJKI LETTER I", "Lo", 0),
  ("KHOJKI LETTER U", "Lo", 0),
  ("KHOJKI LETTER E", "Lo", 0),
  ("KHOJKI LETTER AI", "Lo", 0),
  ("KHOJKI LETTER O", "Lo", 0),
  ("KHOJKI LETTER AU", "Lo", 0),
  ("KHOJKI LETTER KA", "Lo", 0),
  ("KHOJKI LETTER KHA", "Lo", 0),
  ("KHOJKI LETTER GA", "Lo", 0),
  ("KHOJKI LETTER GGA", "Lo", 0),
  ("KHOJKI LETTER GHA", "Lo", 0),
  ("KHOJKI LETTER NGA", "Lo", 0),
  ("KHOJKI LETTER CA", "Lo", 0),
  ("KHOJKI LETTER CHA", "Lo", 0),
  ("KHOJKI LETTER JA", "Lo", 0),
  ("KHOJKI LETTER JJA", "Lo", 0),
  (),
  ("KHOJKI LETTER NYA", "Lo", 0),
  ("KHOJKI LETTER TTA", "Lo", 0),
  ("KHOJKI LETTER TTHA", "Lo", 0),
  ("KHOJKI LETTER DDA", "Lo", 0),
  ("KHOJKI LETTER DDHA", "Lo", 0),
  ("KHOJKI LETTER NNA", "Lo", 0),
  ("KHOJKI LETTER TA", "Lo", 0),
  ("KHOJKI LETTER THA", "Lo", 0),
  ("KHOJKI LETTER DA", "Lo", 0),
  ("KHOJKI LETTER DDDA", "Lo", 0),
  ("KHOJKI LETTER DHA", "Lo", 0),
  ("KHOJKI LETTER NA", "Lo", 0),
  ("KHOJKI LETTER PA", "Lo", 0),
  ("KHOJKI LETTER PHA", "Lo", 0),
  ("KHOJKI LETTER BA", "Lo", 0),
  ("KHOJKI LETTER BBA", "Lo", 0),
  ("KHOJKI LETTER BHA", "Lo", 0),
  ("KHOJKI LETTER MA", "Lo", 0),
  ("KHOJKI LETTER YA", "Lo", 0),
  ("KHOJKI LETTER RA", "Lo", 0),
  ("KHOJKI LETTER LA", "Lo", 0),
  ("KHOJKI LETTER VA", "Lo", 0),
  ("KHOJKI LETTER SA", "Lo", 0),
  ("KHOJKI LETTER HA", "Lo", 0),
  ("KHOJKI LETTER LLA", "Lo", 0),
  ("KHOJKI VOWEL SIGN AA", "Mc", 0),
  ("KHOJKI VOWEL SIGN I", "Mc", 0),
  ("KHOJKI VOWEL SIGN II", "Mc", 0),
  ("KHOJKI VOWEL SIGN U", "Mn", 0),
  ("KHOJKI VOWEL SIGN E", "Mn", 0),
  ("KHOJKI VOWEL SIGN AI", "Mn", 0),
  ("KHOJKI VOWEL SIGN O", "Mc", 0),
  ("KHOJKI VOWEL SIGN AU", "Mc", 0),
  ("KHOJKI SIGN ANUSVARA", "Mn", 0),
  ("KHOJKI SIGN VIRAMA", "Mc", 9),
  ("KHOJKI SIGN NUKTA", "Mn", 7),
  ("KHOJKI SIGN SHADDA", "Mn", 0),
  ("KHOJKI DANDA", "Po", 0),
  ("KHOJKI DOUBLE DANDA", "Po", 0),
  ("KHOJKI WORD SEPARATOR", "Po", 0),
  ("KHOJKI SECTION MARK", "Po", 0),
  ("KHOJKI DOUBLE SECTION MARK", "Po", 0),
  ("KHOJKI ABBREVIATION SIGN", "Po", 0),
  ("KHOJKI SIGN SUKUN", "Mn", 0),
  ("KHOJKI LETTER QA", "Lo", 0),
  ("KHOJKI LETTER SHORT I", "Lo", 0),
  ("KHOJKI VOWEL SIGN VOCALIC R", "Mn", 0),
)
