#let data = (
  (),
  ("ORIYA SIGN CANDRABINDU", "Mn", 0),
  ("ORIYA SIGN ANUSVARA", "Mc", 0),
  ("ORIYA SIGN VISARGA", "Mc", 0),
  (),
  ("ORIYA LETTER A", "Lo", 0),
  ("ORIYA LETTER AA", "Lo", 0),
  ("ORIYA LETTER I", "Lo", 0),
  ("ORIYA LETTER II", "Lo", 0),
  ("ORIYA LETTER U", "Lo", 0),
  ("ORIYA LETTER UU", "Lo", 0),
  ("ORIYA LETTER VOCALIC R", "Lo", 0),
  ("ORIYA LETTER VOCALIC L", "Lo", 0),
  (),
  (),
  ("ORIYA LETTER E", "Lo", 0),
  ("ORIYA LETTER AI", "Lo", 0),
  (),
  (),
  ("ORIYA LETTER O", "Lo", 0),
  ("ORIYA LETTER AU", "Lo", 0),
  ("ORIYA LETTER KA", "Lo", 0),
  ("ORIYA LETTER KHA", "Lo", 0),
  ("ORIYA LETTER GA", "Lo", 0),
  ("ORIYA LETTER GHA", "Lo", 0),
  ("ORIYA LETTER NGA", "Lo", 0),
  ("ORIYA LETTER CA", "Lo", 0),
  ("ORIYA LETTER CHA", "Lo", 0),
  ("ORIYA LETTER JA", "Lo", 0),
  ("ORIYA LETTER JHA", "Lo", 0),
  ("ORIYA LETTER NYA", "Lo", 0),
  ("ORIYA LETTER TTA", "Lo", 0),
  ("ORIYA LETTER TTHA", "Lo", 0),
  ("ORIYA LETTER DDA", "Lo", 0),
  ("ORIYA LETTER DDHA", "Lo", 0),
  ("ORIYA LETTER NNA", "Lo", 0),
  ("ORIYA LETTER TA", "Lo", 0),
  ("ORIYA LETTER THA", "Lo", 0),
  ("ORIYA LETTER DA", "Lo", 0),
  ("ORIYA LETTER DHA", "Lo", 0),
  ("ORIYA LETTER NA", "Lo", 0),
  (),
  ("ORIYA LETTER PA", "Lo", 0),
  ("ORIYA LETTER PHA", "Lo", 0),
  ("ORIYA LETTER BA", "Lo", 0),
  ("ORIYA LETTER BHA", "Lo", 0),
  ("ORIYA LETTER MA", "Lo", 0),
  ("ORIYA LETTER YA", "Lo", 0),
  ("ORIYA LETTER RA", "Lo", 0),
  (),
  ("ORIYA LETTER LA", "Lo", 0),
  ("ORIYA LETTER LLA", "Lo", 0),
  (),
  ("ORIYA LETTER VA", "Lo", 0),
  ("ORIYA LETTER SHA", "Lo", 0),
  ("ORIYA LETTER SSA", "Lo", 0),
  ("ORIYA LETTER SA", "Lo", 0),
  ("ORIYA LETTER HA", "Lo", 0),
  (),
  (),
  ("ORIYA SIGN NUKTA", "Mn", 7),
  ("ORIYA SIGN AVAGRAHA", "Lo", 0),
  ("ORIYA VOWEL SIGN AA", "Mc", 0),
  ("ORIYA VOWEL SIGN I", "Mn", 0),
  ("ORIYA VOWEL SIGN II", "Mc", 0),
  ("ORIYA VOWEL SIGN U", "Mn", 0),
  ("ORIYA VOWEL SIGN UU", "Mn", 0),
  ("ORIYA VOWEL SIGN VOCALIC R", "Mn", 0),
  ("ORIYA VOWEL SIGN VOCALIC RR", "Mn", 0),
  (),
  (),
  ("ORIYA VOWEL SIGN E", "Mc", 0),
  ("ORIYA VOWEL SIGN AI", "Mc", 0),
  (),
  (),
  ("ORIYA VOWEL SIGN O", "Mc", 0),
  ("ORIYA VOWEL SIGN AU", "Mc", 0),
  ("ORIYA SIGN VIRAMA", "Mn", 9),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("ORIYA SIGN OVERLINE", "Mn", 0),
  ("ORIYA AI LENGTH MARK", "Mn", 0),
  ("ORIYA AU LENGTH MARK", "Mc", 0),
  (),
  (),
  (),
  (),
  ("ORIYA LETTER RRA", "Lo", 0),
  ("ORIYA LETTER RHA", "Lo", 0),
  (),
  ("ORIYA LETTER YYA", "Lo", 0),
  ("ORIYA LETTER VOCALIC RR", "Lo", 0),
  ("ORIYA LETTER VOCALIC LL", "Lo", 0),
  ("ORIYA VOWEL SIGN VOCALIC L", "Mn", 0),
  ("ORIYA VOWEL SIGN VOCALIC LL", "Mn", 0),
  (),
  (),
  ("ORIYA DIGIT ZERO", "Nd", 0),
  ("ORIYA DIGIT ONE", "Nd", 0),
  ("ORIYA DIGIT TWO", "Nd", 0),
  ("ORIYA DIGIT THREE", "Nd", 0),
  ("ORIYA DIGIT FOUR", "Nd", 0),
  ("ORIYA DIGIT FIVE", "Nd", 0),
  ("ORIYA DIGIT SIX", "Nd", 0),
  ("ORIYA DIGIT SEVEN", "Nd", 0),
  ("ORIYA DIGIT EIGHT", "Nd", 0),
  ("ORIYA DIGIT NINE", "Nd", 0),
  ("ORIYA ISSHAR", "So", 0),
  ("ORIYA LETTER WA", "Lo", 0),
  ("ORIYA FRACTION ONE QUARTER", "No", 0),
  ("ORIYA FRACTION ONE HALF", "No", 0),
  ("ORIYA FRACTION THREE QUARTERS", "No", 0),
  ("ORIYA FRACTION ONE SIXTEENTH", "No", 0),
  ("ORIYA FRACTION ONE EIGHTH", "No", 0),
  ("ORIYA FRACTION THREE SIXTEENTHS", "No", 0),
)
