#let data = (
  ("TAI LE LETTER KA", "Lo", 0),
  ("TAI LE LETTER XA", "Lo", 0),
  ("TAI LE LETTER NGA", "Lo", 0),
  ("TAI LE LETTER TSA", "Lo", 0),
  ("TAI LE LETTER SA", "Lo", 0),
  ("TAI LE LETTER YA", "Lo", 0),
  ("TAI LE LETTER TA", "Lo", 0),
  ("TAI LE LETTER THA", "Lo", 0),
  ("TAI LE LETTER LA", "Lo", 0),
  ("TAI LE LETTER PA", "Lo", 0),
  ("TAI LE LETTER PHA", "Lo", 0),
  ("TAI LE LETTER MA", "Lo", 0),
  ("TAI LE LETTER FA", "Lo", 0),
  ("TAI LE LETTER VA", "Lo", 0),
  ("TAI LE LETTER HA", "Lo", 0),
  ("TAI LE LETTER QA", "Lo", 0),
  ("TAI LE LETTER KHA", "Lo", 0),
  ("TAI LE LETTER TSHA", "Lo", 0),
  ("TAI LE LETTER NA", "Lo", 0),
  ("TAI LE LETTER A", "Lo", 0),
  ("TAI LE LETTER I", "Lo", 0),
  ("TAI LE LETTER EE", "Lo", 0),
  ("TAI LE LETTER EH", "Lo", 0),
  ("TAI LE LETTER U", "Lo", 0),
  ("TAI LE LETTER OO", "Lo", 0),
  ("TAI LE LETTER O", "Lo", 0),
  ("TAI LE LETTER UE", "Lo", 0),
  ("TAI LE LETTER E", "Lo", 0),
  ("TAI LE LETTER AUE", "Lo", 0),
  ("TAI LE LETTER AI", "Lo", 0),
  (),
  (),
  ("TAI LE LETTER TONE-2", "Lo", 0),
  ("TAI LE LETTER TONE-3", "Lo", 0),
  ("TAI LE LETTER TONE-4", "Lo", 0),
  ("TAI LE LETTER TONE-5", "Lo", 0),
  ("TAI LE LETTER TONE-6", "Lo", 0),
)
