#let data = (
  "2": ("ARABIC LETTER DAL WITH TWO DOTS VERTICALLY BELOW", "Lo", 0),
  "3": ("ARABIC LETTER TAH WITH TWO DOTS VERTICALLY BELOW", "Lo", 0),
  "4": ("ARABIC LETTER KAF WITH TWO DOTS VERTICALLY BELOW", "Lo", 0),
  "3c": ("ARABIC COMBINING ALEF OVERLAY", "Mn", 0),
  "3d": ("ARABIC SMALL LOW WORD SAKTA", "Mn", 220),
  "3e": ("ARABIC SMALL LOW WORD QASR", "Mn", 220),
  "3f": ("ARABIC SMALL LOW WORD MADDA", "Mn", 220),
)
