#let data = (
  ("MULTANI LETTER A", "Lo", 0),
  ("MULTANI LETTER I", "Lo", 0),
  ("MULTANI LETTER U", "Lo", 0),
  ("MULTANI LETTER E", "Lo", 0),
  ("MULTANI LETTER KA", "Lo", 0),
  ("MULTANI LETTER KHA", "Lo", 0),
  ("MULTANI LETTER GA", "Lo", 0),
  (),
  ("MULTANI LETTER GHA", "Lo", 0),
  (),
  ("MULTANI LETTER CA", "Lo", 0),
  ("MULTANI LETTER CHA", "Lo", 0),
  ("MULTANI LETTER JA", "Lo", 0),
  ("MULTANI LETTER JJA", "Lo", 0),
  (),
  ("MULTANI LETTER NYA", "Lo", 0),
  ("MULTANI LETTER TTA", "Lo", 0),
  ("MULTANI LETTER TTHA", "Lo", 0),
  ("MULTANI LETTER DDA", "Lo", 0),
  ("MULTANI LETTER DDDA", "Lo", 0),
  ("MULTANI LETTER DDHA", "Lo", 0),
  ("MULTANI LETTER NNA", "Lo", 0),
  ("MULTANI LETTER TA", "Lo", 0),
  ("MULTANI LETTER THA", "Lo", 0),
  ("MULTANI LETTER DA", "Lo", 0),
  ("MULTANI LETTER DHA", "Lo", 0),
  ("MULTANI LETTER NA", "Lo", 0),
  ("MULTANI LETTER PA", "Lo", 0),
  ("MULTANI LETTER PHA", "Lo", 0),
  ("MULTANI LETTER BA", "Lo", 0),
  (),
  ("MULTANI LETTER BHA", "Lo", 0),
  ("MULTANI LETTER MA", "Lo", 0),
  ("MULTANI LETTER YA", "Lo", 0),
  ("MULTANI LETTER RA", "Lo", 0),
  ("MULTANI LETTER LA", "Lo", 0),
  ("MULTANI LETTER VA", "Lo", 0),
  ("MULTANI LETTER SA", "Lo", 0),
  ("MULTANI LETTER HA", "Lo", 0),
  ("MULTANI LETTER RRA", "Lo", 0),
  ("MULTANI LETTER RHA", "Lo", 0),
  ("MULTANI SECTION MARK", "Po", 0),
)
