#let data = (
  "9": ("INTERLINEAR ANNOTATION ANCHOR", "Cf", 0),
  "a": ("INTERLINEAR ANNOTATION SEPARATOR", "Cf", 0),
  "b": ("INTERLINEAR ANNOTATION TERMINATOR", "Cf", 0),
  "c": ("OBJECT REPLACEMENT CHARACTER", "So", 0),
  "d": ("REPLACEMENT CHARACTER", "So", 0),
)
