#let data = (
  ("TAI VIET LETTER LOW KO", "Lo", 0),
  ("TAI VIET LETTER HIGH KO", "Lo", 0),
  ("TAI VIET LETTER LOW KHO", "Lo", 0),
  ("TAI VIET LETTER HIGH KHO", "Lo", 0),
  ("TAI VIET LETTER LOW KHHO", "Lo", 0),
  ("TAI VIET LETTER HIGH KHHO", "Lo", 0),
  ("TAI VIET LETTER LOW GO", "Lo", 0),
  ("TAI VIET LETTER HIGH GO", "Lo", 0),
  ("TAI VIET LETTER LOW NGO", "Lo", 0),
  ("TAI VIET LETTER HIGH NGO", "Lo", 0),
  ("TAI VIET LETTER LOW CO", "Lo", 0),
  ("TAI VIET LETTER HIGH CO", "Lo", 0),
  ("TAI VIET LETTER LOW CHO", "Lo", 0),
  ("TAI VIET LETTER HIGH CHO", "Lo", 0),
  ("TAI VIET LETTER LOW SO", "Lo", 0),
  ("TAI VIET LETTER HIGH SO", "Lo", 0),
  ("TAI VIET LETTER LOW NYO", "Lo", 0),
  ("TAI VIET LETTER HIGH NYO", "Lo", 0),
  ("TAI VIET LETTER LOW DO", "Lo", 0),
  ("TAI VIET LETTER HIGH DO", "Lo", 0),
  ("TAI VIET LETTER LOW TO", "Lo", 0),
  ("TAI VIET LETTER HIGH TO", "Lo", 0),
  ("TAI VIET LETTER LOW THO", "Lo", 0),
  ("TAI VIET LETTER HIGH THO", "Lo", 0),
  ("TAI VIET LETTER LOW NO", "Lo", 0),
  ("TAI VIET LETTER HIGH NO", "Lo", 0),
  ("TAI VIET LETTER LOW BO", "Lo", 0),
  ("TAI VIET LETTER HIGH BO", "Lo", 0),
  ("TAI VIET LETTER LOW PO", "Lo", 0),
  ("TAI VIET LETTER HIGH PO", "Lo", 0),
  ("TAI VIET LETTER LOW PHO", "Lo", 0),
  ("TAI VIET LETTER HIGH PHO", "Lo", 0),
  ("TAI VIET LETTER LOW FO", "Lo", 0),
  ("TAI VIET LETTER HIGH FO", "Lo", 0),
  ("TAI VIET LETTER LOW MO", "Lo", 0),
  ("TAI VIET LETTER HIGH MO", "Lo", 0),
  ("TAI VIET LETTER LOW YO", "Lo", 0),
  ("TAI VIET LETTER HIGH YO", "Lo", 0),
  ("TAI VIET LETTER LOW RO", "Lo", 0),
  ("TAI VIET LETTER HIGH RO", "Lo", 0),
  ("TAI VIET LETTER LOW LO", "Lo", 0),
  ("TAI VIET LETTER HIGH LO", "Lo", 0),
  ("TAI VIET LETTER LOW VO", "Lo", 0),
  ("TAI VIET LETTER HIGH VO", "Lo", 0),
  ("TAI VIET LETTER LOW HO", "Lo", 0),
  ("TAI VIET LETTER HIGH HO", "Lo", 0),
  ("TAI VIET LETTER LOW O", "Lo", 0),
  ("TAI VIET LETTER HIGH O", "Lo", 0),
  ("TAI VIET MAI KANG", "Mn", 230),
  ("TAI VIET VOWEL AA", "Lo", 0),
  ("TAI VIET VOWEL I", "Mn", 230),
  ("TAI VIET VOWEL UE", "Mn", 230),
  ("TAI VIET VOWEL U", "Mn", 220),
  ("TAI VIET VOWEL E", "Lo", 0),
  ("TAI VIET VOWEL O", "Lo", 0),
  ("TAI VIET MAI KHIT", "Mn", 230),
  ("TAI VIET VOWEL IA", "Mn", 230),
  ("TAI VIET VOWEL UEA", "Lo", 0),
  ("TAI VIET VOWEL UA", "Lo", 0),
  ("TAI VIET VOWEL AUE", "Lo", 0),
  ("TAI VIET VOWEL AY", "Lo", 0),
  ("TAI VIET VOWEL AN", "Lo", 0),
  ("TAI VIET VOWEL AM", "Mn", 230),
  ("TAI VIET TONE MAI EK", "Mn", 230),
  ("TAI VIET TONE MAI NUENG", "Lo", 0),
  ("TAI VIET TONE MAI THO", "Mn", 230),
  ("TAI VIET TONE MAI SONG", "Lo", 0),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TAI VIET SYMBOL KON", "Lo", 0),
  ("TAI VIET SYMBOL NUENG", "Lo", 0),
  ("TAI VIET SYMBOL SAM", "Lm", 0),
  ("TAI VIET SYMBOL HO HOI", "Po", 0),
  ("TAI VIET SYMBOL KOI KOI", "Po", 0),
)
