#let data = (
  ("WANCHO LETTER AA", "Lo", 0),
  ("WANCHO LETTER A", "Lo", 0),
  ("WANCHO LETTER BA", "Lo", 0),
  ("WANCHO LETTER CA", "Lo", 0),
  ("WANCHO LETTER DA", "Lo", 0),
  ("WANCHO LETTER GA", "Lo", 0),
  ("WANCHO LETTER YA", "Lo", 0),
  ("WANCHO LETTER PHA", "Lo", 0),
  ("WANCHO LETTER LA", "Lo", 0),
  ("WANCHO LETTER NA", "Lo", 0),
  ("WANCHO LETTER PA", "Lo", 0),
  ("WANCHO LETTER TA", "Lo", 0),
  ("WANCHO LETTER THA", "Lo", 0),
  ("WANCHO LETTER FA", "Lo", 0),
  ("WANCHO LETTER SA", "Lo", 0),
  ("WANCHO LETTER SHA", "Lo", 0),
  ("WANCHO LETTER JA", "Lo", 0),
  ("WANCHO LETTER ZA", "Lo", 0),
  ("WANCHO LETTER WA", "Lo", 0),
  ("WANCHO LETTER VA", "Lo", 0),
  ("WANCHO LETTER KA", "Lo", 0),
  ("WANCHO LETTER O", "Lo", 0),
  ("WANCHO LETTER AU", "Lo", 0),
  ("WANCHO LETTER RA", "Lo", 0),
  ("WANCHO LETTER MA", "Lo", 0),
  ("WANCHO LETTER KHA", "Lo", 0),
  ("WANCHO LETTER HA", "Lo", 0),
  ("WANCHO LETTER E", "Lo", 0),
  ("WANCHO LETTER I", "Lo", 0),
  ("WANCHO LETTER NGA", "Lo", 0),
  ("WANCHO LETTER U", "Lo", 0),
  ("WANCHO LETTER LLHA", "Lo", 0),
  ("WANCHO LETTER TSA", "Lo", 0),
  ("WANCHO LETTER TRA", "Lo", 0),
  ("WANCHO LETTER ONG", "Lo", 0),
  ("WANCHO LETTER AANG", "Lo", 0),
  ("WANCHO LETTER ANG", "Lo", 0),
  ("WANCHO LETTER ING", "Lo", 0),
  ("WANCHO LETTER ON", "Lo", 0),
  ("WANCHO LETTER EN", "Lo", 0),
  ("WANCHO LETTER AAN", "Lo", 0),
  ("WANCHO LETTER NYA", "Lo", 0),
  ("WANCHO LETTER UEN", "Lo", 0),
  ("WANCHO LETTER YIH", "Lo", 0),
  ("WANCHO TONE TUP", "Mn", 230),
  ("WANCHO TONE TUPNI", "Mn", 230),
  ("WANCHO TONE KOI", "Mn", 230),
  ("WANCHO TONE KOINI", "Mn", 230),
  ("WANCHO DIGIT ZERO", "Nd", 0),
  ("WANCHO DIGIT ONE", "Nd", 0),
  ("WANCHO DIGIT TWO", "Nd", 0),
  ("WANCHO DIGIT THREE", "Nd", 0),
  ("WANCHO DIGIT FOUR", "Nd", 0),
  ("WANCHO DIGIT FIVE", "Nd", 0),
  ("WANCHO DIGIT SIX", "Nd", 0),
  ("WANCHO DIGIT SEVEN", "Nd", 0),
  ("WANCHO DIGIT EIGHT", "Nd", 0),
  ("WANCHO DIGIT NINE", "Nd", 0),
  (),
  (),
  (),
  (),
  (),
  ("WANCHO NGUN SIGN", "Sc", 0),
)
