#let data = (
  ("NEWA LETTER A", "Lo", 0),
  ("NEWA LETTER AA", "Lo", 0),
  ("NEWA LETTER I", "Lo", 0),
  ("NEWA LETTER II", "Lo", 0),
  ("NEWA LETTER U", "Lo", 0),
  ("NEWA LETTER UU", "Lo", 0),
  ("NEWA LETTER VOCALIC R", "Lo", 0),
  ("NEWA LETTER VOCALIC RR", "Lo", 0),
  ("NEWA LETTER VOCALIC L", "Lo", 0),
  ("NEWA LETTER VOCALIC LL", "Lo", 0),
  ("NEWA LETTER E", "Lo", 0),
  ("NEWA LETTER AI", "Lo", 0),
  ("NEWA LETTER O", "Lo", 0),
  ("NEWA LETTER AU", "Lo", 0),
  ("NEWA LETTER KA", "Lo", 0),
  ("NEWA LETTER KHA", "Lo", 0),
  ("NEWA LETTER GA", "Lo", 0),
  ("NEWA LETTER GHA", "Lo", 0),
  ("NEWA LETTER NGA", "Lo", 0),
  ("NEWA LETTER NGHA", "Lo", 0),
  ("NEWA LETTER CA", "Lo", 0),
  ("NEWA LETTER CHA", "Lo", 0),
  ("NEWA LETTER JA", "Lo", 0),
  ("NEWA LETTER JHA", "Lo", 0),
  ("NEWA LETTER NYA", "Lo", 0),
  ("NEWA LETTER NYHA", "Lo", 0),
  ("NEWA LETTER TTA", "Lo", 0),
  ("NEWA LETTER TTHA", "Lo", 0),
  ("NEWA LETTER DDA", "Lo", 0),
  ("NEWA LETTER DDHA", "Lo", 0),
  ("NEWA LETTER NNA", "Lo", 0),
  ("NEWA LETTER TA", "Lo", 0),
  ("NEWA LETTER THA", "Lo", 0),
  ("NEWA LETTER DA", "Lo", 0),
  ("NEWA LETTER DHA", "Lo", 0),
  ("NEWA LETTER NA", "Lo", 0),
  ("NEWA LETTER NHA", "Lo", 0),
  ("NEWA LETTER PA", "Lo", 0),
  ("NEWA LETTER PHA", "Lo", 0),
  ("NEWA LETTER BA", "Lo", 0),
  ("NEWA LETTER BHA", "Lo", 0),
  ("NEWA LETTER MA", "Lo", 0),
  ("NEWA LETTER MHA", "Lo", 0),
  ("NEWA LETTER YA", "Lo", 0),
  ("NEWA LETTER RA", "Lo", 0),
  ("NEWA LETTER RHA", "Lo", 0),
  ("NEWA LETTER LA", "Lo", 0),
  ("NEWA LETTER LHA", "Lo", 0),
  ("NEWA LETTER WA", "Lo", 0),
  ("NEWA LETTER SHA", "Lo", 0),
  ("NEWA LETTER SSA", "Lo", 0),
  ("NEWA LETTER SA", "Lo", 0),
  ("NEWA LETTER HA", "Lo", 0),
  ("NEWA VOWEL SIGN AA", "Mc", 0),
  ("NEWA VOWEL SIGN I", "Mc", 0),
  ("NEWA VOWEL SIGN II", "Mc", 0),
  ("NEWA VOWEL SIGN U", "Mn", 0),
  ("NEWA VOWEL SIGN UU", "Mn", 0),
  ("NEWA VOWEL SIGN VOCALIC R", "Mn", 0),
  ("NEWA VOWEL SIGN VOCALIC RR", "Mn", 0),
  ("NEWA VOWEL SIGN VOCALIC L", "Mn", 0),
  ("NEWA VOWEL SIGN VOCALIC LL", "Mn", 0),
  ("NEWA VOWEL SIGN E", "Mn", 0),
  ("NEWA VOWEL SIGN AI", "Mn", 0),
  ("NEWA VOWEL SIGN O", "Mc", 0),
  ("NEWA VOWEL SIGN AU", "Mc", 0),
  ("NEWA SIGN VIRAMA", "Mn", 9),
  ("NEWA SIGN CANDRABINDU", "Mn", 0),
  ("NEWA SIGN ANUSVARA", "Mn", 0),
  ("NEWA SIGN VISARGA", "Mc", 0),
  ("NEWA SIGN NUKTA", "Mn", 7),
  ("NEWA SIGN AVAGRAHA", "Lo", 0),
  ("NEWA SIGN FINAL ANUSVARA", "Lo", 0),
  ("NEWA OM", "Lo", 0),
  ("NEWA SIDDHI", "Lo", 0),
  ("NEWA DANDA", "Po", 0),
  ("NEWA DOUBLE DANDA", "Po", 0),
  ("NEWA COMMA", "Po", 0),
  ("NEWA GAP FILLER", "Po", 0),
  ("NEWA ABBREVIATION SIGN", "Po", 0),
  ("NEWA DIGIT ZERO", "Nd", 0),
  ("NEWA DIGIT ONE", "Nd", 0),
  ("NEWA DIGIT TWO", "Nd", 0),
  ("NEWA DIGIT THREE", "Nd", 0),
  ("NEWA DIGIT FOUR", "Nd", 0),
  ("NEWA DIGIT FIVE", "Nd", 0),
  ("NEWA DIGIT SIX", "Nd", 0),
  ("NEWA DIGIT SEVEN", "Nd", 0),
  ("NEWA DIGIT EIGHT", "Nd", 0),
  ("NEWA DIGIT NINE", "Nd", 0),
  ("NEWA DOUBLE COMMA", "Po", 0),
  ("NEWA PLACEHOLDER MARK", "Po", 0),
  (),
  ("NEWA INSERTION SIGN", "Po", 0),
  ("NEWA SANDHI MARK", "Mn", 230),
  ("NEWA LETTER VEDIC ANUSVARA", "Lo", 0),
  ("NEWA SIGN JIHVAMULIYA", "Lo", 0),
  ("NEWA SIGN UPADHMANIYA", "Lo", 0),
)
