#let data = (
  ("MODI LETTER A", "Lo", 0),
  ("MODI LETTER AA", "Lo", 0),
  ("MODI LETTER I", "Lo", 0),
  ("MODI LETTER II", "Lo", 0),
  ("MODI LETTER U", "Lo", 0),
  ("MODI LETTER UU", "Lo", 0),
  ("MODI LETTER VOCALIC R", "Lo", 0),
  ("MODI LETTER VOCALIC RR", "Lo", 0),
  ("MODI LETTER VOCALIC L", "Lo", 0),
  ("MODI LETTER VOCALIC LL", "Lo", 0),
  ("MODI LETTER E", "Lo", 0),
  ("MODI LETTER AI", "Lo", 0),
  ("MODI LETTER O", "Lo", 0),
  ("MODI LETTER AU", "Lo", 0),
  ("MODI LETTER KA", "Lo", 0),
  ("MODI LETTER KHA", "Lo", 0),
  ("MODI LETTER GA", "Lo", 0),
  ("MODI LETTER GHA", "Lo", 0),
  ("MODI LETTER NGA", "Lo", 0),
  ("MODI LETTER CA", "Lo", 0),
  ("MODI LETTER CHA", "Lo", 0),
  ("MODI LETTER JA", "Lo", 0),
  ("MODI LETTER JHA", "Lo", 0),
  ("MODI LETTER NYA", "Lo", 0),
  ("MODI LETTER TTA", "Lo", 0),
  ("MODI LETTER TTHA", "Lo", 0),
  ("MODI LETTER DDA", "Lo", 0),
  ("MODI LETTER DDHA", "Lo", 0),
  ("MODI LETTER NNA", "Lo", 0),
  ("MODI LETTER TA", "Lo", 0),
  ("MODI LETTER THA", "Lo", 0),
  ("MODI LETTER DA", "Lo", 0),
  ("MODI LETTER DHA", "Lo", 0),
  ("MODI LETTER NA", "Lo", 0),
  ("MODI LETTER PA", "Lo", 0),
  ("MODI LETTER PHA", "Lo", 0),
  ("MODI LETTER BA", "Lo", 0),
  ("MODI LETTER BHA", "Lo", 0),
  ("MODI LETTER MA", "Lo", 0),
  ("MODI LETTER YA", "Lo", 0),
  ("MODI LETTER RA", "Lo", 0),
  ("MODI LETTER LA", "Lo", 0),
  ("MODI LETTER VA", "Lo", 0),
  ("MODI LETTER SHA", "Lo", 0),
  ("MODI LETTER SSA", "Lo", 0),
  ("MODI LETTER SA", "Lo", 0),
  ("MODI LETTER HA", "Lo", 0),
  ("MODI LETTER LLA", "Lo", 0),
  ("MODI VOWEL SIGN AA", "Mc", 0),
  ("MODI VOWEL SIGN I", "Mc", 0),
  ("MODI VOWEL SIGN II", "Mc", 0),
  ("MODI VOWEL SIGN U", "Mn", 0),
  ("MODI VOWEL SIGN UU", "Mn", 0),
  ("MODI VOWEL SIGN VOCALIC R", "Mn", 0),
  ("MODI VOWEL SIGN VOCALIC RR", "Mn", 0),
  ("MODI VOWEL SIGN VOCALIC L", "Mn", 0),
  ("MODI VOWEL SIGN VOCALIC LL", "Mn", 0),
  ("MODI VOWEL SIGN E", "Mn", 0),
  ("MODI VOWEL SIGN AI", "Mn", 0),
  ("MODI VOWEL SIGN O", "Mc", 0),
  ("MODI VOWEL SIGN AU", "Mc", 0),
  ("MODI SIGN ANUSVARA", "Mn", 0),
  ("MODI SIGN VISARGA", "Mc", 0),
  ("MODI SIGN VIRAMA", "Mn", 9),
  ("MODI SIGN ARDHACANDRA", "Mn", 0),
  ("MODI DANDA", "Po", 0),
  ("MODI DOUBLE DANDA", "Po", 0),
  ("MODI ABBREVIATION SIGN", "Po", 0),
  ("MODI SIGN HUVA", "Lo", 0),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("MODI DIGIT ZERO", "Nd", 0),
  ("MODI DIGIT ONE", "Nd", 0),
  ("MODI DIGIT TWO", "Nd", 0),
  ("MODI DIGIT THREE", "Nd", 0),
  ("MODI DIGIT FOUR", "Nd", 0),
  ("MODI DIGIT FIVE", "Nd", 0),
  ("MODI DIGIT SIX", "Nd", 0),
  ("MODI DIGIT SEVEN", "Nd", 0),
  ("MODI DIGIT EIGHT", "Nd", 0),
  ("MODI DIGIT NINE", "Nd", 0),
)
