#let data = (
  ("DEVANAGARI HEAD MARK", "Po", 0),
  ("DEVANAGARI HEAD MARK WITH HEADSTROKE", "Po", 0),
  ("DEVANAGARI SIGN BHALE", "Po", 0),
  ("DEVANAGARI SIGN BHALE WITH HOOK", "Po", 0),
  ("DEVANAGARI SIGN EXTENDED BHALE", "Po", 0),
  ("DEVANAGARI SIGN EXTENDED BHALE WITH HOOK", "Po", 0),
  ("DEVANAGARI SIGN WESTERN FIVE-LIKE BHALE", "Po", 0),
  ("DEVANAGARI SIGN WESTERN NINE-LIKE BHALE", "Po", 0),
  ("DEVANAGARI SIGN REVERSED NINE-LIKE BHALE", "Po", 0),
  ("DEVANAGARI SIGN MINDU", "Po", 0),
)
