#let data = (
  ("OL ONAL LETTER O", "Lo", 0),
  ("OL ONAL LETTER OM", "Lo", 0),
  ("OL ONAL LETTER ONG", "Lo", 0),
  ("OL ONAL LETTER ORR", "Lo", 0),
  ("OL ONAL LETTER OO", "Lo", 0),
  ("OL ONAL LETTER OY", "Lo", 0),
  ("OL ONAL LETTER A", "Lo", 0),
  ("OL ONAL LETTER AD", "Lo", 0),
  ("OL ONAL LETTER AB", "Lo", 0),
  ("OL ONAL LETTER AH", "Lo", 0),
  ("OL ONAL LETTER AL", "Lo", 0),
  ("OL ONAL LETTER AW", "Lo", 0),
  ("OL ONAL LETTER I", "Lo", 0),
  ("OL ONAL LETTER IT", "Lo", 0),
  ("OL ONAL LETTER IP", "Lo", 0),
  ("OL ONAL LETTER ITT", "Lo", 0),
  ("OL ONAL LETTER ID", "Lo", 0),
  ("OL ONAL LETTER IN", "Lo", 0),
  ("OL ONAL LETTER U", "Lo", 0),
  ("OL ONAL LETTER UK", "Lo", 0),
  ("OL ONAL LETTER UDD", "Lo", 0),
  ("OL ONAL LETTER UJ", "Lo", 0),
  ("OL ONAL LETTER UNY", "Lo", 0),
  ("OL ONAL LETTER UR", "Lo", 0),
  ("OL ONAL LETTER E", "Lo", 0),
  ("OL ONAL LETTER ES", "Lo", 0),
  ("OL ONAL LETTER EH", "Lo", 0),
  ("OL ONAL LETTER EC", "Lo", 0),
  ("OL ONAL LETTER ENN", "Lo", 0),
  ("OL ONAL LETTER EG", "Lo", 0),
  ("OL ONAL SIGN MU", "Mn", 230),
  ("OL ONAL SIGN IKIR", "Mn", 220),
  ("OL ONAL SIGN HODDOND", "Lo", 0),
  ("OL ONAL DIGIT ZERO", "Nd", 0),
  ("OL ONAL DIGIT ONE", "Nd", 0),
  ("OL ONAL DIGIT TWO", "Nd", 0),
  ("OL ONAL DIGIT THREE", "Nd", 0),
  ("OL ONAL DIGIT FOUR", "Nd", 0),
  ("OL ONAL DIGIT FIVE", "Nd", 0),
  ("OL ONAL DIGIT SIX", "Nd", 0),
  ("OL ONAL DIGIT SEVEN", "Nd", 0),
  ("OL ONAL DIGIT EIGHT", "Nd", 0),
  ("OL ONAL DIGIT NINE", "Nd", 0),
  (),
  (),
  (),
  (),
  ("OL ONAL ABBREVIATION SIGN", "Po", 0),
)
