#let data = (
  ("OLD ITALIC LETTER A", "Lo", 0),
  ("OLD ITALIC LETTER BE", "Lo", 0),
  ("OLD ITALIC LETTER KE", "Lo", 0),
  ("OLD ITALIC LETTER DE", "Lo", 0),
  ("OLD ITALIC LETTER E", "Lo", 0),
  ("OLD ITALIC LETTER VE", "Lo", 0),
  ("OLD ITALIC LETTER ZE", "Lo", 0),
  ("OLD ITALIC LETTER HE", "Lo", 0),
  ("OLD ITALIC LETTER THE", "Lo", 0),
  ("OLD ITALIC LETTER I", "Lo", 0),
  ("OLD ITALIC LETTER KA", "Lo", 0),
  ("OLD ITALIC LETTER EL", "Lo", 0),
  ("OLD ITALIC LETTER EM", "Lo", 0),
  ("OLD ITALIC LETTER EN", "Lo", 0),
  ("OLD ITALIC LETTER ESH", "Lo", 0),
  ("OLD ITALIC LETTER O", "Lo", 0),
  ("OLD ITALIC LETTER PE", "Lo", 0),
  ("OLD ITALIC LETTER SHE", "Lo", 0),
  ("OLD ITALIC LETTER KU", "Lo", 0),
  ("OLD ITALIC LETTER ER", "Lo", 0),
  ("OLD ITALIC LETTER ES", "Lo", 0),
  ("OLD ITALIC LETTER TE", "Lo", 0),
  ("OLD ITALIC LETTER U", "Lo", 0),
  ("OLD ITALIC LETTER EKS", "Lo", 0),
  ("OLD ITALIC LETTER PHE", "Lo", 0),
  ("OLD ITALIC LETTER KHE", "Lo", 0),
  ("OLD ITALIC LETTER EF", "Lo", 0),
  ("OLD ITALIC LETTER ERS", "Lo", 0),
  ("OLD ITALIC LETTER CHE", "Lo", 0),
  ("OLD ITALIC LETTER II", "Lo", 0),
  ("OLD ITALIC LETTER UU", "Lo", 0),
  ("OLD ITALIC LETTER ESS", "Lo", 0),
  ("OLD ITALIC NUMERAL ONE", "No", 0),
  ("OLD ITALIC NUMERAL FIVE", "No", 0),
  ("OLD ITALIC NUMERAL TEN", "No", 0),
  ("OLD ITALIC NUMERAL FIFTY", "No", 0),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("OLD ITALIC LETTER YE", "Lo", 0),
  ("OLD ITALIC LETTER NORTHERN TSE", "Lo", 0),
  ("OLD ITALIC LETTER SOUTHERN TSE", "Lo", 0),
)
