#let data = (
  ("MAKASAR LETTER KA", "Lo", 0),
  ("MAKASAR LETTER GA", "Lo", 0),
  ("MAKASAR LETTER NGA", "Lo", 0),
  ("MAKASAR LETTER PA", "Lo", 0),
  ("MAKASAR LETTER BA", "Lo", 0),
  ("MAKASAR LETTER MA", "Lo", 0),
  ("MAKASAR LETTER TA", "Lo", 0),
  ("MAKASAR LETTER DA", "Lo", 0),
  ("MAKASAR LETTER NA", "Lo", 0),
  ("MAKASAR LETTER CA", "Lo", 0),
  ("MAKASAR LETTER JA", "Lo", 0),
  ("MAKASAR LETTER NYA", "Lo", 0),
  ("MAKASAR LETTER YA", "Lo", 0),
  ("MAKASAR LETTER RA", "Lo", 0),
  ("MAKASAR LETTER LA", "Lo", 0),
  ("MAKASAR LETTER VA", "Lo", 0),
  ("MAKASAR LETTER SA", "Lo", 0),
  ("MAKASAR LETTER A", "Lo", 0),
  ("MAKASAR ANGKA", "Lo", 0),
  ("MAKASAR VOWEL SIGN I", "Mn", 0),
  ("MAKASAR VOWEL SIGN U", "Mn", 0),
  ("MAKASAR VOWEL SIGN E", "Mc", 0),
  ("MAKASAR VOWEL SIGN O", "Mc", 0),
  ("MAKASAR PASSIMBANG", "Po", 0),
  ("MAKASAR END OF SECTION", "Po", 0),
)
