#let data = (
  ("BALLET SHOES", "So", 0),
  ("ONE-PIECE SWIMSUIT", "So", 0),
  ("BRIEFS", "So", 0),
  ("SHORTS", "So", 0),
  ("THONG SANDAL", "So", 0),
  ("LIGHT BLUE HEART", "So", 0),
  ("GREY HEART", "So", 0),
  ("PINK HEART", "So", 0),
  ("DROP OF BLOOD", "So", 0),
  ("ADHESIVE BANDAGE", "So", 0),
  ("STETHOSCOPE", "So", 0),
  ("X-RAY", "So", 0),
  ("CRUTCH", "So", 0),
  (),
  (),
  (),
  ("YO-YO", "So", 0),
  ("KITE", "So", 0),
  ("PARACHUTE", "So", 0),
  ("BOOMERANG", "So", 0),
  ("MAGIC WAND", "So", 0),
  ("PINATA", "So", 0),
  ("NESTING DOLLS", "So", 0),
  ("MARACAS", "So", 0),
  ("FLUTE", "So", 0),
  ("HARP", "So", 0),
  (),
  (),
  (),
  (),
  (),
  ("SHOVEL", "So", 0),
  ("RINGED PLANET", "So", 0),
  ("CHAIR", "So", 0),
  ("RAZOR", "So", 0),
  ("AXE", "So", 0),
  ("DIYA LAMP", "So", 0),
  ("BANJO", "So", 0),
  ("MILITARY HELMET", "So", 0),
  ("ACCORDION", "So", 0),
  ("LONG DRUM", "So", 0),
  ("COIN", "So", 0),
  ("CARPENTRY SAW", "So", 0),
  ("SCREWDRIVER", "So", 0),
  ("LADDER", "So", 0),
  ("HOOK", "So", 0),
  ("MIRROR", "So", 0),
  ("WINDOW", "So", 0),
  ("PLUNGER", "So", 0),
  ("SEWING NEEDLE", "So", 0),
  ("KNOT", "So", 0),
  ("BUCKET", "So", 0),
  ("MOUSE TRAP", "So", 0),
  ("TOOTHBRUSH", "So", 0),
  ("HEADSTONE", "So", 0),
  ("PLACARD", "So", 0),
  ("ROCK", "So", 0),
  ("MIRROR BALL", "So", 0),
  ("IDENTIFICATION CARD", "So", 0),
  ("LOW BATTERY", "So", 0),
  ("HAMSA", "So", 0),
  ("FOLDING HAND FAN", "So", 0),
  ("HAIR PICK", "So", 0),
  ("KHANDA", "So", 0),
  ("FLY", "So", 0),
  ("WORM", "So", 0),
  ("BEETLE", "So", 0),
  ("COCKROACH", "So", 0),
  ("POTTED PLANT", "So", 0),
  ("WOOD", "So", 0),
  ("FEATHER", "So", 0),
  ("LOTUS", "So", 0),
  ("CORAL", "So", 0),
  ("EMPTY NEST", "So", 0),
  ("NEST WITH EGGS", "So", 0),
  ("HYACINTH", "So", 0),
  ("JELLYFISH", "So", 0),
  ("WING", "So", 0),
  ("LEAFLESS TREE", "So", 0),
  ("GOOSE", "So", 0),
  ("ANATOMICAL HEART", "So", 0),
  ("LUNGS", "So", 0),
  ("PEOPLE HUGGING", "So", 0),
  ("PREGNANT MAN", "So", 0),
  ("PREGNANT PERSON", "So", 0),
  ("PERSON WITH CROWN", "So", 0),
  ("FINGERPRINT", "So", 0),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("MOOSE", "So", 0),
  ("DONKEY", "So", 0),
  ("BLUEBERRIES", "So", 0),
  ("BELL PEPPER", "So", 0),
  ("OLIVE", "So", 0),
  ("FLATBREAD", "So", 0),
  ("TAMALE", "So", 0),
  ("FONDUE", "So", 0),
  ("TEAPOT", "So", 0),
  ("POURING LIQUID", "So", 0),
  ("BEANS", "So", 0),
  ("JAR", "So", 0),
  ("GINGER ROOT", "So", 0),
  ("PEA POD", "So", 0),
  ("ROOT VEGETABLE", "So", 0),
  (),
  (),
  ("SPLATTER", "So", 0),
  ("MELTING FACE", "So", 0),
  ("SALUTING FACE", "So", 0),
  ("FACE WITH OPEN EYES AND HAND OVER MOUTH", "So", 0),
  ("FACE WITH PEEKING EYE", "So", 0),
  ("FACE WITH DIAGONAL MOUTH", "So", 0),
  ("DOTTED LINE FACE", "So", 0),
  ("BITING LIP", "So", 0),
  ("BUBBLES", "So", 0),
  ("SHAKING FACE", "So", 0),
  ("FACE WITH BAGS UNDER EYES", "So", 0),
  (),
  (),
  (),
  (),
  (),
  (),
  ("HAND WITH INDEX FINGER AND THUMB CROSSED", "So", 0),
  ("RIGHTWARDS HAND", "So", 0),
  ("LEFTWARDS HAND", "So", 0),
  ("PALM DOWN HAND", "So", 0),
  ("PALM UP HAND", "So", 0),
  ("INDEX POINTING AT THE VIEWER", "So", 0),
  ("HEART HANDS", "So", 0),
  ("LEFTWARDS PUSHING HAND", "So", 0),
  ("RIGHTWARDS PUSHING HAND", "So", 0),
)
