#let data = (
  ("LISU LETTER BA", "Lo", 0),
  ("LISU LETTER PA", "Lo", 0),
  ("LISU LETTER PHA", "Lo", 0),
  ("LISU LETTER DA", "Lo", 0),
  ("LISU LETTER TA", "Lo", 0),
  ("LISU LETTER THA", "Lo", 0),
  ("LISU LETTER GA", "Lo", 0),
  ("LISU LETTER KA", "Lo", 0),
  ("LISU LETTER KHA", "Lo", 0),
  ("LISU LETTER JA", "Lo", 0),
  ("LISU LETTER CA", "Lo", 0),
  ("LISU LETTER CHA", "Lo", 0),
  ("LISU LETTER DZA", "Lo", 0),
  ("LISU LETTER TSA", "Lo", 0),
  ("LISU LETTER TSHA", "Lo", 0),
  ("LISU LETTER MA", "Lo", 0),
  ("LISU LETTER NA", "Lo", 0),
  ("LISU LETTER LA", "Lo", 0),
  ("LISU LETTER SA", "Lo", 0),
  ("LISU LETTER ZHA", "Lo", 0),
  ("LISU LETTER ZA", "Lo", 0),
  ("LISU LETTER NGA", "Lo", 0),
  ("LISU LETTER HA", "Lo", 0),
  ("LISU LETTER XA", "Lo", 0),
  ("LISU LETTER HHA", "Lo", 0),
  ("LISU LETTER FA", "Lo", 0),
  ("LISU LETTER WA", "Lo", 0),
  ("LISU LETTER SHA", "Lo", 0),
  ("LISU LETTER YA", "Lo", 0),
  ("LISU LETTER GHA", "Lo", 0),
  ("LISU LETTER A", "Lo", 0),
  ("LISU LETTER AE", "Lo", 0),
  ("LISU LETTER E", "Lo", 0),
  ("LISU LETTER EU", "Lo", 0),
  ("LISU LETTER I", "Lo", 0),
  ("LISU LETTER O", "Lo", 0),
  ("LISU LETTER U", "Lo", 0),
  ("LISU LETTER UE", "Lo", 0),
  ("LISU LETTER UH", "Lo", 0),
  ("LISU LETTER OE", "Lo", 0),
  ("LISU LETTER TONE MYA TI", "Lm", 0),
  ("LISU LETTER TONE NA PO", "Lm", 0),
  ("LISU LETTER TONE MYA CYA", "Lm", 0),
  ("LISU LETTER TONE MYA BO", "Lm", 0),
  ("LISU LETTER TONE MYA NA", "Lm", 0),
  ("LISU LETTER TONE MYA JEU", "Lm", 0),
  ("LISU PUNCTUATION COMMA", "Po", 0),
  ("LISU PUNCTUATION FULL STOP", "Po", 0),
)
