#let data = (
  ("AHOM LETTER KA", "Lo", 0),
  ("AHOM LETTER KHA", "Lo", 0),
  ("AHOM LETTER NGA", "Lo", 0),
  ("AHOM LETTER NA", "Lo", 0),
  ("AHOM LETTER TA", "Lo", 0),
  ("AHOM LETTER ALTERNATE TA", "Lo", 0),
  ("AHOM LETTER PA", "Lo", 0),
  ("AHOM LETTER PHA", "Lo", 0),
  ("AHOM LETTER BA", "Lo", 0),
  ("AHOM LETTER MA", "Lo", 0),
  ("AHOM LETTER JA", "Lo", 0),
  ("AHOM LETTER CHA", "Lo", 0),
  ("AHOM LETTER THA", "Lo", 0),
  ("AHOM LETTER RA", "Lo", 0),
  ("AHOM LETTER LA", "Lo", 0),
  ("AHOM LETTER SA", "Lo", 0),
  ("AHOM LETTER NYA", "Lo", 0),
  ("AHOM LETTER HA", "Lo", 0),
  ("AHOM LETTER A", "Lo", 0),
  ("AHOM LETTER DA", "Lo", 0),
  ("AHOM LETTER DHA", "Lo", 0),
  ("AHOM LETTER GA", "Lo", 0),
  ("AHOM LETTER ALTERNATE GA", "Lo", 0),
  ("AHOM LETTER GHA", "Lo", 0),
  ("AHOM LETTER BHA", "Lo", 0),
  ("AHOM LETTER JHA", "Lo", 0),
  ("AHOM LETTER ALTERNATE BA", "Lo", 0),
  (),
  (),
  ("AHOM CONSONANT SIGN MEDIAL LA", "Mn", 0),
  ("AHOM CONSONANT SIGN MEDIAL RA", "Mc", 0),
  ("AHOM CONSONANT SIGN MEDIAL LIGATING RA", "Mn", 0),
  ("AHOM VOWEL SIGN A", "Mc", 0),
  ("AHOM VOWEL SIGN AA", "Mc", 0),
  ("AHOM VOWEL SIGN I", "Mn", 0),
  ("AHOM VOWEL SIGN II", "Mn", 0),
  ("AHOM VOWEL SIGN U", "Mn", 0),
  ("AHOM VOWEL SIGN UU", "Mn", 0),
  ("AHOM VOWEL SIGN E", "Mc", 0),
  ("AHOM VOWEL SIGN AW", "Mn", 0),
  ("AHOM VOWEL SIGN O", "Mn", 0),
  ("AHOM VOWEL SIGN AI", "Mn", 0),
  ("AHOM VOWEL SIGN AM", "Mn", 0),
  ("AHOM SIGN KILLER", "Mn", 9),
  (),
  (),
  (),
  (),
  ("AHOM DIGIT ZERO", "Nd", 0),
  ("AHOM DIGIT ONE", "Nd", 0),
  ("AHOM DIGIT TWO", "Nd", 0),
  ("AHOM DIGIT THREE", "Nd", 0),
  ("AHOM DIGIT FOUR", "Nd", 0),
  ("AHOM DIGIT FIVE", "Nd", 0),
  ("AHOM DIGIT SIX", "Nd", 0),
  ("AHOM DIGIT SEVEN", "Nd", 0),
  ("AHOM DIGIT EIGHT", "Nd", 0),
  ("AHOM DIGIT NINE", "Nd", 0),
  ("AHOM NUMBER TEN", "No", 0),
  ("AHOM NUMBER TWENTY", "No", 0),
  ("AHOM SIGN SMALL SECTION", "Po", 0),
  ("AHOM SIGN SECTION", "Po", 0),
  ("AHOM SIGN RULAI", "Po", 0),
  ("AHOM SYMBOL VI", "So", 0),
  ("AHOM LETTER CA", "Lo", 0),
  ("AHOM LETTER TTA", "Lo", 0),
  ("AHOM LETTER TTHA", "Lo", 0),
  ("AHOM LETTER DDA", "Lo", 0),
  ("AHOM LETTER DDHA", "Lo", 0),
  ("AHOM LETTER NNA", "Lo", 0),
  ("AHOM LETTER LLA", "Lo", 0),
)
