#let data = (
  ("EURO-CURRENCY SIGN", "Sc", 0),
  ("COLON SIGN", "Sc", 0),
  ("CRUZEIRO SIGN", "Sc", 0),
  ("FRENCH FRANC SIGN", "Sc", 0),
  ("LIRA SIGN", "Sc", 0),
  ("MILL SIGN", "Sc", 0),
  ("NAIRA SIGN", "Sc", 0),
  ("PESETA SIGN", "Sc", 0),
  ("RUPEE SIGN", "Sc", 0),
  ("WON SIGN", "Sc", 0),
  ("NEW SHEQEL SIGN", "Sc", 0),
  ("DONG SIGN", "Sc", 0),
  ("EURO SIGN", "Sc", 0),
  ("KIP SIGN", "Sc", 0),
  ("TUGRIK SIGN", "Sc", 0),
  ("DRACHMA SIGN", "Sc", 0),
  ("GERMAN PENNY SIGN", "Sc", 0),
  ("PESO SIGN", "Sc", 0),
  ("GUARANI SIGN", "Sc", 0),
  ("AUSTRAL SIGN", "Sc", 0),
  ("HRYVNIA SIGN", "Sc", 0),
  ("CEDI SIGN", "Sc", 0),
  ("LIVRE TOURNOIS SIGN", "Sc", 0),
  ("SPESMILO SIGN", "Sc", 0),
  ("TENGE SIGN", "Sc", 0),
  ("INDIAN RUPEE SIGN", "Sc", 0),
  ("TURKISH LIRA SIGN", "Sc", 0),
  ("NORDIC MARK SIGN", "Sc", 0),
  ("MANAT SIGN", "Sc", 0),
  ("RUBLE SIGN", "Sc", 0),
  ("LARI SIGN", "Sc", 0),
  ("BITCOIN SIGN", "Sc", 0),
  ("SOM SIGN", "Sc", 0),
)
