#let data = (
  (),
  (),
  (),
  (),
  (),
  ("BOPOMOFO LETTER B", "Lo", 0),
  ("BOPOMOFO LETTER P", "Lo", 0),
  ("BOPOMOFO LETTER M", "Lo", 0),
  ("BOPOMOFO LETTER F", "Lo", 0),
  ("BOPOMOFO LETTER D", "Lo", 0),
  ("BOPOMOFO LETTER T", "Lo", 0),
  ("BOPOMOFO LETTER N", "Lo", 0),
  ("BOPOMOFO LETTER L", "Lo", 0),
  ("BOPOMOFO LETTER G", "Lo", 0),
  ("BOPOMOFO LETTER K", "Lo", 0),
  ("BOPOMOFO LETTER H", "Lo", 0),
  ("BOPOMOFO LETTER J", "Lo", 0),
  ("BOPOMOFO LETTER Q", "Lo", 0),
  ("BOPOMOFO LETTER X", "Lo", 0),
  ("BOPOMOFO LETTER ZH", "Lo", 0),
  ("BOPOMOFO LETTER CH", "Lo", 0),
  ("BOPOMOFO LETTER SH", "Lo", 0),
  ("BOPOMOFO LETTER R", "Lo", 0),
  ("BOPOMOFO LETTER Z", "Lo", 0),
  ("BOPOMOFO LETTER C", "Lo", 0),
  ("BOPOMOFO LETTER S", "Lo", 0),
  ("BOPOMOFO LETTER A", "Lo", 0),
  ("BOPOMOFO LETTER O", "Lo", 0),
  ("BOPOMOFO LETTER E", "Lo", 0),
  ("BOPOMOFO LETTER EH", "Lo", 0),
  ("BOPOMOFO LETTER AI", "Lo", 0),
  ("BOPOMOFO LETTER EI", "Lo", 0),
  ("BOPOMOFO LETTER AU", "Lo", 0),
  ("BOPOMOFO LETTER OU", "Lo", 0),
  ("BOPOMOFO LETTER AN", "Lo", 0),
  ("BOPOMOFO LETTER EN", "Lo", 0),
  ("BOPOMOFO LETTER ANG", "Lo", 0),
  ("BOPOMOFO LETTER ENG", "Lo", 0),
  ("BOPOMOFO LETTER ER", "Lo", 0),
  ("BOPOMOFO LETTER I", "Lo", 0),
  ("BOPOMOFO LETTER U", "Lo", 0),
  ("BOPOMOFO LETTER IU", "Lo", 0),
  ("BOPOMOFO LETTER V", "Lo", 0),
  ("BOPOMOFO LETTER NG", "Lo", 0),
  ("BOPOMOFO LETTER GN", "Lo", 0),
  ("BOPOMOFO LETTER IH", "Lo", 0),
  ("BOPOMOFO LETTER O WITH DOT ABOVE", "Lo", 0),
  ("BOPOMOFO LETTER NN", "Lo", 0),
)
