/// This file is auto-generated from the HTML tags metadata.
/// Do not edit this file directly.
/// HTML element bindings
/// html, link, table, label, style, strong, time, figure, sub, sup are excluded because they are conflicting with `std`.

#import "html-bindings-h.typ" as h
#import h: head, title, base, meta, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, header, footer, address, p, hr, pre, blockquote, ol, ul, li, dl, dt, dd, figcaption, main, div, a, em, small, s, cite, q, dfn, abbr, ruby, rb, rt, rp, code, var, samp, kbd, i, b, u, mark, bdi, bdo, span, br, wbr, ins, del, picture, img, iframe, embed, object, param, video, audio, source, track, map, area, caption, colgroup, col, tbody, thead, tfoot, tr, td, th, form, input, button, select, datalist, optgroup, option, textarea, output, progress, meter, fieldset, legend, details, summary, dialog, script, noscript, template, canvas, slot, data, hgroup, menu, search, fencedframe, selectedcontent
