// Canonical list of aesthetic-channel names, single-sourced here so the
// `aes()` constructor, the geom constant-param sink, and `annotate` stay in
// step. Kept dependency-free: `layer.typ` (imported by every geom) imports
// this, so any dependency would risk an import cycle.

#let AES-KEYS = (
  "x",
  "y",
  "z",
  "colour",
  "fill",
  "size",
  "alpha",
  "linewidth",
  "group",
  "shape",
  "linetype",
  "label",
  "xmin",
  "xmax",
  "ymin",
  "ymax",
  "xend",
  "yend",
  "xintercept",
  "yintercept",
  "slope",
  "intercept",
  "weight",
  "stroke",
  "x0",
  "y0",
  "a",
  "b",
  "angle",
  "radius",
  "height",
  "nudge-x",
  "nudge-y",
)
