[package]
name = "tieflied"
version = "0.2.2"
compiler = "0.13.1"
authors = ["Lena Tauchner"]
entrypoint = "lib.typ"
license = "MIT"
description = "Song book template (Liederbuch)"
keywords = ["music", "songs"]
categories = ["layout", "fun"]
disciplines = []
repository = "https://github.com/Tiefseetauchner/TiefLied"
homepage = "https://www.lukechriswalker.at/projects/6a26a3c4b6efd6b40d60bfc6"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
