#import "@preview/aimesymb:0.1.0": *

#set document(title: "aimesymb catalog")
#set page(paper: "a4", margin: 12mm)
#set text(size: 8.5pt)
#set heading(numbering: "1.")

#let card(item) = box(
  width: 100%,
  inset: (x: 5pt, y: 3pt),
  radius: 2pt,
  fill: luma(96%),
  grid(
    columns: (1fr, auto),
    column-gutter: 6pt,
    align(left + horizon, raw(item.at(0))),
    align(right + horizon, $#(item.at(1))$),
  ),
)

#let catalog(title, items) = {
  heading(level: 2, title)
  grid(
    columns: (1fr, 1fr, 1fr),
    column-gutter: 5pt,
    row-gutter: 4pt,
    ..items.map(card),
  )
}

= aimesymb catalog

The names match LaTeX's `amssymb` and `amsfonts` interfaces without the leading
backslash. Every card is a real equation, so this document also exercises
font routing and math-class layout.

#catalog("AMSa operators, arrows, relations, and shapes", (
  ("boxdot", boxdot),
  ("boxplus", boxplus),
  ("boxtimes", boxtimes),
  ("square", square),
  ("blacksquare", blacksquare),
  ("centerdot", centerdot),
  ("lozenge", lozenge),
  ("blacklozenge", blacklozenge),
  ("circlearrowright", circlearrowright),
  ("circlearrowleft", circlearrowleft),
  ("rightleftharpoons", rightleftharpoons),
  ("leftrightharpoons", leftrightharpoons),
  ("boxminus", boxminus),
  ("Vdash", Vdash),
  ("Vvdash", Vvdash),
  ("vDash", vDash),
  ("twoheadrightarrow", twoheadrightarrow),
  ("twoheadleftarrow", twoheadleftarrow),
  ("leftleftarrows", leftleftarrows),
  ("rightrightarrows", rightrightarrows),
  ("upuparrows", upuparrows),
  ("downdownarrows", downdownarrows),
  ("upharpoonright", upharpoonright),
  ("downharpoonright", downharpoonright),
  ("upharpoonleft", upharpoonleft),
  ("downharpoonleft", downharpoonleft),
  ("rightarrowtail", rightarrowtail),
  ("leftarrowtail", leftarrowtail),
  ("leftrightarrows", leftrightarrows),
  ("rightleftarrows", rightleftarrows),
  ("Lsh", Lsh),
  ("Rsh", Rsh),
  ("rightsquigarrow", rightsquigarrow),
  ("leftrightsquigarrow", leftrightsquigarrow),
  ("looparrowleft", looparrowleft),
  ("looparrowright", looparrowright),
  ("circeq", circeq),
  ("succsim", succsim),
  ("gtrsim", gtrsim),
  ("gtrapprox", gtrapprox),
  ("multimap", multimap),
  ("therefore", therefore),
  ("because", because),
  ("doteqdot", doteqdot),
  ("triangleq", triangleq),
  ("precsim", precsim),
  ("lesssim", lesssim),
  ("lessapprox", lessapprox),
  ("eqslantless", eqslantless),
  ("eqslantgtr", eqslantgtr),
  ("curlyeqprec", curlyeqprec),
  ("curlyeqsucc", curlyeqsucc),
  ("preccurlyeq", preccurlyeq),
  ("leqq", leqq),
  ("leqslant", leqslant),
  ("lessgtr", lessgtr),
  ("backprime", backprime),
  ("risingdotseq", risingdotseq),
  ("fallingdotseq", fallingdotseq),
  ("succcurlyeq", succcurlyeq),
  ("geqq", geqq),
  ("geqslant", geqslant),
  ("gtrless", gtrless),
  ("sqsubset", sqsubset),
  ("sqsupset", sqsupset),
  ("vartriangleright", vartriangleright),
  ("vartriangleleft", vartriangleleft),
  ("trianglerighteq", trianglerighteq),
  ("trianglelefteq", trianglelefteq),
  ("bigstar", bigstar),
  ("between", between),
  ("blacktriangledown", blacktriangledown),
  ("blacktriangleright", blacktriangleright),
  ("blacktriangleleft", blacktriangleleft),
  ("vartriangle", vartriangle),
  ("blacktriangle", blacktriangle),
  ("triangledown", triangledown),
  ("eqcirc", eqcirc),
  ("lesseqgtr", lesseqgtr),
  ("gtreqless", gtreqless),
  ("lesseqqgtr", lesseqqgtr),
  ("gtreqqless", gtreqqless),
  ("Rrightarrow", Rrightarrow),
  ("Lleftarrow", Lleftarrow),
  ("veebar", veebar),
  ("barwedge", barwedge),
  ("doublebarwedge", doublebarwedge),
  ("angle", angle),
  ("measuredangle", measuredangle),
  ("sphericalangle", sphericalangle),
  ("varpropto", varpropto),
  ("smallsmile", smallsmile),
  ("smallfrown", smallfrown),
  ("Subset", Subset),
  ("Supset", Supset),
  ("Cup", Cup),
  ("Cap", Cap),
  ("curlywedge", curlywedge),
  ("curlyvee", curlyvee),
  ("leftthreetimes", leftthreetimes),
  ("rightthreetimes", rightthreetimes),
  ("subseteqq", subseteqq),
  ("supseteqq", supseteqq),
  ("bumpeq", bumpeq),
  ("Bumpeq", Bumpeq),
  ("lll", lll),
  ("ggg", ggg),
  ("circledS", circledS),
  ("pitchfork", pitchfork),
  ("dotplus", dotplus),
  ("backsim", backsim),
  ("backsimeq", backsimeq),
  ("complement", complement),
  ("intercal", intercal),
  ("circledcirc", circledcirc),
  ("circledast", circledast),
  ("circleddash", circleddash),
))

#catalog("AMSb negated relations and variants", (
  ("lvertneqq", lvertneqq),
  ("gvertneqq", gvertneqq),
  ("nleq", nleq),
  ("ngeq", ngeq),
  ("nless", nless),
  ("ngtr", ngtr),
  ("nprec", nprec),
  ("nsucc", nsucc),
  ("lneqq", lneqq),
  ("gneqq", gneqq),
  ("nleqslant", nleqslant),
  ("ngeqslant", ngeqslant),
  ("lneq", lneq),
  ("gneq", gneq),
  ("npreceq", npreceq),
  ("nsucceq", nsucceq),
  ("precnsim", precnsim),
  ("succnsim", succnsim),
  ("lnsim", lnsim),
  ("gnsim", gnsim),
  ("nleqq", nleqq),
  ("ngeqq", ngeqq),
  ("precneqq", precneqq),
  ("succneqq", succneqq),
  ("precnapprox", precnapprox),
  ("succnapprox", succnapprox),
  ("lnapprox", lnapprox),
  ("gnapprox", gnapprox),
  ("nsim", nsim),
  ("ncong", ncong),
  ("diagup", diagup),
  ("diagdown", diagdown),
  ("varsubsetneq", varsubsetneq),
  ("varsupsetneq", varsupsetneq),
  ("nsubseteqq", nsubseteqq),
  ("nsupseteqq", nsupseteqq),
  ("subsetneqq", subsetneqq),
  ("supsetneqq", supsetneqq),
  ("varsubsetneqq", varsubsetneqq),
  ("varsupsetneqq", varsupsetneqq),
  ("subsetneq", subsetneq),
  ("supsetneq", supsetneq),
  ("nsubseteq", nsubseteq),
  ("nsupseteq", nsupseteq),
  ("nparallel", nparallel),
  ("nmid", nmid),
  ("nshortmid", nshortmid),
  ("nshortparallel", nshortparallel),
  ("nvdash", nvdash),
  ("nVdash", nVdash),
  ("nvDash", nvDash),
  ("nVDash", nVDash),
  ("ntrianglerighteq", ntrianglerighteq),
  ("ntrianglelefteq", ntrianglelefteq),
  ("ntriangleleft", ntriangleleft),
  ("ntriangleright", ntriangleright),
  ("nleftarrow", nleftarrow),
  ("nrightarrow", nrightarrow),
  ("nLeftarrow", nLeftarrow),
  ("nRightarrow", nRightarrow),
  ("nLeftrightarrow", nLeftrightarrow),
  ("nleftrightarrow", nleftrightarrow),
))

#catalog("AMSb miscellaneous symbols", (
  ("divideontimes", divideontimes),
  ("varnothing", varnothing),
  ("nexists", nexists),
  ("Finv", Finv),
  ("Game", Game),
  ("mho", mho),
  ("eth", eth),
  ("eqsim", eqsim),
  ("beth", beth),
  ("gimel", gimel),
  ("daleth", daleth),
  ("lessdot", lessdot),
  ("gtrdot", gtrdot),
  ("ltimes", ltimes),
  ("rtimes", rtimes),
  ("shortmid", shortmid),
  ("shortparallel", shortparallel),
  ("smallsetminus", smallsetminus),
  ("thicksim", thicksim),
  ("thickapprox", thickapprox),
  ("approxeq", approxeq),
  ("succapprox", succapprox),
  ("precapprox", precapprox),
  ("curvearrowleft", curvearrowleft),
  ("curvearrowright", curvearrowright),
  ("digamma", digamma),
  ("varkappa", varkappa),
  ("Bbbk", Bbbk),
  ("hslash", hslash),
  ("hbar", hbar),
  ("backepsilon", backepsilon),
))

#catalog("amsfonts extras", (
  ("yen", yen),
  ("checkmark", checkmark),
  ("circledR", circledR),
  ("maltese", maltese),
  ("ulcorner", ulcorner),
  ("urcorner", urcorner),
  ("llcorner", llcorner),
  ("lrcorner", lrcorner),
  ("dashrightarrow", dashrightarrow),
  ("dashleftarrow", dashleftarrow),
  ("Join", Join),
  ("lhd", lhd),
  ("unlhd", unlhd),
  ("rhd", rhd),
  ("unrhd", unrhd),
))

#catalog("symbol aliases", (
  ("restriction", restriction),
  ("Doteq", Doteq),
  ("doublecup", doublecup),
  ("doublecap", doublecap),
  ("llless", llless),
  ("gggtr", gggtr),
  ("Box", Box),
  ("Diamond", Diamond),
  ("leadsto", leadsto),
  ("dasharrow", dasharrow),
))

== Alphabet and accent aliases

$ bb(A B C N R Z) quad Bbbk quad mathfrak(A B C g) quad frak(g) $

$ bold(alpha + beta) quad widehat(A B C) quad widetilde(x y z) $
