#import "@preview/pedigrypst:0.1.0" as pedigrypst: pedigree

#set page(height: auto, width: 6.25in)
#pedigree(length: 2cm, convergence-time: 250, empty-style: red.lighten(40%), {
  import pedigrypst: *
  individual(1, 1, "male")
  individual(1, 2, "female")
  individual(2, 1, "female")
  individual(2, 2, "male")
  individual(2, 3, "female")
  individual(2, 4, "male")
  individual(3, 1, "male")
  individual(3, 2, "female")
  individual(3, 3, "male")
  individual(3, 4, "male")
  individual(3, 5, "female")
  individual(3, 6, "female")
  individual(4, 1, "female")
  individual(4, 2, "female")
  individual(5, 1, "male")
  individual(6, 1, "male")
  individual(6, 2, "male")
  individual(6, 3, "male")
  individual(6, 4, "male", fill: "filled", propositus: true)

  union("i1-1", "i1-2")
  union("i2-1", "i2-2")
  union("i2-3", "i2-4")
  union("i3-1", "i4-1", consanguineous: true)
  union("i3-2", "i3-3")
  union("i3-4", "i3-5")
  union("i5-1", "i4-2", consanguineous: true)

  children("u1", "i2-2", "i2-4")
  children("u2", "i3-1")
  children("u3", "i3-3", "i3-4", "i3-6")
  children("u4", "i5-1")
  children("u5", "i4-1")
  children("u6", "i4-2")
  children("u7", "i6-1", "i6-2", "i6-3", "i6-4")
})