[package]
name = "theoframe"
version = "0.2.0"
entrypoint = "lib.typ"
exclude = ["assets/*", "*.pdf"]
authors = ["HeXiongwu"]
license = "MIT"
description = "A mini Theorem Environments that is very easy to use."
repository = "https://github.com/hexiongwu1995/typst-theoframe"
keywords = ["theorem", "lemma", "environment", "math"]
disciplines = ["computer-science", "engineering", "mathematics", "physics", "education"]
categories = ["components"]
compiler = "0.15.0"