[package]
name = "gairm-import"
version = "0.8.0"
entrypoint = "lib.typ"
authors = ["Shane Murphy"]
license = "MIT"
description = "Parses and validates JSON against JSON Schema and returns a normalised dict; built in support for JSON Resumes."
repository = "https://github.com/smur89/gairm-import"
keywords = ["json", "json-resume", "resume", "cv", "loader", "schema"]
categories = ["utility"]
compiler = "0.15.0"
