[package]
name = "answerly"
version = "0.1.0"
entrypoint = "lib.typ"
categories = [ "utility", "book" ]
disciplines = [ "education" ]
description = "Record and format answers to questions in worksheets or textbooks."
authors = ["Alasdair Casperd"]
license = "MIT"
repository = "https://github.com/alasdair-casperd/answerly"
keywords = [ "answer", "worksheet", "exercise", "textbook", "solutions" ]
exclude = ["assets/**", "examples/**"]