[package]
name = "manifesto"
version = "0.2.0"
compiler = "0.14.0"
description = "Create stunning documentation websites using native HTML export"
repository = "https://codeberg.org/grangelouis/manifesto"
categories = ["layout", "visualization"]
disciplines = ["design", "education"]
keywords = ["documentation", "docs", "html", "website", "site", "static", "online"]
exclude = [".forgejo"]
entrypoint = "src/lib.typ"
authors = ["Louis Grange <https://codeberg.org/grangelouis>"]
license = "MPL-2.0"

[template]
path = "template"
thumbnail = "thumbnail.png"
entrypoint = "docs.typ"
