#let data = (
  ("SHARADA SIGN CANDRABINDU", "Mn", 0, none),
  ("SHARADA SIGN ANUSVARA", "Mn", 0, none),
  ("SHARADA SIGN VISARGA", "Mc", 0, none),
  ("SHARADA LETTER A", "Lo", 0, none),
  ("SHARADA LETTER AA", "Lo", 0, none),
  ("SHARADA LETTER I", "Lo", 0, none),
  ("SHARADA LETTER II", "Lo", 0, none),
  ("SHARADA LETTER U", "Lo", 0, none),
  ("SHARADA LETTER UU", "Lo", 0, none),
  ("SHARADA LETTER VOCALIC R", "Lo", 0, none),
  ("SHARADA LETTER VOCALIC RR", "Lo", 0, none),
  ("SHARADA LETTER VOCALIC L", "Lo", 0, none),
  ("SHARADA LETTER VOCALIC LL", "Lo", 0, none),
  ("SHARADA LETTER E", "Lo", 0, none),
  ("SHARADA LETTER AI", "Lo", 0, none),
  ("SHARADA LETTER O", "Lo", 0, none),
  ("SHARADA LETTER AU", "Lo", 0, none),
  ("SHARADA LETTER KA", "Lo", 0, none),
  ("SHARADA LETTER KHA", "Lo", 0, none),
  ("SHARADA LETTER GA", "Lo", 0, none),
  ("SHARADA LETTER GHA", "Lo", 0, none),
  ("SHARADA LETTER NGA", "Lo", 0, none),
  ("SHARADA LETTER CA", "Lo", 0, none),
  ("SHARADA LETTER CHA", "Lo", 0, none),
  ("SHARADA LETTER JA", "Lo", 0, none),
  ("SHARADA LETTER JHA", "Lo", 0, none),
  ("SHARADA LETTER NYA", "Lo", 0, none),
  ("SHARADA LETTER TTA", "Lo", 0, none),
  ("SHARADA LETTER TTHA", "Lo", 0, none),
  ("SHARADA LETTER DDA", "Lo", 0, none),
  ("SHARADA LETTER DDHA", "Lo", 0, none),
  ("SHARADA LETTER NNA", "Lo", 0, none),
  ("SHARADA LETTER TA", "Lo", 0, none),
  ("SHARADA LETTER THA", "Lo", 0, none),
  ("SHARADA LETTER DA", "Lo", 0, none),
  ("SHARADA LETTER DHA", "Lo", 0, none),
  ("SHARADA LETTER NA", "Lo", 0, none),
  ("SHARADA LETTER PA", "Lo", 0, none),
  ("SHARADA LETTER PHA", "Lo", 0, none),
  ("SHARADA LETTER BA", "Lo", 0, none),
  ("SHARADA LETTER BHA", "Lo", 0, none),
  ("SHARADA LETTER MA", "Lo", 0, none),
  ("SHARADA LETTER YA", "Lo", 0, none),
  ("SHARADA LETTER RA", "Lo", 0, none),
  ("SHARADA LETTER LA", "Lo", 0, none),
  ("SHARADA LETTER LLA", "Lo", 0, none),
  ("SHARADA LETTER VA", "Lo", 0, none),
  ("SHARADA LETTER SHA", "Lo", 0, none),
  ("SHARADA LETTER SSA", "Lo", 0, none),
  ("SHARADA LETTER SA", "Lo", 0, none),
  ("SHARADA LETTER HA", "Lo", 0, none),
  ("SHARADA VOWEL SIGN AA", "Mc", 0, none),
  ("SHARADA VOWEL SIGN I", "Mc", 0, none),
  ("SHARADA VOWEL SIGN II", "Mc", 0, none),
  ("SHARADA VOWEL SIGN U", "Mn", 0, none),
  ("SHARADA VOWEL SIGN UU", "Mn", 0, none),
  ("SHARADA VOWEL SIGN VOCALIC R", "Mn", 0, none),
  ("SHARADA VOWEL SIGN VOCALIC RR", "Mn", 0, none),
  ("SHARADA VOWEL SIGN VOCALIC L", "Mn", 0, none),
  ("SHARADA VOWEL SIGN VOCALIC LL", "Mn", 0, none),
  ("SHARADA VOWEL SIGN E", "Mn", 0, none),
  ("SHARADA VOWEL SIGN AI", "Mn", 0, none),
  ("SHARADA VOWEL SIGN O", "Mn", 0, none),
  ("SHARADA VOWEL SIGN AU", "Mc", 0, none),
  ("SHARADA SIGN VIRAMA", "Mc", 9, none),
  ("SHARADA SIGN AVAGRAHA", "Lo", 0, none),
  ("SHARADA SIGN JIHVAMULIYA", "Lo", 0, none),
  ("SHARADA SIGN UPADHMANIYA", "Lo", 0, none),
  ("SHARADA OM", "Lo", 0, none),
  ("SHARADA DANDA", "Po", 0, none),
  ("SHARADA DOUBLE DANDA", "Po", 0, none),
  ("SHARADA ABBREVIATION SIGN", "Po", 0, none),
  ("SHARADA SEPARATOR", "Po", 0, none),
  ("SHARADA SANDHI MARK", "Mn", 0, none),
  ("SHARADA SIGN NUKTA", "Mn", 7, none),
  ("SHARADA VOWEL MODIFIER MARK", "Mn", 0, none),
  ("SHARADA EXTRA SHORT VOWEL MARK", "Mn", 0, none),
  ("SHARADA SUTRA MARK", "Po", 0, none),
  ("SHARADA VOWEL SIGN PRISHTHAMATRA E", "Mc", 0, none),
  ("SHARADA SIGN INVERTED CANDRABINDU", "Mn", 0, none),
  ("SHARADA DIGIT ZERO", "Nd", 0, none),
  ("SHARADA DIGIT ONE", "Nd", 0, none),
  ("SHARADA DIGIT TWO", "Nd", 0, none),
  ("SHARADA DIGIT THREE", "Nd", 0, none),
  ("SHARADA DIGIT FOUR", "Nd", 0, none),
  ("SHARADA DIGIT FIVE", "Nd", 0, none),
  ("SHARADA DIGIT SIX", "Nd", 0, none),
  ("SHARADA DIGIT SEVEN", "Nd", 0, none),
  ("SHARADA DIGIT EIGHT", "Nd", 0, none),
  ("SHARADA DIGIT NINE", "Nd", 0, none),
  ("SHARADA EKAM", "Lo", 0, none),
  ("SHARADA SIGN SIDDHAM", "Po", 0, none),
  ("SHARADA HEADSTROKE", "Lo", 0, none),
  ("SHARADA CONTINUATION SIGN", "Po", 0, none),
  ("SHARADA SECTION MARK-1", "Po", 0, none),
  ("SHARADA SECTION MARK-2", "Po", 0, none),
)
