#let data = (
  ("ADLAM CAPITAL LETTER ALIF", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER DAALI", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER LAAM", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER MIIM", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER BA", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER SINNYIIYHE", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER PE", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER BHE", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER RA", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER E", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER FA", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER I", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER O", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER DHA", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER YHE", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER WAW", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER NUN", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER KAF", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER YA", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER U", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER JIIM", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER CHI", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER HA", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER QAAF", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER GA", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER NYA", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER TU", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER NHA", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER VA", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER KHA", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER GBE", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER ZAL", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER KPO", "Lu", 0, none),
  ("ADLAM CAPITAL LETTER SHA", "Lu", 0, none),
  ("ADLAM SMALL LETTER ALIF", "Ll", 0, none),
  ("ADLAM SMALL LETTER DAALI", "Ll", 0, none),
  ("ADLAM SMALL LETTER LAAM", "Ll", 0, none),
  ("ADLAM SMALL LETTER MIIM", "Ll", 0, none),
  ("ADLAM SMALL LETTER BA", "Ll", 0, none),
  ("ADLAM SMALL LETTER SINNYIIYHE", "Ll", 0, none),
  ("ADLAM SMALL LETTER PE", "Ll", 0, none),
  ("ADLAM SMALL LETTER BHE", "Ll", 0, none),
  ("ADLAM SMALL LETTER RA", "Ll", 0, none),
  ("ADLAM SMALL LETTER E", "Ll", 0, none),
  ("ADLAM SMALL LETTER FA", "Ll", 0, none),
  ("ADLAM SMALL LETTER I", "Ll", 0, none),
  ("ADLAM SMALL LETTER O", "Ll", 0, none),
  ("ADLAM SMALL LETTER DHA", "Ll", 0, none),
  ("ADLAM SMALL LETTER YHE", "Ll", 0, none),
  ("ADLAM SMALL LETTER WAW", "Ll", 0, none),
  ("ADLAM SMALL LETTER NUN", "Ll", 0, none),
  ("ADLAM SMALL LETTER KAF", "Ll", 0, none),
  ("ADLAM SMALL LETTER YA", "Ll", 0, none),
  ("ADLAM SMALL LETTER U", "Ll", 0, none),
  ("ADLAM SMALL LETTER JIIM", "Ll", 0, none),
  ("ADLAM SMALL LETTER CHI", "Ll", 0, none),
  ("ADLAM SMALL LETTER HA", "Ll", 0, none),
  ("ADLAM SMALL LETTER QAAF", "Ll", 0, none),
  ("ADLAM SMALL LETTER GA", "Ll", 0, none),
  ("ADLAM SMALL LETTER NYA", "Ll", 0, none),
  ("ADLAM SMALL LETTER TU", "Ll", 0, none),
  ("ADLAM SMALL LETTER NHA", "Ll", 0, none),
  ("ADLAM SMALL LETTER VA", "Ll", 0, none),
  ("ADLAM SMALL LETTER KHA", "Ll", 0, none),
  ("ADLAM SMALL LETTER GBE", "Ll", 0, none),
  ("ADLAM SMALL LETTER ZAL", "Ll", 0, none),
  ("ADLAM SMALL LETTER KPO", "Ll", 0, none),
  ("ADLAM SMALL LETTER SHA", "Ll", 0, none),
  ("ADLAM ALIF LENGTHENER", "Mn", 230, none),
  ("ADLAM VOWEL LENGTHENER", "Mn", 230, none),
  ("ADLAM GEMINATION MARK", "Mn", 230, none),
  ("ADLAM HAMZA", "Mn", 230, none),
  ("ADLAM CONSONANT MODIFIER", "Mn", 230, none),
  ("ADLAM GEMINATE CONSONANT MODIFIER", "Mn", 230, none),
  ("ADLAM NUKTA", "Mn", 7, none),
  ("ADLAM NASALIZATION MARK", "Lm", 0, none),
  (),
  (),
  (),
  (),
  ("ADLAM DIGIT ZERO", "Nd", 0, none),
  ("ADLAM DIGIT ONE", "Nd", 0, none),
  ("ADLAM DIGIT TWO", "Nd", 0, none),
  ("ADLAM DIGIT THREE", "Nd", 0, none),
  ("ADLAM DIGIT FOUR", "Nd", 0, none),
  ("ADLAM DIGIT FIVE", "Nd", 0, none),
  ("ADLAM DIGIT SIX", "Nd", 0, none),
  ("ADLAM DIGIT SEVEN", "Nd", 0, none),
  ("ADLAM DIGIT EIGHT", "Nd", 0, none),
  ("ADLAM DIGIT NINE", "Nd", 0, none),
  (),
  (),
  (),
  (),
  ("ADLAM INITIAL EXCLAMATION MARK", "Po", 0, none),
  ("ADLAM INITIAL QUESTION MARK", "Po", 0, none),
)
