#let data = (
  ("BUGINESE LETTER KA", "Lo", 0, none),
  ("BUGINESE LETTER GA", "Lo", 0, none),
  ("BUGINESE LETTER NGA", "Lo", 0, none),
  ("BUGINESE LETTER NGKA", "Lo", 0, none),
  ("BUGINESE LETTER PA", "Lo", 0, none),
  ("BUGINESE LETTER BA", "Lo", 0, none),
  ("BUGINESE LETTER MA", "Lo", 0, none),
  ("BUGINESE LETTER MPA", "Lo", 0, none),
  ("BUGINESE LETTER TA", "Lo", 0, none),
  ("BUGINESE LETTER DA", "Lo", 0, none),
  ("BUGINESE LETTER NA", "Lo", 0, none),
  ("BUGINESE LETTER NRA", "Lo", 0, none),
  ("BUGINESE LETTER CA", "Lo", 0, none),
  ("BUGINESE LETTER JA", "Lo", 0, none),
  ("BUGINESE LETTER NYA", "Lo", 0, none),
  ("BUGINESE LETTER NYCA", "Lo", 0, none),
  ("BUGINESE LETTER YA", "Lo", 0, none),
  ("BUGINESE LETTER RA", "Lo", 0, none),
  ("BUGINESE LETTER LA", "Lo", 0, none),
  ("BUGINESE LETTER VA", "Lo", 0, none),
  ("BUGINESE LETTER SA", "Lo", 0, none),
  ("BUGINESE LETTER A", "Lo", 0, none),
  ("BUGINESE LETTER HA", "Lo", 0, none),
  ("BUGINESE VOWEL SIGN I", "Mn", 230, none),
  ("BUGINESE VOWEL SIGN U", "Mn", 220, none),
  ("BUGINESE VOWEL SIGN E", "Mc", 0, none),
  ("BUGINESE VOWEL SIGN O", "Mc", 0, none),
  ("BUGINESE VOWEL SIGN AE", "Mn", 0, none),
  (),
  (),
  ("BUGINESE PALLAWA", "Po", 0, none),
  ("BUGINESE END OF SECTION", "Po", 0, none),
)
