#let data = (
  ("ETHIOPIC SYLLABLE LOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE MOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ROA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SHOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE TOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE COA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE NYOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GLOTTAL OA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE DDOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE JOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE THOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CHOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PHOA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE POA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GGWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GGWI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GGWEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GGWE", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("ETHIOPIC SYLLABLE SSA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SSU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SSI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SSAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SSEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SSE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SSO", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE CCA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCO", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE ZZA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZZU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZZI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZZAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZZEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZZE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE ZZO", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE CCHA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCHU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCHI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCHAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCHEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCHE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE CCHO", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE QYA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QYU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QYI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QYAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QYEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QYE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE QYO", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE KYA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KYU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KYI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KYAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KYEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KYE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE KYO", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE XYA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XYU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XYI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XYAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XYEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XYE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE XYO", "Lo", 0, none),
  (),
  ("ETHIOPIC SYLLABLE GYA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GYU", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GYI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GYAA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GYEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GYE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE GYO", "Lo", 0, none),
)
