#let data = (
  ("KATAKANA LETTER SMALL KU", "Lo", 0, none),
  ("KATAKANA LETTER SMALL SI", "Lo", 0, none),
  ("KATAKANA LETTER SMALL SU", "Lo", 0, none),
  ("KATAKANA LETTER SMALL TO", "Lo", 0, none),
  ("KATAKANA LETTER SMALL NU", "Lo", 0, none),
  ("KATAKANA LETTER SMALL HA", "Lo", 0, none),
  ("KATAKANA LETTER SMALL HI", "Lo", 0, none),
  ("KATAKANA LETTER SMALL HU", "Lo", 0, none),
  ("KATAKANA LETTER SMALL HE", "Lo", 0, none),
  ("KATAKANA LETTER SMALL HO", "Lo", 0, none),
  ("KATAKANA LETTER SMALL MU", "Lo", 0, none),
  ("KATAKANA LETTER SMALL RA", "Lo", 0, none),
  ("KATAKANA LETTER SMALL RI", "Lo", 0, none),
  ("KATAKANA LETTER SMALL RU", "Lo", 0, none),
  ("KATAKANA LETTER SMALL RE", "Lo", 0, none),
  ("KATAKANA LETTER SMALL RO", "Lo", 0, none),
)
