#let data = (
  ("AVESTAN LETTER A", "Lo", 0, none),
  ("AVESTAN LETTER AA", "Lo", 0, none),
  ("AVESTAN LETTER AO", "Lo", 0, none),
  ("AVESTAN LETTER AAO", "Lo", 0, none),
  ("AVESTAN LETTER AN", "Lo", 0, none),
  ("AVESTAN LETTER AAN", "Lo", 0, none),
  ("AVESTAN LETTER AE", "Lo", 0, none),
  ("AVESTAN LETTER AEE", "Lo", 0, none),
  ("AVESTAN LETTER E", "Lo", 0, none),
  ("AVESTAN LETTER EE", "Lo", 0, none),
  ("AVESTAN LETTER O", "Lo", 0, none),
  ("AVESTAN LETTER OO", "Lo", 0, none),
  ("AVESTAN LETTER I", "Lo", 0, none),
  ("AVESTAN LETTER II", "Lo", 0, none),
  ("AVESTAN LETTER U", "Lo", 0, none),
  ("AVESTAN LETTER UU", "Lo", 0, none),
  ("AVESTAN LETTER KE", "Lo", 0, none),
  ("AVESTAN LETTER XE", "Lo", 0, none),
  ("AVESTAN LETTER XYE", "Lo", 0, none),
  ("AVESTAN LETTER XVE", "Lo", 0, none),
  ("AVESTAN LETTER GE", "Lo", 0, none),
  ("AVESTAN LETTER GGE", "Lo", 0, none),
  ("AVESTAN LETTER GHE", "Lo", 0, none),
  ("AVESTAN LETTER CE", "Lo", 0, none),
  ("AVESTAN LETTER JE", "Lo", 0, none),
  ("AVESTAN LETTER TE", "Lo", 0, none),
  ("AVESTAN LETTER THE", "Lo", 0, none),
  ("AVESTAN LETTER DE", "Lo", 0, none),
  ("AVESTAN LETTER DHE", "Lo", 0, none),
  ("AVESTAN LETTER TTE", "Lo", 0, none),
  ("AVESTAN LETTER PE", "Lo", 0, none),
  ("AVESTAN LETTER FE", "Lo", 0, none),
  ("AVESTAN LETTER BE", "Lo", 0, none),
  ("AVESTAN LETTER BHE", "Lo", 0, none),
  ("AVESTAN LETTER NGE", "Lo", 0, none),
  ("AVESTAN LETTER NGYE", "Lo", 0, none),
  ("AVESTAN LETTER NGVE", "Lo", 0, none),
  ("AVESTAN LETTER NE", "Lo", 0, none),
  ("AVESTAN LETTER NYE", "Lo", 0, none),
  ("AVESTAN LETTER NNE", "Lo", 0, none),
  ("AVESTAN LETTER ME", "Lo", 0, none),
  ("AVESTAN LETTER HME", "Lo", 0, none),
  ("AVESTAN LETTER YYE", "Lo", 0, none),
  ("AVESTAN LETTER YE", "Lo", 0, none),
  ("AVESTAN LETTER VE", "Lo", 0, none),
  ("AVESTAN LETTER RE", "Lo", 0, none),
  ("AVESTAN LETTER LE", "Lo", 0, none),
  ("AVESTAN LETTER SE", "Lo", 0, none),
  ("AVESTAN LETTER ZE", "Lo", 0, none),
  ("AVESTAN LETTER SHE", "Lo", 0, none),
  ("AVESTAN LETTER ZHE", "Lo", 0, none),
  ("AVESTAN LETTER SHYE", "Lo", 0, none),
  ("AVESTAN LETTER SSHE", "Lo", 0, none),
  ("AVESTAN LETTER HE", "Lo", 0, none),
  (),
  (),
  (),
  ("AVESTAN ABBREVIATION MARK", "Po", 0, none),
  ("TINY TWO DOTS OVER ONE DOT PUNCTUATION", "Po", 0, none),
  ("SMALL TWO DOTS OVER ONE DOT PUNCTUATION", "Po", 0, none),
  ("LARGE TWO DOTS OVER ONE DOT PUNCTUATION", "Po", 0, none),
  ("LARGE ONE DOT OVER TWO DOTS PUNCTUATION", "Po", 0, none),
  ("LARGE TWO RINGS OVER ONE RING PUNCTUATION", "Po", 0, none),
  ("LARGE ONE RING OVER TWO RINGS PUNCTUATION", "Po", 0, none),
)
