#let data = (
  ("OGHAM SPACE MARK", "Zs", 0, none),
  ("OGHAM LETTER BEITH", "Lo", 0, none),
  ("OGHAM LETTER LUIS", "Lo", 0, none),
  ("OGHAM LETTER FEARN", "Lo", 0, none),
  ("OGHAM LETTER SAIL", "Lo", 0, none),
  ("OGHAM LETTER NION", "Lo", 0, none),
  ("OGHAM LETTER UATH", "Lo", 0, none),
  ("OGHAM LETTER DAIR", "Lo", 0, none),
  ("OGHAM LETTER TINNE", "Lo", 0, none),
  ("OGHAM LETTER COLL", "Lo", 0, none),
  ("OGHAM LETTER CEIRT", "Lo", 0, none),
  ("OGHAM LETTER MUIN", "Lo", 0, none),
  ("OGHAM LETTER GORT", "Lo", 0, none),
  ("OGHAM LETTER NGEADAL", "Lo", 0, none),
  ("OGHAM LETTER STRAIF", "Lo", 0, none),
  ("OGHAM LETTER RUIS", "Lo", 0, none),
  ("OGHAM LETTER AILM", "Lo", 0, none),
  ("OGHAM LETTER ONN", "Lo", 0, none),
  ("OGHAM LETTER UR", "Lo", 0, none),
  ("OGHAM LETTER EADHADH", "Lo", 0, none),
  ("OGHAM LETTER IODHADH", "Lo", 0, none),
  ("OGHAM LETTER EABHADH", "Lo", 0, none),
  ("OGHAM LETTER OR", "Lo", 0, none),
  ("OGHAM LETTER UILLEANN", "Lo", 0, none),
  ("OGHAM LETTER IFIN", "Lo", 0, none),
  ("OGHAM LETTER EAMHANCHOLL", "Lo", 0, none),
  ("OGHAM LETTER PEITH", "Lo", 0, none),
  ("OGHAM FEATHER MARK", "Ps", 0, none),
  ("OGHAM REVERSED FEATHER MARK", "Pe", 0, none),
)
