#let data = (
  ("BLACK SUN WITH RAYS", "So", 0, none),
  ("CLOUD", "So", 0, none),
  ("UMBRELLA", "So", 0, none),
  ("SNOWMAN", "So", 0, none),
  ("COMET", "So", 0, none),
  ("BLACK STAR", "So", 0, "B"),
  ("WHITE STAR", "So", 0, "B"),
  ("LIGHTNING", "So", 0, none),
  ("THUNDERSTORM", "So", 0, none),
  ("SUN", "So", 0, "N"),
  ("ASCENDING NODE", "So", 0, none),
  ("DESCENDING NODE", "So", 0, none),
  ("CONJUNCTION", "So", 0, "N"),
  ("OPPOSITION", "So", 0, none),
  ("BLACK TELEPHONE", "So", 0, none),
  ("WHITE TELEPHONE", "So", 0, none),
  ("BALLOT BOX", "So", 0, none),
  ("BALLOT BOX WITH CHECK", "So", 0, none),
  ("BALLOT BOX WITH X", "So", 0, none),
  ("SALTIRE", "So", 0, none),
  ("UMBRELLA WITH RAIN DROPS", "So", 0, none),
  ("HOT BEVERAGE", "So", 0, none),
  ("WHITE SHOGI PIECE", "So", 0, none),
  ("BLACK SHOGI PIECE", "So", 0, none),
  ("SHAMROCK", "So", 0, none),
  ("REVERSED ROTATED FLORAL HEART BULLET", "So", 0, none),
  ("BLACK LEFT POINTING INDEX", "So", 0, none),
  ("BLACK RIGHT POINTING INDEX", "So", 0, none),
  ("WHITE LEFT POINTING INDEX", "So", 0, none),
  ("WHITE UP POINTING INDEX", "So", 0, none),
  ("WHITE RIGHT POINTING INDEX", "So", 0, none),
  ("WHITE DOWN POINTING INDEX", "So", 0, none),
  ("SKULL AND CROSSBONES", "So", 0, none),
  ("CAUTION SIGN", "So", 0, none),
  ("RADIOACTIVE SIGN", "So", 0, none),
  ("BIOHAZARD SIGN", "So", 0, none),
  ("CADUCEUS", "So", 0, none),
  ("ANKH", "So", 0, none),
  ("ORTHODOX CROSS", "So", 0, none),
  ("CHI RHO", "So", 0, none),
  ("CROSS OF LORRAINE", "So", 0, none),
  ("CROSS OF JERUSALEM", "So", 0, none),
  ("STAR AND CRESCENT", "So", 0, none),
  ("FARSI SYMBOL", "So", 0, none),
  ("ADI SHAKTI", "So", 0, none),
  ("HAMMER AND SICKLE", "So", 0, none),
  ("PEACE SYMBOL", "So", 0, none),
  ("YIN YANG", "So", 0, none),
  ("TRIGRAM FOR HEAVEN", "So", 0, none),
  ("TRIGRAM FOR LAKE", "So", 0, none),
  ("TRIGRAM FOR FIRE", "So", 0, none),
  ("TRIGRAM FOR THUNDER", "So", 0, none),
  ("TRIGRAM FOR WIND", "So", 0, none),
  ("TRIGRAM FOR WATER", "So", 0, none),
  ("TRIGRAM FOR MOUNTAIN", "So", 0, none),
  ("TRIGRAM FOR EARTH", "So", 0, none),
  ("WHEEL OF DHARMA", "So", 0, none),
  ("WHITE FROWNING FACE", "So", 0, none),
  ("WHITE SMILING FACE", "So", 0, none),
  ("BLACK SMILING FACE", "So", 0, none),
  ("WHITE SUN WITH RAYS", "So", 0, none),
  ("FIRST QUARTER MOON", "So", 0, "N"),
  ("LAST QUARTER MOON", "So", 0, "N"),
  ("MERCURY", "So", 0, "N"),
  ("FEMALE SIGN", "So", 0, "N"),
  ("EARTH", "So", 0, "N"),
  ("MALE SIGN", "So", 0, "N"),
  ("JUPITER", "So", 0, "N"),
  ("SATURN", "So", 0, "N"),
  ("URANUS", "So", 0, none),
  ("NEPTUNE", "So", 0, "N"),
  ("PLUTO", "So", 0, "N"),
  ("ARIES", "So", 0, "N"),
  ("TAURUS", "So", 0, "N"),
  ("GEMINI", "So", 0, none),
  ("CANCER", "So", 0, none),
  ("LEO", "So", 0, none),
  ("VIRGO", "So", 0, none),
  ("LIBRA", "So", 0, none),
  ("SCORPIUS", "So", 0, none),
  ("SAGITTARIUS", "So", 0, none),
  ("CAPRICORN", "So", 0, none),
  ("AQUARIUS", "So", 0, none),
  ("PISCES", "So", 0, none),
  ("WHITE CHESS KING", "So", 0, none),
  ("WHITE CHESS QUEEN", "So", 0, none),
  ("WHITE CHESS ROOK", "So", 0, none),
  ("WHITE CHESS BISHOP", "So", 0, none),
  ("WHITE CHESS KNIGHT", "So", 0, none),
  ("WHITE CHESS PAWN", "So", 0, none),
  ("BLACK CHESS KING", "So", 0, none),
  ("BLACK CHESS QUEEN", "So", 0, none),
  ("BLACK CHESS ROOK", "So", 0, none),
  ("BLACK CHESS BISHOP", "So", 0, none),
  ("BLACK CHESS KNIGHT", "So", 0, none),
  ("BLACK CHESS PAWN", "So", 0, none),
  ("BLACK SPADE SUIT", "So", 0, "N"),
  ("WHITE HEART SUIT", "So", 0, "N"),
  ("WHITE DIAMOND SUIT", "So", 0, "N"),
  ("BLACK CLUB SUIT", "So", 0, "N"),
  ("WHITE SPADE SUIT", "So", 0, "N"),
  ("BLACK HEART SUIT", "So", 0, "N"),
  ("BLACK DIAMOND SUIT", "So", 0, "N"),
  ("WHITE CLUB SUIT", "So", 0, "N"),
  ("HOT SPRINGS", "So", 0, none),
  ("QUARTER NOTE", "So", 0, "N"),
  ("EIGHTH NOTE", "So", 0, none),
  ("BEAMED EIGHTH NOTES", "So", 0, none),
  ("BEAMED SIXTEENTH NOTES", "So", 0, none),
  ("MUSIC FLAT SIGN", "So", 0, "N"),
  ("MUSIC NATURAL SIGN", "So", 0, "N"),
  ("MUSIC SHARP SIGN", "Sm", 0, "N"),
  ("WEST SYRIAC CROSS", "So", 0, none),
  ("EAST SYRIAC CROSS", "So", 0, none),
  ("UNIVERSAL RECYCLING SYMBOL", "So", 0, none),
  ("RECYCLING SYMBOL FOR TYPE-1 PLASTICS", "So", 0, none),
  ("RECYCLING SYMBOL FOR TYPE-2 PLASTICS", "So", 0, none),
  ("RECYCLING SYMBOL FOR TYPE-3 PLASTICS", "So", 0, none),
  ("RECYCLING SYMBOL FOR TYPE-4 PLASTICS", "So", 0, none),
  ("RECYCLING SYMBOL FOR TYPE-5 PLASTICS", "So", 0, none),
  ("RECYCLING SYMBOL FOR TYPE-6 PLASTICS", "So", 0, none),
  ("RECYCLING SYMBOL FOR TYPE-7 PLASTICS", "So", 0, none),
  ("RECYCLING SYMBOL FOR GENERIC MATERIALS", "So", 0, none),
  ("BLACK UNIVERSAL RECYCLING SYMBOL", "So", 0, none),
  ("RECYCLED PAPER SYMBOL", "So", 0, none),
  ("PARTIALLY-RECYCLED PAPER SYMBOL", "So", 0, none),
  ("PERMANENT PAPER SIGN", "So", 0, none),
  ("WHEELCHAIR SYMBOL", "So", 0, none),
  ("DIE FACE-1", "So", 0, "N"),
  ("DIE FACE-2", "So", 0, "N"),
  ("DIE FACE-3", "So", 0, "N"),
  ("DIE FACE-4", "So", 0, "N"),
  ("DIE FACE-5", "So", 0, "N"),
  ("DIE FACE-6", "So", 0, "N"),
  ("WHITE CIRCLE WITH DOT RIGHT", "So", 0, "N"),
  ("WHITE CIRCLE WITH TWO DOTS", "So", 0, "N"),
  ("BLACK CIRCLE WITH WHITE DOT RIGHT", "So", 0, "N"),
  ("BLACK CIRCLE WITH TWO WHITE DOTS", "So", 0, "N"),
  ("MONOGRAM FOR YANG", "So", 0, none),
  ("MONOGRAM FOR YIN", "So", 0, none),
  ("DIGRAM FOR GREATER YANG", "So", 0, none),
  ("DIGRAM FOR LESSER YIN", "So", 0, none),
  ("DIGRAM FOR LESSER YANG", "So", 0, none),
  ("DIGRAM FOR GREATER YIN", "So", 0, none),
  ("WHITE FLAG", "So", 0, none),
  ("BLACK FLAG", "So", 0, none),
  ("HAMMER AND PICK", "So", 0, none),
  ("ANCHOR", "So", 0, none),
  ("CROSSED SWORDS", "So", 0, none),
  ("STAFF OF AESCULAPIUS", "So", 0, none),
  ("SCALES", "So", 0, none),
  ("ALEMBIC", "So", 0, none),
  ("FLOWER", "So", 0, none),
  ("GEAR", "So", 0, none),
  ("STAFF OF HERMES", "So", 0, none),
  ("ATOM SYMBOL", "So", 0, none),
  ("FLEUR-DE-LIS", "So", 0, none),
  ("OUTLINED WHITE STAR", "So", 0, none),
  ("THREE LINES CONVERGING RIGHT", "So", 0, none),
  ("THREE LINES CONVERGING LEFT", "So", 0, none),
  ("WARNING SIGN", "So", 0, none),
  ("HIGH VOLTAGE SIGN", "So", 0, none),
  ("DOUBLED FEMALE SIGN", "So", 0, none),
  ("DOUBLED MALE SIGN", "So", 0, none),
  ("INTERLOCKED FEMALE AND MALE SIGN", "So", 0, none),
  ("MALE AND FEMALE SIGN", "So", 0, none),
  ("MALE WITH STROKE SIGN", "So", 0, none),
  ("MALE WITH STROKE AND MALE AND FEMALE SIGN", "So", 0, none),
  ("VERTICAL MALE WITH STROKE SIGN", "So", 0, none),
  ("HORIZONTAL MALE WITH STROKE SIGN", "So", 0, none),
  ("MEDIUM WHITE CIRCLE", "So", 0, "N"),
  ("MEDIUM BLACK CIRCLE", "So", 0, "N"),
  ("MEDIUM SMALL WHITE CIRCLE", "So", 0, "N"),
  ("MARRIAGE SYMBOL", "So", 0, none),
  ("DIVORCE SYMBOL", "So", 0, none),
  ("UNMARRIED PARTNERSHIP SYMBOL", "So", 0, none),
  ("COFFIN", "So", 0, none),
  ("FUNERAL URN", "So", 0, none),
  ("NEUTER", "So", 0, "N"),
  ("CERES", "So", 0, none),
  ("PALLAS", "So", 0, none),
  ("JUNO", "So", 0, none),
  ("VESTA", "So", 0, none),
  ("CHIRON", "So", 0, none),
  ("BLACK MOON LILITH", "So", 0, none),
  ("SEXTILE", "So", 0, none),
  ("SEMISEXTILE", "So", 0, none),
  ("QUINCUNX", "So", 0, none),
  ("SESQUIQUADRATE", "So", 0, none),
  ("SOCCER BALL", "So", 0, none),
  ("BASEBALL", "So", 0, none),
  ("SQUARED KEY", "So", 0, none),
  ("WHITE DRAUGHTS MAN", "So", 0, none),
  ("WHITE DRAUGHTS KING", "So", 0, none),
  ("BLACK DRAUGHTS MAN", "So", 0, none),
  ("BLACK DRAUGHTS KING", "So", 0, none),
  ("SNOWMAN WITHOUT SNOW", "So", 0, none),
  ("SUN BEHIND CLOUD", "So", 0, none),
  ("RAIN", "So", 0, none),
  ("BLACK SNOWMAN", "So", 0, none),
  ("THUNDER CLOUD AND RAIN", "So", 0, none),
  ("TURNED WHITE SHOGI PIECE", "So", 0, none),
  ("TURNED BLACK SHOGI PIECE", "So", 0, none),
  ("WHITE DIAMOND IN SQUARE", "So", 0, none),
  ("CROSSING LANES", "So", 0, none),
  ("DISABLED CAR", "So", 0, none),
  ("OPHIUCHUS", "So", 0, none),
  ("PICK", "So", 0, none),
  ("CAR SLIDING", "So", 0, none),
  ("HELMET WITH WHITE CROSS", "So", 0, none),
  ("CIRCLED CROSSING LANES", "So", 0, none),
  ("CHAINS", "So", 0, none),
  ("NO ENTRY", "So", 0, none),
  ("ALTERNATE ONE-WAY LEFT WAY TRAFFIC", "So", 0, none),
  ("BLACK TWO-WAY LEFT WAY TRAFFIC", "So", 0, none),
  ("WHITE TWO-WAY LEFT WAY TRAFFIC", "So", 0, none),
  ("BLACK LEFT LANE MERGE", "So", 0, none),
  ("WHITE LEFT LANE MERGE", "So", 0, none),
  ("DRIVE SLOW SIGN", "So", 0, none),
  ("HEAVY WHITE DOWN-POINTING TRIANGLE", "So", 0, none),
  ("LEFT CLOSED ENTRY", "So", 0, none),
  ("SQUARED SALTIRE", "So", 0, none),
  ("FALLING DIAGONAL IN WHITE CIRCLE IN BLACK SQUARE", "So", 0, none),
  ("BLACK TRUCK", "So", 0, none),
  ("RESTRICTED LEFT ENTRY-1", "So", 0, none),
  ("RESTRICTED LEFT ENTRY-2", "So", 0, none),
  ("ASTRONOMICAL SYMBOL FOR URANUS", "So", 0, none),
  ("HEAVY CIRCLE WITH STROKE AND TWO DOTS ABOVE", "So", 0, none),
  ("PENTAGRAM", "So", 0, none),
  ("RIGHT-HANDED INTERLACED PENTAGRAM", "So", 0, none),
  ("LEFT-HANDED INTERLACED PENTAGRAM", "So", 0, none),
  ("INVERTED PENTAGRAM", "So", 0, none),
  ("BLACK CROSS ON SHIELD", "So", 0, none),
  ("SHINTO SHRINE", "So", 0, none),
  ("CHURCH", "So", 0, none),
  ("CASTLE", "So", 0, none),
  ("HISTORIC SITE", "So", 0, none),
  ("GEAR WITHOUT HUB", "So", 0, none),
  ("GEAR WITH HANDLES", "So", 0, none),
  ("MAP SYMBOL FOR LIGHTHOUSE", "So", 0, none),
  ("MOUNTAIN", "So", 0, none),
  ("UMBRELLA ON GROUND", "So", 0, none),
  ("FOUNTAIN", "So", 0, none),
  ("FLAG IN HOLE", "So", 0, none),
  ("FERRY", "So", 0, none),
  ("SAILBOAT", "So", 0, none),
  ("SQUARE FOUR CORNERS", "So", 0, none),
  ("SKIER", "So", 0, none),
  ("ICE SKATE", "So", 0, none),
  ("PERSON WITH BALL", "So", 0, none),
  ("TENT", "So", 0, none),
  ("JAPANESE BANK SYMBOL", "So", 0, none),
  ("HEADSTONE GRAVEYARD SYMBOL", "So", 0, none),
  ("FUEL PUMP", "So", 0, none),
  ("CUP ON BLACK SQUARE", "So", 0, none),
  ("WHITE FLAG WITH HORIZONTAL MIDDLE BLACK STRIPE", "So", 0, none),
)
