#let data = (
  ("TAKRI LETTER A", "Lo", 0, none),
  ("TAKRI LETTER AA", "Lo", 0, none),
  ("TAKRI LETTER I", "Lo", 0, none),
  ("TAKRI LETTER II", "Lo", 0, none),
  ("TAKRI LETTER U", "Lo", 0, none),
  ("TAKRI LETTER UU", "Lo", 0, none),
  ("TAKRI LETTER E", "Lo", 0, none),
  ("TAKRI LETTER AI", "Lo", 0, none),
  ("TAKRI LETTER O", "Lo", 0, none),
  ("TAKRI LETTER AU", "Lo", 0, none),
  ("TAKRI LETTER KA", "Lo", 0, none),
  ("TAKRI LETTER KHA", "Lo", 0, none),
  ("TAKRI LETTER GA", "Lo", 0, none),
  ("TAKRI LETTER GHA", "Lo", 0, none),
  ("TAKRI LETTER NGA", "Lo", 0, none),
  ("TAKRI LETTER CA", "Lo", 0, none),
  ("TAKRI LETTER CHA", "Lo", 0, none),
  ("TAKRI LETTER JA", "Lo", 0, none),
  ("TAKRI LETTER JHA", "Lo", 0, none),
  ("TAKRI LETTER NYA", "Lo", 0, none),
  ("TAKRI LETTER TTA", "Lo", 0, none),
  ("TAKRI LETTER TTHA", "Lo", 0, none),
  ("TAKRI LETTER DDA", "Lo", 0, none),
  ("TAKRI LETTER DDHA", "Lo", 0, none),
  ("TAKRI LETTER NNA", "Lo", 0, none),
  ("TAKRI LETTER TA", "Lo", 0, none),
  ("TAKRI LETTER THA", "Lo", 0, none),
  ("TAKRI LETTER DA", "Lo", 0, none),
  ("TAKRI LETTER DHA", "Lo", 0, none),
  ("TAKRI LETTER NA", "Lo", 0, none),
  ("TAKRI LETTER PA", "Lo", 0, none),
  ("TAKRI LETTER PHA", "Lo", 0, none),
  ("TAKRI LETTER BA", "Lo", 0, none),
  ("TAKRI LETTER BHA", "Lo", 0, none),
  ("TAKRI LETTER MA", "Lo", 0, none),
  ("TAKRI LETTER YA", "Lo", 0, none),
  ("TAKRI LETTER RA", "Lo", 0, none),
  ("TAKRI LETTER LA", "Lo", 0, none),
  ("TAKRI LETTER VA", "Lo", 0, none),
  ("TAKRI LETTER SHA", "Lo", 0, none),
  ("TAKRI LETTER SA", "Lo", 0, none),
  ("TAKRI LETTER HA", "Lo", 0, none),
  ("TAKRI LETTER RRA", "Lo", 0, none),
  ("TAKRI SIGN ANUSVARA", "Mn", 0, none),
  ("TAKRI SIGN VISARGA", "Mc", 0, none),
  ("TAKRI VOWEL SIGN AA", "Mn", 0, none),
  ("TAKRI VOWEL SIGN I", "Mc", 0, none),
  ("TAKRI VOWEL SIGN II", "Mc", 0, none),
  ("TAKRI VOWEL SIGN U", "Mn", 0, none),
  ("TAKRI VOWEL SIGN UU", "Mn", 0, none),
  ("TAKRI VOWEL SIGN E", "Mn", 0, none),
  ("TAKRI VOWEL SIGN AI", "Mn", 0, none),
  ("TAKRI VOWEL SIGN O", "Mn", 0, none),
  ("TAKRI VOWEL SIGN AU", "Mn", 0, none),
  ("TAKRI SIGN VIRAMA", "Mc", 9, none),
  ("TAKRI SIGN NUKTA", "Mn", 7, none),
  ("TAKRI LETTER ARCHAIC KHA", "Lo", 0, none),
  ("TAKRI ABBREVIATION SIGN", "Po", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TAKRI DIGIT ZERO", "Nd", 0, none),
  ("TAKRI DIGIT ONE", "Nd", 0, none),
  ("TAKRI DIGIT TWO", "Nd", 0, none),
  ("TAKRI DIGIT THREE", "Nd", 0, none),
  ("TAKRI DIGIT FOUR", "Nd", 0, none),
  ("TAKRI DIGIT FIVE", "Nd", 0, none),
  ("TAKRI DIGIT SIX", "Nd", 0, none),
  ("TAKRI DIGIT SEVEN", "Nd", 0, none),
  ("TAKRI DIGIT EIGHT", "Nd", 0, none),
  ("TAKRI DIGIT NINE", "Nd", 0, none),
)
