#let data = (
  ("BASSA VAH LETTER ENNI", "Lo", 0, none),
  ("BASSA VAH LETTER KA", "Lo", 0, none),
  ("BASSA VAH LETTER SE", "Lo", 0, none),
  ("BASSA VAH LETTER FA", "Lo", 0, none),
  ("BASSA VAH LETTER MBE", "Lo", 0, none),
  ("BASSA VAH LETTER YIE", "Lo", 0, none),
  ("BASSA VAH LETTER GAH", "Lo", 0, none),
  ("BASSA VAH LETTER DHII", "Lo", 0, none),
  ("BASSA VAH LETTER KPAH", "Lo", 0, none),
  ("BASSA VAH LETTER JO", "Lo", 0, none),
  ("BASSA VAH LETTER HWAH", "Lo", 0, none),
  ("BASSA VAH LETTER WA", "Lo", 0, none),
  ("BASSA VAH LETTER ZO", "Lo", 0, none),
  ("BASSA VAH LETTER GBU", "Lo", 0, none),
  ("BASSA VAH LETTER DO", "Lo", 0, none),
  ("BASSA VAH LETTER CE", "Lo", 0, none),
  ("BASSA VAH LETTER UWU", "Lo", 0, none),
  ("BASSA VAH LETTER TO", "Lo", 0, none),
  ("BASSA VAH LETTER BA", "Lo", 0, none),
  ("BASSA VAH LETTER VU", "Lo", 0, none),
  ("BASSA VAH LETTER YEIN", "Lo", 0, none),
  ("BASSA VAH LETTER PA", "Lo", 0, none),
  ("BASSA VAH LETTER WADDA", "Lo", 0, none),
  ("BASSA VAH LETTER A", "Lo", 0, none),
  ("BASSA VAH LETTER O", "Lo", 0, none),
  ("BASSA VAH LETTER OO", "Lo", 0, none),
  ("BASSA VAH LETTER U", "Lo", 0, none),
  ("BASSA VAH LETTER EE", "Lo", 0, none),
  ("BASSA VAH LETTER E", "Lo", 0, none),
  ("BASSA VAH LETTER I", "Lo", 0, none),
  (),
  (),
  ("BASSA VAH COMBINING HIGH TONE", "Mn", 1, none),
  ("BASSA VAH COMBINING LOW TONE", "Mn", 1, none),
  ("BASSA VAH COMBINING MID TONE", "Mn", 1, none),
  ("BASSA VAH COMBINING LOW-MID TONE", "Mn", 1, none),
  ("BASSA VAH COMBINING HIGH-LOW TONE", "Mn", 1, none),
  ("BASSA VAH FULL STOP", "Po", 0, none),
)
