#let data = (
  ("BUHID LETTER A", "Lo", 0, none),
  ("BUHID LETTER I", "Lo", 0, none),
  ("BUHID LETTER U", "Lo", 0, none),
  ("BUHID LETTER KA", "Lo", 0, none),
  ("BUHID LETTER GA", "Lo", 0, none),
  ("BUHID LETTER NGA", "Lo", 0, none),
  ("BUHID LETTER TA", "Lo", 0, none),
  ("BUHID LETTER DA", "Lo", 0, none),
  ("BUHID LETTER NA", "Lo", 0, none),
  ("BUHID LETTER PA", "Lo", 0, none),
  ("BUHID LETTER BA", "Lo", 0, none),
  ("BUHID LETTER MA", "Lo", 0, none),
  ("BUHID LETTER YA", "Lo", 0, none),
  ("BUHID LETTER RA", "Lo", 0, none),
  ("BUHID LETTER LA", "Lo", 0, none),
  ("BUHID LETTER WA", "Lo", 0, none),
  ("BUHID LETTER SA", "Lo", 0, none),
  ("BUHID LETTER HA", "Lo", 0, none),
  ("BUHID VOWEL SIGN I", "Mn", 0, none),
  ("BUHID VOWEL SIGN U", "Mn", 0, none),
)
