#let data = (
  ("PRESENTATION FORM FOR VERTICAL COMMA", "Po", 0, none),
  ("PRESENTATION FORM FOR VERTICAL IDEOGRAPHIC COMMA", "Po", 0, none),
  ("PRESENTATION FORM FOR VERTICAL IDEOGRAPHIC FULL STOP", "Po", 0, none),
  ("PRESENTATION FORM FOR VERTICAL COLON", "Po", 0, none),
  ("PRESENTATION FORM FOR VERTICAL SEMICOLON", "Po", 0, none),
  ("PRESENTATION FORM FOR VERTICAL EXCLAMATION MARK", "Po", 0, none),
  ("PRESENTATION FORM FOR VERTICAL QUESTION MARK", "Po", 0, none),
  ("PRESENTATION FORM FOR VERTICAL LEFT WHITE LENTICULAR BRACKET", "Ps", 0, none),
  ("PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRAKCET", "Pe", 0, none),
  ("PRESENTATION FORM FOR VERTICAL HORIZONTAL ELLIPSIS", "Po", 0, none),
)
