#let data = (
  ("SUPERSCRIPT ZERO", "No", 0, none),
  ("SUPERSCRIPT LATIN SMALL LETTER I", "Lm", 0, none),
  (),
  (),
  ("SUPERSCRIPT FOUR", "No", 0, none),
  ("SUPERSCRIPT FIVE", "No", 0, none),
  ("SUPERSCRIPT SIX", "No", 0, none),
  ("SUPERSCRIPT SEVEN", "No", 0, none),
  ("SUPERSCRIPT EIGHT", "No", 0, none),
  ("SUPERSCRIPT NINE", "No", 0, none),
  ("SUPERSCRIPT PLUS SIGN", "Sm", 0, "N"),
  ("SUPERSCRIPT MINUS", "Sm", 0, "N"),
  ("SUPERSCRIPT EQUALS SIGN", "Sm", 0, "N"),
  ("SUPERSCRIPT LEFT PARENTHESIS", "Ps", 0, "N"),
  ("SUPERSCRIPT RIGHT PARENTHESIS", "Pe", 0, "N"),
  ("SUPERSCRIPT LATIN SMALL LETTER N", "Lm", 0, none),
  ("SUBSCRIPT ZERO", "No", 0, none),
  ("SUBSCRIPT ONE", "No", 0, none),
  ("SUBSCRIPT TWO", "No", 0, none),
  ("SUBSCRIPT THREE", "No", 0, none),
  ("SUBSCRIPT FOUR", "No", 0, none),
  ("SUBSCRIPT FIVE", "No", 0, none),
  ("SUBSCRIPT SIX", "No", 0, none),
  ("SUBSCRIPT SEVEN", "No", 0, none),
  ("SUBSCRIPT EIGHT", "No", 0, none),
  ("SUBSCRIPT NINE", "No", 0, none),
  ("SUBSCRIPT PLUS SIGN", "Sm", 0, "N"),
  ("SUBSCRIPT MINUS", "Sm", 0, "N"),
  ("SUBSCRIPT EQUALS SIGN", "Sm", 0, "N"),
  ("SUBSCRIPT LEFT PARENTHESIS", "Ps", 0, "N"),
  ("SUBSCRIPT RIGHT PARENTHESIS", "Pe", 0, "N"),
  (),
  ("LATIN SUBSCRIPT SMALL LETTER A", "Lm", 0, none),
  ("LATIN SUBSCRIPT SMALL LETTER E", "Lm", 0, none),
  ("LATIN SUBSCRIPT SMALL LETTER O", "Lm", 0, none),
  ("LATIN SUBSCRIPT SMALL LETTER X", "Lm", 0, none),
  ("LATIN SUBSCRIPT SMALL LETTER SCHWA", "Lm", 0, none),
  ("LATIN SUBSCRIPT SMALL LETTER H", "Lm", 0, none),
  ("LATIN SUBSCRIPT SMALL LETTER K", "Lm", 0, none),
  ("LATIN SUBSCRIPT SMALL LETTER L", "Lm", 0, none),
  ("LATIN SUBSCRIPT SMALL LETTER M", "Lm", 0, none),
  ("LATIN SUBSCRIPT SMALL LETTER N", "Lm", 0, none),
  ("LATIN SUBSCRIPT SMALL LETTER P", "Lm", 0, none),
  ("LATIN SUBSCRIPT SMALL LETTER S", "Lm", 0, none),
  ("LATIN SUBSCRIPT SMALL LETTER T", "Lm", 0, none),
)
