#let data = (
  ("LIMBU VOWEL-CARRIER LETTER", "Lo", 0, none),
  ("LIMBU LETTER KA", "Lo", 0, none),
  ("LIMBU LETTER KHA", "Lo", 0, none),
  ("LIMBU LETTER GA", "Lo", 0, none),
  ("LIMBU LETTER GHA", "Lo", 0, none),
  ("LIMBU LETTER NGA", "Lo", 0, none),
  ("LIMBU LETTER CA", "Lo", 0, none),
  ("LIMBU LETTER CHA", "Lo", 0, none),
  ("LIMBU LETTER JA", "Lo", 0, none),
  ("LIMBU LETTER JHA", "Lo", 0, none),
  ("LIMBU LETTER YAN", "Lo", 0, none),
  ("LIMBU LETTER TA", "Lo", 0, none),
  ("LIMBU LETTER THA", "Lo", 0, none),
  ("LIMBU LETTER DA", "Lo", 0, none),
  ("LIMBU LETTER DHA", "Lo", 0, none),
  ("LIMBU LETTER NA", "Lo", 0, none),
  ("LIMBU LETTER PA", "Lo", 0, none),
  ("LIMBU LETTER PHA", "Lo", 0, none),
  ("LIMBU LETTER BA", "Lo", 0, none),
  ("LIMBU LETTER BHA", "Lo", 0, none),
  ("LIMBU LETTER MA", "Lo", 0, none),
  ("LIMBU LETTER YA", "Lo", 0, none),
  ("LIMBU LETTER RA", "Lo", 0, none),
  ("LIMBU LETTER LA", "Lo", 0, none),
  ("LIMBU LETTER WA", "Lo", 0, none),
  ("LIMBU LETTER SHA", "Lo", 0, none),
  ("LIMBU LETTER SSA", "Lo", 0, none),
  ("LIMBU LETTER SA", "Lo", 0, none),
  ("LIMBU LETTER HA", "Lo", 0, none),
  ("LIMBU LETTER GYAN", "Lo", 0, none),
  ("LIMBU LETTER TRA", "Lo", 0, none),
  (),
  ("LIMBU VOWEL SIGN A", "Mn", 0, none),
  ("LIMBU VOWEL SIGN I", "Mn", 0, none),
  ("LIMBU VOWEL SIGN U", "Mn", 0, none),
  ("LIMBU VOWEL SIGN EE", "Mc", 0, none),
  ("LIMBU VOWEL SIGN AI", "Mc", 0, none),
  ("LIMBU VOWEL SIGN OO", "Mc", 0, none),
  ("LIMBU VOWEL SIGN AU", "Mc", 0, none),
  ("LIMBU VOWEL SIGN E", "Mn", 0, none),
  ("LIMBU VOWEL SIGN O", "Mn", 0, none),
  ("LIMBU SUBJOINED LETTER YA", "Mc", 0, none),
  ("LIMBU SUBJOINED LETTER RA", "Mc", 0, none),
  ("LIMBU SUBJOINED LETTER WA", "Mc", 0, none),
  (),
  (),
  (),
  (),
  ("LIMBU SMALL LETTER KA", "Mc", 0, none),
  ("LIMBU SMALL LETTER NGA", "Mc", 0, none),
  ("LIMBU SMALL LETTER ANUSVARA", "Mn", 0, none),
  ("LIMBU SMALL LETTER TA", "Mc", 0, none),
  ("LIMBU SMALL LETTER NA", "Mc", 0, none),
  ("LIMBU SMALL LETTER PA", "Mc", 0, none),
  ("LIMBU SMALL LETTER MA", "Mc", 0, none),
  ("LIMBU SMALL LETTER RA", "Mc", 0, none),
  ("LIMBU SMALL LETTER LA", "Mc", 0, none),
  ("LIMBU SIGN MUKPHRENG", "Mn", 222, none),
  ("LIMBU SIGN KEMPHRENG", "Mn", 230, none),
  ("LIMBU SIGN SA-I", "Mn", 220, none),
  (),
  (),
  (),
  (),
  ("LIMBU SIGN LOO", "So", 0, none),
  (),
  (),
  (),
  ("LIMBU EXCLAMATION MARK", "Po", 0, none),
  ("LIMBU QUESTION MARK", "Po", 0, none),
  ("LIMBU DIGIT ZERO", "Nd", 0, none),
  ("LIMBU DIGIT ONE", "Nd", 0, none),
  ("LIMBU DIGIT TWO", "Nd", 0, none),
  ("LIMBU DIGIT THREE", "Nd", 0, none),
  ("LIMBU DIGIT FOUR", "Nd", 0, none),
  ("LIMBU DIGIT FIVE", "Nd", 0, none),
  ("LIMBU DIGIT SIX", "Nd", 0, none),
  ("LIMBU DIGIT SEVEN", "Nd", 0, none),
  ("LIMBU DIGIT EIGHT", "Nd", 0, none),
  ("LIMBU DIGIT NINE", "Nd", 0, none),
)
