#let data = (
  ("MARCHEN HEAD MARK", "Po", 0, none),
  ("MARCHEN MARK SHAD", "Po", 0, none),
  ("MARCHEN LETTER KA", "Lo", 0, none),
  ("MARCHEN LETTER KHA", "Lo", 0, none),
  ("MARCHEN LETTER GA", "Lo", 0, none),
  ("MARCHEN LETTER NGA", "Lo", 0, none),
  ("MARCHEN LETTER CA", "Lo", 0, none),
  ("MARCHEN LETTER CHA", "Lo", 0, none),
  ("MARCHEN LETTER JA", "Lo", 0, none),
  ("MARCHEN LETTER NYA", "Lo", 0, none),
  ("MARCHEN LETTER TA", "Lo", 0, none),
  ("MARCHEN LETTER THA", "Lo", 0, none),
  ("MARCHEN LETTER DA", "Lo", 0, none),
  ("MARCHEN LETTER NA", "Lo", 0, none),
  ("MARCHEN LETTER PA", "Lo", 0, none),
  ("MARCHEN LETTER PHA", "Lo", 0, none),
  ("MARCHEN LETTER BA", "Lo", 0, none),
  ("MARCHEN LETTER MA", "Lo", 0, none),
  ("MARCHEN LETTER TSA", "Lo", 0, none),
  ("MARCHEN LETTER TSHA", "Lo", 0, none),
  ("MARCHEN LETTER DZA", "Lo", 0, none),
  ("MARCHEN LETTER WA", "Lo", 0, none),
  ("MARCHEN LETTER ZHA", "Lo", 0, none),
  ("MARCHEN LETTER ZA", "Lo", 0, none),
  ("MARCHEN LETTER -A", "Lo", 0, none),
  ("MARCHEN LETTER YA", "Lo", 0, none),
  ("MARCHEN LETTER RA", "Lo", 0, none),
  ("MARCHEN LETTER LA", "Lo", 0, none),
  ("MARCHEN LETTER SHA", "Lo", 0, none),
  ("MARCHEN LETTER SA", "Lo", 0, none),
  ("MARCHEN LETTER HA", "Lo", 0, none),
  ("MARCHEN LETTER A", "Lo", 0, none),
  (),
  (),
  ("MARCHEN SUBJOINED LETTER KA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER KHA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER GA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER NGA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER CA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER CHA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER JA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER NYA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER TA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER THA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER DA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER NA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER PA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER PHA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER BA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER MA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER TSA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER TSHA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER DZA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER WA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER ZHA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER ZA", "Mn", 0, none),
  (),
  ("MARCHEN SUBJOINED LETTER YA", "Mc", 0, none),
  ("MARCHEN SUBJOINED LETTER RA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER LA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER SHA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER SA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER HA", "Mn", 0, none),
  ("MARCHEN SUBJOINED LETTER A", "Mn", 0, none),
  ("MARCHEN VOWEL SIGN AA", "Mn", 0, none),
  ("MARCHEN VOWEL SIGN I", "Mc", 0, none),
  ("MARCHEN VOWEL SIGN U", "Mn", 0, none),
  ("MARCHEN VOWEL SIGN E", "Mn", 0, none),
  ("MARCHEN VOWEL SIGN O", "Mc", 0, none),
  ("MARCHEN SIGN ANUSVARA", "Mn", 0, none),
  ("MARCHEN SIGN CANDRABINDU", "Mn", 0, none),
)
