#let data = (
  ("PALMYRENE LETTER ALEPH", "Lo", 0, none),
  ("PALMYRENE LETTER BETH", "Lo", 0, none),
  ("PALMYRENE LETTER GIMEL", "Lo", 0, none),
  ("PALMYRENE LETTER DALETH", "Lo", 0, none),
  ("PALMYRENE LETTER HE", "Lo", 0, none),
  ("PALMYRENE LETTER WAW", "Lo", 0, none),
  ("PALMYRENE LETTER ZAYIN", "Lo", 0, none),
  ("PALMYRENE LETTER HETH", "Lo", 0, none),
  ("PALMYRENE LETTER TETH", "Lo", 0, none),
  ("PALMYRENE LETTER YODH", "Lo", 0, none),
  ("PALMYRENE LETTER KAPH", "Lo", 0, none),
  ("PALMYRENE LETTER LAMEDH", "Lo", 0, none),
  ("PALMYRENE LETTER MEM", "Lo", 0, none),
  ("PALMYRENE LETTER FINAL NUN", "Lo", 0, none),
  ("PALMYRENE LETTER NUN", "Lo", 0, none),
  ("PALMYRENE LETTER SAMEKH", "Lo", 0, none),
  ("PALMYRENE LETTER AYIN", "Lo", 0, none),
  ("PALMYRENE LETTER PE", "Lo", 0, none),
  ("PALMYRENE LETTER SADHE", "Lo", 0, none),
  ("PALMYRENE LETTER QOPH", "Lo", 0, none),
  ("PALMYRENE LETTER RESH", "Lo", 0, none),
  ("PALMYRENE LETTER SHIN", "Lo", 0, none),
  ("PALMYRENE LETTER TAW", "Lo", 0, none),
  ("PALMYRENE LEFT-POINTING FLEURON", "So", 0, none),
  ("PALMYRENE RIGHT-POINTING FLEURON", "So", 0, none),
  ("PALMYRENE NUMBER ONE", "No", 0, none),
  ("PALMYRENE NUMBER TWO", "No", 0, none),
  ("PALMYRENE NUMBER THREE", "No", 0, none),
  ("PALMYRENE NUMBER FOUR", "No", 0, none),
  ("PALMYRENE NUMBER FIVE", "No", 0, none),
  ("PALMYRENE NUMBER TEN", "No", 0, none),
  ("PALMYRENE NUMBER TWENTY", "No", 0, none),
)
