#let data = (
  ("REJANG LETTER KA", "Lo", 0, none),
  ("REJANG LETTER GA", "Lo", 0, none),
  ("REJANG LETTER NGA", "Lo", 0, none),
  ("REJANG LETTER TA", "Lo", 0, none),
  ("REJANG LETTER DA", "Lo", 0, none),
  ("REJANG LETTER NA", "Lo", 0, none),
  ("REJANG LETTER PA", "Lo", 0, none),
  ("REJANG LETTER BA", "Lo", 0, none),
  ("REJANG LETTER MA", "Lo", 0, none),
  ("REJANG LETTER CA", "Lo", 0, none),
  ("REJANG LETTER JA", "Lo", 0, none),
  ("REJANG LETTER NYA", "Lo", 0, none),
  ("REJANG LETTER SA", "Lo", 0, none),
  ("REJANG LETTER RA", "Lo", 0, none),
  ("REJANG LETTER LA", "Lo", 0, none),
  ("REJANG LETTER YA", "Lo", 0, none),
  ("REJANG LETTER WA", "Lo", 0, none),
  ("REJANG LETTER HA", "Lo", 0, none),
  ("REJANG LETTER MBA", "Lo", 0, none),
  ("REJANG LETTER NGGA", "Lo", 0, none),
  ("REJANG LETTER NDA", "Lo", 0, none),
  ("REJANG LETTER NYJA", "Lo", 0, none),
  ("REJANG LETTER A", "Lo", 0, none),
  ("REJANG VOWEL SIGN I", "Mn", 0, none),
  ("REJANG VOWEL SIGN U", "Mn", 0, none),
  ("REJANG VOWEL SIGN E", "Mn", 0, none),
  ("REJANG VOWEL SIGN AI", "Mn", 0, none),
  ("REJANG VOWEL SIGN O", "Mn", 0, none),
  ("REJANG VOWEL SIGN AU", "Mn", 0, none),
  ("REJANG VOWEL SIGN EU", "Mn", 0, none),
  ("REJANG VOWEL SIGN EA", "Mn", 0, none),
  ("REJANG CONSONANT SIGN NG", "Mn", 0, none),
  ("REJANG CONSONANT SIGN N", "Mn", 0, none),
  ("REJANG CONSONANT SIGN R", "Mn", 0, none),
  ("REJANG CONSONANT SIGN H", "Mc", 0, none),
  ("REJANG VIRAMA", "Mc", 9, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("REJANG SECTION MARK", "Po", 0, none),
)
