#let data = (
  ("ELYMAIC LETTER ALEPH", "Lo", 0, none),
  ("ELYMAIC LETTER BETH", "Lo", 0, none),
  ("ELYMAIC LETTER GIMEL", "Lo", 0, none),
  ("ELYMAIC LETTER DALETH", "Lo", 0, none),
  ("ELYMAIC LETTER HE", "Lo", 0, none),
  ("ELYMAIC LETTER WAW", "Lo", 0, none),
  ("ELYMAIC LETTER ZAYIN", "Lo", 0, none),
  ("ELYMAIC LETTER HETH", "Lo", 0, none),
  ("ELYMAIC LETTER TETH", "Lo", 0, none),
  ("ELYMAIC LETTER YODH", "Lo", 0, none),
  ("ELYMAIC LETTER KAPH", "Lo", 0, none),
  ("ELYMAIC LETTER LAMEDH", "Lo", 0, none),
  ("ELYMAIC LETTER MEM", "Lo", 0, none),
  ("ELYMAIC LETTER NUN", "Lo", 0, none),
  ("ELYMAIC LETTER SAMEKH", "Lo", 0, none),
  ("ELYMAIC LETTER AYIN", "Lo", 0, none),
  ("ELYMAIC LETTER PE", "Lo", 0, none),
  ("ELYMAIC LETTER SADHE", "Lo", 0, none),
  ("ELYMAIC LETTER QOPH", "Lo", 0, none),
  ("ELYMAIC LETTER RESH", "Lo", 0, none),
  ("ELYMAIC LETTER SHIN", "Lo", 0, none),
  ("ELYMAIC LETTER TAW", "Lo", 0, none),
  ("ELYMAIC LIGATURE ZAYIN-YODH", "Lo", 0, none),
)
