#let data = (
  ("CHAKMA SIGN CANDRABINDU", "Mn", 230, none),
  ("CHAKMA SIGN ANUSVARA", "Mn", 230, none),
  ("CHAKMA SIGN VISARGA", "Mn", 230, none),
  ("CHAKMA LETTER AA", "Lo", 0, none),
  ("CHAKMA LETTER I", "Lo", 0, none),
  ("CHAKMA LETTER U", "Lo", 0, none),
  ("CHAKMA LETTER E", "Lo", 0, none),
  ("CHAKMA LETTER KAA", "Lo", 0, none),
  ("CHAKMA LETTER KHAA", "Lo", 0, none),
  ("CHAKMA LETTER GAA", "Lo", 0, none),
  ("CHAKMA LETTER GHAA", "Lo", 0, none),
  ("CHAKMA LETTER NGAA", "Lo", 0, none),
  ("CHAKMA LETTER CAA", "Lo", 0, none),
  ("CHAKMA LETTER CHAA", "Lo", 0, none),
  ("CHAKMA LETTER JAA", "Lo", 0, none),
  ("CHAKMA LETTER JHAA", "Lo", 0, none),
  ("CHAKMA LETTER NYAA", "Lo", 0, none),
  ("CHAKMA LETTER TTAA", "Lo", 0, none),
  ("CHAKMA LETTER TTHAA", "Lo", 0, none),
  ("CHAKMA LETTER DDAA", "Lo", 0, none),
  ("CHAKMA LETTER DDHAA", "Lo", 0, none),
  ("CHAKMA LETTER NNAA", "Lo", 0, none),
  ("CHAKMA LETTER TAA", "Lo", 0, none),
  ("CHAKMA LETTER THAA", "Lo", 0, none),
  ("CHAKMA LETTER DAA", "Lo", 0, none),
  ("CHAKMA LETTER DHAA", "Lo", 0, none),
  ("CHAKMA LETTER NAA", "Lo", 0, none),
  ("CHAKMA LETTER PAA", "Lo", 0, none),
  ("CHAKMA LETTER PHAA", "Lo", 0, none),
  ("CHAKMA LETTER BAA", "Lo", 0, none),
  ("CHAKMA LETTER BHAA", "Lo", 0, none),
  ("CHAKMA LETTER MAA", "Lo", 0, none),
  ("CHAKMA LETTER YYAA", "Lo", 0, none),
  ("CHAKMA LETTER YAA", "Lo", 0, none),
  ("CHAKMA LETTER RAA", "Lo", 0, none),
  ("CHAKMA LETTER LAA", "Lo", 0, none),
  ("CHAKMA LETTER WAA", "Lo", 0, none),
  ("CHAKMA LETTER SAA", "Lo", 0, none),
  ("CHAKMA LETTER HAA", "Lo", 0, none),
  ("CHAKMA VOWEL SIGN A", "Mn", 0, none),
  ("CHAKMA VOWEL SIGN I", "Mn", 0, none),
  ("CHAKMA VOWEL SIGN II", "Mn", 0, none),
  ("CHAKMA VOWEL SIGN U", "Mn", 0, none),
  ("CHAKMA VOWEL SIGN UU", "Mn", 0, none),
  ("CHAKMA VOWEL SIGN E", "Mc", 0, none),
  ("CHAKMA VOWEL SIGN AI", "Mn", 0, none),
  ("CHAKMA VOWEL SIGN O", "Mn", 0, none),
  ("CHAKMA VOWEL SIGN AU", "Mn", 0, none),
  ("CHAKMA VOWEL SIGN OI", "Mn", 0, none),
  ("CHAKMA O MARK", "Mn", 0, none),
  ("CHAKMA AU MARK", "Mn", 0, none),
  ("CHAKMA VIRAMA", "Mn", 9, none),
  ("CHAKMA MAAYYAA", "Mn", 9, none),
  (),
  ("CHAKMA DIGIT ZERO", "Nd", 0, none),
  ("CHAKMA DIGIT ONE", "Nd", 0, none),
  ("CHAKMA DIGIT TWO", "Nd", 0, none),
  ("CHAKMA DIGIT THREE", "Nd", 0, none),
  ("CHAKMA DIGIT FOUR", "Nd", 0, none),
  ("CHAKMA DIGIT FIVE", "Nd", 0, none),
  ("CHAKMA DIGIT SIX", "Nd", 0, none),
  ("CHAKMA DIGIT SEVEN", "Nd", 0, none),
  ("CHAKMA DIGIT EIGHT", "Nd", 0, none),
  ("CHAKMA DIGIT NINE", "Nd", 0, none),
  ("CHAKMA SECTION MARK", "Po", 0, none),
  ("CHAKMA DANDA", "Po", 0, none),
  ("CHAKMA DOUBLE DANDA", "Po", 0, none),
  ("CHAKMA QUESTION MARK", "Po", 0, none),
  ("CHAKMA LETTER LHAA", "Lo", 0, none),
  ("CHAKMA VOWEL SIGN AA", "Mc", 0, none),
  ("CHAKMA VOWEL SIGN EI", "Mc", 0, none),
  ("CHAKMA LETTER VAA", "Lo", 0, none),
)
