#let data = (
  ("KHMER LETTER KA", "Lo", 0, none),
  ("KHMER LETTER KHA", "Lo", 0, none),
  ("KHMER LETTER KO", "Lo", 0, none),
  ("KHMER LETTER KHO", "Lo", 0, none),
  ("KHMER LETTER NGO", "Lo", 0, none),
  ("KHMER LETTER CA", "Lo", 0, none),
  ("KHMER LETTER CHA", "Lo", 0, none),
  ("KHMER LETTER CO", "Lo", 0, none),
  ("KHMER LETTER CHO", "Lo", 0, none),
  ("KHMER LETTER NYO", "Lo", 0, none),
  ("KHMER LETTER DA", "Lo", 0, none),
  ("KHMER LETTER TTHA", "Lo", 0, none),
  ("KHMER LETTER DO", "Lo", 0, none),
  ("KHMER LETTER TTHO", "Lo", 0, none),
  ("KHMER LETTER NNO", "Lo", 0, none),
  ("KHMER LETTER TA", "Lo", 0, none),
  ("KHMER LETTER THA", "Lo", 0, none),
  ("KHMER LETTER TO", "Lo", 0, none),
  ("KHMER LETTER THO", "Lo", 0, none),
  ("KHMER LETTER NO", "Lo", 0, none),
  ("KHMER LETTER BA", "Lo", 0, none),
  ("KHMER LETTER PHA", "Lo", 0, none),
  ("KHMER LETTER PO", "Lo", 0, none),
  ("KHMER LETTER PHO", "Lo", 0, none),
  ("KHMER LETTER MO", "Lo", 0, none),
  ("KHMER LETTER YO", "Lo", 0, none),
  ("KHMER LETTER RO", "Lo", 0, none),
  ("KHMER LETTER LO", "Lo", 0, none),
  ("KHMER LETTER VO", "Lo", 0, none),
  ("KHMER LETTER SHA", "Lo", 0, none),
  ("KHMER LETTER SSO", "Lo", 0, none),
  ("KHMER LETTER SA", "Lo", 0, none),
  ("KHMER LETTER HA", "Lo", 0, none),
  ("KHMER LETTER LA", "Lo", 0, none),
  ("KHMER LETTER QA", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL QAQ", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL QAA", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL QI", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL QII", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL QU", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL QUK", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL QUU", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL QUUV", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL RY", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL RYY", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL LY", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL LYY", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL QE", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL QAI", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL QOO TYPE ONE", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL QOO TYPE TWO", "Lo", 0, none),
  ("KHMER INDEPENDENT VOWEL QAU", "Lo", 0, none),
  ("KHMER VOWEL INHERENT AQ", "Mn", 0, none),
  ("KHMER VOWEL INHERENT AA", "Mn", 0, none),
  ("KHMER VOWEL SIGN AA", "Mc", 0, none),
  ("KHMER VOWEL SIGN I", "Mn", 0, none),
  ("KHMER VOWEL SIGN II", "Mn", 0, none),
  ("KHMER VOWEL SIGN Y", "Mn", 0, none),
  ("KHMER VOWEL SIGN YY", "Mn", 0, none),
  ("KHMER VOWEL SIGN U", "Mn", 0, none),
  ("KHMER VOWEL SIGN UU", "Mn", 0, none),
  ("KHMER VOWEL SIGN UA", "Mn", 0, none),
  ("KHMER VOWEL SIGN OE", "Mc", 0, none),
  ("KHMER VOWEL SIGN YA", "Mc", 0, none),
  ("KHMER VOWEL SIGN IE", "Mc", 0, none),
  ("KHMER VOWEL SIGN E", "Mc", 0, none),
  ("KHMER VOWEL SIGN AE", "Mc", 0, none),
  ("KHMER VOWEL SIGN AI", "Mc", 0, none),
  ("KHMER VOWEL SIGN OO", "Mc", 0, none),
  ("KHMER VOWEL SIGN AU", "Mc", 0, none),
  ("KHMER SIGN NIKAHIT", "Mn", 0, none),
  ("KHMER SIGN REAHMUK", "Mc", 0, none),
  ("KHMER SIGN YUUKALEAPINTU", "Mc", 0, none),
  ("KHMER SIGN MUUSIKATOAN", "Mn", 0, none),
  ("KHMER SIGN TRIISAP", "Mn", 0, none),
  ("KHMER SIGN BANTOC", "Mn", 0, none),
  ("KHMER SIGN ROBAT", "Mn", 0, none),
  ("KHMER SIGN TOANDAKHIAT", "Mn", 0, none),
  ("KHMER SIGN KAKABAT", "Mn", 0, none),
  ("KHMER SIGN AHSDA", "Mn", 0, none),
  ("KHMER SIGN SAMYOK SANNYA", "Mn", 0, none),
  ("KHMER SIGN VIRIAM", "Mn", 0, none),
  ("KHMER SIGN COENG", "Mn", 9, none),
  ("KHMER SIGN BATHAMASAT", "Mn", 0, none),
  ("KHMER SIGN KHAN", "Po", 0, none),
  ("KHMER SIGN BARIYOOSAN", "Po", 0, none),
  ("KHMER SIGN CAMNUC PII KUUH", "Po", 0, none),
  ("KHMER SIGN LEK TOO", "Lm", 0, none),
  ("KHMER SIGN BEYYAL", "Po", 0, none),
  ("KHMER SIGN PHNAEK MUAN", "Po", 0, none),
  ("KHMER SIGN KOOMUUT", "Po", 0, none),
  ("KHMER CURRENCY SYMBOL RIEL", "Sc", 0, none),
  ("KHMER SIGN AVAKRAHASANYA", "Lo", 0, none),
  ("KHMER SIGN ATTHACAN", "Mn", 230, none),
  (),
  (),
  ("KHMER DIGIT ZERO", "Nd", 0, none),
  ("KHMER DIGIT ONE", "Nd", 0, none),
  ("KHMER DIGIT TWO", "Nd", 0, none),
  ("KHMER DIGIT THREE", "Nd", 0, none),
  ("KHMER DIGIT FOUR", "Nd", 0, none),
  ("KHMER DIGIT FIVE", "Nd", 0, none),
  ("KHMER DIGIT SIX", "Nd", 0, none),
  ("KHMER DIGIT SEVEN", "Nd", 0, none),
  ("KHMER DIGIT EIGHT", "Nd", 0, none),
  ("KHMER DIGIT NINE", "Nd", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  ("KHMER SYMBOL LEK ATTAK SON", "No", 0, none),
  ("KHMER SYMBOL LEK ATTAK MUOY", "No", 0, none),
  ("KHMER SYMBOL LEK ATTAK PII", "No", 0, none),
  ("KHMER SYMBOL LEK ATTAK BEI", "No", 0, none),
  ("KHMER SYMBOL LEK ATTAK BUON", "No", 0, none),
  ("KHMER SYMBOL LEK ATTAK PRAM", "No", 0, none),
  ("KHMER SYMBOL LEK ATTAK PRAM-MUOY", "No", 0, none),
  ("KHMER SYMBOL LEK ATTAK PRAM-PII", "No", 0, none),
  ("KHMER SYMBOL LEK ATTAK PRAM-BEI", "No", 0, none),
  ("KHMER SYMBOL LEK ATTAK PRAM-BUON", "No", 0, none),
)
