#let data = (
  ("JAVANESE SIGN PANYANGGA", "Mn", 0, none),
  ("JAVANESE SIGN CECAK", "Mn", 0, none),
  ("JAVANESE SIGN LAYAR", "Mn", 0, none),
  ("JAVANESE SIGN WIGNYAN", "Mc", 0, none),
  ("JAVANESE LETTER A", "Lo", 0, none),
  ("JAVANESE LETTER I KAWI", "Lo", 0, none),
  ("JAVANESE LETTER I", "Lo", 0, none),
  ("JAVANESE LETTER II", "Lo", 0, none),
  ("JAVANESE LETTER U", "Lo", 0, none),
  ("JAVANESE LETTER PA CEREK", "Lo", 0, none),
  ("JAVANESE LETTER NGA LELET", "Lo", 0, none),
  ("JAVANESE LETTER NGA LELET RASWADI", "Lo", 0, none),
  ("JAVANESE LETTER E", "Lo", 0, none),
  ("JAVANESE LETTER AI", "Lo", 0, none),
  ("JAVANESE LETTER O", "Lo", 0, none),
  ("JAVANESE LETTER KA", "Lo", 0, none),
  ("JAVANESE LETTER KA SASAK", "Lo", 0, none),
  ("JAVANESE LETTER KA MURDA", "Lo", 0, none),
  ("JAVANESE LETTER GA", "Lo", 0, none),
  ("JAVANESE LETTER GA MURDA", "Lo", 0, none),
  ("JAVANESE LETTER NGA", "Lo", 0, none),
  ("JAVANESE LETTER CA", "Lo", 0, none),
  ("JAVANESE LETTER CA MURDA", "Lo", 0, none),
  ("JAVANESE LETTER JA", "Lo", 0, none),
  ("JAVANESE LETTER NYA MURDA", "Lo", 0, none),
  ("JAVANESE LETTER JA MAHAPRANA", "Lo", 0, none),
  ("JAVANESE LETTER NYA", "Lo", 0, none),
  ("JAVANESE LETTER TTA", "Lo", 0, none),
  ("JAVANESE LETTER TTA MAHAPRANA", "Lo", 0, none),
  ("JAVANESE LETTER DDA", "Lo", 0, none),
  ("JAVANESE LETTER DDA MAHAPRANA", "Lo", 0, none),
  ("JAVANESE LETTER NA MURDA", "Lo", 0, none),
  ("JAVANESE LETTER TA", "Lo", 0, none),
  ("JAVANESE LETTER TA MURDA", "Lo", 0, none),
  ("JAVANESE LETTER DA", "Lo", 0, none),
  ("JAVANESE LETTER DA MAHAPRANA", "Lo", 0, none),
  ("JAVANESE LETTER NA", "Lo", 0, none),
  ("JAVANESE LETTER PA", "Lo", 0, none),
  ("JAVANESE LETTER PA MURDA", "Lo", 0, none),
  ("JAVANESE LETTER BA", "Lo", 0, none),
  ("JAVANESE LETTER BA MURDA", "Lo", 0, none),
  ("JAVANESE LETTER MA", "Lo", 0, none),
  ("JAVANESE LETTER YA", "Lo", 0, none),
  ("JAVANESE LETTER RA", "Lo", 0, none),
  ("JAVANESE LETTER RA AGUNG", "Lo", 0, none),
  ("JAVANESE LETTER LA", "Lo", 0, none),
  ("JAVANESE LETTER WA", "Lo", 0, none),
  ("JAVANESE LETTER SA MURDA", "Lo", 0, none),
  ("JAVANESE LETTER SA MAHAPRANA", "Lo", 0, none),
  ("JAVANESE LETTER SA", "Lo", 0, none),
  ("JAVANESE LETTER HA", "Lo", 0, none),
  ("JAVANESE SIGN CECAK TELU", "Mn", 7, none),
  ("JAVANESE VOWEL SIGN TARUNG", "Mc", 0, none),
  ("JAVANESE VOWEL SIGN TOLONG", "Mc", 0, none),
  ("JAVANESE VOWEL SIGN WULU", "Mn", 0, none),
  ("JAVANESE VOWEL SIGN WULU MELIK", "Mn", 0, none),
  ("JAVANESE VOWEL SIGN SUKU", "Mn", 0, none),
  ("JAVANESE VOWEL SIGN SUKU MENDUT", "Mn", 0, none),
  ("JAVANESE VOWEL SIGN TALING", "Mc", 0, none),
  ("JAVANESE VOWEL SIGN DIRGA MURE", "Mc", 0, none),
  ("JAVANESE VOWEL SIGN PEPET", "Mn", 0, none),
  ("JAVANESE CONSONANT SIGN KERET", "Mn", 0, none),
  ("JAVANESE CONSONANT SIGN PENGKAL", "Mc", 0, none),
  ("JAVANESE CONSONANT SIGN CAKRA", "Mc", 0, none),
  ("JAVANESE PANGKON", "Mc", 9, none),
  ("JAVANESE LEFT RERENGGAN", "Po", 0, none),
  ("JAVANESE RIGHT RERENGGAN", "Po", 0, none),
  ("JAVANESE PADA ANDAP", "Po", 0, none),
  ("JAVANESE PADA MADYA", "Po", 0, none),
  ("JAVANESE PADA LUHUR", "Po", 0, none),
  ("JAVANESE PADA WINDU", "Po", 0, none),
  ("JAVANESE PADA PANGKAT", "Po", 0, none),
  ("JAVANESE PADA LINGSA", "Po", 0, none),
  ("JAVANESE PADA LUNGSI", "Po", 0, none),
  ("JAVANESE PADA ADEG", "Po", 0, none),
  ("JAVANESE PADA ADEG ADEG", "Po", 0, none),
  ("JAVANESE PADA PISELEH", "Po", 0, none),
  ("JAVANESE TURNED PADA PISELEH", "Po", 0, none),
  (),
  ("JAVANESE PANGRANGKEP", "Lm", 0, none),
  ("JAVANESE DIGIT ZERO", "Nd", 0, none),
  ("JAVANESE DIGIT ONE", "Nd", 0, none),
  ("JAVANESE DIGIT TWO", "Nd", 0, none),
  ("JAVANESE DIGIT THREE", "Nd", 0, none),
  ("JAVANESE DIGIT FOUR", "Nd", 0, none),
  ("JAVANESE DIGIT FIVE", "Nd", 0, none),
  ("JAVANESE DIGIT SIX", "Nd", 0, none),
  ("JAVANESE DIGIT SEVEN", "Nd", 0, none),
  ("JAVANESE DIGIT EIGHT", "Nd", 0, none),
  ("JAVANESE DIGIT NINE", "Nd", 0, none),
  (),
  (),
  (),
  (),
  ("JAVANESE PADA TIRTA TUMETES", "Po", 0, none),
  ("JAVANESE PADA ISEN-ISEN", "Po", 0, none),
)
