#let data = (
  ("COUNTING ROD UNIT DIGIT ONE", "No", 0, none),
  ("COUNTING ROD UNIT DIGIT TWO", "No", 0, none),
  ("COUNTING ROD UNIT DIGIT THREE", "No", 0, none),
  ("COUNTING ROD UNIT DIGIT FOUR", "No", 0, none),
  ("COUNTING ROD UNIT DIGIT FIVE", "No", 0, none),
  ("COUNTING ROD UNIT DIGIT SIX", "No", 0, none),
  ("COUNTING ROD UNIT DIGIT SEVEN", "No", 0, none),
  ("COUNTING ROD UNIT DIGIT EIGHT", "No", 0, none),
  ("COUNTING ROD UNIT DIGIT NINE", "No", 0, none),
  ("COUNTING ROD TENS DIGIT ONE", "No", 0, none),
  ("COUNTING ROD TENS DIGIT TWO", "No", 0, none),
  ("COUNTING ROD TENS DIGIT THREE", "No", 0, none),
  ("COUNTING ROD TENS DIGIT FOUR", "No", 0, none),
  ("COUNTING ROD TENS DIGIT FIVE", "No", 0, none),
  ("COUNTING ROD TENS DIGIT SIX", "No", 0, none),
  ("COUNTING ROD TENS DIGIT SEVEN", "No", 0, none),
  ("COUNTING ROD TENS DIGIT EIGHT", "No", 0, none),
  ("COUNTING ROD TENS DIGIT NINE", "No", 0, none),
  ("IDEOGRAPHIC TALLY MARK ONE", "No", 0, none),
  ("IDEOGRAPHIC TALLY MARK TWO", "No", 0, none),
  ("IDEOGRAPHIC TALLY MARK THREE", "No", 0, none),
  ("IDEOGRAPHIC TALLY MARK FOUR", "No", 0, none),
  ("IDEOGRAPHIC TALLY MARK FIVE", "No", 0, none),
  ("TALLY MARK ONE", "No", 0, none),
  ("TALLY MARK FIVE", "No", 0, none),
)
