#let data = (
  ("HATRAN LETTER ALEPH", "Lo", 0, none),
  ("HATRAN LETTER BETH", "Lo", 0, none),
  ("HATRAN LETTER GIMEL", "Lo", 0, none),
  ("HATRAN LETTER DALETH-RESH", "Lo", 0, none),
  ("HATRAN LETTER HE", "Lo", 0, none),
  ("HATRAN LETTER WAW", "Lo", 0, none),
  ("HATRAN LETTER ZAYN", "Lo", 0, none),
  ("HATRAN LETTER HETH", "Lo", 0, none),
  ("HATRAN LETTER TETH", "Lo", 0, none),
  ("HATRAN LETTER YODH", "Lo", 0, none),
  ("HATRAN LETTER KAPH", "Lo", 0, none),
  ("HATRAN LETTER LAMEDH", "Lo", 0, none),
  ("HATRAN LETTER MEM", "Lo", 0, none),
  ("HATRAN LETTER NUN", "Lo", 0, none),
  ("HATRAN LETTER SAMEKH", "Lo", 0, none),
  ("HATRAN LETTER AYN", "Lo", 0, none),
  ("HATRAN LETTER PE", "Lo", 0, none),
  ("HATRAN LETTER SADHE", "Lo", 0, none),
  ("HATRAN LETTER QOPH", "Lo", 0, none),
  (),
  ("HATRAN LETTER SHIN", "Lo", 0, none),
  ("HATRAN LETTER TAW", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  ("HATRAN NUMBER ONE", "No", 0, none),
  ("HATRAN NUMBER FIVE", "No", 0, none),
  ("HATRAN NUMBER TEN", "No", 0, none),
  ("HATRAN NUMBER TWENTY", "No", 0, none),
  ("HATRAN NUMBER ONE HUNDRED", "No", 0, none),
)
