#let data = (
  ("VULGAR FRACTION ONE SEVENTH", "No", 0, none),
  ("VULGAR FRACTION ONE NINTH", "No", 0, none),
  ("VULGAR FRACTION ONE TENTH", "No", 0, none),
  ("VULGAR FRACTION ONE THIRD", "No", 0, none),
  ("VULGAR FRACTION TWO THIRDS", "No", 0, none),
  ("VULGAR FRACTION ONE FIFTH", "No", 0, none),
  ("VULGAR FRACTION TWO FIFTHS", "No", 0, none),
  ("VULGAR FRACTION THREE FIFTHS", "No", 0, none),
  ("VULGAR FRACTION FOUR FIFTHS", "No", 0, none),
  ("VULGAR FRACTION ONE SIXTH", "No", 0, none),
  ("VULGAR FRACTION FIVE SIXTHS", "No", 0, none),
  ("VULGAR FRACTION ONE EIGHTH", "No", 0, none),
  ("VULGAR FRACTION THREE EIGHTHS", "No", 0, none),
  ("VULGAR FRACTION FIVE EIGHTHS", "No", 0, none),
  ("VULGAR FRACTION SEVEN EIGHTHS", "No", 0, none),
  ("FRACTION NUMERATOR ONE", "No", 0, none),
  ("ROMAN NUMERAL ONE", "Nl", 0, none),
  ("ROMAN NUMERAL TWO", "Nl", 0, none),
  ("ROMAN NUMERAL THREE", "Nl", 0, none),
  ("ROMAN NUMERAL FOUR", "Nl", 0, none),
  ("ROMAN NUMERAL FIVE", "Nl", 0, none),
  ("ROMAN NUMERAL SIX", "Nl", 0, none),
  ("ROMAN NUMERAL SEVEN", "Nl", 0, none),
  ("ROMAN NUMERAL EIGHT", "Nl", 0, none),
  ("ROMAN NUMERAL NINE", "Nl", 0, none),
  ("ROMAN NUMERAL TEN", "Nl", 0, none),
  ("ROMAN NUMERAL ELEVEN", "Nl", 0, none),
  ("ROMAN NUMERAL TWELVE", "Nl", 0, none),
  ("ROMAN NUMERAL FIFTY", "Nl", 0, none),
  ("ROMAN NUMERAL ONE HUNDRED", "Nl", 0, none),
  ("ROMAN NUMERAL FIVE HUNDRED", "Nl", 0, none),
  ("ROMAN NUMERAL ONE THOUSAND", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL ONE", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL TWO", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL THREE", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL FOUR", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL FIVE", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL SIX", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL SEVEN", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL EIGHT", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL NINE", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL TEN", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL ELEVEN", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL TWELVE", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL FIFTY", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL ONE HUNDRED", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL FIVE HUNDRED", "Nl", 0, none),
  ("SMALL ROMAN NUMERAL ONE THOUSAND", "Nl", 0, none),
  ("ROMAN NUMERAL ONE THOUSAND C D", "Nl", 0, none),
  ("ROMAN NUMERAL FIVE THOUSAND", "Nl", 0, none),
  ("ROMAN NUMERAL TEN THOUSAND", "Nl", 0, none),
  ("ROMAN NUMERAL REVERSED ONE HUNDRED", "Lu", 0, none),
  ("LATIN SMALL LETTER REVERSED C", "Ll", 0, none),
  ("ROMAN NUMERAL SIX LATE FORM", "Nl", 0, none),
  ("ROMAN NUMERAL FIFTY EARLY FORM", "Nl", 0, none),
  ("ROMAN NUMERAL FIFTY THOUSAND", "Nl", 0, none),
  ("ROMAN NUMERAL ONE HUNDRED THOUSAND", "Nl", 0, none),
  ("VULGAR FRACTION ZERO THIRDS", "No", 0, none),
  ("TURNED DIGIT TWO", "So", 0, none),
  ("TURNED DIGIT THREE", "So", 0, none),
)
