#let data = (
  ("OLD PERMIC LETTER AN", "Lo", 0, none),
  ("OLD PERMIC LETTER BUR", "Lo", 0, none),
  ("OLD PERMIC LETTER GAI", "Lo", 0, none),
  ("OLD PERMIC LETTER DOI", "Lo", 0, none),
  ("OLD PERMIC LETTER E", "Lo", 0, none),
  ("OLD PERMIC LETTER ZHOI", "Lo", 0, none),
  ("OLD PERMIC LETTER DZHOI", "Lo", 0, none),
  ("OLD PERMIC LETTER ZATA", "Lo", 0, none),
  ("OLD PERMIC LETTER DZITA", "Lo", 0, none),
  ("OLD PERMIC LETTER I", "Lo", 0, none),
  ("OLD PERMIC LETTER KOKE", "Lo", 0, none),
  ("OLD PERMIC LETTER LEI", "Lo", 0, none),
  ("OLD PERMIC LETTER MENOE", "Lo", 0, none),
  ("OLD PERMIC LETTER NENOE", "Lo", 0, none),
  ("OLD PERMIC LETTER VOOI", "Lo", 0, none),
  ("OLD PERMIC LETTER PEEI", "Lo", 0, none),
  ("OLD PERMIC LETTER REI", "Lo", 0, none),
  ("OLD PERMIC LETTER SII", "Lo", 0, none),
  ("OLD PERMIC LETTER TAI", "Lo", 0, none),
  ("OLD PERMIC LETTER U", "Lo", 0, none),
  ("OLD PERMIC LETTER CHERY", "Lo", 0, none),
  ("OLD PERMIC LETTER SHOOI", "Lo", 0, none),
  ("OLD PERMIC LETTER SHCHOOI", "Lo", 0, none),
  ("OLD PERMIC LETTER YRY", "Lo", 0, none),
  ("OLD PERMIC LETTER YERU", "Lo", 0, none),
  ("OLD PERMIC LETTER O", "Lo", 0, none),
  ("OLD PERMIC LETTER OO", "Lo", 0, none),
  ("OLD PERMIC LETTER EF", "Lo", 0, none),
  ("OLD PERMIC LETTER HA", "Lo", 0, none),
  ("OLD PERMIC LETTER TSIU", "Lo", 0, none),
  ("OLD PERMIC LETTER VER", "Lo", 0, none),
  ("OLD PERMIC LETTER YER", "Lo", 0, none),
  ("OLD PERMIC LETTER YERI", "Lo", 0, none),
  ("OLD PERMIC LETTER YAT", "Lo", 0, none),
  ("OLD PERMIC LETTER IE", "Lo", 0, none),
  ("OLD PERMIC LETTER YU", "Lo", 0, none),
  ("OLD PERMIC LETTER YA", "Lo", 0, none),
  ("OLD PERMIC LETTER IA", "Lo", 0, none),
  ("COMBINING OLD PERMIC LETTER AN", "Mn", 230, none),
  ("COMBINING OLD PERMIC LETTER DOI", "Mn", 230, none),
  ("COMBINING OLD PERMIC LETTER ZATA", "Mn", 230, none),
  ("COMBINING OLD PERMIC LETTER NENOE", "Mn", 230, none),
  ("COMBINING OLD PERMIC LETTER SII", "Mn", 230, none),
)
