#let data = (
  ("CHEROKEE LETTER A", "Lu", 0, none),
  ("CHEROKEE LETTER E", "Lu", 0, none),
  ("CHEROKEE LETTER I", "Lu", 0, none),
  ("CHEROKEE LETTER O", "Lu", 0, none),
  ("CHEROKEE LETTER U", "Lu", 0, none),
  ("CHEROKEE LETTER V", "Lu", 0, none),
  ("CHEROKEE LETTER GA", "Lu", 0, none),
  ("CHEROKEE LETTER KA", "Lu", 0, none),
  ("CHEROKEE LETTER GE", "Lu", 0, none),
  ("CHEROKEE LETTER GI", "Lu", 0, none),
  ("CHEROKEE LETTER GO", "Lu", 0, none),
  ("CHEROKEE LETTER GU", "Lu", 0, none),
  ("CHEROKEE LETTER GV", "Lu", 0, none),
  ("CHEROKEE LETTER HA", "Lu", 0, none),
  ("CHEROKEE LETTER HE", "Lu", 0, none),
  ("CHEROKEE LETTER HI", "Lu", 0, none),
  ("CHEROKEE LETTER HO", "Lu", 0, none),
  ("CHEROKEE LETTER HU", "Lu", 0, none),
  ("CHEROKEE LETTER HV", "Lu", 0, none),
  ("CHEROKEE LETTER LA", "Lu", 0, none),
  ("CHEROKEE LETTER LE", "Lu", 0, none),
  ("CHEROKEE LETTER LI", "Lu", 0, none),
  ("CHEROKEE LETTER LO", "Lu", 0, none),
  ("CHEROKEE LETTER LU", "Lu", 0, none),
  ("CHEROKEE LETTER LV", "Lu", 0, none),
  ("CHEROKEE LETTER MA", "Lu", 0, none),
  ("CHEROKEE LETTER ME", "Lu", 0, none),
  ("CHEROKEE LETTER MI", "Lu", 0, none),
  ("CHEROKEE LETTER MO", "Lu", 0, none),
  ("CHEROKEE LETTER MU", "Lu", 0, none),
  ("CHEROKEE LETTER NA", "Lu", 0, none),
  ("CHEROKEE LETTER HNA", "Lu", 0, none),
  ("CHEROKEE LETTER NAH", "Lu", 0, none),
  ("CHEROKEE LETTER NE", "Lu", 0, none),
  ("CHEROKEE LETTER NI", "Lu", 0, none),
  ("CHEROKEE LETTER NO", "Lu", 0, none),
  ("CHEROKEE LETTER NU", "Lu", 0, none),
  ("CHEROKEE LETTER NV", "Lu", 0, none),
  ("CHEROKEE LETTER QUA", "Lu", 0, none),
  ("CHEROKEE LETTER QUE", "Lu", 0, none),
  ("CHEROKEE LETTER QUI", "Lu", 0, none),
  ("CHEROKEE LETTER QUO", "Lu", 0, none),
  ("CHEROKEE LETTER QUU", "Lu", 0, none),
  ("CHEROKEE LETTER QUV", "Lu", 0, none),
  ("CHEROKEE LETTER SA", "Lu", 0, none),
  ("CHEROKEE LETTER S", "Lu", 0, none),
  ("CHEROKEE LETTER SE", "Lu", 0, none),
  ("CHEROKEE LETTER SI", "Lu", 0, none),
  ("CHEROKEE LETTER SO", "Lu", 0, none),
  ("CHEROKEE LETTER SU", "Lu", 0, none),
  ("CHEROKEE LETTER SV", "Lu", 0, none),
  ("CHEROKEE LETTER DA", "Lu", 0, none),
  ("CHEROKEE LETTER TA", "Lu", 0, none),
  ("CHEROKEE LETTER DE", "Lu", 0, none),
  ("CHEROKEE LETTER TE", "Lu", 0, none),
  ("CHEROKEE LETTER DI", "Lu", 0, none),
  ("CHEROKEE LETTER TI", "Lu", 0, none),
  ("CHEROKEE LETTER DO", "Lu", 0, none),
  ("CHEROKEE LETTER DU", "Lu", 0, none),
  ("CHEROKEE LETTER DV", "Lu", 0, none),
  ("CHEROKEE LETTER DLA", "Lu", 0, none),
  ("CHEROKEE LETTER TLA", "Lu", 0, none),
  ("CHEROKEE LETTER TLE", "Lu", 0, none),
  ("CHEROKEE LETTER TLI", "Lu", 0, none),
  ("CHEROKEE LETTER TLO", "Lu", 0, none),
  ("CHEROKEE LETTER TLU", "Lu", 0, none),
  ("CHEROKEE LETTER TLV", "Lu", 0, none),
  ("CHEROKEE LETTER TSA", "Lu", 0, none),
  ("CHEROKEE LETTER TSE", "Lu", 0, none),
  ("CHEROKEE LETTER TSI", "Lu", 0, none),
  ("CHEROKEE LETTER TSO", "Lu", 0, none),
  ("CHEROKEE LETTER TSU", "Lu", 0, none),
  ("CHEROKEE LETTER TSV", "Lu", 0, none),
  ("CHEROKEE LETTER WA", "Lu", 0, none),
  ("CHEROKEE LETTER WE", "Lu", 0, none),
  ("CHEROKEE LETTER WI", "Lu", 0, none),
  ("CHEROKEE LETTER WO", "Lu", 0, none),
  ("CHEROKEE LETTER WU", "Lu", 0, none),
  ("CHEROKEE LETTER WV", "Lu", 0, none),
  ("CHEROKEE LETTER YA", "Lu", 0, none),
  ("CHEROKEE LETTER YE", "Lu", 0, none),
  ("CHEROKEE LETTER YI", "Lu", 0, none),
  ("CHEROKEE LETTER YO", "Lu", 0, none),
  ("CHEROKEE LETTER YU", "Lu", 0, none),
  ("CHEROKEE LETTER YV", "Lu", 0, none),
  ("CHEROKEE LETTER MV", "Lu", 0, none),
  (),
  (),
  ("CHEROKEE SMALL LETTER YE", "Ll", 0, none),
  ("CHEROKEE SMALL LETTER YI", "Ll", 0, none),
  ("CHEROKEE SMALL LETTER YO", "Ll", 0, none),
  ("CHEROKEE SMALL LETTER YU", "Ll", 0, none),
  ("CHEROKEE SMALL LETTER YV", "Ll", 0, none),
  ("CHEROKEE SMALL LETTER MV", "Ll", 0, none),
)
