#let data = (
  ("MANDAIC LETTER HALQA", "Lo", 0, none),
  ("MANDAIC LETTER AB", "Lo", 0, none),
  ("MANDAIC LETTER AG", "Lo", 0, none),
  ("MANDAIC LETTER AD", "Lo", 0, none),
  ("MANDAIC LETTER AH", "Lo", 0, none),
  ("MANDAIC LETTER USHENNA", "Lo", 0, none),
  ("MANDAIC LETTER AZ", "Lo", 0, none),
  ("MANDAIC LETTER IT", "Lo", 0, none),
  ("MANDAIC LETTER ATT", "Lo", 0, none),
  ("MANDAIC LETTER AKSA", "Lo", 0, none),
  ("MANDAIC LETTER AK", "Lo", 0, none),
  ("MANDAIC LETTER AL", "Lo", 0, none),
  ("MANDAIC LETTER AM", "Lo", 0, none),
  ("MANDAIC LETTER AN", "Lo", 0, none),
  ("MANDAIC LETTER AS", "Lo", 0, none),
  ("MANDAIC LETTER IN", "Lo", 0, none),
  ("MANDAIC LETTER AP", "Lo", 0, none),
  ("MANDAIC LETTER ASZ", "Lo", 0, none),
  ("MANDAIC LETTER AQ", "Lo", 0, none),
  ("MANDAIC LETTER AR", "Lo", 0, none),
  ("MANDAIC LETTER ASH", "Lo", 0, none),
  ("MANDAIC LETTER AT", "Lo", 0, none),
  ("MANDAIC LETTER DUSHENNA", "Lo", 0, none),
  ("MANDAIC LETTER KAD", "Lo", 0, none),
  ("MANDAIC LETTER AIN", "Lo", 0, none),
  ("MANDAIC AFFRICATION MARK", "Mn", 220, none),
  ("MANDAIC VOCALIZATION MARK", "Mn", 220, none),
  ("MANDAIC GEMINATION MARK", "Mn", 220, none),
  (),
  (),
  ("MANDAIC PUNCTUATION", "Po", 0, none),
)
