#let data = (
  ("KANNADA SIGN SPACING CANDRABINDU", "Lo", 0, none),
  ("KANNADA SIGN CANDRABINDU", "Mn", 0, none),
  ("KANNADA SIGN ANUSVARA", "Mc", 0, none),
  ("KANNADA SIGN VISARGA", "Mc", 0, none),
  ("KANNADA SIGN SIDDHAM", "Po", 0, none),
  ("KANNADA LETTER A", "Lo", 0, none),
  ("KANNADA LETTER AA", "Lo", 0, none),
  ("KANNADA LETTER I", "Lo", 0, none),
  ("KANNADA LETTER II", "Lo", 0, none),
  ("KANNADA LETTER U", "Lo", 0, none),
  ("KANNADA LETTER UU", "Lo", 0, none),
  ("KANNADA LETTER VOCALIC R", "Lo", 0, none),
  ("KANNADA LETTER VOCALIC L", "Lo", 0, none),
  (),
  ("KANNADA LETTER E", "Lo", 0, none),
  ("KANNADA LETTER EE", "Lo", 0, none),
  ("KANNADA LETTER AI", "Lo", 0, none),
  (),
  ("KANNADA LETTER O", "Lo", 0, none),
  ("KANNADA LETTER OO", "Lo", 0, none),
  ("KANNADA LETTER AU", "Lo", 0, none),
  ("KANNADA LETTER KA", "Lo", 0, none),
  ("KANNADA LETTER KHA", "Lo", 0, none),
  ("KANNADA LETTER GA", "Lo", 0, none),
  ("KANNADA LETTER GHA", "Lo", 0, none),
  ("KANNADA LETTER NGA", "Lo", 0, none),
  ("KANNADA LETTER CA", "Lo", 0, none),
  ("KANNADA LETTER CHA", "Lo", 0, none),
  ("KANNADA LETTER JA", "Lo", 0, none),
  ("KANNADA LETTER JHA", "Lo", 0, none),
  ("KANNADA LETTER NYA", "Lo", 0, none),
  ("KANNADA LETTER TTA", "Lo", 0, none),
  ("KANNADA LETTER TTHA", "Lo", 0, none),
  ("KANNADA LETTER DDA", "Lo", 0, none),
  ("KANNADA LETTER DDHA", "Lo", 0, none),
  ("KANNADA LETTER NNA", "Lo", 0, none),
  ("KANNADA LETTER TA", "Lo", 0, none),
  ("KANNADA LETTER THA", "Lo", 0, none),
  ("KANNADA LETTER DA", "Lo", 0, none),
  ("KANNADA LETTER DHA", "Lo", 0, none),
  ("KANNADA LETTER NA", "Lo", 0, none),
  (),
  ("KANNADA LETTER PA", "Lo", 0, none),
  ("KANNADA LETTER PHA", "Lo", 0, none),
  ("KANNADA LETTER BA", "Lo", 0, none),
  ("KANNADA LETTER BHA", "Lo", 0, none),
  ("KANNADA LETTER MA", "Lo", 0, none),
  ("KANNADA LETTER YA", "Lo", 0, none),
  ("KANNADA LETTER RA", "Lo", 0, none),
  ("KANNADA LETTER RRA", "Lo", 0, none),
  ("KANNADA LETTER LA", "Lo", 0, none),
  ("KANNADA LETTER LLA", "Lo", 0, none),
  (),
  ("KANNADA LETTER VA", "Lo", 0, none),
  ("KANNADA LETTER SHA", "Lo", 0, none),
  ("KANNADA LETTER SSA", "Lo", 0, none),
  ("KANNADA LETTER SA", "Lo", 0, none),
  ("KANNADA LETTER HA", "Lo", 0, none),
  (),
  (),
  ("KANNADA SIGN NUKTA", "Mn", 7, none),
  ("KANNADA SIGN AVAGRAHA", "Lo", 0, none),
  ("KANNADA VOWEL SIGN AA", "Mc", 0, none),
  ("KANNADA VOWEL SIGN I", "Mn", 0, none),
  ("KANNADA VOWEL SIGN II", "Mc", 0, none),
  ("KANNADA VOWEL SIGN U", "Mc", 0, none),
  ("KANNADA VOWEL SIGN UU", "Mc", 0, none),
  ("KANNADA VOWEL SIGN VOCALIC R", "Mc", 0, none),
  ("KANNADA VOWEL SIGN VOCALIC RR", "Mc", 0, none),
  (),
  ("KANNADA VOWEL SIGN E", "Mn", 0, none),
  ("KANNADA VOWEL SIGN EE", "Mc", 0, none),
  ("KANNADA VOWEL SIGN AI", "Mc", 0, none),
  (),
  ("KANNADA VOWEL SIGN O", "Mc", 0, none),
  ("KANNADA VOWEL SIGN OO", "Mc", 0, none),
  ("KANNADA VOWEL SIGN AU", "Mn", 0, none),
  ("KANNADA SIGN VIRAMA", "Mn", 9, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("KANNADA LENGTH MARK", "Mc", 0, none),
  ("KANNADA AI LENGTH MARK", "Mc", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  ("KANNADA LETTER NAKAARA POLLU", "Lo", 0, none),
  ("KANNADA LETTER FA", "Lo", 0, none),
  (),
  ("KANNADA LETTER VOCALIC RR", "Lo", 0, none),
  ("KANNADA LETTER VOCALIC LL", "Lo", 0, none),
  ("KANNADA VOWEL SIGN VOCALIC L", "Mn", 0, none),
  ("KANNADA VOWEL SIGN VOCALIC LL", "Mn", 0, none),
  (),
  (),
  ("KANNADA DIGIT ZERO", "Nd", 0, none),
  ("KANNADA DIGIT ONE", "Nd", 0, none),
  ("KANNADA DIGIT TWO", "Nd", 0, none),
  ("KANNADA DIGIT THREE", "Nd", 0, none),
  ("KANNADA DIGIT FOUR", "Nd", 0, none),
  ("KANNADA DIGIT FIVE", "Nd", 0, none),
  ("KANNADA DIGIT SIX", "Nd", 0, none),
  ("KANNADA DIGIT SEVEN", "Nd", 0, none),
  ("KANNADA DIGIT EIGHT", "Nd", 0, none),
  ("KANNADA DIGIT NINE", "Nd", 0, none),
  (),
  ("KANNADA SIGN JIHVAMULIYA", "Lo", 0, none),
  ("KANNADA SIGN UPADHMANIYA", "Lo", 0, none),
  ("KANNADA SIGN COMBINING ANUSVARA ABOVE RIGHT", "Mc", 0, none),
)
