#let data = (
  ("TAGALOG LETTER A", "Lo", 0, none),
  ("TAGALOG LETTER I", "Lo", 0, none),
  ("TAGALOG LETTER U", "Lo", 0, none),
  ("TAGALOG LETTER KA", "Lo", 0, none),
  ("TAGALOG LETTER GA", "Lo", 0, none),
  ("TAGALOG LETTER NGA", "Lo", 0, none),
  ("TAGALOG LETTER TA", "Lo", 0, none),
  ("TAGALOG LETTER DA", "Lo", 0, none),
  ("TAGALOG LETTER NA", "Lo", 0, none),
  ("TAGALOG LETTER PA", "Lo", 0, none),
  ("TAGALOG LETTER BA", "Lo", 0, none),
  ("TAGALOG LETTER MA", "Lo", 0, none),
  ("TAGALOG LETTER YA", "Lo", 0, none),
  ("TAGALOG LETTER RA", "Lo", 0, none),
  ("TAGALOG LETTER LA", "Lo", 0, none),
  ("TAGALOG LETTER WA", "Lo", 0, none),
  ("TAGALOG LETTER SA", "Lo", 0, none),
  ("TAGALOG LETTER HA", "Lo", 0, none),
  ("TAGALOG VOWEL SIGN I", "Mn", 0, none),
  ("TAGALOG VOWEL SIGN U", "Mn", 0, none),
  ("TAGALOG SIGN VIRAMA", "Mn", 9, none),
  ("TAGALOG SIGN PAMUDPOD", "Mc", 9, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TAGALOG LETTER ARCHAIC RA", "Lo", 0, none),
)
