#let data = (
  ("YEZIDI LETTER ELIF", "Lo", 0, none),
  ("YEZIDI LETTER BE", "Lo", 0, none),
  ("YEZIDI LETTER PE", "Lo", 0, none),
  ("YEZIDI LETTER PHE", "Lo", 0, none),
  ("YEZIDI LETTER THE", "Lo", 0, none),
  ("YEZIDI LETTER SE", "Lo", 0, none),
  ("YEZIDI LETTER CIM", "Lo", 0, none),
  ("YEZIDI LETTER CHIM", "Lo", 0, none),
  ("YEZIDI LETTER CHHIM", "Lo", 0, none),
  ("YEZIDI LETTER HHA", "Lo", 0, none),
  ("YEZIDI LETTER XA", "Lo", 0, none),
  ("YEZIDI LETTER DAL", "Lo", 0, none),
  ("YEZIDI LETTER ZAL", "Lo", 0, none),
  ("YEZIDI LETTER RA", "Lo", 0, none),
  ("YEZIDI LETTER RHA", "Lo", 0, none),
  ("YEZIDI LETTER ZA", "Lo", 0, none),
  ("YEZIDI LETTER JA", "Lo", 0, none),
  ("YEZIDI LETTER SIN", "Lo", 0, none),
  ("YEZIDI LETTER SHIN", "Lo", 0, none),
  ("YEZIDI LETTER SAD", "Lo", 0, none),
  ("YEZIDI LETTER DAD", "Lo", 0, none),
  ("YEZIDI LETTER TA", "Lo", 0, none),
  ("YEZIDI LETTER ZE", "Lo", 0, none),
  ("YEZIDI LETTER EYN", "Lo", 0, none),
  ("YEZIDI LETTER XHEYN", "Lo", 0, none),
  ("YEZIDI LETTER FA", "Lo", 0, none),
  ("YEZIDI LETTER VA", "Lo", 0, none),
  ("YEZIDI LETTER VA ALTERNATE FORM", "Lo", 0, none),
  ("YEZIDI LETTER QAF", "Lo", 0, none),
  ("YEZIDI LETTER KAF", "Lo", 0, none),
  ("YEZIDI LETTER KHAF", "Lo", 0, none),
  ("YEZIDI LETTER GAF", "Lo", 0, none),
  ("YEZIDI LETTER LAM", "Lo", 0, none),
  ("YEZIDI LETTER MIM", "Lo", 0, none),
  ("YEZIDI LETTER NUN", "Lo", 0, none),
  ("YEZIDI LETTER UM", "Lo", 0, none),
  ("YEZIDI LETTER WAW", "Lo", 0, none),
  ("YEZIDI LETTER OW", "Lo", 0, none),
  ("YEZIDI LETTER EW", "Lo", 0, none),
  ("YEZIDI LETTER HAY", "Lo", 0, none),
  ("YEZIDI LETTER YOT", "Lo", 0, none),
  ("YEZIDI LETTER ET", "Lo", 0, none),
  (),
  ("YEZIDI COMBINING HAMZA MARK", "Mn", 230, none),
  ("YEZIDI COMBINING MADDA MARK", "Mn", 230, none),
  ("YEZIDI HYPHENATION MARK", "Pd", 0, none),
  (),
  (),
  ("YEZIDI LETTER LAM WITH DOT ABOVE", "Lo", 0, none),
  ("YEZIDI LETTER YOT WITH CIRCUMFLEX ABOVE", "Lo", 0, none),
)
