#let data = (
  ("NANDINAGARI LETTER A", "Lo", 0, none),
  ("NANDINAGARI LETTER AA", "Lo", 0, none),
  ("NANDINAGARI LETTER I", "Lo", 0, none),
  ("NANDINAGARI LETTER II", "Lo", 0, none),
  ("NANDINAGARI LETTER U", "Lo", 0, none),
  ("NANDINAGARI LETTER UU", "Lo", 0, none),
  ("NANDINAGARI LETTER VOCALIC R", "Lo", 0, none),
  ("NANDINAGARI LETTER VOCALIC RR", "Lo", 0, none),
  (),
  (),
  ("NANDINAGARI LETTER E", "Lo", 0, none),
  ("NANDINAGARI LETTER AI", "Lo", 0, none),
  ("NANDINAGARI LETTER O", "Lo", 0, none),
  ("NANDINAGARI LETTER AU", "Lo", 0, none),
  ("NANDINAGARI LETTER KA", "Lo", 0, none),
  ("NANDINAGARI LETTER KHA", "Lo", 0, none),
  ("NANDINAGARI LETTER GA", "Lo", 0, none),
  ("NANDINAGARI LETTER GHA", "Lo", 0, none),
  ("NANDINAGARI LETTER NGA", "Lo", 0, none),
  ("NANDINAGARI LETTER CA", "Lo", 0, none),
  ("NANDINAGARI LETTER CHA", "Lo", 0, none),
  ("NANDINAGARI LETTER JA", "Lo", 0, none),
  ("NANDINAGARI LETTER JHA", "Lo", 0, none),
  ("NANDINAGARI LETTER NYA", "Lo", 0, none),
  ("NANDINAGARI LETTER TTA", "Lo", 0, none),
  ("NANDINAGARI LETTER TTHA", "Lo", 0, none),
  ("NANDINAGARI LETTER DDA", "Lo", 0, none),
  ("NANDINAGARI LETTER DDHA", "Lo", 0, none),
  ("NANDINAGARI LETTER NNA", "Lo", 0, none),
  ("NANDINAGARI LETTER TA", "Lo", 0, none),
  ("NANDINAGARI LETTER THA", "Lo", 0, none),
  ("NANDINAGARI LETTER DA", "Lo", 0, none),
  ("NANDINAGARI LETTER DHA", "Lo", 0, none),
  ("NANDINAGARI LETTER NA", "Lo", 0, none),
  ("NANDINAGARI LETTER PA", "Lo", 0, none),
  ("NANDINAGARI LETTER PHA", "Lo", 0, none),
  ("NANDINAGARI LETTER BA", "Lo", 0, none),
  ("NANDINAGARI LETTER BHA", "Lo", 0, none),
  ("NANDINAGARI LETTER MA", "Lo", 0, none),
  ("NANDINAGARI LETTER YA", "Lo", 0, none),
  ("NANDINAGARI LETTER RA", "Lo", 0, none),
  ("NANDINAGARI LETTER LA", "Lo", 0, none),
  ("NANDINAGARI LETTER VA", "Lo", 0, none),
  ("NANDINAGARI LETTER SHA", "Lo", 0, none),
  ("NANDINAGARI LETTER SSA", "Lo", 0, none),
  ("NANDINAGARI LETTER SA", "Lo", 0, none),
  ("NANDINAGARI LETTER HA", "Lo", 0, none),
  ("NANDINAGARI LETTER LLA", "Lo", 0, none),
  ("NANDINAGARI LETTER RRA", "Lo", 0, none),
  ("NANDINAGARI VOWEL SIGN AA", "Mc", 0, none),
  ("NANDINAGARI VOWEL SIGN I", "Mc", 0, none),
  ("NANDINAGARI VOWEL SIGN II", "Mc", 0, none),
  ("NANDINAGARI VOWEL SIGN U", "Mn", 0, none),
  ("NANDINAGARI VOWEL SIGN UU", "Mn", 0, none),
  ("NANDINAGARI VOWEL SIGN VOCALIC R", "Mn", 0, none),
  ("NANDINAGARI VOWEL SIGN VOCALIC RR", "Mn", 0, none),
  (),
  (),
  ("NANDINAGARI VOWEL SIGN E", "Mn", 0, none),
  ("NANDINAGARI VOWEL SIGN AI", "Mn", 0, none),
  ("NANDINAGARI VOWEL SIGN O", "Mc", 0, none),
  ("NANDINAGARI VOWEL SIGN AU", "Mc", 0, none),
  ("NANDINAGARI SIGN ANUSVARA", "Mc", 0, none),
  ("NANDINAGARI SIGN VISARGA", "Mc", 0, none),
  ("NANDINAGARI SIGN VIRAMA", "Mn", 9, none),
  ("NANDINAGARI SIGN AVAGRAHA", "Lo", 0, none),
  ("NANDINAGARI SIGN SIDDHAM", "Po", 0, none),
  ("NANDINAGARI HEADSTROKE", "Lo", 0, none),
  ("NANDINAGARI VOWEL SIGN PRISHTHAMATRA E", "Mc", 0, none),
)
