#let data = (
  ("SORA SOMPENG LETTER SAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER TAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER BAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER CAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER DAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER GAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER MAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER NGAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER LAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER NAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER VAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER PAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER YAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER RAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER HAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER KAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER JAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER NYAH", "Lo", 0, none),
  ("SORA SOMPENG LETTER AH", "Lo", 0, none),
  ("SORA SOMPENG LETTER EEH", "Lo", 0, none),
  ("SORA SOMPENG LETTER IH", "Lo", 0, none),
  ("SORA SOMPENG LETTER UH", "Lo", 0, none),
  ("SORA SOMPENG LETTER OH", "Lo", 0, none),
  ("SORA SOMPENG LETTER EH", "Lo", 0, none),
  ("SORA SOMPENG LETTER MAE", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("SORA SOMPENG DIGIT ZERO", "Nd", 0, none),
  ("SORA SOMPENG DIGIT ONE", "Nd", 0, none),
  ("SORA SOMPENG DIGIT TWO", "Nd", 0, none),
  ("SORA SOMPENG DIGIT THREE", "Nd", 0, none),
  ("SORA SOMPENG DIGIT FOUR", "Nd", 0, none),
  ("SORA SOMPENG DIGIT FIVE", "Nd", 0, none),
  ("SORA SOMPENG DIGIT SIX", "Nd", 0, none),
  ("SORA SOMPENG DIGIT SEVEN", "Nd", 0, none),
  ("SORA SOMPENG DIGIT EIGHT", "Nd", 0, none),
  ("SORA SOMPENG DIGIT NINE", "Nd", 0, none),
)
