#let data = (
  ("TIFINAGH LETTER YA", "Lo", 0, none),
  ("TIFINAGH LETTER YAB", "Lo", 0, none),
  ("TIFINAGH LETTER YABH", "Lo", 0, none),
  ("TIFINAGH LETTER YAG", "Lo", 0, none),
  ("TIFINAGH LETTER YAGHH", "Lo", 0, none),
  ("TIFINAGH LETTER BERBER ACADEMY YAJ", "Lo", 0, none),
  ("TIFINAGH LETTER YAJ", "Lo", 0, none),
  ("TIFINAGH LETTER YAD", "Lo", 0, none),
  ("TIFINAGH LETTER YADH", "Lo", 0, none),
  ("TIFINAGH LETTER YADD", "Lo", 0, none),
  ("TIFINAGH LETTER YADDH", "Lo", 0, none),
  ("TIFINAGH LETTER YEY", "Lo", 0, none),
  ("TIFINAGH LETTER YAF", "Lo", 0, none),
  ("TIFINAGH LETTER YAK", "Lo", 0, none),
  ("TIFINAGH LETTER TUAREG YAK", "Lo", 0, none),
  ("TIFINAGH LETTER YAKHH", "Lo", 0, none),
  ("TIFINAGH LETTER YAH", "Lo", 0, none),
  ("TIFINAGH LETTER BERBER ACADEMY YAH", "Lo", 0, none),
  ("TIFINAGH LETTER TUAREG YAH", "Lo", 0, none),
  ("TIFINAGH LETTER YAHH", "Lo", 0, none),
  ("TIFINAGH LETTER YAA", "Lo", 0, none),
  ("TIFINAGH LETTER YAKH", "Lo", 0, none),
  ("TIFINAGH LETTER TUAREG YAKH", "Lo", 0, none),
  ("TIFINAGH LETTER YAQ", "Lo", 0, none),
  ("TIFINAGH LETTER TUAREG YAQ", "Lo", 0, none),
  ("TIFINAGH LETTER YI", "Lo", 0, none),
  ("TIFINAGH LETTER YAZH", "Lo", 0, none),
  ("TIFINAGH LETTER AHAGGAR YAZH", "Lo", 0, none),
  ("TIFINAGH LETTER TUAREG YAZH", "Lo", 0, none),
  ("TIFINAGH LETTER YAL", "Lo", 0, none),
  ("TIFINAGH LETTER YAM", "Lo", 0, none),
  ("TIFINAGH LETTER YAN", "Lo", 0, none),
  ("TIFINAGH LETTER TUAREG YAGN", "Lo", 0, none),
  ("TIFINAGH LETTER TUAREG YANG", "Lo", 0, none),
  ("TIFINAGH LETTER YAP", "Lo", 0, none),
  ("TIFINAGH LETTER YU", "Lo", 0, none),
  ("TIFINAGH LETTER YAR", "Lo", 0, none),
  ("TIFINAGH LETTER YARR", "Lo", 0, none),
  ("TIFINAGH LETTER YAGH", "Lo", 0, none),
  ("TIFINAGH LETTER TUAREG YAGH", "Lo", 0, none),
  ("TIFINAGH LETTER AYER YAGH", "Lo", 0, none),
  ("TIFINAGH LETTER YAS", "Lo", 0, none),
  ("TIFINAGH LETTER YASS", "Lo", 0, none),
  ("TIFINAGH LETTER YASH", "Lo", 0, none),
  ("TIFINAGH LETTER YAT", "Lo", 0, none),
  ("TIFINAGH LETTER YATH", "Lo", 0, none),
  ("TIFINAGH LETTER YACH", "Lo", 0, none),
  ("TIFINAGH LETTER YATT", "Lo", 0, none),
  ("TIFINAGH LETTER YAV", "Lo", 0, none),
  ("TIFINAGH LETTER YAW", "Lo", 0, none),
  ("TIFINAGH LETTER YAY", "Lo", 0, none),
  ("TIFINAGH LETTER YAZ", "Lo", 0, none),
  ("TIFINAGH LETTER TAWELLEMET YAZ", "Lo", 0, none),
  ("TIFINAGH LETTER YAZZ", "Lo", 0, none),
  ("TIFINAGH LETTER YE", "Lo", 0, none),
  ("TIFINAGH LETTER YO", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TIFINAGH MODIFIER LETTER LABIALIZATION MARK", "Lm", 0, none),
  ("TIFINAGH SEPARATOR MARK", "Po", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TIFINAGH CONSONANT JOINER", "Mn", 9, none),
)
