#let data = (
  ("MYANMAR LETTER KA", "Lo", 0, none),
  ("MYANMAR LETTER KHA", "Lo", 0, none),
  ("MYANMAR LETTER GA", "Lo", 0, none),
  ("MYANMAR LETTER GHA", "Lo", 0, none),
  ("MYANMAR LETTER NGA", "Lo", 0, none),
  ("MYANMAR LETTER CA", "Lo", 0, none),
  ("MYANMAR LETTER CHA", "Lo", 0, none),
  ("MYANMAR LETTER JA", "Lo", 0, none),
  ("MYANMAR LETTER JHA", "Lo", 0, none),
  ("MYANMAR LETTER NYA", "Lo", 0, none),
  ("MYANMAR LETTER NNYA", "Lo", 0, none),
  ("MYANMAR LETTER TTA", "Lo", 0, none),
  ("MYANMAR LETTER TTHA", "Lo", 0, none),
  ("MYANMAR LETTER DDA", "Lo", 0, none),
  ("MYANMAR LETTER DDHA", "Lo", 0, none),
  ("MYANMAR LETTER NNA", "Lo", 0, none),
  ("MYANMAR LETTER TA", "Lo", 0, none),
  ("MYANMAR LETTER THA", "Lo", 0, none),
  ("MYANMAR LETTER DA", "Lo", 0, none),
  ("MYANMAR LETTER DHA", "Lo", 0, none),
  ("MYANMAR LETTER NA", "Lo", 0, none),
  ("MYANMAR LETTER PA", "Lo", 0, none),
  ("MYANMAR LETTER PHA", "Lo", 0, none),
  ("MYANMAR LETTER BA", "Lo", 0, none),
  ("MYANMAR LETTER BHA", "Lo", 0, none),
  ("MYANMAR LETTER MA", "Lo", 0, none),
  ("MYANMAR LETTER YA", "Lo", 0, none),
  ("MYANMAR LETTER RA", "Lo", 0, none),
  ("MYANMAR LETTER LA", "Lo", 0, none),
  ("MYANMAR LETTER WA", "Lo", 0, none),
  ("MYANMAR LETTER SA", "Lo", 0, none),
  ("MYANMAR LETTER HA", "Lo", 0, none),
  ("MYANMAR LETTER LLA", "Lo", 0, none),
  ("MYANMAR LETTER A", "Lo", 0, none),
  ("MYANMAR LETTER SHAN A", "Lo", 0, none),
  ("MYANMAR LETTER I", "Lo", 0, none),
  ("MYANMAR LETTER II", "Lo", 0, none),
  ("MYANMAR LETTER U", "Lo", 0, none),
  ("MYANMAR LETTER UU", "Lo", 0, none),
  ("MYANMAR LETTER E", "Lo", 0, none),
  ("MYANMAR LETTER MON E", "Lo", 0, none),
  ("MYANMAR LETTER O", "Lo", 0, none),
  ("MYANMAR LETTER AU", "Lo", 0, none),
  ("MYANMAR VOWEL SIGN TALL AA", "Mc", 0, none),
  ("MYANMAR VOWEL SIGN AA", "Mc", 0, none),
  ("MYANMAR VOWEL SIGN I", "Mn", 0, none),
  ("MYANMAR VOWEL SIGN II", "Mn", 0, none),
  ("MYANMAR VOWEL SIGN U", "Mn", 0, none),
  ("MYANMAR VOWEL SIGN UU", "Mn", 0, none),
  ("MYANMAR VOWEL SIGN E", "Mc", 0, none),
  ("MYANMAR VOWEL SIGN AI", "Mn", 0, none),
  ("MYANMAR VOWEL SIGN MON II", "Mn", 0, none),
  ("MYANMAR VOWEL SIGN MON O", "Mn", 0, none),
  ("MYANMAR VOWEL SIGN E ABOVE", "Mn", 0, none),
  ("MYANMAR SIGN ANUSVARA", "Mn", 0, none),
  ("MYANMAR SIGN DOT BELOW", "Mn", 7, none),
  ("MYANMAR SIGN VISARGA", "Mc", 0, none),
  ("MYANMAR SIGN VIRAMA", "Mn", 9, none),
  ("MYANMAR SIGN ASAT", "Mn", 9, none),
  ("MYANMAR CONSONANT SIGN MEDIAL YA", "Mc", 0, none),
  ("MYANMAR CONSONANT SIGN MEDIAL RA", "Mc", 0, none),
  ("MYANMAR CONSONANT SIGN MEDIAL WA", "Mn", 0, none),
  ("MYANMAR CONSONANT SIGN MEDIAL HA", "Mn", 0, none),
  ("MYANMAR LETTER GREAT SA", "Lo", 0, none),
  ("MYANMAR DIGIT ZERO", "Nd", 0, none),
  ("MYANMAR DIGIT ONE", "Nd", 0, none),
  ("MYANMAR DIGIT TWO", "Nd", 0, none),
  ("MYANMAR DIGIT THREE", "Nd", 0, none),
  ("MYANMAR DIGIT FOUR", "Nd", 0, none),
  ("MYANMAR DIGIT FIVE", "Nd", 0, none),
  ("MYANMAR DIGIT SIX", "Nd", 0, none),
  ("MYANMAR DIGIT SEVEN", "Nd", 0, none),
  ("MYANMAR DIGIT EIGHT", "Nd", 0, none),
  ("MYANMAR DIGIT NINE", "Nd", 0, none),
  ("MYANMAR SIGN LITTLE SECTION", "Po", 0, none),
  ("MYANMAR SIGN SECTION", "Po", 0, none),
  ("MYANMAR SYMBOL LOCATIVE", "Po", 0, none),
  ("MYANMAR SYMBOL COMPLETED", "Po", 0, none),
  ("MYANMAR SYMBOL AFOREMENTIONED", "Po", 0, none),
  ("MYANMAR SYMBOL GENITIVE", "Po", 0, none),
  ("MYANMAR LETTER SHA", "Lo", 0, none),
  ("MYANMAR LETTER SSA", "Lo", 0, none),
  ("MYANMAR LETTER VOCALIC R", "Lo", 0, none),
  ("MYANMAR LETTER VOCALIC RR", "Lo", 0, none),
  ("MYANMAR LETTER VOCALIC L", "Lo", 0, none),
  ("MYANMAR LETTER VOCALIC LL", "Lo", 0, none),
  ("MYANMAR VOWEL SIGN VOCALIC R", "Mc", 0, none),
  ("MYANMAR VOWEL SIGN VOCALIC RR", "Mc", 0, none),
  ("MYANMAR VOWEL SIGN VOCALIC L", "Mn", 0, none),
  ("MYANMAR VOWEL SIGN VOCALIC LL", "Mn", 0, none),
  ("MYANMAR LETTER MON NGA", "Lo", 0, none),
  ("MYANMAR LETTER MON JHA", "Lo", 0, none),
  ("MYANMAR LETTER MON BBA", "Lo", 0, none),
  ("MYANMAR LETTER MON BBE", "Lo", 0, none),
  ("MYANMAR CONSONANT SIGN MON MEDIAL NA", "Mn", 0, none),
  ("MYANMAR CONSONANT SIGN MON MEDIAL MA", "Mn", 0, none),
  ("MYANMAR CONSONANT SIGN MON MEDIAL LA", "Mn", 0, none),
  ("MYANMAR LETTER SGAW KAREN SHA", "Lo", 0, none),
  ("MYANMAR VOWEL SIGN SGAW KAREN EU", "Mc", 0, none),
  ("MYANMAR TONE MARK SGAW KAREN HATHI", "Mc", 0, none),
  ("MYANMAR TONE MARK SGAW KAREN KE PHO", "Mc", 0, none),
  ("MYANMAR LETTER WESTERN PWO KAREN THA", "Lo", 0, none),
  ("MYANMAR LETTER WESTERN PWO KAREN PWA", "Lo", 0, none),
  ("MYANMAR VOWEL SIGN WESTERN PWO KAREN EU", "Mc", 0, none),
  ("MYANMAR VOWEL SIGN WESTERN PWO KAREN UE", "Mc", 0, none),
  ("MYANMAR SIGN WESTERN PWO KAREN TONE-1", "Mc", 0, none),
  ("MYANMAR SIGN WESTERN PWO KAREN TONE-2", "Mc", 0, none),
  ("MYANMAR SIGN WESTERN PWO KAREN TONE-3", "Mc", 0, none),
  ("MYANMAR SIGN WESTERN PWO KAREN TONE-4", "Mc", 0, none),
  ("MYANMAR SIGN WESTERN PWO KAREN TONE-5", "Mc", 0, none),
  ("MYANMAR LETTER EASTERN PWO KAREN NNA", "Lo", 0, none),
  ("MYANMAR LETTER EASTERN PWO KAREN YWA", "Lo", 0, none),
  ("MYANMAR LETTER EASTERN PWO KAREN GHWA", "Lo", 0, none),
  ("MYANMAR VOWEL SIGN GEBA KAREN I", "Mn", 0, none),
  ("MYANMAR VOWEL SIGN KAYAH OE", "Mn", 0, none),
  ("MYANMAR VOWEL SIGN KAYAH U", "Mn", 0, none),
  ("MYANMAR VOWEL SIGN KAYAH EE", "Mn", 0, none),
  ("MYANMAR LETTER SHAN KA", "Lo", 0, none),
  ("MYANMAR LETTER SHAN KHA", "Lo", 0, none),
  ("MYANMAR LETTER SHAN GA", "Lo", 0, none),
  ("MYANMAR LETTER SHAN CA", "Lo", 0, none),
  ("MYANMAR LETTER SHAN ZA", "Lo", 0, none),
  ("MYANMAR LETTER SHAN NYA", "Lo", 0, none),
  ("MYANMAR LETTER SHAN DA", "Lo", 0, none),
  ("MYANMAR LETTER SHAN NA", "Lo", 0, none),
  ("MYANMAR LETTER SHAN PHA", "Lo", 0, none),
  ("MYANMAR LETTER SHAN FA", "Lo", 0, none),
  ("MYANMAR LETTER SHAN BA", "Lo", 0, none),
  ("MYANMAR LETTER SHAN THA", "Lo", 0, none),
  ("MYANMAR LETTER SHAN HA", "Lo", 0, none),
  ("MYANMAR CONSONANT SIGN SHAN MEDIAL WA", "Mn", 0, none),
  ("MYANMAR VOWEL SIGN SHAN AA", "Mc", 0, none),
  ("MYANMAR VOWEL SIGN SHAN E", "Mc", 0, none),
  ("MYANMAR VOWEL SIGN SHAN E ABOVE", "Mn", 0, none),
  ("MYANMAR VOWEL SIGN SHAN FINAL Y", "Mn", 0, none),
  ("MYANMAR SIGN SHAN TONE-2", "Mc", 0, none),
  ("MYANMAR SIGN SHAN TONE-3", "Mc", 0, none),
  ("MYANMAR SIGN SHAN TONE-5", "Mc", 0, none),
  ("MYANMAR SIGN SHAN TONE-6", "Mc", 0, none),
  ("MYANMAR SIGN SHAN COUNCIL TONE-2", "Mc", 0, none),
  ("MYANMAR SIGN SHAN COUNCIL TONE-3", "Mc", 0, none),
  ("MYANMAR SIGN SHAN COUNCIL EMPHATIC TONE", "Mn", 220, none),
  ("MYANMAR LETTER RUMAI PALAUNG FA", "Lo", 0, none),
  ("MYANMAR SIGN RUMAI PALAUNG TONE-5", "Mc", 0, none),
  ("MYANMAR SHAN DIGIT ZERO", "Nd", 0, none),
  ("MYANMAR SHAN DIGIT ONE", "Nd", 0, none),
  ("MYANMAR SHAN DIGIT TWO", "Nd", 0, none),
  ("MYANMAR SHAN DIGIT THREE", "Nd", 0, none),
  ("MYANMAR SHAN DIGIT FOUR", "Nd", 0, none),
  ("MYANMAR SHAN DIGIT FIVE", "Nd", 0, none),
  ("MYANMAR SHAN DIGIT SIX", "Nd", 0, none),
  ("MYANMAR SHAN DIGIT SEVEN", "Nd", 0, none),
  ("MYANMAR SHAN DIGIT EIGHT", "Nd", 0, none),
  ("MYANMAR SHAN DIGIT NINE", "Nd", 0, none),
  ("MYANMAR SIGN KHAMTI TONE-1", "Mc", 0, none),
  ("MYANMAR SIGN KHAMTI TONE-3", "Mc", 0, none),
  ("MYANMAR VOWEL SIGN AITON A", "Mc", 0, none),
  ("MYANMAR VOWEL SIGN AITON AI", "Mn", 0, none),
  ("MYANMAR SYMBOL SHAN ONE", "So", 0, none),
  ("MYANMAR SYMBOL SHAN EXCLAMATION", "So", 0, none),
)
