#let data = (
  ("HANIFI ROHINGYA LETTER A", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER BA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER PA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER TA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER TTA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER JA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER CA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER HA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER KHA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER FA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER DA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER DDA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER RA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER RRA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER ZA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER SA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER SHA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER KA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER GA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER LA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER MA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER NA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER WA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER KINNA WA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER YA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER KINNA YA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER NGA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER NYA", "Lo", 0, none),
  ("HANIFI ROHINGYA LETTER VA", "Lo", 0, none),
  ("HANIFI ROHINGYA VOWEL A", "Lo", 0, none),
  ("HANIFI ROHINGYA VOWEL I", "Lo", 0, none),
  ("HANIFI ROHINGYA VOWEL U", "Lo", 0, none),
  ("HANIFI ROHINGYA VOWEL E", "Lo", 0, none),
  ("HANIFI ROHINGYA VOWEL O", "Lo", 0, none),
  ("HANIFI ROHINGYA MARK SAKIN", "Lo", 0, none),
  ("HANIFI ROHINGYA MARK NA KHONNA", "Lo", 0, none),
  ("HANIFI ROHINGYA SIGN HARBAHAY", "Mn", 230, none),
  ("HANIFI ROHINGYA SIGN TAHALA", "Mn", 230, none),
  ("HANIFI ROHINGYA SIGN TANA", "Mn", 230, none),
  ("HANIFI ROHINGYA SIGN TASSI", "Mn", 230, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("HANIFI ROHINGYA DIGIT ZERO", "Nd", 0, none),
  ("HANIFI ROHINGYA DIGIT ONE", "Nd", 0, none),
  ("HANIFI ROHINGYA DIGIT TWO", "Nd", 0, none),
  ("HANIFI ROHINGYA DIGIT THREE", "Nd", 0, none),
  ("HANIFI ROHINGYA DIGIT FOUR", "Nd", 0, none),
  ("HANIFI ROHINGYA DIGIT FIVE", "Nd", 0, none),
  ("HANIFI ROHINGYA DIGIT SIX", "Nd", 0, none),
  ("HANIFI ROHINGYA DIGIT SEVEN", "Nd", 0, none),
  ("HANIFI ROHINGYA DIGIT EIGHT", "Nd", 0, none),
  ("HANIFI ROHINGYA DIGIT NINE", "Nd", 0, none),
)
