#let data = (
  ("NABATAEAN LETTER FINAL ALEPH", "Lo", 0, none),
  ("NABATAEAN LETTER ALEPH", "Lo", 0, none),
  ("NABATAEAN LETTER FINAL BETH", "Lo", 0, none),
  ("NABATAEAN LETTER BETH", "Lo", 0, none),
  ("NABATAEAN LETTER GIMEL", "Lo", 0, none),
  ("NABATAEAN LETTER DALETH", "Lo", 0, none),
  ("NABATAEAN LETTER FINAL HE", "Lo", 0, none),
  ("NABATAEAN LETTER HE", "Lo", 0, none),
  ("NABATAEAN LETTER WAW", "Lo", 0, none),
  ("NABATAEAN LETTER ZAYIN", "Lo", 0, none),
  ("NABATAEAN LETTER HETH", "Lo", 0, none),
  ("NABATAEAN LETTER TETH", "Lo", 0, none),
  ("NABATAEAN LETTER FINAL YODH", "Lo", 0, none),
  ("NABATAEAN LETTER YODH", "Lo", 0, none),
  ("NABATAEAN LETTER FINAL KAPH", "Lo", 0, none),
  ("NABATAEAN LETTER KAPH", "Lo", 0, none),
  ("NABATAEAN LETTER FINAL LAMEDH", "Lo", 0, none),
  ("NABATAEAN LETTER LAMEDH", "Lo", 0, none),
  ("NABATAEAN LETTER FINAL MEM", "Lo", 0, none),
  ("NABATAEAN LETTER MEM", "Lo", 0, none),
  ("NABATAEAN LETTER FINAL NUN", "Lo", 0, none),
  ("NABATAEAN LETTER NUN", "Lo", 0, none),
  ("NABATAEAN LETTER SAMEKH", "Lo", 0, none),
  ("NABATAEAN LETTER AYIN", "Lo", 0, none),
  ("NABATAEAN LETTER PE", "Lo", 0, none),
  ("NABATAEAN LETTER SADHE", "Lo", 0, none),
  ("NABATAEAN LETTER QOPH", "Lo", 0, none),
  ("NABATAEAN LETTER RESH", "Lo", 0, none),
  ("NABATAEAN LETTER FINAL SHIN", "Lo", 0, none),
  ("NABATAEAN LETTER SHIN", "Lo", 0, none),
  ("NABATAEAN LETTER TAW", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("NABATAEAN NUMBER ONE", "No", 0, none),
  ("NABATAEAN NUMBER TWO", "No", 0, none),
  ("NABATAEAN NUMBER THREE", "No", 0, none),
  ("NABATAEAN NUMBER FOUR", "No", 0, none),
  ("NABATAEAN CRUCIFORM NUMBER FOUR", "No", 0, none),
  ("NABATAEAN NUMBER FIVE", "No", 0, none),
  ("NABATAEAN NUMBER TEN", "No", 0, none),
  ("NABATAEAN NUMBER TWENTY", "No", 0, none),
  ("NABATAEAN NUMBER ONE HUNDRED", "No", 0, none),
)
