#let data = (
  ("PLAYING CARD BACK", "So", 0, none),
  ("PLAYING CARD ACE OF SPADES", "So", 0, none),
  ("PLAYING CARD TWO OF SPADES", "So", 0, none),
  ("PLAYING CARD THREE OF SPADES", "So", 0, none),
  ("PLAYING CARD FOUR OF SPADES", "So", 0, none),
  ("PLAYING CARD FIVE OF SPADES", "So", 0, none),
  ("PLAYING CARD SIX OF SPADES", "So", 0, none),
  ("PLAYING CARD SEVEN OF SPADES", "So", 0, none),
  ("PLAYING CARD EIGHT OF SPADES", "So", 0, none),
  ("PLAYING CARD NINE OF SPADES", "So", 0, none),
  ("PLAYING CARD TEN OF SPADES", "So", 0, none),
  ("PLAYING CARD JACK OF SPADES", "So", 0, none),
  ("PLAYING CARD KNIGHT OF SPADES", "So", 0, none),
  ("PLAYING CARD QUEEN OF SPADES", "So", 0, none),
  ("PLAYING CARD KING OF SPADES", "So", 0, none),
  (),
  (),
  ("PLAYING CARD ACE OF HEARTS", "So", 0, none),
  ("PLAYING CARD TWO OF HEARTS", "So", 0, none),
  ("PLAYING CARD THREE OF HEARTS", "So", 0, none),
  ("PLAYING CARD FOUR OF HEARTS", "So", 0, none),
  ("PLAYING CARD FIVE OF HEARTS", "So", 0, none),
  ("PLAYING CARD SIX OF HEARTS", "So", 0, none),
  ("PLAYING CARD SEVEN OF HEARTS", "So", 0, none),
  ("PLAYING CARD EIGHT OF HEARTS", "So", 0, none),
  ("PLAYING CARD NINE OF HEARTS", "So", 0, none),
  ("PLAYING CARD TEN OF HEARTS", "So", 0, none),
  ("PLAYING CARD JACK OF HEARTS", "So", 0, none),
  ("PLAYING CARD KNIGHT OF HEARTS", "So", 0, none),
  ("PLAYING CARD QUEEN OF HEARTS", "So", 0, none),
  ("PLAYING CARD KING OF HEARTS", "So", 0, none),
  ("PLAYING CARD RED JOKER", "So", 0, none),
  (),
  ("PLAYING CARD ACE OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD TWO OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD THREE OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD FOUR OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD FIVE OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD SIX OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD SEVEN OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD EIGHT OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD NINE OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD TEN OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD JACK OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD KNIGHT OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD QUEEN OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD KING OF DIAMONDS", "So", 0, none),
  ("PLAYING CARD BLACK JOKER", "So", 0, none),
  (),
  ("PLAYING CARD ACE OF CLUBS", "So", 0, none),
  ("PLAYING CARD TWO OF CLUBS", "So", 0, none),
  ("PLAYING CARD THREE OF CLUBS", "So", 0, none),
  ("PLAYING CARD FOUR OF CLUBS", "So", 0, none),
  ("PLAYING CARD FIVE OF CLUBS", "So", 0, none),
  ("PLAYING CARD SIX OF CLUBS", "So", 0, none),
  ("PLAYING CARD SEVEN OF CLUBS", "So", 0, none),
  ("PLAYING CARD EIGHT OF CLUBS", "So", 0, none),
  ("PLAYING CARD NINE OF CLUBS", "So", 0, none),
  ("PLAYING CARD TEN OF CLUBS", "So", 0, none),
  ("PLAYING CARD JACK OF CLUBS", "So", 0, none),
  ("PLAYING CARD KNIGHT OF CLUBS", "So", 0, none),
  ("PLAYING CARD QUEEN OF CLUBS", "So", 0, none),
  ("PLAYING CARD KING OF CLUBS", "So", 0, none),
  ("PLAYING CARD WHITE JOKER", "So", 0, none),
  ("PLAYING CARD FOOL", "So", 0, none),
  ("PLAYING CARD TRUMP-1", "So", 0, none),
  ("PLAYING CARD TRUMP-2", "So", 0, none),
  ("PLAYING CARD TRUMP-3", "So", 0, none),
  ("PLAYING CARD TRUMP-4", "So", 0, none),
  ("PLAYING CARD TRUMP-5", "So", 0, none),
  ("PLAYING CARD TRUMP-6", "So", 0, none),
  ("PLAYING CARD TRUMP-7", "So", 0, none),
  ("PLAYING CARD TRUMP-8", "So", 0, none),
  ("PLAYING CARD TRUMP-9", "So", 0, none),
  ("PLAYING CARD TRUMP-10", "So", 0, none),
  ("PLAYING CARD TRUMP-11", "So", 0, none),
  ("PLAYING CARD TRUMP-12", "So", 0, none),
  ("PLAYING CARD TRUMP-13", "So", 0, none),
  ("PLAYING CARD TRUMP-14", "So", 0, none),
  ("PLAYING CARD TRUMP-15", "So", 0, none),
  ("PLAYING CARD TRUMP-16", "So", 0, none),
  ("PLAYING CARD TRUMP-17", "So", 0, none),
  ("PLAYING CARD TRUMP-18", "So", 0, none),
  ("PLAYING CARD TRUMP-19", "So", 0, none),
  ("PLAYING CARD TRUMP-20", "So", 0, none),
  ("PLAYING CARD TRUMP-21", "So", 0, none),
)
