#let data = (
  ("TELUGU SIGN COMBINING CANDRABINDU ABOVE", "Mn", 0, none),
  ("TELUGU SIGN CANDRABINDU", "Mc", 0, none),
  ("TELUGU SIGN ANUSVARA", "Mc", 0, none),
  ("TELUGU SIGN VISARGA", "Mc", 0, none),
  ("TELUGU SIGN COMBINING ANUSVARA ABOVE", "Mn", 0, none),
  ("TELUGU LETTER A", "Lo", 0, none),
  ("TELUGU LETTER AA", "Lo", 0, none),
  ("TELUGU LETTER I", "Lo", 0, none),
  ("TELUGU LETTER II", "Lo", 0, none),
  ("TELUGU LETTER U", "Lo", 0, none),
  ("TELUGU LETTER UU", "Lo", 0, none),
  ("TELUGU LETTER VOCALIC R", "Lo", 0, none),
  ("TELUGU LETTER VOCALIC L", "Lo", 0, none),
  (),
  ("TELUGU LETTER E", "Lo", 0, none),
  ("TELUGU LETTER EE", "Lo", 0, none),
  ("TELUGU LETTER AI", "Lo", 0, none),
  (),
  ("TELUGU LETTER O", "Lo", 0, none),
  ("TELUGU LETTER OO", "Lo", 0, none),
  ("TELUGU LETTER AU", "Lo", 0, none),
  ("TELUGU LETTER KA", "Lo", 0, none),
  ("TELUGU LETTER KHA", "Lo", 0, none),
  ("TELUGU LETTER GA", "Lo", 0, none),
  ("TELUGU LETTER GHA", "Lo", 0, none),
  ("TELUGU LETTER NGA", "Lo", 0, none),
  ("TELUGU LETTER CA", "Lo", 0, none),
  ("TELUGU LETTER CHA", "Lo", 0, none),
  ("TELUGU LETTER JA", "Lo", 0, none),
  ("TELUGU LETTER JHA", "Lo", 0, none),
  ("TELUGU LETTER NYA", "Lo", 0, none),
  ("TELUGU LETTER TTA", "Lo", 0, none),
  ("TELUGU LETTER TTHA", "Lo", 0, none),
  ("TELUGU LETTER DDA", "Lo", 0, none),
  ("TELUGU LETTER DDHA", "Lo", 0, none),
  ("TELUGU LETTER NNA", "Lo", 0, none),
  ("TELUGU LETTER TA", "Lo", 0, none),
  ("TELUGU LETTER THA", "Lo", 0, none),
  ("TELUGU LETTER DA", "Lo", 0, none),
  ("TELUGU LETTER DHA", "Lo", 0, none),
  ("TELUGU LETTER NA", "Lo", 0, none),
  (),
  ("TELUGU LETTER PA", "Lo", 0, none),
  ("TELUGU LETTER PHA", "Lo", 0, none),
  ("TELUGU LETTER BA", "Lo", 0, none),
  ("TELUGU LETTER BHA", "Lo", 0, none),
  ("TELUGU LETTER MA", "Lo", 0, none),
  ("TELUGU LETTER YA", "Lo", 0, none),
  ("TELUGU LETTER RA", "Lo", 0, none),
  ("TELUGU LETTER RRA", "Lo", 0, none),
  ("TELUGU LETTER LA", "Lo", 0, none),
  ("TELUGU LETTER LLA", "Lo", 0, none),
  ("TELUGU LETTER LLLA", "Lo", 0, none),
  ("TELUGU LETTER VA", "Lo", 0, none),
  ("TELUGU LETTER SHA", "Lo", 0, none),
  ("TELUGU LETTER SSA", "Lo", 0, none),
  ("TELUGU LETTER SA", "Lo", 0, none),
  ("TELUGU LETTER HA", "Lo", 0, none),
  (),
  (),
  ("TELUGU SIGN NUKTA", "Mn", 7, none),
  ("TELUGU SIGN AVAGRAHA", "Lo", 0, none),
  ("TELUGU VOWEL SIGN AA", "Mn", 0, none),
  ("TELUGU VOWEL SIGN I", "Mn", 0, none),
  ("TELUGU VOWEL SIGN II", "Mn", 0, none),
  ("TELUGU VOWEL SIGN U", "Mc", 0, none),
  ("TELUGU VOWEL SIGN UU", "Mc", 0, none),
  ("TELUGU VOWEL SIGN VOCALIC R", "Mc", 0, none),
  ("TELUGU VOWEL SIGN VOCALIC RR", "Mc", 0, none),
  (),
  ("TELUGU VOWEL SIGN E", "Mn", 0, none),
  ("TELUGU VOWEL SIGN EE", "Mn", 0, none),
  ("TELUGU VOWEL SIGN AI", "Mn", 0, none),
  (),
  ("TELUGU VOWEL SIGN O", "Mn", 0, none),
  ("TELUGU VOWEL SIGN OO", "Mn", 0, none),
  ("TELUGU VOWEL SIGN AU", "Mn", 0, none),
  ("TELUGU SIGN VIRAMA", "Mn", 9, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TELUGU LENGTH MARK", "Mn", 84, none),
  ("TELUGU AI LENGTH MARK", "Mn", 91, none),
  (),
  ("TELUGU LETTER TSA", "Lo", 0, none),
  ("TELUGU LETTER DZA", "Lo", 0, none),
  ("TELUGU LETTER RRRA", "Lo", 0, none),
  (),
  (),
  ("TELUGU LETTER NAKAARA POLLU", "Lo", 0, none),
  (),
  (),
  ("TELUGU LETTER VOCALIC RR", "Lo", 0, none),
  ("TELUGU LETTER VOCALIC LL", "Lo", 0, none),
  ("TELUGU VOWEL SIGN VOCALIC L", "Mn", 0, none),
  ("TELUGU VOWEL SIGN VOCALIC LL", "Mn", 0, none),
  (),
  (),
  ("TELUGU DIGIT ZERO", "Nd", 0, none),
  ("TELUGU DIGIT ONE", "Nd", 0, none),
  ("TELUGU DIGIT TWO", "Nd", 0, none),
  ("TELUGU DIGIT THREE", "Nd", 0, none),
  ("TELUGU DIGIT FOUR", "Nd", 0, none),
  ("TELUGU DIGIT FIVE", "Nd", 0, none),
  ("TELUGU DIGIT SIX", "Nd", 0, none),
  ("TELUGU DIGIT SEVEN", "Nd", 0, none),
  ("TELUGU DIGIT EIGHT", "Nd", 0, none),
  ("TELUGU DIGIT NINE", "Nd", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TELUGU SIGN SIDDHAM", "Po", 0, none),
  ("TELUGU FRACTION DIGIT ZERO FOR ODD POWERS OF FOUR", "No", 0, none),
  ("TELUGU FRACTION DIGIT ONE FOR ODD POWERS OF FOUR", "No", 0, none),
  ("TELUGU FRACTION DIGIT TWO FOR ODD POWERS OF FOUR", "No", 0, none),
  ("TELUGU FRACTION DIGIT THREE FOR ODD POWERS OF FOUR", "No", 0, none),
  ("TELUGU FRACTION DIGIT ONE FOR EVEN POWERS OF FOUR", "No", 0, none),
  ("TELUGU FRACTION DIGIT TWO FOR EVEN POWERS OF FOUR", "No", 0, none),
  ("TELUGU FRACTION DIGIT THREE FOR EVEN POWERS OF FOUR", "No", 0, none),
  ("TELUGU SIGN TUUMU", "So", 0, none),
)
