#let data = (
  ("TOTO LETTER PA", "Lo", 0, none),
  ("TOTO LETTER BA", "Lo", 0, none),
  ("TOTO LETTER TA", "Lo", 0, none),
  ("TOTO LETTER DA", "Lo", 0, none),
  ("TOTO LETTER KA", "Lo", 0, none),
  ("TOTO LETTER GA", "Lo", 0, none),
  ("TOTO LETTER MA", "Lo", 0, none),
  ("TOTO LETTER NA", "Lo", 0, none),
  ("TOTO LETTER NGA", "Lo", 0, none),
  ("TOTO LETTER SA", "Lo", 0, none),
  ("TOTO LETTER CHA", "Lo", 0, none),
  ("TOTO LETTER YA", "Lo", 0, none),
  ("TOTO LETTER WA", "Lo", 0, none),
  ("TOTO LETTER JA", "Lo", 0, none),
  ("TOTO LETTER HA", "Lo", 0, none),
  ("TOTO LETTER RA", "Lo", 0, none),
  ("TOTO LETTER LA", "Lo", 0, none),
  ("TOTO LETTER I", "Lo", 0, none),
  ("TOTO LETTER BREATHY I", "Lo", 0, none),
  ("TOTO LETTER IU", "Lo", 0, none),
  ("TOTO LETTER BREATHY IU", "Lo", 0, none),
  ("TOTO LETTER U", "Lo", 0, none),
  ("TOTO LETTER E", "Lo", 0, none),
  ("TOTO LETTER BREATHY E", "Lo", 0, none),
  ("TOTO LETTER EO", "Lo", 0, none),
  ("TOTO LETTER BREATHY EO", "Lo", 0, none),
  ("TOTO LETTER O", "Lo", 0, none),
  ("TOTO LETTER AE", "Lo", 0, none),
  ("TOTO LETTER BREATHY AE", "Lo", 0, none),
  ("TOTO LETTER A", "Lo", 0, none),
  ("TOTO SIGN RISING TONE", "Mn", 230, none),
)
