#let data = (
  ("HANUNOO LETTER A", "Lo", 0, none),
  ("HANUNOO LETTER I", "Lo", 0, none),
  ("HANUNOO LETTER U", "Lo", 0, none),
  ("HANUNOO LETTER KA", "Lo", 0, none),
  ("HANUNOO LETTER GA", "Lo", 0, none),
  ("HANUNOO LETTER NGA", "Lo", 0, none),
  ("HANUNOO LETTER TA", "Lo", 0, none),
  ("HANUNOO LETTER DA", "Lo", 0, none),
  ("HANUNOO LETTER NA", "Lo", 0, none),
  ("HANUNOO LETTER PA", "Lo", 0, none),
  ("HANUNOO LETTER BA", "Lo", 0, none),
  ("HANUNOO LETTER MA", "Lo", 0, none),
  ("HANUNOO LETTER YA", "Lo", 0, none),
  ("HANUNOO LETTER RA", "Lo", 0, none),
  ("HANUNOO LETTER LA", "Lo", 0, none),
  ("HANUNOO LETTER WA", "Lo", 0, none),
  ("HANUNOO LETTER SA", "Lo", 0, none),
  ("HANUNOO LETTER HA", "Lo", 0, none),
  ("HANUNOO VOWEL SIGN I", "Mn", 0, none),
  ("HANUNOO VOWEL SIGN U", "Mn", 0, none),
  ("HANUNOO SIGN PAMUDPOD", "Mc", 9, none),
  ("PHILIPPINE SINGLE PUNCTUATION", "Po", 0, none),
  ("PHILIPPINE DOUBLE PUNCTUATION", "Po", 0, none),
)
