#let data = (
  ("ROCKET", "So", 0, none),
  ("HELICOPTER", "So", 0, none),
  ("STEAM LOCOMOTIVE", "So", 0, none),
  ("RAILWAY CAR", "So", 0, none),
  ("HIGH-SPEED TRAIN", "So", 0, none),
  ("HIGH-SPEED TRAIN WITH BULLET NOSE", "So", 0, none),
  ("TRAIN", "So", 0, none),
  ("METRO", "So", 0, none),
  ("LIGHT RAIL", "So", 0, none),
  ("STATION", "So", 0, none),
  ("TRAM", "So", 0, none),
  ("TRAM CAR", "So", 0, none),
  ("BUS", "So", 0, none),
  ("ONCOMING BUS", "So", 0, none),
  ("TROLLEYBUS", "So", 0, none),
  ("BUS STOP", "So", 0, none),
  ("MINIBUS", "So", 0, none),
  ("AMBULANCE", "So", 0, none),
  ("FIRE ENGINE", "So", 0, none),
  ("POLICE CAR", "So", 0, none),
  ("ONCOMING POLICE CAR", "So", 0, none),
  ("TAXI", "So", 0, none),
  ("ONCOMING TAXI", "So", 0, none),
  ("AUTOMOBILE", "So", 0, none),
  ("ONCOMING AUTOMOBILE", "So", 0, none),
  ("RECREATIONAL VEHICLE", "So", 0, none),
  ("DELIVERY TRUCK", "So", 0, none),
  ("ARTICULATED LORRY", "So", 0, none),
  ("TRACTOR", "So", 0, none),
  ("MONORAIL", "So", 0, none),
  ("MOUNTAIN RAILWAY", "So", 0, none),
  ("SUSPENSION RAILWAY", "So", 0, none),
  ("MOUNTAIN CABLEWAY", "So", 0, none),
  ("AERIAL TRAMWAY", "So", 0, none),
  ("SHIP", "So", 0, none),
  ("ROWBOAT", "So", 0, none),
  ("SPEEDBOAT", "So", 0, none),
  ("HORIZONTAL TRAFFIC LIGHT", "So", 0, none),
  ("VERTICAL TRAFFIC LIGHT", "So", 0, none),
  ("CONSTRUCTION SIGN", "So", 0, none),
  ("POLICE CARS REVOLVING LIGHT", "So", 0, none),
  ("TRIANGULAR FLAG ON POST", "So", 0, none),
  ("DOOR", "So", 0, none),
  ("NO ENTRY SIGN", "So", 0, none),
  ("SMOKING SYMBOL", "So", 0, none),
  ("NO SMOKING SYMBOL", "So", 0, none),
  ("PUT LITTER IN ITS PLACE SYMBOL", "So", 0, none),
  ("DO NOT LITTER SYMBOL", "So", 0, none),
  ("POTABLE WATER SYMBOL", "So", 0, none),
  ("NON-POTABLE WATER SYMBOL", "So", 0, none),
  ("BICYCLE", "So", 0, none),
  ("NO BICYCLES", "So", 0, none),
  ("BICYCLIST", "So", 0, none),
  ("MOUNTAIN BICYCLIST", "So", 0, none),
  ("PEDESTRIAN", "So", 0, none),
  ("NO PEDESTRIANS", "So", 0, none),
  ("CHILDREN CROSSING", "So", 0, none),
  ("MENS SYMBOL", "So", 0, none),
  ("WOMENS SYMBOL", "So", 0, none),
  ("RESTROOM", "So", 0, none),
  ("BABY SYMBOL", "So", 0, none),
  ("TOILET", "So", 0, none),
  ("WATER CLOSET", "So", 0, none),
  ("SHOWER", "So", 0, none),
  ("BATH", "So", 0, none),
  ("BATHTUB", "So", 0, none),
  ("PASSPORT CONTROL", "So", 0, none),
  ("CUSTOMS", "So", 0, none),
  ("BAGGAGE CLAIM", "So", 0, none),
  ("LEFT LUGGAGE", "So", 0, none),
  ("TRIANGLE WITH ROUNDED CORNERS", "So", 0, none),
  ("PROHIBITED SIGN", "So", 0, none),
  ("CIRCLED INFORMATION SOURCE", "So", 0, none),
  ("BOYS SYMBOL", "So", 0, none),
  ("GIRLS SYMBOL", "So", 0, none),
  ("COUCH AND LAMP", "So", 0, none),
  ("SLEEPING ACCOMMODATION", "So", 0, none),
  ("SHOPPING BAGS", "So", 0, none),
  ("BELLHOP BELL", "So", 0, none),
  ("BED", "So", 0, none),
  ("PLACE OF WORSHIP", "So", 0, none),
  ("OCTAGONAL SIGN", "So", 0, none),
  ("SHOPPING TROLLEY", "So", 0, none),
  ("STUPA", "So", 0, none),
  ("PAGODA", "So", 0, none),
  ("HINDU TEMPLE", "So", 0, none),
  ("HUT", "So", 0, none),
  ("ELEVATOR", "So", 0, none),
  (),
  (),
  (),
  (),
  ("WIRELESS", "So", 0, none),
  ("PLAYGROUND SLIDE", "So", 0, none),
  ("WHEEL", "So", 0, none),
  ("RING BUOY", "So", 0, none),
  ("HAMMER AND WRENCH", "So", 0, none),
  ("SHIELD", "So", 0, none),
  ("OIL DRUM", "So", 0, none),
  ("MOTORWAY", "So", 0, none),
  ("RAILWAY TRACK", "So", 0, none),
  ("MOTOR BOAT", "So", 0, none),
  ("UP-POINTING MILITARY AIRPLANE", "So", 0, none),
  ("UP-POINTING AIRPLANE", "So", 0, none),
  ("UP-POINTING SMALL AIRPLANE", "So", 0, none),
  ("SMALL AIRPLANE", "So", 0, none),
  ("NORTHEAST-POINTING AIRPLANE", "So", 0, none),
  ("AIRPLANE DEPARTURE", "So", 0, none),
  ("AIRPLANE ARRIVING", "So", 0, none),
  (),
  (),
  (),
  ("SATELLITE", "So", 0, none),
  ("ONCOMING FIRE ENGINE", "So", 0, none),
  ("DIESEL LOCOMOTIVE", "So", 0, none),
  ("PASSENGER SHIP", "So", 0, none),
  ("SCOOTER", "So", 0, none),
  ("MOTOR SCOOTER", "So", 0, none),
  ("CANOE", "So", 0, none),
  ("SLED", "So", 0, none),
  ("FLYING SAUCER", "So", 0, none),
  ("SKATEBOARD", "So", 0, none),
  ("AUTO RICKSHAW", "So", 0, none),
  ("PICKUP TRUCK", "So", 0, none),
  ("ROLLER SKATE", "So", 0, none),
)
