#let data = (
  ("CJK RADICAL REPEAT", "So", 0, none),
  ("CJK RADICAL CLIFF", "So", 0, none),
  ("CJK RADICAL SECOND ONE", "So", 0, none),
  ("CJK RADICAL SECOND TWO", "So", 0, none),
  ("CJK RADICAL SECOND THREE", "So", 0, none),
  ("CJK RADICAL PERSON", "So", 0, none),
  ("CJK RADICAL BOX", "So", 0, none),
  ("CJK RADICAL TABLE", "So", 0, none),
  ("CJK RADICAL KNIFE ONE", "So", 0, none),
  ("CJK RADICAL KNIFE TWO", "So", 0, none),
  ("CJK RADICAL DIVINATION", "So", 0, none),
  ("CJK RADICAL SEAL", "So", 0, none),
  ("CJK RADICAL SMALL ONE", "So", 0, none),
  ("CJK RADICAL SMALL TWO", "So", 0, none),
  ("CJK RADICAL LAME ONE", "So", 0, none),
  ("CJK RADICAL LAME TWO", "So", 0, none),
  ("CJK RADICAL LAME THREE", "So", 0, none),
  ("CJK RADICAL LAME FOUR", "So", 0, none),
  ("CJK RADICAL SNAKE", "So", 0, none),
  ("CJK RADICAL THREAD", "So", 0, none),
  ("CJK RADICAL SNOUT ONE", "So", 0, none),
  ("CJK RADICAL SNOUT TWO", "So", 0, none),
  ("CJK RADICAL HEART ONE", "So", 0, none),
  ("CJK RADICAL HEART TWO", "So", 0, none),
  ("CJK RADICAL HAND", "So", 0, none),
  ("CJK RADICAL RAP", "So", 0, none),
  (),
  ("CJK RADICAL CHOKE", "So", 0, none),
  ("CJK RADICAL SUN", "So", 0, none),
  ("CJK RADICAL MOON", "So", 0, none),
  ("CJK RADICAL DEATH", "So", 0, none),
  ("CJK RADICAL MOTHER", "So", 0, none),
  ("CJK RADICAL CIVILIAN", "So", 0, none),
  ("CJK RADICAL WATER ONE", "So", 0, none),
  ("CJK RADICAL WATER TWO", "So", 0, none),
  ("CJK RADICAL FIRE", "So", 0, none),
  ("CJK RADICAL PAW ONE", "So", 0, none),
  ("CJK RADICAL PAW TWO", "So", 0, none),
  ("CJK RADICAL SIMPLIFIED HALF TREE TRUNK", "So", 0, none),
  ("CJK RADICAL COW", "So", 0, none),
  ("CJK RADICAL DOG", "So", 0, none),
  ("CJK RADICAL JADE", "So", 0, none),
  ("CJK RADICAL BOLT OF CLOTH", "So", 0, none),
  ("CJK RADICAL EYE", "So", 0, none),
  ("CJK RADICAL SPIRIT ONE", "So", 0, none),
  ("CJK RADICAL SPIRIT TWO", "So", 0, none),
  ("CJK RADICAL BAMBOO", "So", 0, none),
  ("CJK RADICAL SILK", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED SILK", "So", 0, none),
  ("CJK RADICAL NET ONE", "So", 0, none),
  ("CJK RADICAL NET TWO", "So", 0, none),
  ("CJK RADICAL NET THREE", "So", 0, none),
  ("CJK RADICAL NET FOUR", "So", 0, none),
  ("CJK RADICAL MESH", "So", 0, none),
  ("CJK RADICAL SHEEP", "So", 0, none),
  ("CJK RADICAL RAM", "So", 0, none),
  ("CJK RADICAL EWE", "So", 0, none),
  ("CJK RADICAL OLD", "So", 0, none),
  ("CJK RADICAL BRUSH ONE", "So", 0, none),
  ("CJK RADICAL BRUSH TWO", "So", 0, none),
  ("CJK RADICAL MEAT", "So", 0, none),
  ("CJK RADICAL MORTAR", "So", 0, none),
  ("CJK RADICAL GRASS ONE", "So", 0, none),
  ("CJK RADICAL GRASS TWO", "So", 0, none),
  ("CJK RADICAL GRASS THREE", "So", 0, none),
  ("CJK RADICAL TIGER", "So", 0, none),
  ("CJK RADICAL CLOTHES", "So", 0, none),
  ("CJK RADICAL WEST ONE", "So", 0, none),
  ("CJK RADICAL WEST TWO", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED SEE", "So", 0, none),
  ("CJK RADICAL SIMPLIFIED HORN", "So", 0, none),
  ("CJK RADICAL HORN", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED SPEECH", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED SHELL", "So", 0, none),
  ("CJK RADICAL FOOT", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED CART", "So", 0, none),
  ("CJK RADICAL SIMPLIFIED WALK", "So", 0, none),
  ("CJK RADICAL WALK ONE", "So", 0, none),
  ("CJK RADICAL WALK TWO", "So", 0, none),
  ("CJK RADICAL CITY", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED GOLD", "So", 0, none),
  ("CJK RADICAL LONG ONE", "So", 0, none),
  ("CJK RADICAL LONG TWO", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED LONG", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED GATE", "So", 0, none),
  ("CJK RADICAL MOUND ONE", "So", 0, none),
  ("CJK RADICAL MOUND TWO", "So", 0, none),
  ("CJK RADICAL RAIN", "So", 0, none),
  ("CJK RADICAL BLUE", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED TANNED LEATHER", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED LEAF", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED WIND", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED FLY", "So", 0, none),
  ("CJK RADICAL EAT ONE", "So", 0, none),
  ("CJK RADICAL EAT TWO", "So", 0, none),
  ("CJK RADICAL EAT THREE", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED EAT", "So", 0, none),
  ("CJK RADICAL HEAD", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED HORSE", "So", 0, none),
  ("CJK RADICAL BONE", "So", 0, none),
  ("CJK RADICAL GHOST", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED FISH", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED BIRD", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED SALT", "So", 0, none),
  ("CJK RADICAL SIMPLIFIED WHEAT", "So", 0, none),
  ("CJK RADICAL SIMPLIFIED YELLOW", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED FROG", "So", 0, none),
  ("CJK RADICAL J-SIMPLIFIED EVEN", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED EVEN", "So", 0, none),
  ("CJK RADICAL J-SIMPLIFIED TOOTH", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED TOOTH", "So", 0, none),
  ("CJK RADICAL J-SIMPLIFIED DRAGON", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED DRAGON", "So", 0, none),
  ("CJK RADICAL TURTLE", "So", 0, none),
  ("CJK RADICAL J-SIMPLIFIED TURTLE", "So", 0, none),
  ("CJK RADICAL C-SIMPLIFIED TURTLE", "So", 0, none),
)
