#let data = (
  ("CHORASMIAN LETTER ALEPH", "Lo", 0, none),
  ("CHORASMIAN LETTER SMALL ALEPH", "Lo", 0, none),
  ("CHORASMIAN LETTER BETH", "Lo", 0, none),
  ("CHORASMIAN LETTER GIMEL", "Lo", 0, none),
  ("CHORASMIAN LETTER DALETH", "Lo", 0, none),
  ("CHORASMIAN LETTER HE", "Lo", 0, none),
  ("CHORASMIAN LETTER WAW", "Lo", 0, none),
  ("CHORASMIAN LETTER CURLED WAW", "Lo", 0, none),
  ("CHORASMIAN LETTER ZAYIN", "Lo", 0, none),
  ("CHORASMIAN LETTER HETH", "Lo", 0, none),
  ("CHORASMIAN LETTER YODH", "Lo", 0, none),
  ("CHORASMIAN LETTER KAPH", "Lo", 0, none),
  ("CHORASMIAN LETTER LAMEDH", "Lo", 0, none),
  ("CHORASMIAN LETTER MEM", "Lo", 0, none),
  ("CHORASMIAN LETTER NUN", "Lo", 0, none),
  ("CHORASMIAN LETTER SAMEKH", "Lo", 0, none),
  ("CHORASMIAN LETTER AYIN", "Lo", 0, none),
  ("CHORASMIAN LETTER PE", "Lo", 0, none),
  ("CHORASMIAN LETTER RESH", "Lo", 0, none),
  ("CHORASMIAN LETTER SHIN", "Lo", 0, none),
  ("CHORASMIAN LETTER TAW", "Lo", 0, none),
  ("CHORASMIAN NUMBER ONE", "No", 0, none),
  ("CHORASMIAN NUMBER TWO", "No", 0, none),
  ("CHORASMIAN NUMBER THREE", "No", 0, none),
  ("CHORASMIAN NUMBER FOUR", "No", 0, none),
  ("CHORASMIAN NUMBER TEN", "No", 0, none),
  ("CHORASMIAN NUMBER TWENTY", "No", 0, none),
  ("CHORASMIAN NUMBER ONE HUNDRED", "No", 0, none),
)
