#import "@preview/energy-dia:0.1.0": *

#set text(lang: "en", font :"Times New Roman")

= Energy-Dia Demo Collection

This document introduces all features of the Energy-Dia library step by step. Starting from simple examples, it progresses to more complex chemically meaningful diagrams.

All diagrams can adjust size using `width` and `height` parameters.

*Note: The energy values used in the examples were generated by an LLM or adjusted for visual appeal, so their scientific accuracy is not guaranteed. Please be aware of this.*

== 1. Basics of Atomic Orbital Diagrams

=== 1.1 Simplest Example

A minimal example showing only energy levels.

#ao(
  width: 8,
  height: 6,
  (energy: -10, electrons: 0),
  (energy: -5, electrons: 0),
)

=== 1.2 Basic Example with Electrons

Energy levels containing electrons. Electrons are automatically placed.

#ao(
  width: 8,
  height: 6,
  (energy: -10, electrons: 2),
  (energy: -5, electrons: 1),
)

=== 1.3 With Captions

Display orbital names as captions.

#ao(
  width: 8,
  height: 6,
  (energy: -10, electrons: 2, caption: "1s"),
  (energy: -3, electrons: 2, caption: "2s"),
)

=== 1.4 Representing Degenerate Orbitals

Use degeneracy to represent multiple orbitals at the same energy level.

#ao(
  width: 8,
  height: 6,
  (energy: -10, electrons: 2, caption: "1s"),
  (energy: -5, electrons: 3, degeneracy: 3, caption: "2p"),
)

=== 1.5 Specifying Spin-Up Electrons

You can explicitly specify the number of spin-up electrons with the `up` parameter. If not specified, they are placed alternately automatically.

#ao(
  width: 8,
  height: 6,
  (energy: -10, electrons: 2, caption: "1s"),
  (energy: -5, electrons: 4, degeneracy: 3, up: 3, caption: "2p"),
)

=== 1.6 Displaying Atomic Name

You can display the atomic name with the `name` parameter.

#ao(
  width: 8,
  height: 8,
  name: "C",
  (energy: -10, electrons: 2, caption: "1s"),
  (energy: -3, electrons: 2, caption: "2s"),
  (energy: -1, electrons: 2, degeneracy: 3, caption: "2p"),
)

=== 1.7 Hiding Energy Values

You can hide energy value labels with `exclude_energy: true`.

#ao(
  width: 8,
  height: 8,
  name: "N",
  exclude_energy: true,
  (energy: -14, electrons: 2, caption: "1s"),
  (energy: -3, electrons: 2, caption: "2s"),
  (energy: -1, electrons: 3, degeneracy: 3, up: 3, caption: "2p"),
)

== 2. Electron Configurations of Real Atoms

=== 2.1 Hydrogen (H)

#ao(
  width: 8,
  height: 6,
  name: "H",
  (energy: -14, electrons: 1, caption: "1s"),
)

=== 2.2 Helium (He)

#ao(
  width: 8,
  height: 6,
  name: "He",
  (energy: -25, electrons: 2, caption: "1s"),
)

=== 2.3 Carbon (C)

#ao(
  width: 10,
  height: 10,
  name: "C",
  (energy: -19, electrons: 2, caption: "1s"),
  (energy: -11, electrons: 2, caption: "2s"),
  (energy: -7, electrons: 2, degeneracy: 3, caption: "2p"),
)

=== 2.4 Nitrogen (N)

Electron configuration following Hund's rule (in degenerate orbitals, electrons occupy separate orbitals).

#ao(
  width: 10,
  height: 10,
  name: "N",
  (energy: -26, electrons: 2, caption: "1s"),
  (energy: -13, electrons: 2, caption: "2s"),
  (energy: -9, electrons: 3, degeneracy: 3, up: 3, caption: "2p"),
)

=== 2.5 Oxygen (O)

#ao(
  width: 10,
  height: 10,
  name: "O",
  (energy: -32, electrons: 2, caption: "1s"),
  (energy: -16, electrons: 2, caption: "2s"),
  (energy: -12, electrons: 4, degeneracy: 3, up: 3, caption: "2p"),
)

== 3. Basics of Molecular Orbital Diagrams

=== 3.1 Simplest MO Diagram

A minimal example where one molecular orbital is formed from two atomic orbitals.

#mo(
  width: 12,
  height: 8,
  atom1: ((energy: -5, electrons: 1),),
  molecule: ((energy: -8, electrons: 2),),
  atom2: ((energy: -5, electrons: 1),),
)

=== 3.2 Bonding and Antibonding Orbitals

Display both bonding and antibonding orbitals.

#mo(
  width: 12,
  height: 8,
  atom1: ((energy: -5, electrons: 1),),
  molecule: (
    (energy: -8, electrons: 2),
    (energy: -2, electrons: 0),
  ),
  atom2: ((energy: -5, electrons: 1),),
)

=== 3.3 Connections Between Orbitals

Use labels to show correspondence between atomic and molecular orbitals.

#mo(
  width: 12,
  height: 8,
  atom1: ((energy: -5, electrons: 1, label: 1),),
  molecule: (
    (energy: -8, electrons: 2, label: 2),
    (energy: -2, electrons: 0, label: 3),
  ),
  atom2: ((energy: -5, electrons: 1, label: 4),),
  (1, 2), (1, 3), (4, 2), (4, 3)
)

=== 3.4 With Captions

Add captions to orbitals.

#mo(
  width: 12,
  height: 8,
  atom1: ((energy: -5, electrons: 1, label: 1, caption: "1s"),),
  molecule: (
    (energy: -8, electrons: 2, label: 2, caption: [$sigma$]),
    (energy: -2, electrons: 0, label: 3, caption: [$sigma^*$]),
  ),
  atom2: ((energy: -5, electrons: 1, label: 4, caption: "1s"),),
  (1, 2), (1, 3), (4, 2), (4, 3)
)

=== 3.5 Displaying Atomic and Molecular Names

Display names for left atom, central molecule, and right atom with the `names` parameter.

#mo(
  width: 12,
  height: 8,
  names: ("H", $"H"_2$, "H"),
  atom1: ((energy: -5, electrons: 1, label: 1, caption: "1s"),),
  molecule: (
    (energy: -8, electrons: 2, label: 2, caption: [$sigma$]),
    (energy: -2, electrons: 0, label: 3, caption: [$sigma^*$]),
  ),
  atom2: ((energy: -5, electrons: 1, label: 4, caption: "1s"),),
  (1, 2), (1, 3), (4, 2), (4, 3)
)

== 4. MO Diagrams of Real Molecules

=== 4.1 Helium Molecular Ion ($"He"_2^+$)

#mo(
  width: 15,
  height: 10,
  names: ("He", $"He"_2^+$, $"He"^+$),
  atom1: ((energy: -24.6, electrons: 2, label: 1, caption: "1s"),),
  molecule: (
    (energy: -27.0, electrons: 2, label: 2, caption: [$sigma_(1s)$]),
    (energy: -22.2, electrons: 1, label: 3, caption: [$sigma^*_(1s)$]),
  ),
  atom2: ((energy: -24.6, electrons: 1, label: 4, caption: "1s"),),
  (1, 2), (1, 3), (4, 2), (4, 3)
)

=== 4.2 Lithium Molecule (Li₂)

#mo(
  width: 15,
  height: 10,
  names: ("Li", $"Li"_2$, "Li"),
  atom1: (
    (energy: -5.4, electrons: 2, label: 1, caption: "1s"),
    (energy: -0.2, electrons: 1, label: 2, caption: "2s"),
  ),
  molecule: (
    (energy: -5.7, electrons: 2, label: 3, caption: [$sigma_(1s)$]),
    (energy: -5.1, electrons: 2, label: 4, caption: [$sigma^*_(1s)$]),
    (energy: -0.4, electrons: 2, label: 5, caption: [$sigma_(2s)$]),
    (energy: 0.1, electrons: 0, label: 6, caption: [$sigma^*_(2s)$]),
  ),
  atom2: (
    (energy: -5.4, electrons: 2, label: 7, caption: "1s"),
    (energy: -0.2, electrons: 1, label: 8, caption: "2s"),
  ),
  (1, 3), (1, 4), (2, 5), (2, 6),
  (7, 3), (7, 4), (8, 5), (8, 6)
)

=== 4.3 Oxygen Molecule ($"O"_2$)

A molecule with a double bond that exhibits paramagnetism. This is the complete example introduced in the README.

#mo(
  width: 15,
  height: 12,
  names: ("O", $"O"_2$, "O"),
  exclude_energy: false,
  atom1: (
    (energy: -14, electrons: 2, label: 1, caption: "2s"),
    (energy: -5, electrons: 4, degeneracy: 3, up: 3, label: 2, caption: "2p"),
  ),
  molecule: (
    (energy: -16, electrons: 2, label: 3, caption: [$sigma_(2s)$]),
    (energy: -12, electrons: 2, label: 4, caption: [$sigma^*_(2s)$]),
    (energy: -8, electrons: 2, label: 5, caption: [$sigma_(2p)$]),
    (energy: -6, electrons: 4, degeneracy: 2, label: 7, caption: [$pi_(2p)$]),
    (energy: -4, electrons: 2, degeneracy: 2, up: 2, label: 8, caption: [$pi^*_(2p)$]),
    (energy: -2, electrons: 0, label: 6, caption: [$sigma^*_(2p)$]),
  ),
  atom2: (
    (energy: -14, electrons: 2, label: 9, caption: "2s"),
    (energy: -5, electrons: 4, degeneracy: 3, up: 3, label: 10, caption: "2p"),
  ),
  (1, 3), (1, 4), (2, 5), (2, 7), (2, 8), (2, 6),
  (9, 3), (9, 4), (10, 5), (10, 7), (10, 8), (10, 6)
)

=== 4.4 Fluorine Molecule ($"F"_2$)

#mo(
  width: 15,
  height: 12,
  names: ("F", $"F"_2$, "F"),
  atom1: (
    (energy: -18, electrons: 2, label: 1, caption: "2s"),
    (energy: -8, electrons: 5, degeneracy: 3, up: 3, label: 2, caption: "2p"),
  ),
  molecule: (
    (energy: -20, electrons: 2, label: 3, caption: [$sigma_(2s)$]),
    (energy: -16, electrons: 2, label: 4, caption: [$sigma^*_(2s)$]),
    (energy: -12, electrons: 2, label: 5, caption: [$sigma_(2p)$]),
    (energy: -10, electrons: 4, degeneracy: 2, label: 6, caption: [$pi_(2p)$]),
    (energy: -6, electrons: 4, degeneracy: 2, label: 7, caption: [$pi^*_(2p)$]),
    (energy: -4, electrons: 0, label: 8, caption: [$sigma^*_(2p)$]),
  ),
  atom2: (
    (energy: -18, electrons: 2, label: 9, caption: "2s"),
    (energy: -8, electrons: 5, degeneracy: 3, up: 3, label: 10, caption: "2p"),
  ),
  (1, 3), (1, 4), (2, 5), (2, 6), (2, 7), (2, 8),
  (9, 3), (9, 4), (10, 5), (10, 6), (10, 7), (10, 8)
)

== 5. Band Structure Diagrams

=== 5.1 Basic Band Structure

Display manually entered energy levels.

#band(
  width: 8,
  height: 8,
  -5, -4, -3, 0, 1, 2
)

=== 5.2 With Energy Labels

Display energy values with `include_energy_labels: true`.

#band(
  width: 8,
  height: 8,
  include_energy_labels: true,
  -5, -4, -3, 0, 1, 2
)

=== 5.3 With Material Name

Display material name with the `name` parameter.

#band(
  width: 8,
  height: 8,
  name: "Si",
  include_energy_labels: true,
  -5, -4, -3, 0, 1, 2
)

=== 5.4 Loading from CSV Data

Load energy levels from a CSV file and display them.

#let data = csv("test.csv")
#let energies = data.map(row => float(row.at(0))).flatten()
#band(
  width: 10,
  height: 8,
  name: "Sample",
  include_energy_labels: false,
  ..energies
)

=== 5.5 Many Energy Levels

Band structures usually have many energy levels.

#band(
  width: 10,
  height: 10,
  name: "Semiconductor",
  include_energy_labels: false,
  -8, -7.8, -7.5, -7.2, -7, -6.8, -6.5, -6.2, -6,
  -5.5, -5.2, -5, -4.8, -4.5, -4.2, -4, -3.8, -3.5,
  2, 2.2, 2.5, 2.8, 3, 3.2, 3.5, 3.8, 4,
  4.5, 4.8, 5, 5.2, 5.5, 5.8, 6, 6.2, 6.5
)

== Summary

This demo introduced the following features:

*Atomic Orbital Diagrams (AO):*
- Basic energy level display
- Electron configuration
- Degenerate orbitals (degeneracy)
- Spin states (up parameter)
- Atomic name display
- Show/hide energy values

*Molecular Orbital Diagrams (MO):*
- Transition from atomic orbitals to molecular orbitals
- Connections between orbitals
- Degenerate molecular orbitals
- Display of atomic and molecular names
- Electron configurations of real molecules

*Band Structure Diagrams (Band):*
- Basic band display
- Loading data from CSV
- Show/hide energy labels
- Display of many energy levels

For detailed parameter descriptions, please refer to README.md.
