[package]
name = "clari-docs"
version = "0.1.0"
entrypoint = "lib.typ"
compiler = "0.13.0"
authors = ["Joe02exe"]
license = "MIT-0"
description = "Comprehensive and highly-customizable presentations."
repository = "https://github.com/Joe02exe/clari-slides"
keywords = ["slides", "presentation", "template", "academic", "beamer"]
categories = ["presentation", "layout", "components"]
exclude = ["thumbnail.png", ".github", "example.png"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
