/*
 * mkuipers-ulusofona
 *
 * Academic document templates for Universidade Lusófona: `ulthesis` for
 * theses/dissertations, `ulreport` for lab/course reports. Both are thin
 * wrappers around the shared engine in core.typ (page layout, header/
 * footer, theorem environments, outline/glossary machinery) — see the
 * README for how to choose between them.
 *
 * Adapted by: Martijn Kuipers (martijn.kuipers@ulusofona.pt)
 */

#import "core.typ" as core
#import "core.typ": chapter, part, appendices, my-bibliography, make-index, thmref, index, mathcal, scr, theorem, definition, corollary, proposition, notation, exercise, example, problem, vocabulary, remark
#import "@preview/acrostiche:0.7.0": *

#let ulthesis(
  title: "",
  type: "",
  subtype: "",
  subtitle: "",
  date: "",
  authors: (),
  supervisors: (),
  external: "",
  department: "Departamento de Engenharia Informática e Sistemas de Informação",
  paper-size: "a4",
  logo: none,
  cover: image("cover_image.jpg"),
  image-index: none,
  body,
  main-color: black,
  lang: "en",
  list-of-figures: true,
  list-of-tables: true,
  list-of-acronyms: true,
  glossary-data: none,
  glossary-unused: false,
  acknowledgements: none,
  abstract-en: none,
  abstract-pt: none,
  supplement-chapter: "Chapter",
  supplement-part: "Part",
  toc-depth: 2,
  font-size: 10pt,
  part-style: 0,
  lowercase-references: false) = core.uldocument(
    title: title,
    type: type,
    subtype: subtype,
    subtitle: subtitle,
    date: date,
    authors: authors,
    supervisors: supervisors,
    supervisor-label: "Orientador",
    cosupervisor-label: "Co-orientador",
    external: external,
    external-label: "Entidade Externa",
    department: department,
    paper-size: paper-size,
    logo: logo,
    cover: cover,
    image-index: image-index,
    main-color: main-color,
    lang: lang,
    list-of-figures: list-of-figures,
    list-of-tables: list-of-tables,
    list-of-acronyms: list-of-acronyms,
    glossary-data: glossary-data,
    glossary-unused: glossary-unused,
    glossary-position: "front",
    acknowledgements: acknowledgements,
    abstract-en: abstract-en,
    abstract-pt: abstract-pt,
    copyright-phrase: "esta dissertação",
    supplement-chapter: supplement-chapter,
    supplement-part: supplement-part,
    toc-depth: toc-depth,
    font-size: font-size,
    part-style: part-style,
    lowercase-references: lowercase-references,
    body,
  )

#let ulreport(
  title: "",
  type: "Relatório de Laboratório",
  subtitle: "",
  date: "",
  authors: (),
  course-unit: "",
  group: "",
  professors: (),
  external: "",
  external-label: "Entidade Externa",
  department: "Departamento de Engenharia Informática e Sistemas de Informação",
  paper-size: "a4",
  logo: none,
  cover: image("cover_image.jpg"),
  image-index: none,
  body,
  main-color: black,
  lang: "pt",
  list-of-acronyms: true,
  glossary-data: none,
  glossary-unused: false,
  supplement-chapter: "Capítulo",
  supplement-part: "Parte",
  toc-depth: 2,
  font-size: 10pt,
  part-style: 0,
  lowercase-references: false) = core.uldocument(
    title: title,
    type: type,
    subtype: "",
    subtitle: subtitle,
    date: date,
    authors: authors,
    supervisors: professors,
    supervisor-label: "Professor de UC",
    cosupervisor-label: "Professor de UC",
    course-unit: course-unit,
    group: group,
    external: external,
    external-label: external-label,
    department: department,
    paper-size: paper-size,
    logo: logo,
    cover: cover,
    image-index: image-index,
    main-color: main-color,
    lang: lang,
    list-of-figures: false,
    list-of-tables: false,
    list-of-acronyms: list-of-acronyms,
    glossary-data: glossary-data,
    glossary-unused: glossary-unused,
    glossary-position: "back",
    acknowledgements: none,
    abstract-en: none,
    abstract-pt: none,
    copyright-phrase: "este relatório",
    supplement-chapter: supplement-chapter,
    supplement-part: supplement-part,
    toc-depth: toc-depth,
    font-size: font-size,
    part-style: part-style,
    lowercase-references: lowercase-references,
    body,
  )
