// The main function of abntly: `#show: abntly` at the top of the work. It is built in parts: the layout (layout.typ:
// the page, the parts of the work, the running header, the links, the language), then the typography (fonts.typ),
// the spacing (spacing.typ) and the form of the elements (elements.typ), all in `em` of the body: 12 pt, which an
// author changes with `#set text(size: 11pt)` after `#show: abntly`, as the page with `#set page(...)`. The data of
// the work (info.typ, `config-info`) go into a state at its start, for the pages that print them, and into the
// metadata of the PDF.
#import "layout.typ": dark-indigo, layout
#import "fonts.typ": fonts
#import "spacing.typ": spacing
#import "elements.typ": elements
#import "words.typ": config-names
#import "info.typ": keywords, metadata-of, resolve, work
#import "structure.typ": nature, register-keyed, summary
#import "citations.typ": citation-systems, citations
#import "@preview/glossarium:0.5.10": make-glossary

// The defaults: `table-font-size` is a reduced body for the tables, a decision of the package (NBR 14724, 5.1, does
// not list the tables among what takes a smaller size); the numbering of the equations by chapter is a decision of
// the package too; "label" numbers only the equations that have a label, over the package equate; the citation
// systems are those of src/citations.typ; `dark-indigo` is a dark indigo (src/layout.typ). `info` is left out in a
// work without data, and `none` is refused for it.
/// Applies the ABNT formatting to the whole document. It must be used with a `show` rule at the top of the file:
/// `#show: abntly.with(info: config-info(...))`.
///
/// The function sets up the page, the margins, the fonts, the spacing, the presentation of the elements of the text,
/// the citations and the list of references. Settings that are not parameters can be changed with `set` rules after
/// the call. For example, `#set text(size: 11pt)` changes the font size, and every other size scales with it.
///
/// - body (content): Content of the work.
/// - info (dictionary): Data of the work, created with `config-info`. They are used on the cover, the title page, the
///   approval sheet and the catalog card, and written to the metadata of the PDF. Can be left out in a work without
///   those pages.
/// - lang (str): Language of the work: `"pt"` or `"en"`. Sets the hyphenation and the terms generated by the package
///   ("Capítulo", "Fonte", "Sumário"). For another language, give the terms in `names` and use `#set text(lang: "es")`
///   after the call.
/// - names (dictionary): Terms of the package to replace, created with `config-names`.
/// - two-sided (bool): If `true`, formats the work for printing on both sides of the sheet: mirrored margins, page
///   number on the outer side and primary sections starting on an odd page. In this mode, the draft stamps of the
///   catalog card and of the approval sheet are not shown.
/// - hyperlink (color, none): Colour of the links (addresses, cross-references, citations, summary and note marks).
///   Use `black` for printing or `none` to remove the links.
/// - table-font-size (length): Size of the text of the tables, in `em` of the body. The default, `10em / 12`, is 10
///   pt in a body of 12 pt. Use `1em` to keep the size of the body. A quadro always uses the size of the body.
/// - equation-numbering (str, function): Format of the numbering of the equations. `"(1.1)"` numbers by chapter and
///   `"(1)"` numbers through the work. With a letter at the end, as in `"(1.1a)"` or `"(1a)"`, the lines of one
///   equation share its number and take letters. Also accepts a function.
/// - equation-number-mode (str): Which equations are numbered. `"label"` numbers only the equations (or lines) that
///   have a label. `"line"` numbers every line; `#<equate:revoke>` at the end of a line removes its number.
/// - citation-system (str): Citation system (NBR 10520:2023): `"alf"`, author-date, as in "(Silva, 2020, p. 4)";
///   `"num"`, numeric between parentheses, as in "(1, p. 30)"; `"overcite"`, numeric as a superscript; `"ieee"`,
///   numeric between brackets, as in "[1, p. 30]". The list of references follows NBR 6023:2025 in every system.
/// -> content
#let abntly(
  body,
  info: (:),
  lang: "pt",
  names: (:),
  two-sided: false,
  hyperlink: dark-indigo,
  table-font-size: 10em / 12,
  equation-numbering: "(1.1)",
  equation-number-mode: "label",
  citation-system: "alf",
) = {
  assert(
    lang in ("pt", "en"),
    message: "abntly: lang must be \"pt\" or \"en\" (another language: its words in "
      + "`names` and `#set text(lang: ...)` after `#show: abntly`); got "
      + repr(lang),
  )
  assert(type(two-sided) == bool, message: "abntly: two-sided must be true or false; got " + repr(two-sided))
  assert(
    hyperlink == none or type(hyperlink) == color,
    message: "abntly: hyperlink must be a colour, like dark-indigo or black, or none; got " + repr(hyperlink),
  )
  assert(
    type(table-font-size) == length and table-font-size.abs == 0pt and table-font-size.em > 0,
    message: "abntly: table-font-size must be a length in em of the body, like 1em or 10em / 12; got "
      + repr(table-font-size),
  )
  assert(
    type(equation-numbering) in (str, function),
    message: "abntly: equation-numbering must be a pattern like \"(1)\" or \"(1.1)\", or a function; got "
      + repr(equation-numbering),
  )
  assert(
    equation-number-mode in ("label", "line"),
    message: "abntly: equation-number-mode must be \"label\" or \"line\"; got " + repr(equation-number-mode),
  )
  assert(
    citation-system in citation-systems,
    message: "abntly: citation-system must be \"alf\", \"num\", "
      + "\"overcite\" or \"ieee\"; got "
      + repr(citation-system),
  )
  show: layout.with(lang: lang, names: config-names(..names), two-sided: two-sided, hyperlink: hyperlink)
  show: fonts
  show: spacing
  show: elements.with(
    table-font-size: table-font-size,
    equation-numbering: equation-numbering,
    equation-number-mode: equation-number-mode,
  )
  // the calls and the list of references (NBR 10520, NBR 6023), in the system chosen (src/citations.typ)
  show: citations.with(system: citation-system)
  // the acronyms, the symbols and the terms of the glossary written with keys (`list-of-acronyms((key: "abnt",
  // ...))`), cited in the text as `@abnt`, over the package glossarium: their entries registered at the start, so
  // that the text cites those of a list that comes after it (the glossary)
  show: make-glossary
  register-keyed()
  // the entries of the summary (src/structure.typ)
  show: summary
  // the data, in the state and in the metadata of the PDF: the title, the author and the institution are known now;
  // the nature of the title page and the keywords of the abstracts only after the body runs, so the metadata come
  // inside a `context` (a `set document` there reaches the document)
  let data = resolve(info)
  work.update(data)
  context {
    let fields = metadata-of(data, nature.final(), keywords.final(), text.lang)
    set document(..fields) if fields.len() > 0
  }
  body
}
