// GENERATED by scripts/build_tokens.py from packages/tokens/tokens.toml — DO NOT EDIT
//
// SAPIANS Design Tokens
// Modern typography-driven scientific publishing & slide system
// Crisp White Edition (Google DeepMind & Apple Precision Standards)

// Core Color Palette
#let sapians-dark = rgb("161311")  // Canvas for cover/takeaway; primary text on white
#let sapians-paper = rgb("FFFFFF")  // Canvas for reading pages
#let sapians-card-bg = rgb("F8F8FA")  // Elevated card surface
#let sapians-text-dark = rgb("161311")  // Deep charcoal primary text on light canvas
#let sapians-text-light = rgb("EDEBDC")  // Text on dark canvas
#let sapians-muted-dark = rgb("6D675F")  // Subtitles, annotations, axis labels
#let sapians-muted-light = rgb("A9A498")  // Secondary text and annotations on dark canvas
#let sapians-terracotta = rgb("C96F3F")  // The only intervention color. Kickers, step numbers, accents — never body text, never fills
#let sapians-line = rgb("E5E0D8")  // Hairline rules (0.25 pt)
#let sapians-line-dark = rgb("3A342E")  // Hairline rules on dark canvas
#let sapians-code-bg = rgb("F6F5F2")  // Code containers
#let sapians-code-bg-dark = rgb("201C19")  // Dark code box background
#let sapians-blue-data = rgb("315B86")  // Primary data series
#let sapians-amber = rgb("D9822B")  // Secondary data series
#let sapians-sage = rgb("4E8752")  // Tertiary data series
#let sapians-white = rgb("FFFFFF")  // Pure white (distinct alias from paper for plot facecolors)

// Typography Font Families
#let font-sans = ("Inter", "Helvetica Neue", "Arial")
#let font-serif = ("Charter", "Times New Roman")
#let font-mono = ("JetBrains Mono", "Menlo", "Courier New")

// Calibrated Typographic Scale (16:9 Presentation: 160mm x 90mm)
#let font-size-display = 28pt  // Cover title
#let font-size-h1 = 13pt  // Slide main title
#let font-size-h2 = 10.5pt  // Secondary header
#let font-size-h3 = 8.5pt  // Hero card text
#let font-size-body = 6.8pt  // Standard slide body
#let font-size-small = 5.8pt  // Secondary annotations
#let font-size-kicker = 5.2pt  // Uppercase tracking kickers
#let font-size-code = 5.5pt  // Monospace code listings

// Slide Dimensions (16:9 Presentation Standard)
#let slide-width = 160mm
#let slide-height = 90mm
#let slide-margin-x = 10mm
#let slide-margin-y = 6mm

// Standard Radii & Precision Strokes (0.25pt Hairlines)
#let radius-sm = 1.2mm
#let radius-md = 2.0mm
#let radius-lg = 3.5mm
#let stroke-light = 0.25pt + sapians-line
#let stroke-dark = 0.25pt + sapians-line-dark
#let stroke-accent = 0.75pt + sapians-terracotta
