#{
  import "@preview/wut-thesis:0.1.0": wut-thesis, acknowledgements, figure-outline, table-outline, appendix
  import "utils.typ": flex-caption-styles, todo, glossary-outline
  import "glossary.typ": glossary
  import "@preview/glossarium:0.5.7": make-glossary, register-glossary
  import "@preview/drafting:0.2.2": note-outline, set-margin-note-defaults

  show: make-glossary
  register-glossary(glossary)
  show: flex-caption-styles


  /** Drafting

    The "draft" variable is used to change the coloring of links, show TODOs (both in
    the thesis and TODO outline), as well as DRAFT in the header and the title. This
    should be true until the final version is handed-in.

    The "in-print" variable is used to generate a PDF file for physical printing (it adds
    bigger margins on the binding part of the page and changes the numbering placement).
    It should be set to `false` unless you want to create a version of the PDF file for
    physical print, in which case set it to `true`. To prepare a PDF file for the
    final hand-in (that is to upload it to APD/onedrive) please set this variable to
    `false`. variable to false.

  **/
  let draft = true
  let in-print = false
  set-margin-note-defaults(hidden: not draft)

  /// Set the languages of your studies and thesis.
  let lang = (
    /// Language in which you studied, influences the language of the titlepage.
    studies: "pl",
    /// Language in which your thesis is written, influences the rest of the text (i.e.
    /// abstracts order, captions/references supplements, hyphenation etc).
    thesis: "en"
  )

  show: wut-thesis.with(
    draft: draft,
    in-print: in-print,
    lang: lang,
    // Adjust the following fields accordingly to your thesis
    titlepage-info: (
      thesis-type: "engineer", // or "bachelor" or "master"
      program: "Informatyka",
      specialisation: "Sztuczna Inteligencja",
      institute: "Instytut Informatyki",
      supervisor: "prof. dr hab. inż. Mittens Meowington",
      // The optional advisor of the thesis, this will be typeset as
      //  `consultation`/`konsultacje` in the titlepage.
      advisor: "Dr. Felix Pawsworth", // or `none` if there were no advisors
      faculty: "weiti", // see the tutorial section of this thesis for a list of all possible faculty shorthands
      index-number: "123456",
      date: datetime.today(), // not today: datetime(year: 1969, month: 9, day: 6,)
    ),
    // if you don't want to create a title page (e.g. if you need to use the one
    // generated by APD) then comment the above `titlepage-info` lines and instead
    // uncomment this line:
    // titlepage-info: none,
    author: "Felina Whiskerstein",
    // Note that regardless of the language of your thesis you need to fill in all the
    // fields below - both *.en and *.pl
    title: (
      en: "Purrfection: How Cats Skillfully Train and Manipulate Humans to Serve Their Every Need",
      pl: "Miauestria: Jak koty umiejętnie trenują i manipulują ludźmi w celu zaspokojenia wszystkich swoich potrzeb",
    ),
    abstract: (
      en: [
        // max 1 page
        This study explores the intricate ways in which domestic cats employ manipulation tactics to influence human behavior. Utilizing a mixed-methods approach that combines observational data, surveys, and interviews, this research investigates how cats utilize vocalizations, body language, and attention-seeking behaviors to achieve their goals, ranging from soliciting food to initiating play.

        The findings reveal that cats predominantly use vocalizations such as meowing, purring, and chirping to manipulate their human companions. Meowing is particularly effective for demanding attention and food, while purring is often used to enhance bonding and comfort. Chirps and trills are employed to encourage play and interaction. Additionally, body language such as kneading, tail positioning, and eye contact play significant roles in communication and manipulation. Attention-seeking behaviors, including climbing, rubbing, and bringing objects, are crucial in eliciting responses from humans.

        The research highlights the positive impact of these manipulation tactics on human-cat relationships, although it also acknowledges the potential for frustration and behavioral adjustments by cat owners. The study contributes valuable insights into the complexities of human-animal interactions and suggests pathways for future research, including larger sample sizes, longitudinal studies, and experimental investigations.

        This work offers practical implications for enhancing human-cat interactions and improving the understanding of feline behavior, fostering more harmonious relationships between cats and their human companions.
      ],
      pl: [
        // max 1 page
        Niniejsze badanie bada skomplikowane sposoby, w jakie koty domowe stosują taktyki manipulacji, aby wpływać na ludzkie zachowanie. Wykorzystując mieszane podejście metodologiczne, które łączy dane obserwacyjne, ankiety i wywiady, badanie to bada, w jaki sposób koty wykorzystują wokalizacje, język ciała i zachowania poszukujące uwagi, aby osiągnąć swoje cele, od zabiegania o jedzenie po inicjowanie zabawy.

        Wyniki badań pokazują, że koty używają głównie wokalizacji, takich jak miauczenie, mruczenie i ćwierkanie, aby manipulować swoimi ludzkimi towarzyszami. Miauczenie jest szczególnie skuteczne w domaganiu się uwagi i pożywienia, podczas gdy mruczenie jest często wykorzystywane w celu zwiększenia więzi i komfortu. Świergoty i tryle są wykorzystywane do zachęcania do zabawy i interakcji. Ponadto język ciała, taki jak ugniatanie, ułożenie ogona i kontakt wzrokowy, odgrywają znaczącą rolę w komunikacji i manipulacji. Zachowania wymagające uwagi, w tym wspinanie się, pocieranie i przynoszenie przedmiotów, mają kluczowe znaczenie dla wywoływania reakcji ze strony ludzi.

        Badania podkreślają pozytywny wpływ tych taktyk manipulacji na relacje między człowiekiem a kotem, choć dostrzegają również potencjał frustracji i dostosowania zachowań przez właścicieli kotów. Badanie wnosi cenny wgląd w złożoność interakcji człowiek-zwierzę i sugeruje ścieżki przyszłych badań, w tym większe rozmiary prób, badania podłużne i badania eksperymentalne.

        Praca ta oferuje praktyczne implikacje dla poprawy interakcji człowiek-kot i lepszego zrozumienia kocich zachowań, sprzyjając bardziej harmonijnym relacjom między kotami i ich ludzkimi towarzyszami.
      ]
    ),
    keywords: (
      en: ("cat", "manipulation", "anthrozoology"),
      pl: ("algorytm ewolucyjny", "optymalizacja", "strojenie", "hiperparametr", "sieć neuronowa")
    ),
  )

  // --- Custom Settings ---
  // if you want to override any settings from the template here is the place to do so,
  // e.g.:
  // set text(font: "Comic Sans MS")


  // --- Main Chapters ---
  include "content/Tutorial.typ" // Some trivial, but useful snippets
  include "content/Introduction.typ"
  include "content/LiteratureReview.typ"
  include "content/Methodology.typ"
  include "content/DataCollection.typ"
  include "content/Analysis.typ"
  include "content/Conclusion.typ"

  // --- Acknowledgements ---
  // You can put your acknowledgements (pol. podziękowania) here.
  // Below is an example containing acknowledgements for the PLGrid grant.
  // Comment out if not needed.
  acknowledgements[
    We gratefully acknowledge Poland's high-performance Infrastructure PLGrid
    #text(fill: red)[(wybierz właściwy ośrodek z listy: ACK Cyfronet AGH, PCSS, CI TASK,
      WCSS)] for providing computer facilities and support within computational grant no
    #text(fill: red)[(numer grantu)]
    #todo[Numer grantu i typ ośrodka]
  ]

  // --- Bibliography ---
  bibliography("items.bib", style: "ieee")

  // List of Acronyms - comment out, if not needed (no abbreviations were used).
  glossary-outline(glossary)

  // List of figures - comment out, if not needed.
  figure-outline()

  // List of tables - comment out, if not needed.
  table-outline()

  // --- Appendices ---
  // Comment out if not needed.
  appendix(lang.thesis, include "content/Appendix.typ")

  if draft {
    set heading(numbering: none)
    note-outline(title: "TODOs")
  }
}
