[package]
name = "imperial-thesis"
version = "0.1.0"
entrypoint = "template.typ"
authors = ["bkmashiro <https://github.com/bkmashiro>"]
license = "MIT"
description = "Typst template for Imperial College London Individual Project / Thesis (Department of Computing)."
repository = "https://github.com/bkmashiro/ic-individual-project-typst"
keywords = ["thesis", "imperial", "university", "template"]
categories = ["thesis"]
compiler = "0.11.0"
exclude = ["example.pdf", "build.sh", "build.ps1", "Makefile", ".github", "fonts/", "figures/IMPERIAL_I_*.svg", "main.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
