// Built-in journal data transcribed from ACM-Reference-Format.bst (auto-extracted).
//  * journal-macros: the .bst's MACRO {abbr} {"Full Name"} table — seed values so
//    `journal = csur` resolves like bibtex even when the .bib doesn't define it.
//  * journal-canon: the .bst's journal.canon.abbrev table (Full Name -> canonical
//    abbreviation), applied to the journal field before emphasis.
#let journal-macros = (
  "cie": "ACM Computers in Entertainment",
  "csur": "ACM Computing Surveys",
  "dgov": "Digital Government: Research and Practice",
  "dtrap": "Digital Threats: Research and Practice",
  "health": "ACM Transactions on Computing for Healthcare",
  "imwut": "PACM on Interactive, Mobile, Wearable and Ubiquitous Technologies",
  "jacm": "Journal of the ACM",
  "jdiq": "ACM Journal of Data and Information Quality",
  "jea": "ACM Journal of Experimental Algorithmics",
  "jeric": "ACM Journal of Educational Resources in Computing",
  "jetc": "ACM Journal on Emerging Technologies in Computing Systems",
  "jocch": "ACM Journal on Computing and Cultural Heritage",
  "pacmcgit": "Proceedings of the ACM on Computer Graphics and Interactive Techniques",
  "pacmhci": "PACM on Human-Computer Interaction",
  "pacmpl": "PACM on Programming Languages",
  "pomacs": "PACM on Measurement and Analysis of Computing Systems",
  "taas": "ACM Transactions on Autonomous and Adaptive Systems",
  "taccess": "ACM Transactions on Accessible Computing",
  "taco": "ACM Transactions on Architecture and Code Optimization",
  "talg": "ACM Transactions on Algorithms",
  "tallip": "ACM Transactions on Asian and Low-Resource Language Information Processing",
  "tap": "ACM Transactions on Applied Perception",
  "tcps": "ACM Transactions on Cyber-Physical Systems",
  "tds": "ACM/IMS Transactions on Data Science",
  "teac": "ACM Transactions on Economics and Computation",
  "tecs": "ACM Transactions on Embedded Computing Systems",
  "telo": "ACM Transactions on Evolutionary Learning",
  "thri": "ACM Transactions on Human-Robot Interaction",
  "tiis": "ACM Transactions on Interactive Intelligent Systems",
  "tiot": "ACM Transactions on Internet of Things",
  "tissec": "ACM Transactions on Information and System Security",
  "tist": "ACM Transactions on Intelligent Systems and Technology",
  "tkdd": "ACM Transactions on Knowledge Discovery from Data",
  "tmis": "ACM Transactions on Management Information Systems",
  "toce": "ACM Transactions on Computing Education",
  "tochi": "ACM Transactions on Computer-Human Interaction",
  "tocl": "ACM Transactions on Computational Logic",
  "tocs": "ACM Transactions on Computer Systems",
  "toct": "ACM Transactions on Computation Theory",
  "todaes": "ACM Transactions on Design Automation of Electronic Systems",
  "tods": "ACM Transactions on Database Systems",
  "tog": "ACM Transactions on Graphics",
  "tois": "ACM Transactions on Information Systems",
  "toit": "ACM Transactions on Internet Technology",
  "tomacs": "ACM Transactions on Modeling and Computer Simulation",
  "tomm": "ACM Transactions on Multimedia Computing, Communications and Applications",
  "tompecs": "ACM Transactions on Modeling and Performance Evaluation of Computing Systems",
  "toms": "ACM Transactions on Mathematical Software",
  "topc": "ACM Transactions on Parallel Computing",
  "toplas": "ACM Transactions on Programming Languages and Systems",
  "tops": "ACM Transactions on Privacy and Security",
  "tos": "ACM Transactions on Storage",
  "tosem": "ACM Transactions on Software Engineering and Methodology",
  "tosn": "ACM Transactions on Sensor Networks",
  "tqc": "ACM Transactions on Quantum Computing",
  "trets": "ACM Transactions on Reconfigurable Technology and Systems",
  "tsas": "ACM Transactions on Spatial Algorithms and Systems",
  "tsc": "ACM Transactions on Social Computing",
  "tslp": "ACM Transactions on Speech and Language Processing",
  "tweb": "ACM Transactions on the Web",
  "acmcs": "ACM Computing Surveys",
  "acta": "Acta Informatica",
  "cacm": "Communications of the ACM",
  "ibmjrd": "IBM Journal of Research and Development",
  "ibmsj": "IBM Systems Journal",
  "ieeese": "IEEE Transactions on Software Engineering",
  "ieeetc": "IEEE Transactions on Computers",
  "ieeetcad": "IEEE Transactions on Computer-Aided Design of Integrated Circuits",
  "ipl": "Information Processing Letters",
  "jcss": "Journal of Computer and System Sciences",
  "scp": "Science of Computer Programming",
  "sicomp": "SIAM Journal on Computing",
  "toois": "ACM Transactions on Office Information Systems",
  "tcs": "Theoretical Computer Science",
)

#let journal-canon = (
  "ACM Computing Surveys": "Comput. Surveys",
  "{ACM} Computing Surveys": "Comput. Surveys",
  "ACM Transactions on Mathematical Software": "ACM Trans. Math. Software",
  "{ACM} Transactions on Mathematical Software": "ACM Trans. Math. Software",
  "ACM SIGNUM Newsletter": "ACM SIGNUM Newslett.",
  "ACM {SIGNUM} Newsletter": "ACM SIGNUM Newslett.",
  "{ACM} SIGNUM Newsletter": "ACM SIGNUM Newslett.",
  "{ACM} {SIGNUM} Newsletter": "ACM SIGNUM Newslett.",
  "American Journal of Sociology": "Amer. J. Sociology",
  "American Mathematical Monthly": "Amer. Math. Monthly",
  "American Mathematical Society Translations": "Amer. Math. Soc. Transl.",
  "Applied Mathematics and Computation": "Appl. Math. Comput.",
  "British Journal of Mathematical and Statistical Psychology": "Brit. J. Math. Statist. Psych.",
  "Bulletin of the American Mathematical Society": "Bull. Amer. Math. Soc.",
  "Canadian Mathematical Bulletin": "Canad. Math. Bull.",
  "Communications of the ACM": "Commun. ACM",
  "Communications of the {ACM}": "Commun. ACM",
  "Computers and Structures": "Comput. \& Structures",
  "Contemporary Mathematics": "Contemp. Math.",
  "Crelle's Journal": "Crelle's J.",
  "Giornale di Mathematiche": "Giorn. Mat.",
  "IEEE Transactions on Aerospace and Electronic Systems": "IEEE Trans. Aerospace Electron. Systems",
  "{IEEE} Transactions on Aerospace and Electronic Systems": "IEEE Trans. Aerospace Electron. Systems",
  "IEEE Transactions on Automatic Control": "IEEE Trans. Automat. Control",
  "{IEEE} Transactions on Automatic Control": "IEEE Trans. Automat. Control",
  "IEEE Transactions on Computers": "IEEE Trans. Comput.",
  "{IEEE} Transactions on Computers": "IEEE Trans. Comput.",
  "IMA Journal of Numerical Analysis": "IMA J. Numer. Anal.",
  "{IMA} Journal of Numerical Analysis": "IMA J. Numer. Anal.",
  "Information Processing Letters": "Inform. Process. Lett.",
  "International Journal for Numerical Methods in Engineering": "Internat. J. Numer. Methods Engrg.",
  "International Journal of Control": "Internat. J. Control",
  "International Journal of Supercomputing Applications": "Internat. J. Supercomputing Applic.",
  "Journal of Computational Physics": "J. Comput. Phys.",
  "Journal of Computational and Applied Mathematics": "J. Comput. Appl. Math.",
  "Journal of Computer and System Sciences": "J. Comput. System Sci.",
  "Journal of Mathematical Analysis and Applications": "J. Math. Anal. Appl.",
  "Journal of Mathematical Physics": "J. Math. Phys.",
  "Journal of Parallel and Distributed Computing": "J. Parallel and Distrib. Comput.",
  "Journal of Research of the National Bureau of Standards": "J. Res. Nat. Bur. Standards",
  "Journal of VLSI and Computer Systems": "J. VLSI Comput. Syst.",
  "Journal of {VLSI} and Computer Systems": "J. VLSI Comput. Syst.",
  "Journal of the ACM": "J. ACM",
  "Journal of the American Statistical Association": "J. Amer. Statist. Assoc.",
  "Journal of the Institute of Mathematics and its Applications": "J. Inst. Math. Appl.",
  "Journal of the Society for Industrial and Applied Mathematics": "J. Soc. Indust. Appl. Math.",
  "Journal of the Society for Industrial and Applied Mathematics, Series B, Numerical Analysis": "J. Soc. Indust. Appl. Math. Ser. B Numer. Anal.",
  "Linear Algebra and its Applications": "Linear Algebra Appl.",
  "Mathematica Scandinavica": "Math. Scand.",
  "Mathematical Tables and Other Aids to Computation": "Math. Tables Aids Comput.",
  "Mathematics of Computation": "Math. Comp.",
  "Mathematische Annalen": "Math. Ann.",
  "Numerische Mathematik": "Numer. Math.",
  "Pacific Journal of Mathematics": "Pacific J. Math.",
  "Parallel Computing": "Parallel Comput.",
  "Philosophical Magazine": "Philos. Mag.",
  "Proceedings of the American Mathematical Society": "Proc. Amer. Math. Soc.",
  "Proceedings of the IEEE": "Proc. IEEE",
  "Proceedings of the {IEEE}": "Proc. IEEE",
  "Proceedings of the National Academy of Sciences of the USA": "Proc. Nat. Acad. Sci. U. S. A.",
  "Quarterly Journal of Mathematics, Oxford, Series (2)": "Quart. J. Math. Oxford Ser. (2)",
  "Quarterly of Applied Mathematics": "Quart. Appl. Math.",
  "Review of the International Statisical Institute": "Rev. Inst. Internat. Statist.",
  "SIAM Journal on Algebraic and Discrete Methods": "SIAM J. Algebraic Discrete Methods",
  "{SIAM} Journal on Algebraic and Discrete Methods": "SIAM J. Algebraic Discrete Methods",
  "SIAM Journal on Applied Mathematics": "SIAM J. Appl. Math.",
  "{SIAM} Journal on Applied Mathematics": "SIAM J. Appl. Math.",
  "SIAM Journal on Computing": "SIAM J. Comput.",
  "{SIAM} Journal on Computing": "SIAM J. Comput.",
  "SIAM Journal on Matrix Analysis and Applications": "SIAM J. Matrix Anal. Appl.",
  "{SIAM} Journal on Matrix Analysis and Applications": "SIAM J. Matrix Anal. Appl.",
  "SIAM Journal on Numerical Analysis": "SIAM J. Numer. Anal.",
  "{SIAM} Journal on Numerical Analysis": "SIAM J. Numer. Anal.",
  "SIAM Journal on Scientific and Statistical Computing": "SIAM J. Sci. Statist. Comput.",
  "{SIAM} Journal on Scientific and Statistical Computing": "SIAM J. Sci. Statist. Comput.",
  "SIAM Review": "SIAM Rev.",
  "{SIAM} Review": "SIAM Rev.",
  "Software Practice and Experience": "Software Prac. Experience",
  "Statistical Science": "Statist. Sci.",
  "The Computer Journal": "Comput. J.",
  "Transactions of the American Mathematical Society": "Trans. Amer. Math. Soc.",
  "USSR Computational Mathematics and Mathematical Physics": "U. S. S. R. Comput. Math. and Math. Phys.",
  "{USSR} Computational Mathematics and Mathematical Physics": "U. S. S. R. Comput. Math. and Math. Phys.",
  "Zeitschrift fur Angewandte Mathematik und Mechanik": "Z. Angew. Math. Mech.",
  "Zeitschrift fur Angewandte Mathematik und Physik": "Z. Angew. Math. Phys.",
)
