// ACM journal table, transcribed in full from acmart.dtx's \acmJournal choice
// table (the dummy FACMP fallback is intentionally omitted).
//
// key -> (name, short, issn). issn is acmart's \@permissionCodeTwo (falling back
// to \@permissionCodeOne when Two is absent), used in the
// "ACM <issn>/<year>/<month>-ART<article>" copyright line; `short` is the
// running-head/footer abbreviation.
#let journals = (
  ACMJCSS: (name: "ACM Journal on Computing and Sustainable Societies", short: "ACM J. Comput. Sustain. Soc.", issn: "2834-5533"),
  ACMJDS: (name: "ACM Journal of Data Science", short: "ACM J. Data Sci.", issn: "3069-3497"),
  AILET: (name: "ACM AI Letters", short: "ACM AI Lett.", issn: "3068-8590"),
  CIE: (name: "ACM Computers in Entertainment", short: "ACM Comput. Entertain.", issn: "1544-3574"),
  CSUR: (name: "ACM Computing Surveys", short: "ACM Comput. Surv.", issn: "1557-7341"),
  DGOV: (name: "Digital Government: Research and Practice", short: "Digit. Gov. Res. Pract.", issn: "2639-0175"),
  DLT: (name: "Distributed Ledger Technologies: Research and Practice", short: "Distrib. Ledger Technol.", issn: "2769-6480"),
  DTRAP: (name: "Digital Threats: Research and Practice", short: "Digit. Threat. Res. Pract.", issn: "2576-5337"),
  FAC: (name: "Formal Aspects of Computing", short: "Form. Asp. Comput.", issn: "1433-299X"),
  GAMES: (name: "ACM Games: Research and Practice", short: "ACM Games", issn: "2832-5516"),
  HEALTH: (name: "ACM Transactions on Computing for Healthcare", short: "ACM Trans. Comput. Healthcare", issn: "2637-8051"),
  IMWUT: (name: "Proceedings of the ACM on Interactive, Mobile, Wearable and Ubiquitous Technologies", short: "Proc. ACM Interact. Mob. Wearable Ubiquitous Technol.", issn: "2474-9567"),
  JACM: (name: "Journal of the ACM", short: "J. ACM", issn: "1557-735X"),
  JATS: (name: "Journal on Autonomous Transportation Systems", short: "ACM J. Auton. Transport. Syst.", issn: "2833-0528"),
  JDIQ: (name: "ACM Journal of Data and Information Quality", short: "ACM J. Data Inform. Quality", issn: "1936-1963"),
  JDS: (name: "ACM Journal of Data Science", short: "ACM J. Data Sci.", issn: "2831-3194"),
  JEA: (name: "ACM Journal of Experimental Algorithmics", short: "ACM J. Exp. Algor.", issn: "1084-6654"),
  JERIC: (name: "ACM Journal of Educational Resources in Computing", short: "ACM J. Edu. Resources in Comput.", issn: "1073-0516"),
  JETC: (name: "ACM Journal on Emerging Technologies in Computing Systems", short: "ACM J. Emerg. Technol. Comput. Syst.", issn: "1550-4840"),
  JOCCH: (name: "ACM Journal on Computing and Cultural Heritage", short: "ACM J. Comput. Cult. Herit.", issn: "1556-4711"),
  JRC: (name: "ACM Journal on Responsible Computing", short: "ACM J. Responsib. Comput.", issn: "2832-0565"),
  PACMCGIT: (name: "Proceedings of the ACM on Computer Graphics and Interactive Techniques", short: "Proc. ACM Comput. Graph. Interact. Tech.", issn: "2577-6193"),
  PACMHCI: (name: "Proceedings of the ACM on Human-Computer Interaction", short: "Proc. ACM Hum.-Comput. Interact.", issn: "2573-0142"),
  PACMMOD: (name: "Proceedings of the ACM on Management of Data", short: "Proc. ACM Manag. Data", issn: "2836-6573"),
  PACMNET: (name: "Proceedings of the ACM on Networking", short: "Proc. ACM Netw.", issn: "2834-5509"),
  PACMPL: (name: "Proceedings of the ACM on Programming Languages", short: "Proc. ACM Program. Lang.", issn: "2475-1421"),
  PACMSE: (name: "Proceedings of the ACM on Software Engineering", short: "Proc. ACM Softw. Eng.", issn: "2994-970X"),
  POMACS: (name: "Proceedings of the ACM on Measurement and Analysis of Computing Systems", short: "Proc. ACM Meas. Anal. Comput. Syst.", issn: "2476-1249"),
  TAAS: (name: "ACM Transactions on Autonomous and Adaptive Systems", short: "ACM Trans. Autonom. Adapt. Syst.", issn: "1556-4703"),
  TACCESS: (name: "ACM Transactions on Accessible Computing", short: "ACM Trans. Access. Comput.", issn: "1936-7236"),
  TACO: (name: "ACM Transactions on Architecture and Code Optimization", short: "ACM Trans. Arch. Code Optim.", issn: "1544-3973"),
  TAIS: (name: "ACM Transactions on AI for Science", short: "ACM Trans. AI Sci.", issn: "3066-4438"),
  TAISAP: (name: "ACM Transactions on AI Security and Privacy", short: "ACM Trans. AI Secur. Priv.", issn: "3068-3564"),
  TALG: (name: "ACM Transactions on Algorithms", short: "ACM Trans. Algor.", issn: "1549-6333"),
  TALLIP: (name: "ACM Transactions on Asian and Low-Resource Language Information Processing", short: "ACM Trans. Asian Low-Resour. Lang. Inf. Process.", issn: "2375-4702"),
  TAP: (name: "ACM Transactions on Applied Perception", short: "ACM Trans. Appl. Percept.", issn: "1544-3965"),
  TCPS: (name: "ACM Transactions on Cyber-Physical Systems", short: "ACM Trans. Cyber-Phys. Syst.", issn: "2378-9638"),
  TDS: (name: "ACM Transactions on Data Science", short: "ACM Trans. Data Sci.", issn: "2577-3224"),
  TEAC: (name: "ACM Transactions on Economics and Computation", short: "ACM Trans. Econ. Comput.", issn: "2167-8383"),
  TECS: (name: "ACM Transactions on Embedded Computing Systems", short: "ACM Trans. Embedd. Comput. Syst.", issn: "1558-3465"),
  TELO: (name: "ACM Transactions on Evolutionary Learning and Optimization", short: "ACM Trans. Evol. Learn. Optim.", issn: "2688-3007"),
  THRI: (name: "ACM Transactions on Human-Robot Interaction", short: "ACM Trans. Hum.-Robot Interact.", issn: "2573-9522"),
  TIIS: (name: "ACM Transactions on Interactive Intelligent Systems", short: "ACM Trans. Interact. Intell. Syst.", issn: "2160-6463"),
  TIOT: (name: "ACM Transactions on Internet of Things", short: "ACM Trans. Internet Things", issn: "2577-6207"),
  TISSEC: (name: "ACM Transactions on Information and System Security", short: "ACM Trans. Info. Syst. Sec.", issn: "1094-9224"),
  TIST: (name: "ACM Transactions on Intelligent Systems and Technology", short: "ACM Trans. Intell. Syst. Technol.", issn: "2157-6912"),
  TKDD: (name: "ACM Transactions on Knowledge Discovery from Data", short: "ACM Trans. Knowl. Discov. Data.", issn: "1556-472X"),
  TMIS: (name: "ACM Transactions on Management Information Systems", short: "ACM Trans. Manag. Inform. Syst.", issn: "2158-6578"),
  TOCE: (name: "ACM Transactions on Computing Education", short: "ACM Trans. Comput. Educ.", issn: "1946-6226"),
  TOCHI: (name: "ACM Transactions on Computer-Human Interaction", short: "ACM Trans. Comput.-Hum. Interact.", issn: "1557-7325"),
  TOCL: (name: "ACM Transactions on Computational Logic", short: "ACM Trans. Comput. Logic", issn: "1557-945X"),
  TOCS: (name: "ACM Transactions on Computer Systems", short: "ACM Trans. Comput. Syst.", issn: "1557-7333"),
  TOCT: (name: "ACM Transactions on Computation Theory", short: "ACM Trans. Comput. Theory", issn: "1942-3462"),
  TODAES: (name: "ACM Transactions on Design Automation of Electronic Systems", short: "ACM Trans. Des. Autom. Electron. Syst.", issn: "1557-7309"),
  TODS: (name: "ACM Transactions on Database Systems", short: "ACM Trans. Datab. Syst.", issn: "1557-4644"),
  TOG: (name: "ACM Transactions on Graphics", short: "ACM Trans. Graph.", issn: "1557-7368"),
  TOIS: (name: "ACM Transactions on Information Systems", short: "ACM Trans. Inf. Syst.", issn: "1558-2868"),
  TOIT: (name: "ACM Transactions on Internet Technology", short: "ACM Trans. Internet Technol.", issn: "1557-6051"),
  TOMACS: (name: "ACM Transactions on Modeling and Computer Simulation", short: "ACM Trans. Model. Comput. Simul.", issn: "1558-1195"),
  TOMM: (name: "ACM Transactions on Multimedia Computing, Communications and Applications", short: "ACM Trans. Multimedia Comput. Commun. Appl.", issn: "1551-6865"),
  TOMPECS: (name: "ACM Transactions on Modeling and Performance Evaluation of Computing Systems", short: "ACM Trans. Model. Perform. Eval. Comput. Syst.", issn: "2376-3647"),
  TOMS: (name: "ACM Transactions on Mathematical Software", short: "ACM Trans. Math. Softw.", issn: "1557-7295"),
  TOPC: (name: "ACM Transactions on Parallel Computing", short: "ACM Trans. Parallel Comput.", issn: "2329-4957"),
  TOPLAS: (name: "ACM Transactions on Programming Languages and Systems", short: "ACM Trans. Program. Lang. Syst.", issn: "1558-4593"),
  TOPML: (name: "ACM Transactions on Probabilistic Machine Learning", short: "ACM Trans. Probab. Mach. Learn.", issn: "2836-8924"),
  TOPS: (name: "ACM Transactions on Privacy and Security", short: "ACM Trans. Priv. Sec.", issn: "2471-2574"),
  TORS: (name: "ACM Transactions on Recommender Systems", short: "ACM Trans. Recomm. Syst.", issn: "2770-6699"),
  TOS: (name: "ACM Transactions on Storage", short: "ACM Trans. Storage", issn: "1553-3093"),
  TOSEM: (name: "ACM Transactions on Software Engineering and Methodology", short: "ACM Trans. Softw. Eng. Methodol.", issn: "1557-7392"),
  TOSN: (name: "ACM Transactions on Sensor Networks", short: "ACM Trans. Sensor Netw.", issn: "1550-4867"),
  TQC: (name: "ACM Transactions on Quantum Computing", short: "ACM Trans. Quantum Comput.", issn: "2643-6817"),
  TRETS: (name: "ACM Transactions on Reconfigurable Technology and Systems", short: "ACM Trans. Reconfig. Technol. Syst.", issn: "1936-7414"),
  TSAS: (name: "ACM Transactions on Spatial Algorithms and Systems", short: "ACM Trans. Spatial Algorithms Syst.", issn: "2374-0361"),
  TSC: (name: "ACM Transactions on Social Computing", short: "ACM Trans. Soc. Comput.", issn: "2469-7826"),
  TSLP: (name: "ACM Transactions on Speech and Language Processing", short: "ACM Trans. Speech Lang. Process.", issn: "2329-9304"),
  TWEB: (name: "ACM Transactions on the Web", short: "ACM Trans. Web", issn: "1559-114X"),
)

#let lookup-journal(key) = {
  if key == none { return (name: none, short: none, issn: "XXXX-XXXX") }
  let s = str(key)
  journals.at(s, default: (name: s, short: s, issn: "XXXX-XXXX"))
}
