[package]
name = "tiny-bingo"
version = "0.1.0"
entrypoint = "tiny-bingo.typ"
authors = ["Torstein Nordgård-Hansen"]
license = "AGPL-3.0-or-later"
description = "Generate randomized bingo boards."
repository = "https://github.com/torsteinnh/tiny-bingo"
keywords = ["Bingo", "Game", "Social", "Board"]
compiler = "0.14.0"
categories = ["components"]
