// https://en.wikipedia.org/wiki/X-SAMPA
// https://en.wikipedia.org/wiki/Comparison_of_ASCII_encodings_of_the_International_Phonetic_Alphabet

#let xsampa-unicode = (
  ("!", "ꜜ"),
  ("!\\", "ǃ"),
  ("", ""),
  ("%", "ˌ"),
  ("&", "ɶ"),
  ("'", "ʲ"),
  ("-", ""),
  ("-\\", "‿"),
  (".", "."),
  ("1", "ɨ"),
  ("2", "ø"),
  ("3", "ɜ"),
  ("3\\", "ɞ"),
  ("4", "ɾ"),
  ("5", "ɫ"),
  ("6", "ɐ"),
  ("7", "ɤ"),
  ("8", "ɵ"),
  ("9", "œ"),
  (":", "ː"),
  (":\\", "ˑ"),
  ("</>", "↗"),
  ("<F>", "↘"),
  ("<R>", "↗"),
  ("<\\", "ʢ"),
  ("<\\>", "↘"),
  ("=", "̩"),
  ("=\\", "ǂ"),
  (">\\", "ʡ"),
  ("?", "ʔ"),
  ("?\\", "ʕ"),
  ("@", "ə"),
  ("@\\", "ɘ"),
  ("@`", "ɚ"),
  ("A", "ɑ"),
  ("B", "β"),
  ("B\\", "ʙ"),
  ("C", "ç"),
  ("D", "ð"),
  ("E", "ɛ"),
  ("F", "ɱ"),
  ("G", "ɣ"),
  ("G\\", "ɢ"),
  ("G\\_<", "ʛ"),
  ("H", "ɥ"),
  ("H\\", "ʜ"),
  ("I", "ɪ"),
  ("I\\", "ᵻ"),
  ("J", "ɲ"),
  ("J\\", "ɟ"),
  ("J\\_<", "ʄ"),
  ("K", "ɬ"),
  ("K\\", "ɮ"),
  ("L", "ʎ"),
  ("L\\", "ʟ"),
  ("M", "ɯ"),
  ("M\\", "ɰ"),
  ("N", "ŋ"),
  ("N\\", "ɴ"),
  ("O", "ɔ"),
  ("O\\", "ʘ"),
  ("P", "ʋ"),
  ("Q", "ɒ"),
  ("R", "ʁ"),
  ("R\\", "ʀ"),
  ("S", "ʃ"),
  ("T", "θ"),
  ("U", "ʊ"),
  ("U\\", "ᵿ"),
  ("V", "ʌ"),
  ("W", "ʍ"),
  ("X", "χ"),
  ("X\\", "ħ"),
  ("Y", "ʏ"),
  ("Z", "ʒ"),
  ("\"", "ˈ"),
  ("^", "ꜛ"),
  ("_", "͡"),
  ("_+", "̟"),
  ("_-", "̠"),
  ("_/", "̌"),
  ("_/_\\", "᷈"),
  ("_0", "̥"),
  ("_=", "̩"),
  ("_>", "ʼ"),
  ("_?\\", "ˤ"),
  ("_A", "̘"),
  ("_B", "̏"),
  ("_B_L", "᷅"),
  ("_F", "̂"),
  ("_G", "ˠ"),
  ("_H", "́"),
  ("_H_L", "̂"),
  ("_H_T", "᷄"),
  ("_L", "̀"),
  ("_L_H", "̌"),
  ("_M", "̄"),
  ("_M_H_L", "᷈"),
  ("_N", "̼"),
  ("_O", "̹"),
  ("_R", "̌"),
  ("_R_F", "᷈"),
  ("_T", "̋"),
  ("_X", "̆"),
  ("_\"", "̈"),
  ("_\\", "̂"),
  ("_^", "̯"),
  ("_a", "̺"),
  ("_c", "̜"),
  ("_d", "̪"),
  ("_e", "̴"),
  ("_h", "ʰ"),
  ("_j", "ʲ"),
  ("_k", "̰"),
  ("_l", "ˡ"),
  ("_m", "̻"),
  ("_n", "ⁿ"),
  ("_o", "̞"),
  ("_q", "̙"),
  ("_r", "̝"),
  ("_t", "̤"),
  ("_v", "̬"),
  ("_w", "ʷ"),
  ("_x", "̽"),
  ("_}", "̚"),
  ("_~", "̃"),
  ("`", "˞"),
  ("a", "a"),
  ("b", "b"),
  ("b_<", "ɓ"),
  ("c", "c"),
  ("d", "d"),
  ("d_<", "ɗ"),
  ("d`", "ɖ"),
  ("e", "e"),
  ("f", "f"),
  ("g", "ɡ"),
  ("g_<", "ɠ"),
  ("h", "h"),
  ("h\\", "ɦ"),
  ("i", "i"),
  ("j", "j"),
  ("j\\", "ʝ"),
  ("k", "k"),
  ("l", "l"),
  ("l\\", "ɺ"),
  ("l`", "ɭ"),
  ("m", "m"),
  ("n", "n"),
  ("n`", "ɳ"),
  ("o", "o"),
  ("p", "p"),
  ("p\\", "ɸ"),
  ("q", "q"),
  ("r", "r"),
  ("r\\", "ɹ"),
  ("r\\`", "ɻ"),
  ("r`", "ɽ"),
  ("s", "s"),
  ("s\\", "ɕ"),
  ("s`", "ʂ"),
  ("t", "t"),
  ("t`", "ʈ"),
  ("u", "u"),
  ("v", "v"),
  ("v\\", "ʋ"),
  ("w", "w"),
  ("x", "x"),
  ("x\\", "ɧ"),
  ("y", "y"),
  ("z", "z"),
  ("z\\", "ʑ"),
  ("z`", "ʐ"),
  ("{", "æ"),
  ("|", "|"),
  ("|\\", "ǀ"),
  ("|\\|\\", "ǁ"),
  ("||", "‖"),
  ("}", "ʉ"),
  ("~", "̃"),
).sorted(
  key: (pair) => -pair.at(0).len()
)

#let samprosa-unicode = (
  ("B", "˩"),
  ("L", "˨"),
  ("M", "˧"),
  ("H", "˦"),
  ("T", "˥"),
)

#let samprosa-to-unicode(text, reverse: false) = {
  let (from, to) = if reverse { (1, 0) } else { (0, 1) }
  for pair in samprosa-unicode {
    text = text.replace(pair.at(from), pair.at(to))
  }
  text
}

#let convert-samprosa(text, reverse: false) = {
  if reverse {
    let tone-regex = regex("[˩˨˧˦˥]+")
    while text.matches(tone-regex).len() != 0 {
      let tone = text.matches(tone-regex).sorted(key: x => x.text.len()).last().text
      text = text.replace(tone, "<" + samprosa-to-unicode(tone, reverse: true) + ">")
    }
  } else {
    let samprosa-regex = regex("<[BLMHT]+>")
    let tones = text.matches(samprosa-regex)
    for tone in tones {
      text = text.replace(tone.text, samprosa-to-unicode(tone.text.trim(regex("<|>")), reverse: false))
    }
  }
  text
}

#let convert-xsampa(text, reverse: false) = {
  let (from, to) = if reverse { (1, 0) } else { (0, 1) }
  text = convert-samprosa(text, reverse: reverse)
  for pair in xsampa-unicode {
    text = text.replace(pair.at(from), pair.at(to))
  }
  text
}
