[package]
name = "dati-basati"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Vittorio Robecchi <https://github.com/victuarvi>"]
license = "GPL-3.0"
description = "Draw Entity-Relations diagrams."
repository = "https://www.github.com/victuarvi/dati-basati"
keywords = ["er-diagrams", "entity relations diagrams"]
categories = ["visualization", "scripting"]
disciplines = ["engineering", "computer-science"]
exclude = ["/docs/*", "/examples/*", "*.pdf", "*.sh"]
compiler = "0.13.0"
