#let theme(
  inset: 6pt,
  fill: red,
  radius: 4pt,
  stroke: 1pt,
  type-radius: 2pt,
  type-inset: 4pt,
  type-fill: orange,
  type-stroke: none,
  line-paint: black,
  line-thickness: 1pt,
  mark-size: 1pt,
  text-color: black,
  name-weight: "bold",
  type-weight: "regular",
  text-weight: "regular",
) = {
  return (
    inset: inset,
    fill: fill,
    radius: radius,
    stroke: stroke,
    type-radius: type-radius,
    type-inset: type-inset,
    type-fill: type-fill,
    type-stroke: type-stroke,
    line-paint: line-paint,
    line-thickness: line-thickness,
    mark-size: mark-size,
    text-color: text-color,
    name-weight: name-weight,
    type-weight: type-weight,
    text-weight: text-weight,
  )
}

#let themes = (
  // Default theme
  default: theme(
    inset: 6pt,
    fill: red,
    radius: 4pt,
    stroke: 1pt,
    type-radius: 2pt,
    type-inset: 4pt,
    type-fill: orange,
    type-stroke: none,
  ),

  blueprint: theme(
    inset: 7pt,
    fill: rgb("#174A7E"),
    radius: 1pt,
    stroke: rgb("#A9D6F5"),
    type-radius: 1pt,
    type-inset: 4pt,
    type-fill: rgb("#D8EEFF"),
    type-stroke: none,
    line-paint: rgb("#A9D6F5"),
    line-thickness: 0.8pt,
    mark-size: 1.2pt,
    text-color: white,
    name-weight: "bold",
    type-weight: "regular",
    text-weight: "regular",
  ),

  bauhaus: theme(
    inset: 8pt,
    fill: rgb("#F2D53C"),
    radius: 0pt,
    stroke: rgb("#111111"),
    type-radius: 0pt,
    type-inset: 5pt,
    type-fill: rgb("#E23B2E"),
    type-stroke: rgb("#111111"),
    line-paint: rgb("#111111"),
    line-thickness: 2pt,
    mark-size: 2pt,
    text-color: rgb("#111111"),
    name-weight: "bold",
    type-weight: "bold",
    text-weight: "regular",
  ),

  terminal: theme(
    inset: 7pt,
    fill: rgb("#101810"),
    radius: 2pt,
    stroke: rgb("#55FF77"),
    type-radius: 1pt,
    type-inset: 4pt,
    type-fill: rgb("#17351D"),
    type-stroke: rgb("#55FF77"),
    line-paint: rgb("#55FF77"),
    line-thickness: 0.7pt,
    mark-size: 1pt,
    text-color: rgb("#7CFF91"),
    name-weight: "bold",
    type-weight: "regular",
    text-weight: "regular",
  ),

  desert: theme(
    inset: 8pt,
    fill: rgb("#E8C9A0"),
    radius: 7pt,
    stroke: rgb("#8A4B32"),
    type-radius: 4pt,
    type-inset: 4pt,
    type-fill: rgb("#B85C3D"),
    type-stroke: none,
    line-paint: rgb("#8A4B32"),
    line-thickness: 1.2pt,
    mark-size: 1.3pt,
    text-color: rgb("#37251C"),
    name-weight: "bold",
    type-weight: "bold",
    text-weight: "regular",
  ),

  arctic: theme(
    inset: 7pt,
    fill: rgb("#E8F5F8"),
    radius: 5pt,
    stroke: rgb("#75AAB8"),
    type-radius: 3pt,
    type-inset: 4pt,
    type-fill: rgb("#B9E4EA"),
    type-stroke: none,
    line-paint: rgb("#75AAB8"),
    line-thickness: 0.8pt,
    mark-size: 1pt,
    text-color: rgb("#183A44"),
    name-weight: "bold",
    type-weight: "regular",
    text-weight: "regular",
  ),

  vaporwave: theme(
    inset: 8pt,
    fill: rgb("#302B63"),
    radius: 8pt,
    stroke: rgb("#FF71CE"),
    type-radius: 6pt,
    type-inset: 5pt,
    type-fill: rgb("#01CDFE"),
    type-stroke: none,
    line-paint: rgb("#B967FF"),
    line-thickness: 1.5pt,
    mark-size: 1pt,
    text-color: white,
    name-weight: "bold",
    type-weight: "bold",
    text-weight: "regular",
  ),

  botanical: theme(
    inset: 8pt,
    fill: rgb("#DCE5D2"),
    radius: 9pt,
    stroke: rgb("#4D6545"),
    type-radius: 8pt,
    type-inset: 5pt,
    type-fill: rgb("#708B61"),
    type-stroke: none,
    line-paint: rgb("#71816A"),
    line-thickness: 1pt,
    mark-size: 1.2pt,
    text-color: rgb("#263226"),
    name-weight: "bold",
    type-weight: "regular",
    text-weight: "regular",
  ),

  industrial: theme(
    inset: 7pt,
    fill: rgb("#D9D9D6"),
    radius: 1pt,
    stroke: rgb("#242424"),
    type-radius: 1pt,
    type-inset: 4pt,
    type-fill: rgb("#F4B400"),
    type-stroke: rgb("#242424"),
    line-paint: rgb("#242424"),
    line-thickness: 1.8pt,
    mark-size: 1.8pt,
    text-color: rgb("#171717"),
    name-weight: "bold",
    type-weight: "bold",
    text-weight: "regular",
  ),

  editorial: theme(
    inset: 9pt,
    fill: rgb("#F5F3EE"),
    radius: 0pt,
    stroke: rgb("#1B1B1B"),
    type-radius: 0pt,
    type-inset: 3pt,
    type-fill: rgb("#1B1B1B"),
    type-stroke: none,
    line-paint: rgb("#1B1B1B"),
    line-thickness: 0.6pt,
    mark-size: 0.8pt,
    text-color: rgb("#1B1B1B"),
    name-weight: "bold",
    type-weight: "regular",
    text-weight: "regular",
  ),

  deep-ocean: theme(
    inset: 8pt,
    fill: rgb("#082F3D"),
    radius: 6pt,
    stroke: rgb("#23C7B8"),
    type-radius: 4pt,
    type-inset: 4pt,
    type-fill: rgb("#0D6E75"),
    type-stroke: none,
    line-paint: rgb("#42B7B0"),
    line-thickness: 1pt,
    mark-size: 1.3pt,
    text-color: rgb("#E8FAF8"),
    name-weight: "bold",
    type-weight: "bold",
    text-weight: "regular",
  ),

  // Dark
  pixies: theme(
    inset: 6pt,
    fill: gray.darken(40%),
    radius: 0pt,
    stroke: 3pt,
    type-radius: 0pt,
    type-inset: 4pt,
    type-fill: gray.darken(70%),
    type-stroke: black + 2pt,
    line-paint: black,
    line-thickness: 1pt,
    text-color: white.darken(10%),
  ),

  // Material Design 3 - Clean, modern, elevation-based
  material-design: theme(
    inset: 12pt,
    fill: rgb("#e8def8"),
    radius: 8pt,
    stroke: 0pt,
    type-radius: 4pt,
    type-inset: 8pt,
    type-fill: rgb("#d0bcff"),
    type-stroke: none,
    line-paint: rgb("#d0bcff"),
    line-thickness: 2pt,
  ),

  // Modern/Clean - Minimal borders, generous spacing
  modern: theme(
    inset: 8pt,
    fill: rgb("#f5f5f5"),
    radius: 8pt,
    stroke: 0pt,
    type-radius: 4pt,
    type-inset: 6pt,
    type-fill: rgb("#e8e8e8"),
    type-stroke: none,
  ),
)
