[package]
name = "revtyp"
version = "0.15.0"
entrypoint = "src/main.typ"
description = "Prepare papers in the style of the APS Physical Review journals"
authors = [ "Philipp Niedermayer <@eltos>" ]
license = "GPL-3.0-only AND MIT-0"
repository = "https://github.com/eltos/revtyp"
keywords = [
  "paper",
  "accelerator",
  "physics",
  "revtex",
  "aps",
  "physical review",
  "pra",
  "prab",
  "prapplied",
]
categories = [ "paper" ]
disciplines = [ "physics", "engineering" ]
compiler = "0.14.0"

[template]
path = "template"
entrypoint = "paper.typ"
thumbnail = "thumbnail.webp"
