// Constants
#let SIZE_HUGE = 1.5em
#let SIZE_LARGE = 1.1em
#let SIZE_NORMAL = 1em
#let SIZE_SMALL = 0.9em
#let SIZE_TINY = 0.7em

#let BODY_FONT = "Source Serif Pro"
#let BODY_SIZE = 11pt
#let BODY_WEIGHT = "light"
#let HEADING_FONT = "Source Sans Pro"

#let PAGE_MARGIN = 0.5in

#let HEADER_SIZE = SIZE_SMALL
#let HEADER_ICON_HEIGHT = SIZE_NORMAL
#let HEADER_ICON_SPACING = 0.25em

#let FOOTER_SIZE = SIZE_TINY
#let FOOTER_TEXT_WEIGHT = "thin"

#let HEADLINE_NAME_SIZE = SIZE_HUGE
#let HEADLINE_NAME_WEIGHT = "bold"
#let HEADLINE_HRULE_STROKE = 1pt + black

#let TAGLINE_SIZE = SIZE_NORMAL
#let TAGLINE_STYLE = "italic"
#let TAGLINE_WEIGHT = "regular"

#let SECTION_HEADING_SIZE = 0.8em // TODO: this seems wrong, should be SIZE_NORMAL (etc)
#let SECTION_HEADING_WEIGHT = "semibold"
#let SECTION_HEADING_HRULE_STROKE = 0.75pt + navy.lighten(10%)
#let SECTION_HEADING_SPACE_ABOVE = 1em
#let SECTION_HEADING_SPACE_BELOW = 0.5em
#let SECTION_HEADING_BLOCK_FILL = luma(100%) //gradient.linear(blue.lighten(99%), luma(100%))
#let SECTION_HEADING_BLOCK_RADIUS = 2pt
#let SECTION_HEADING_BLOCK_OUTSET = 0.2em

#let COMPANY_ICON_SIZE = SIZE_NORMAL
#let COMPANY_ICON_SPACING = 0.25em
#let COMPANY_NAME_SIZE = SIZE_LARGE
#let COMPANY_NAME_WEIGHT = "semibold"
#let COMPANY_DATE_SIZE = COMPANY_NAME_SIZE
#let COMPANY_DATE_WEIGHT = "semibold"
#let COMPANY_BLOCK_BELOW = 1.3em

#let JOB_NAME_SIZE = SIZE_NORMAL
#let JOB_NAME_STYLE = "normal"
#let JOB_NAME_WEIGHT = "medium"
#let JOB_LOCATION_SIZE = SIZE_SMALL
#let JOB_LOCATION_STYLE = JOB_NAME_STYLE
#let JOB_LOCATION_WEIGHT = "light"
#let JOB_BLOCK_ABOVE = 0.6em
#let JOB_BLOCK_BELOW = 1em
#let EMPTY_JOB_NUDGE = -0.75em

#let TABLE_HEADER_COLOR = blue.lighten(70%)
#let TABLE_ZEBRA_COLOR_0 = green.lighten(85%)
#let TABLE_ZEBRA_COLOR_1 = green.lighten(95%)

#let HRULE_HEIGHT = 0.5em
