#let data = (
  ("OL CHIKI DIGIT ZERO", "Nd", 0, none),
  ("OL CHIKI DIGIT ONE", "Nd", 0, none),
  ("OL CHIKI DIGIT TWO", "Nd", 0, none),
  ("OL CHIKI DIGIT THREE", "Nd", 0, none),
  ("OL CHIKI DIGIT FOUR", "Nd", 0, none),
  ("OL CHIKI DIGIT FIVE", "Nd", 0, none),
  ("OL CHIKI DIGIT SIX", "Nd", 0, none),
  ("OL CHIKI DIGIT SEVEN", "Nd", 0, none),
  ("OL CHIKI DIGIT EIGHT", "Nd", 0, none),
  ("OL CHIKI DIGIT NINE", "Nd", 0, none),
  ("OL CHIKI LETTER LA", "Lo", 0, none),
  ("OL CHIKI LETTER AT", "Lo", 0, none),
  ("OL CHIKI LETTER AG", "Lo", 0, none),
  ("OL CHIKI LETTER ANG", "Lo", 0, none),
  ("OL CHIKI LETTER AL", "Lo", 0, none),
  ("OL CHIKI LETTER LAA", "Lo", 0, none),
  ("OL CHIKI LETTER AAK", "Lo", 0, none),
  ("OL CHIKI LETTER AAJ", "Lo", 0, none),
  ("OL CHIKI LETTER AAM", "Lo", 0, none),
  ("OL CHIKI LETTER AAW", "Lo", 0, none),
  ("OL CHIKI LETTER LI", "Lo", 0, none),
  ("OL CHIKI LETTER IS", "Lo", 0, none),
  ("OL CHIKI LETTER IH", "Lo", 0, none),
  ("OL CHIKI LETTER INY", "Lo", 0, none),
  ("OL CHIKI LETTER IR", "Lo", 0, none),
  ("OL CHIKI LETTER LU", "Lo", 0, none),
  ("OL CHIKI LETTER UC", "Lo", 0, none),
  ("OL CHIKI LETTER UD", "Lo", 0, none),
  ("OL CHIKI LETTER UNN", "Lo", 0, none),
  ("OL CHIKI LETTER UY", "Lo", 0, none),
  ("OL CHIKI LETTER LE", "Lo", 0, none),
  ("OL CHIKI LETTER EP", "Lo", 0, none),
  ("OL CHIKI LETTER EDD", "Lo", 0, none),
  ("OL CHIKI LETTER EN", "Lo", 0, none),
  ("OL CHIKI LETTER ERR", "Lo", 0, none),
  ("OL CHIKI LETTER LO", "Lo", 0, none),
  ("OL CHIKI LETTER OTT", "Lo", 0, none),
  ("OL CHIKI LETTER OB", "Lo", 0, none),
  ("OL CHIKI LETTER OV", "Lo", 0, none),
  ("OL CHIKI LETTER OH", "Lo", 0, none),
  ("OL CHIKI MU TTUDDAG", "Lm", 0, none),
  ("OL CHIKI GAAHLAA TTUDDAAG", "Lm", 0, none),
  ("OL CHIKI MU-GAAHLAA TTUDDAAG", "Lm", 0, none),
  ("OL CHIKI RELAA", "Lm", 0, none),
  ("OL CHIKI PHAARKAA", "Lm", 0, none),
  ("OL CHIKI AHAD", "Lm", 0, none),
  ("OL CHIKI PUNCTUATION MUCAAD", "Po", 0, none),
  ("OL CHIKI PUNCTUATION DOUBLE MUCAAD", "Po", 0, none),
)
