#let data = (
  ("GURUNG KHEMA LETTER A", "Lo", 0, none),
  ("GURUNG KHEMA LETTER KA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER KHA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER GA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER GHA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER NGA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER CA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER CHA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER JA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER JHA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER HA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER TTA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER TTHA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER DDA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER DDHA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER VA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER TA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER THA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER DA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER DHA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER NA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER PA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER PHA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER BA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER BHA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER MA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER YA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER RA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER LA", "Lo", 0, none),
  ("GURUNG KHEMA LETTER SA", "Lo", 0, none),
  ("GURUNG KHEMA VOWEL SIGN AA", "Mn", 0, none),
  ("GURUNG KHEMA VOWEL SIGN I", "Mn", 0, none),
  ("GURUNG KHEMA VOWEL SIGN II", "Mn", 0, none),
  ("GURUNG KHEMA VOWEL SIGN U", "Mn", 0, none),
  ("GURUNG KHEMA VOWEL SIGN UU", "Mn", 0, none),
  ("GURUNG KHEMA VOWEL SIGN E", "Mn", 0, none),
  ("GURUNG KHEMA VOWEL SIGN EE", "Mn", 0, none),
  ("GURUNG KHEMA VOWEL SIGN AI", "Mn", 0, none),
  ("GURUNG KHEMA VOWEL SIGN O", "Mn", 0, none),
  ("GURUNG KHEMA VOWEL SIGN OO", "Mn", 0, none),
  ("GURUNG KHEMA VOWEL SIGN AU", "Mn", 0, none),
  ("GURUNG KHEMA VOWEL LENGTH MARK", "Mn", 0, none),
  ("GURUNG KHEMA CONSONANT SIGN MEDIAL YA", "Mc", 0, none),
  ("GURUNG KHEMA CONSONANT SIGN MEDIAL VA", "Mc", 0, none),
  ("GURUNG KHEMA CONSONANT SIGN MEDIAL HA", "Mc", 0, none),
  ("GURUNG KHEMA SIGN ANUSVARA", "Mn", 0, none),
  ("GURUNG KHEMA CONSONANT SIGN MEDIAL RA", "Mn", 0, none),
  ("GURUNG KHEMA SIGN THOLHOMA", "Mn", 9, none),
  ("GURUNG KHEMA DIGIT ZERO", "Nd", 0, none),
  ("GURUNG KHEMA DIGIT ONE", "Nd", 0, none),
  ("GURUNG KHEMA DIGIT TWO", "Nd", 0, none),
  ("GURUNG KHEMA DIGIT THREE", "Nd", 0, none),
  ("GURUNG KHEMA DIGIT FOUR", "Nd", 0, none),
  ("GURUNG KHEMA DIGIT FIVE", "Nd", 0, none),
  ("GURUNG KHEMA DIGIT SIX", "Nd", 0, none),
  ("GURUNG KHEMA DIGIT SEVEN", "Nd", 0, none),
  ("GURUNG KHEMA DIGIT EIGHT", "Nd", 0, none),
  ("GURUNG KHEMA DIGIT NINE", "Nd", 0, none),
)
