#let data = (
  ("BHAIKSUKI LETTER A", "Lo", 0, none),
  ("BHAIKSUKI LETTER AA", "Lo", 0, none),
  ("BHAIKSUKI LETTER I", "Lo", 0, none),
  ("BHAIKSUKI LETTER II", "Lo", 0, none),
  ("BHAIKSUKI LETTER U", "Lo", 0, none),
  ("BHAIKSUKI LETTER UU", "Lo", 0, none),
  ("BHAIKSUKI LETTER VOCALIC R", "Lo", 0, none),
  ("BHAIKSUKI LETTER VOCALIC RR", "Lo", 0, none),
  ("BHAIKSUKI LETTER VOCALIC L", "Lo", 0, none),
  (),
  ("BHAIKSUKI LETTER E", "Lo", 0, none),
  ("BHAIKSUKI LETTER AI", "Lo", 0, none),
  ("BHAIKSUKI LETTER O", "Lo", 0, none),
  ("BHAIKSUKI LETTER AU", "Lo", 0, none),
  ("BHAIKSUKI LETTER KA", "Lo", 0, none),
  ("BHAIKSUKI LETTER KHA", "Lo", 0, none),
  ("BHAIKSUKI LETTER GA", "Lo", 0, none),
  ("BHAIKSUKI LETTER GHA", "Lo", 0, none),
  ("BHAIKSUKI LETTER NGA", "Lo", 0, none),
  ("BHAIKSUKI LETTER CA", "Lo", 0, none),
  ("BHAIKSUKI LETTER CHA", "Lo", 0, none),
  ("BHAIKSUKI LETTER JA", "Lo", 0, none),
  ("BHAIKSUKI LETTER JHA", "Lo", 0, none),
  ("BHAIKSUKI LETTER NYA", "Lo", 0, none),
  ("BHAIKSUKI LETTER TTA", "Lo", 0, none),
  ("BHAIKSUKI LETTER TTHA", "Lo", 0, none),
  ("BHAIKSUKI LETTER DDA", "Lo", 0, none),
  ("BHAIKSUKI LETTER DDHA", "Lo", 0, none),
  ("BHAIKSUKI LETTER NNA", "Lo", 0, none),
  ("BHAIKSUKI LETTER TA", "Lo", 0, none),
  ("BHAIKSUKI LETTER THA", "Lo", 0, none),
  ("BHAIKSUKI LETTER DA", "Lo", 0, none),
  ("BHAIKSUKI LETTER DHA", "Lo", 0, none),
  ("BHAIKSUKI LETTER NA", "Lo", 0, none),
  ("BHAIKSUKI LETTER PA", "Lo", 0, none),
  ("BHAIKSUKI LETTER PHA", "Lo", 0, none),
  ("BHAIKSUKI LETTER BA", "Lo", 0, none),
  ("BHAIKSUKI LETTER BHA", "Lo", 0, none),
  ("BHAIKSUKI LETTER MA", "Lo", 0, none),
  ("BHAIKSUKI LETTER YA", "Lo", 0, none),
  ("BHAIKSUKI LETTER RA", "Lo", 0, none),
  ("BHAIKSUKI LETTER LA", "Lo", 0, none),
  ("BHAIKSUKI LETTER VA", "Lo", 0, none),
  ("BHAIKSUKI LETTER SHA", "Lo", 0, none),
  ("BHAIKSUKI LETTER SSA", "Lo", 0, none),
  ("BHAIKSUKI LETTER SA", "Lo", 0, none),
  ("BHAIKSUKI LETTER HA", "Lo", 0, none),
  ("BHAIKSUKI VOWEL SIGN AA", "Mc", 0, none),
  ("BHAIKSUKI VOWEL SIGN I", "Mn", 0, none),
  ("BHAIKSUKI VOWEL SIGN II", "Mn", 0, none),
  ("BHAIKSUKI VOWEL SIGN U", "Mn", 0, none),
  ("BHAIKSUKI VOWEL SIGN UU", "Mn", 0, none),
  ("BHAIKSUKI VOWEL SIGN VOCALIC R", "Mn", 0, none),
  ("BHAIKSUKI VOWEL SIGN VOCALIC RR", "Mn", 0, none),
  ("BHAIKSUKI VOWEL SIGN VOCALIC L", "Mn", 0, none),
  (),
  ("BHAIKSUKI VOWEL SIGN E", "Mn", 0, none),
  ("BHAIKSUKI VOWEL SIGN AI", "Mn", 0, none),
  ("BHAIKSUKI VOWEL SIGN O", "Mn", 0, none),
  ("BHAIKSUKI VOWEL SIGN AU", "Mn", 0, none),
  ("BHAIKSUKI SIGN CANDRABINDU", "Mn", 0, none),
  ("BHAIKSUKI SIGN ANUSVARA", "Mn", 0, none),
  ("BHAIKSUKI SIGN VISARGA", "Mc", 0, none),
  ("BHAIKSUKI SIGN VIRAMA", "Mn", 9, none),
  ("BHAIKSUKI SIGN AVAGRAHA", "Lo", 0, none),
  ("BHAIKSUKI DANDA", "Po", 0, none),
  ("BHAIKSUKI DOUBLE DANDA", "Po", 0, none),
  ("BHAIKSUKI WORD SEPARATOR", "Po", 0, none),
  ("BHAIKSUKI GAP FILLER-1", "Po", 0, none),
  ("BHAIKSUKI GAP FILLER-2", "Po", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("BHAIKSUKI DIGIT ZERO", "Nd", 0, none),
  ("BHAIKSUKI DIGIT ONE", "Nd", 0, none),
  ("BHAIKSUKI DIGIT TWO", "Nd", 0, none),
  ("BHAIKSUKI DIGIT THREE", "Nd", 0, none),
  ("BHAIKSUKI DIGIT FOUR", "Nd", 0, none),
  ("BHAIKSUKI DIGIT FIVE", "Nd", 0, none),
  ("BHAIKSUKI DIGIT SIX", "Nd", 0, none),
  ("BHAIKSUKI DIGIT SEVEN", "Nd", 0, none),
  ("BHAIKSUKI DIGIT EIGHT", "Nd", 0, none),
  ("BHAIKSUKI DIGIT NINE", "Nd", 0, none),
  ("BHAIKSUKI NUMBER ONE", "No", 0, none),
  ("BHAIKSUKI NUMBER TWO", "No", 0, none),
  ("BHAIKSUKI NUMBER THREE", "No", 0, none),
  ("BHAIKSUKI NUMBER FOUR", "No", 0, none),
  ("BHAIKSUKI NUMBER FIVE", "No", 0, none),
  ("BHAIKSUKI NUMBER SIX", "No", 0, none),
  ("BHAIKSUKI NUMBER SEVEN", "No", 0, none),
  ("BHAIKSUKI NUMBER EIGHT", "No", 0, none),
  ("BHAIKSUKI NUMBER NINE", "No", 0, none),
  ("BHAIKSUKI NUMBER TEN", "No", 0, none),
  ("BHAIKSUKI NUMBER TWENTY", "No", 0, none),
  ("BHAIKSUKI NUMBER THIRTY", "No", 0, none),
  ("BHAIKSUKI NUMBER FORTY", "No", 0, none),
  ("BHAIKSUKI NUMBER FIFTY", "No", 0, none),
  ("BHAIKSUKI NUMBER SIXTY", "No", 0, none),
  ("BHAIKSUKI NUMBER SEVENTY", "No", 0, none),
  ("BHAIKSUKI NUMBER EIGHTY", "No", 0, none),
  ("BHAIKSUKI NUMBER NINETY", "No", 0, none),
  ("BHAIKSUKI HUNDREDS UNIT MARK", "No", 0, none),
)
