#let data = (
  ("BENGALI ANJI", "Lo", 0, none),
  ("BENGALI SIGN CANDRABINDU", "Mn", 0, none),
  ("BENGALI SIGN ANUSVARA", "Mc", 0, none),
  ("BENGALI SIGN VISARGA", "Mc", 0, none),
  (),
  ("BENGALI LETTER A", "Lo", 0, none),
  ("BENGALI LETTER AA", "Lo", 0, none),
  ("BENGALI LETTER I", "Lo", 0, none),
  ("BENGALI LETTER II", "Lo", 0, none),
  ("BENGALI LETTER U", "Lo", 0, none),
  ("BENGALI LETTER UU", "Lo", 0, none),
  ("BENGALI LETTER VOCALIC R", "Lo", 0, none),
  ("BENGALI LETTER VOCALIC L", "Lo", 0, none),
  (),
  (),
  ("BENGALI LETTER E", "Lo", 0, none),
  ("BENGALI LETTER AI", "Lo", 0, none),
  (),
  (),
  ("BENGALI LETTER O", "Lo", 0, none),
  ("BENGALI LETTER AU", "Lo", 0, none),
  ("BENGALI LETTER KA", "Lo", 0, none),
  ("BENGALI LETTER KHA", "Lo", 0, none),
  ("BENGALI LETTER GA", "Lo", 0, none),
  ("BENGALI LETTER GHA", "Lo", 0, none),
  ("BENGALI LETTER NGA", "Lo", 0, none),
  ("BENGALI LETTER CA", "Lo", 0, none),
  ("BENGALI LETTER CHA", "Lo", 0, none),
  ("BENGALI LETTER JA", "Lo", 0, none),
  ("BENGALI LETTER JHA", "Lo", 0, none),
  ("BENGALI LETTER NYA", "Lo", 0, none),
  ("BENGALI LETTER TTA", "Lo", 0, none),
  ("BENGALI LETTER TTHA", "Lo", 0, none),
  ("BENGALI LETTER DDA", "Lo", 0, none),
  ("BENGALI LETTER DDHA", "Lo", 0, none),
  ("BENGALI LETTER NNA", "Lo", 0, none),
  ("BENGALI LETTER TA", "Lo", 0, none),
  ("BENGALI LETTER THA", "Lo", 0, none),
  ("BENGALI LETTER DA", "Lo", 0, none),
  ("BENGALI LETTER DHA", "Lo", 0, none),
  ("BENGALI LETTER NA", "Lo", 0, none),
  (),
  ("BENGALI LETTER PA", "Lo", 0, none),
  ("BENGALI LETTER PHA", "Lo", 0, none),
  ("BENGALI LETTER BA", "Lo", 0, none),
  ("BENGALI LETTER BHA", "Lo", 0, none),
  ("BENGALI LETTER MA", "Lo", 0, none),
  ("BENGALI LETTER YA", "Lo", 0, none),
  ("BENGALI LETTER RA", "Lo", 0, none),
  (),
  ("BENGALI LETTER LA", "Lo", 0, none),
  (),
  (),
  (),
  ("BENGALI LETTER SHA", "Lo", 0, none),
  ("BENGALI LETTER SSA", "Lo", 0, none),
  ("BENGALI LETTER SA", "Lo", 0, none),
  ("BENGALI LETTER HA", "Lo", 0, none),
  (),
  (),
  ("BENGALI SIGN NUKTA", "Mn", 7, none),
  ("BENGALI SIGN AVAGRAHA", "Lo", 0, none),
  ("BENGALI VOWEL SIGN AA", "Mc", 0, none),
  ("BENGALI VOWEL SIGN I", "Mc", 0, none),
  ("BENGALI VOWEL SIGN II", "Mc", 0, none),
  ("BENGALI VOWEL SIGN U", "Mn", 0, none),
  ("BENGALI VOWEL SIGN UU", "Mn", 0, none),
  ("BENGALI VOWEL SIGN VOCALIC R", "Mn", 0, none),
  ("BENGALI VOWEL SIGN VOCALIC RR", "Mn", 0, none),
  (),
  (),
  ("BENGALI VOWEL SIGN E", "Mc", 0, none),
  ("BENGALI VOWEL SIGN AI", "Mc", 0, none),
  (),
  (),
  ("BENGALI VOWEL SIGN O", "Mc", 0, none),
  ("BENGALI VOWEL SIGN AU", "Mc", 0, none),
  ("BENGALI SIGN VIRAMA", "Mn", 9, none),
  ("BENGALI LETTER KHANDA TA", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("BENGALI AU LENGTH MARK", "Mc", 0, none),
  (),
  (),
  (),
  (),
  ("BENGALI LETTER RRA", "Lo", 0, none),
  ("BENGALI LETTER RHA", "Lo", 0, none),
  (),
  ("BENGALI LETTER YYA", "Lo", 0, none),
  ("BENGALI LETTER VOCALIC RR", "Lo", 0, none),
  ("BENGALI LETTER VOCALIC LL", "Lo", 0, none),
  ("BENGALI VOWEL SIGN VOCALIC L", "Mn", 0, none),
  ("BENGALI VOWEL SIGN VOCALIC LL", "Mn", 0, none),
  (),
  (),
  ("BENGALI DIGIT ZERO", "Nd", 0, none),
  ("BENGALI DIGIT ONE", "Nd", 0, none),
  ("BENGALI DIGIT TWO", "Nd", 0, none),
  ("BENGALI DIGIT THREE", "Nd", 0, none),
  ("BENGALI DIGIT FOUR", "Nd", 0, none),
  ("BENGALI DIGIT FIVE", "Nd", 0, none),
  ("BENGALI DIGIT SIX", "Nd", 0, none),
  ("BENGALI DIGIT SEVEN", "Nd", 0, none),
  ("BENGALI DIGIT EIGHT", "Nd", 0, none),
  ("BENGALI DIGIT NINE", "Nd", 0, none),
  ("BENGALI LETTER RA WITH MIDDLE DIAGONAL", "Lo", 0, none),
  ("BENGALI LETTER RA WITH LOWER DIAGONAL", "Lo", 0, none),
  ("BENGALI RUPEE MARK", "Sc", 0, none),
  ("BENGALI RUPEE SIGN", "Sc", 0, none),
  ("BENGALI CURRENCY NUMERATOR ONE", "No", 0, none),
  ("BENGALI CURRENCY NUMERATOR TWO", "No", 0, none),
  ("BENGALI CURRENCY NUMERATOR THREE", "No", 0, none),
  ("BENGALI CURRENCY NUMERATOR FOUR", "No", 0, none),
  ("BENGALI CURRENCY NUMERATOR ONE LESS THAN THE DENOMINATOR", "No", 0, none),
  ("BENGALI CURRENCY DENOMINATOR SIXTEEN", "No", 0, none),
  ("BENGALI ISSHAR", "So", 0, none),
  ("BENGALI GANDA MARK", "Sc", 0, none),
  ("BENGALI LETTER VEDIC ANUSVARA", "Lo", 0, none),
  ("BENGALI ABBREVIATION SIGN", "Po", 0, none),
  ("BENGALI SANDHI MARK", "Mn", 230, none),
)
