#let data = (
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("<control>", "Cc", 0, none),
  ("NO-BREAK SPACE", "Zs", 0, "S"),
  ("INVERTED EXCLAMATION MARK", "Po", 0, "P"),
  ("CENT SIGN", "Sc", 0, "N"),
  ("POUND SIGN", "Sc", 0, "N"),
  ("CURRENCY SIGN", "Sc", 0, "N"),
  ("YEN SIGN", "Sc", 0, "N"),
  ("BROKEN BAR", "So", 0, "N"),
  ("SECTION SIGN", "Po", 0, "N"),
  ("DIAERESIS", "Sk", 0, "D"),
  ("COPYRIGHT SIGN", "So", 0, none),
  ("FEMININE ORDINAL INDICATOR", "Lo", 0, none),
  ("LEFT-POINTING DOUBLE ANGLE QUOTATION MARK", "Pi", 0, none),
  ("NOT SIGN", "Sm", 0, "U"),
  ("SOFT HYPHEN", "Cf", 0, none),
  ("REGISTERED SIGN", "So", 0, none),
  ("MACRON", "Sk", 0, "D"),
  ("DEGREE SIGN", "So", 0, "N"),
  ("PLUS-MINUS SIGN", "Sm", 0, "V"),
  ("SUPERSCRIPT TWO", "No", 0, "N"),
  ("SUPERSCRIPT THREE", "No", 0, "N"),
  ("ACUTE ACCENT", "Sk", 0, "N"),
  ("MICRO SIGN", "Ll", 0, "N"),
  ("PILCROW SIGN", "Po", 0, "N"),
  ("MIDDLE DOT", "Po", 0, "B"),
  ("CEDILLA", "Sk", 0, none),
  ("SUPERSCRIPT ONE", "No", 0, "N"),
  ("MASCULINE ORDINAL INDICATOR", "Lo", 0, none),
  ("RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK", "Pf", 0, none),
  ("VULGAR FRACTION ONE QUARTER", "No", 0, "N"),
  ("VULGAR FRACTION ONE HALF", "No", 0, "N"),
  ("VULGAR FRACTION THREE QUARTERS", "No", 0, "N"),
  ("INVERTED QUESTION MARK", "Po", 0, "P"),
  ("LATIN CAPITAL LETTER A WITH GRAVE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER A WITH ACUTE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER A WITH CIRCUMFLEX", "Lu", 0, none),
  ("LATIN CAPITAL LETTER A WITH TILDE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER A WITH DIAERESIS", "Lu", 0, none),
  ("LATIN CAPITAL LETTER A WITH RING ABOVE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER AE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER C WITH CEDILLA", "Lu", 0, none),
  ("LATIN CAPITAL LETTER E WITH GRAVE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER E WITH ACUTE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER E WITH CIRCUMFLEX", "Lu", 0, none),
  ("LATIN CAPITAL LETTER E WITH DIAERESIS", "Lu", 0, none),
  ("LATIN CAPITAL LETTER I WITH GRAVE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER I WITH ACUTE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER I WITH CIRCUMFLEX", "Lu", 0, none),
  ("LATIN CAPITAL LETTER I WITH DIAERESIS", "Lu", 0, none),
  ("LATIN CAPITAL LETTER ETH", "Lu", 0, none),
  ("LATIN CAPITAL LETTER N WITH TILDE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER O WITH GRAVE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER O WITH ACUTE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER O WITH CIRCUMFLEX", "Lu", 0, none),
  ("LATIN CAPITAL LETTER O WITH TILDE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER O WITH DIAERESIS", "Lu", 0, none),
  ("MULTIPLICATION SIGN", "Sm", 0, "B"),
  ("LATIN CAPITAL LETTER O WITH STROKE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER U WITH GRAVE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER U WITH ACUTE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER U WITH CIRCUMFLEX", "Lu", 0, none),
  ("LATIN CAPITAL LETTER U WITH DIAERESIS", "Lu", 0, none),
  ("LATIN CAPITAL LETTER Y WITH ACUTE", "Lu", 0, none),
  ("LATIN CAPITAL LETTER THORN", "Lu", 0, none),
  ("LATIN SMALL LETTER SHARP S", "Ll", 0, none),
  ("LATIN SMALL LETTER A WITH GRAVE", "Ll", 0, none),
  ("LATIN SMALL LETTER A WITH ACUTE", "Ll", 0, none),
  ("LATIN SMALL LETTER A WITH CIRCUMFLEX", "Ll", 0, none),
  ("LATIN SMALL LETTER A WITH TILDE", "Ll", 0, none),
  ("LATIN SMALL LETTER A WITH DIAERESIS", "Ll", 0, none),
  ("LATIN SMALL LETTER A WITH RING ABOVE", "Ll", 0, none),
  ("LATIN SMALL LETTER AE", "Ll", 0, none),
  ("LATIN SMALL LETTER C WITH CEDILLA", "Ll", 0, none),
  ("LATIN SMALL LETTER E WITH GRAVE", "Ll", 0, none),
  ("LATIN SMALL LETTER E WITH ACUTE", "Ll", 0, none),
  ("LATIN SMALL LETTER E WITH CIRCUMFLEX", "Ll", 0, none),
  ("LATIN SMALL LETTER E WITH DIAERESIS", "Ll", 0, none),
  ("LATIN SMALL LETTER I WITH GRAVE", "Ll", 0, none),
  ("LATIN SMALL LETTER I WITH ACUTE", "Ll", 0, none),
  ("LATIN SMALL LETTER I WITH CIRCUMFLEX", "Ll", 0, none),
  ("LATIN SMALL LETTER I WITH DIAERESIS", "Ll", 0, none),
  ("LATIN SMALL LETTER ETH", "Ll", 0, none),
  ("LATIN SMALL LETTER N WITH TILDE", "Ll", 0, none),
  ("LATIN SMALL LETTER O WITH GRAVE", "Ll", 0, none),
  ("LATIN SMALL LETTER O WITH ACUTE", "Ll", 0, none),
  ("LATIN SMALL LETTER O WITH CIRCUMFLEX", "Ll", 0, none),
  ("LATIN SMALL LETTER O WITH TILDE", "Ll", 0, none),
  ("LATIN SMALL LETTER O WITH DIAERESIS", "Ll", 0, none),
  ("DIVISION SIGN", "Sm", 0, "B"),
  ("LATIN SMALL LETTER O WITH STROKE", "Ll", 0, none),
  ("LATIN SMALL LETTER U WITH GRAVE", "Ll", 0, none),
  ("LATIN SMALL LETTER U WITH ACUTE", "Ll", 0, none),
  ("LATIN SMALL LETTER U WITH CIRCUMFLEX", "Ll", 0, none),
  ("LATIN SMALL LETTER U WITH DIAERESIS", "Ll", 0, none),
  ("LATIN SMALL LETTER Y WITH ACUTE", "Ll", 0, none),
  ("LATIN SMALL LETTER THORN", "Ll", 0, none),
  ("LATIN SMALL LETTER Y WITH DIAERESIS", "Ll", 0, none),
)
