#let data = (
  ("GRANTHA SIGN COMBINING ANUSVARA ABOVE", "Mn", 0, none),
  ("GRANTHA SIGN CANDRABINDU", "Mn", 0, none),
  ("GRANTHA SIGN ANUSVARA", "Mc", 0, none),
  ("GRANTHA SIGN VISARGA", "Mc", 0, none),
  (),
  ("GRANTHA LETTER A", "Lo", 0, none),
  ("GRANTHA LETTER AA", "Lo", 0, none),
  ("GRANTHA LETTER I", "Lo", 0, none),
  ("GRANTHA LETTER II", "Lo", 0, none),
  ("GRANTHA LETTER U", "Lo", 0, none),
  ("GRANTHA LETTER UU", "Lo", 0, none),
  ("GRANTHA LETTER VOCALIC R", "Lo", 0, none),
  ("GRANTHA LETTER VOCALIC L", "Lo", 0, none),
  (),
  (),
  ("GRANTHA LETTER EE", "Lo", 0, none),
  ("GRANTHA LETTER AI", "Lo", 0, none),
  (),
  (),
  ("GRANTHA LETTER OO", "Lo", 0, none),
  ("GRANTHA LETTER AU", "Lo", 0, none),
  ("GRANTHA LETTER KA", "Lo", 0, none),
  ("GRANTHA LETTER KHA", "Lo", 0, none),
  ("GRANTHA LETTER GA", "Lo", 0, none),
  ("GRANTHA LETTER GHA", "Lo", 0, none),
  ("GRANTHA LETTER NGA", "Lo", 0, none),
  ("GRANTHA LETTER CA", "Lo", 0, none),
  ("GRANTHA LETTER CHA", "Lo", 0, none),
  ("GRANTHA LETTER JA", "Lo", 0, none),
  ("GRANTHA LETTER JHA", "Lo", 0, none),
  ("GRANTHA LETTER NYA", "Lo", 0, none),
  ("GRANTHA LETTER TTA", "Lo", 0, none),
  ("GRANTHA LETTER TTHA", "Lo", 0, none),
  ("GRANTHA LETTER DDA", "Lo", 0, none),
  ("GRANTHA LETTER DDHA", "Lo", 0, none),
  ("GRANTHA LETTER NNA", "Lo", 0, none),
  ("GRANTHA LETTER TA", "Lo", 0, none),
  ("GRANTHA LETTER THA", "Lo", 0, none),
  ("GRANTHA LETTER DA", "Lo", 0, none),
  ("GRANTHA LETTER DHA", "Lo", 0, none),
  ("GRANTHA LETTER NA", "Lo", 0, none),
  (),
  ("GRANTHA LETTER PA", "Lo", 0, none),
  ("GRANTHA LETTER PHA", "Lo", 0, none),
  ("GRANTHA LETTER BA", "Lo", 0, none),
  ("GRANTHA LETTER BHA", "Lo", 0, none),
  ("GRANTHA LETTER MA", "Lo", 0, none),
  ("GRANTHA LETTER YA", "Lo", 0, none),
  ("GRANTHA LETTER RA", "Lo", 0, none),
  (),
  ("GRANTHA LETTER LA", "Lo", 0, none),
  ("GRANTHA LETTER LLA", "Lo", 0, none),
  (),
  ("GRANTHA LETTER VA", "Lo", 0, none),
  ("GRANTHA LETTER SHA", "Lo", 0, none),
  ("GRANTHA LETTER SSA", "Lo", 0, none),
  ("GRANTHA LETTER SA", "Lo", 0, none),
  ("GRANTHA LETTER HA", "Lo", 0, none),
  (),
  ("COMBINING BINDU BELOW", "Mn", 7, none),
  ("GRANTHA SIGN NUKTA", "Mn", 7, none),
  ("GRANTHA SIGN AVAGRAHA", "Lo", 0, none),
  ("GRANTHA VOWEL SIGN AA", "Mc", 0, none),
  ("GRANTHA VOWEL SIGN I", "Mc", 0, none),
  ("GRANTHA VOWEL SIGN II", "Mn", 0, none),
  ("GRANTHA VOWEL SIGN U", "Mc", 0, none),
  ("GRANTHA VOWEL SIGN UU", "Mc", 0, none),
  ("GRANTHA VOWEL SIGN VOCALIC R", "Mc", 0, none),
  ("GRANTHA VOWEL SIGN VOCALIC RR", "Mc", 0, none),
  (),
  (),
  ("GRANTHA VOWEL SIGN EE", "Mc", 0, none),
  ("GRANTHA VOWEL SIGN AI", "Mc", 0, none),
  (),
  (),
  ("GRANTHA VOWEL SIGN OO", "Mc", 0, none),
  ("GRANTHA VOWEL SIGN AU", "Mc", 0, none),
  ("GRANTHA SIGN VIRAMA", "Mc", 9, none),
  (),
  (),
  ("GRANTHA OM", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  ("GRANTHA AU LENGTH MARK", "Mc", 0, none),
  (),
  (),
  (),
  (),
  (),
  ("GRANTHA SIGN PLUTA", "Lo", 0, none),
  ("GRANTHA LETTER VEDIC ANUSVARA", "Lo", 0, none),
  ("GRANTHA LETTER VEDIC DOUBLE ANUSVARA", "Lo", 0, none),
  ("GRANTHA LETTER VOCALIC RR", "Lo", 0, none),
  ("GRANTHA LETTER VOCALIC LL", "Lo", 0, none),
  ("GRANTHA VOWEL SIGN VOCALIC L", "Mc", 0, none),
  ("GRANTHA VOWEL SIGN VOCALIC LL", "Mc", 0, none),
  (),
  (),
  ("COMBINING GRANTHA DIGIT ZERO", "Mn", 230, none),
  ("COMBINING GRANTHA DIGIT ONE", "Mn", 230, none),
  ("COMBINING GRANTHA DIGIT TWO", "Mn", 230, none),
  ("COMBINING GRANTHA DIGIT THREE", "Mn", 230, none),
  ("COMBINING GRANTHA DIGIT FOUR", "Mn", 230, none),
  ("COMBINING GRANTHA DIGIT FIVE", "Mn", 230, none),
  ("COMBINING GRANTHA DIGIT SIX", "Mn", 230, none),
  (),
  (),
  (),
  ("COMBINING GRANTHA LETTER A", "Mn", 230, none),
  ("COMBINING GRANTHA LETTER KA", "Mn", 230, none),
  ("COMBINING GRANTHA LETTER NA", "Mn", 230, none),
  ("COMBINING GRANTHA LETTER VI", "Mn", 230, none),
  ("COMBINING GRANTHA LETTER PA", "Mn", 230, none),
)
