#let data = (
  ("LEPCHA LETTER KA", "Lo", 0, none),
  ("LEPCHA LETTER KLA", "Lo", 0, none),
  ("LEPCHA LETTER KHA", "Lo", 0, none),
  ("LEPCHA LETTER GA", "Lo", 0, none),
  ("LEPCHA LETTER GLA", "Lo", 0, none),
  ("LEPCHA LETTER NGA", "Lo", 0, none),
  ("LEPCHA LETTER CA", "Lo", 0, none),
  ("LEPCHA LETTER CHA", "Lo", 0, none),
  ("LEPCHA LETTER JA", "Lo", 0, none),
  ("LEPCHA LETTER NYA", "Lo", 0, none),
  ("LEPCHA LETTER TA", "Lo", 0, none),
  ("LEPCHA LETTER THA", "Lo", 0, none),
  ("LEPCHA LETTER DA", "Lo", 0, none),
  ("LEPCHA LETTER NA", "Lo", 0, none),
  ("LEPCHA LETTER PA", "Lo", 0, none),
  ("LEPCHA LETTER PLA", "Lo", 0, none),
  ("LEPCHA LETTER PHA", "Lo", 0, none),
  ("LEPCHA LETTER FA", "Lo", 0, none),
  ("LEPCHA LETTER FLA", "Lo", 0, none),
  ("LEPCHA LETTER BA", "Lo", 0, none),
  ("LEPCHA LETTER BLA", "Lo", 0, none),
  ("LEPCHA LETTER MA", "Lo", 0, none),
  ("LEPCHA LETTER MLA", "Lo", 0, none),
  ("LEPCHA LETTER TSA", "Lo", 0, none),
  ("LEPCHA LETTER TSHA", "Lo", 0, none),
  ("LEPCHA LETTER DZA", "Lo", 0, none),
  ("LEPCHA LETTER YA", "Lo", 0, none),
  ("LEPCHA LETTER RA", "Lo", 0, none),
  ("LEPCHA LETTER LA", "Lo", 0, none),
  ("LEPCHA LETTER HA", "Lo", 0, none),
  ("LEPCHA LETTER HLA", "Lo", 0, none),
  ("LEPCHA LETTER VA", "Lo", 0, none),
  ("LEPCHA LETTER SA", "Lo", 0, none),
  ("LEPCHA LETTER SHA", "Lo", 0, none),
  ("LEPCHA LETTER WA", "Lo", 0, none),
  ("LEPCHA LETTER A", "Lo", 0, none),
  ("LEPCHA SUBJOINED LETTER YA", "Mc", 0, none),
  ("LEPCHA SUBJOINED LETTER RA", "Mc", 0, none),
  ("LEPCHA VOWEL SIGN AA", "Mc", 0, none),
  ("LEPCHA VOWEL SIGN I", "Mc", 0, none),
  ("LEPCHA VOWEL SIGN O", "Mc", 0, none),
  ("LEPCHA VOWEL SIGN OO", "Mc", 0, none),
  ("LEPCHA VOWEL SIGN U", "Mc", 0, none),
  ("LEPCHA VOWEL SIGN UU", "Mc", 0, none),
  ("LEPCHA VOWEL SIGN E", "Mn", 0, none),
  ("LEPCHA CONSONANT SIGN K", "Mn", 0, none),
  ("LEPCHA CONSONANT SIGN M", "Mn", 0, none),
  ("LEPCHA CONSONANT SIGN L", "Mn", 0, none),
  ("LEPCHA CONSONANT SIGN N", "Mn", 0, none),
  ("LEPCHA CONSONANT SIGN P", "Mn", 0, none),
  ("LEPCHA CONSONANT SIGN R", "Mn", 0, none),
  ("LEPCHA CONSONANT SIGN T", "Mn", 0, none),
  ("LEPCHA CONSONANT SIGN NYIN-DO", "Mc", 0, none),
  ("LEPCHA CONSONANT SIGN KANG", "Mc", 0, none),
  ("LEPCHA SIGN RAN", "Mn", 0, none),
  ("LEPCHA SIGN NUKTA", "Mn", 7, none),
  (),
  (),
  (),
  ("LEPCHA PUNCTUATION TA-ROL", "Po", 0, none),
  ("LEPCHA PUNCTUATION NYET THYOOM TA-ROL", "Po", 0, none),
  ("LEPCHA PUNCTUATION CER-WA", "Po", 0, none),
  ("LEPCHA PUNCTUATION TSHOOK CER-WA", "Po", 0, none),
  ("LEPCHA PUNCTUATION TSHOOK", "Po", 0, none),
  ("LEPCHA DIGIT ZERO", "Nd", 0, none),
  ("LEPCHA DIGIT ONE", "Nd", 0, none),
  ("LEPCHA DIGIT TWO", "Nd", 0, none),
  ("LEPCHA DIGIT THREE", "Nd", 0, none),
  ("LEPCHA DIGIT FOUR", "Nd", 0, none),
  ("LEPCHA DIGIT FIVE", "Nd", 0, none),
  ("LEPCHA DIGIT SIX", "Nd", 0, none),
  ("LEPCHA DIGIT SEVEN", "Nd", 0, none),
  ("LEPCHA DIGIT EIGHT", "Nd", 0, none),
  ("LEPCHA DIGIT NINE", "Nd", 0, none),
  (),
  (),
  (),
  ("LEPCHA LETTER TTA", "Lo", 0, none),
  ("LEPCHA LETTER TTHA", "Lo", 0, none),
  ("LEPCHA LETTER DDA", "Lo", 0, none),
)
