#let data = (
  ("MAHJONG TILE EAST WIND", "So", 0, none),
  ("MAHJONG TILE SOUTH WIND", "So", 0, none),
  ("MAHJONG TILE WEST WIND", "So", 0, none),
  ("MAHJONG TILE NORTH WIND", "So", 0, none),
  ("MAHJONG TILE RED DRAGON", "So", 0, none),
  ("MAHJONG TILE GREEN DRAGON", "So", 0, none),
  ("MAHJONG TILE WHITE DRAGON", "So", 0, none),
  ("MAHJONG TILE ONE OF CHARACTERS", "So", 0, none),
  ("MAHJONG TILE TWO OF CHARACTERS", "So", 0, none),
  ("MAHJONG TILE THREE OF CHARACTERS", "So", 0, none),
  ("MAHJONG TILE FOUR OF CHARACTERS", "So", 0, none),
  ("MAHJONG TILE FIVE OF CHARACTERS", "So", 0, none),
  ("MAHJONG TILE SIX OF CHARACTERS", "So", 0, none),
  ("MAHJONG TILE SEVEN OF CHARACTERS", "So", 0, none),
  ("MAHJONG TILE EIGHT OF CHARACTERS", "So", 0, none),
  ("MAHJONG TILE NINE OF CHARACTERS", "So", 0, none),
  ("MAHJONG TILE ONE OF BAMBOOS", "So", 0, none),
  ("MAHJONG TILE TWO OF BAMBOOS", "So", 0, none),
  ("MAHJONG TILE THREE OF BAMBOOS", "So", 0, none),
  ("MAHJONG TILE FOUR OF BAMBOOS", "So", 0, none),
  ("MAHJONG TILE FIVE OF BAMBOOS", "So", 0, none),
  ("MAHJONG TILE SIX OF BAMBOOS", "So", 0, none),
  ("MAHJONG TILE SEVEN OF BAMBOOS", "So", 0, none),
  ("MAHJONG TILE EIGHT OF BAMBOOS", "So", 0, none),
  ("MAHJONG TILE NINE OF BAMBOOS", "So", 0, none),
  ("MAHJONG TILE ONE OF CIRCLES", "So", 0, none),
  ("MAHJONG TILE TWO OF CIRCLES", "So", 0, none),
  ("MAHJONG TILE THREE OF CIRCLES", "So", 0, none),
  ("MAHJONG TILE FOUR OF CIRCLES", "So", 0, none),
  ("MAHJONG TILE FIVE OF CIRCLES", "So", 0, none),
  ("MAHJONG TILE SIX OF CIRCLES", "So", 0, none),
  ("MAHJONG TILE SEVEN OF CIRCLES", "So", 0, none),
  ("MAHJONG TILE EIGHT OF CIRCLES", "So", 0, none),
  ("MAHJONG TILE NINE OF CIRCLES", "So", 0, none),
  ("MAHJONG TILE PLUM", "So", 0, none),
  ("MAHJONG TILE ORCHID", "So", 0, none),
  ("MAHJONG TILE BAMBOO", "So", 0, none),
  ("MAHJONG TILE CHRYSANTHEMUM", "So", 0, none),
  ("MAHJONG TILE SPRING", "So", 0, none),
  ("MAHJONG TILE SUMMER", "So", 0, none),
  ("MAHJONG TILE AUTUMN", "So", 0, none),
  ("MAHJONG TILE WINTER", "So", 0, none),
  ("MAHJONG TILE JOKER", "So", 0, none),
  ("MAHJONG TILE BACK", "So", 0, none),
)
