#let data = (
  ("MALAYALAM SIGN COMBINING ANUSVARA ABOVE", "Mn", 0, none),
  ("MALAYALAM SIGN CANDRABINDU", "Mn", 0, none),
  ("MALAYALAM SIGN ANUSVARA", "Mc", 0, none),
  ("MALAYALAM SIGN VISARGA", "Mc", 0, none),
  ("MALAYALAM LETTER VEDIC ANUSVARA", "Lo", 0, none),
  ("MALAYALAM LETTER A", "Lo", 0, none),
  ("MALAYALAM LETTER AA", "Lo", 0, none),
  ("MALAYALAM LETTER I", "Lo", 0, none),
  ("MALAYALAM LETTER II", "Lo", 0, none),
  ("MALAYALAM LETTER U", "Lo", 0, none),
  ("MALAYALAM LETTER UU", "Lo", 0, none),
  ("MALAYALAM LETTER VOCALIC R", "Lo", 0, none),
  ("MALAYALAM LETTER VOCALIC L", "Lo", 0, none),
  (),
  ("MALAYALAM LETTER E", "Lo", 0, none),
  ("MALAYALAM LETTER EE", "Lo", 0, none),
  ("MALAYALAM LETTER AI", "Lo", 0, none),
  (),
  ("MALAYALAM LETTER O", "Lo", 0, none),
  ("MALAYALAM LETTER OO", "Lo", 0, none),
  ("MALAYALAM LETTER AU", "Lo", 0, none),
  ("MALAYALAM LETTER KA", "Lo", 0, none),
  ("MALAYALAM LETTER KHA", "Lo", 0, none),
  ("MALAYALAM LETTER GA", "Lo", 0, none),
  ("MALAYALAM LETTER GHA", "Lo", 0, none),
  ("MALAYALAM LETTER NGA", "Lo", 0, none),
  ("MALAYALAM LETTER CA", "Lo", 0, none),
  ("MALAYALAM LETTER CHA", "Lo", 0, none),
  ("MALAYALAM LETTER JA", "Lo", 0, none),
  ("MALAYALAM LETTER JHA", "Lo", 0, none),
  ("MALAYALAM LETTER NYA", "Lo", 0, none),
  ("MALAYALAM LETTER TTA", "Lo", 0, none),
  ("MALAYALAM LETTER TTHA", "Lo", 0, none),
  ("MALAYALAM LETTER DDA", "Lo", 0, none),
  ("MALAYALAM LETTER DDHA", "Lo", 0, none),
  ("MALAYALAM LETTER NNA", "Lo", 0, none),
  ("MALAYALAM LETTER TA", "Lo", 0, none),
  ("MALAYALAM LETTER THA", "Lo", 0, none),
  ("MALAYALAM LETTER DA", "Lo", 0, none),
  ("MALAYALAM LETTER DHA", "Lo", 0, none),
  ("MALAYALAM LETTER NA", "Lo", 0, none),
  ("MALAYALAM LETTER NNNA", "Lo", 0, none),
  ("MALAYALAM LETTER PA", "Lo", 0, none),
  ("MALAYALAM LETTER PHA", "Lo", 0, none),
  ("MALAYALAM LETTER BA", "Lo", 0, none),
  ("MALAYALAM LETTER BHA", "Lo", 0, none),
  ("MALAYALAM LETTER MA", "Lo", 0, none),
  ("MALAYALAM LETTER YA", "Lo", 0, none),
  ("MALAYALAM LETTER RA", "Lo", 0, none),
  ("MALAYALAM LETTER RRA", "Lo", 0, none),
  ("MALAYALAM LETTER LA", "Lo", 0, none),
  ("MALAYALAM LETTER LLA", "Lo", 0, none),
  ("MALAYALAM LETTER LLLA", "Lo", 0, none),
  ("MALAYALAM LETTER VA", "Lo", 0, none),
  ("MALAYALAM LETTER SHA", "Lo", 0, none),
  ("MALAYALAM LETTER SSA", "Lo", 0, none),
  ("MALAYALAM LETTER SA", "Lo", 0, none),
  ("MALAYALAM LETTER HA", "Lo", 0, none),
  ("MALAYALAM LETTER TTTA", "Lo", 0, none),
  ("MALAYALAM SIGN VERTICAL BAR VIRAMA", "Mn", 9, none),
  ("MALAYALAM SIGN CIRCULAR VIRAMA", "Mn", 9, none),
  ("MALAYALAM SIGN AVAGRAHA", "Lo", 0, none),
  ("MALAYALAM VOWEL SIGN AA", "Mc", 0, none),
  ("MALAYALAM VOWEL SIGN I", "Mc", 0, none),
  ("MALAYALAM VOWEL SIGN II", "Mc", 0, none),
  ("MALAYALAM VOWEL SIGN U", "Mn", 0, none),
  ("MALAYALAM VOWEL SIGN UU", "Mn", 0, none),
  ("MALAYALAM VOWEL SIGN VOCALIC R", "Mn", 0, none),
  ("MALAYALAM VOWEL SIGN VOCALIC RR", "Mn", 0, none),
  (),
  ("MALAYALAM VOWEL SIGN E", "Mc", 0, none),
  ("MALAYALAM VOWEL SIGN EE", "Mc", 0, none),
  ("MALAYALAM VOWEL SIGN AI", "Mc", 0, none),
  (),
  ("MALAYALAM VOWEL SIGN O", "Mc", 0, none),
  ("MALAYALAM VOWEL SIGN OO", "Mc", 0, none),
  ("MALAYALAM VOWEL SIGN AU", "Mc", 0, none),
  ("MALAYALAM SIGN VIRAMA", "Mn", 9, none),
  ("MALAYALAM LETTER DOT REPH", "Lo", 0, none),
  ("MALAYALAM SIGN PARA", "So", 0, none),
  (),
  (),
  (),
  (),
  ("MALAYALAM LETTER CHILLU M", "Lo", 0, none),
  ("MALAYALAM LETTER CHILLU Y", "Lo", 0, none),
  ("MALAYALAM LETTER CHILLU LLL", "Lo", 0, none),
  ("MALAYALAM AU LENGTH MARK", "Mc", 0, none),
  ("MALAYALAM FRACTION ONE ONE-HUNDRED-AND-SIXTIETH", "No", 0, none),
  ("MALAYALAM FRACTION ONE FORTIETH", "No", 0, none),
  ("MALAYALAM FRACTION THREE EIGHTIETHS", "No", 0, none),
  ("MALAYALAM FRACTION ONE TWENTIETH", "No", 0, none),
  ("MALAYALAM FRACTION ONE TENTH", "No", 0, none),
  ("MALAYALAM FRACTION THREE TWENTIETHS", "No", 0, none),
  ("MALAYALAM FRACTION ONE FIFTH", "No", 0, none),
  ("MALAYALAM LETTER ARCHAIC II", "Lo", 0, none),
  ("MALAYALAM LETTER VOCALIC RR", "Lo", 0, none),
  ("MALAYALAM LETTER VOCALIC LL", "Lo", 0, none),
  ("MALAYALAM VOWEL SIGN VOCALIC L", "Mn", 0, none),
  ("MALAYALAM VOWEL SIGN VOCALIC LL", "Mn", 0, none),
  (),
  (),
  ("MALAYALAM DIGIT ZERO", "Nd", 0, none),
  ("MALAYALAM DIGIT ONE", "Nd", 0, none),
  ("MALAYALAM DIGIT TWO", "Nd", 0, none),
  ("MALAYALAM DIGIT THREE", "Nd", 0, none),
  ("MALAYALAM DIGIT FOUR", "Nd", 0, none),
  ("MALAYALAM DIGIT FIVE", "Nd", 0, none),
  ("MALAYALAM DIGIT SIX", "Nd", 0, none),
  ("MALAYALAM DIGIT SEVEN", "Nd", 0, none),
  ("MALAYALAM DIGIT EIGHT", "Nd", 0, none),
  ("MALAYALAM DIGIT NINE", "Nd", 0, none),
  ("MALAYALAM NUMBER TEN", "No", 0, none),
  ("MALAYALAM NUMBER ONE HUNDRED", "No", 0, none),
  ("MALAYALAM NUMBER ONE THOUSAND", "No", 0, none),
  ("MALAYALAM FRACTION ONE QUARTER", "No", 0, none),
  ("MALAYALAM FRACTION ONE HALF", "No", 0, none),
  ("MALAYALAM FRACTION THREE QUARTERS", "No", 0, none),
  ("MALAYALAM FRACTION ONE SIXTEENTH", "No", 0, none),
  ("MALAYALAM FRACTION ONE EIGHTH", "No", 0, none),
  ("MALAYALAM FRACTION THREE SIXTEENTHS", "No", 0, none),
  ("MALAYALAM DATE MARK", "So", 0, none),
  ("MALAYALAM LETTER CHILLU NN", "Lo", 0, none),
  ("MALAYALAM LETTER CHILLU N", "Lo", 0, none),
  ("MALAYALAM LETTER CHILLU RR", "Lo", 0, none),
  ("MALAYALAM LETTER CHILLU L", "Lo", 0, none),
  ("MALAYALAM LETTER CHILLU LL", "Lo", 0, none),
  ("MALAYALAM LETTER CHILLU K", "Lo", 0, none),
)
