#let data = (
  ("MONOGRAM FOR EARTH", "So", 0, none),
  ("DIGRAM FOR HEAVENLY EARTH", "So", 0, none),
  ("DIGRAM FOR HUMAN EARTH", "So", 0, none),
  ("DIGRAM FOR EARTHLY HEAVEN", "So", 0, none),
  ("DIGRAM FOR EARTHLY HUMAN", "So", 0, none),
  ("DIGRAM FOR EARTH", "So", 0, none),
  ("TETRAGRAM FOR CENTRE", "So", 0, none),
  ("TETRAGRAM FOR FULL CIRCLE", "So", 0, none),
  ("TETRAGRAM FOR MIRED", "So", 0, none),
  ("TETRAGRAM FOR BARRIER", "So", 0, none),
  ("TETRAGRAM FOR KEEPING SMALL", "So", 0, none),
  ("TETRAGRAM FOR CONTRARIETY", "So", 0, none),
  ("TETRAGRAM FOR ASCENT", "So", 0, none),
  ("TETRAGRAM FOR OPPOSITION", "So", 0, none),
  ("TETRAGRAM FOR BRANCHING OUT", "So", 0, none),
  ("TETRAGRAM FOR DEFECTIVENESS OR DISTORTION", "So", 0, none),
  ("TETRAGRAM FOR DIVERGENCE", "So", 0, none),
  ("TETRAGRAM FOR YOUTHFULNESS", "So", 0, none),
  ("TETRAGRAM FOR INCREASE", "So", 0, none),
  ("TETRAGRAM FOR PENETRATION", "So", 0, none),
  ("TETRAGRAM FOR REACH", "So", 0, none),
  ("TETRAGRAM FOR CONTACT", "So", 0, none),
  ("TETRAGRAM FOR HOLDING BACK", "So", 0, none),
  ("TETRAGRAM FOR WAITING", "So", 0, none),
  ("TETRAGRAM FOR FOLLOWING", "So", 0, none),
  ("TETRAGRAM FOR ADVANCE", "So", 0, none),
  ("TETRAGRAM FOR RELEASE", "So", 0, none),
  ("TETRAGRAM FOR RESISTANCE", "So", 0, none),
  ("TETRAGRAM FOR EASE", "So", 0, none),
  ("TETRAGRAM FOR JOY", "So", 0, none),
  ("TETRAGRAM FOR CONTENTION", "So", 0, none),
  ("TETRAGRAM FOR ENDEAVOUR", "So", 0, none),
  ("TETRAGRAM FOR DUTIES", "So", 0, none),
  ("TETRAGRAM FOR CHANGE", "So", 0, none),
  ("TETRAGRAM FOR DECISIVENESS", "So", 0, none),
  ("TETRAGRAM FOR BOLD RESOLUTION", "So", 0, none),
  ("TETRAGRAM FOR PACKING", "So", 0, none),
  ("TETRAGRAM FOR LEGION", "So", 0, none),
  ("TETRAGRAM FOR CLOSENESS", "So", 0, none),
  ("TETRAGRAM FOR KINSHIP", "So", 0, none),
  ("TETRAGRAM FOR GATHERING", "So", 0, none),
  ("TETRAGRAM FOR STRENGTH", "So", 0, none),
  ("TETRAGRAM FOR PURITY", "So", 0, none),
  ("TETRAGRAM FOR FULLNESS", "So", 0, none),
  ("TETRAGRAM FOR RESIDENCE", "So", 0, none),
  ("TETRAGRAM FOR LAW OR MODEL", "So", 0, none),
  ("TETRAGRAM FOR RESPONSE", "So", 0, none),
  ("TETRAGRAM FOR GOING TO MEET", "So", 0, none),
  ("TETRAGRAM FOR ENCOUNTERS", "So", 0, none),
  ("TETRAGRAM FOR STOVE", "So", 0, none),
  ("TETRAGRAM FOR GREATNESS", "So", 0, none),
  ("TETRAGRAM FOR ENLARGEMENT", "So", 0, none),
  ("TETRAGRAM FOR PATTERN", "So", 0, none),
  ("TETRAGRAM FOR RITUAL", "So", 0, none),
  ("TETRAGRAM FOR FLIGHT", "So", 0, none),
  ("TETRAGRAM FOR VASTNESS OR WASTING", "So", 0, none),
  ("TETRAGRAM FOR CONSTANCY", "So", 0, none),
  ("TETRAGRAM FOR MEASURE", "So", 0, none),
  ("TETRAGRAM FOR ETERNITY", "So", 0, none),
  ("TETRAGRAM FOR UNITY", "So", 0, none),
  ("TETRAGRAM FOR DIMINISHMENT", "So", 0, none),
  ("TETRAGRAM FOR CLOSED MOUTH", "So", 0, none),
  ("TETRAGRAM FOR GUARDEDNESS", "So", 0, none),
  ("TETRAGRAM FOR GATHERING IN", "So", 0, none),
  ("TETRAGRAM FOR MASSING", "So", 0, none),
  ("TETRAGRAM FOR ACCUMULATION", "So", 0, none),
  ("TETRAGRAM FOR EMBELLISHMENT", "So", 0, none),
  ("TETRAGRAM FOR DOUBT", "So", 0, none),
  ("TETRAGRAM FOR WATCH", "So", 0, none),
  ("TETRAGRAM FOR SINKING", "So", 0, none),
  ("TETRAGRAM FOR INNER", "So", 0, none),
  ("TETRAGRAM FOR DEPARTURE", "So", 0, none),
  ("TETRAGRAM FOR DARKENING", "So", 0, none),
  ("TETRAGRAM FOR DIMMING", "So", 0, none),
  ("TETRAGRAM FOR EXHAUSTION", "So", 0, none),
  ("TETRAGRAM FOR SEVERANCE", "So", 0, none),
  ("TETRAGRAM FOR STOPPAGE", "So", 0, none),
  ("TETRAGRAM FOR HARDNESS", "So", 0, none),
  ("TETRAGRAM FOR COMPLETION", "So", 0, none),
  ("TETRAGRAM FOR CLOSURE", "So", 0, none),
  ("TETRAGRAM FOR FAILURE", "So", 0, none),
  ("TETRAGRAM FOR AGGRAVATION", "So", 0, none),
  ("TETRAGRAM FOR COMPLIANCE", "So", 0, none),
  ("TETRAGRAM FOR ON THE VERGE", "So", 0, none),
  ("TETRAGRAM FOR DIFFICULTIES", "So", 0, none),
  ("TETRAGRAM FOR LABOURING", "So", 0, none),
  ("TETRAGRAM FOR FOSTERING", "So", 0, none),
)
