#let data = (
  ("MEETEI MAYEK LETTER E", "Lo", 0, none),
  ("MEETEI MAYEK LETTER O", "Lo", 0, none),
  ("MEETEI MAYEK LETTER CHA", "Lo", 0, none),
  ("MEETEI MAYEK LETTER NYA", "Lo", 0, none),
  ("MEETEI MAYEK LETTER TTA", "Lo", 0, none),
  ("MEETEI MAYEK LETTER TTHA", "Lo", 0, none),
  ("MEETEI MAYEK LETTER DDA", "Lo", 0, none),
  ("MEETEI MAYEK LETTER DDHA", "Lo", 0, none),
  ("MEETEI MAYEK LETTER NNA", "Lo", 0, none),
  ("MEETEI MAYEK LETTER SHA", "Lo", 0, none),
  ("MEETEI MAYEK LETTER SSA", "Lo", 0, none),
  ("MEETEI MAYEK VOWEL SIGN II", "Mc", 0, none),
  ("MEETEI MAYEK VOWEL SIGN UU", "Mn", 0, none),
  ("MEETEI MAYEK VOWEL SIGN AAI", "Mn", 0, none),
  ("MEETEI MAYEK VOWEL SIGN AU", "Mc", 0, none),
  ("MEETEI MAYEK VOWEL SIGN AAU", "Mc", 0, none),
  ("MEETEI MAYEK CHEIKHAN", "Po", 0, none),
  ("MEETEI MAYEK AHANG KHUDAM", "Po", 0, none),
  ("MEETEI MAYEK ANJI", "Lo", 0, none),
  ("MEETEI MAYEK SYLLABLE REPETITION MARK", "Lm", 0, none),
  ("MEETEI MAYEK WORD REPETITION MARK", "Lm", 0, none),
  ("MEETEI MAYEK VOWEL SIGN VISARGA", "Mc", 0, none),
  ("MEETEI MAYEK VIRAMA", "Mn", 9, none),
)
