#let data = (
  ("RUMI DIGIT ONE", "No", 0, none),
  ("RUMI DIGIT TWO", "No", 0, none),
  ("RUMI DIGIT THREE", "No", 0, none),
  ("RUMI DIGIT FOUR", "No", 0, none),
  ("RUMI DIGIT FIVE", "No", 0, none),
  ("RUMI DIGIT SIX", "No", 0, none),
  ("RUMI DIGIT SEVEN", "No", 0, none),
  ("RUMI DIGIT EIGHT", "No", 0, none),
  ("RUMI DIGIT NINE", "No", 0, none),
  ("RUMI NUMBER TEN", "No", 0, none),
  ("RUMI NUMBER TWENTY", "No", 0, none),
  ("RUMI NUMBER THIRTY", "No", 0, none),
  ("RUMI NUMBER FORTY", "No", 0, none),
  ("RUMI NUMBER FIFTY", "No", 0, none),
  ("RUMI NUMBER SIXTY", "No", 0, none),
  ("RUMI NUMBER SEVENTY", "No", 0, none),
  ("RUMI NUMBER EIGHTY", "No", 0, none),
  ("RUMI NUMBER NINETY", "No", 0, none),
  ("RUMI NUMBER ONE HUNDRED", "No", 0, none),
  ("RUMI NUMBER TWO HUNDRED", "No", 0, none),
  ("RUMI NUMBER THREE HUNDRED", "No", 0, none),
  ("RUMI NUMBER FOUR HUNDRED", "No", 0, none),
  ("RUMI NUMBER FIVE HUNDRED", "No", 0, none),
  ("RUMI NUMBER SIX HUNDRED", "No", 0, none),
  ("RUMI NUMBER SEVEN HUNDRED", "No", 0, none),
  ("RUMI NUMBER EIGHT HUNDRED", "No", 0, none),
  ("RUMI NUMBER NINE HUNDRED", "No", 0, none),
  ("RUMI FRACTION ONE HALF", "No", 0, none),
  ("RUMI FRACTION ONE QUARTER", "No", 0, none),
  ("RUMI FRACTION ONE THIRD", "No", 0, none),
  ("RUMI FRACTION TWO THIRDS", "No", 0, none),
)
