#let data = (
  ("KIRAT RAI SIGN ANUSVARA", "Lm", 0, none),
  ("KIRAT RAI SIGN TONPI", "Lm", 0, none),
  ("KIRAT RAI SIGN VISARGA", "Lm", 0, none),
  ("KIRAT RAI LETTER A", "Lo", 0, none),
  ("KIRAT RAI LETTER KA", "Lo", 0, none),
  ("KIRAT RAI LETTER KHA", "Lo", 0, none),
  ("KIRAT RAI LETTER GA", "Lo", 0, none),
  ("KIRAT RAI LETTER GHA", "Lo", 0, none),
  ("KIRAT RAI LETTER NGA", "Lo", 0, none),
  ("KIRAT RAI LETTER CA", "Lo", 0, none),
  ("KIRAT RAI LETTER CHA", "Lo", 0, none),
  ("KIRAT RAI LETTER JA", "Lo", 0, none),
  ("KIRAT RAI LETTER JHA", "Lo", 0, none),
  ("KIRAT RAI LETTER NYA", "Lo", 0, none),
  ("KIRAT RAI LETTER TTA", "Lo", 0, none),
  ("KIRAT RAI LETTER TTHA", "Lo", 0, none),
  ("KIRAT RAI LETTER DDA", "Lo", 0, none),
  ("KIRAT RAI LETTER DDHA", "Lo", 0, none),
  ("KIRAT RAI LETTER TA", "Lo", 0, none),
  ("KIRAT RAI LETTER THA", "Lo", 0, none),
  ("KIRAT RAI LETTER DA", "Lo", 0, none),
  ("KIRAT RAI LETTER DHA", "Lo", 0, none),
  ("KIRAT RAI LETTER NA", "Lo", 0, none),
  ("KIRAT RAI LETTER PA", "Lo", 0, none),
  ("KIRAT RAI LETTER PHA", "Lo", 0, none),
  ("KIRAT RAI LETTER BA", "Lo", 0, none),
  ("KIRAT RAI LETTER BHA", "Lo", 0, none),
  ("KIRAT RAI LETTER MA", "Lo", 0, none),
  ("KIRAT RAI LETTER YA", "Lo", 0, none),
  ("KIRAT RAI LETTER RA", "Lo", 0, none),
  ("KIRAT RAI LETTER LA", "Lo", 0, none),
  ("KIRAT RAI LETTER VA", "Lo", 0, none),
  ("KIRAT RAI LETTER SA", "Lo", 0, none),
  ("KIRAT RAI LETTER SHA", "Lo", 0, none),
  ("KIRAT RAI LETTER HA", "Lo", 0, none),
  ("KIRAT RAI VOWEL SIGN AA", "Lo", 0, none),
  ("KIRAT RAI VOWEL SIGN I", "Lo", 0, none),
  ("KIRAT RAI VOWEL SIGN U", "Lo", 0, none),
  ("KIRAT RAI VOWEL SIGN UE", "Lo", 0, none),
  ("KIRAT RAI VOWEL SIGN E", "Lo", 0, none),
  ("KIRAT RAI VOWEL SIGN AI", "Lo", 0, none),
  ("KIRAT RAI VOWEL SIGN O", "Lo", 0, none),
  ("KIRAT RAI VOWEL SIGN AU", "Lo", 0, none),
  ("KIRAT RAI SIGN VIRAMA", "Lm", 0, none),
  ("KIRAT RAI SIGN SAAT", "Lm", 0, none),
  ("KIRAT RAI SIGN YUPI", "Po", 0, none),
  ("KIRAT RAI DANDA", "Po", 0, none),
  ("KIRAT RAI DOUBLE DANDA", "Po", 0, none),
  ("KIRAT RAI DIGIT ZERO", "Nd", 0, none),
  ("KIRAT RAI DIGIT ONE", "Nd", 0, none),
  ("KIRAT RAI DIGIT TWO", "Nd", 0, none),
  ("KIRAT RAI DIGIT THREE", "Nd", 0, none),
  ("KIRAT RAI DIGIT FOUR", "Nd", 0, none),
  ("KIRAT RAI DIGIT FIVE", "Nd", 0, none),
  ("KIRAT RAI DIGIT SIX", "Nd", 0, none),
  ("KIRAT RAI DIGIT SEVEN", "Nd", 0, none),
  ("KIRAT RAI DIGIT EIGHT", "Nd", 0, none),
  ("KIRAT RAI DIGIT NINE", "Nd", 0, none),
)
