#let data = (
  ("PHOENICIAN LETTER ALF", "Lo", 0, none),
  ("PHOENICIAN LETTER BET", "Lo", 0, none),
  ("PHOENICIAN LETTER GAML", "Lo", 0, none),
  ("PHOENICIAN LETTER DELT", "Lo", 0, none),
  ("PHOENICIAN LETTER HE", "Lo", 0, none),
  ("PHOENICIAN LETTER WAU", "Lo", 0, none),
  ("PHOENICIAN LETTER ZAI", "Lo", 0, none),
  ("PHOENICIAN LETTER HET", "Lo", 0, none),
  ("PHOENICIAN LETTER TET", "Lo", 0, none),
  ("PHOENICIAN LETTER YOD", "Lo", 0, none),
  ("PHOENICIAN LETTER KAF", "Lo", 0, none),
  ("PHOENICIAN LETTER LAMD", "Lo", 0, none),
  ("PHOENICIAN LETTER MEM", "Lo", 0, none),
  ("PHOENICIAN LETTER NUN", "Lo", 0, none),
  ("PHOENICIAN LETTER SEMK", "Lo", 0, none),
  ("PHOENICIAN LETTER AIN", "Lo", 0, none),
  ("PHOENICIAN LETTER PE", "Lo", 0, none),
  ("PHOENICIAN LETTER SADE", "Lo", 0, none),
  ("PHOENICIAN LETTER QOF", "Lo", 0, none),
  ("PHOENICIAN LETTER ROSH", "Lo", 0, none),
  ("PHOENICIAN LETTER SHIN", "Lo", 0, none),
  ("PHOENICIAN LETTER TAU", "Lo", 0, none),
  ("PHOENICIAN NUMBER ONE", "No", 0, none),
  ("PHOENICIAN NUMBER TEN", "No", 0, none),
  ("PHOENICIAN NUMBER TWENTY", "No", 0, none),
  ("PHOENICIAN NUMBER ONE HUNDRED", "No", 0, none),
  ("PHOENICIAN NUMBER TWO", "No", 0, none),
  ("PHOENICIAN NUMBER THREE", "No", 0, none),
  (),
  (),
  (),
  ("PHOENICIAN WORD SEPARATOR", "Po", 0, none),
)
