#let data = (
  ("MONGOLIAN BIRGA", "Po", 0, none),
  ("MONGOLIAN ELLIPSIS", "Po", 0, none),
  ("MONGOLIAN COMMA", "Po", 0, none),
  ("MONGOLIAN FULL STOP", "Po", 0, none),
  ("MONGOLIAN COLON", "Po", 0, none),
  ("MONGOLIAN FOUR DOTS", "Po", 0, none),
  ("MONGOLIAN TODO SOFT HYPHEN", "Pd", 0, none),
  ("MONGOLIAN SIBE SYLLABLE BOUNDARY MARKER", "Po", 0, none),
  ("MONGOLIAN MANCHU COMMA", "Po", 0, none),
  ("MONGOLIAN MANCHU FULL STOP", "Po", 0, none),
  ("MONGOLIAN NIRUGU", "Po", 0, none),
  ("MONGOLIAN FREE VARIATION SELECTOR ONE", "Mn", 0, none),
  ("MONGOLIAN FREE VARIATION SELECTOR TWO", "Mn", 0, none),
  ("MONGOLIAN FREE VARIATION SELECTOR THREE", "Mn", 0, none),
  ("MONGOLIAN VOWEL SEPARATOR", "Cf", 0, none),
  ("MONGOLIAN FREE VARIATION SELECTOR FOUR", "Mn", 0, none),
  ("MONGOLIAN DIGIT ZERO", "Nd", 0, none),
  ("MONGOLIAN DIGIT ONE", "Nd", 0, none),
  ("MONGOLIAN DIGIT TWO", "Nd", 0, none),
  ("MONGOLIAN DIGIT THREE", "Nd", 0, none),
  ("MONGOLIAN DIGIT FOUR", "Nd", 0, none),
  ("MONGOLIAN DIGIT FIVE", "Nd", 0, none),
  ("MONGOLIAN DIGIT SIX", "Nd", 0, none),
  ("MONGOLIAN DIGIT SEVEN", "Nd", 0, none),
  ("MONGOLIAN DIGIT EIGHT", "Nd", 0, none),
  ("MONGOLIAN DIGIT NINE", "Nd", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  ("MONGOLIAN LETTER A", "Lo", 0, none),
  ("MONGOLIAN LETTER E", "Lo", 0, none),
  ("MONGOLIAN LETTER I", "Lo", 0, none),
  ("MONGOLIAN LETTER O", "Lo", 0, none),
  ("MONGOLIAN LETTER U", "Lo", 0, none),
  ("MONGOLIAN LETTER OE", "Lo", 0, none),
  ("MONGOLIAN LETTER UE", "Lo", 0, none),
  ("MONGOLIAN LETTER EE", "Lo", 0, none),
  ("MONGOLIAN LETTER NA", "Lo", 0, none),
  ("MONGOLIAN LETTER ANG", "Lo", 0, none),
  ("MONGOLIAN LETTER BA", "Lo", 0, none),
  ("MONGOLIAN LETTER PA", "Lo", 0, none),
  ("MONGOLIAN LETTER QA", "Lo", 0, none),
  ("MONGOLIAN LETTER GA", "Lo", 0, none),
  ("MONGOLIAN LETTER MA", "Lo", 0, none),
  ("MONGOLIAN LETTER LA", "Lo", 0, none),
  ("MONGOLIAN LETTER SA", "Lo", 0, none),
  ("MONGOLIAN LETTER SHA", "Lo", 0, none),
  ("MONGOLIAN LETTER TA", "Lo", 0, none),
  ("MONGOLIAN LETTER DA", "Lo", 0, none),
  ("MONGOLIAN LETTER CHA", "Lo", 0, none),
  ("MONGOLIAN LETTER JA", "Lo", 0, none),
  ("MONGOLIAN LETTER YA", "Lo", 0, none),
  ("MONGOLIAN LETTER RA", "Lo", 0, none),
  ("MONGOLIAN LETTER WA", "Lo", 0, none),
  ("MONGOLIAN LETTER FA", "Lo", 0, none),
  ("MONGOLIAN LETTER KA", "Lo", 0, none),
  ("MONGOLIAN LETTER KHA", "Lo", 0, none),
  ("MONGOLIAN LETTER TSA", "Lo", 0, none),
  ("MONGOLIAN LETTER ZA", "Lo", 0, none),
  ("MONGOLIAN LETTER HAA", "Lo", 0, none),
  ("MONGOLIAN LETTER ZRA", "Lo", 0, none),
  ("MONGOLIAN LETTER LHA", "Lo", 0, none),
  ("MONGOLIAN LETTER ZHI", "Lo", 0, none),
  ("MONGOLIAN LETTER CHI", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO LONG VOWEL SIGN", "Lm", 0, none),
  ("MONGOLIAN LETTER TODO E", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO I", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO O", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO U", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO OE", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO UE", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO ANG", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO BA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO PA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO QA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO GA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO MA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO TA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO DA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO CHA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO JA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO TSA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO YA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO WA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO KA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO GAA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO HAA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO JIA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO NIA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO DZA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE E", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE I", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE IY", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE UE", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE U", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE ANG", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE KA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE GA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE HA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE PA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE SHA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE TA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE DA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE JA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE FA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE GAA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE HAA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE TSA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE ZA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE RAA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE CHA", "Lo", 0, none),
  ("MONGOLIAN LETTER SIBE ZHA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU I", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU KA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU RA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU FA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ZHA", "Lo", 0, none),
  ("MONGOLIAN LETTER CHA WITH TWO DOTS", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("MONGOLIAN LETTER ALI GALI ANUSVARA ONE", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI VISARGA ONE", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI DAMARU", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI UBADAMA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI INVERTED UBADAMA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI BALUDA", "Mn", 0, none),
  ("MONGOLIAN LETTER ALI GALI THREE BALUDA", "Mn", 0, none),
  ("MONGOLIAN LETTER ALI GALI A", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI I", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI KA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI NGA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI CA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI TTA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI TTHA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI DDA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI NNA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI TA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI DA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI PA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI PHA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI SSA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI ZHA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI ZA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI AH", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO ALI GALI TA", "Lo", 0, none),
  ("MONGOLIAN LETTER TODO ALI GALI ZHA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI GHA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI NGA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI CA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI JHA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI TTA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI DDHA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI TA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI DHA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI SSA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI CYA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI ZHA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI ZA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI HALF U", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI HALF YA", "Lo", 0, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI BHA", "Lo", 0, none),
  ("MONGOLIAN LETTER ALI GALI DAGALGA", "Mn", 228, none),
  ("MONGOLIAN LETTER MANCHU ALI GALI LHA", "Lo", 0, none),
)
