#let data = (
  ("CIRCLED CROSS FORMEE WITH FOUR DOTS", "So", 0, none),
  ("CIRCLED CROSS FORMEE WITH TWO DOTS", "So", 0, none),
  ("CIRCLED CROSS FORMEE", "So", 0, none),
  ("LEFT HALF CIRCLE WITH FOUR DOTS", "So", 0, none),
  ("LEFT HALF CIRCLE WITH THREE DOTS", "So", 0, none),
  ("LEFT HALF CIRCLE WITH TWO DOTS", "So", 0, none),
  ("LEFT HALF CIRCLE WITH DOT", "So", 0, none),
  ("LEFT HALF CIRCLE", "So", 0, none),
  ("DOWNWARD FACING HOOK", "So", 0, none),
  ("DOWNWARD FACING NOTCHED HOOK", "So", 0, none),
  ("DOWNWARD FACING HOOK WITH DOT", "So", 0, none),
  ("DOWNWARD FACING NOTCHED HOOK WITH DOT", "So", 0, none),
  ("PINCHED FINGERS", "So", 0, none),
  ("WHITE HEART", "So", 0, none),
  ("BROWN HEART", "So", 0, none),
  ("PINCHING HAND", "So", 0, none),
  ("ZIPPER-MOUTH FACE", "So", 0, none),
  ("MONEY-MOUTH FACE", "So", 0, none),
  ("FACE WITH THERMOMETER", "So", 0, none),
  ("NERD FACE", "So", 0, none),
  ("THINKING FACE", "So", 0, none),
  ("FACE WITH HEAD-BANDAGE", "So", 0, none),
  ("ROBOT FACE", "So", 0, none),
  ("HUGGING FACE", "So", 0, none),
  ("SIGN OF THE HORNS", "So", 0, none),
  ("CALL ME HAND", "So", 0, none),
  ("RAISED BACK OF HAND", "So", 0, none),
  ("LEFT-FACING FIST", "So", 0, none),
  ("RIGHT-FACING FIST", "So", 0, none),
  ("HANDSHAKE", "So", 0, none),
  ("HAND WITH INDEX AND MIDDLE FINGERS CROSSED", "So", 0, none),
  ("I LOVE YOU HAND SIGN", "So", 0, none),
  ("FACE WITH COWBOY HAT", "So", 0, none),
  ("CLOWN FACE", "So", 0, none),
  ("NAUSEATED FACE", "So", 0, none),
  ("ROLLING ON THE FLOOR LAUGHING", "So", 0, none),
  ("DROOLING FACE", "So", 0, none),
  ("LYING FACE", "So", 0, none),
  ("FACE PALM", "So", 0, none),
  ("SNEEZING FACE", "So", 0, none),
  ("FACE WITH ONE EYEBROW RAISED", "So", 0, none),
  ("GRINNING FACE WITH STAR EYES", "So", 0, none),
  ("GRINNING FACE WITH ONE LARGE AND ONE SMALL EYE", "So", 0, none),
  ("FACE WITH FINGER COVERING CLOSED LIPS", "So", 0, none),
  ("SERIOUS FACE WITH SYMBOLS COVERING MOUTH", "So", 0, none),
  ("SMILING FACE WITH SMILING EYES AND HAND COVERING MOUTH", "So", 0, none),
  ("FACE WITH OPEN MOUTH VOMITING", "So", 0, none),
  ("SHOCKED FACE WITH EXPLODING HEAD", "So", 0, none),
  ("PREGNANT WOMAN", "So", 0, none),
  ("BREAST-FEEDING", "So", 0, none),
  ("PALMS UP TOGETHER", "So", 0, none),
  ("SELFIE", "So", 0, none),
  ("PRINCE", "So", 0, none),
  ("MAN IN TUXEDO", "So", 0, none),
  ("MOTHER CHRISTMAS", "So", 0, none),
  ("SHRUG", "So", 0, none),
  ("PERSON DOING CARTWHEEL", "So", 0, none),
  ("JUGGLING", "So", 0, none),
  ("FENCER", "So", 0, none),
  ("MODERN PENTATHLON", "So", 0, none),
  ("WRESTLERS", "So", 0, none),
  ("WATER POLO", "So", 0, none),
  ("HANDBALL", "So", 0, none),
  ("DIVING MASK", "So", 0, none),
  ("WILTED FLOWER", "So", 0, none),
  ("DRUM WITH DRUMSTICKS", "So", 0, none),
  ("CLINKING GLASSES", "So", 0, none),
  ("TUMBLER GLASS", "So", 0, none),
  ("SPOON", "So", 0, none),
  ("GOAL NET", "So", 0, none),
  ("RIFLE", "So", 0, none),
  ("FIRST PLACE MEDAL", "So", 0, none),
  ("SECOND PLACE MEDAL", "So", 0, none),
  ("THIRD PLACE MEDAL", "So", 0, none),
  ("BOXING GLOVE", "So", 0, none),
  ("MARTIAL ARTS UNIFORM", "So", 0, none),
  ("CURLING STONE", "So", 0, none),
  ("LACROSSE STICK AND BALL", "So", 0, none),
  ("SOFTBALL", "So", 0, none),
  ("FLYING DISC", "So", 0, none),
  ("CROISSANT", "So", 0, none),
  ("AVOCADO", "So", 0, none),
  ("CUCUMBER", "So", 0, none),
  ("BACON", "So", 0, none),
  ("POTATO", "So", 0, none),
  ("CARROT", "So", 0, none),
  ("BAGUETTE BREAD", "So", 0, none),
  ("GREEN SALAD", "So", 0, none),
  ("SHALLOW PAN OF FOOD", "So", 0, none),
  ("STUFFED FLATBREAD", "So", 0, none),
  ("EGG", "So", 0, none),
  ("GLASS OF MILK", "So", 0, none),
  ("PEANUTS", "So", 0, none),
  ("KIWIFRUIT", "So", 0, none),
  ("PANCAKES", "So", 0, none),
  ("DUMPLING", "So", 0, none),
  ("FORTUNE COOKIE", "So", 0, none),
  ("TAKEOUT BOX", "So", 0, none),
  ("CHOPSTICKS", "So", 0, none),
  ("BOWL WITH SPOON", "So", 0, none),
  ("CUP WITH STRAW", "So", 0, none),
  ("COCONUT", "So", 0, none),
  ("BROCCOLI", "So", 0, none),
  ("PIE", "So", 0, none),
  ("PRETZEL", "So", 0, none),
  ("CUT OF MEAT", "So", 0, none),
  ("SANDWICH", "So", 0, none),
  ("CANNED FOOD", "So", 0, none),
  ("LEAFY GREEN", "So", 0, none),
  ("MANGO", "So", 0, none),
  ("MOON CAKE", "So", 0, none),
  ("BAGEL", "So", 0, none),
  ("SMILING FACE WITH SMILING EYES AND THREE HEARTS", "So", 0, none),
  ("YAWNING FACE", "So", 0, none),
  ("SMILING FACE WITH TEAR", "So", 0, none),
  ("FACE WITH PARTY HORN AND PARTY HAT", "So", 0, none),
  ("FACE WITH UNEVEN EYES AND WAVY MOUTH", "So", 0, none),
  ("OVERHEATED FACE", "So", 0, none),
  ("FREEZING FACE", "So", 0, none),
  ("NINJA", "So", 0, none),
  ("DISGUISED FACE", "So", 0, none),
  ("FACE HOLDING BACK TEARS", "So", 0, none),
  ("FACE WITH PLEADING EYES", "So", 0, none),
  ("SARI", "So", 0, none),
  ("LAB COAT", "So", 0, none),
  ("GOGGLES", "So", 0, none),
  ("HIKING BOOT", "So", 0, none),
  ("FLAT SHOE", "So", 0, none),
  ("CRAB", "So", 0, none),
  ("LION FACE", "So", 0, none),
  ("SCORPION", "So", 0, none),
  ("TURKEY", "So", 0, none),
  ("UNICORN FACE", "So", 0, none),
  ("EAGLE", "So", 0, none),
  ("DUCK", "So", 0, none),
  ("BAT", "So", 0, none),
  ("SHARK", "So", 0, none),
  ("OWL", "So", 0, none),
  ("FOX FACE", "So", 0, none),
  ("BUTTERFLY", "So", 0, none),
  ("DEER", "So", 0, none),
  ("GORILLA", "So", 0, none),
  ("LIZARD", "So", 0, none),
  ("RHINOCEROS", "So", 0, none),
  ("SHRIMP", "So", 0, none),
  ("SQUID", "So", 0, none),
  ("GIRAFFE FACE", "So", 0, none),
  ("ZEBRA FACE", "So", 0, none),
  ("HEDGEHOG", "So", 0, none),
  ("SAUROPOD", "So", 0, none),
  ("T-REX", "So", 0, none),
  ("CRICKET", "So", 0, none),
  ("KANGAROO", "So", 0, none),
  ("LLAMA", "So", 0, none),
  ("PEACOCK", "So", 0, none),
  ("HIPPOPOTAMUS", "So", 0, none),
  ("PARROT", "So", 0, none),
  ("RACCOON", "So", 0, none),
  ("LOBSTER", "So", 0, none),
  ("MOSQUITO", "So", 0, none),
  ("MICROBE", "So", 0, none),
  ("BADGER", "So", 0, none),
  ("SWAN", "So", 0, none),
  ("MAMMOTH", "So", 0, none),
  ("DODO", "So", 0, none),
  ("SLOTH", "So", 0, none),
  ("OTTER", "So", 0, none),
  ("ORANGUTAN", "So", 0, none),
  ("SKUNK", "So", 0, none),
  ("FLAMINGO", "So", 0, none),
  ("OYSTER", "So", 0, none),
  ("BEAVER", "So", 0, none),
  ("BISON", "So", 0, none),
  ("SEAL", "So", 0, none),
  ("GUIDE DOG", "So", 0, none),
  ("PROBING CANE", "So", 0, none),
  ("EMOJI COMPONENT RED HAIR", "So", 0, none),
  ("EMOJI COMPONENT CURLY HAIR", "So", 0, none),
  ("EMOJI COMPONENT BALD", "So", 0, none),
  ("EMOJI COMPONENT WHITE HAIR", "So", 0, none),
  ("BONE", "So", 0, none),
  ("LEG", "So", 0, none),
  ("FOOT", "So", 0, none),
  ("TOOTH", "So", 0, none),
  ("SUPERHERO", "So", 0, none),
  ("SUPERVILLAIN", "So", 0, none),
  ("SAFETY VEST", "So", 0, none),
  ("EAR WITH HEARING AID", "So", 0, none),
  ("MOTORIZED WHEELCHAIR", "So", 0, none),
  ("MANUAL WHEELCHAIR", "So", 0, none),
  ("MECHANICAL ARM", "So", 0, none),
  ("MECHANICAL LEG", "So", 0, none),
  ("CHEESE WEDGE", "So", 0, none),
  ("CUPCAKE", "So", 0, none),
  ("SALT SHAKER", "So", 0, none),
  ("BEVERAGE BOX", "So", 0, none),
  ("GARLIC", "So", 0, none),
  ("ONION", "So", 0, none),
  ("FALAFEL", "So", 0, none),
  ("WAFFLE", "So", 0, none),
  ("BUTTER", "So", 0, none),
  ("MATE DRINK", "So", 0, none),
  ("ICE CUBE", "So", 0, none),
  ("BUBBLE TEA", "So", 0, none),
  ("TROLL", "So", 0, none),
  ("STANDING PERSON", "So", 0, none),
  ("KNEELING PERSON", "So", 0, none),
  ("DEAF PERSON", "So", 0, none),
  ("FACE WITH MONOCLE", "So", 0, none),
  ("ADULT", "So", 0, none),
  ("CHILD", "So", 0, none),
  ("OLDER ADULT", "So", 0, none),
  ("BEARDED PERSON", "So", 0, none),
  ("PERSON WITH HEADSCARF", "So", 0, none),
  ("PERSON IN STEAMY ROOM", "So", 0, none),
  ("PERSON CLIMBING", "So", 0, none),
  ("PERSON IN LOTUS POSITION", "So", 0, none),
  ("MAGE", "So", 0, none),
  ("FAIRY", "So", 0, none),
  ("VAMPIRE", "So", 0, none),
  ("MERPERSON", "So", 0, none),
  ("ELF", "So", 0, none),
  ("GENIE", "So", 0, none),
  ("ZOMBIE", "So", 0, none),
  ("BRAIN", "So", 0, none),
  ("ORANGE HEART", "So", 0, none),
  ("BILLED CAP", "So", 0, none),
  ("SCARF", "So", 0, none),
  ("GLOVES", "So", 0, none),
  ("COAT", "So", 0, none),
  ("SOCKS", "So", 0, none),
  ("RED GIFT ENVELOPE", "So", 0, none),
  ("FIRECRACKER", "So", 0, none),
  ("JIGSAW PUZZLE PIECE", "So", 0, none),
  ("TEST TUBE", "So", 0, none),
  ("PETRI DISH", "So", 0, none),
  ("DNA DOUBLE HELIX", "So", 0, none),
  ("COMPASS", "So", 0, none),
  ("ABACUS", "So", 0, none),
  ("FIRE EXTINGUISHER", "So", 0, none),
  ("TOOLBOX", "So", 0, none),
  ("BRICK", "So", 0, none),
  ("MAGNET", "So", 0, none),
  ("LUGGAGE", "So", 0, none),
  ("LOTION BOTTLE", "So", 0, none),
  ("SPOOL OF THREAD", "So", 0, none),
  ("BALL OF YARN", "So", 0, none),
  ("SAFETY PIN", "So", 0, none),
  ("TEDDY BEAR", "So", 0, none),
  ("BROOM", "So", 0, none),
  ("BASKET", "So", 0, none),
  ("ROLL OF PAPER", "So", 0, none),
  ("BAR OF SOAP", "So", 0, none),
  ("SPONGE", "So", 0, none),
  ("RECEIPT", "So", 0, none),
  ("NAZAR AMULET", "So", 0, none),
)
