#let data = (
  ("AEGEAN WORD SEPARATOR LINE", "Po", 0, none),
  ("AEGEAN WORD SEPARATOR DOT", "Po", 0, none),
  ("AEGEAN CHECK MARK", "Po", 0, none),
  (),
  (),
  (),
  (),
  ("AEGEAN NUMBER ONE", "No", 0, none),
  ("AEGEAN NUMBER TWO", "No", 0, none),
  ("AEGEAN NUMBER THREE", "No", 0, none),
  ("AEGEAN NUMBER FOUR", "No", 0, none),
  ("AEGEAN NUMBER FIVE", "No", 0, none),
  ("AEGEAN NUMBER SIX", "No", 0, none),
  ("AEGEAN NUMBER SEVEN", "No", 0, none),
  ("AEGEAN NUMBER EIGHT", "No", 0, none),
  ("AEGEAN NUMBER NINE", "No", 0, none),
  ("AEGEAN NUMBER TEN", "No", 0, none),
  ("AEGEAN NUMBER TWENTY", "No", 0, none),
  ("AEGEAN NUMBER THIRTY", "No", 0, none),
  ("AEGEAN NUMBER FORTY", "No", 0, none),
  ("AEGEAN NUMBER FIFTY", "No", 0, none),
  ("AEGEAN NUMBER SIXTY", "No", 0, none),
  ("AEGEAN NUMBER SEVENTY", "No", 0, none),
  ("AEGEAN NUMBER EIGHTY", "No", 0, none),
  ("AEGEAN NUMBER NINETY", "No", 0, none),
  ("AEGEAN NUMBER ONE HUNDRED", "No", 0, none),
  ("AEGEAN NUMBER TWO HUNDRED", "No", 0, none),
  ("AEGEAN NUMBER THREE HUNDRED", "No", 0, none),
  ("AEGEAN NUMBER FOUR HUNDRED", "No", 0, none),
  ("AEGEAN NUMBER FIVE HUNDRED", "No", 0, none),
  ("AEGEAN NUMBER SIX HUNDRED", "No", 0, none),
  ("AEGEAN NUMBER SEVEN HUNDRED", "No", 0, none),
  ("AEGEAN NUMBER EIGHT HUNDRED", "No", 0, none),
  ("AEGEAN NUMBER NINE HUNDRED", "No", 0, none),
  ("AEGEAN NUMBER ONE THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER TWO THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER THREE THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER FOUR THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER FIVE THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER SIX THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER SEVEN THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER EIGHT THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER NINE THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER TEN THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER TWENTY THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER THIRTY THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER FORTY THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER FIFTY THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER SIXTY THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER SEVENTY THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER EIGHTY THOUSAND", "No", 0, none),
  ("AEGEAN NUMBER NINETY THOUSAND", "No", 0, none),
  (),
  (),
  (),
  ("AEGEAN WEIGHT BASE UNIT", "So", 0, none),
  ("AEGEAN WEIGHT FIRST SUBUNIT", "So", 0, none),
  ("AEGEAN WEIGHT SECOND SUBUNIT", "So", 0, none),
  ("AEGEAN WEIGHT THIRD SUBUNIT", "So", 0, none),
  ("AEGEAN WEIGHT FOURTH SUBUNIT", "So", 0, none),
  ("AEGEAN DRY MEASURE FIRST SUBUNIT", "So", 0, none),
  ("AEGEAN LIQUID MEASURE FIRST SUBUNIT", "So", 0, none),
  ("AEGEAN MEASURE SECOND SUBUNIT", "So", 0, none),
  ("AEGEAN MEASURE THIRD SUBUNIT", "So", 0, none),
)
