#let data = (
  ("UGARITIC LETTER ALPA", "Lo", 0, none),
  ("UGARITIC LETTER BETA", "Lo", 0, none),
  ("UGARITIC LETTER GAMLA", "Lo", 0, none),
  ("UGARITIC LETTER KHA", "Lo", 0, none),
  ("UGARITIC LETTER DELTA", "Lo", 0, none),
  ("UGARITIC LETTER HO", "Lo", 0, none),
  ("UGARITIC LETTER WO", "Lo", 0, none),
  ("UGARITIC LETTER ZETA", "Lo", 0, none),
  ("UGARITIC LETTER HOTA", "Lo", 0, none),
  ("UGARITIC LETTER TET", "Lo", 0, none),
  ("UGARITIC LETTER YOD", "Lo", 0, none),
  ("UGARITIC LETTER KAF", "Lo", 0, none),
  ("UGARITIC LETTER SHIN", "Lo", 0, none),
  ("UGARITIC LETTER LAMDA", "Lo", 0, none),
  ("UGARITIC LETTER MEM", "Lo", 0, none),
  ("UGARITIC LETTER DHAL", "Lo", 0, none),
  ("UGARITIC LETTER NUN", "Lo", 0, none),
  ("UGARITIC LETTER ZU", "Lo", 0, none),
  ("UGARITIC LETTER SAMKA", "Lo", 0, none),
  ("UGARITIC LETTER AIN", "Lo", 0, none),
  ("UGARITIC LETTER PU", "Lo", 0, none),
  ("UGARITIC LETTER SADE", "Lo", 0, none),
  ("UGARITIC LETTER QOPA", "Lo", 0, none),
  ("UGARITIC LETTER RASHA", "Lo", 0, none),
  ("UGARITIC LETTER THANNA", "Lo", 0, none),
  ("UGARITIC LETTER GHAIN", "Lo", 0, none),
  ("UGARITIC LETTER TO", "Lo", 0, none),
  ("UGARITIC LETTER I", "Lo", 0, none),
  ("UGARITIC LETTER U", "Lo", 0, none),
  ("UGARITIC LETTER SSU", "Lo", 0, none),
  (),
  ("UGARITIC WORD DIVIDER", "Po", 0, none),
)
