#let data = (
  ("LINEAR B IDEOGRAM B100 MAN", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B102 WOMAN", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B104 DEER", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B105 EQUID", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B105F MARE", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B105M STALLION", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B106F EWE", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B106M RAM", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B107F SHE-GOAT", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B107M HE-GOAT", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B108F SOW", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B108M BOAR", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B109F COW", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B109M BULL", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B120 WHEAT", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B121 BARLEY", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B122 OLIVE", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B123 SPICE", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B125 CYPERUS", "Lo", 0, none),
  ("LINEAR B MONOGRAM B127 KAPO", "Lo", 0, none),
  ("LINEAR B MONOGRAM B128 KANAKO", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B130 OIL", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B131 WINE", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B132", "Lo", 0, none),
  ("LINEAR B MONOGRAM B133 AREPA", "Lo", 0, none),
  ("LINEAR B MONOGRAM B135 MERI", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B140 BRONZE", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B141 GOLD", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B142", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B145 WOOL", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B146", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B150", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B151 HORN", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B152", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B153", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B154", "Lo", 0, none),
  ("LINEAR B MONOGRAM B156 TURO2", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B157", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B158", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B159 CLOTH", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B160", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B161", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B162 GARMENT", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B163 ARMOUR", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B164", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B165", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B166", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B167", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B168", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B169", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B170", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B171", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B172", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B173 MONTH", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B174", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B176 TREE", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B177", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B178", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B179", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B180", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B181", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B182", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B183", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B184", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B185", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B189", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B190", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B191 HELMET", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B220 FOOTSTOOL", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B225 BATHTUB", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B230 SPEAR", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B231 ARROW", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B232", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B233 SWORD", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B234", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B236", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B240 WHEELED CHARIOT", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B241 CHARIOT", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B242 CHARIOT FRAME", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B243 WHEEL", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B245", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B246", "Lo", 0, none),
  ("LINEAR B MONOGRAM B247 DIPTE", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B248", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B249", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B251", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B252", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B253", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B254 DART", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B255", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B256", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B257", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B258", "Lo", 0, none),
  ("LINEAR B IDEOGRAM B259", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B155", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B200", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B201", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B202", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B203", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B204", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B205", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B206", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B207", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B208", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B209", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B210", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B211", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B212", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B213", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B214", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B215", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B216", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B217", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B218", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B219", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B221", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B222", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B226", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B227", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B228", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B229", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B250", "Lo", 0, none),
  ("LINEAR B IDEOGRAM VESSEL B305", "Lo", 0, none),
)
