#let data = (
  ("SIDDHAM LETTER A", "Lo", 0, none),
  ("SIDDHAM LETTER AA", "Lo", 0, none),
  ("SIDDHAM LETTER I", "Lo", 0, none),
  ("SIDDHAM LETTER II", "Lo", 0, none),
  ("SIDDHAM LETTER U", "Lo", 0, none),
  ("SIDDHAM LETTER UU", "Lo", 0, none),
  ("SIDDHAM LETTER VOCALIC R", "Lo", 0, none),
  ("SIDDHAM LETTER VOCALIC RR", "Lo", 0, none),
  ("SIDDHAM LETTER VOCALIC L", "Lo", 0, none),
  ("SIDDHAM LETTER VOCALIC LL", "Lo", 0, none),
  ("SIDDHAM LETTER E", "Lo", 0, none),
  ("SIDDHAM LETTER AI", "Lo", 0, none),
  ("SIDDHAM LETTER O", "Lo", 0, none),
  ("SIDDHAM LETTER AU", "Lo", 0, none),
  ("SIDDHAM LETTER KA", "Lo", 0, none),
  ("SIDDHAM LETTER KHA", "Lo", 0, none),
  ("SIDDHAM LETTER GA", "Lo", 0, none),
  ("SIDDHAM LETTER GHA", "Lo", 0, none),
  ("SIDDHAM LETTER NGA", "Lo", 0, none),
  ("SIDDHAM LETTER CA", "Lo", 0, none),
  ("SIDDHAM LETTER CHA", "Lo", 0, none),
  ("SIDDHAM LETTER JA", "Lo", 0, none),
  ("SIDDHAM LETTER JHA", "Lo", 0, none),
  ("SIDDHAM LETTER NYA", "Lo", 0, none),
  ("SIDDHAM LETTER TTA", "Lo", 0, none),
  ("SIDDHAM LETTER TTHA", "Lo", 0, none),
  ("SIDDHAM LETTER DDA", "Lo", 0, none),
  ("SIDDHAM LETTER DDHA", "Lo", 0, none),
  ("SIDDHAM LETTER NNA", "Lo", 0, none),
  ("SIDDHAM LETTER TA", "Lo", 0, none),
  ("SIDDHAM LETTER THA", "Lo", 0, none),
  ("SIDDHAM LETTER DA", "Lo", 0, none),
  ("SIDDHAM LETTER DHA", "Lo", 0, none),
  ("SIDDHAM LETTER NA", "Lo", 0, none),
  ("SIDDHAM LETTER PA", "Lo", 0, none),
  ("SIDDHAM LETTER PHA", "Lo", 0, none),
  ("SIDDHAM LETTER BA", "Lo", 0, none),
  ("SIDDHAM LETTER BHA", "Lo", 0, none),
  ("SIDDHAM LETTER MA", "Lo", 0, none),
  ("SIDDHAM LETTER YA", "Lo", 0, none),
  ("SIDDHAM LETTER RA", "Lo", 0, none),
  ("SIDDHAM LETTER LA", "Lo", 0, none),
  ("SIDDHAM LETTER VA", "Lo", 0, none),
  ("SIDDHAM LETTER SHA", "Lo", 0, none),
  ("SIDDHAM LETTER SSA", "Lo", 0, none),
  ("SIDDHAM LETTER SA", "Lo", 0, none),
  ("SIDDHAM LETTER HA", "Lo", 0, none),
  ("SIDDHAM VOWEL SIGN AA", "Mc", 0, none),
  ("SIDDHAM VOWEL SIGN I", "Mc", 0, none),
  ("SIDDHAM VOWEL SIGN II", "Mc", 0, none),
  ("SIDDHAM VOWEL SIGN U", "Mn", 0, none),
  ("SIDDHAM VOWEL SIGN UU", "Mn", 0, none),
  ("SIDDHAM VOWEL SIGN VOCALIC R", "Mn", 0, none),
  ("SIDDHAM VOWEL SIGN VOCALIC RR", "Mn", 0, none),
  (),
  (),
  ("SIDDHAM VOWEL SIGN E", "Mc", 0, none),
  ("SIDDHAM VOWEL SIGN AI", "Mc", 0, none),
  ("SIDDHAM VOWEL SIGN O", "Mc", 0, none),
  ("SIDDHAM VOWEL SIGN AU", "Mc", 0, none),
  ("SIDDHAM SIGN CANDRABINDU", "Mn", 0, none),
  ("SIDDHAM SIGN ANUSVARA", "Mn", 0, none),
  ("SIDDHAM SIGN VISARGA", "Mc", 0, none),
  ("SIDDHAM SIGN VIRAMA", "Mn", 9, none),
  ("SIDDHAM SIGN NUKTA", "Mn", 7, none),
  ("SIDDHAM SIGN SIDDHAM", "Po", 0, none),
  ("SIDDHAM DANDA", "Po", 0, none),
  ("SIDDHAM DOUBLE DANDA", "Po", 0, none),
  ("SIDDHAM SEPARATOR DOT", "Po", 0, none),
  ("SIDDHAM SEPARATOR BAR", "Po", 0, none),
  ("SIDDHAM REPETITION MARK-1", "Po", 0, none),
  ("SIDDHAM REPETITION MARK-2", "Po", 0, none),
  ("SIDDHAM REPETITION MARK-3", "Po", 0, none),
  ("SIDDHAM END OF TEXT MARK", "Po", 0, none),
  ("SIDDHAM SECTION MARK WITH TRIDENT AND U-SHAPED ORNAMENTS", "Po", 0, none),
  ("SIDDHAM SECTION MARK WITH TRIDENT AND DOTTED CRESCENTS", "Po", 0, none),
  ("SIDDHAM SECTION MARK WITH RAYS AND DOTTED CRESCENTS", "Po", 0, none),
  ("SIDDHAM SECTION MARK WITH RAYS AND DOTTED DOUBLE CRESCENTS", "Po", 0, none),
  ("SIDDHAM SECTION MARK WITH RAYS AND DOTTED TRIPLE CRESCENTS", "Po", 0, none),
  ("SIDDHAM SECTION MARK DOUBLE RING", "Po", 0, none),
  ("SIDDHAM SECTION MARK DOUBLE RING WITH RAYS", "Po", 0, none),
  ("SIDDHAM SECTION MARK WITH DOUBLE CRESCENTS", "Po", 0, none),
  ("SIDDHAM SECTION MARK WITH TRIPLE CRESCENTS", "Po", 0, none),
  ("SIDDHAM SECTION MARK WITH QUADRUPLE CRESCENTS", "Po", 0, none),
  ("SIDDHAM SECTION MARK WITH SEPTUPLE CRESCENTS", "Po", 0, none),
  ("SIDDHAM SECTION MARK WITH CIRCLES AND RAYS", "Po", 0, none),
  ("SIDDHAM SECTION MARK WITH CIRCLES AND TWO ENCLOSURES", "Po", 0, none),
  ("SIDDHAM SECTION MARK WITH CIRCLES AND FOUR ENCLOSURES", "Po", 0, none),
  ("SIDDHAM LETTER THREE-CIRCLE ALTERNATE I", "Lo", 0, none),
  ("SIDDHAM LETTER TWO-CIRCLE ALTERNATE I", "Lo", 0, none),
  ("SIDDHAM LETTER TWO-CIRCLE ALTERNATE II", "Lo", 0, none),
  ("SIDDHAM LETTER ALTERNATE U", "Lo", 0, none),
  ("SIDDHAM VOWEL SIGN ALTERNATE U", "Mn", 0, none),
  ("SIDDHAM VOWEL SIGN ALTERNATE UU", "Mn", 0, none),
)
