#let data = (
  ("CYPRIOT SYLLABLE A", "Lo", 0, none),
  ("CYPRIOT SYLLABLE E", "Lo", 0, none),
  ("CYPRIOT SYLLABLE I", "Lo", 0, none),
  ("CYPRIOT SYLLABLE O", "Lo", 0, none),
  ("CYPRIOT SYLLABLE U", "Lo", 0, none),
  ("CYPRIOT SYLLABLE JA", "Lo", 0, none),
  (),
  (),
  ("CYPRIOT SYLLABLE JO", "Lo", 0, none),
  (),
  ("CYPRIOT SYLLABLE KA", "Lo", 0, none),
  ("CYPRIOT SYLLABLE KE", "Lo", 0, none),
  ("CYPRIOT SYLLABLE KI", "Lo", 0, none),
  ("CYPRIOT SYLLABLE KO", "Lo", 0, none),
  ("CYPRIOT SYLLABLE KU", "Lo", 0, none),
  ("CYPRIOT SYLLABLE LA", "Lo", 0, none),
  ("CYPRIOT SYLLABLE LE", "Lo", 0, none),
  ("CYPRIOT SYLLABLE LI", "Lo", 0, none),
  ("CYPRIOT SYLLABLE LO", "Lo", 0, none),
  ("CYPRIOT SYLLABLE LU", "Lo", 0, none),
  ("CYPRIOT SYLLABLE MA", "Lo", 0, none),
  ("CYPRIOT SYLLABLE ME", "Lo", 0, none),
  ("CYPRIOT SYLLABLE MI", "Lo", 0, none),
  ("CYPRIOT SYLLABLE MO", "Lo", 0, none),
  ("CYPRIOT SYLLABLE MU", "Lo", 0, none),
  ("CYPRIOT SYLLABLE NA", "Lo", 0, none),
  ("CYPRIOT SYLLABLE NE", "Lo", 0, none),
  ("CYPRIOT SYLLABLE NI", "Lo", 0, none),
  ("CYPRIOT SYLLABLE NO", "Lo", 0, none),
  ("CYPRIOT SYLLABLE NU", "Lo", 0, none),
  ("CYPRIOT SYLLABLE PA", "Lo", 0, none),
  ("CYPRIOT SYLLABLE PE", "Lo", 0, none),
  ("CYPRIOT SYLLABLE PI", "Lo", 0, none),
  ("CYPRIOT SYLLABLE PO", "Lo", 0, none),
  ("CYPRIOT SYLLABLE PU", "Lo", 0, none),
  ("CYPRIOT SYLLABLE RA", "Lo", 0, none),
  ("CYPRIOT SYLLABLE RE", "Lo", 0, none),
  ("CYPRIOT SYLLABLE RI", "Lo", 0, none),
  ("CYPRIOT SYLLABLE RO", "Lo", 0, none),
  ("CYPRIOT SYLLABLE RU", "Lo", 0, none),
  ("CYPRIOT SYLLABLE SA", "Lo", 0, none),
  ("CYPRIOT SYLLABLE SE", "Lo", 0, none),
  ("CYPRIOT SYLLABLE SI", "Lo", 0, none),
  ("CYPRIOT SYLLABLE SO", "Lo", 0, none),
  ("CYPRIOT SYLLABLE SU", "Lo", 0, none),
  ("CYPRIOT SYLLABLE TA", "Lo", 0, none),
  ("CYPRIOT SYLLABLE TE", "Lo", 0, none),
  ("CYPRIOT SYLLABLE TI", "Lo", 0, none),
  ("CYPRIOT SYLLABLE TO", "Lo", 0, none),
  ("CYPRIOT SYLLABLE TU", "Lo", 0, none),
  ("CYPRIOT SYLLABLE WA", "Lo", 0, none),
  ("CYPRIOT SYLLABLE WE", "Lo", 0, none),
  ("CYPRIOT SYLLABLE WI", "Lo", 0, none),
  ("CYPRIOT SYLLABLE WO", "Lo", 0, none),
  (),
  ("CYPRIOT SYLLABLE XA", "Lo", 0, none),
  ("CYPRIOT SYLLABLE XE", "Lo", 0, none),
  (),
  (),
  (),
  ("CYPRIOT SYLLABLE ZA", "Lo", 0, none),
  (),
  (),
  ("CYPRIOT SYLLABLE ZO", "Lo", 0, none),
)
