#let data = (
  ("HEBE", "So", 0, none),
  ("IRIS", "So", 0, none),
  ("FLORA", "So", 0, none),
  ("METIS", "So", 0, none),
  ("PARTHENOPE", "So", 0, none),
  ("VICTORIA", "So", 0, none),
  ("EGERIA", "So", 0, none),
  ("IRENE", "So", 0, none),
  ("EUNOMIA", "So", 0, none),
  ("PSYCHE", "So", 0, none),
  ("THETIS", "So", 0, none),
  ("MELPOMENE", "So", 0, none),
  ("FORTUNA", "So", 0, none),
  ("ASTRONOMICAL SYMBOL FOR ASTEROID PROSERPINA", "So", 0, none),
  ("BELLONA", "So", 0, none),
  ("AMPHITRITE", "So", 0, none),
  ("LEUKOTHEA", "So", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("GEOMANTIC FIGURE POPULUS", "So", 0, none),
  ("GEOMANTIC FIGURE TRISTITIA", "So", 0, none),
  ("GEOMANTIC FIGURE ALBUS", "So", 0, none),
  ("GEOMANTIC FIGURE FORTUNA MAJOR", "So", 0, none),
  ("GEOMANTIC FIGURE RUBEUS", "So", 0, none),
  ("GEOMANTIC FIGURE ACQUISITIO", "So", 0, none),
  ("GEOMANTIC FIGURE CONJUNCTIO", "So", 0, none),
  ("GEOMANTIC FIGURE CAPUT DRACONIS", "So", 0, none),
  ("GEOMANTIC FIGURE LAETITIA", "So", 0, none),
  ("GEOMANTIC FIGURE CARCER", "So", 0, none),
  ("GEOMANTIC FIGURE AMISSIO", "So", 0, none),
  ("GEOMANTIC FIGURE PUELLA", "So", 0, none),
  ("GEOMANTIC FIGURE FORTUNA MINOR", "So", 0, none),
  ("GEOMANTIC FIGURE PUER", "So", 0, none),
  ("GEOMANTIC FIGURE CAUDA DRACONIS", "So", 0, none),
  ("GEOMANTIC FIGURE VIA", "So", 0, none),
  ("MEDIUM SMALL WHITE CIRCLE WITH HORIZONTAL BAR", "Sm", 0, none),
)
