#let data = (
  ("LINEAR B SYLLABLE B008 A", "Lo", 0, none),
  ("LINEAR B SYLLABLE B038 E", "Lo", 0, none),
  ("LINEAR B SYLLABLE B028 I", "Lo", 0, none),
  ("LINEAR B SYLLABLE B061 O", "Lo", 0, none),
  ("LINEAR B SYLLABLE B010 U", "Lo", 0, none),
  ("LINEAR B SYLLABLE B001 DA", "Lo", 0, none),
  ("LINEAR B SYLLABLE B045 DE", "Lo", 0, none),
  ("LINEAR B SYLLABLE B007 DI", "Lo", 0, none),
  ("LINEAR B SYLLABLE B014 DO", "Lo", 0, none),
  ("LINEAR B SYLLABLE B051 DU", "Lo", 0, none),
  ("LINEAR B SYLLABLE B057 JA", "Lo", 0, none),
  ("LINEAR B SYLLABLE B046 JE", "Lo", 0, none),
  (),
  ("LINEAR B SYLLABLE B036 JO", "Lo", 0, none),
  ("LINEAR B SYLLABLE B065 JU", "Lo", 0, none),
  ("LINEAR B SYLLABLE B077 KA", "Lo", 0, none),
  ("LINEAR B SYLLABLE B044 KE", "Lo", 0, none),
  ("LINEAR B SYLLABLE B067 KI", "Lo", 0, none),
  ("LINEAR B SYLLABLE B070 KO", "Lo", 0, none),
  ("LINEAR B SYLLABLE B081 KU", "Lo", 0, none),
  ("LINEAR B SYLLABLE B080 MA", "Lo", 0, none),
  ("LINEAR B SYLLABLE B013 ME", "Lo", 0, none),
  ("LINEAR B SYLLABLE B073 MI", "Lo", 0, none),
  ("LINEAR B SYLLABLE B015 MO", "Lo", 0, none),
  ("LINEAR B SYLLABLE B023 MU", "Lo", 0, none),
  ("LINEAR B SYLLABLE B006 NA", "Lo", 0, none),
  ("LINEAR B SYLLABLE B024 NE", "Lo", 0, none),
  ("LINEAR B SYLLABLE B030 NI", "Lo", 0, none),
  ("LINEAR B SYLLABLE B052 NO", "Lo", 0, none),
  ("LINEAR B SYLLABLE B055 NU", "Lo", 0, none),
  ("LINEAR B SYLLABLE B003 PA", "Lo", 0, none),
  ("LINEAR B SYLLABLE B072 PE", "Lo", 0, none),
  ("LINEAR B SYLLABLE B039 PI", "Lo", 0, none),
  ("LINEAR B SYLLABLE B011 PO", "Lo", 0, none),
  ("LINEAR B SYLLABLE B050 PU", "Lo", 0, none),
  ("LINEAR B SYLLABLE B016 QA", "Lo", 0, none),
  ("LINEAR B SYLLABLE B078 QE", "Lo", 0, none),
  ("LINEAR B SYLLABLE B021 QI", "Lo", 0, none),
  ("LINEAR B SYLLABLE B032 QO", "Lo", 0, none),
  (),
  ("LINEAR B SYLLABLE B060 RA", "Lo", 0, none),
  ("LINEAR B SYLLABLE B027 RE", "Lo", 0, none),
  ("LINEAR B SYLLABLE B053 RI", "Lo", 0, none),
  ("LINEAR B SYLLABLE B002 RO", "Lo", 0, none),
  ("LINEAR B SYLLABLE B026 RU", "Lo", 0, none),
  ("LINEAR B SYLLABLE B031 SA", "Lo", 0, none),
  ("LINEAR B SYLLABLE B009 SE", "Lo", 0, none),
  ("LINEAR B SYLLABLE B041 SI", "Lo", 0, none),
  ("LINEAR B SYLLABLE B012 SO", "Lo", 0, none),
  ("LINEAR B SYLLABLE B058 SU", "Lo", 0, none),
  ("LINEAR B SYLLABLE B059 TA", "Lo", 0, none),
  ("LINEAR B SYLLABLE B004 TE", "Lo", 0, none),
  ("LINEAR B SYLLABLE B037 TI", "Lo", 0, none),
  ("LINEAR B SYLLABLE B005 TO", "Lo", 0, none),
  ("LINEAR B SYLLABLE B069 TU", "Lo", 0, none),
  ("LINEAR B SYLLABLE B054 WA", "Lo", 0, none),
  ("LINEAR B SYLLABLE B075 WE", "Lo", 0, none),
  ("LINEAR B SYLLABLE B040 WI", "Lo", 0, none),
  ("LINEAR B SYLLABLE B042 WO", "Lo", 0, none),
  (),
  ("LINEAR B SYLLABLE B017 ZA", "Lo", 0, none),
  ("LINEAR B SYLLABLE B074 ZE", "Lo", 0, none),
  (),
  ("LINEAR B SYLLABLE B020 ZO", "Lo", 0, none),
  ("LINEAR B SYLLABLE B025 A2", "Lo", 0, none),
  ("LINEAR B SYLLABLE B043 A3", "Lo", 0, none),
  ("LINEAR B SYLLABLE B085 AU", "Lo", 0, none),
  ("LINEAR B SYLLABLE B071 DWE", "Lo", 0, none),
  ("LINEAR B SYLLABLE B090 DWO", "Lo", 0, none),
  ("LINEAR B SYLLABLE B048 NWA", "Lo", 0, none),
  ("LINEAR B SYLLABLE B029 PU2", "Lo", 0, none),
  ("LINEAR B SYLLABLE B062 PTE", "Lo", 0, none),
  ("LINEAR B SYLLABLE B076 RA2", "Lo", 0, none),
  ("LINEAR B SYLLABLE B033 RA3", "Lo", 0, none),
  ("LINEAR B SYLLABLE B068 RO2", "Lo", 0, none),
  ("LINEAR B SYLLABLE B066 TA2", "Lo", 0, none),
  ("LINEAR B SYLLABLE B087 TWE", "Lo", 0, none),
  ("LINEAR B SYLLABLE B091 TWO", "Lo", 0, none),
  (),
  (),
  ("LINEAR B SYMBOL B018", "Lo", 0, none),
  ("LINEAR B SYMBOL B019", "Lo", 0, none),
  ("LINEAR B SYMBOL B022", "Lo", 0, none),
  ("LINEAR B SYMBOL B034", "Lo", 0, none),
  ("LINEAR B SYMBOL B047", "Lo", 0, none),
  ("LINEAR B SYMBOL B049", "Lo", 0, none),
  ("LINEAR B SYMBOL B056", "Lo", 0, none),
  ("LINEAR B SYMBOL B063", "Lo", 0, none),
  ("LINEAR B SYMBOL B064", "Lo", 0, none),
  ("LINEAR B SYMBOL B079", "Lo", 0, none),
  ("LINEAR B SYMBOL B082", "Lo", 0, none),
  ("LINEAR B SYMBOL B083", "Lo", 0, none),
  ("LINEAR B SYMBOL B086", "Lo", 0, none),
  ("LINEAR B SYMBOL B089", "Lo", 0, none),
)
