#let data = (
  ("OLD UYGHUR LETTER ALEPH", "Lo", 0, none),
  ("OLD UYGHUR LETTER BETH", "Lo", 0, none),
  ("OLD UYGHUR LETTER GIMEL-HETH", "Lo", 0, none),
  ("OLD UYGHUR LETTER WAW", "Lo", 0, none),
  ("OLD UYGHUR LETTER ZAYIN", "Lo", 0, none),
  ("OLD UYGHUR LETTER FINAL HETH", "Lo", 0, none),
  ("OLD UYGHUR LETTER YODH", "Lo", 0, none),
  ("OLD UYGHUR LETTER KAPH", "Lo", 0, none),
  ("OLD UYGHUR LETTER LAMEDH", "Lo", 0, none),
  ("OLD UYGHUR LETTER MEM", "Lo", 0, none),
  ("OLD UYGHUR LETTER NUN", "Lo", 0, none),
  ("OLD UYGHUR LETTER SAMEKH", "Lo", 0, none),
  ("OLD UYGHUR LETTER PE", "Lo", 0, none),
  ("OLD UYGHUR LETTER SADHE", "Lo", 0, none),
  ("OLD UYGHUR LETTER RESH", "Lo", 0, none),
  ("OLD UYGHUR LETTER SHIN", "Lo", 0, none),
  ("OLD UYGHUR LETTER TAW", "Lo", 0, none),
  ("OLD UYGHUR LETTER LESH", "Lo", 0, none),
  ("OLD UYGHUR COMBINING DOT ABOVE", "Mn", 230, none),
  ("OLD UYGHUR COMBINING DOT BELOW", "Mn", 220, none),
  ("OLD UYGHUR COMBINING TWO DOTS ABOVE", "Mn", 230, none),
  ("OLD UYGHUR COMBINING TWO DOTS BELOW", "Mn", 220, none),
  ("OLD UYGHUR PUNCTUATION BAR", "Po", 0, none),
  ("OLD UYGHUR PUNCTUATION TWO BARS", "Po", 0, none),
  ("OLD UYGHUR PUNCTUATION TWO DOTS", "Po", 0, none),
  ("OLD UYGHUR PUNCTUATION FOUR DOTS", "Po", 0, none),
)
