#let data = (
  ("TIRHUTA ANJI", "Lo", 0, none),
  ("TIRHUTA LETTER A", "Lo", 0, none),
  ("TIRHUTA LETTER AA", "Lo", 0, none),
  ("TIRHUTA LETTER I", "Lo", 0, none),
  ("TIRHUTA LETTER II", "Lo", 0, none),
  ("TIRHUTA LETTER U", "Lo", 0, none),
  ("TIRHUTA LETTER UU", "Lo", 0, none),
  ("TIRHUTA LETTER VOCALIC R", "Lo", 0, none),
  ("TIRHUTA LETTER VOCALIC RR", "Lo", 0, none),
  ("TIRHUTA LETTER VOCALIC L", "Lo", 0, none),
  ("TIRHUTA LETTER VOCALIC LL", "Lo", 0, none),
  ("TIRHUTA LETTER E", "Lo", 0, none),
  ("TIRHUTA LETTER AI", "Lo", 0, none),
  ("TIRHUTA LETTER O", "Lo", 0, none),
  ("TIRHUTA LETTER AU", "Lo", 0, none),
  ("TIRHUTA LETTER KA", "Lo", 0, none),
  ("TIRHUTA LETTER KHA", "Lo", 0, none),
  ("TIRHUTA LETTER GA", "Lo", 0, none),
  ("TIRHUTA LETTER GHA", "Lo", 0, none),
  ("TIRHUTA LETTER NGA", "Lo", 0, none),
  ("TIRHUTA LETTER CA", "Lo", 0, none),
  ("TIRHUTA LETTER CHA", "Lo", 0, none),
  ("TIRHUTA LETTER JA", "Lo", 0, none),
  ("TIRHUTA LETTER JHA", "Lo", 0, none),
  ("TIRHUTA LETTER NYA", "Lo", 0, none),
  ("TIRHUTA LETTER TTA", "Lo", 0, none),
  ("TIRHUTA LETTER TTHA", "Lo", 0, none),
  ("TIRHUTA LETTER DDA", "Lo", 0, none),
  ("TIRHUTA LETTER DDHA", "Lo", 0, none),
  ("TIRHUTA LETTER NNA", "Lo", 0, none),
  ("TIRHUTA LETTER TA", "Lo", 0, none),
  ("TIRHUTA LETTER THA", "Lo", 0, none),
  ("TIRHUTA LETTER DA", "Lo", 0, none),
  ("TIRHUTA LETTER DHA", "Lo", 0, none),
  ("TIRHUTA LETTER NA", "Lo", 0, none),
  ("TIRHUTA LETTER PA", "Lo", 0, none),
  ("TIRHUTA LETTER PHA", "Lo", 0, none),
  ("TIRHUTA LETTER BA", "Lo", 0, none),
  ("TIRHUTA LETTER BHA", "Lo", 0, none),
  ("TIRHUTA LETTER MA", "Lo", 0, none),
  ("TIRHUTA LETTER YA", "Lo", 0, none),
  ("TIRHUTA LETTER RA", "Lo", 0, none),
  ("TIRHUTA LETTER LA", "Lo", 0, none),
  ("TIRHUTA LETTER VA", "Lo", 0, none),
  ("TIRHUTA LETTER SHA", "Lo", 0, none),
  ("TIRHUTA LETTER SSA", "Lo", 0, none),
  ("TIRHUTA LETTER SA", "Lo", 0, none),
  ("TIRHUTA LETTER HA", "Lo", 0, none),
  ("TIRHUTA VOWEL SIGN AA", "Mc", 0, none),
  ("TIRHUTA VOWEL SIGN I", "Mc", 0, none),
  ("TIRHUTA VOWEL SIGN II", "Mc", 0, none),
  ("TIRHUTA VOWEL SIGN U", "Mn", 0, none),
  ("TIRHUTA VOWEL SIGN UU", "Mn", 0, none),
  ("TIRHUTA VOWEL SIGN VOCALIC R", "Mn", 0, none),
  ("TIRHUTA VOWEL SIGN VOCALIC RR", "Mn", 0, none),
  ("TIRHUTA VOWEL SIGN VOCALIC L", "Mn", 0, none),
  ("TIRHUTA VOWEL SIGN VOCALIC LL", "Mn", 0, none),
  ("TIRHUTA VOWEL SIGN E", "Mc", 0, none),
  ("TIRHUTA VOWEL SIGN SHORT E", "Mn", 0, none),
  ("TIRHUTA VOWEL SIGN AI", "Mc", 0, none),
  ("TIRHUTA VOWEL SIGN O", "Mc", 0, none),
  ("TIRHUTA VOWEL SIGN SHORT O", "Mc", 0, none),
  ("TIRHUTA VOWEL SIGN AU", "Mc", 0, none),
  ("TIRHUTA SIGN CANDRABINDU", "Mn", 0, none),
  ("TIRHUTA SIGN ANUSVARA", "Mn", 0, none),
  ("TIRHUTA SIGN VISARGA", "Mc", 0, none),
  ("TIRHUTA SIGN VIRAMA", "Mn", 9, none),
  ("TIRHUTA SIGN NUKTA", "Mn", 7, none),
  ("TIRHUTA SIGN AVAGRAHA", "Lo", 0, none),
  ("TIRHUTA GVANG", "Lo", 0, none),
  ("TIRHUTA ABBREVIATION SIGN", "Po", 0, none),
  ("TIRHUTA OM", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TIRHUTA DIGIT ZERO", "Nd", 0, none),
  ("TIRHUTA DIGIT ONE", "Nd", 0, none),
  ("TIRHUTA DIGIT TWO", "Nd", 0, none),
  ("TIRHUTA DIGIT THREE", "Nd", 0, none),
  ("TIRHUTA DIGIT FOUR", "Nd", 0, none),
  ("TIRHUTA DIGIT FIVE", "Nd", 0, none),
  ("TIRHUTA DIGIT SIX", "Nd", 0, none),
  ("TIRHUTA DIGIT SEVEN", "Nd", 0, none),
  ("TIRHUTA DIGIT EIGHT", "Nd", 0, none),
  ("TIRHUTA DIGIT NINE", "Nd", 0, none),
)
