#let data = (
  ("SQUARE APAATO", "So", 0, none),
  ("SQUARE ARUHUA", "So", 0, none),
  ("SQUARE ANPEA", "So", 0, none),
  ("SQUARE AARU", "So", 0, none),
  ("SQUARE ININGU", "So", 0, none),
  ("SQUARE INTI", "So", 0, none),
  ("SQUARE UON", "So", 0, none),
  ("SQUARE ESUKUUDO", "So", 0, none),
  ("SQUARE EEKAA", "So", 0, none),
  ("SQUARE ONSU", "So", 0, none),
  ("SQUARE OOMU", "So", 0, none),
  ("SQUARE KAIRI", "So", 0, none),
  ("SQUARE KARATTO", "So", 0, none),
  ("SQUARE KARORII", "So", 0, none),
  ("SQUARE GARON", "So", 0, none),
  ("SQUARE GANMA", "So", 0, none),
  ("SQUARE GIGA", "So", 0, none),
  ("SQUARE GINII", "So", 0, none),
  ("SQUARE KYURII", "So", 0, none),
  ("SQUARE GIRUDAA", "So", 0, none),
  ("SQUARE KIRO", "So", 0, none),
  ("SQUARE KIROGURAMU", "So", 0, none),
  ("SQUARE KIROMEETORU", "So", 0, none),
  ("SQUARE KIROWATTO", "So", 0, none),
  ("SQUARE GURAMU", "So", 0, none),
  ("SQUARE GURAMUTON", "So", 0, none),
  ("SQUARE KURUZEIRO", "So", 0, none),
  ("SQUARE KUROONE", "So", 0, none),
  ("SQUARE KEESU", "So", 0, none),
  ("SQUARE KORUNA", "So", 0, none),
  ("SQUARE KOOPO", "So", 0, none),
  ("SQUARE SAIKURU", "So", 0, none),
  ("SQUARE SANTIIMU", "So", 0, none),
  ("SQUARE SIRINGU", "So", 0, none),
  ("SQUARE SENTI", "So", 0, none),
  ("SQUARE SENTO", "So", 0, none),
  ("SQUARE DAASU", "So", 0, none),
  ("SQUARE DESI", "So", 0, none),
  ("SQUARE DORU", "So", 0, none),
  ("SQUARE TON", "So", 0, none),
  ("SQUARE NANO", "So", 0, none),
  ("SQUARE NOTTO", "So", 0, none),
  ("SQUARE HAITU", "So", 0, none),
  ("SQUARE PAASENTO", "So", 0, none),
  ("SQUARE PAATU", "So", 0, none),
  ("SQUARE BAARERU", "So", 0, none),
  ("SQUARE PIASUTORU", "So", 0, none),
  ("SQUARE PIKURU", "So", 0, none),
  ("SQUARE PIKO", "So", 0, none),
  ("SQUARE BIRU", "So", 0, none),
  ("SQUARE HUARADDO", "So", 0, none),
  ("SQUARE HUIITO", "So", 0, none),
  ("SQUARE BUSSYERU", "So", 0, none),
  ("SQUARE HURAN", "So", 0, none),
  ("SQUARE HEKUTAARU", "So", 0, none),
  ("SQUARE PESO", "So", 0, none),
  ("SQUARE PENIHI", "So", 0, none),
  ("SQUARE HERUTU", "So", 0, none),
  ("SQUARE PENSU", "So", 0, none),
  ("SQUARE PEEZI", "So", 0, none),
  ("SQUARE BEETA", "So", 0, none),
  ("SQUARE POINTO", "So", 0, none),
  ("SQUARE BORUTO", "So", 0, none),
  ("SQUARE HON", "So", 0, none),
  ("SQUARE PONDO", "So", 0, none),
  ("SQUARE HOORU", "So", 0, none),
  ("SQUARE HOON", "So", 0, none),
  ("SQUARE MAIKURO", "So", 0, none),
  ("SQUARE MAIRU", "So", 0, none),
  ("SQUARE MAHHA", "So", 0, none),
  ("SQUARE MARUKU", "So", 0, none),
  ("SQUARE MANSYON", "So", 0, none),
  ("SQUARE MIKURON", "So", 0, none),
  ("SQUARE MIRI", "So", 0, none),
  ("SQUARE MIRIBAARU", "So", 0, none),
  ("SQUARE MEGA", "So", 0, none),
  ("SQUARE MEGATON", "So", 0, none),
  ("SQUARE MEETORU", "So", 0, none),
  ("SQUARE YAADO", "So", 0, none),
  ("SQUARE YAARU", "So", 0, none),
  ("SQUARE YUAN", "So", 0, none),
  ("SQUARE RITTORU", "So", 0, none),
  ("SQUARE RIRA", "So", 0, none),
  ("SQUARE RUPII", "So", 0, none),
  ("SQUARE RUUBURU", "So", 0, none),
  ("SQUARE REMU", "So", 0, none),
  ("SQUARE RENTOGEN", "So", 0, none),
  ("SQUARE WATTO", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR ZERO", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR ONE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWO", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR THREE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR FOUR", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR FIVE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR SIX", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR SEVEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR EIGHT", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR NINE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR ELEVEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWELVE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR THIRTEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR FOURTEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR FIFTEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR SIXTEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR SEVENTEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR EIGHTEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR NINETEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWENTY", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWENTY-ONE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWENTY-TWO", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWENTY-THREE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR HOUR TWENTY-FOUR", "So", 0, none),
  ("SQUARE HPA", "So", 0, none),
  ("SQUARE DA", "So", 0, none),
  ("SQUARE AU", "So", 0, none),
  ("SQUARE BAR", "So", 0, none),
  ("SQUARE OV", "So", 0, none),
  ("SQUARE PC", "So", 0, none),
  ("SQUARE DM", "So", 0, none),
  ("SQUARE DM SQUARED", "So", 0, none),
  ("SQUARE DM CUBED", "So", 0, none),
  ("SQUARE IU", "So", 0, none),
  ("SQUARE ERA NAME HEISEI", "So", 0, none),
  ("SQUARE ERA NAME SYOUWA", "So", 0, none),
  ("SQUARE ERA NAME TAISYOU", "So", 0, none),
  ("SQUARE ERA NAME MEIZI", "So", 0, none),
  ("SQUARE CORPORATION", "So", 0, none),
  ("SQUARE PA AMPS", "So", 0, none),
  ("SQUARE NA", "So", 0, none),
  ("SQUARE MU A", "So", 0, none),
  ("SQUARE MA", "So", 0, none),
  ("SQUARE KA", "So", 0, none),
  ("SQUARE KB", "So", 0, none),
  ("SQUARE MB", "So", 0, none),
  ("SQUARE GB", "So", 0, none),
  ("SQUARE CAL", "So", 0, none),
  ("SQUARE KCAL", "So", 0, none),
  ("SQUARE PF", "So", 0, none),
  ("SQUARE NF", "So", 0, none),
  ("SQUARE MU F", "So", 0, none),
  ("SQUARE MU G", "So", 0, none),
  ("SQUARE MG", "So", 0, none),
  ("SQUARE KG", "So", 0, none),
  ("SQUARE HZ", "So", 0, none),
  ("SQUARE KHZ", "So", 0, none),
  ("SQUARE MHZ", "So", 0, none),
  ("SQUARE GHZ", "So", 0, none),
  ("SQUARE THZ", "So", 0, none),
  ("SQUARE MU L", "So", 0, none),
  ("SQUARE ML", "So", 0, none),
  ("SQUARE DL", "So", 0, none),
  ("SQUARE KL", "So", 0, none),
  ("SQUARE FM", "So", 0, none),
  ("SQUARE NM", "So", 0, none),
  ("SQUARE MU M", "So", 0, none),
  ("SQUARE MM", "So", 0, none),
  ("SQUARE CM", "So", 0, none),
  ("SQUARE KM", "So", 0, none),
  ("SQUARE MM SQUARED", "So", 0, none),
  ("SQUARE CM SQUARED", "So", 0, none),
  ("SQUARE M SQUARED", "So", 0, none),
  ("SQUARE KM SQUARED", "So", 0, none),
  ("SQUARE MM CUBED", "So", 0, none),
  ("SQUARE CM CUBED", "So", 0, none),
  ("SQUARE M CUBED", "So", 0, none),
  ("SQUARE KM CUBED", "So", 0, none),
  ("SQUARE M OVER S", "So", 0, none),
  ("SQUARE M OVER S SQUARED", "So", 0, none),
  ("SQUARE PA", "So", 0, none),
  ("SQUARE KPA", "So", 0, none),
  ("SQUARE MPA", "So", 0, none),
  ("SQUARE GPA", "So", 0, none),
  ("SQUARE RAD", "So", 0, none),
  ("SQUARE RAD OVER S", "So", 0, none),
  ("SQUARE RAD OVER S SQUARED", "So", 0, none),
  ("SQUARE PS", "So", 0, none),
  ("SQUARE NS", "So", 0, none),
  ("SQUARE MU S", "So", 0, none),
  ("SQUARE MS", "So", 0, none),
  ("SQUARE PV", "So", 0, none),
  ("SQUARE NV", "So", 0, none),
  ("SQUARE MU V", "So", 0, none),
  ("SQUARE MV", "So", 0, none),
  ("SQUARE KV", "So", 0, none),
  ("SQUARE MV MEGA", "So", 0, none),
  ("SQUARE PW", "So", 0, none),
  ("SQUARE NW", "So", 0, none),
  ("SQUARE MU W", "So", 0, none),
  ("SQUARE MW", "So", 0, none),
  ("SQUARE KW", "So", 0, none),
  ("SQUARE MW MEGA", "So", 0, none),
  ("SQUARE K OHM", "So", 0, none),
  ("SQUARE M OHM", "So", 0, none),
  ("SQUARE AM", "So", 0, none),
  ("SQUARE BQ", "So", 0, none),
  ("SQUARE CC", "So", 0, none),
  ("SQUARE CD", "So", 0, none),
  ("SQUARE C OVER KG", "So", 0, none),
  ("SQUARE CO", "So", 0, none),
  ("SQUARE DB", "So", 0, none),
  ("SQUARE GY", "So", 0, none),
  ("SQUARE HA", "So", 0, none),
  ("SQUARE HP", "So", 0, none),
  ("SQUARE IN", "So", 0, none),
  ("SQUARE KK", "So", 0, none),
  ("SQUARE KM CAPITAL", "So", 0, none),
  ("SQUARE KT", "So", 0, none),
  ("SQUARE LM", "So", 0, none),
  ("SQUARE LN", "So", 0, none),
  ("SQUARE LOG", "So", 0, none),
  ("SQUARE LX", "So", 0, none),
  ("SQUARE MB SMALL", "So", 0, none),
  ("SQUARE MIL", "So", 0, none),
  ("SQUARE MOL", "So", 0, none),
  ("SQUARE PH", "So", 0, none),
  ("SQUARE PM", "So", 0, none),
  ("SQUARE PPM", "So", 0, none),
  ("SQUARE PR", "So", 0, none),
  ("SQUARE SR", "So", 0, none),
  ("SQUARE SV", "So", 0, none),
  ("SQUARE WB", "So", 0, none),
  ("SQUARE V OVER M", "So", 0, none),
  ("SQUARE A OVER M", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY ONE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWO", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY THREE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY FOUR", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY FIVE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY SIX", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY SEVEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY EIGHT", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY NINE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY ELEVEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWELVE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY THIRTEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY FOURTEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY FIFTEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY SIXTEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY SEVENTEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY EIGHTEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY NINETEEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-ONE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-TWO", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-THREE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-FOUR", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-FIVE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-SIX", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-SEVEN", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-EIGHT", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY TWENTY-NINE", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY THIRTY", "So", 0, none),
  ("IDEOGRAPHIC TELEGRAPH SYMBOL FOR DAY THIRTY-ONE", "So", 0, none),
  ("SQUARE GAL", "So", 0, none),
)
