#let data = (
  ("DIVES AKURU LETTER A", "Lo", 0, none),
  ("DIVES AKURU LETTER AA", "Lo", 0, none),
  ("DIVES AKURU LETTER I", "Lo", 0, none),
  ("DIVES AKURU LETTER II", "Lo", 0, none),
  ("DIVES AKURU LETTER U", "Lo", 0, none),
  ("DIVES AKURU LETTER UU", "Lo", 0, none),
  ("DIVES AKURU LETTER E", "Lo", 0, none),
  (),
  (),
  ("DIVES AKURU LETTER O", "Lo", 0, none),
  (),
  (),
  ("DIVES AKURU LETTER KA", "Lo", 0, none),
  ("DIVES AKURU LETTER KHA", "Lo", 0, none),
  ("DIVES AKURU LETTER GA", "Lo", 0, none),
  ("DIVES AKURU LETTER GHA", "Lo", 0, none),
  ("DIVES AKURU LETTER NGA", "Lo", 0, none),
  ("DIVES AKURU LETTER CA", "Lo", 0, none),
  ("DIVES AKURU LETTER CHA", "Lo", 0, none),
  ("DIVES AKURU LETTER JA", "Lo", 0, none),
  (),
  ("DIVES AKURU LETTER NYA", "Lo", 0, none),
  ("DIVES AKURU LETTER TTA", "Lo", 0, none),
  (),
  ("DIVES AKURU LETTER DDA", "Lo", 0, none),
  ("DIVES AKURU LETTER DDHA", "Lo", 0, none),
  ("DIVES AKURU LETTER NNA", "Lo", 0, none),
  ("DIVES AKURU LETTER TA", "Lo", 0, none),
  ("DIVES AKURU LETTER THA", "Lo", 0, none),
  ("DIVES AKURU LETTER DA", "Lo", 0, none),
  ("DIVES AKURU LETTER DHA", "Lo", 0, none),
  ("DIVES AKURU LETTER NA", "Lo", 0, none),
  ("DIVES AKURU LETTER PA", "Lo", 0, none),
  ("DIVES AKURU LETTER PHA", "Lo", 0, none),
  ("DIVES AKURU LETTER BA", "Lo", 0, none),
  ("DIVES AKURU LETTER BHA", "Lo", 0, none),
  ("DIVES AKURU LETTER MA", "Lo", 0, none),
  ("DIVES AKURU LETTER YA", "Lo", 0, none),
  ("DIVES AKURU LETTER YYA", "Lo", 0, none),
  ("DIVES AKURU LETTER RA", "Lo", 0, none),
  ("DIVES AKURU LETTER LA", "Lo", 0, none),
  ("DIVES AKURU LETTER VA", "Lo", 0, none),
  ("DIVES AKURU LETTER SHA", "Lo", 0, none),
  ("DIVES AKURU LETTER SSA", "Lo", 0, none),
  ("DIVES AKURU LETTER SA", "Lo", 0, none),
  ("DIVES AKURU LETTER HA", "Lo", 0, none),
  ("DIVES AKURU LETTER LLA", "Lo", 0, none),
  ("DIVES AKURU LETTER ZA", "Lo", 0, none),
  ("DIVES AKURU VOWEL SIGN AA", "Mc", 0, none),
  ("DIVES AKURU VOWEL SIGN I", "Mc", 0, none),
  ("DIVES AKURU VOWEL SIGN II", "Mc", 0, none),
  ("DIVES AKURU VOWEL SIGN U", "Mc", 0, none),
  ("DIVES AKURU VOWEL SIGN UU", "Mc", 0, none),
  ("DIVES AKURU VOWEL SIGN E", "Mc", 0, none),
  (),
  ("DIVES AKURU VOWEL SIGN AI", "Mc", 0, none),
  ("DIVES AKURU VOWEL SIGN O", "Mc", 0, none),
  (),
  (),
  ("DIVES AKURU SIGN ANUSVARA", "Mn", 0, none),
  ("DIVES AKURU SIGN CANDRABINDU", "Mn", 0, none),
  ("DIVES AKURU SIGN HALANTA", "Mc", 9, none),
  ("DIVES AKURU VIRAMA", "Mn", 9, none),
  ("DIVES AKURU PREFIXED NASAL SIGN", "Lo", 0, none),
  ("DIVES AKURU MEDIAL YA", "Mc", 0, none),
  ("DIVES AKURU INITIAL RA", "Lo", 0, none),
  ("DIVES AKURU MEDIAL RA", "Mc", 0, none),
  ("DIVES AKURU SIGN NUKTA", "Mn", 7, none),
  ("DIVES AKURU DOUBLE DANDA", "Po", 0, none),
  ("DIVES AKURU GAP FILLER", "Po", 0, none),
  ("DIVES AKURU END OF TEXT MARK", "Po", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("DIVES AKURU DIGIT ZERO", "Nd", 0, none),
  ("DIVES AKURU DIGIT ONE", "Nd", 0, none),
  ("DIVES AKURU DIGIT TWO", "Nd", 0, none),
  ("DIVES AKURU DIGIT THREE", "Nd", 0, none),
  ("DIVES AKURU DIGIT FOUR", "Nd", 0, none),
  ("DIVES AKURU DIGIT FIVE", "Nd", 0, none),
  ("DIVES AKURU DIGIT SIX", "Nd", 0, none),
  ("DIVES AKURU DIGIT SEVEN", "Nd", 0, none),
  ("DIVES AKURU DIGIT EIGHT", "Nd", 0, none),
  ("DIVES AKURU DIGIT NINE", "Nd", 0, none),
)
