#let data = (
  (),
  ("GURMUKHI SIGN ADAK BINDI", "Mn", 0, none),
  ("GURMUKHI SIGN BINDI", "Mn", 0, none),
  ("GURMUKHI SIGN VISARGA", "Mc", 0, none),
  (),
  ("GURMUKHI LETTER A", "Lo", 0, none),
  ("GURMUKHI LETTER AA", "Lo", 0, none),
  ("GURMUKHI LETTER I", "Lo", 0, none),
  ("GURMUKHI LETTER II", "Lo", 0, none),
  ("GURMUKHI LETTER U", "Lo", 0, none),
  ("GURMUKHI LETTER UU", "Lo", 0, none),
  (),
  (),
  (),
  (),
  ("GURMUKHI LETTER EE", "Lo", 0, none),
  ("GURMUKHI LETTER AI", "Lo", 0, none),
  (),
  (),
  ("GURMUKHI LETTER OO", "Lo", 0, none),
  ("GURMUKHI LETTER AU", "Lo", 0, none),
  ("GURMUKHI LETTER KA", "Lo", 0, none),
  ("GURMUKHI LETTER KHA", "Lo", 0, none),
  ("GURMUKHI LETTER GA", "Lo", 0, none),
  ("GURMUKHI LETTER GHA", "Lo", 0, none),
  ("GURMUKHI LETTER NGA", "Lo", 0, none),
  ("GURMUKHI LETTER CA", "Lo", 0, none),
  ("GURMUKHI LETTER CHA", "Lo", 0, none),
  ("GURMUKHI LETTER JA", "Lo", 0, none),
  ("GURMUKHI LETTER JHA", "Lo", 0, none),
  ("GURMUKHI LETTER NYA", "Lo", 0, none),
  ("GURMUKHI LETTER TTA", "Lo", 0, none),
  ("GURMUKHI LETTER TTHA", "Lo", 0, none),
  ("GURMUKHI LETTER DDA", "Lo", 0, none),
  ("GURMUKHI LETTER DDHA", "Lo", 0, none),
  ("GURMUKHI LETTER NNA", "Lo", 0, none),
  ("GURMUKHI LETTER TA", "Lo", 0, none),
  ("GURMUKHI LETTER THA", "Lo", 0, none),
  ("GURMUKHI LETTER DA", "Lo", 0, none),
  ("GURMUKHI LETTER DHA", "Lo", 0, none),
  ("GURMUKHI LETTER NA", "Lo", 0, none),
  (),
  ("GURMUKHI LETTER PA", "Lo", 0, none),
  ("GURMUKHI LETTER PHA", "Lo", 0, none),
  ("GURMUKHI LETTER BA", "Lo", 0, none),
  ("GURMUKHI LETTER BHA", "Lo", 0, none),
  ("GURMUKHI LETTER MA", "Lo", 0, none),
  ("GURMUKHI LETTER YA", "Lo", 0, none),
  ("GURMUKHI LETTER RA", "Lo", 0, none),
  (),
  ("GURMUKHI LETTER LA", "Lo", 0, none),
  ("GURMUKHI LETTER LLA", "Lo", 0, none),
  (),
  ("GURMUKHI LETTER VA", "Lo", 0, none),
  ("GURMUKHI LETTER SHA", "Lo", 0, none),
  (),
  ("GURMUKHI LETTER SA", "Lo", 0, none),
  ("GURMUKHI LETTER HA", "Lo", 0, none),
  (),
  (),
  ("GURMUKHI SIGN NUKTA", "Mn", 7, none),
  (),
  ("GURMUKHI VOWEL SIGN AA", "Mc", 0, none),
  ("GURMUKHI VOWEL SIGN I", "Mc", 0, none),
  ("GURMUKHI VOWEL SIGN II", "Mc", 0, none),
  ("GURMUKHI VOWEL SIGN U", "Mn", 0, none),
  ("GURMUKHI VOWEL SIGN UU", "Mn", 0, none),
  (),
  (),
  (),
  (),
  ("GURMUKHI VOWEL SIGN EE", "Mn", 0, none),
  ("GURMUKHI VOWEL SIGN AI", "Mn", 0, none),
  (),
  (),
  ("GURMUKHI VOWEL SIGN OO", "Mn", 0, none),
  ("GURMUKHI VOWEL SIGN AU", "Mn", 0, none),
  ("GURMUKHI SIGN VIRAMA", "Mn", 9, none),
  (),
  (),
  (),
  ("GURMUKHI SIGN UDAAT", "Mn", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("GURMUKHI LETTER KHHA", "Lo", 0, none),
  ("GURMUKHI LETTER GHHA", "Lo", 0, none),
  ("GURMUKHI LETTER ZA", "Lo", 0, none),
  ("GURMUKHI LETTER RRA", "Lo", 0, none),
  (),
  ("GURMUKHI LETTER FA", "Lo", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("GURMUKHI DIGIT ZERO", "Nd", 0, none),
  ("GURMUKHI DIGIT ONE", "Nd", 0, none),
  ("GURMUKHI DIGIT TWO", "Nd", 0, none),
  ("GURMUKHI DIGIT THREE", "Nd", 0, none),
  ("GURMUKHI DIGIT FOUR", "Nd", 0, none),
  ("GURMUKHI DIGIT FIVE", "Nd", 0, none),
  ("GURMUKHI DIGIT SIX", "Nd", 0, none),
  ("GURMUKHI DIGIT SEVEN", "Nd", 0, none),
  ("GURMUKHI DIGIT EIGHT", "Nd", 0, none),
  ("GURMUKHI DIGIT NINE", "Nd", 0, none),
  ("GURMUKHI TIPPI", "Mn", 0, none),
  ("GURMUKHI ADDAK", "Mn", 0, none),
  ("GURMUKHI IRI", "Lo", 0, none),
  ("GURMUKHI URA", "Lo", 0, none),
  ("GURMUKHI EK ONKAR", "Lo", 0, none),
  ("GURMUKHI SIGN YAKASH", "Mn", 0, none),
  ("GURMUKHI ABBREVIATION SIGN", "Po", 0, none),
)
