#let data = (
  ("ETHIOPIC SYLLABLE SEBATBEIT MWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE MWI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE MWEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE MWE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SEBATBEIT BWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BWI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BWEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE BWE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SEBATBEIT FWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE FWI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE FWEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE FWE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE SEBATBEIT PWA", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PWI", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PWEE", "Lo", 0, none),
  ("ETHIOPIC SYLLABLE PWE", "Lo", 0, none),
  ("ETHIOPIC TONAL MARK YIZET", "So", 0, none),
  ("ETHIOPIC TONAL MARK DERET", "So", 0, none),
  ("ETHIOPIC TONAL MARK RIKRIK", "So", 0, none),
  ("ETHIOPIC TONAL MARK SHORT RIKRIK", "So", 0, none),
  ("ETHIOPIC TONAL MARK DIFAT", "So", 0, none),
  ("ETHIOPIC TONAL MARK KENAT", "So", 0, none),
  ("ETHIOPIC TONAL MARK CHIRET", "So", 0, none),
  ("ETHIOPIC TONAL MARK HIDET", "So", 0, none),
  ("ETHIOPIC TONAL MARK DERET-HIDET", "So", 0, none),
  ("ETHIOPIC TONAL MARK KURT", "So", 0, none),
)
