#let data = (
  (),
  ("LANGUAGE TAG", "Cf", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("TAG SPACE", "Cf", 0, none),
  ("TAG EXCLAMATION MARK", "Cf", 0, none),
  ("TAG QUOTATION MARK", "Cf", 0, none),
  ("TAG NUMBER SIGN", "Cf", 0, none),
  ("TAG DOLLAR SIGN", "Cf", 0, none),
  ("TAG PERCENT SIGN", "Cf", 0, none),
  ("TAG AMPERSAND", "Cf", 0, none),
  ("TAG APOSTROPHE", "Cf", 0, none),
  ("TAG LEFT PARENTHESIS", "Cf", 0, none),
  ("TAG RIGHT PARENTHESIS", "Cf", 0, none),
  ("TAG ASTERISK", "Cf", 0, none),
  ("TAG PLUS SIGN", "Cf", 0, none),
  ("TAG COMMA", "Cf", 0, none),
  ("TAG HYPHEN-MINUS", "Cf", 0, none),
  ("TAG FULL STOP", "Cf", 0, none),
  ("TAG SOLIDUS", "Cf", 0, none),
  ("TAG DIGIT ZERO", "Cf", 0, none),
  ("TAG DIGIT ONE", "Cf", 0, none),
  ("TAG DIGIT TWO", "Cf", 0, none),
  ("TAG DIGIT THREE", "Cf", 0, none),
  ("TAG DIGIT FOUR", "Cf", 0, none),
  ("TAG DIGIT FIVE", "Cf", 0, none),
  ("TAG DIGIT SIX", "Cf", 0, none),
  ("TAG DIGIT SEVEN", "Cf", 0, none),
  ("TAG DIGIT EIGHT", "Cf", 0, none),
  ("TAG DIGIT NINE", "Cf", 0, none),
  ("TAG COLON", "Cf", 0, none),
  ("TAG SEMICOLON", "Cf", 0, none),
  ("TAG LESS-THAN SIGN", "Cf", 0, none),
  ("TAG EQUALS SIGN", "Cf", 0, none),
  ("TAG GREATER-THAN SIGN", "Cf", 0, none),
  ("TAG QUESTION MARK", "Cf", 0, none),
  ("TAG COMMERCIAL AT", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER A", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER B", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER C", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER D", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER E", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER F", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER G", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER H", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER I", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER J", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER K", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER L", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER M", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER N", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER O", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER P", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER Q", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER R", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER S", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER T", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER U", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER V", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER W", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER X", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER Y", "Cf", 0, none),
  ("TAG LATIN CAPITAL LETTER Z", "Cf", 0, none),
  ("TAG LEFT SQUARE BRACKET", "Cf", 0, none),
  ("TAG REVERSE SOLIDUS", "Cf", 0, none),
  ("TAG RIGHT SQUARE BRACKET", "Cf", 0, none),
  ("TAG CIRCUMFLEX ACCENT", "Cf", 0, none),
  ("TAG LOW LINE", "Cf", 0, none),
  ("TAG GRAVE ACCENT", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER A", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER B", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER C", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER D", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER E", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER F", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER G", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER H", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER I", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER J", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER K", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER L", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER M", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER N", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER O", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER P", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER Q", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER R", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER S", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER T", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER U", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER V", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER W", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER X", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER Y", "Cf", 0, none),
  ("TAG LATIN SMALL LETTER Z", "Cf", 0, none),
  ("TAG LEFT CURLY BRACKET", "Cf", 0, none),
  ("TAG VERTICAL LINE", "Cf", 0, none),
  ("TAG RIGHT CURLY BRACKET", "Cf", 0, none),
  ("TAG TILDE", "Cf", 0, none),
  ("CANCEL TAG", "Cf", 0, none),
)
