#let data = (
  ("KHAROSHTHI LETTER A", "Lo", 0, none),
  ("KHAROSHTHI VOWEL SIGN I", "Mn", 0, none),
  ("KHAROSHTHI VOWEL SIGN U", "Mn", 0, none),
  ("KHAROSHTHI VOWEL SIGN VOCALIC R", "Mn", 0, none),
  (),
  ("KHAROSHTHI VOWEL SIGN E", "Mn", 0, none),
  ("KHAROSHTHI VOWEL SIGN O", "Mn", 0, none),
  (),
  (),
  (),
  (),
  (),
  ("KHAROSHTHI VOWEL LENGTH MARK", "Mn", 0, none),
  ("KHAROSHTHI SIGN DOUBLE RING BELOW", "Mn", 220, none),
  ("KHAROSHTHI SIGN ANUSVARA", "Mn", 0, none),
  ("KHAROSHTHI SIGN VISARGA", "Mn", 230, none),
  ("KHAROSHTHI LETTER KA", "Lo", 0, none),
  ("KHAROSHTHI LETTER KHA", "Lo", 0, none),
  ("KHAROSHTHI LETTER GA", "Lo", 0, none),
  ("KHAROSHTHI LETTER GHA", "Lo", 0, none),
  (),
  ("KHAROSHTHI LETTER CA", "Lo", 0, none),
  ("KHAROSHTHI LETTER CHA", "Lo", 0, none),
  ("KHAROSHTHI LETTER JA", "Lo", 0, none),
  (),
  ("KHAROSHTHI LETTER NYA", "Lo", 0, none),
  ("KHAROSHTHI LETTER TTA", "Lo", 0, none),
  ("KHAROSHTHI LETTER TTHA", "Lo", 0, none),
  ("KHAROSHTHI LETTER DDA", "Lo", 0, none),
  ("KHAROSHTHI LETTER DDHA", "Lo", 0, none),
  ("KHAROSHTHI LETTER NNA", "Lo", 0, none),
  ("KHAROSHTHI LETTER TA", "Lo", 0, none),
  ("KHAROSHTHI LETTER THA", "Lo", 0, none),
  ("KHAROSHTHI LETTER DA", "Lo", 0, none),
  ("KHAROSHTHI LETTER DHA", "Lo", 0, none),
  ("KHAROSHTHI LETTER NA", "Lo", 0, none),
  ("KHAROSHTHI LETTER PA", "Lo", 0, none),
  ("KHAROSHTHI LETTER PHA", "Lo", 0, none),
  ("KHAROSHTHI LETTER BA", "Lo", 0, none),
  ("KHAROSHTHI LETTER BHA", "Lo", 0, none),
  ("KHAROSHTHI LETTER MA", "Lo", 0, none),
  ("KHAROSHTHI LETTER YA", "Lo", 0, none),
  ("KHAROSHTHI LETTER RA", "Lo", 0, none),
  ("KHAROSHTHI LETTER LA", "Lo", 0, none),
  ("KHAROSHTHI LETTER VA", "Lo", 0, none),
  ("KHAROSHTHI LETTER SHA", "Lo", 0, none),
  ("KHAROSHTHI LETTER SSA", "Lo", 0, none),
  ("KHAROSHTHI LETTER SA", "Lo", 0, none),
  ("KHAROSHTHI LETTER ZA", "Lo", 0, none),
  ("KHAROSHTHI LETTER HA", "Lo", 0, none),
  ("KHAROSHTHI LETTER KKA", "Lo", 0, none),
  ("KHAROSHTHI LETTER TTTHA", "Lo", 0, none),
  ("KHAROSHTHI LETTER TTTA", "Lo", 0, none),
  ("KHAROSHTHI LETTER VHA", "Lo", 0, none),
  (),
  (),
  ("KHAROSHTHI SIGN BAR ABOVE", "Mn", 230, none),
  ("KHAROSHTHI SIGN CAUDA", "Mn", 1, none),
  ("KHAROSHTHI SIGN DOT BELOW", "Mn", 220, none),
  (),
  (),
  (),
  (),
  ("KHAROSHTHI VIRAMA", "Mn", 9, none),
  ("KHAROSHTHI DIGIT ONE", "No", 0, none),
  ("KHAROSHTHI DIGIT TWO", "No", 0, none),
  ("KHAROSHTHI DIGIT THREE", "No", 0, none),
  ("KHAROSHTHI DIGIT FOUR", "No", 0, none),
  ("KHAROSHTHI NUMBER TEN", "No", 0, none),
  ("KHAROSHTHI NUMBER TWENTY", "No", 0, none),
  ("KHAROSHTHI NUMBER ONE HUNDRED", "No", 0, none),
  ("KHAROSHTHI NUMBER ONE THOUSAND", "No", 0, none),
  ("KHAROSHTHI FRACTION ONE HALF", "No", 0, none),
  (),
  (),
  (),
  (),
  (),
  (),
  (),
  ("KHAROSHTHI PUNCTUATION DOT", "Po", 0, none),
  ("KHAROSHTHI PUNCTUATION SMALL CIRCLE", "Po", 0, none),
  ("KHAROSHTHI PUNCTUATION CIRCLE", "Po", 0, none),
  ("KHAROSHTHI PUNCTUATION CRESCENT BAR", "Po", 0, none),
  ("KHAROSHTHI PUNCTUATION MANGALAM", "Po", 0, none),
  ("KHAROSHTHI PUNCTUATION LOTUS", "Po", 0, none),
  ("KHAROSHTHI PUNCTUATION DANDA", "Po", 0, none),
  ("KHAROSHTHI PUNCTUATION DOUBLE DANDA", "Po", 0, none),
  ("KHAROSHTHI PUNCTUATION LINES", "Po", 0, none),
)
