[package]
name = "auto-pinyin"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Gabriel Wu <@lucifer1004>"]
license = "MIT"
description = "Convert Chinese to pinyin with multiple styles and overrides."
repository = "https://github.com/lucifer1004/auto-pinyin"
keywords = ["pinyin", "chinese", "conversion", "linguistics"]
categories = ["text", "utility", "languages"]
compiler = "0.14.0"

exclude = [
    "wasm/",
    "rust-pinyin/",
    "Justfile",
    "example.typ",
    ".gitignore",
    ".gitmodules",
    ".jj/",
]
