[package]
name = "calepin"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["Vincent Arel-Bundock"]
license = "MIT"
description = "Write computational notebooks with executable code chunks."
repository = "https://github.com/vincentarelbundock/calepin"
homepage = "https://vincentarelbundock.github.io/calepin"
keywords = ["notebook", "literate-programming", "reproducible", "code-execution", "python", "r"]
categories = ["integration", "scripting"]
compiler = "0.13.0"
