# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "kych"
version = "0.1.0"
entrypoint = "src/kych.typ"
authors = ["CrossDark <https://kych.net> @crossdark"]
license = "MIT-0"
description = "个人静态网站的生成器,基于vsheg/tufted.由于本项目为个人网站设计,因此不提供英文说明"
homepage = "http://kych.net"
repository = "https://github.com/CrossDark/TyKYCH"
# keywords = []
# categories = []
# disciplines = []
# compiler = ""
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
