[package]
name = "astro"
version = "0.1.6"
repository = "https://github.com/AnvarAtayev/astro"
license = "MIT"
entrypoint = "src/bodies.typ"
authors = ["Anvar Atayev <https://github.com/AnvarAtayev>"]
description = "Draw celestial bodies in Typst"
categories = [ "visualization" ]
disciplines = [ "education", "physics" ]
keywords = ["astronomy", "planet", "solar system", "space", "cosmos"]