#import "@preview/elsearticle:1.0.0": *
// #import "../src/elsearticle.typ": *

#let bf(a) = $bold(upright(#a))$

#let abstract = [This paper presents an adaptive frequency-domain Kalman filter for the identification of dynamic loads acting on a mechanical structure. The primary motivation for this work is to demonstrate that a properly tuned standard Kalman filter is capable to accurately identifying dynamic loads in the frequency domain. The proposed method is based on the assumption that the system is linear and the dynamic loads are sparse and broadband. The originality of this work lies in the tuning of the process noise covariance matrix, which is adapted at each frequency step through different formulations. Other mechanisms, such as the estimation of the measurement noise covariance matrix and the initialization of the filter, are also implemented to make the filter converges to a consistent solution. Numerical and experimental validations are proposed to evaluate the performance of the adaptive filter compared to Bayesian regularization. The numerical validation consists of a simply-supported beam excited by a random excitation under different operating conditions, while the experimental validation is performed on a simply-supported plate excited by an impact hammer. The results show that the proposed methodology allows the accurate identification of spatially sparse broadband sources provided that the filter is properly tuned.]

#show: elsearticle.with(
  title: "An adaptive frequency-domain Kalman filter for source identification in structural dynamics",
  authors: (
    (
      name: "M. Aucejo",
      affiliation: "Laboratoire de Mécanique des Structures et des Systèmes Couplés, Conservatoire National des Arts et Métiers, F 75003 Paris, France",
      corr: "mathieu.aucejo@lecnam.net",
      id: "a",
    ),
    (
      name: "O. De Smet",
      affiliation: none,
      id: "a"
    ),
  ),
  journal: "Journal of Sound and Vibration",
  abstract: abstract,
  keywords: ("Linear inverse problem", "Force identification", "Space-frequency approach", "Kalman filter"),
  format: "review",
  // line-numbering: true,
)

= Introduction

Although the identification of dynamic loads acting on mechanical structures has been studied since at least the 1970s @Orm74 @Fla77, it remains an active area of research. The main reason is that source identification is a challenging inverse problem that is often ill-posed in the Hadamard sense @Had02. Moreover, determining the excitation sources to which a structure is subjected is of great interest in many fields of engineering. This knowledge can be applied in various contexts, such as structural health monitoring @Fri13, transfer path analysis @Jan99, structural design @Cor08, virtual sensing @Jan19, system identification @Rog22, or vibration control @Lei20.

From a general perspective, source identification methods can be categorized into four main groups. The first group comprizes regularization methods, which perform equally well in the time and frequency domains. Their objective is to constrain the solution space in order to ensure a unique and stable solution. Among these methods, the Truncated Singular Decomposition (TSVD) method is the most direct. It discards all the singular values of the system matrix below a certain threshold in order to reduce the condition number of the matrix to invert @Pot84 @Sun20. Another way to regularize the problem is to constrain the solution to follow a certain behavior. This idea is at the heart of additive and multiplicative regularization approaches @Li10. These methods consist of finding a solution that minimizes a functional that incorporates prior knowledge about the noise corrupting the data as well as the solution to identify. This information is conveyed through the data-fidelity and the regularization terms, respectively. While data-fidelity term is often chosen to be the $ell_2$-norm of the model residual to reflect that the data are corrupted by an additive Gaussian white noise @Auc16, the regularization term can take various forms. The choice of the regularization term depends on the specific problem and any prior knowledge about the sources. Selecting the regularization term as the squared $ell_2$-norm of the solution leads to Tikhonov regularization, which promotes the smoothness of the solution @Thi03 @Ren13. The regularization term can also be chosen as the $ell_q$-norm of the solution (with $q <= 1$) to promote sparsity of the solution @Qia17 @Auc17. Another popular choice is the mixed norm, or the $ell_(p,q)$-norm, which constrains the space-frequency or the space-time behavior of the solution @Rez16 @Auc19. A more general approach to regularization is provided by the Bayesian framework, which incorporates prior knowledge about the solution in a probabilistic manner. In this framework, most of the methods cited above can be interpreted as the maximum a posteriori (MAP) estimate of a dedicated Bayesian model @Li18 @Auc19b. More generally, the Bayesian paradigm allows to access to the posterior uncertainty of the solution, which is a valuable information in many applications @Zha12 @Fau17 @Auc18. \
The second group consists of methods that directly exploit the equation of motion of the structure. This group includes methods derived from the virtual work principle, such as the Virtual Field Method (VFM) @Ber14, the Selective source method @Tot18 or the Moving Least Squares (MLS) method @Xu15. This group also includes the Force Analysis Technique (FAT) @Pez95 and its derivative, the Corrected Force Analysis Technique (CFAT) @Lec12. The latter methods are based on a finite difference discretization of the equation of motion. In FAT, a wavenumber filter and a spatial filter are implemented to cope with measurement noise and discontinuies of the force distribution at boundaries, respectively. In CFAT, the noise sensitivity is addressed by implementing correction factors on the discretized operators that are derived from the wavenumber analysis of the systematic error induced by the finite difference discretization. All the previous methods have initially been designed for applications in the frequency domain. However, extensions to the time domain have been proposed for VFM @Odo17, FAT @Auj19 and CFAT @Pez20. \
The third group corresponds to methods that rely on the use of artificial intelligence (AI) techniques, and more specifically deep learning strategies, which have become popular in recent years. These methods can be divided into two categories: purely data-driven methods, which do not rely on any physical model, and hybrid/physics-informed methods, which combine knowledge coming from both physical models and data. Purely data-driven methods assume that the relationship between the measured data and the unknown sources can be learned from large amounts of training data. These methods often involve the use of neural networks, typically convolutional @Tab19 @Yan23 @Zho24 or recurrent @Zho19 @Yan21 @Esh22 @Imp24. Hybrid methods, on the other hand, leverage both physical models and data to learn the relationship between the measured data and the unknown sources. Various approaches have been proposed in the literature to incorporate physics into the learning process. These approach includes, but not exclusively, the use of a finite element model @Li24, the Duhamel's integral @Zho24b, algorithm unrolling @Zho25, and sensor configuration @Hua23. Since deep learning frameworks generally use real numbers @Lee22, most of the aforementioned methods operate in the time domain. A notable exception is the identification of load autopower spectra in the frequency domain proposed by Wang et al., since these quantities are purely real @Wan21. \
The fourth and final group consists of recursive filtering methods, that primarily operate in the time domain and make use of available information in a sequential manner to estimate the excitation sources. Although dynamic programming @Bus97 @Nor06 and adaptive filtering @Stu12 fall into this category, the most popular method is certainly the Bayesian filtering, and more specifically Kalman-like filtering. Depending on how the input estimation is performed, two types of methods deriving from this particular architecture may be distinguished for input-state estimation problems. The first category includes methods that estimate the input in conjunction with the system state, such as the Augmented Kalman Filter (AKF) @Lou12 and the Gaussian Process Latent Force Model (GPLFM) @Nay19, Zou23, while the second category gather the methods estimating the input and state vectors sequentially. In this category fall the Gillinjs and de Moore filter @Lou12b, the Dual Kalman Filter (DKF) @Eft15, the Sequential Bayesian Filter @Sed19 or the Sparse adaptive Bayesian Filter (SaBF) @Ghi22.

If we restrict ourselves to the frequency domain, regularization methods are the most commonly used. They are often preferred because they can be applied to a wide range of problems, without requiring strong assumptions about the mechanical system or the sources. In practice, the problem can be solved either at each frequency step independently, or jointly over a frequency band. When solved at each frequency, the reconstructed solution can be computed efficiently, but may be inaccurate near the resonance frequencies of the structure, since the response at these particular frequencies is primarily driven by its modes @Auc14. Conversely, when solved jointly over a frequency band, as in mixed-norm regularization, the solution is more accurate. However, this increases the computational complexity, which may limit its application to large-scale problems. To combine the best of both worlds, i.e. to obtain an accurate solution at a reasonable computational cost, one possible alternative is to approach the problem recursively, by adapting Kalman-like filtering in the frequency domain. Such an approach has been implemented with some success by the authors through a sequential Bayesian filter, that allows the state and the input of a linear mechanical system to be estimated @Auc25. The approach adopted in this paper is rather different, since the objective is to estimate the input only by using a standard Kalman filter. In other words, the aim is to maintain the algorithmic simplicity and the computational efficiency, without compromising the solution accuracy. With this in mind, the present paper aims to demonstrate that a standard Kalman filter, when properly tuned, can accurately identify broadband and spatially sparse dynamic loads in the frequency domain.

The proposed approach relies on two pillars to achieve this objective. The first one is the implementation of a complex-valued Kalman filter, which allows the filter to operate in the frequency domain. Although this type of filter has already been proposed in the literature, its application to source identification problems remains largely unexplored. The complex-valued Kalman filter is particularly well-suited to problems involving complex-valued data, such as those encountered in power systems @Das99 @Per24, in audio signal processing @Enz06, acoustic system identification @Kab22, and more generally in signal processing @Fan19 @Wan19. The second pillar involves defining a suitable initialization strategy and properly tuning the process and measurement noise covariance matrices. The latter point is an old but still ongoing problem in Kalman filtering @Meh70 @Dun17 @Zha20, because it significantly affects the ability of the filter to converge to a consistent solution. While the measurement noise covariance matrix will be estimated from the vibration data using an original Bayesian optimization, the process noise covariance matrix is more challenging to estimate a priori, since it is related to the state equation modeling the evolution of the system state. In this work, it is proposed to adapt the process noise covariance matrix at each frequency step using different formulations, namely the Maximum Likelihood Estimation (MLE), the Maximum A Posteriori Estimation (MAPE), and the Relaxation Scheme (RS). This choice allows to compare the influence and the performance of each adaption mechanism. Finally, the filter is initialized by estimating the initial state and covariance matrix, which is performed through a Bayesian regularization.

To introduce each building block of the proposed method in a pedagogical manner, the paper is organized into four sections. Section~@s:kalman presents the theoretical foundations of the frequency-domain Kalman filter, which is based on a complex-valued state-space representation of the system. Section 3 details the tuning of the filter, which relies on the computation of an adapted initial solution and the description of the procedures used to calibrate the measurement and process noise covariance matrices. Sections 4 and 5 evaluate the ability of the proposed method to reconstruct physically consistent excitation sources both numerically and experimentally. The numerical validation consists of a simply-supported beam excited by a random excitation under different operating conditions, while the experimental validation is performed on a simply-supported plate excited by an impact hammer. Comparisons with the results obtained by Bayesian regularization are provided to put the performance of the proposed method into perspective.

= Adaptive Frequency-domain Kalman filter <s:kalman>

This section describes the theoretical foundations of the adaptive frequency-domain Kalman filter proposed in this paper. First, it introduces the state-space representation of the system, which forms the basis for the adaptive Kalman filter described in the second part.

== State-space representation of the system in the frequency domain

Kalman filtering relies on the definition of an appropriate state-space representation of the system, which is a mathematical model describing how the state evolves between two frequency steps and how it is related to the measurements performed on the mechanical system. Since this study focuses solely on estimating dynamic loads acting on a mechanical structure, the state of the system is the vector of the excitation sources to be identified at a given frequency $f_k$ and noted $bf(u)_k$, while the measurements are the vibration data recorded at the same frequency and noted $bf(y)_k$.

Given this choice of state and output variables, the state equation is supposed to be a random walk model. This model assumes that $bf(u)_(k+1)$, the state at a given frequency $f_(k+1)$, is equal to $bf(u)_k$, the state at the previous frequency $f_k$, plus a random noise term $bf(w)_k$, which is assumed to be Gaussian with zero mean and covariance matrix $bf(Q)_k$, that is:
$
  bf(u)_(k+1) = bf(u)_k + bf(w)_k.
$
The output equation relates the state to the measurements. In the frequency domain, it is common to assume that the noiseless measurements $bf(y)_k$ are related to the state $bf(u)_k$ through the transfer functions matrix $bf(H)_k$, which completely describes the dynamic behavior of the system at the frequency $f_k$. If we further assume that the data are corrupted by an additive Gaussian noise $bf(v)_k$ with zero mean and covariance matrix $bf(R)_k$, the output equation is finally given by:
$
  bf(y)_k = bf(H)_k bf(u)_k + bf(v)_k.
$

Combining the previous state and output equations, the system dynamics can be summarized by the following state-space model:
$
  cases(
    bf(u)_(k+1) = bf(u)_k + bf(w)_k,
    bf(y)_k = bf(H)_k bf(u)_k + bf(v)_k,
  ).
$

#bibliography("latex/bibliography.bib")