[package]
name = "cetz-feynman-lite"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Zhou Rui <@ZhouRui-xzit>"]
license = "MIT"
description = "Draw customizable Feynman diagrams with CeTZ."
repository = "https://github.com/ZhouRui-xzit/Cetz-Feynman-Lite"
compiler = "0.15.0"
keywords = ["feynman diagrams", "physics", "cetz"]
exclude = ["/output/**", "/phi4-demo/**", "/tikz-feynman/**", "/tests/**", "/scripts/**", "/docs/**", "/examples/**", "/.git/**", "/.vscode/**", "/CONTRIBUTING.md"]
