#let title-english = "Towards Smart Inventions and their Novelty"
#let title-german = "Über schlaue Erfindungen und deren Neuartigkeit"
#let author = "Findus"
#let degree = "Master"
#let submission-date = datetime.today() // or use: datetime(day: 1, month: 1, year: 2025)
#let institute = "Institut für schlaue Erfindungen"
#let program = "Tüfteln und Basteln"
#let company = "Pettersson's Patentideen"
#let university = "Universität Småland"
#let supervisor = "Pettersson"
#let advisor = "Gustravsson"
#let place = "Lübeck"
#let top-left-img = image("../images/top-left.png")
#let top-right-img = image("../images/top-right.png")
#let slogan-img = image("../images/slogan.png")
#let is-print = false
#let body-font = "New Computer Modern"
#let sans-font = "New Computer Modern Sans"