[package]
name = "timble"
version = "1.0.0"
entrypoint = "timble.typ"
authors = ["@Mambouna"]
license = "MPL-2.0"
description = "Draw and style precise time tables with ease."
repository = "https://github.com/Mambouna/timble"
keywords = ["timetable", "timing", "time", "table", "chart", "charts", "diagram", "diagrams"]
categories = ["visualization", "utility"]
exclude = ["example"]
