[package]
name = "toot"
version = "0.1.0"
entrypoint = "toot.typ"
authors = ["Andreas Kröpelin"]
license = "MIT"
description = "Typst Opinionated Online Tutorials."
repository = "https://codeberg.org/a5s/toot"
keywords = ["html", "online", "tutorial", "documentation", "docs"]
categories = ["utility"]
compiler = "0.14.0"
exclude = ["logo"]

[template]
path = "template"
entrypoint = "src/index.typ"
thumbnail = "thumbnail.png"
