[package]
name = "sanor"
version = "0.2.1"
entrypoint = "src/lib.typ"
authors = ["pacaunt <@pacaunt>"]
license = "MIT"
compiler = "0.13.1"
repository = "https://github.com/pacaunt/sanor"
description = "Fast, small, presentation animation utility"
categories = ["utility", "presentation"]
exclude = ["/gallery/*"]