# 著者・年が同じ文献がある場合に番号を付与するため，その番号を付与する位置を指定する特殊文字列
year-doubling = "%year-doubling"

# アルファベット順にソートを行うか
bib-sort = true

# 引用されている順番にソートを行うか
bib-sort-ref = true

# 引用されている文献だけでなく全ての文献を表示するか
bib-full = true

# citeのスタイル設定
bib-cite-author = "author-set-cite"
bib-cite-year = "all-return"

# vancouverスタイル設定
bib-vancouver = "[1]"
vancouver-style = true

# 重複著者・年号文献の year-doubling に表示する文字列
bib-year-doubling = "a"

# 文献リストのタイトルを文頭大文字にするか
sentence-case-titles = true

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# bib-vancouver = "manual"のときの設定
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
bib-vancouver-manual = "bib-vancouver-manual-default"

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 各引用の表示形式設定
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

[cite]
    bib-cite = ["[", "bib-citen-default", ", ", "]"]
    bib-citet = ["", "bib-citet-default", "; ", ""]
    bib-citep = ["(", "bib-citep-default", "; ", ")"]
    bib-citen = ["[", "bib-citen-default", ", ", "]"]
    bib-citefull = ["", "bib-citefull-default", "; ", ""]

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 各要素の表示形式設定
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[entry.article]
    [entry.article.en]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        journal = ["", "", "all-emph", "", ", ", [], "."]
        volume = ["", "Vol. ", "all-return", "", ", ", [], "."]
        number = ["", "No. ", "all-return", "", ", ", [], ")."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.article.ja]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        journal = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "Vol. ", "all-return", "", ", ", [], "."]
        number = ["", "No. ", "all-return", "", ", ", [], ")."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.book]
    [entry.book.en]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-emph", "", ", ", [], "."]
        volume = ["", "Vol. ", "all-return", "", ". ", [], "."]
        series = [" of ", "", "all-emph", "", ". ", ["volume"], "."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", " edition", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.book.ja]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ", ", [], "."]
        series = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "第", "all-return", "巻", ". ", [], "巻."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "第", "all-return", "版", ", ", [], "版."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.booklet]
    [entry.booklet.en]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        howpublished = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.booklet.ja]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        howpublished = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.inbook]
    [entry.inbook.en]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-emph", "", ", ", [], "."]
        volume = ["", "Vol. ", "all-return", "", ", ", [], "."]
        series = [" of ", "", "all-emph", "", ", ", ["volume"], "."]
        chapter = ["", "chapter ", "all-return", "", ", ", [], "."]
        pages = ["", "", "page-set", "", ". ", [], "."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", " edition", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.inbook.ja]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ", ", [], "."]
        series = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "第", "all-return", "巻", ", ", [], "巻."]
        chapter = ["", "第", "all-return", "章", ", ", [], "章."]
        pages = ["", "", "page-set", "", ". ", [], "."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.incollection]
    [entry.incollection.en]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        editor = ["", "In ", "author-set3", ", editor", ", ", [], ", editor."]
        booktitle = ["", "", "all-emph", "", ", ", [], "."]
        volume = ["", "Vol. ", "all-return", "", ", ", [], "."]
        series = [" of ", "", "all-emph", "", ", ", ["volume"], "."]
        chapter = ["", "chapter ", "all-return", "", ", ", [], "."]
        pages = ["", "", "page-set", "", ". ", [], "."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", " edition", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.incollection.ja]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        editor = ["", "", "author-set3", "（編）", ", ", [], ", （編）."]
        booktitle = ["", "", "all-return", "", ", ", [], "."]
        series = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "第", "all-return", "巻", ", ", [], "巻."]
        chapter = ["", "第", "all-return", "章", ", ", [], "章."]
        pages = ["", "", "page-set", "", ". ", [], "."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.inproceedings]
    [entry.inproceedings.en]
        author = ["", "", "author-set3", "", ", ", [], "."]
        title = ["", "", "all-return", "", ", ", [], "."]
        editor = ["", "In ", "author-set3", ", editor", ", ", [], ", editor."]
        booktitle = ["", "", "all-emph", "", ", ", [], "."]
        volume = ["", "Vol. ", "all-return", "", ", ", [], "."]
        series = [" of ", "", "all-emph", "", ", ", ["volume"], "."]
        pages = ["", "", "page-set", "", ". ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        organization = ["", "", "all-return", "", ", ", [], "."]
        publisher = ["", "", "all-return", "", ". ", [], "."]
        note = ["", "", "all-return", "", ". ", [], "."]
    [entry.inproceedings.ja]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        editor = ["", "", "author-set3", "（編）", ", ", [], ", editor."]
        booktitle = ["", "", "all-return", "", ", ", [], "."]
        series = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "第", "all-return", "巻", ", ", [], "巻."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        organization = ["", "", "all-return", "", ", ", [], "."]
        publisher = ["", "", "all-return", "", ". ", [], "."]
        note = ["", "", "all-return", "", ". ", [], "."]

[entry.conference]
    [entry.conference.en]
        author = ["", "", "author-set3", "", ", ", [], "."]
        title = ["", "", "all-return", "", ", ", [], "."]
        editor = ["", "In ", "author-set3", ", editor", ", ", [], ", editor."]
        booktitle = ["", "", "all-emph", "", ", ", [], "."]
        volume = ["", "Vol. ", "all-return", "", ", ", [], "."]
        series = [" of ", "", "all-emph", "", ", ", ["volume"], "."]
        pages = ["", "", "page-set", "", ". ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        organization = ["", "", "all-return", "", ", ", [], "."]
        publisher = ["", "", "all-return", "", ". ", [], "."]
        note = ["", "", "all-return", "", ". ", [], "."]
    [entry.conference.ja]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        editor = ["", "", "author-set3", "（編）", ", ", [], ", editor."]
        booktitle = ["", "", "all-return", "", ", ", [], "."]
        series = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "第", "all-return", "巻", ", ", [], "巻."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        organization = ["", "", "all-return", "", ", ", [], "."]
        publisher = ["", "", "all-return", "", ". ", [], "."]
        note = ["", "", "all-return", "", ". ", [], "."]

[entry.manual]
    [entry.manual.en]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-emph", "", ". ", [], "."]
        organization = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", " edition", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.manual.ja]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        organization = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.mastersthesis]
    [entry.mastersthesis.en]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        school = ["", "Master's thesis, ", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ". ", [], "."]
    [entry.mastersthesis.ja]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        school = ["", "修士論文, ", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ". ", [], "."]

[entry.misc]
    [entry.misc.en]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        howpublished = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.misc.ja]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        howpublished = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.online]
    [entry.online.en]
        author = ["", "", "author-set3", "", ", ", [], "."]
        title = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.online.ja]
        author = ["", "", "author-set3", "", ", ", [], "."]
        title = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.phdthesis]
    [entry.phdthesis.en]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-emph", "", ". ", [], "."]
        school = ["", "Phd thesis, ", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.phdthesis.ja]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        school = ["", "博士論文, ", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.proceedings]
    [entry.proceedings.en]
        editor = ["", "", "author-set3", ", editor", ". ", [], ", editor."]
        title = ["", "", "all-emph", "", ", ", [], "."]
        volume = ["", "Vol. ", "all-return", "", ", ", [], "."]
        series = [" of ", "", "all-emph", "", ", ", ["volume"], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        publisher = ["", "", "all-return", "", ". ", [], "."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.proceedings.ja]
        editor = ["", "", "author-set3", "（編）", ". ", [], "（編）."]
        title = ["", "", "all-return", "", ", ", [], "."]
        series = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "第", "all-return", "巻", ", ", [], "巻."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        publisher = ["", "", "all-return", "", ". ", [], "."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.techreport]
    [entry.techreport.en]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        type = ["", "", "all-return", "", ", ", [], "."]
        number = [" ", "", "all-return", "", ", ", ["type"], "."]
        institution = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.techreport.ja]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        type = ["", "", "all-return", "", ", ", [], "."]
        number = [" ", "", "all-return", "", ", ", ["type"], "."]
        institution = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.unpublished]
    [entry.unpublished.en]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        note = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
    [entry.unpublished.ja]
        author = ["", "", "author-set3", "", ". ", [], "."]
        title = ["", "", "all-return", "", ". ", [], "."]
        note = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ". ", [], "."]
        year = [" ", "", "all-return", "%year-doubling", ". ", ["month"], "%year-doubling."]
