# tieice: standard pBibTeX Japanese bibliography style.
# This file is self-contained; edit it directly to customize the style.

# 著者・年が同じ文献がある場合に番号を付与するため，その番号を付与する位置を指定する特殊文字列
year-doubling = "%year-doubling"

# アルファベット順にソートを行うか
bib-sort = false

# 引用されている順番にソートを行うか
bib-sort-ref = true

# 引用されている文献だけでなく全ての文献を表示するか
bib-full = false

# citeのスタイル設定
bib-cite-author = "author-set-cite"
bib-cite-year = "all-return"

# vancouverスタイル設定
bib-vancouver = "[1]"
vancouver-style = true

# 重複著者・年号文献の year-doubling に表示する文字列
bib-year-doubling = "a"

# 文献リストのタイトルを文頭大文字にするか
sentence-case-titles = true

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# bib-vancouver = "manual"のときの設定
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
bib-vancouver-manual = "bib-vancouver-manual-default"

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 各引用の表示形式設定
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

[cite]
    bib-cite = ["[", "bib-citen-default", ", ", "]"]
    bib-citet = ["", "bib-citet-default", "; ", ""]
    bib-citep = ["(", "bib-citep-default", "; ", ")"]
    bib-citen = ["[", "bib-citen-default", ", ", "]"]
    bib-citefull = ["", "bib-citefull-default", "; ", ""]

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# 各要素の表示形式設定
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[entry.article]
    [entry.article.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        journal = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "", "all-bold", "", ", ", [], "."]
        number = ["", "", "all-return", "", ", ", [], "."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "journal", "volume", "number", "pages"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.article.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        journal = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "", "all-bold", "", ", ", [], "."]
        number = ["", "", "all-return", "", ", ", [], "."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "journal", "volume", "number", "pages"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.book]
    [entry.book.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        volume = ["", "Vol. ", "all-return", "", ", ", [], "."]
        series = [" of ", "", "all-return", "", ", ", ["volume"], "."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", " edition", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "volume", "series", "publisher", "address", "edition"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.book.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        series = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "第", "all-return", "巻", ", ", [], "巻."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "第", "all-return", "版", ", ", [], "版."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "volume", "series", "publisher", "address", "edition"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.booklet]
    [entry.booklet.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        howpublished = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "howpublished", "address"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.booklet.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        howpublished = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "howpublished", "address"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.inbook]
    [entry.inbook.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        volume = ["", "Vol. ", "all-return", "", ", ", [], "."]
        series = [" of ", "", "all-return", "", ", ", ["volume"], "."]
        chapter = ["", "chapter ", "all-return", "", ", ", [], "."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", " edition", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "volume", "series", "chapter", "publisher", "address", "edition", "page"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.inbook.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        series = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "第", "all-return", "巻", ", ", [], "巻."]
        chapter = ["", "第", "all-return", "章", ", ", [], "章."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "volume", "series", "chapter", "publisher", "address", "edition", "page"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.incollection]
    [entry.incollection.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        editor = ["", "In ", "author-set4", ", editor", ", ", [], ", editor."]
        booktitle = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "Vol. ", "all-return", "", ", ", [], "."]
        series = [" of ", "", "all-return", "", ", ", ["volume"], "."]
        chapter = ["", "chapter ", "all-return", "", ", ", [], "."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", " edition", ", ", [], "."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "editor", "booktitle", "volume", "series", "chapter", "publisher", "address", "edition", "pages"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.incollection.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        editor = ["", "", "author-set4", "（編）", ", ", [], ", （編）."]
        booktitle = ["", "", "all-return", "", ", ", [], "."]
        series = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "第", "all-return", "巻", ", ", [], "巻."]
        chapter = ["", "第", "all-return", "章", ", ", [], "章."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", "", ", ", [], "."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "editor", "booktitle", "volume", "series", "chapter", "publisher", "address", "edition", "pages"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.inproceedings]
    [entry.inproceedings.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        editor = ["", "In ", "author-set4", ", editor", ", ", [], ", editor."]
        booktitle = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "Vol. ", "all-return", "", ", ", [], "."]
        series = [" of ", "", "all-return", "", ", ", ["volume"], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "editor", "booktitle", "volume", "series", "address", "pages"], "%year-doubling)."]
        organization = ["", "", "all-return", "", ", ", [], "."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.inproceedings.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        editor = ["", "", "author-set4", "（編）", ", ", [], ", editor."]
        booktitle = ["", "", "all-return", "", ", ", [], "."]
        series = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "第", "all-return", "巻", ", ", [], "巻."]
        address = ["", "", "all-return", "", ", ", [], "."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "editor", "booktitle", "volume", "series", "address", "pages"], "%year-doubling)."]
        organization = ["", "", "all-return", "", ", ", [], "."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.conference]
    [entry.conference.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        editor = ["", "In ", "author-set4", ", editor", ", ", [], ", editor."]
        booktitle = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "Vol. ", "all-return", "", ", ", [], "."]
        series = [" of ", "", "all-return", "", ", ", ["volume"], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "editor", "booktitle", "volume", "series", "address", "pages"], "%year-doubling)."]
        organization = ["", "", "all-return", "", ", ", [], "."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.conference.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        editor = ["", "", "author-set4", "（編）", ", ", [], ", editor."]
        booktitle = ["", "", "all-return", "", ", ", [], "."]
        series = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "第", "all-return", "巻", ", ", [], "巻."]
        address = ["", "", "all-return", "", ", ", [], "."]
        pages = ["", "", "page-set", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "editor", "booktitle", "volume", "series", "address", "pages"], "%year-doubling)."]
        organization = ["", "", "all-return", "", ", ", [], "."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.manual]
    [entry.manual.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        organization = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", " edition", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "organization", "address", "edition"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.manual.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        organization = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        edition = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "organization", "address", "edition"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.mastersthesis]
    [entry.mastersthesis.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        school = ["", "Master's thesis, ", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "school", "address"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.mastersthesis.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        school = ["", "修士論文, ", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "school", "address"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.misc]
    [entry.misc.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        howpublished = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "howpublished"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.misc.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        howpublished = ["", "", "all-return", "", ", ", [], "."]
        month = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "howpublished"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.online]
    [entry.online.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.online.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.phdthesis]
    [entry.phdthesis.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        school = ["", "PhD thesis, ", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "school", "address"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.phdthesis.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        school = ["", "博士論文, ", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "school", "address"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.proceedings]
    [entry.proceedings.en]
        editor = ["", "", "author-set4", ", ed.", ", ", [], ", editor."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        volume = ["", "Vol. ", "all-return", "", ", ", [], "."]
        series = [" of ", "", "all-return", "", ", ", ["volume"], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "volume", "series", "address"], "%year-doubling)."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.proceedings.ja]
        editor = ["", "", "author-set4", "（編）", ", ", [], "（編）."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        series = ["", "", "all-return", "", ", ", [], "."]
        volume = ["", "第", "all-return", "巻", ", ", [], "巻."]
        address = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "volume", "series", "address"], "%year-doubling)."]
        publisher = ["", "", "all-return", "", ", ", [], "."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.techreport]
    [entry.techreport.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "", "all-return", ", Technical Report", ", ", [], "."]
        type = ["", "", "all-return", "", ", ", [], "."]
        number = [" ", "", "all-return", "", ", ", ["type"], "."]
        institution = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "type", "number", "institution", "address"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]
    [entry.techreport.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "", "all-return", ", 技術報告", ", ", [], "."]
        type = ["", "", "all-return", "", ", ", [], "."]
        number = [" ", "", "all-return", "", ", ", ["type"], "."]
        institution = ["", "", "all-return", "", ", ", [], "."]
        address = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "type", "number", "institution", "address"], "%year-doubling)."]
        note = ["", "", "all-return", "", ", ", [], "."]

[entry.unpublished]
    [entry.unpublished.en]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        note = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "note"], "%year-doubling)."]
    [entry.unpublished.ja]
        author = ["", "", "author-set4", "", ": ", [], "."]
        title = ["", "\"", "all-return", "\"", ", ", [], "\"."]
        note = ["", "", "all-return", "", ", ", [], "."]
        year = [" ", "(", "all-return", "%year-doubling)", ", ", ["title", "note"], "%year-doubling)."]
