/// Generate URL strings to contents on different media platforms. These links usually have similar patterns that only differs in terms of content ID, and the functions are here to avoid repetitions and simplifying the writing of these links.
///
/// Note that the generated URLs are of type `string`, not `content`. To make the link clickable you can wrap it with a `link` element, or for more nicely-formatted display text, use functions from `linkify.display` instead.
///
/// Due to privacy reasons, platforms like Xhaohongshu are currently not supported.
/// Please beware the share links generated by these apps contain the sharer's personal info and is thus unsafe. Be cautious not to include them in publicized documents.
/// If I discover how to generate a sanitized link in the future, I might consider support those platforms.
///
///
/// 此子模块用于生成各大互联网内容平台的内容链接，由于这些链接通常有着固定的格式，只是某些参数不同，通过本模块提供的函数，可以简化这些链接的生成，减少代码重复。
///
/// 本模块生成的 URL 链接均为字符串 `str` 格式，不是富文本 `content` 格式，若直接插入文档中是不可点击的。若要生成可点击的链接，可使用一个 `link` 元素包裹 URL 字符串。你也可以考虑使用 `linkify.display` 子模块中的函数为这些链接直接生成格式化的显示文本。
///
/// 包括小红书在内的某些平台，其生成的分享链接会包含用户的个人信息，有隐私泄露的风险，故目前尚不提供这些平台内容的链接生成。同时也请注意避免在公开发布的文档中使用这些可能泄露个人信息的分享链接。若未来发现有办法对这些分享链接中的个人信息进行脱敏处理，我可以考虑加入相关的函数。

#import "_impl/url.typ": (
  bili,
  weixin,
  zhihu,
  youtube,
  wiki,
  moegirl,
  twitter,
  isbn,
)

#let B站 = bili
#let 微信 = weixin
#let 知乎 = zhihu
#let 油管 = youtube
#let 维基 = wiki
#let 萌百 = moegirl
#let 推特 = twitter
#let X = twitter