[package]
name = "inelegant-note"         # 项目名，需要使用
version = "0.9.0"        # 项目版本，一般来说是 0.1.0
entrypoint = "lib.typ"   # 项目入口文件
authors = ["Type <@typetypewriter>"] # 开发人员，可以写成 ["Your Name <@your-github-name>"]
license = "MIT"          # 许可证书
description = "A Typst template which has the feature of Elegant Book and others."      # 项目描述
repository = "https://github.com/typetypewriter/inelegant-note"       # Github 仓库目录
categories = ["book"]  # 可选，项目类型

[template]               # 如果你有模板文件，可以配置该项，否则注释
path = "template"        # 模板目录
entrypoint = "main.typ"  # 模板入口
thumbnail = "thumbnail.png"


