[package]
name = "clean-esi"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Chamel Nadir Bouacha <https://github.com/Chamiln17>"]
license = "MIT-0"
description = "Final-year project (PFE) thesis for ESI Algiers, following the school's formatting standards."
repository = "https://github.com/Chamiln17/clean-esi"
keywords = ["esi", "esi algiers", "École nationale Supérieure d'Informatique", "pfe", "thesis", "final year project"]
categories = ["thesis"]
disciplines = ["computer-science"]
compiler = "0.14.0"
exclude = ["assets/*"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
