// datify-core data backend.
//
// Data lives in per-locale TOML files under translations/locales/<lang>.toml,
// generated by tools/generate-cldr.mjs. Only genuinely-localized values are
// stored (a value is omitted when it equals the CLDR root); missing values are
// resolved here at read time via the fallback chain.
//
// Lazy loading: only the small index is read at import time. Each accessor
// reads exactly the one locale file it needs (toml() is memoized, so repeated
// reads within a compile are free). Importing this module loads zero locale
// data until an accessor is actually called.
//
// Typst has no try/catch: calling toml() on a missing file aborts the whole
// compile. So we never build a path we have not first confirmed against the
// index. _resolve-lang only ever returns a code that is in _index.locales (or
// the default locale, which is also in the index).

#let _index = toml("translations/index.toml")
#let _locales = _index.locales

// Terminal fallback locale. Always present in the index and written in full by
// the generator, so it is a complete safety net for every lookup. Change here
// to retarget the default.
#let _default-lang = "en"

#let _load = (lang) => toml("translations/locales/" + lang + ".toml")

// Opt-in community overlay: hand-maintained data that overrides CLDR for
// specific locales (regional conventions / styling). It is never written by the
// generator, so it survives the monthly regeneration. The index is small and
// eager; overlay files are partial (only the cells they override).
#let _community-index = toml("translations/community/index.toml")
#let _community-locales = _community-index.locales
#let _load-community = (lang) => toml("translations/community/locales/" + lang + ".toml")

// CLDR truncation rule: try the exact code, then drop the trailing subtag and
// retry. Returns the first code present in `locales`, or none.
//   "az-Arab-IQ" -> "az-Arab" -> "az" -> ...
#let _resolve-in = (locales, lang) => {
  let parts = lang.split("-")
  while parts.len() > 0 {
    let code = parts.join("-")
    if locales.contains(code) {
      return code
    }
    parts = parts.slice(0, parts.len() - 1)
  }
  return none
}

// Resolve against the CLDR index, falling back to the default locale.
#let _resolve-lang = (lang) => {
  let code = _resolve-in(_locales, lang)
  if code != none { return code }
  return _default-lang
}

// Read data.<category>.<usage>.<width>.<key>, tolerating absent sections
// (under the omit rule a locale file may not contain a given section at all).
#let _lookup = (data, category, usage, width, key) => {
  data
    .at(category, default: (:))
    .at(usage, default: (:))
    .at(width, default: (:))
    .at(key, default: none)
}

// Resolve a day/month cell. When `community` is enabled, the overlay is tried
// first (truncation within the community index); any cell it doesn't define
// falls through to CLDR (the resolved locale, then the default locale).
#let _resolve-cell = (lang, category, usage, width, key, community: false) => {
  if community {
    let cc = _resolve-in(_community-locales, lang)
    if cc != none {
      let cv = _lookup(_load-community(cc), category, usage, width, key)
      if cv != none { return cv }
    }
  }
  let resolved = _resolve-lang(lang)
  let value = _lookup(_load(resolved), category, usage, width, key)
  if value == none and resolved != _default-lang {
    value = _lookup(_load(_default-lang), category, usage, width, key)
  }
  return value
}

#let get-day-name = (
  weekday,
  lang: "en",
  usage: "stand-alone",
  width: "wide",
  community: false,
) => {
  let weekday_type = type(weekday)

  // Only accept int or str
  if not (weekday_type == int or weekday_type == str) {
    panic("Invalid weekday type: must be an integer or a string, got " + str(type(weekday)))
  } else {
    if weekday_type == int {
      if not (weekday >= 1 and weekday <= 7) {
        panic("Invalid weekday: " + str(weekday) + " (must be 1–7)")
      }
    } else {
      if not (weekday >= "1" and weekday <= "7") {
        panic("Invalid weekday: " + weekday + " (must be \"1\"–\"7\")")
      }
    }
  }

  let weekday_str = str(weekday)

  if not (usage == "format" or usage == "stand-alone") {
    panic("Invalid day usage: " + usage + " (must be 'format' or 'stand-alone')")
  }
  if not (width == "wide" or width == "abbreviated" or width == "narrow") {
    panic("Invalid day width: " + width + " (must be 'wide', 'abbreviated', 'narrow')")
  }

  let value = _resolve-cell(lang, "days", usage, width, weekday_str, community: community)
  if value == none {
    panic(
      "No day name for weekday " + weekday_str +
      " in language " + lang +
      ", usage " + usage +
      ", width " + width
    )
  }
  return value
}

#let get-month-name = (
  month,
  lang: "en",
  usage: "stand-alone", // "format" or "stand-alone"
  width: "wide", // "wide", "abbreviated", "narrow"
  community: false,
) => {
  let month_type = type(month)

  // Only accept int or str
  if not (month_type == int or month_type == str) {
    panic("Invalid month type: must be an integer or a string, got " + str(type(month)))
  } else {
    if month_type == int {
      if not (month >= 1 and month <= 12) {
        panic("Invalid month: " + str(month) + " (must be 1–12)")
      }
    } else {
      if not (month >= "1" and month <= "12") {
        panic("Invalid month: " + month + " (must be \"1\"–\"12\")")
      }
    }
  }

  let month_str = str(month)

  if not (usage == "format" or usage == "stand-alone") {
    panic("Invalid month usage: " + usage + " (must be 'format' or 'stand-alone')")
  }
  if not (width == "wide" or width == "abbreviated" or width == "narrow") {
    panic("Invalid month width: " + width + " (must be 'wide', 'abbreviated', 'narrow')")
  }

  let value = _resolve-cell(lang, "months", usage, width, month_str, community: community)
  if value == none {
    panic(
      "No month name for month " + month_str +
      " in language " + lang +
      ", usage " + usage +
      ", width " + width
    )
  }
  return value
}

#let _pattern-keys = ("full", "long", "medium", "short")

#let get-date-pattern = (
  pattern-type,
  lang: "en",
  community: false,
) => {
  if not (type(pattern-type) == str) {
    panic("Invalid pattern type: must be a string and a known pattern key, got " + str(type(pattern-type)))
  }
  if not _pattern-keys.contains(pattern-type) {
    panic("Unknown pattern type: " + pattern-type + " (must be one of " + _pattern-keys.join(", ") + ")")
  }

  if community {
    let cc = _resolve-in(_community-locales, lang)
    if cc != none {
      let cv = _load-community(cc).at("patterns", default: (:)).at(pattern-type, default: none)
      if cv != none { return cv }
    }
  }

  let resolved = _resolve-lang(lang)
  let value = _load(resolved).at("patterns", default: (:)).at(pattern-type, default: none)
  if value == none and resolved != _default-lang {
    value = _load(_default-lang).at("patterns", default: (:)).at(pattern-type, default: none)
  }
  if value == none {
    panic(
      "No date pattern '" + pattern-type + "' in language " + lang
    )
  }
  return value
}
