[package]
name = "ficons"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Balder W. Holst"]
license = "MIT"
description = "Open source vector icons."
repository = "https://github.com/BalderHolst/typst-feather-icons"
keywords = ["icons", "vector", "feather"]
categories = ["visualization"]
disciplines = ["design"]
exclude = ["example.svg", "docs.pdf"]

[tool.install]
namespace = "local"
