[package]
name = "unofficial-whu-lab-report"
version = "0.1.1"
entrypoint = "lib.typ"
authors = ["Shouzhuo Yi <@whoisKIWIIZZZ>", "Mingyu Zhang <@zoomy14112>"]
license = "MIT"
description = "An unofficial course lab report template for Wuhan University (WHU). 武汉大学计算机学院本科生课程设计报告模板(非官方)"
repository = "https://github.com/zoomy14112/report-theme-whu"
keywords = ["report", "whu", "course", "chinese"]
categories = ["report", "thesis"]
compiler = "0.14.0"
exclude = ["template/example.png", "template/signature.png"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
