// Endfield Document Template
// Generated by: typst init @preview/endfield-doc:0.1.2
//
// Delete or replace any fields you don't need.
#import "@preview/endfield-doc:0.1.2": endfield-doc

#show: endfield-doc.with(
  title: [Arknights: Endfield Typst Template],
  subtitle: [Template Testing and Debugging],
  author: [
    // The cover is its own page context; resetting the footnote counter keeps
    // the affiliation marks starting at 1 rather than continuing a prior count.
    metasequoiaNI#counter(footnote).update(0)#footnote[Rinkosoft CO., LTD.]<rinkosoft>,
    Yvonne#footnote[Endfield Industries, OMV Dijiang, Talos II Synchorous Orbit]<endfield>#footnote[United Workers' Syndicates of Talos II (Valley IV Base), Valley IV, Talos II]<uwst>,
    Zhuang Fangyi#footnote[Hongshan Academy of Sciences, Wuling ASTD, Talos II]<wuling>],
  date: datetime.today().display("[year]-[month]-[day]"),
  institution: [
    Rinkosoft
  ],
  lang: "en",
  region: "cn",
  equation-numbering: "(1)",
  heading-pagebreak: true,
  page-numbering: "1",
)

= General Text Testing

== Latin Text

The *Ætherside* represents a comprehensive dimensional state at Depth 1, overlapping with realspace (Depth 0) across subterranean, atmospheric, and orbital regions. @depth-equation shows the correlation between proximity to rift boundaries and local Depth readings.

$ D(x) = tanh(lambda x) $ <depth-equation>

Where $D$ represents the Depth field taking values in $[-1, 1]$, with $D = 0$ being realspace (normal conditions), $D = -1$ the Originium Internalization Universe, and $D = 1$ the Ætherside. The parameter $x$ denotes proximity to rift boundaries. Active Blight manifests most intensely when depth readings approach $0.5$, corresponding to the Ætherside-Realspace overlap zone where the Higgs-like scalar field undergoes significant deviation from the vacuum expectation value.

== CJK Test

=== Simplified Chinese

所以325是什么意思？🤔难道是指明日方舟up主魔法ZC目录2024年3月11日的直播，彼时由龙哥哥今天又鸽了主办的明日方舟集成战略民间赛事仙术杯第五届正在如火如荼地展开中，本届仙术杯采取团队赛的形式，ZC 代表冠军厨小队的第二位出战，使用科学分队焰影苇草开但由于临场过于紧张运气Maybe和肉鸽基础不够扎实等原因在第三层关底利刃所指暴毙，局内结算325分啊，我还以为是出自明日方舟up主魔法ZC目录2024年3月11日的直播，彼时由龙哥哥今天又鸽了主办的明日方舟集成战略民间赛事仙术杯第五届正在如火如荼地展开中，本届仙术杯采取团队赛的形式，ZC 代表冠军厨小队的第二位出战，使用科学分队焰影苇草开但由于临场过于紧张运气Maybe和肉鸽基础不够扎实等原因在第三层关底利刃所指暴毙，局内结算325分吗？

=== Japanese

それで、325ってどういう意味なの🤔？まさか「明日方舟」のアップ主・魔法ZC目录（マホウZCムロク）が2024年3月11日に配信した、龍哥哥今天又鸽了（ロン兄貴が今日もサボった）主催の「明日方舟」統合戦略民間大会・仙術杯第五届がまさに熱戦を繰り広げている最中の出来事？今大会はチーム戦形式で、ZCは優勝厨チームの第二代表として出場。科学分隊の焰影苇草（エンエイイグサ）でスタートしたものの、緊張のあまり運もMaybeで、ローグライクの基礎力不足が原因で、第三層ボスの「利刃所指（刃の指す先）」で戦闘不能に。最終スコアは325点だったって話？

= Special Formatting Test

== Code Block

```Rust
pub fn spawn_model(
    mut commands:   Commands,
    mut meshes:     ResMut<Assets<Mesh>>,
    mut materials:  ResMut<Assets<MmdMaterial>>,
    mut ibp_assets: ResMut<Assets<SkinnedMeshInverseBindposes>>,
    asset_server:   Res<AssetServer>,
) {
    let extra = vec!["other tex".to_string(), "spa".to_string()];

    spawn_pmx_model(
        &mut commands, &mut meshes, &mut materials, &mut ibp_assets, &asset_server,
        include_bytes!("../../assets/perlica/perlica.pmx"),
        &MmdModelMetadata {
            display_name:               "Perlica".to_string(),
            pmx_name:                   String::new(),
            file_path:                  "perlica/perlica.pmx".to_string(),
            other_texture_paths:        extra.clone(),
            material_mapping_toml_path: Some("perlica/material.toml".to_string()),
        },
        Transform::from_xyz(-16.0, 0.0, 0.0),
    );
}
```

== Other Formats

- *Strong emphasis*
- _Emphasis_
- `Raw text`
- https://typst.app
- $ E = m c^2 $

=== Nested Lists

- First level
  - Second level
    - Third level

1. Ordered item
2. Another ordered item

=== Deep Heading

==== Level Four Heading

Level-four headings stay visually consistent with the levels above.

== Tables and Figures

#figure(
  table(
    columns: (auto, 1fr, auto),
    align: (left, left, right),
    table.header[Depth][Region][$D$],
    [0], [Realspace], [$0.0$],
    [1], [Ætherside], [$1.0$],
    [-1], [Originium Internalization Universe], [$-1.0$],
  ),
  caption: [Depth values and their corresponding regions.],
)

== Block Quote

#quote(block: true, attribution: [庄方宜])[
  青霄碧落，乌云尽扫
]

= Known Issue & Acknowledgements

== Known Issue

- CJK typefaces ship no italic face, so `_emphasis_` renders as *bold* for CJK
  runs while Latin text keeps real italics.
- Layout is tuned for A4; other `paper` sizes are accepted but not rescaled.

== Acknowledgements

- #link("https://endfield.hypergryph.com/", "Arknights: Endfield by Hypergryph"),
- #link("https://github.com/leostudiooo/typst-touying-theme-endfield.git", "Endfield Style Touying Theme for Typst by Leostudiooo")
